client/certificates.go
=> fix for issue #105

pkg/engine/overlay.go, pkg/engine/overlay_test.go
* I have corrected notes from previous Mutation Overlay PR
=> Refactoring

examples/Validate/check_cpu_memory.yaml, examples/Validate/check_hostpath.yaml, examples/Validate/check_image_version.yaml, examples/Validate/check_nodeport.yaml, examples/Validate/check_not_root.yaml, examples/Validate/check_probe_exists.yaml, examples/Validate/check_probe_intervals.yaml, examples/Validate/check_whitelist_registries.yaml, examples/mutate/overlay/policy_set_imagePullPolicy.yaml, test/ConfigMap/policy-CM.yaml, test/Job/job.yaml, test/Job/policy-job.yaml, test/PodTemplate/PodTemplate.yaml, test/PodTemplate/policy-PodTemplate.yaml
examples are updated and for now results are folloving:
**Validation**
check_cpu_memory.yaml	- added workaround and works
check_hostpath.yaml	- workaround and works
check_image_version.yaml - fixed and works
check_nodeport.yaml	- added workaround and works
check_not_root.yaml - bool issue (https://github.com/nirmata/kyverno/issues/102)
check_probe_exists.yaml - fixed, added workaround and works
check_probe_intervals.yaml - fixed and works
check_whitelist_registries.yaml- added workaround and works
**Mutation:
Patches**
policy-endpoints. yaml - ok
**Overlay**
policy_set_imagePullPolicy.yaml - added workaround and works
**CLI**
policy-deployment.yaml - should work
**Generate**
policy_generate.yaml -  ok
=> added workarounds to make examples valid

documentation/installation.md
@patelrit - I updated the docs, based on your feedback. Let us know if this change helps clarifies what needs to be done.
@shivdudhani - please review and test.
=> Update install docs

README.md, examples/validate/check_registries.yaml
- add link to examples from docs section
=> - rename example - add link to examples from docs section

.travis.yml
- initial support for Travis CI
=> create ci file

pkg/engine/validation.go, pkg/engine/validation_test.go
=> Fixed bug #117

pkg/engine/mutation.go, pkg/engine/overlay.go, pkg/engine/overlay_test.go, pkg/engine/patches.go, pkg/engine/patches_test.go, pkg/engine/validation.go, pkg/engine/validation_test.go, pkg/kyverno/apply/apply.go, pkg/result/result.go, pkg/webhooks/server.go
Fixed bugs detected while devtesting
=> 0.3 bugfix #1

.travis.yml, Makefile
- Add a step to run unit tests after a successful build for #5.
- makefile target to view code-coverage report
=> 152 automate testing

definitions/install_debug.yaml, documentation/installation.md, init.go, main.go, pkg/config/config.go, pkg/webhooks/registration.go, scripts/deploy-controller-debug.sh, scripts/generate-self-signed-cert-and-k8secrets-debug.sh
This PR implements:
- Allow user to run Kyverno in debug mode
- Update installation doc to run in debug mode
=> 125 debug mode

pkg/engine/overlay.go, pkg/engine/overlay_test.go, pkg/engine/pattern.go, pkg/engine/utils.go, pkg/engine/validation.go
Simplified code for overlays and patterns, added comments
=> Prepare to 50 and 115

pkg/dclient/certificates.go, pkg/dclient/client.go, pkg/violation/builder.go
Issue #177 
Expose dryRun option for the client 
- Create
- Update
- UpdateStatus
- Delete
** based on the order of PR merge #175 might require work on the unit tests**
=> support dryRun parameter in client api

pkg/controller/controller_test.go, pkg/dclient/client.go, pkg/dclient/client_test.go, pkg/dclient/utils.go, pkg/sharedinformer/utils.go
Unit test for
- client (dynamic client, typed client & policy client)
- controller ( create policy)
Additional components:
- provide mock client
=> Client test

pkg/controller/controller.go, pkg/dclient/certificates.go, pkg/dclient/client.go, pkg/event/controller.go, pkg/violation/builder.go
=> replace utilruntime.HandleError with glog.Error

.github/ISSUE_TEMPLATE/scenario-to-support.md
=> Update issue templates

pkg/kyverno/apply/apply.go
=> remove local scope of var

definitions/install.yaml, pkg/apis/policy/v1alpha1/types.go, pkg/engine/engine.go, pkg/engine/utils.go
=> Add namespace selector to filter on namespace

pkg/config/config.go, pkg/utils/util.go, pkg/utils/util_test.go, pkg/webhooks/registration.go, pkg/webhooks/server.go, pkg/webhooks/utils.go, scripts/deploy-controller-debug.sh, scripts/generate-self-signed-cert-and-k8secrets-debug.sh
=> Validate uniqueness of the rule name within the policy

pkg/annotations/annotations.go
fixes #228 
Change field name from error to messages are requested.
=> change annotations struct field name

definitions/install.yaml, pkg/webhooks/utils.go, pkg/webhooks/validation.go
=> change flag field

pkg/violation/builder.go
=> handle return

pkg/engine/engine.go, pkg/engine/utils.go
=> existing resources checks all namespace, instead of jst default it left blank

definitions/install.yaml, main.go, pkg/controller/cleanup.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/engine/engine.go, pkg/engine/utils.go, pkg/utils/util.go, pkg/webhooks/server.go
Modifying the current command line arg "filterKinds" to "filterResources"
Input will be [Kind, Namespace, Name]
Example
[Deployment, kyverno, kyverno]
[Events, *, *]
Wild cards need to be used and the format is comma-separated wrapped in square braces.
closes #234
=> Filter resources

definitions/install.yaml, pkg/utils/util.go
=> update arguments & cleanup print

definitions/install_custom_args.yaml, examples/policy_generate_networkPolicy.yaml, main.go, pkg/event/msgbuilder.go, pkg/gencontroller/generation.go, pkg/webhooks/registration.go, pkg/webhooks/report.go, test/generate-resource/generate.sh, test/generate-resource/main.go
- fix #258 
- add script to generate  benchmark manifest
- fix example/netwrokpolicy name
- fix #235
=> improve event text + fix #235

main.go, pkg/clientNew/listers/kyverno/v1alpha1/expansion_generated.go, pkg/engine/generation.go, pkg/namespace/controller.go, pkg/namespace/expansion.go, pkg/namespace/generation.go, pkg/policy/controller.go, pkg/webhooks/mutation.go, pkg/webhooks/registration.go
Fixes after initial testing for generation logic
=> Test redesign

definitions/install.yaml
revert some incorrect changes & add more checks
=> correct install.yaml

pkg/api/kyverno/v1alpha1/types.go, pkg/engine/overlay.go, pkg/namespace/generation.go, pkg/policy/apply.go, pkg/policy/controller.go, pkg/policy/status.go, pkg/webhooks/mutation.go, pkg/webhooks/validation.go
fixes #277
Sample output:
```
Status:
Rules:
Applied Count:                          48
Average Execution Time:                 89.157µs
Mutations Count:                        0
Rule Name:                              check-readinessProbe-exists
Violation Count:                        6
Applied Count:                          54
Average Execution Time:                 52.443µs
Mutations Count:                        0
Rule Name:                              check-livenessProbe-exists
Violation Count:                        0
Average Generation Rules Execution Time:  0s
Average Mutation Rules Execution Time:    192.478µs
Average Validation Rules Execution Time:  0s
Resources Blocked Count:                  0
Rules Applied Count:                      108
Violation Count: …
```
=> Rule stats

pkg/event/controller.go, pkg/policyviolation/helpers.go
=> ignore creation of event and PV if Name is not assigned.

documentation/writing-policies-validate.md, pkg/engine/anchor.go, pkg/engine/validation.go, pkg/engine/validation_test.go, test/scenarios/test/scenario_mutate_validate_qos.yaml, test/scenarios/test/scenario_validate_containerSecurityContext.yaml, test/scenarios/test/scenario_validate_healthChecks.yaml, test/scenarios/test/scenario_validate_imageRegistries.yaml, test/scenarios/test/scenario_validate_nonRootUser.yaml
- update message to show resource path of failure for validation
-  print custom message on failure 
- anyPattern to return on first success validation
-  update scenarios for test runner
fixes #339 
fixes #336 
fixes #276 
fixes #331
=> Update error message + anyPattern flow

pkg/namespace/controller.go, pkg/namespace/generation.go
Policies with generate rules are applied on policy creation, previously the rules were applied as per namespace controllers re-conciliation cycle.
fixes #355
=> process policy in namespaces

.travis.yml
Skip building travis CI jobs for documentation changes.
=> skip documentation changes

pkg/webhooks/annotations.go, pkg/webhooks/annotations_test.go, pkg/webhooks/mutation.go, pkg/webhooks/utils.go
=> fix 365 annotation_bug

pkg/api/kyverno/v1alpha1/utils.go, pkg/engine/anchor.go, pkg/engine/utils.go, pkg/engine/validation_test.go
=> Feature negation anchor

definitions/install.yaml, definitions/install_custom_args.yaml
=> update apiVersion for deployment

samples/DisallowHostFS.md, samples/README.md, samples/best_practices/disallow_host_filesystem.yaml
=> 409 update hostpath policy

pkg/engine/generation.go, pkg/engine/pattern.go, pkg/utils/json.go, pkg/webhooks/validation.go, samples/best_practices/require_namespace_quota.yaml, samples/more/policy_validate_user_group_fsgroup_id.yaml
=> Revert "use validatepattern in generate rule to check for subset existance"

test/scenarios/samples/best_practices/scenario_validate_disallow_docker_sock_mount.yaml
- Add a period to message string scenario file.
More explanation in #437
=> add period to message in scenario

pkg/checker/checker.go, pkg/checker/status.go, pkg/webhooks/server.go
Generate Event on kyverno deployment after webhook active status update.
fixes #460
=> create event on webhook status update

pkg/policyviolation/generator.go, pkg/policyviolation/namespacedpv.go
- return detailed error message
- set pv name with old pv when updates the pv, otherwise it throws  error `resource name may not be empty`
=> enhance error message, set pv name when updates

definitions/install.yaml, pkg/engine/mutation.go, pkg/engine/overlay.go, pkg/policyviolation/controller.go, pkg/policyviolation/generator.go, pkg/policyviolation/namespacedpv.go, pkg/policyviolation/namespacepvcontroller.go, pkg/webhooks/annotations.go, pkg/webhooks/mutation.go, test/scenarios/samples/best_practices/add_safe_to_evict.yaml, test/scenarios/samples/best_practices/add_safe_to_evict2.yaml
=> fix annotation patch in mutate rule

pkg/namespace/controller.go, pkg/policystore/policystore_test.go
Filter namespace resource too, if specified to filter.
fixes #485
=> filter namespaces

pkg/policy/cleanup.go
=> fix pv cleanup #496

pkg/policyviolation/generator.go, pkg/policyviolation/namespacedpv.go
- Update policy Name format
fixes #495
=> policy violation name format update

pkg/event/msgbuilder.go, pkg/kyverno/apply/apply.go, pkg/namespace/report.go, pkg/policy/report.go, pkg/webhooks/report.go, pkg/webhooks/validation.go
- Update event reason.
- reformat the code
=> update event message

pkg/policyviolation/generator.go, pkg/policyviolation/namespacedpv.go
=> explicitly set resource version of policy violation when update

definitions/install.yaml, definitions/install_debug.yaml
- Add printer columns for policy violations
- some suggested shortNames for CRDs(open for improvements)
fixes #474
=> 474 feature

pkg/engine/pattern.go, pkg/engine/validation.go, pkg/engine/validation_test.go, pkg/testrunner/scenario.go, test/scenarios/other/scenario_validate_disallow_default_serviceaccount.yaml, test/scenarios/other/scenario_validate_selinux_context.yaml, test/scenarios/samples/best_practices/disallow_docker_sock_mount.yaml, test/scenarios/samples/best_practices/scenario_validate_disallow_helm_tiller.yaml
Removes the newline and updates the scenario files.
fixes #514
=> remove newline from engine response strings

cmd/kyverno/main.go, pkg/utils/util.go
=> 590 move helper to pkg/utils

pkg/engine/mutate/overlay.go, pkg/engine/mutate/overlayCondition.go, pkg/engine/mutate/overlayCondition_test.go, pkg/engine/mutate/overlayError.go, pkg/engine/mutate/overlay_test.go, pkg/engine/mutate/patches.go, pkg/engine/mutate/patches_test.go, pkg/engine/mutate/utils.go, pkg/engine/mutate/utils_test.go, pkg/engine/mutation.go, pkg/engine/mutation_test.go, pkg/engine/policy/validate.go, pkg/engine/policyContext.go, pkg/engine/utils.go, pkg/engine/utils/utils.go, pkg/engine/utils/utils_test.go, pkg/engine/utils_test.go, pkg/engine/validation.go, pkg/engine/validation_test.go, pkg/webhooks/common.go, pkg/webhooks/generation.go, pkg/webhooks/mutation.go, pkg/webhooks/policymutation_test.go
This PR refactor the engine mutation, move it to the sub-package. Would be good to get merged so the later features can pick up the changes.
=> move mutation to subpackage pkg/engine/mutate

pkg/webhooks/common.go
=> pass in original resource to validation if patches from mutation is nil

documentation/writing-policies.md, pkg/webhooks/generation.go, test/policy/generate/variable.yaml
fixes #605 
Add missing documentation for `preconditions`
=> fix the bugs and add pre-condition checks

Makefile
=> add missing var for PACKAGE

pkg/generate/generate.go
=> substitute variable values on a copy of policy rule

samples/best_practices/disallow_default_namespace.yaml
Remove `pod-policies.kyverno.io/autogen-controllers: none`
=> Remove autogen annotation

pkg/engine/policy/validate.go
=> Error message for spec.background

definitions/install.yaml, definitions/install_debug.yaml
=> add type in openapi schema

definitions/install.yaml, documentation/installation.md
Use Custom ClusterRole for kyverno.
=> kyverno ClusterRole

pkg/event/msgbuilder.go, pkg/webhooks/mutation.go, pkg/webhooks/report.go, pkg/webhooks/validation.go
=> refactor events

samples/DisallowDefaultNamespace.md, samples/best_practices/disallow_default_namespace.yaml
=> Add rules to disallow default namespace for pod controllers.

pkg/engine/validation.go, pkg/engine/validation_test.go, pkg/webhooks/common.go
=> #725 - anyPattern error improvements

documentation/kyverno-cli.md
I created an AUR package for the `kyverno` cli, therefore I wanted to publish its existence for other fellow arch users
=> Add info about the kyverno AUR package

README.md, documentation/writing-policies-match-exclude.md, documentation/writing-policies.md
=> 1.1.5 doc updates

definitions/install.yaml, definitions/install_debug.yaml
=> #755 - Resource field should be optional for exclude

.travis.yml
Fixed #759 
Signed-off-by: Yuvraj <yuvraj.yad001@gmail.com>
=> Caching added to travis ci

definitions/install.yaml
=> update clusterrole kyverno:webhook to approve csr for 1.18 cluster

pkg/openapi/crdSync.go
=> #783 - Fixing crd sync panic

pkg/dclient/client.go, pkg/openapi/crdSync.go
=> #783 - CRD sync panics on kubernetes versions 1.16 and below

pkg/kyverno/apply/command.go, pkg/policy/generate/fake.go
=> #787 - CLI panics for policies with variables

definitions/install.yaml, definitions/install_debug.yaml
=> #789 - Generate definition missing namespace field

pkg/engine/mutation.go
=> #775 - Removing unneeded annotations

samples/RequirePodRequestsLimits.md, samples/best_practices/require_pod_requests_limits.yaml, test/scenarios/samples/best_practices/require_pod_requests_limits.yaml
=> remove cpu limit in BP require_pod_requests_limits.yaml

definitions/install.yaml, definitions/install_debug.yaml, pkg/api/kyverno/v1/types.go, pkg/generate/policyStatus_test.go, pkg/policystatus/main.go, pkg/policystatus/status_test.go, pkg/policyviolation/policyStatus_test.go
=> #808 - Policy status is not being updated

documentation/testing-policies.md
Updated instructions with current locations of `policy-CM.yaml` and `CM.yaml`.
=> Documentation update

pkg/generate/generate.go
Fix #802:
- set generate.data.kind from generate.kind if not present
=> 802 set kind in generate

Makefile, definitions/install.yaml, pkg/webhooks/annotations.go, pkg/webhooks/mutation.go, pkg/webhooks/server.go, pkg/webhooks/validation.go
This PR fixes #811, also suppress unnecessary logs.
=> 811 - fix duplicate pv create on both pod and pod-controller

Makefile, cmd/kyverno/main.go, definitions/install.yaml, go.mod, go.sum, pkg/checker/checker.go, pkg/checker/status.go, pkg/constant/constant.go, pkg/dclient/client.go, pkg/dclient/utils.go, pkg/event/controller.go, pkg/generate/cleanup/controller.go, pkg/generate/controller.go, pkg/generate/generate.go, pkg/openapi/crdSync.go, pkg/policy/apply.go, pkg/policy/controller.go, pkg/policy/existing.go, pkg/policyviolation/generator.go, pkg/webhookconfig/checker.go, pkg/webhookconfig/registration.go, pkg/webhookconfig/resource.go, pkg/webhookconfig/rwebhookregister.go, pkg/webhooks/annotations.go, pkg/webhooks/generate/generate.go, pkg/webhooks/mutation.go, pkg/webhooks/policymutation.go, pkg/webhooks/policymutation_test.go, pkg/webhooks/server.go, pkg/webhooks/validation.go
This PR fixes #838, by parsing the newer version of CRD to a difference JSON object.
Changes:
- increase CRD sync period to 10 minutes
- increase background sync period to 5 minutes
- fix "failed to list resources" for Namespace
- suppress logs
=> 838 - fix parse CRD error: added CRD 1.16+ spec

documentation/writing-policies-autogen.md
=> fixed a documentation typo

charts/kyverno/crds/crds.yaml, charts/kyverno/templates/clusterrolebinding.yaml, definitions/install.yaml, pkg/engine/mutation.go, pkg/engine/validation.go, pkg/engine/validation_test.go, pkg/policy/existing.go, pkg/webhooks/mutation.go, pkg/webhooks/server.go, test/scenarios/other/scenario_validate_disallow_default_serviceaccount.yaml, test/scenarios/other/scenario_validate_selinux_context.yaml, test/scenarios/samples/best_practices/disallow_docker_sock_mount.yaml, test/scenarios/samples/best_practices/scenario_validate_disallow_helm_tiller.yaml
- fix #869 
- add clusterrole "admin", "edit" and "view" to kyverno serviceaccount #837
- fix variable scope
- add debug log
=> 869 - auto-gen annotation is not inserted connrectly

charts/kyverno/values.yaml, definitions/install.yaml
| Status  | Type  | Env Vars Change |  Issue |
| :---: | :---: | :---: | :--: |
| Ready | Feature | No |  #857   |
add CPU and memory resource requests, and a memory limit, for Kyverno defination and kyverno chart.
=> Added cpu & memory resource requests and limits

charts/kyverno/values.yaml, definitions/install.yaml, pkg/config/config.go, pkg/webhooks/server.go
| Status  | Type  | Env Vars Change |  Issue |
| :---: | :---: | :---: | :--: |
|  Ready | Feature | No |  #856   |
Add  readiness and liveness prob. For Kyverno defination and kyverno chart.
=> Added readiness and liveness prob 

README.md
=> Note added for kubernetes version in README

go.mod, go.sum, pkg/checker/status.go, pkg/engine/mutation.go, pkg/openapi/crdSync.go, pkg/openapi/validation.go, pkg/policyviolation/clusterpv.go, pkg/policyviolation/common.go, pkg/policyviolation/namespacedpv.go, pkg/webhooks/mutation.go, pkg/webhooks/server.go
=> bug fixes - #894, #892, #891

cmd/kyverno/main.go, definitions/install.yaml
- Enable profiling by the flag, added [dev wiki](https://github.com/nirmata/kyverno/wiki/Profiling-Kyverno-on-Kubernetes)
- Update image tag
=> enable profiling

pkg/engine/mutation.go, pkg/policy/apply.go, pkg/policyviolation/generator.go, pkg/webhooks/validation.go
Fix issue: auto-gen annotation is reported as a violation.
```
rules:
- message: mutation json patches not found at resource path /spec/template/metadata/annotations/pod-policies.kyverno.io~1autogen-applied
name: podControllerAnnotation
type: Mutation
```
=> bug fix auto-gen annotation reported as violation

charts/kyverno/README.md, documentation/installation.md
Fixed : #842 
Added documentation for helm repository
=> helm docs added for helm repository

.github/workflows/helm-release.yaml, .github/workflows/release.yaml, .goreleaser.yml
Fixed helm release and docker release ci issues
works.
=> Hotfix: fix ci pipeline

.github/workflows/release.yaml, .goreleaser.yml
Removed all docker build changes from github action 
works.
=> revert docker build changes

definitions/install.yaml
=> tag v1.1.6-rc5

definitions/install.yaml
=> #837 - add aggregated view clusterroles for default k8s roles (view, edit and admin)

README.md
=> Add a quick start

documentation/kyverno-cli.md, pkg/kyverno/apply/command.go, pkg/kyverno/common/common.go, pkg/kyverno/validate/command.go
https://github.com/nirmata/kyverno/issues/915
> /kind bug
Correcting the Exit Codes of the CLI which will be useful for automation scripts.
=> CLI error handling using different exit codes. 

pkg/kyverno/apply/command.go, pkg/kyverno/common/common.go
Closes https://github.com/nirmata/kyverno/issues/934
/kind feature
Updated the sanitized error to provide sanitized error and raw error.
works.
=> updated sanitized error

README.md, charts/kyverno/crds/crds.yaml, definitions/crds/crds.yaml, definitions/install.yaml, definitions/install_debug.yaml, documentation/writing-policies-generate.md, pkg/api/kyverno/v1/types.go, pkg/generate/generate.go, pkg/webhooks/generate/generate.go, pkg/webhooks/generation.go, pkg/webhooks/server.go
fixes #560 
/kind feature
This feature include a field `synchronize` in generate CRD for keeping resources synchhronized 
if value is `true` then resource will be synchhronized. It is a optional field 
````yaml
metadata:
name: basic-policy
spec:
rules:
- name: "Generate ConfigMap"
match:
resources:
kinds: 
- Namespace
generate:
kind: ConfigMap # Kind of resource 
name: default-config # Name of the new Resource
namespace: "{{request.object.metadata.name}}" # namespace that triggers this rule
synchronize : true
clone:
name: config-template
- name: "Generate Secret (insecure)"
match:
resources:
kinds: 
- Namespace
generate:
kind: Secret
name: mongo-creds
synchronize : true
namespace: …
```
=> Synchronize data for generated resources

pkg/engine/mutation.go, pkg/engine/utils.go, pkg/engine/validation.go, pkg/engine/variables/common.go, pkg/webhooks/annotations.go, pkg/webhooks/server.go
=> Ignore auto-gen annotation on Pod when processing DENY rule

documentation/installation.md, pkg/policy/existing.go, pkg/policy/utils.go, pkg/policyviolation/namespacedpv.go
=> Background mode only apply to running pods

pkg/api/kyverno/v1/utils.go, pkg/engine/mutation.go, pkg/engine/validation.go, pkg/policy/controller.go, pkg/policy/existing.go
#939 
> /kind bug
See comment in #939.
works.
=> Avoid generating violation on pre-exist pod

pkg/engine/mutation.go, pkg/webhooks/mutation.go
Fixes #948 
> /kind bug
works.
=> Skip inserting auto-gen annotation into podController on UPDATE admission request

documentation/writing-policies-autogen.md
Update auto-gen document - not support DENY and Generate policy.
works.
=> Update auto-gen doc

samples/DisallowNewCapabilities.md, samples/best_practices/disallow_new_capabilities.yaml
Fixes #928
/kind bug
Update docs
works.
- [x ] I have added or changed [the documentation](documentation/).
=> Update docs for add capabilities

go.sum, pkg/engine/mutation.go, pkg/engine/response/response.go, pkg/engine/validation.go, pkg/engine/validation_test.go, pkg/event/controller.go, pkg/event/util.go, pkg/kyverno/apply/command.go, pkg/policy/apply.go, pkg/policy/cleanup.go, pkg/policy/controller.go, pkg/policy/namespacedpv.go, pkg/policy/report.go, pkg/policy/webhookregistration.go, pkg/policyviolation/builder.go, pkg/webhookconfig/registration.go, pkg/webhookconfig/resource.go, pkg/webhookconfig/rwebhookregister.go, pkg/webhooks/annotations.go, pkg/webhooks/common.go, pkg/webhooks/mutation.go, pkg/webhooks/report.go, pkg/webhooks/validation.go
Fixes #945 and #946 
/kind bug
- Cleanup logging 
- Change event generation retry to be less aggressive
=> update logging, naming, and event retry

documentation/installation.md
Updated readme - for installing kyverno with dynamic namespace 
Related to #841
=> Updated namespace related readme

cmd/kyverno/main.go, pkg/config/dynamicconfig.go, pkg/policycache/cache.go, pkg/policycache/cache_test.go, pkg/policycache/informer.go, pkg/policycache/type.go, pkg/webhooks/common.go, pkg/webhooks/generation.go, pkg/webhooks/mutation.go, pkg/webhooks/server.go, pkg/webhooks/validation.go
Fixes #956 
/kind feature
See https://github.com/nirmata/kyverno/issues/956#issuecomment-651587289.
=> Add policy cache based on policyType

README.md, documentation/writing-policies-autogen.md, documentation/writing-policies-generate.md, documentation/writing-policies-mutate.md, documentation/writing-policies-validate.md
update docs and add community meeting section
=> update README.md - community and restructure

pkg/engine/validate/validate.go
=> Resolve Kyverno panic when sync the generate request

pkg/userinfo/roleRef.go, pkg/webhooks/server.go
=> Error message update

pkg/kyverno/apply/command.go
#872
mutated policy will be printed in yaml format
=> print mutated policy as yaml

pkg/generate/generate.go
This PR is submitted by @evalsocket. It fixes the deletion of synchronized generated resource.
works.
=> bugfix - delete synchronized resources

.krew.yaml
=> krew yaml fixes

pkg/config/config.go
=> fixed deployment name in config

pkg/generate/generate.go, pkg/webhooks/server.go
=> policy name added in labels

documentation/writing-policies-match-exclude.md
=> Update selecting resource doc

.gitignore, pkg/event/builder_test.go, pkg/event/controller.go, pkg/event/msgbuilder.go, pkg/event/reason.go, pkg/generate/generate.go, pkg/generate/report.go, pkg/policy/report.go, pkg/webhooks/generation.go, pkg/webhooks/report.go
Fixes #834, #1003.
See https://github.com/nirmata/kyverno/issues/834#issuecomment-660326022.
works.
=> Events fix

documentation/kyverno-cli.md, pkg/engine/mutation.go, pkg/kyverno/apply/command.go
closes https://github.com/nirmata/kyverno/issues/879
Now in Kyverno CLI, we can save the mutated resource in provided file or folder.
works.
=> Feature/CLI saving mutate results 

pkg/kyverno/apply/command.go
https://github.com/nirmata/kyverno/issues/879
Removed mutated policy from apply.
works.
=> removed mutated policy

pkg/generate/cleanup/controller.go
=> [BUG] Generate request is not cleaned up after delete the generate policy

.github/workflows/build.yaml, .github/workflows/release.yaml, Makefile, scripts/ci.sh
https://github.com/evalsocket/kyverno/runs/971378870?check_suite_focus=true
works.
=> Added e2e test in release

Makefile, README.md, definitions/kustomization.yaml, definitions/release/install.yaml
=> 1040 automate release

documentation/installation.md
=> Update the doc on how excluded userInfo flags 

charts/kyverno/values.yaml, definitions/install.yaml, definitions/manifest/deployment.yaml, pkg/config/dynamicconfig.go
=> default exclude group role added 

Makefile, cmd/kyverno/main.go, definitions/install.yaml, definitions/manifest/deployment.yaml, pkg/config/dynamicconfig.go, pkg/engine/generation.go, pkg/engine/mutation.go, pkg/engine/utils.go, pkg/engine/utils_test.go, pkg/engine/validation.go, pkg/generate/cleanup/controller.go, pkg/generate/controller.go, pkg/generate/generate.go, pkg/policy/apply.go, pkg/policy/existing.go, pkg/policystatus/main.go, pkg/testrunner/scenario.go, pkg/userinfo/roleRef.go, pkg/webhooks/generation.go, pkg/webhooks/mutation.go, pkg/webhooks/policyvalidation.go, pkg/webhooks/server.go, pkg/webhooks/validate_audit.go, pkg/webhooks/validation.go
=> Add go fmt

documentation/writing-policies-mutate.md, pkg/webhooks/mutation.go
=> update mutation jsonPatch doc

definitions/install.yaml, pkg/webhooks/server.go
The PR adds improves the mutation webhook logic. 
Closes #1027.
works.
=> Improvements in webhook

charts/kyverno/crds/crds.yaml, definitions/crds/crds.yaml, definitions/install.yaml, definitions/install_debug.yaml, documentation/writing-policies-match-exclude.md, go.sum, pkg/api/kyverno/v1/types.go, pkg/engine/utils.go, pkg/policymutation/policymutation.go
closes https://github.com/nirmata/kyverno/issues/1022
user can match based on metadata annotations
works.
=> Supporting annotations in match/exclude

charts/kyverno/templates/configmap.yaml, charts/kyverno/values.yaml, pkg/config/dynamicconfig.go
=> [BUG] filterK8Resources is not correctly configured using ConfigMap 

samples/DisallowNewCapabilities.md, samples/best_practices/disallow_new_capabilities.yaml
=> fix policy

pkg/kyverno/common/common.go
=> return early in CLI if generated patches from policy mutation is nil

pkg/kyverno/common/common.go, pkg/policy/validate.go
closes https://github.com/nirmata/kyverno/issues/826
Added check for the variables passed by the user in policies. 
valid variables:
- request.*
- serviceAccountName
- serviceAccountNamespace
works.
=> Allowing only few variables in the policies

charts/kyverno/crds/crds.yaml, charts/kyverno/templates/clusterrole.yaml, definitions/install.yaml, definitions/install_debug.yaml, definitions/k8s-resource/rbac.yaml, definitions/release/install.yaml
=> add watch permission of namespace policy to clusterrole kyverno:customresources

.github/workflows/release.yaml, cmd/kyverno/main.go, pkg/event/controller.go
=> Events take several minutes to show on the resource 

documentation/writing-policies-validate.md, go.sum, pkg/engine/anchor/anchor.go, pkg/engine/anchor/common/common.go, pkg/engine/anchor/common/common_test.go, pkg/engine/common/anchorKey.go, pkg/engine/mutate/overlay.go, pkg/engine/mutate/overlayCondition.go, pkg/engine/mutate/utils.go, pkg/engine/utils/utils.go, pkg/engine/validate/utils.go, pkg/engine/validate/validate.go, pkg/engine/validate/validate_test.go, pkg/policy/common/common.go, pkg/policy/generate/validate.go, pkg/policy/mutate/validate.go, pkg/policy/validate.go, pkg/policy/validate/validate.go
Fixes [https://github.com/nirmata/kyverno/issues/715](https://github.com/nirmata/kyverno/issues/715)
/kind bug
Resolved conditional anchor issue and added validation for labels.
Labels support only string values.
works.
=> resolved conditional anchor issue and added validation to pattern labels

documentation/writing-policies-generate.md, pkg/engine/generation.go, pkg/generate/cleanup/controller.go, pkg/generate/controller.go, pkg/generate/generate.go, pkg/webhooks/generate/generate.go, pkg/webhooks/generation.go, samples/AddDefaultNetworkPolicy.md, samples/AddNamespaceQuotas.md, samples/best_practices/add_network_policy.yaml, samples/best_practices/add_ns_quota.yaml
=> Generate policy does not work on namespace update

cmd/kyverno/main.go, documentation/kyverno-cli.md, go.mod, pkg/auth/auth.go, pkg/checker/checker.go, pkg/kyverno/common/common.go, pkg/kyverno/validate/command.go, pkg/openapi/crdSync.go, pkg/utils/util.go, pkg/webhooks/server.go
closes #794 
closes #795 
Supporting policy validation against CRD in CLI
works.
=> Supporting CRD validation in CLI

pkg/generate/cleanup/controller.go, pkg/generate/controller.go, pkg/generate/generate.go, pkg/policy/validate.go, pkg/webhooks/generation.go
[https://github.com/nirmata/kyverno/issues/793](https://github.com/nirmata/kyverno/issues/793)
/kind bug
added validation of invalid fields in policy
works.
=> added invalid field validation for policy

pkg/openapi/crdSync.go
https://github.com/nirmata/kyverno/issues/1100
> /kind bug
Fixed return for openapiV3
works.
=> fixed return

pkg/policymutation/cronjob.go, pkg/policymutation/policymutation.go
fixes #1054 
/kind bug
added autogen for patch strategic merge
works.
=> added autogen for patch strategic merge

pkg/engine/mutate/strategicPreprocessing.go, pkg/engine/mutate/strategicPreprocessing_test.go
fixes [https://github.com/nirmata/kyverno/issues/1113](https://github.com/nirmata/kyverno/issues/1113)
/kind bug
works.
=> fixed additional anchor bug in patch strategic merge

pkg/policystatus/main.go, pkg/webhooks/policymutation.go
=> skip policy mutation on status update

pkg/policymutation/policymutation.go, pkg/policymutation/policymutation_test.go, samples/DisallowBindMounts.md, samples/best_practices/disallow_bind_mounts.yaml
=> Bugfix policymutation

pkg/kyverno/apply/command.go
closes https://github.com/nirmata/kyverno/issues/1122 and https://github.com/nirmata/kyverno/issues/1121
> /kind bug
https://github.com/nirmata/kyverno/issues/1121 - now the mutated resource is getting saved in given file or folder
https://github.com/nirmata/kyverno/issues/1122 - fixed variable substitution (applying variable using a file)
works.
=> Fixes CLI bug - mutate resource and variable substitution

documentation/writing-policies-preconditions.md
=> update operator doc

pkg/engine/mutate/strategicPreprocessing.go, pkg/engine/mutate/strategicPreprocessing_test.go, pkg/policy/validate.go
fixes [https://github.com/nirmata/kyverno/issues/1113](https://github.com/nirmata/kyverno/issues/1113)
fixes [https://github.com/nirmata/kyverno/issues/1135](https://github.com/nirmata/kyverno/issues/1135)
/kind bug
works.
=> fixed policy validation and patch strategic merge bug

go.mod, pkg/generate/generate.go
=> Generate policy with backword compatibility

pkg/api/kyverno/v1/types.go, pkg/engine/mutate/mutation.go, pkg/engine/mutation_test.go, pkg/policymutation/policymutation.go, pkg/webhooks/policymutation_test.go, samples/AddSafeToEvict.md, samples/best_practices/add_safe_to_evict.yaml, test/output/output_mutate_pod_spec.yaml, test/output/output_mutate_validate_qos.yaml, test/resources/resource_mutate_pod_spec.yaml, test/resources/resource_mutate_validate_qos.yaml, test/scenarios/other/scenario_mutate_pod_spec.yaml, test/scenarios/other/scenario_mutate_validate_qos.yaml, test/scenarios/samples/best_practices/add_safe_to_evict.yaml, test/scenarios/samples/best_practices/add_safe_to_evict2.yaml
fixes [https://github.com/nirmata/kyverno/issues/1025](https://github.com/nirmata/kyverno/issues/1025)
fixes [https://github.com/nirmata/kyverno/issues/1128](https://github.com/nirmata/kyverno/issues/1128)
/kind feature
/kind bug
added conversion of overlay to patch strategic merge
modified the unittest files to comply with the conversion
works.
=> added conversion of overlay to patch strategic merge

README.md
=> Add video review

README.md
- reorder links
- add Coffee and Cloud Native video
- remove Go report card (temporary) as the site is down
=> add links in chronological order (latest first)

charts/kyverno/values.yaml
=> fixes #1152

pkg/kyverno/apply/command.go
=> remove mutation message when no rules are applied

pkg/kyverno/validate/command.go
Closes https://github.com/nirmata/kyverno/issues/1120
> /kind bug
Fixed the current yaml output format for validate in CLI
works.
=> fixed yaml package for CLI validate

documentation/installation.md
=> update installation guides

pkg/policy/validate.go
closes https://github.com/nirmata/kyverno/issues/1160
> /kind bug
fixed selector under exclude 
works.
=> added condition for exclude selector

.krew.yaml, CONTRIBUTING.md, Makefile, README.md, charts/kyverno/Chart.yaml, documentation/kyverno-cli.md, pkg/policymutation/policymutation_test.go, pkg/testrunner/utils.go, samples/README.md, samples/RequirePodProbes.md, samples/best_practices/require_probes.yaml
Fixes #1140, add auto-gen annotation to require-pod-probes.
=> 1140 update best practice require-pod-probes

pkg/kyverno/common/common.go, pkg/kyverno/validate/command.go
closes https://github.com/kyverno/kyverno/issues/1134
removed log statements from CLI
works.
=> cleanup cli output

.github/workflows/build.yaml, .krew.yaml, CONTRIBUTING.md, Makefile, README.md, charts/kyverno/Chart.yaml, documentation/kyverno-cli.md, pkg/policymutation/policymutation_test.go, pkg/testrunner/utils.go, samples/README.md, samples/RequirePodProbes.md, samples/best_practices/require_probes.yaml
=> Publish test image 

index.yaml
=> Migrate helm chart from nirmata to kyverno

README.md, documentation/installation.md
=> Fix documentation for helm

pkg/kyverno/apply/command.go
closes https://github.com/kyverno/kyverno/issues/1194
> /kind bug
Fixed panic while applying policy on cluster 
works.
=> Fixed panic while applying policy on cluster 

charts/kyverno/templates/deployment.yaml, definitions/install.yaml, definitions/install_debug.yaml, definitions/k8s-resource/rbac.yaml, definitions/manifest/deployment.yaml, definitions/release/install.yaml, pkg/engine/validate/common.go, pkg/engine/validate/pattern.go, pkg/webhooks/server.go, scripts/verify-deployment.sh
Fixes https://github.com/kyverno/kyverno/issues/1207.
/kind bug
Updated YAMLs to add a PodSecurityContext
- [ x] I have added tests that prove my fix is effective or that my feature
works.
- [ x] I have added or changed [the documentation](documentation/).
=> 1207 add security context

cmd/initContainer/main.go, pkg/utils/util.go, pkg/utils/util_test.go
#1226 
/kind bug
Fix version regex  to allow text after patch
- [ x] I have added tests that prove my fix is effective or that my feature
works.
=> allow text after patch versions

samples/AddDefaultNetworkPolicy.md, samples/AddNamespaceQuotas.md, samples/AddSafeToEvict.md, samples/CheckUserGroup.md, samples/DisallowBindMounts.md, samples/DisallowDefaultNamespace.md, samples/DisallowDockerSockMount.md, samples/DisallowHelmTiller.md, samples/DisallowHostNetworkPort.md, samples/DisallowHostPIDIPC.md, samples/DisallowLatestTag.md, samples/DisallowNewCapabilities.md, samples/DisallowPrivilegedContainers.md, samples/DisallowRootUser.md, samples/DisallowSysctls.md, samples/RequirePodProbes.md, samples/RequirePodRequestsLimits.md, samples/RequireReadOnlyRootFS.md, samples/RestrictAutomountSAToken.md, samples/RestrictImageRegistries.md, samples/RestrictIngressClasses.md, samples/RestrictNodePort.md, samples/best_practices/add_network_policy.yaml, samples/best_practices/add_ns_quota.yaml
=> manifest fixes; typos; linting

OWNERS.md
Add OWNERS.md file for CNCF sandbox submission
works.
=> add owners

OWNERS.md
=> add newline

pkg/engine/generation.go, pkg/webhooks/mutation.go
closes https://github.com/kyverno/kyverno/issues/954
To suppress the error logs for crd and validation error.
works.
=> Supress Error Logs

CONTRIBUTING.md, samples/CreatePodAntiAffinity.md, samples/README.md, samples/RequireCertainLabels.md, samples/RequireLabels.md, samples/RequirePodProbes.md, samples/RestrictImageRegistries.md, samples/RestrictLoadBalancer.md, samples/SpreadPodsAcrossTopology.md, samples/best_practices/require_labels.yaml, samples/more/create_pod_antiaffinity.yaml, samples/more/restrict_image_registries.yaml, samples/more/restrict_loadbalancer.yaml, samples/more/spread_pods_across_topology.yaml
Add two new samples; typos; enhancements to existing samples.
works.
=> new samples; updates

charts/kyverno/crds/crds.yaml, definitions/crds/kyverno.io_clusterpolicies.yaml, definitions/crds/kyverno.io_policies.yaml, definitions/install.yaml, definitions/install_debug.yaml, definitions/release/install.yaml, pkg/api/kyverno/v1/policy_types.go
Update CRD schema to be compatible with k8s 1.17.
=> Update CRDs 

.github/workflows/image.yaml, Makefile, charts/kyverno/README.md, charts/kyverno/values.yaml, definitions/install.yaml, definitions/kustomization.yaml, definitions/manifest/deployment.yaml, definitions/release/install.yaml, scripts/ci.sh, scripts/install-cli.sh
=> Revert "Migrate image to GitHub registry"

charts/kyverno/templates/clusterrole.yaml, charts/kyverno/templates/clusterrolebinding.yaml, definitions/install.yaml, definitions/install_debug.yaml, definitions/k8s-resource/clusterrolebindings.yaml, definitions/k8s-resource/clusterroles.yaml, definitions/k8s-resource/kustomization.yaml, pkg/generate/cleanup/cleanup.go
This PR syncs RBAC permissions in Helm charts, also removes duplicate clusterroles.
=> Update RBAC permissions

pkg/generate/cleanup/cleanup.go, pkg/generate/cleanup/controller.go, pkg/generate/controller.go, pkg/generate/generate.go, pkg/generate/resource.go, pkg/policyreport/builder.go
This PR restricts policy report name size, properly handles errors in generate controller.
=> Restrict report name size, fix errors in generate

go.mod, go.sum, pkg/engine/mutate/patchJson6902.go, pkg/engine/mutate/strategicMergePatch.go, pkg/engine/mutate/strategicPreprocessing.go, pkg/engine/mutate/strategicPreprocessing_test.go, pkg/generate/cleanup/controller.go, pkg/generate/controller.go, pkg/webhooks/mutation.go
=> Fix 1287 - failed to update annotation through mutate policy

pkg/policy/validate.go
closes https://github.com/kyverno/kyverno/issues/1301
> /kind bug
Added annotations check for policies with match and exclude.
works.
=> added annotations check in validation

samples/README.md, samples/RequireImagePullPolicyAlways.md, samples/RequireLatestImagesNotUseAlways.md, samples/misc/imagepullpolicy-always.yaml, samples/misc/latestimage-notalways.yaml
Add new sample policies around imagePullPolicy practices in new Miscellaneous section.
works.
=> new samples around image practices

pkg/openapi/validation.go
Fixes https://github.com/kyverno/kyverno/issues/1306
/kind bug
- [ x] I have tested with policies in bug report
=> add nil checks and refactor schema lookups

charts/kyverno/README.md
Fix helm repo link in README
works.
=> update helm repo link

pkg/generate/generate.go
Fix #1291 
/kind cleanup
Change log level from 4 to 2 
works.
=> Added logging for synchronize events for generate rules

.github/ISSUE_TEMPLATE/scenario-to-support.md
Update policy request template so users are aware of an existing samples library.
works.
=> update policy issue template

cmd/kyverno/main.go, pkg/engine/variables/operator/in.go, pkg/policy/apply.go, pkg/resourcecache/main.go
Fixes https://github.com/kyverno/kyverno/issues/1324.
Fixes https://github.com/kyverno/kyverno/issues/1325.
=> Fix panic when building ConfigMap cache

samples/README.md, samples/RequirePodsDropAll.md, samples/more/require_drop_all.yaml
=> add drop all policy

pkg/webhooks/server.go
closes https://github.com/kyverno/kyverno/issues/1294
> /kind bug
fixed trigging of generate rule in policy with a mutate and generate rule
works.
=> fixed triggring generate rule

charts/kyverno/crds/crds.yaml, definitions/crds/kyverno.io_clusterpolicies.yaml, definitions/crds/kyverno.io_policies.yaml, definitions/install.yaml, definitions/install_debug.yaml, pkg/api/kyverno/v1/policy_types.go, pkg/engine/utils.go, pkg/engine/utils_test.go, pkg/policymutation/policymutation.go, pkg/webhooks/common.go, pkg/webhooks/mutation.go, pkg/webhooks/server.go, pkg/webhooks/validate_audit.go
Fixes 1332.
/kind bug
Add support for wildcards in `selector.matchLabels` keys and values.
- [ x] I have added tests that prove my fix is effective or that my feature
works.
- [ x] I have added or changed [the documentation](documentation/).
=> 1332 wildcards in labels and annotations

pkg/webhookconfig/monitor.go, pkg/webhookconfig/registration.go
=> Fix webhook registration

pkg/engine/common/anchorKey.go, pkg/engine/generation.go, pkg/engine/validate/utils.go, pkg/engine/validate/validate.go, pkg/engine/validate/validate_test.go, pkg/engine/validation.go, pkg/policy/validate_controller.go
Fixes #1314 .
/kind bug
works.
=> 1314 validate rule

cmd/initContainer/main.go, cmd/kyverno/main.go, pkg/policy/validate_controller.go, pkg/policyreport/builder.go, pkg/policyreport/reportcontroller.go, pkg/webhooks/validation.go
Fixes https://github.com/kyverno/kyverno/issues/1370
=> 1370 clean up stale RCRs

pkg/engine/mutation.go, pkg/engine/validation.go, pkg/kyverno/validate/command.go, pkg/policy/validate.go
Fixes https://github.com/kyverno/kyverno/issues/1338.
=> Clarify policy application behavior on pods that are managed by workload controllers

pkg/generate/generate.go
=> Disable updates of generated resource when synchronize is set to false

scripts/ci.sh
Added kustomize install script in e2e infrastructure setup 
works.
=> Added kustomize install script

cmd/kyverno/main.go, pkg/generate/cleanup/controller.go, pkg/generate/generate.go, pkg/generate/generate_controller.go, pkg/webhooks/generate/generate.go, pkg/webhooks/generation.go, pkg/webhooks/server.go
https://github.com/kyverno/kyverno/issues/1345
Added label to generate requests.
Reduced API calls - using cache.
works.
=> 1345 use GR lister 

charts/kyverno/crds/crds.yaml, definitions/install.yaml, definitions/install_debug.yaml, pkg/api/kyverno/v1/policy_types.go, pkg/generate/generate.go, pkg/generate/generate_controller.go, pkg/policy/generate/validate.go, pkg/webhooks/generate/generate.go
Fixes #1390 
skip updating target if generate rule has no data and clone information
works.
=> allow generate with no data/status

pkg/generate/generate.go, pkg/policy/utils.go, pkg/policy/validate.go, pkg/utils/util.go, pkg/webhooks/generation.go
=> Fixes 1399 - generate with multiple rules

pkg/config/dynamicconfig.go, pkg/engine/generation.go, pkg/engine/policyContext.go, pkg/engine/utils.go, pkg/generate/generate.go, pkg/testrunner/scenario.go, pkg/webhooks/generation.go, pkg/webhooks/mutation.go, pkg/webhooks/validation.go
Fixes #1377
Check configured exclude list for generate rules
works.
=> filter resources excluded in config

.github/workflows/fossa.yml
Ref: https://github.com/cncf/foundation/issues/109
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
=> FOSSA scanning added

samples/AddSeccompProfile.md, samples/README.md, samples/more/add_pod_default_seccompprofile.yaml
Add a sample policy for setting Seccomp securityContext for 1.19 and above.
works.
=> add sample Seccomp securityContext example

pkg/kyverno/apply/command.go, pkg/kyverno/apply/command_test.go
https://github.com/kyverno/kyverno/issues/1266
Added test cases for policy report.
works.
=> Policy report cli testcases

pkg/engine/validation.go, pkg/policyreport/builder.go, pkg/webhooks/generation.go, pkg/webhooks/server.go, pkg/webhooks/validation.go
=> skip validation patterns for delete requests

cmd/initContainer/main.go, go.mod, go.sum, pkg/openapi/crdSync.go, pkg/openapi/validation.go, pkg/policyreport/reportrequest.go
=> Fix memory leak in CRD sync controller

cmd/kyverno/main.go, pkg/dclient/certificates.go, pkg/engine/mutate/patchesUtils.go, pkg/generate/generate.go, pkg/kyverno/apply/command.go, pkg/kyverno/validate/command.go, pkg/openapi/validation.go, pkg/policy/validate.go, pkg/policy/validate_test.go, pkg/policyreport/common.go, pkg/policyreport/reportrequest.go, pkg/policystatus/policy_status.go, pkg/tls/tls.go, pkg/webhooks/policymutation.go, pkg/webhooks/policyvalidation.go, pkg/webhooks/server.go
This PR:
- removes RCR entry from the datastore
- removes flag `fqdn-as-cn`
- fixes https://github.com/kyverno/kyverno/issues/1449
=> Improve / clean up code

pkg/engine/variables/vars.go, pkg/engine/variables/vars_test.go
#1466 
- [x ] I have added tests that prove my fix is effective or that my feature
works.
=> support nested JMESPATH var substitution

CONTRIBUTING.md
=> Add DCO sign instruction 

ADOPTERS.md, adopters.md
=> add adopters

cmd/initContainer/main.go, cmd/kyverno/main.go, pkg/dclient/client.go, pkg/generate/generate_controller.go, pkg/utils/util.go
Fixes #1479 
Fixes #1490
works.
=> handle discovery errors for metrics API group

charts/kyverno/README.md, charts/kyverno/templates/policies/default/disallow-adding-capabilities.yaml, charts/kyverno/templates/policies/default/disallow-host-namespaces.yaml, charts/kyverno/templates/policies/default/disallow-host-path.yaml, charts/kyverno/templates/policies/default/disallow-host-ports.yaml, charts/kyverno/templates/policies/default/disallow-privileged-containers.yaml, charts/kyverno/templates/policies/default/disallow-proc-mount.yaml, charts/kyverno/templates/policies/default/disallow-selinux.yaml, charts/kyverno/templates/policies/default/restrict-apparmor-profiles.yaml, charts/kyverno/templates/policies/default/restrict-sysctls.yaml, charts/kyverno/templates/policies/restricted/deny-privilege-escalation.yaml, charts/kyverno/templates/policies/restricted/require-non-root-groups.yaml, charts/kyverno/templates/policies/restricted/require-run-as-nonroot.yaml, charts/kyverno/templates/policies/restricted/restrict-seccomp.yaml, charts/kyverno/templates/policies/restricted/restrict-volume-types.yaml, charts/kyverno/values.yaml
Signed-off-by: Raj Babu Das <mail.rajdas@gmail.com>
Adding policies(default, restricted) to kyverno helm charts
Notes:
- By default, `policyType` is default in `values.yaml` 
- Supported type- default/restricted.
- All cluster policies are referred from https://github.com/kyverno/policies
Directory structure
Related issue- https://github.com/kyverno/kyverno/issues/1430
works.
=> Adding cluster policies(default, restricted) to kyverno helm charts

Makefile
Signed-off-by: Raj Babu Das <mail.rajdas@gmail.com>
works.
=> revert cli image name to kyverno-cli

charts/kyverno/crds/crds.yaml, definitions/crds/kyverno.io_clusterpolicies.yaml, definitions/crds/kyverno.io_policies.yaml, definitions/install.yaml, definitions/install_debug.yaml, pkg/api/kyverno/v1/policy_types.go
Updated docs for API call.
works.
- [ x] I have added or changed [the documentation](documentation/).
=> update APICall docs

cmd/kyverno/main.go, pkg/dclient/client.go, pkg/dclient/client_test.go, pkg/event/controller.go, pkg/resourcecache/main.go, pkg/webhookconfig/common.go, pkg/webhookconfig/registration.go
=> Reduce throttling requests (GET)

pkg/policystatus/policy_status.go
Fixes https://github.com/kyverno/kyverno/issues/1503.
=> Compare policy status before sending update request

pkg/kyverno/common/common.go, pkg/kyverno/common/fetch.go
Signed-off-by: Raj Das <mail.rajdas@gmail.com>
PR- https://github.com/kyverno/kyverno/pull/1527
works.
=> (Recreate PR)- Adding support for applying git raw by kyverno cli

pkg/engine/utils.go, pkg/generate/generate_controller.go
https://github.com/kyverno/kyverno/issues/931
Even valid resource was blocked by NamesapceSelector.
> /kind bug
fixed the issue
works.
=> Valid resource is blocked by namespace selector

index.yaml
=> Update the link to logo image

.github/workflows/build.yaml, .github/workflows/e2e.yaml, Makefile
closes #1550 
> /kind design
Introduced gofmt checks and also, edited "fmt" target in Makefile. The previous, even after being applied, did not "go format" all the go files as per `gofmt`. The newly added one does that rightfully, hence, added it.
works.
=> added: gofmt check over the existing github workflows

index.yaml
=> Update icon in index.yaml

charts/kyverno/Chart.yaml
=> Update icon in chart.yaml

charts/kyverno/README.md, charts/kyverno/templates/NOTES.txt, charts/kyverno/templates/policies/default/disallow-adding-capabilities.yaml, charts/kyverno/templates/policies/default/disallow-host-namespaces.yaml, charts/kyverno/templates/policies/default/disallow-host-path.yaml, charts/kyverno/templates/policies/default/disallow-host-ports.yaml, charts/kyverno/templates/policies/default/disallow-privileged-containers.yaml, charts/kyverno/templates/policies/default/disallow-proc-mount.yaml, charts/kyverno/templates/policies/default/disallow-selinux.yaml, charts/kyverno/templates/policies/default/restrict-apparmor-profiles.yaml, charts/kyverno/templates/policies/default/restrict-sysctls.yaml, charts/kyverno/templates/policies/restricted/deny-privilege-escalation.yaml, charts/kyverno/templates/policies/restricted/require-non-root-groups.yaml, charts/kyverno/templates/policies/restricted/require-run-as-nonroot.yaml, charts/kyverno/templates/policies/restricted/restrict-seccomp.yaml, charts/kyverno/templates/policies/restricted/restrict-volume-types.yaml, charts/kyverno/values.yaml
Signed-off-by: Raj Das <mail.rajdas@gmail.com>
Issue- https://github.com/kyverno/kyverno/issues/1549
Changes
1. Adding default policies for `restricted` podSecurityStandard
2. Adding notes.txt on helm install
3. Moving validationFailureAction as variable in values.yaml
4. 
works.
=> Adding default policies for restricted mode and adding notes to helm install

.github/ISSUE_TEMPLATE/scenario-to-support.md, .github/PULL_REQUEST_TEMPLATE.md
* Updates links in the PR template,
* Fixes some spelling
* Fixes minor formatting for consistency
works.
=> update links and formatting in PR template

pkg/kyverno/common/fetch.go
closes #1508 
> /kind bug
using "sigs.k8s.io/yaml" 's YAMLToJSON function to convert the input YAML byte object to the corresponding JSON byte object, under the `convertToUnstructuredObject` function. This way the nil values of empty provided fields are preserved instead of defaulting them to 0, hence, prevents kyverno from not throwing error and making false positives.
[https://github.com/kyverno/kyverno/issues/1508#issuecomment-776315382](https://github.com/kyverno/kyverno/issues/1508#issuecomment-776315382)
=> fix: restricting empty value from passing through the validation checks

pkg/webhooks/generation.go, pkg/webhooks/generation_test.go
code improvement - https://github.com/kyverno/kyverno/pull/1563#pullrequestreview-586869297
=> code improvement

pkg/kyverno/common/common.go
closes - https://github.com/kyverno/kyverno/issues/1596
> /kind bug
=> CLI Panic Fix - Getting invalid memory address error while using kyverno with --set

pkg/policy/validate.go, pkg/policy/validate_test.go
=> fix: allowed templatised values to be exempted from validation checks

pkg/webhooks/server.go
=> rename context2 -> enginecontext

Makefile, pkg/engine/context/context.go, pkg/engine/context/evaluate.go, pkg/engine/generation.go, pkg/engine/jsonContext.go, pkg/engine/mutate/patchJson6902_test.go, pkg/engine/mutation.go, pkg/engine/validation.go, pkg/engine/variables/vars.go, pkg/engine/variables/vars_test.go, pkg/generate/generate.go, pkg/policy/background.go, pkg/policy/generate/validate.go, pkg/policy/validate.go, pkg/policy/validate_test.go, pkg/policymutation/policymutation.go, pkg/webhooks/generation.go, pkg/webhooks/mutation.go, pkg/webhooks/policyvalidation.go, pkg/webhooks/server.go
fixes #1464 
fixes #1628 
fixes #1593 
> /kind bug
=> Bug fixes - policy validation, auto-generated rules, apiCall support in mutate and generate

charts/kyverno/crds/crds.yaml, definitions/crds/kyverno.io_clusterpolicies.yaml, definitions/crds/kyverno.io_policies.yaml, definitions/install.yaml, definitions/install_debug.yaml, pkg/api/kyverno/v1/policy_types.go
Fixes #1584 
> /kind bug
I ran `make kustomize-crd` in the project root but it didn't reflect my changes rather some other changes were made to the generated YAML files.
=> fix: list operators in deny conditions

pkg/policy/apply.go
closes https://github.com/kyverno/kyverno/issues/1626
> /kind bug
passing namespace label in policy context for validation of policy
=> Fix for - namespaceSelector in match prevents background scanning

charts/kyverno/crds/crds.yaml, definitions/crds/kyverno.io_clusterpolicies.yaml, definitions/crds/kyverno.io_policies.yaml, definitions/install.yaml, definitions/install_debug.yaml, pkg/api/kyverno/v1/policy_types.go
=> fix: removed validator

samples/DisallowHostNetworkPort.md, samples/best_practices/disallow_host_network_port.yaml
> /kind bug
Fixes https://github.com/kyverno/kyverno/issues/1653.
Update the policy to - X(hostPort): "null".
=> Fix: Null value doesn't work on negation's value

pkg/common/common.go, pkg/engine/generation.go, pkg/engine/utils.go, pkg/event/controller.go, pkg/policy/existing.go, pkg/resourcecache/main.go, pkg/resourcecache/resourcecache.go, pkg/webhooks/generation.go
Fixes : https://github.com/kyverno/kyverno/issues/1218
> /kind bug
Expansion to ResourceDescription to allow for groups/api version in addition to kinds
**Supported Format**
* Group/Version/Kind
* Group /Kind
* Kind
=> Bug Fix: Extends match / exclude to use apiGroup and apiVersion (#1218)

pkg/engine/apiPath.go, pkg/engine/apiPath_test.go
Signed-off-by: jsnider-mtu <jsnider@mtu.edu>
#1668 
/kind bug
Correct the ordering of parts of the API path when it includes namespaces.
=> Bug Fix #1668; Fix API path

pkg/kyverno/common/common.go
closes https://github.com/kyverno/kyverno/issues/1666
> /kind bug
Added logic for policy variable with `\"`
=> Added condition for slash in Kyverno CLI

pkg/kyverno/apply/command.go, pkg/kyverno/common/common.go, pkg/kyverno/common/common_test.go, pkg/kyverno/test/command.go
closes https://github.com/kyverno/kyverno/issues/1524
Added namespace selector logic in Kyverno CLI
=> Kyverno CLI - Namespace Selector

pkg/kyverno/common/common.go
closes https://github.com/kyverno/kyverno/issues/1693
> /kind bug
Added condition for policy with and without namespace selector filter
=> Policy without namespace selector gives error in Kyverno CLI- "pass the namespace labels"

pkg/kyverno/test/command.go, pkg/kyverno/test/git.go
> /kind bug
Fix feature branch test yamls are not getting test and log level issue.
=> Bug: Fix test yamls not working from feature branch

cmd/kyverno/localDockerfile, pkg/engine/mutate/mutation.go, pkg/engine/mutate/patchesUtils.go, pkg/engine/mutate/patchesUtils_test.go
Fixes https://github.com/kyverno/kyverno/issues/1612.
/kind bug
With [this](https://github.com/kyverno/kyverno/pull/1645) PR that changes `patchesJson6902` behavior, we no longer need the extra logic to handle the webhook re-invocation policy. This PR removes the relevant logic.
=> Remove logic that handles reinvocation policy

pkg/engine/mutate/mutation.go, pkg/webhooks/mutation.go
fixes #1465
/kind bug
- Raise log level to error instead of info in case when policy application has rules failed
- Add rule name to response so log could get list of failed rules
=> Bug Fix: #1465 issue; fix empty list of failed rules

pkg/kyverno/apply/command.go
closes https://github.com/kyverno/kyverno/issues/1706
> /kind bug
=> Kyverno CLI gives error on applying any policy on a resource 

pkg/engine/variables/evaluate_test.go, pkg/engine/variables/operator/in.go
Signed-off-by: Joshua Snider <jsnider@mtu.edu>
#1689 
/kind bug
Change isNotIn to return true if any element of key is not found in value.
=> Change isNotIn

pkg/engine/anchor/anchor.go, pkg/policy/common/validate_pattern.go
closes https://github.com/kyverno/kyverno/issues/1674
Looping all the items in the given array. Currently it process only the first element in the array.
=> Enhancement/existence anchor - should loop all the items in the array

pkg/engine/jsonContext.go
Fixes variable substitution in context.apiCall.jmesPath
=> fixes variable substitution in context.apiCall.jmesPath

cmd/kyverno/main.go, definitions/manifest/deployment.yaml, pkg/generate/cleanup/controller.go, pkg/generate/generate_controller.go, pkg/webhooks/generation.go
Fixes #1670.
With this PR, the number of generate workers can be configured with the flag `gen-workers`.
- If not, I have raised an issue in [kyverno/website](https://github.com/kyverno/website) to track the doc update: https://github.com/kyverno/website/issues/116
=> make the number of generate workers configurable

cmd/kyverno/main.go, go.mod, go.sum, pkg/engine/context/context.go, pkg/engine/context/imageutils.go, pkg/engine/context/imageutils_test.go, pkg/engine/mutation_test.go, pkg/engine/validation_test.go, pkg/generate/generate.go, pkg/webhooks/server.go, pkg/webhooks/validate_audit.go, pkg/webhooks/validation.go
This PR:
- fixes #1145
- remove `supportMutateValidate`
With this PR, the user should be able to access image details with the following variables (replace value in \<\> by container's name):
- {{images.containers.\<container-name\>.registry}} 
- {{images.containers.\<container-name\>.name}} 
- {{images.containers.\<container-name\>.tag}} 
- {{images.containers.\<container-name\>.digest}} 
- {{images.initContainers.\<initContainer-name\>.registry}} 
- {{images.initContainers.\<initContainer-name\>.name}} 
- {{images.initContainers.\<initContainer-name\>.tag}} 
- {{images.initContainers.\<initContainer-name\>.digest}} 
- [] I have added tests that …
=> Add Images info to variables context

pkg/generate/validate.go, pkg/generate/validate_test.go, pkg/webhooks/generation.go
closes https://github.com/kyverno/kyverno/issues/1675 , https://github.com/kyverno/kyverno/issues/1643
> /kind bug
Added separate validate logic for generate.
=> Added validate logic for generate to handle multiple items in array

pkg/kyverno/common/fetch.go
closes https://github.com/kyverno/kyverno/issues/1677
> /kind bug
skipping schema check for unknown kinds
=> Skipping schema check for unknown kinds

pkg/webhooks/generation.go
issue reported in slack - https://kubernetes.slack.com/archives/CLGR9BJU9/p1615992258008500
related issues : https://github.com/kyverno/kyverno/issues/1643 , https://github.com/kyverno/kyverno/issues/1675
> /kind bug
=> [Bug] - generate policy with clone loops endlessly with multiple items in array

.github/workflows/e2e.yaml, cmd/kyverno/main.go, pkg/webhookconfig/registration.go
Fixes #1740
/kind bug
This ensures that the webhooks are not added to API server before the webhook service endpoints are assigned an IP.  This should help prevent webhooks being called and causing Kubernetes API server timeouts before the kube-controller-manager has updated the Kyverno service endpoints.
=> Register webhooks only once service endpoint is ready

pkg/policy/common.go
> /kind bug
Fixes https://github.com/kyverno/kyverno/issues/1743.
Fixes https://github.com/kyverno/kyverno/issues/1752.
=> Fix exclude logic

pkg/engine/context/imageutils.go, pkg/engine/context/imageutils_test.go
Fixes https://github.com/kyverno/kyverno/issues/1757.
=> Set default image registry and tag if not present

pkg/generate/resource.go, pkg/utils/util.go, pkg/utils/util_test.go, scripts/create-e2e-infrastruture.sh
/kind bug
Fixes https://github.com/kyverno/kyverno/issues/1764.
=> Remove namespace field on kind Namespace

Makefile, test/e2e/generate/generate_test.go, test/e2e/mutate/config.go, test/e2e/mutate/mutate_test.go, test/e2e/mutate/resources.go, test/e2e/utils.go
https://github.com/kyverno/kyverno/issues/1778
/kind cleanup
I have been hitting some rough edges around mutation and therefore wanted to have an easy way to test against them in the future. This E2E test aims to make sure that behaviour doesn't break & we can easily replicate failures.
I will add some more test cases in a follow up. This is mainly to introduce the initial structure.
=> Add e2e test for mutation

.github/PULL_REQUEST_TEMPLATE.md, .github/pr_documentation.md
See relevant discussion here: https://github.com/kyverno/kyverno/discussions/1782
This PR updates the pull request template and adds a new documentation Markdown file which explains the process by which users who add or change Kyverno functionality should format their PRs.
=> add PR docs guide

.github/workflows/build.yaml, .github/workflows/e2e.yaml, charts/kyverno/templates/tests/test.yaml, charts/kyverno/values.yaml
Adds Helm lint testing and Helm install testing to Github Actions. The Helm install testing relies on tests that already setup Kind cluster.
=> Add Helm tests to Github Actions

pkg/policyreport/builder.go
Signed-off-by: Frank Jogeleit <frank.jogeleit@web.de>
/kind cleanup
Fix typo in method names
@chipzoller @realshuting
=> Fix Typo in builder method names

.github/PULL_REQUEST_TEMPLATE.md
/kind bug
This PR fixes the link to `pr_documentation.md` in the pull request template.
=> fix link to PR doc

pkg/webhooks/validation.go
The violation was not removed from the report when the resource was deleted. See ref https://github.com/kyverno/kyverno/issues/1780#issuecomment-821536394.
/bug
=> Fix result removal for DELETION requests

test/e2e/mutate/config.go, test/e2e/mutate/resources.go
=> Add e2e test with nested jmesPath in context

pkg/common/common.go, pkg/engine/generation.go, pkg/engine/jsonContext.go, pkg/engine/mutation.go, pkg/engine/mutation_test.go, pkg/engine/validation.go, pkg/engine/validation_test.go, pkg/generate/generate.go, pkg/kyverno/apply/command.go, pkg/kyverno/common/common.go, pkg/kyverno/store/store.go
closes https://github.com/kyverno/kyverno/issues/1515, https://github.com/kyverno/kyverno/issues/1525
Variables should be passed in a yaml file in the following format:
```
policies:
- name: <policy name>
rules:
- name: <rule name>
values:
<variable>: <value>
```
https://github.com/kyverno/website/issues/134
=> Feature/1515 - handle configmap and api variable cli 

.github/PULL_REQUEST_TEMPLATE.md
FIX Typo
FIX Link to the PR documentation file when a new PR is opened.
=> Fix: Link to pr_documentation file

charts/kyverno/templates/NOTES.txt
#1814 
Display Chart version after Helm installation : 
`Thank you for installing kyverno v1.3.6-rc1`
=> Display which chart version is installed

go.sum, pkg/generate/generate.go
Closes https://github.com/kyverno/kyverno/issues/1859
> /kind bug
updating synchronize label in generated resource 
check steps provided in issue
=> Updating synchronize lable in generated resource

charts/kyverno/crds/crds.yaml, charts/kyverno/templates/deployment.yaml, charts/kyverno/values.yaml, definitions/install.yaml, definitions/install_debug.yaml, definitions/manifest/deployment.yaml
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>
#1776 
Specify resources for the initContainer.
=> Resources for initContainers

Makefile, pkg/kyverno/test/command.go, test/cli/test-fail/missing-policy/policy.yaml, test/cli/test-fail/missing-policy/resources.yaml, test/cli/test-fail/missing-policy/test.yaml, test/cli/test-fail/missing-resource/policy.yaml, test/cli/test-fail/missing-resource/resources.yaml, test/cli/test-fail/missing-resource/test.yaml, test/cli/test-fail/missing-rule/policy.yaml, test/cli/test-fail/missing-rule/resources.yaml, test/cli/test-fail/missing-rule/test.yaml, test/cli/test/simple/resources.yaml, test/cli/test/simple/test.yaml
Fixes #1876 
Allows a test to have new status of `skip` which is used to indicate that the resource being tested does not apply to the policy rule, ie if the policy excludes a certain namespace or excludes via other methods.
If a test is defined but the policy, policy rule or resource are not found, the test command will exit 1 to indicate the tests are misconfigured.
There are e2e tests added using manifests to validate these changes. …
=> Improved testing to allow 'skip' status and fail if tested results do not exist

README.md
=> update star link

README.md
=> add details on contributing

definitions/release/install.yaml
While trying out the tutorial found a recent change that caused the tutorial to not work.
```bash
$ k create -f install.yaml
namespace/kyverno created
customresourcedefinition.apiextensions.k8s.io/clusterpolicies.kyverno.io created
customresourcedefinition.apiextensions.k8s.io/clusterpolicyreports.wgpolicyk8s.io created
customresourcedefinition.apiextensions.k8s.io/clusterreportchangerequests.kyverno.io created
customresourcedefinition.apiextensions.k8s.io/generaterequests.kyverno.io created
customresourcedefinition.apiextensions.k8s.io/policies.kyverno.io created
customresourcedefinition.apiextensions.k8s.io/policyreports.wgpolicyk8s.io created
customresourcedefinition.apiextensions.k8s.io/reportchangerequests.kyverno.io created
serviceaccount/kyverno-service-account created …
```
=> BugFix: move app: kyverno to labels for tutorial

definitions/install.yaml, definitions/install_debug.yaml, definitions/k8s-resource/clusterroles.yaml, definitions/k8s-resource/kustomization.yaml, definitions/k8s-resource/namespace.yaml, definitions/k8s-resource/service.yaml, definitions/k8s-resource/serviceaccount.yaml, definitions/labels.yaml, definitions/manifest/deployment.yaml, definitions/release/install.yaml
/kind bug
This PR:
- update version to v1.3.6; 
- split Kustomization manifests; 
- revert release/install.yaml
@nlamirault - I don't know why the …
=> Update resources' labels

dashboard/grafana/dashboard.json
Now, anyone can import this dashboard JSON directly into Grafana in just a few clicks and they will end up with a fully-fledged Grafana dashboard with a great set of insights around Kyverno deployed over their cluster.
** Setup **: All they have to do is just import the dashboard directly via this JSON. (this is going to be further documented in Kyverno's website)
** In action **:
- [] I have added or changed [the documentation](https://github.com/kyverno/website) …
=> added: JSON for Grafana Dashboard

cmd/initContainer/main.go, pkg/config/config.go
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>
Fixes #1447 
Enhancement
=> change min support kubernetes version to 1.16 for kyverno 1.4

pkg/generate/generate.go
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>
fixes #1416 
Log enhancement
As proposed by @realshuting, I added a suggestion to the existing log
`GenerateController "msg"="failed to apply generate rule" "error"="rolebindings.rbac.authorization.k8s.io is forbidden: User \"system:serviceaccount:kyverno:kyverno-service-account\" cannot create resource \"rolebindings\" in API group \"rbac.authorization.k8s.io\" in the namespace \"experimental\"" "apiVersion"="v1" "kind"="Namespace" "name"="experimental" "namespace"="" "policy"="vin-rolebinding" "resource"="experimental" "rule"="vin-rolebinding" "suggestion"="users need to grant Kyverno's service account additional privileges"
`
- …
=> Improve log message for generate policies

.github/workflows/e2e.yaml, charts/kyverno/templates/service.yaml, charts/kyverno/templates/tests/test.yaml, charts/kyverno/values.yaml, definitions/install.yaml, definitions/install_debug.yaml, definitions/k8s-resource/service.yaml
#1987 
Allow the Kyverno service to be configured differently than the metrics service, mainly with regard to their annotations.
=> Allow metrics service annotations to be defined separate from main service

OWNERS.md
=> add Chip Zoller as a maintainer

pkg/webhookconfig/monitor.go
=> Fix merge eror

.github/issues_bot.yml
Partially solves #1959 
Adding the [Auto label](https://github.com/marketplace/actions/auto-label) bot for the repo. 
=> adding a bot for labelling issues

go.sum
#2033 
> /kind bug
I ran `go mod tidy` while having Go 1.16.2 loaded in my environment.
I wonder if worth adding a matrix to build Github actions so build against Go 1.14 - 1.16 even if still using 1.14 for building …
=> Fix build errors with Go 1.16

charts/kyverno/templates/secret.yaml
Signed-off-by: George Kaz <egeorgekaz@gmail.com>
/kind bug
Current template is wrong. It prints "kyverno.namespace" literally rather than substitute in the correct namespace. This patch fixes that bug.
This error can be seen in the kube-apiserver logs:
```
E0621 13:14:41.093232       1 dispatcher.go:129] failed calling webhook "validate.kyverno.svc": Post https://kyverno-svc.kyverno.svc:443/validate?timeout=3s: x509: certificate is valid for kyverno-svc.kyverno.namespace.svc, not kyverno-svc.kyverno.svc
```
I tested it by temporarily adding these annotations to the secret during my development:
```
annotations:
ca: "{{ printf "*.%s.svc" (include "kyverno.namespace" .) }}"
cert: "{{ printf "%s.%s.svc" (include "kyverno.serviceName" .) (include "kyverno.namespace" .) }}"
```
- [] My PR …
=> Correct ca and cert namespace

charts/kyverno/Chart.yaml
Signed-off-by: George Kaz <egeorgekaz@gmail.com>
https://github.com/kyverno/kyverno/pull/2048
/kind bug
This iterates the chart version which was missing from a previous PR merge
N/A
@vyankyGH as discussed on https://github.com/kyverno/kyverno/pull/2048. Thanks
=> iterate-chart-version

definitions/crds/kyverno.io_policies.yaml, pkg/api/kyverno/v1/policy_types.go
=> fix typo in policy struct

charts/kyverno/templates/deployment.yaml
https://github.com/kyverno/kyverno/issues/2051
=> Remove selector from Helm chart

pkg/engine/validate/pattern.go
#2063 
> /kind bug
Move log message to Debug, that shouldn't be printed with Info.
=> Move log to debug for wildcard pattern matching

charts/kyverno/templates/deployment.yaml, pkg/config/config.go
closes https://github.com/kyverno/kyverno/issues/2002
This issue happen only if deployment name is not set to kyverno
Don't allow custom name of the Deployment, Change to  the fixed name.
**Change the Helm templates using the fixed deployment name**
Before changes following logs
The logs will show `common.go:61] Register "msg"="failed to construct OwnerReference" "error"="deployments.apps \"kyverno\" not found"` also pods/deployment getting stuck.
After Running kyverno with following Helm changes above issue get solve.
`1 registration.go:364] Register "msg"="created webhook"  "kind"="MutatingWebhookConfiguration" "name"="kyverno-verify-mutating-webhook-cfg" I0624 07:16:24.593437       1 registration.go:319] Register "msg"="created …
=> Fix Helm deployment name issue

charts/kyverno/templates/deployment.yaml, pkg/config/config.go
=> Revert "Fix Helm deployment name issue"

charts/kyverno/crds/crds.yaml, definitions/crds/kyverno.io_clusterpolicies.yaml, definitions/crds/kyverno.io_policies.yaml, definitions/install.yaml, definitions/install_debug.yaml, pkg/api/kyverno/v1/policy_types.go, pkg/engine/utils.go, pkg/engine/utils_test.go, pkg/policy/validate.go, pkg/webhooks/policyvalidation.go
Fixes #1990 
Create the following policy:
```
metadata:
spec:
rules:
- name: no-labels
match:
resources:
names: ["dev", "prod-*"]
kinds:
- Pod
validate:
message: "label 'app.kubernetes.io/name' is required"
pattern:
metadata:
labels:
app.kubernetes.io/name: "?*"
```
Try creating this pod and you will see that it will fail (as expected):
```
apiVersion: v1
kind: Pod
metadata:
name: prod-test
labels:
role: myrole
spec:
containers:
- name: web
image: nginx
```
For exclude blocks, create the following policy:
```
metadata:
spec:
validationFailureAction: …
```
=> adding support for multiple names in match and exclude blocks

.github/workflows/release.yaml
Fixes #2057
> /kind bug
Use Helm release Github Action that works with Helm chart releases during tags.  The Helm official Github Action does not work off releases from tags.
=> Fix Helm release during tag

pkg/webhooks/generation.go, test/e2e/generate/config.go, test/e2e/generate/generate_test.go
closes https://github.com/kyverno/kyverno/issues/2085
Added e2e test cases for updated generate workflow. 
These are test cases for PR - https://github.com/kyverno/kyverno/pull/1880
Fixed a bug -> generated resource was not replicating the changes on updating the clone source resource. Even when the generate policy was available.  …
=> 2085 e2e generate policy

charts/kyverno/templates/deployment.yaml
=> Helm chart: Eliminate duplicate env key when iterating over envVars

pkg/kyverno/test/command.go, test/cli/test/autogen/policy.yaml, test/cli/test/autogen/resources.yaml, test/cli/test/autogen/test.yaml
closes https://github.com/kyverno/kyverno/issues/1922
policy.yaml
```yaml
metadata:
name: require-common-labels
spec:
rules:
- name: check-for-labels
match:
resources:
kinds:
- Pod
validate:
message: "Both `app` and `owner` labels must be set on all workloads"
pattern:
metadata:
labels:
app: "?*"
owner: "?*"
```
resource.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
name: pod-with-labels
labels:
app: my-pod
owner: me
---
apiVersion: v1
kind: Pod
metadata:
name: pod-missing-labels
---
metadata:
name: deployment-with-labels
spec:
template:
metadata:
labels:
app: my-pod
owner: me
--- …
```
=> Add autogen-support for test command

charts/kyverno/crds/crds.yaml, definitions/crds/kyverno.io_clusterpolicies.yaml, definitions/crds/kyverno.io_policies.yaml, definitions/install.yaml, definitions/install_debug.yaml, pkg/api/kyverno/v1/policy_types.go
=> adding a note to deprecate name in favour of names

charts/kyverno/templates/service.yaml
closes https://github.com/kyverno/kyverno/issues/1397
Fix Helmchart doesn't respect metricsService.create flag.
Install helmchart with metricsService.create: false in helm values
check kyverno-svc-metrics service should not created
=> Fix Helmchart doesn't respect metricsService.create flag

pkg/engine/utils.go, pkg/engine/utils_test.go
Fixes https://github.com/kyverno/kyverno/issues/1784.
/bug
Prior to this change, if Pods has `ownerReference` set, Kyverno skips pod's rule application since the pod controllers are handled via autogen. With this change, Kyverno checks the kind in the `ownerReference`, and applies Pod's rules if the owner kind is not k8s pod controllers, to list them out: Deployment,StatefulSet,DaemonSet,Job,Cronjob.
Apply following policy to the Pod with `ownerReference` (none k8s pod controllers), the Pod creation gets blocked.
```yaml
metadata:
name: require-run-as-non-root
annotations:
policies.kyverno.io/category: Pod Security Standards (Restricted) …
```
=> Apply pod's rules if the owner is not k8s pod-controllers

charts/kyverno/templates/tests/test.yaml
closes https://github.com/kyverno/kyverno/issues/2125
=> remove duplicate

charts/kyverno/crds/crds.yaml, charts/kyverno/templates/clusterrole.yaml, definitions/install.yaml, definitions/install_debug.yaml, definitions/k8s-resource/clusterroles.yaml, pkg/policy/report.go, pkg/policyreport/policyreport.go, pkg/policyreport/reportcontroller.go
Fixes https://github.com/kyverno/kyverno/issues/2131.
/bug
/enhancement
As described in the issue, this PR:
- Clean up RCRs per background interval
- Clean up RCRs after 10 times retry: the previous logic only drops RCRs from the queue but does not cleanup the existing resources, it could result in stale RCRs (though the chances are low).
Since this issue is not reproducible on my local, I disabled existing cleanup processes (cleanup happens when RCRs get merged to reports succeessfuly) to test the change. With a bunch of policies deployed, when Kyverno started, it generated policy reports with RCRs left in the cluster, after deleted the policy report, the RCRs were cleaned up. This test mocks the background scan process.
```
k get rcr -n kyverno 
NAME        PASS   FAIL   WARN   ERROR …
```
=> Cleanup Report Change Requests

.github/workflows/build.yaml, .github/workflows/helm-release.yaml, .github/workflows/helm-test.yaml, .github/workflows/release.yaml, charts/kyverno/Chart.yaml
kyverno#2073 - Updates chart version to v1.4.2 - merged 13 days ago but not deployed
kyverno#2081 - Fix Helm release during tag - merged 9 days ago
kyverno#2037 - updated chart contents but not chart version - not released - merged 7 days ago
kyverno#2103 - updated chart contents but not chart version - not released - merged 3 hours ago
Status - main branch shows chart version is v1.4.2, git tag is v1.4.1 and latest helm chart on artifacthub.io/packages/helm/kyverno/kyverno is v1.4.1
This PR just iterates the chart version so that it's built, but I think chart versions should be incremented as part of the normal PR/merge process if chart elements are changed
Signed-off-by: George Kaz <egeorgekaz@gmail.com>
- [] I have read the [contributing …
=> Chart changes merged,not deployed,iterate version

.github/workflows/helm-release.yaml, .github/workflows/helm-test.yaml, charts/kyverno/Chart.yaml
https://github.com/kyverno/kyverno/pull/2111#issuecomment-880227169
Adds the missing step to the helm-release workflow. Bumps the version to 1.4.4 to trigger the release step. Does mean that 1.4.2 & 1.4.3 never existed as charts though.
Signed-off-by: George Kaz <egeorgekaz@gmail.com>## Related issue
- [] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_doc …
=> Fix helm-release workflow

.github/workflows/helm-release.yaml
The fix for the Helm releaser proposed in https://github.com/kyverno/kyverno/pull/2150#issuecomment-882829135.
=> Bump Helm version

.github/workflows/helm-release.yaml, .github/workflows/helm-test.yaml
Signed-off-by: George Kaz <egeorgekaz@gmail.com>
Adds helm tests before the helm release on merge
=> add tests before helm release

Makefile
https://github.com/kyverno/kyverno/issues/2114
kind enhancement
Written a separate script for `test-e2e-local`, to make it possible to run tests locally especially for dev environment with a local cluster like Minikube, Docker Desktop, etc.  
```
test-e2e-local:
$(eval export E2E="ok")
kubectl apply -f https://raw.githubusercontent.com/kyverno/kyverno/main/definitions/github/rbac.yaml
kubectl port-forward -n kyverno service/kyverno-svc-metrics  8000:8000 &
go test ./test/e2e/metrics -v
go test ./test/e2e/mutate -v
go test ./test/e2e/generate -v
kill  $!
$(eval export E2E="")
```
- [] My PR contains …
=> Allow running e2e tests on local (dev) cluster 

.github/workflows/release.yaml, charts/kyverno/templates/NOTES.txt
- Remove Github Releaser
- Add app version in Helm notes
=> Remove GitHub Releaser & Add app version in Helm notes

pkg/policycache/cache_test.go
=> fixes for cache tests

pkg/api/kyverno/v1/utils.go, pkg/engine/generation.go, pkg/engine/mutation.go, pkg/engine/utils.go, pkg/engine/validation.go
Signed-off-by: Maxim Goncharenko <goncharenko.maxim@apriorit.com>
/kind bug
Rule was changed in cluster because I added variable substitution logic and I haven't added there rule deep copy.
Now it is present. And also I added workaround for deepcopy using json lib.
```yaml
metadata:
name: pod-exec-allowed
spec:
rules:
- name: myapp-maintenance-allowed
match:
resources:
kinds:
- PodExecOptions
preconditions:
value: CONNECT
validate:
deny:
conditions:
- key: "{{ request.name }}"
value: "myapp-maintenance-*"
```
```yaml
metadata:
name: myapp-maintenance
labels:
app: nginx
spec:
replicas: 1 …
```
=> added deep copy for rule; changed rule deep copy logic

dashboard/grafana/dashboard.json
=> updated: grafana dashboard json with respect to new set of metrics

pkg/webhookconfig/common.go, pkg/webhookconfig/policy.go, pkg/webhookconfig/registration.go, pkg/webhookconfig/resource.go
closes https://github.com/kyverno/kyverno/issues/1957
> /kind bug
Removing ownerReference from the code while registering `mutatingwebhookconfiguration`.
1. Run Kyverno using flux.
2. Check `mutatingwebhookconfiguration ` using command:- `kubectl describe mutatingwebhookconfiguration kyverno-policy-mutating-webhook-cfg`
You will not get the warning message as earlier:
```
Events:
Type     Reason                    Age   From                          Message
----     ------                    ----  ----                          -------
Warning  OwnerRefInvalidNamespace  19m   garbage-collector-controller  ownerRef [apps/v1/Deployment, namespace: , name: kyverno, uid: 2a74562e-6de2-48c7-949b-0c319c3f4b9c] does not exist …
```
=> Removing OwnerReference

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release.yaml, Makefile
- update Make target "release-notes"
- update release workflow config
- update PR template
/enhancements
=> Minor enhancements

pkg/config/config.go, pkg/webhookconfig/common.go, pkg/webhookconfig/policy.go, pkg/webhookconfig/registration.go, pkg/webhookconfig/resource.go
`/milestone 1.4.3`.
When we uninstall kyverno we need to clean up [webhook configurations separately](https://kyverno.io/docs/installation/#clean-up-webhook-configurations). 
Now registering the webhook configurations  with owner reference(with namespace). With this change we need not to clean up the webhook configurations separately, it will be deleted with the uninstallation of kyverno.
After uninstalling kyverno check for webhook configurations:
```
$ kubectl get mutatingwebhookconfigurations                                  
No resources found
$ kubectl get validatingwebhookconfigurations                                 
No resources found
```
- [] I …
=> Adding ownerRef with namespace

.github/workflows/helm-release.yaml
Fixes #2264
> /kind bug
Only release the Helm charts on a tag prefiex by `helm-chart-v` so like `helm-chart-v2.0.3`.
Might need updates to release wiki page
=> Only release Helm charts on tags

pkg/kyverno/apply/apply_command.go
Updated help section of CLI `apply` command.
In the variable format - how to pass the context variable was missing.
=> Updating help section for CLI `apply` command

pkg/engine/mutation_test.go
Signed-off-by: Marcel Mueller <marcel.mueller1@rwth-aachen.de>
/kind cleanup
No actual changes, only code formatting.
Working with this file was unpleasant to me. No actual content was changed, only formatting and some consistency.
Also `tabs` -> `spaces` as the file was half and half currently which is the worst of both sides.
=> Clean up formatting in mutate test file

pkg/engine/mutation_test.go
/kind cleanup
This only adds a test towards #2100 which proves that the issue is not related to any mutation logic but instead closely related to some POD related validation. Therefor `patchesJson6902` is not directly involved.
This diff is a mess until #2338 is merged as I based this PR off of the cleanup.
=> Add test case for non zero index patches with patchesJson6902

pkg/kyverno/common/fetch.go
closes https://github.com/kyverno/kyverno/issues/2350
Add the milestone label by commenting `/milestone 1.4.3`.
> /kind bug
Added condition for getting kinds from `all/any` condition in CLI.
Apply the following service.yaml in cluster
```
apiVersion: v1
kind: Service
metadata:
name: staging
labels:
app: user-service
spec:
type: LoadBalancer
ports:
- port: 8082
protocol: TCP
targetPort: 8082
selector:
app: user-service
```
Now apply the following policy on the cluster resources:
```
metadata:
name: test-policy
spec:
rules:
- name: test-policy-rule
match:
any:
- resources:
kinds: 
- Service
names: 
- "staging"
- resources:
kinds: 
- Service
namespaces:
- "prod"
validate:
message: test …
```
=> Added condition for `all/any` for match | CLI

charts/kyverno-crds/templates/crds.yaml, cmd/kyverno/main.go, definitions/crds/kyverno.io_clusterpolicies.yaml, definitions/crds/kyverno.io_policies.yaml, definitions/install.yaml, definitions/install_debug.yaml, pkg/api/kyverno/v1/policy_types.go, pkg/cosign/cosign.go, pkg/engine/imageVerify.go
Fixes https://github.com/kyverno/kyverno/issues/2294.
/kind feature
Allow configuring alternate image repositories for signatures via a command line argument `imageSignatureRepository` and per rule `rule.verifyImages.Repository`.
=> allow alternate image repositories

SECURITY.md
Closes #2055 
Initialise `security.md` which introduces
- When to and when not to report a vulnerability
- Product Security Team
- Public and Private Security Disclosure Processes  
Inspiration has been taken from various ongoing and graduated CNCF projects to maintain uniformity.
- [] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documen …
=> Initialize Security Disclosure Processes

pkg/kyverno/apply/apply_command.go, pkg/kyverno/common/common.go, pkg/kyverno/test/test_command.go, test/cli/test/variables/cm-globalval-example.yaml, test/cli/test/variables/resources.yaml, test/cli/test/variables/test.yaml, test/cli/test/variables/variables.yaml
Closes #1472
/kind feature
Implemented as specified [here](https://github.com/kyverno/kyverno/pull/1595#issuecomment-799988263).
policy.yaml
```yaml
metadata:
name: cm-globalval-example
spec:
rules:
- name: validate-mode
match:
resources:
kinds:
- Pod
validate:
message: "The value {{ request.mode }} for val1 is not equal to test."
deny:
conditions:
- key: "{{ request.mode }}"
operator: NotEquals
value: dev
```
pod.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
name: test-global-prod
spec:
containers:
- name: nginx
image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
name: test-global-dev
spec:
containers:
- name: nginx …
```
=> CLI: Global variables

charts/kyverno-crds/templates/crds.yaml, definitions/install.yaml, definitions/install_debug.yaml, definitions/k8s-resource/configmap.yaml
Signed-off-by: slayer321 <sachin.maurya7666@gmail.com>
closes #2347
/kind bug
=> remove not consistent kyverno ConfigMap name

.github/workflows/e2e.yaml, charts/kyverno/values.yaml
fixes e2e test cases failure - https://github.com/kyverno/kyverno/pull/2417/checks?check_run_id=3661990352
`/milestone 1.5.0`.
> /kind failing-test
updated logic to replace the `tag` in `value.yaml`
=> fix | e2e test cases are failing with busybox image

charts/kyverno/templates/crds.yaml, charts/kyverno/templates/deployment.yaml, definitions/install.yaml, definitions/manifest/deployment.yaml
Closes #2436 
Related PR #1985 #1982 
Previously the podAntiAffinity was set to hard limits `requiredDuringSchedulingIgnoredDuringExecution` we changed `requiredDuringSchedulingIgnoredDuringExecution` to `preferedDuringSchedulingIgnoredDuringExecution` in the affinity.
The goal is to allow rolling upgrade with the `preferedDuringSchedulingIgnoredDuringExecution` affinity. This would help prevent a situation like this https://github.com/kyverno/kyverno/pull/1985#issuecomment-925022400
Add a label in the deployment `foo: bar` (https://github.com/anushkamittal20/kyverno/blob/fea50b014ab4e0b5d65296e5dc8553b3807867b1/definitions/install.yaml#L6589) and when the manifest is reapplied you can see that the new pod is allowed to create first and then the old pod is deleted, with …
=> Update anti-affinity to the soft limit

charts/kyverno/templates/crds.yaml, definitions/crds/kyverno.io_clusterpolicies.yaml, definitions/crds/kyverno.io_policies.yaml, definitions/install.yaml, definitions/install_debug.yaml, pkg/api/kyverno/v1/clusterpolicy_types.go, pkg/api/kyverno/v1/policy_types.go, pkg/api/kyverno/v1/zz_generated.deepcopy.go
Signed-off-by: ShutingZhao <shutting06@gmail.com>
https://github.com/kyverno/kyverno/issues/1981
/milestone 1.5.0
> /kind api-change
Added new fields `policy.spec.webhookTimeoutSeconds` and `policy.spec.failurePolicy`.
=> Add new fields `webhookTimeoutSeconds` and `failurePolicy` to the policy Spec

charts/kyverno/templates/crds.yaml, definitions/crds/kyverno.io_clusterpolicies.yaml, definitions/crds/kyverno.io_generaterequests.yaml, definitions/crds/kyverno.io_policies.yaml, definitions/install.yaml, definitions/install_debug.yaml, pkg/api/kyverno/v1/policy_types.go
=> Adding deprecation warning for any and all (Rebased)

.github/workflows/image.yaml
@realshuting Fixes the typo in #2438 
/kind bug
Fixes typo in the URL of the container registry in kyverno-cli
=> fix: sign kyverno-cli

pkg/engine/context/context.go
Signed-off-by: anushkamittal20 <anumittal4641@gmail.com>
#2118 
Adding logs to be able to understand where mutate policy is failing as mentioned in #2118 
Once the issue is realised and solved these debug logs will …
=> Adding log statements in context.go

pkg/engine/jmespath/functions_test.go
Signed-off-by: Marcel Mueller <marcel.mueller1@rwth-aachen.de>
/kind cleanup
Just improving consistency and adding some simple testcases.
=> Improve consistency in jmesPath functions test file

pkg/engine/imageVerify.go, pkg/engine/mutation.go, pkg/engine/validation.go, pkg/policy/common.go
Fixes: https://github.com/kyverno/kyverno/issues/2164
1.5.2
/kind bugfix
Remove logic to skip applying polices to managed pods. Now, policies are applied to pod controllers and again to managed pods.
Configure pod security policies and then apply the following "bad pod" which pretends to be a managed pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
name: nginx-96cd9654f-xlg64
ownerReferences:
- apiVersion: apps/v1
blockOwnerDeletion: true
controller: true
kind: ReplicaSet
name: nginx-96cd9654f
uid: d9fb7117-7df3-4500-b06e-7162130f9133
spec:
containers:
- image: public.ecr.aws/nginx/nginx:alpine
imagePullPolicy: IfNotPresent
name: nginx
privileged: true
ports:
- containerPort: 8080
protocol: TCP
```
- [] My PR …
=> re-apply policies to managed pods

api/kyverno/v1/utils.go
Closes #805 
/milestone 1.5.2
/kind bug
- Marshal original object's JSON and unmarshall it into new object
=> Fix deep copy methods

api/kyverno/v1/utils.go
Closes  #2663 
/kind bug
```bash
$ helm install kyverno-policies kyverno/kyverno-policies --namespace kyverno
NAME: kyverno-policies                                                                       
LAST DEPLOYED: Wed Nov  3 01:48:01 2021                                                      
NAMESPACE: kyverno                                                                           
STATUS: deployed                                                                             
REVISION: 1                                                                                  
TEST SUITE: None                                                                             
NOTES: …
```
=> Add nil checks in custom deep copy function

pkg/config/config.go, pkg/webhookconfig/common.go
closes https://github.com/kyverno/kyverno/issues/2623
milestone 1.5.2
/kind bug
Install kverno : kubectl apply -f config/install.yaml 
Install policies : kustomize build https://github.com/kyverno/policies/pod-security | kubectl apply -f -   
Uninstall kyverno.
=> bug fix : Kyverno policies block uninstall of Kyverno

charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml
Signed-off-by: ShutingZhao <shutting06@gmail.com>
Bump chart version to release the change in https://github.com/kyverno/kyverno/pull/2655.
=> Bump chart version to release https://github.com/kyverno/kyverno/pull/2655

pkg/generate/generate.go
Signed-off-by: Pritish Samal [pritish.samal918@gmail.com](mailto:pritish.samal918@gmail.com)
Fied a small typo while going through the codebase
=> fix typo in code comments

pkg/webhookconfig/configmanager.go
follow-up PR for https://github.com/kyverno/kyverno/pull/2615
- [] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding …
=> Ignoring generate kinds from mutate webhook

Makefile
Co-authored-by: Erkan Zileli <erkan.zileli@trendyol.com>
Co-authored-by: Furkan Turkal <furkan.turkal@trendyol.com>
#2702 
/kind feature
=> feat: create new builder for buildx

CHANGELOG.md
- [] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the …
=> Update CHANGELOG for PDB

go.mod, go.sum
Fixes https://github.com/kyverno/kyverno/security/dependabot/go.sum/github.com%2Fopencontainers%2Fimage-spec/open
1 github.com/opencontainers/image-spec vulnerability found in go.sum 10 hours ago
Remediation
Upgrade github.com/opencontainers/image-spec to version 1.0.2 or later. For example:
require github.com/opencontainers/image-spec v1.0.2
Always verify the validity and compatibility of suggestions with your codebase.
1.6
/kind bug
- [] I have added or changed [the documentation](https://github.com/kyverno/website) myself in an …
=> fix dependabot issue and remove stale entries in go.mod

pkg/openapi/crdSync.go
closes https://github.com/kyverno/kyverno/issues/2285
closes https://github.com/kyverno/kyverno/issues/2254
closes https://github.com/kyverno/kyverno/issues/2162
1. Install Volcano Job
2. Create the following policy
```yaml
metadata:
name: add-gpu-limits
annotations:
policies.kyverno.io/title: Add nodeSelector
Adds the nodeSelector field to a Pod spec.
spec:
rules:
- name: add-atleast-one-gpu-vcjob
match:
resources:
kinds:
- batch.volcano.sh/v1alpha1/Job
preconditions:
all:
- key: "{{ request.object.spec.tasks[].template.spec.nodeSelector.gpu | to_string(@) | contains(@, 'true') }}"
value: …
```
=> fix crd sync issue

CHANGELOG.md, charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, definitions/install.yaml, definitions/release/install.yaml, definitions/release/kustomization.yaml, definitions/release/labels.yaml
Signed-off-by: ShutingZhao <shutting06@gmail.com>
=> Release v1.5.2-rc2

CONTRIBUTING.md, MAINTAINERS.md
=> updated the contributing.md file 

ADOPTERS.md
We're actively using and promoting Kyverno at VSHN, at this time mainly for the upcoming product called APPUiO Cloud.
=> Add VSHN as adopter with APPUiO Cloud

pkg/openapi/crdSync.go
closes https://github.com/kyverno/kyverno/issues/1490
/kind bug
https://github.com/kyverno/kyverno/issues/1490#issuecomment-985068081
=> Fix issue 1490 : initContainer fail to start when external.metrics.k8s.io/v1beta1

cmd/initContainer/main.go, cmd/kyverno/main.go, pkg/config/config.go, pkg/config/config_test.go
https://github.com/kyverno/kyverno/issues/2795
/kind feature
This PR adds `-clientRateLimitQPS` and `-clientRateLimitBurst` command-line flags to allow controlling client rate limits.
=> Add command-line flags to allow setting client rate limits (QPS/Burst)

.github/workflows/image.yaml, CHANGELOG.md, charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, definitions/install.yaml, definitions/release/install.yaml, definitions/release/kustomization.yaml, definitions/release/labels.yaml
=> release v1.5.2-rc5

Makefile, docs/crd/v1/index.html
Sync api docs with latest api changes
Here is preview of generated HTML docs:
https://htmlpreview.github.io/?https://github.com/prateekpandey14/kyverno/blob/update-api-docs/docs/crd/v1/index.html#kyverno.io/v1.Rule …
=> [docs]: sync api docs with latest api changes

pkg/webhookconfig/common.go
milestone 1.6.0
/kind bug
Install Kyverno using local changes
Kyverno Pod coming  state
Unistall Kyverno
=> Update labels to fetch cluster role

.github/workflows/image.yaml, Makefile
Closes https://github.com/kyverno/kyverno/issues/2826.
/1.6.0
/bug
/enhancement
From this PR, the dev images are published with wildcard match tag `*-dev-*`, for example, `1.6-dev-hash` for 1.6.x dev images. And the latest image will always be tagged as "<latest minor milestone>-dev-latest", i.e. `1.6-dev-latest`.
See dev images that were published by this job https://github.com/realshuting/kyverno/runs/4555546832?check_suite_focus=true:
- [] I have added or changed [the documentation](https://github.com/kyverno/website) myself …
=> Test publishing dev-test images 

.github/workflows/image.yaml, .github/workflows/release.yaml, Makefile, cmd/alpineBase/Dockerfile
Signed-off-by: ShubhamPalriwala <spalriwalau@gmail.com>
Closes https://github.com/kyverno/kyverno/issues/2705.
=> Cherry pick #2536

charts/kyverno/values.yaml
Signed-off-by: Franz Nemeth <franz.nemeth@fnemeth.net>
#2762
/milestone 1.6
/kind cleanup
The functionality requested in #2762 was already there but it was not reflected in the values.yaml file shipped with the helm chart.
Added a priorityClassName to `charts/kyverno/values.yaml`.
=> added priorityClassName to helm values.yaml

charts/kyverno/templates/aggregateroles.yaml, charts/kyverno/templates/clusterrole.yaml, charts/kyverno/templates/crds.yaml, config/install.yaml, config/install_debug.yaml, config/k8s-resource/aggregateroles.yaml, config/k8s-resource/clusterroles.yaml
Fixes https://github.com/kyverno/kyverno/issues/2858
1.6
/kind bug
Fixed permissions for clusterpolicyreports / policyreports
Tested using a fresh install of Kyverno and pod security policies, to generate policy reports. 
=> fix report permissions

pkg/policy/validate.go, pkg/webhookconfig/common.go
closes https://github.com/kyverno/kyverno/issues/2460
milestone 1.5.3
/kind bug
- "*"
- "*pattern"
- "pattern*"
- "pat*tern"
- "* pattern*"
```
metadata:
name: add-image-pull-secret
spec:
rules:
- name: add-imagepullsecrets
exclude:
resources:
selector:
matchLabels:
strimzi.io/kind: "*"
match:
resources:
kinds:
- Pod
mutate:
spec:
imagePullSecrets:
- name: harbor
```
```
clusterpolicy.kyverno.io/add-image-pull-secret created
```
- [] I have raised an issue in [kyverno/website](https://github.com/kyverno/website) to track the doc update and the link …
=> 2460: Add wildcard support for match label selector

go.mod, pkg/webhookconfig/configmanager.go
Closes #2821 
/milestone 1.5.3
/kind feature
Kyverno writes its webhook configurations for a policy the subject kind of which is Pod, it is only creating pods under .webhooks.rules.resources. In order to listen for AdmissionReview requests when ephemeralContainers are added, it must listen to the /ephemeralcontainers subresource. These changes append `pods/ephemeralcontainers` as validatinwebhook configuration rule to listen ephemeralcontainer subresources.
```yaml
rules:
- apiGroups:
- ""
- apps
- batch
apiVersions:
- v1
operations:
- CREATE
- UPDATE
- DELETE
- CONNECT
resources:
- pods
- pods/ephemeralcontainers
- daemonsets
- deployments
- jobs
- statefulsets
- cronjobs
```
```yaml …
```
=> feat(validation): support for ephemeral containers

.github/workflows/image.yaml, .github/workflows/release.yaml
Signed-off-by: Namanl2001 <namanlakhwani@gmail.com>
#2880  #2882
Currently, Kyverno images are signed using a tag, which is mutable. proposed signing kyverno images with digest 
Also, Kyverno is currently signing its images with a public/private keypair. therefore switching to keyless image signing
keyless image singing with digest example: https://github.com/mattmoor/zero-friction-actions/blob/main/.github/workflows/docker-publish.yml#L42-L50
- [] I have added or changed [the documentation](https://github.com/kyverno/website) myself in an …
=> keyless signing kyverno images with digest

Makefile, charts/kyverno/ci/test-networkpolicy.yaml, charts/kyverno/templates/networkpolicy.yaml, charts/kyverno/values.yaml, go.mod, go.sum, pkg/engine/response/response.go, pkg/engine/utils.go, pkg/engine/validation.go, pkg/policy/validate.go, pkg/policyreport/builder.go, pkg/policyreport/changerequestcreator.go, pkg/tls/certRenewer.go, pkg/tls/reader.go, pkg/webhookconfig/configmanager.go, pkg/webhookconfig/registration.go, pkg/webhooks/common.go, pkg/webhooks/validation.go
Cherry-pick commits for 1.5.3 https://github.com/kyverno/kyverno/pulls?q=is%3Apr+label%3A%22milestone+1.5.3%22+is%3Aclosed.
=> Cherry-pick commits for 1.5.3

CHANGELOG.md, Makefile, charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, definitions/install.yaml, definitions/release/install.yaml, definitions/release/kustomization.yaml, definitions/release/labels.yaml
=> Release v1.5.3-rc1

Makefile
ref: https://github.com/kyverno/kyverno/issues/2920#issuecomment-1006669418
sorry @realshuting for the inconveinence
=> fix: removing docker-buildx-builder to get digest

.github/workflows/image.yaml
ref: https://github.com/kyverno/kyverno/issues/2920#issuecomment-1006732087
cc: @realshuting
=> fix: removing spaces to make CI job work

.github/workflows/image.yaml
`signing` step should pass after adding these permissions
ref: https://github.com/kyverno/kyverno/runs/4729805789?check_suite_focus=true#step:10:14
@mattmoor can you please help in reviewing this pr? Thanks
=> adding proper permissions in github action jobs

.github/PULL_REQUEST_TEMPLATE.md
The current PR template doesn't render the checkboxes by default as unticked and instead as square brackets. This change
allows contributors to use the rendered UI to check boxes instead of manually fixing markdown.
Rendered template at https://github.com/samj1912/kyverno/blob/patch-1/.github/PULL_REQUEST_TEMPLATE.md
- [] I have …
=> Fix the PR template checkboxes to render empty instead of brackets

.github/workflows/image.yaml, .github/workflows/release.yaml, Makefile
I believe I've made all the required changes, which were made for image workflow mentioned in this issue https://github.com/kyverno/kyverno/issues/2920
@realshuting please verify these changes once with previous ones (made for #2920 ), as we won't be able to check these just after the merge and it may affect the next release of kyverno images. 
Thanks
=> Fix: CI job to release images

cmd/initContainer/main.go, pkg/tls/certRenewer.go, pkg/tls/reader.go
Closes #2955 
/milestone 1.5.4
/kind bug
Check for Deployment UID annotation in initContainer
**Clean Install**
1. Kyverno installs and a single ReplicaSet is observed.
2. The policy [disallow_latest_tag.yaml](https://github.com/kyverno/kyverno/blob/main/test/best_practices/disallow_latest_tag.yaml) works as expected.
**Upgrade Test**
1. Upgrade from 1.5.2 to the latest changes doesn't create intermediate pods and only two ReplicaSets are observed.
2. The policy [disallow_latest_tag.yaml](https://github.com/kyverno/kyverno/blob/main/test/best_practices/disallow_latest_tag.yaml) works as expected.
=> Added TLS annotation check in the initContainer

pkg/kyverno/test/test_command.go
Signed-off-by: sloorush <aarush.bhatt@gmail.com>
- closes #2893 
--
--
Add a test summary for `kyverno test` that logs a test summary like:
```
Test Summary: 5 tests passed and 0 tests failed
```
Not very sure on what kind of PR will this come in, same for milestone
=> kyverno/test: print test summary of kyverno test results

pkg/cosign/cosign.go
https://github.com/kyverno/kyverno/issues/2972
1.6
/kind bug
- check for issuer and subject only if they are specified in the policy
- if issuer and/or subject are in the policy, but not in the payload, return an error
- fix log levels
Test with image signed with a static key
=> check for issuer and subject only when declared. fix log levels.

.github/PULL_REQUEST_TEMPLATE.md
n/a
1.6
/kind cleanup
Move `[ ] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.` to the 2nd item in the PR checklist.
N/A
=> move guidelines up

.github/workflows/build.yaml, .github/workflows/e2e.yaml, .github/workflows/fossa.yml, .github/workflows/helm-release.yaml, .github/workflows/helm-test.yaml
Fixes #2949 
#2992
This PR adds the remaining permissions to all workflows in order to get a perfect score on the OSSF scorecard. These workflows were already using read-only permissions but now any new jobs added that require a `write` permission will have to state so explicitly. 
CC: @JimBugwadia 
More testing done with local docker image
```bash
docker run -e GITHUB_AUTH_TOKEN=token gcr.io/openssf/scorecard:stable --checks Token-Permissions --show-details --local . --format json
```
=> Add top level permissions to remaining github workflows

cmd/kyverno/main.go
Cherry-pick the fix for https://github.com/kyverno/kyverno/issues/2951.
=> Add the new flag webhookRegistrationTimeout

CODEOWNERS
=>  Add CODEOWNER

CODEOWNERS, OWNERS.md
cc: @JimBugwadia as requested.
=> Add samj1912 to codeowners

.github/workflows/image.yaml
All of the jobs in this workflow use the same set of permissions and this workflow is only run on pushes to main. Adding the appropriate permissions to read repository contents, publish packages and ID token for cosign.
=> Fix permissions for image publish workflows

.github/workflows/reuse.yaml
ref: https://github.com/kyverno/kyverno/pull/3021#issuecomment-1016382881
https://github.com/kyverno/kyverno/pull/2979/files
cc: @realshuting
=> fix: buildx-action version

CHANGELOG.md, charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, definitions/install.yaml, definitions/release/install.yaml, definitions/release/kustomization.yaml, definitions/release/labels.yaml
=> Release v1.5.5-rc1

charts/kyverno/README.md
=> clarify naming patterns for Kyverno ClusterRoles/ClusterRoleBindings 

charts/kyverno/README.md
=> clarify naming patterns for Kyverno ClusterRoles/ClusterRoleBindings

charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, config/install.yaml, config/release/install.yaml, config/release/kustomization.yaml, config/release/labels.yaml
=> Release v1.6.0-rc1

.github/workflows/build.yaml, .github/workflows/helm-release.yaml, .github/workflows/helm-test.yaml, .github/workflows/image.yaml, .github/workflows/release.yaml
https://github.com/kyverno/kyverno/pull/2979#issuecomment-1019685249.
/1.6.0
/bug
=> Update workflow configurations to fix CI failure

CHANGELOG.md, charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, definitions/install.yaml, definitions/release/install.yaml, definitions/release/kustomization.yaml, definitions/release/labels.yaml, pkg/policy/report.go
- Closes https://github.com/kyverno/kyverno/issues/3065.
- Release v1.5.6.
=> Release 1.5.6

pkg/webhooks/common.go, test/cli/test-fail/invalid-ns/kyverno-test.yaml, test/cli/test-fail/invalid-ns/policy.yaml, test/cli/test-fail/invalid-ns/resources.yaml
backports the fix from #2990 to release 1.5
=> cherry pick #2990 for 1.5

CHANGELOG.md, charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, definitions/install.yaml, definitions/release/install.yaml, definitions/release/kustomization.yaml, definitions/release/labels.yaml
=> Release v1.5.7

pkg/engine/mutation.go, test/cli/test-mutate/foreach/cumulativePatch/kyverno-test.yaml, test/cli/test-mutate/foreach/cumulativePatch/patched.yaml, test/cli/test-mutate/foreach/cumulativePatch/policies.yaml, test/cli/test-mutate/foreach/cumulativePatch/resources.yaml
Fixes #3078
1.6.0
/kind bug
Apply patches on patchedResource (cumulatively)
added test in test\cli\test-mutate\foreach\cumulativePatch\
=> apply patches cumulatively

pkg/engine/mutation.go, pkg/kyverno/common/common.go, test/cli/test-mutate/foreach/cumulativePatch/kyverno-test.yaml, test/cli/test-mutate/foreach/cumulativePatch/patched.yaml, test/cli/test-mutate/foreach/cumulativePatch/policies.yaml, test/cli/test-mutate/foreach/cumulativePatch/resources.yaml, test/cli/test/any-namespaceSelector/policy.yaml, test/cli/test/any-namespaceSelector/resource.yaml, test/cli/test/any-namespaceSelector/test.yaml, test/cli/test/any-namespaceSelector/value.yaml
=> Cherry-pick fixes for 1.6.0.

charts/kyverno/templates/deployment.yaml
Closes #3073 
/kind bug
- Add KYVERNO_DEPLOYMENT environment variable to the initContainer manifest
1. On a fresh cluster, run `helm upgrade -i -n kyverno --create-namespace kyverno-dev chart`
2. Watch the kyverno-pre logs on the pod  `kubectl logs --follow -l=app=kyverno -n kyverno -c kyverno-pre`
3. Kyverno starts properly
=> Add KYVERNO_DEPLOYMENT to initContainer

CHANGELOG.md, charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, definitions/install.yaml, definitions/release/install.yaml, definitions/release/kustomization.yaml, definitions/release/labels.yaml, pkg/kyverno/common/common.go, test/cli/test/any-namespaceSelector/policy.yaml, test/cli/test/any-namespaceSelector/resource.yaml, test/cli/test/any-namespaceSelector/test.yaml, test/cli/test/any-namespaceSelector/value.yaml
Cherry-pick commits and release 1.5.8.
cc @treydock
=> Release 1.5.8

go.mod, go.sum, pkg/cosign/cosign.go, pkg/engine/jsonContext.go, pkg/registryclient/client.go
Related PRs - 
#3096 
#3088 
/kind bug
=> Cherry-pick GGCR mem leak fixes for Kyverno 1.6

pkg/engine/context/imageutils.go
Signed-off-by: Abhinav Sinha <abhinav@nirmata.com>
Cherry pick #3143
=> Cherry pick #3143

charts/kyverno/templates/clusterrole.yaml
`/milestone 1.6.0`.
> /kind bug
As part of tighten and clarify Kyverno roles and permissions, PR #2799 we missed to update the charts
templates events clusterroles with patch verb.
=> add missing patch verbs in event clusterrole

.github/workflows/e2e.yaml, Makefile, charts/kyverno/values.yaml, scripts/create-e2e-infrastruture.sh
https://github.com/kyverno/kyverno/pull/3126#issuecomment-1028570092
=> Update dev image tag in Make targets

pkg/policy/validate.go, test/cli/test/multiple_condition_keys/kyverno-test.yaml, test/cli/test/multiple_condition_keys/policy.yaml, test/cli/test/multiple_condition_keys/resources.yaml
closes : https://github.com/kyverno/kyverno/issues/3147
/kind bug
```
metadata:
name: drop-cap-net-raw
spec:
rules:
- name: drop-cap-net-raw
match:
resources:
kinds:
- Pod
validate:
deny:
conditions:
any:
- key: 
- "30"
- "40"
operator: AnyIn
value: 10-100
```
```
apiVersion: v1
kind: Pod
metadata:
name: test
spec:
containers:
- name: test
image: defdasdabian:923
```
Result:
```
Applying 1 policy to 1 resource... 
(Total number of result count may vary as the policy is mutated by Kyverno. To check the mutated policy please try with log level 5)
policy drop-cap-net-raw -> resource default/Pod/test failed: 
1. drop-cap-net-raw: …
```
=> Fix panic for provides a set to the key of a precondition and deny condition 

Makefile, charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, charts/kyverno/values.yaml, config/install.yaml, config/release/install.yaml, config/release/kustomization.yaml, config/release/labels.yaml, pkg/engine/jmespath/functions.go, pkg/engine/jmespath/new.go, pkg/kyverno/jp/jp_command.go, pkg/kyverno/main.go
=> Cherry-pick commits and release v1.6.0-rc4

charts/kyverno/templates/NOTES.txt
Co-authored-by: Erkan Zileli <erkan.zileli@trendyol.com>
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>
Fixes #3184 
/kind bug
=> feat: fix app version in NOTES.txt

charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, config/install.yaml, config/release/install.yaml, config/release/kustomization.yaml, config/release/labels.yaml
=> Release v1.6.0

go.mod, go.sum, pkg/cosign/cosign.go, pkg/engine/imageVerify.go, pkg/kyverno/test/test_command.go
cherry-pick:
https://github.com/kyverno/kyverno/commit/bd1a145678166dbf9f81cc910e978bc03b58996c
https://github.com/kyverno/kyverno/commit/14111aaa057dfde8be442b0e78dc2a90581ea5de
=> Cherry pick fixes 

pkg/engine/context/imageutils.go, pkg/engine/context/imageutils_test.go
cherry picks https://github.com/kyverno/kyverno/commit/5a541567decdd6f5a9a662ddc3a1b4515d40a753
=> Cherry pick fixes for 1.6.1

charts/kyverno/templates/aggregateroles.yaml, charts/kyverno/templates/crds.yaml, config/install.yaml, config/install_debug.yaml, config/k8s-resource/aggregateroles.yaml, config/release/install.yaml
Closes https://github.com/kyverno/kyverno/issues/3235.
This PR:
- adds aggregated role for generaterequest
- also syncs latest changes to `release/install.yaml` in `main`
1.7.0
/enhancement
=> Add aggregated role for generaterequest

pkg/webhookconfig/registration.go
Cherry-pick https://github.com/kyverno/kyverno/pull/3237.
=> Cherry-pick #3237 to 1.6.1

pkg/engine/context/context.go, pkg/engine/validation.go, pkg/engine/validation_test.go
* fix validation check on UPDATE
* prevent policy bypass using preconditions
* separate replace
* add error handling
Fixes https://github.com/kyverno/kyverno/issues/3253.
1.6.1
/kind bug
=> cherry-pick: Fix old object validation check (#3248) 

README.md
n/a
n/a
/kind feature
Add OpenSSF  Best Practices Badge
=> Add openssf badge

pkg/engine/variables/operator/notequal.go, test/cli/test/foreach-preconditions/kyverno-test.yaml, test/cli/test/foreach-preconditions/policies.yaml, test/cli/test/foreach-preconditions/resources.yaml
Cherry-pick https://github.com/kyverno/kyverno/pull/3228 and https://github.com/kyverno/kyverno/issues/3131.
=> Cherry-pick   Fix foreach validations precondition issue (#3228) to 1.6.1 

api/kyverno/v1/utils.go
Signed-off-by: Abhishek Choudhary <shreemaan.abhishek@gmail.com>
N/A
N/A
/kind cleanup
There was a block of _commented out_ code which has been cleaned up.
N/A
N/A
=> Cleanup commented out lines of code

.github/workflows/helm-release.yaml
Fixes #3267
/kind bug
Update the Github Action used to release Helm charts.  This ensures creation timestamp in the Helm repo is preserved for older releases.
Would be good to get this into 1.6 branch too so that future Helm releases from that branch also make use of this improved repo handling.
=> Fix Helm releasing to preserve creation timestamps

charts/kyverno/templates/deployment.yaml, config/install.yaml, config/manifest/deployment.yaml, config/release/install.yaml
=> Cherry-pick #3274 to 1.6.1

.github/workflows/helm-release.yaml, pkg/utils/util.go, pkg/webhooks/server.go, test/cli/test/secret/kyverno-test.yaml, test/cli/test/secret/patched-resource.yaml, test/cli/test/secret/patched-resource1.yaml, test/cli/test/secret/policy.yaml, test/cli/test/secret/resources.yaml, test/cli/test/secret/resources2.yaml
closes : https://github.com/kyverno/kyverno/issues/2897
/kind bug
1. Create a Policy
````yaml
metadata:
name: add-maintainer
spec:
rules:
- match:
any:
- resources:
kinds:
- Secret
mutate:
metadata:
labels:
+(example.com/maintainer): 'john.doe'
name: add-maintainer
````
2. Create a secret with an empty value and apply it
````yaml
apiVersion: v1
data:
foo: AAAA
bar: ""
kind: Secret
metadata:
name: example
labels:
example.com/maintainer: "jane.doe"
type: Opaque
````
Edit the secret and add a new key (for example: `baz: "BBBB"`).
````yaml
apiVersion: v1
data:
foo: AAAA
bar: ""
baz: BBBB
kind: …
```
=> Fix label mutation while updating the secret

pkg/utils/util.go, pkg/webhooks/server.go, test/cli/test/secret/kyverno-test.yaml, test/cli/test/secret/patched-resource.yaml, test/cli/test/secret/patched-resource1.yaml, test/cli/test/secret/policy.yaml, test/cli/test/secret/resources.yaml, test/cli/test/secret/resources2.yaml
Cherry-pick PR https://github.com/kyverno/kyverno/pull/3273 for issue https://github.com/kyverno/kyverno/issues/2897
=> Cherry-pick #3273 to 1.6.1

.goreleaser.yml, .krew.yaml, Makefile
Signed-off-by: skuethe <56306041+skuethe@users.noreply.github.com>
Closes #3276 
/kind feature
-
-
=> feat: add `linux/s390x` builds

.github/workflows/image-build.yaml, .github/workflows/reuse.yaml
Signed-off-by: Naman Lakhwani <namanlakhwani@gmail.com>
fixes #3280 
/kind bug
updating the trivy scanning step as mentioned in the instructions given here: https://github.com/aquasecurity/trivy-action#using-trivy-to-scan-your-git-repo
verified here: https://github.com/Namanl2001/kyverno/runs/5294213016?check_suite_focus=true#step:11:15
=> update trivy scanning step in GH_workflows

.github/workflows/image-build.yaml, .github/workflows/reuse.yaml, charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, config/install.yaml, config/release/install.yaml, config/release/kustomization.yaml, config/release/labels.yaml
=> Release v1.6.1-rc1

pkg/kyverno/test/git.go
Fixes #3287 
/kind feature
This change only fetches the latest contents of a given git branch instead of cloning the entire history improving the git clone speeds during a test.
=> Shallow clone git repositories for kyverno test command

.github/workflows/e2e.yaml, Makefile, scripts/create-e2e-infrastruture.sh, test/e2e/common/common.go, test/e2e/mutate/config.go, test/e2e/mutate/mutate_test.go, test/e2e/mutate/resources.go
Fixes #3099 
/kind cleanup
This change adds the ability to run E2E tests on all of our supported kubernetes versions per https://kyverno.io/docs/installation/#compatibility-matrix
=> Run E2E tests on all supported k8s versions

go.mod, go.sum, pkg/policy/validate.go, pkg/policy/validate_test.go
=> validate and block policy based on the matched kind cache (#3283)

pkg/kyverno/common/common.go
a simple typo fix.
Signed-off-by: Emin Aktas <emin.aktas@trendyol.com>
=> fix: fix namespace typo

.github/workflows/image.yaml, .github/workflows/release.yaml, .github/workflows/reuse.yaml
ref: https://github.com/kyverno/kyverno/issues/3254#issuecomment-1050102521
=> [release-1.6]: updated image and releaser GH_workflows

.github/workflows/release.yaml
this pr aims to solve the issue we're getting during the last release: https://github.com/kyverno/kyverno/runs/4923596220?check_suite_focus=true#step:9:189
the changes in this pr are verified here: https://github.com/Namanl2001/kyverno/runs/5306816365?check_suite_focus=true
=> fixing release workflow

.github/workflows/reuse.yaml
ref: https://github.com/kyverno/kyverno/pull/3305#pullrequestreview-893379943
=> Fix workflow using regex in `main`

.github/workflows/reuse.yaml, Makefile
seems like wildcards are not supported in the if statements of GH actions, we'll have to use regex for that purpose 
verified here: https://github.com/Namanl2001/kyverno/runs/5330486496?check_suite_focus=true#step:17:1
=> Fix workflow using regex

charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/README.md.gotmpl, charts/kyverno/values.yaml
This PR adds helm-docs generation for kyverno helm chart.
See https://github.com/eddycharly/kyverno/blob/helm-docs-2/charts/kyverno/README.md.
=> feat: gen kyverno helm chart docs

charts/kyverno-policies/Chart.yaml
This PR drops helm v2 support.
=> chore: drop helm v2

charts/kyverno/README.md, charts/kyverno/templates/_helpers.tpl, charts/kyverno/templates/deployment.yaml, charts/kyverno/values.yaml
This PR fixes default seccomp profile so that it passes the restricted PSS profile policies.
=> fix: seccomp profile

.github/workflows/image.yaml, .github/workflows/reuse.yaml, Makefile
=> Cherry-pick #3317 & #3319

.github/workflows/reuse.yaml
verified here: https://github.com/Namanl2001/kyverno/runs/5376208642?check_suite_focus=true
=> add separate step for digest

.github/workflows/image.yaml, .github/workflows/reuse.yaml, Makefile
We were missing a check for digest, when there is a merge on the release branch, added that in this pr. Thanks!
=> fetching proper digest for release images

Makefile
gets tags across all branches, not just the current branch
=> fix release tag command

.github/workflows/reuse.yaml, Makefile
=> fetch tag across all branches instead of current branch

.github/workflows/tests.yaml, Makefile
This PR verifies codegen is up to date  in CI.
=> chore: verify codegen in CI

ADOPTERS.md
=> Add Bloomberg to adopters

pkg/policy/validate.go, test/cli/test/any-all-wildcard/kyverno-test.yaml, test/cli/test/any-all-wildcard/policy.yaml, test/cli/test/any-all-wildcard/resource.yaml
Cherry-pick PR https://github.com/kyverno/kyverno/pull/3352 for issue https://github.com/kyverno/kyverno/issues/https://github.com/kyverno/kyverno/issues/3340
=> Cherry-pick #3352 to v1.6.0

pkg/kyverno/common/common.go, test/cli/test/mixed/kyverno-test.yaml, test/cli/test/mixed/patched-resource.yaml, test/cli/test/mixed/patched-resource1.yaml, test/cli/test/mixed/policy.yaml, test/cli/test/mixed/resource.yaml
Co-authored-by: Vyankatesh Kudtarkar <vyankateshkd@gmail.com>
Cherry-pick #2954 to 1.6.2.
=> Cherry-pick #2954 to 1.6.2

charts/kyverno/README.md, charts/kyverno/templates/configmap.yaml, charts/kyverno/values.yaml
This PR fixes incorrect resource filters with using helm and deploying to a custom namespace.
=> fix: incorrect resource filters with helm and custom namespace

charts/kyverno/templates/clusterrole.yaml, config/install.yaml, config/k8s-resource/clusterroles.yaml, config/release/install.yaml
- Update clusterrole.yaml
- Fix apigroup for resourcequota and limitrange
cherrypick: #3330 
Signed-off-by: Christophe Gasmi <rekcah78@gmail.com>
=> Update generate clusterrole (#3336)

config/install.yaml, config/install_debug.yaml, config/manifest/deployment.yaml
Signed-off-by: Naman Lakhwani <namanlakhwani@gmail.com>
fixes #3266 
/kind bug
Failing to provide a writable $HOME can cause TUF client initialization to panic
policy
```yaml
metadata:
name: testy3-images-signed
spec:
webhookTimeoutSeconds: 5
rules:
- name: testy3-images-signed
match:
resources:
kinds:
- Pod
verifyImages:
- image: "quay.io/rob_best/testy3:*"
subject: "https://github.com/ribbybibby/testy3/.github/workflows/release.yaml@refs/heads/main"
issuer: "https://token.actions.githubusercontent.com" 
```
resource
```yaml
metadata:
name: test 
spec:
replicas: 1
selector:
matchLabels:
app: test
template:
metadata: …
```
=> adding emptyDir vol for keyless signing

config/install.yaml, config/install_debug.yaml, config/manifest/deployment.yaml
=> Cherry pick/3366

OWNERS.md
Add @eddycharly to the OWNERS.md.
Congratulations @eddycharly 🎉
=> Add new contributor

Makefile, docs/crd/v1/index.html, docs/crd/v1alpha1/index.html, docs/crd/v1alpha2/index.html
This PR fixes api reference docs generation.
=> fix: generate api reference docs

.github/workflows/codecov.yaml, Makefile, README.md
Signed-off-by: Abhinav Sinha <abhinav@nirmata.com>
Slack discussion: https://kubernetes.slack.com/archives/C032MM2CH7X/p1647088223256929
`/milestone 1.6.2`
`/kind feature`
Upload and generate code coverage reports through [Codecov](https://codecov.io) for every `push` or `pull_request` event on `main` and `release*` branches.
=> Add `codecov` to CI

pkg/policy/existing.go, pkg/policy/validate_test.go
Cherry-pick PR https://github.com/kyverno/kyverno/pull/3384 for issue https://github.com/kyverno/kyverno/issues/3349
=> Cherry-pick #3384 to v1.6.2 

Makefile, pkg/engine/jsonContext.go, pkg/kyverno/apply/apply_command.go, pkg/kyverno/apply/apply_command_test.go, pkg/kyverno/store/store.go, pkg/kyverno/test/test_command.go, pkg/registryclient/client.go, test/cli/registry/image-example.yaml, test/cli/registry/kyverno-test.yaml, test/cli/registry/resources.yaml, test/cli/test-mutate/kyverno-test.yaml
Fixes #3395 
/kind feature
Adds a `--registry` flag to test and apply commands to actually reach out to the container registries.
=> Add a registry flag to allow direct access to container registries in the CLI

Makefile
This PR adds a `make help` target.
=> chore: add make help target

api/kyverno/v1/common_types.go, api/kyverno/v1/user_info_test.go, api/kyverno/v1/user_info_types.go, pkg/policy/validate.go, pkg/policy/validate_test.go
This PR refactors `UserInfo` validation.
=> refactor: UserInfo validation

pkg/webhookconfig/resource.go
Cherry-pick https://github.com/kyverno/kyverno/pull/3417 to 1.6.2.
=> Cherry-pick #3417 to 1.6.2

.github/ISSUE_TEMPLATE/bug-cli.yaml, .github/ISSUE_TEMPLATE/bug-other.yaml, .github/ISSUE_TEMPLATE/bug-webhook.yaml, .github/ISSUE_TEMPLATE/feature.yaml, .github/PULL_REQUEST_TEMPLATE.md
/kind cleanup
* Adds new issue template called "other" which is a catch-all for issues not fitting into other templates.
* Adds a new `triage` label to all new issues signaling to other maintainers the labels should be curated appropriately.
* Updates check boxes regarding testing
=> PR and issue template updates per contributors' meetings

charts/kyverno/templates/role.yaml, charts/kyverno/templates/rolebinding.yaml
Signed-off-by: Dominik Ruf <dominikruf@gmail.com>
Fixes #3389 discussed with @treydock
/kind bug
- [x ] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.
=> add missing namespace to role and rolebinding (#3389)

pkg/kyverno/common/common.go
Cherry-pick PR https://github.com/kyverno/kyverno/pull/3436 for issue https://github.com/kyverno/kyverno/issues/3435
=> cherrypick 3436 to v1.6.2 

pkg/common/common.go, pkg/engine/utils.go, pkg/policy/existing.go, pkg/policy/validate.go, pkg/utils/util.go, pkg/webhookconfig/configmanager.go, test/cli/test/depecated_apis/kyverno-test.yaml, test/cli/test/depecated_apis/policy.yaml, test/cli/test/depecated_apis/resources.yaml
Cherry-pick PR https://github.com/kyverno/kyverno/pull/3439 for issue https://github.com/kyverno/kyverno/issues/https://github.com/kyverno/kyverno/issues/3261
=> cherrypick 3439 to v1.6.2

pkg/webhooks/generation.go, pkg/webhooks/server.go
=> fix: use RWMutex lock while concurrent read/write (#3462)

pkg/webhookconfig/monitor.go, pkg/webhookconfig/registration.go, pkg/webhookconfig/status.go
=> Cherry picks add-lease PR

charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, config/install.yaml, config/release/install.yaml, config/release/kustomization.yaml, config/release/labels.yaml
=> Release 1.6.2-rc1

pkg/webhooks/generation.go, pkg/webhooks/server.go
/milestone 1.7.0.
Refer: https://github.com/kyverno/kyverno/pull/3467
=> use mutex as field instead of embedded

pkg/webhooks/generation.go, pkg/webhooks/server.go
=> use mutex as field instead of embedded (#3480)

charts/kyverno/templates/role.yaml, charts/kyverno/templates/rolebinding.yaml
Cherry pick #3429 into main branch
> /kind bug
=> add missing namespace to role and rolebinding (#3389) (#3429)

api/kyverno/v1/clusterpolicy_types.go, api/kyverno/v1/image_verification_types.go, api/kyverno/v1/match_resources_types.go, api/kyverno/v1/policy_types.go, api/kyverno/v1/resource_description_types.go, api/kyverno/v1/rule_types.go, api/kyverno/v1/spec_types.go, api/kyverno/v1/user_info_types.go, api/kyverno/v1/utils.go
This PR simplifies validation methods by using named return.
=> chore: simplify validation with named return

charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/ci/hooks-values.yaml, charts/kyverno/templates/crds.yaml, charts/kyverno/templates/helm-pre-delete-hook.yaml, charts/kyverno/values.yaml, config/install.yaml, config/release/install.yaml, config/release/kustomization.yaml, config/release/labels.yaml
=> Cherry-pick #3111 and release v1.6.2-rc3

api/kyverno/v1/clusterpolicy_types.go, api/kyverno/v1/policy_interface.go, api/kyverno/v1/policy_test.go, api/kyverno/v1/policy_types.go, pkg/autogen/autogen_test.go, pkg/kyverno/apply/apply_command.go, pkg/kyverno/common/common.go, pkg/kyverno/common/fetch.go, pkg/kyverno/test/test_command.go, pkg/kyverno/validate/command.go, pkg/openapi/validation.go, pkg/openapi/validation_test.go, pkg/policy/apply.go, pkg/policy/background.go, pkg/policy/common.go, pkg/policy/existing.go, pkg/policy/policy_controller.go, pkg/policy/report.go, pkg/policy/validate.go, pkg/policymutation/policymutation.go, pkg/utils/loadpolicy.go, pkg/webhooks/policymutation_test.go
This PR makes use of policy interface in many places.
=> refactor: use more policy interface

pkg/policy/report.go
This PR reduces dependency to ns lister in policy controller.
=> fix: reduce dependency to ns lister

charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml, charts/kyverno/templates/crds.yaml, config/install.yaml, config/release/install.yaml, config/release/kustomization.yaml, config/release/labels.yaml
=> Release v1.6.2

.github/workflows/reuse.yaml
/kind cleanup
use github repo env `{{ github.repository_owner }}` instead of hardcoded repo name
=> fix: use github repo env instead of hardcoded repo name

pkg/autogen/autogen_test.go, pkg/policy/apply.go, pkg/policymutation/policymutation.go, pkg/utils/json/utils.go
This PR separates json utils into a dedicated sub package.
=> refactor: separate json utils package

cmd/initContainer/main.go, pkg/config/config.go, pkg/config/metricsconfig.go, pkg/utils/os/env.go
This PR adds an os utils sub package.
=> refactor: add os utils sub package

pkg/autogen/rule.go, pkg/autogen/utils.go, pkg/common/common.go, pkg/openapi/validation.go, pkg/policy/existing.go, pkg/policy/validate.go, pkg/policycache/policy_cache.go, pkg/policycache/policy_map.go, pkg/policymutation/policymutation.go, pkg/resourcecache/resourcecache.go, pkg/utils/kube/kind.go, pkg/utils/util.go, pkg/webhookconfig/configmanager.go
This PR creates a kube utils sub package.
=> refactor: separate kube utils package

pkg/webhooks/annotations.go
This PR fixes json path annotation path.
=> fix: annotation path

pkg/engine/response/response.go, pkg/webhooks/common.go
This PR refactor `checkEngineResponse` in webhooks.
=> refactor: checkEngineResponse in webhooks

pkg/utils/admission/utils.go, pkg/utils/engine/response.go, pkg/webhooks/common.go, pkg/webhooks/mutation.go, pkg/webhooks/validation.go, pkg/webhooks/verify_images.go
This PR adds an engine utils sub package.
=> refactor: add engine utils sub package

Makefile
This PR adds some `make help` comments.
=> chore: add some make help comments

MAINTAINERS.md
n/a
n/a
/kind feature
Add @eddycharly as a Kyverno maintainer! 
n/a
=> add @eddycharly as a maintainer!

config/install.yaml, config/manifest/deployment.yaml
n/a
1.7
/kind cleanup
Change the default imagePullPolicy to `Always` to make sure the latest latest is pulled.
n/a
=> update image pull policy for YAML install which uses :latest

pkg/engine/jmespath/functions.go
Signed-off-by: tend2infinity <somu12.ss@gmail.coom>
Closes Issue #3564
/kind bug
Added a returnType for the regex_match command in kyverno jp -l comand output
Terminal Output:
`regex_match(string, string|number) bool
`
=> added returnType for regexMatch in kyverno jp output

pkg/userinfo/roleRef.go, pkg/userinfo/roleRef_test.go
This PR removes some dead code.
=> chore: remove dead code

.github/workflows/image-build.yaml, .github/workflows/reuse.yaml, cmd/cli/kubectl-kyverno/Dockerfile, cmd/initContainer/Dockerfile, cmd/kyverno/Dockerfile
Signed-off-by: Shubham Gupta <shubham.gupta2956@gmail.com>
#2617 
This PR adds hash of dependencies instead of mutable versions
=> Update hash of dependencies instead of mutable version

pkg/background/request_process.go, pkg/background/update_request_controller.go, pkg/engine/background.go, pkg/engine/mutation.go, pkg/webhookconfig/configmanager.go, pkg/webhooks/generation.go, pkg/webhooks/handlers.go, pkg/webhooks/handlers/admission.go, pkg/webhooks/server.go, pkg/webhooks/updaterequest.go, pkg/webhooks/updaterequest/generator.go
This PR sync the changes to the shared dev branch.
=> feat: mutate existing - generates UR for admission requests

charts/kyverno/README.md, charts/kyverno/ci/imagePullSecrets-values.yaml, charts/kyverno/templates/_helpers.tpl, charts/kyverno/templates/deployment.yaml, charts/kyverno/templates/imagepullsecret.yaml, charts/kyverno/values.yaml
Brought up on Slack
https://kubernetes.slack.com/archives/CLGR9BJU9/p1650304196171389
/kind feature
Allow defining the image pull secrets passed to Kyverno `--imagePullSecrets`. This can be used with imageData or image verify policies.
Added CI testing file for Helm with examples.
Once merged I'll open a back port pull request for Kyverno 1.6.x
=> Allow defining imagePullSecrets

pkg/policy/policy_controller.go
=> replace with UR in policy controller generate rules

pkg/policycache/informer.go, pkg/policycache/policy_cache.go, pkg/policycache/policy_map.go
closes : https://github.com/kyverno/kyverno/issues/3626
/kind bug
=> Fix race condition in pCache

cmd/kyverno/main.go, pkg/webhooks/generate/generate.go
Closes: https://github.com/kyverno/kyverno/issues/2447
cleanup the redundant Run() methods no-longer required
=> refact: remove unused Run function from generate

api/kyverno/v1/zz_generated.deepcopy.go, pkg/engine/context/context.go, pkg/engine/imageVerify.go, pkg/utils/image/infos.go, pkg/utils/image/infos_test.go, pkg/utils/kube/image.go, pkg/utils/kube/image_test.go
This PR refactors image utils.
It removes the json pointer from the image utils package and moves it in the kube utils package.
=> refactor: image utils

charts/kyverno/README.md, charts/kyverno/ci/imagePullSecrets-values.yaml, charts/kyverno/templates/_helpers.tpl, charts/kyverno/templates/deployment.yaml, charts/kyverno/templates/imagepullsecret.yaml, charts/kyverno/values.yaml
This is back port to 1.6 of #3633
/milestone 1.6.3
/kind feature
Better support for defining imagePullSecrets for both imageData and image verify policies.
Helm CI values added to validate.
=> [1.6] Allow defining imagePullSecrets

charts/kyverno-policies/Chart.yaml, charts/kyverno/Chart.yaml
This PR adds a couple of artifacthub annotations.
=> chore: add artifacthub operator and prerelease annotations

charts/kyverno-policies/Chart.yaml, charts/kyverno-policies/README.md, charts/kyverno-policies/ci/test-preconditions-values.yaml, charts/kyverno-policies/templates/restricted/disallow-capabilities-strict.yaml, charts/kyverno-policies/values.yaml
Relates to #3656 but does not solve the underlying issue, just avoids it for now.
I will do cherry-pick into main branch once merged. Wanted to get this released to avoid the issues reported in #3656 since the change was released.
=> Add DELETE precondition back

cmd/cli/kubectl-kyverno/Dockerfile, cmd/initContainer/Dockerfile, cmd/kyverno/Dockerfile
Closes https://github.com/kyverno/kyverno/issues/3670.
=> Bump to Go 1.17.9

pkg/engine/validation.go, test/cli/test/limit-configmap-for-sa/kyverno-test.yaml, test/cli/test/limit-configmap-for-sa/limit_configmap_for_sa.yaml, test/cli/test/limit-configmap-for-sa/resource.yaml, test/cli/test/limit-configmap-for-sa/variables.yaml, test/cli/test/restrict_ingress_host/kyverno-test.yaml, test/cli/test/restrict_ingress_host/resource.yaml, test/cli/test/restrict_ingress_host/restrict_ingress_host.yaml, test/cli/test/restrict_ingress_host/values.yaml
closes : https://github.com/kyverno/kyverno/issues/3604
Added test cases
```
Executing limit-configmap-for-sa...
applying 1 policy to 2 resources... 
│───│────────────────────────│──────────────────────────────────│───────────────────────────────────────────│────────│
│ # │ POLICY                 │ RULE                             │ RESOURCE                                  │ RESULT │
│───│────────────────────────│──────────────────────────────────│───────────────────────────────────────────│────────│
│ 1 │ limit-configmap-for-sa │ limit-configmap-for-sa-developer │ default/ConfigMap/any-configmap-name-good │ Pass   │
│ 2 │ limit-configmap-for-sa │ limit-configmap-for-sa-developer │ default/ConfigMap/any-configmap-name-bad …
```
=> Fix test cli CI failures from main

CHANGELOG.md, cmd/kyverno/main.go
This PR removes deprecated flags.
=> feat: remove deprecated flags

cmd/initContainer/main.go, cmd/kyverno/main.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/dynamicconfig.go, pkg/config/log.go, pkg/config/metricsconfig.go
This PR refactors `config` package logger.
=> refactor: config package logger

api/kyverno/v1/common_types.go, api/kyverno/v1/zz_generated.deepcopy.go, docs/crd/v1/index.html, pkg/autogen/rule.go, pkg/engine/mutate/mutation.go, pkg/engine/mutation.go, pkg/engine/validation.go, pkg/policy/validate/validate.go
This PR removes some api unnecessary pointers.
=> refactor: remove some api unnecessary pointers

api/kyverno/v1beta1/constants.go, pkg/background/generate/cleanup/controller.go, pkg/background/generate/generate.go, pkg/compatibility/add_labels.go, pkg/policy/policy_controller.go, pkg/webhooks/generate/generate.go, pkg/webhooks/generation.go, pkg/webhooks/updaterequest/generator.go
This PR list URs for the particular policy on its events.
=> Optimize UR listing on policy events

api/kyverno/v1/common_types.go, api/kyverno/v1/policy_status.go, api/kyverno/v1/zz_generated.deepcopy.go, charts/kyverno/templates/crds.yaml, config/crds/kyverno.io_clusterpolicies.yaml, config/crds/kyverno.io_policies.yaml, config/install.yaml, config/install_debug.yaml, docs/crd/v1/index.html, pkg/webhookconfig/configmanager.go
This PR removes the supported stanza from autogen status.
=> fix: remove supported from autogen status

pkg/autogen/autogen.go, pkg/autogen/autogen_test.go, pkg/autogen/log.go, pkg/autogen/rule.go, pkg/policy/policy_controller.go, pkg/policymutation/policymutation.go, pkg/webhookconfig/configmanager.go
This PR refactors autogen package logger.
=> refactor: autogen package logger

.github/workflows/pr-update.yaml
See https://github.com/adRise/update-pr-branch for more details
=> Auto-update PRs which are enabled for auto-merging

cmd/cli/kubectl-kyverno/apply/apply_command.go, cmd/initContainer/main.go, cmd/kyverno/main.go, pkg/dclient/client.go, pkg/dclient/discovery.go, pkg/dclient/log.go, pkg/dclient/utils.go
This PR refactors `dclient` package logger.
=> refactor: dclient package logger

pkg/policycache/informer.go, pkg/policyreport/reportcontroller.go, pkg/utils/kube/tombstone.go
This PR adds missing tombstone calls.
=> fix: add missing tombstone calls

CHANGELOG.md, cmd/kyverno/main.go, config/install.yaml, config/manifest/deployment.yaml, config/release/install.yaml, pkg/config/dynamicconfig.go
This PR removes config related flags.
=> chore: remove config flags

pkg/event/events.go
Signed-off-by: Frank Jogeleit <frank.jogeleit@lovoo.com>
#3785 
Add rule to PolicyViolation events
=> Add rule to PolicyViolation event messages

pkg/webhookconfig/registration.go
Closes: https://github.com/kyverno/kyverno/issues/3776
This PR fixes pod staying in `Terminating` state when scaling to 0.
=> fix: pod stay in terminating when scaling to 0

cmd/initContainer/main.go, cmd/kyverno/main.go, pkg/utils/util.go
This PR removes useless `NewKubeClient` util.
=> chore: remove useless util NewKubeClient

cmd/kyverno/informer.go, cmd/kyverno/main.go
This PR adds a couple informer util functions.
=> chore: add informer util

api/kyverno/v1/spec_types.go, pkg/policy/on_update_policy_test.go, pkg/policy/validate.go
This PR:
- add a policy validation check for mutate existing policies
Continuation of https://github.com/kyverno/kyverno/pull/3791
=> Policy Validation check for onPolicyUpdate flag

cmd/kyverno/main.go, pkg/background/update_request_controller.go
Closes: https://github.com/kyverno/kyverno/issues/3813
Refer #3791 for more info, we have added the `handler` to `updaterequest.status` to idenity the kyverno pod instance handled the UpdateRequest
=> refact: disable leader for update request controller

pkg/engine/jsonContext.go
=> Improve logging and error handling in json context

pkg/engine/jmespath/functions.go, pkg/engine/jmespath/functions_test.go, test/cli/test-mutate/kyverno-test.yaml, test/cli/test-mutate/patched-resource.yaml, test/cli/test-mutate/policy.yaml, test/cli/test-mutate/resource.yaml
Fixes #3794 
/kind feature
See added CLI tests
=> Add an object_from_lists function

scripts/create-e2e-infrastruture.sh, scripts/deploy-controller.sh, scripts/generate-server-cert.sh
=> refactor: shell to prevent globbing and word splitting

pkg/engine/imageVerify.go, pkg/engine/imageVerify_test.go
n/a
1.7.0
/kind bug-fix
Fix check for empty `oldObject` in context.
n/a
=> fix check and add logs

pkg/policy/policy_controller.go
=> refactor: remove unused functions

cmd/kyverno/main.go, pkg/controllers/certmanager/controller.go, pkg/webhooks/server.go
This PR fetches tls certificate dynamically instead of statically at server start.
=> feat: fetch tls certificate dynamically

.golangci.yml, cmd/cli/kubectl-kyverno/jp/jp_command.go, cmd/cli/kubectl-kyverno/test/test_command.go, pkg/cosign/cosign.go, pkg/engine/common/common.go, pkg/engine/variables/operator/numeric.go, test/e2e/utils.go
This PR enables `unconvert` linter.
=> chore: add unconvert linter

.golangci.yml
This PR enables `durationcheck` linter.
=> chore: enable durationcheck linter

pkg/engine/imageVerify.go, pkg/policy/allowed_vars_test.go, pkg/policy/validate.go
=> skip var checks in attestations (#3876)

.golangci.yml, cmd/cli/kubectl-kyverno/utils/common/common.go, cmd/cli/kubectl-kyverno/utils/common/fetch.go, test/e2e/utils.go
This PR enables `noctx` linter.
=> chore: enable noctx linter

pkg/tls/renewer.go
This PR fixes an issue when writing cert secrets.
=> fix: write secret

cmd/cli/kubectl-kyverno/apply/apply_command.go, cmd/cli/kubectl-kyverno/test/test_command.go, cmd/cli/kubectl-kyverno/utils/common/common.go, cmd/cli/kubectl-kyverno/utils/store/store.go, pkg/engine/utils.go, test/cli/test/limit-configmap-for-sa/kyverno-test.yaml, test/cli/test/limit-configmap-for-sa/limit_configmap_for_sa.yaml, test/cli/test/limit-configmap-for-sa/resource.yaml, test/cli/test/limit-configmap-for-sa/user_info.yaml
Cherry-pick PR https://github.com/kyverno/kyverno/pull/3887
=> cherry pick Fix subject match selector issue in cli (#3887)

charts/kyverno/README.md, charts/kyverno/templates/deployment.yaml, charts/kyverno/values.yaml, cmd/kyverno/main.go, pkg/cosign/init.go, pkg/webhooks/server.go
Cherry pick https://github.com/kyverno/kyverno/pull/3893
1.7.0
/kind bug
=> cherry-pick #3893

charts/kyverno-policies/Chart.yaml, charts/kyverno-policies/README.md, charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/templates/crds.yaml, config/install.yaml, config/release/install.yaml, config/release/kustomization.yaml, config/release/labels.yaml
=> Release v1.7.0-rc1

.github/workflows/helm-release.yaml
=> Cherry-pick - Remove permissions in helm-release workflow (#3901)

.golangci.yml, pkg/common/common.go, pkg/policyreport/changerequestcreator.go
This PR enables `wastedassign` linter.
=> chore: enable wastedassign linter

cmd/kyverno/Dockerfile
=> fix: docker build

pkg/background/common/status.go, pkg/background/request_process.go, pkg/background/update_request_controller.go, pkg/webhooks/updaterequest.go
Fixes https://github.com/kyverno/kyverno/issues/3906.
/1.7.0
/bug
With the change, Kyverno cleans up `Completed` URs for mutate policies.
=> Cleanup the UR for mutate policies once it's completed

pkg/background/common/status.go, pkg/background/request_process.go, pkg/background/update_request_controller.go, pkg/webhooks/updaterequest.go
=> Cherry-pick #3912 

.golangci.yml, pkg/testrunner/scenario.go
This PR enables `dogsled` linter.
=> chore: enable dogsled linter

.golangci.yml, pkg/background/common/errors.go, pkg/engine/context/mock_context.go, pkg/engine/variables/vars.go, pkg/policy/validate.go
This PR enables `errname` linter.
=> chore: enable errname linter

.golangci.yml, pkg/engine/utils.go, pkg/openapi/validation.go, pkg/policy/validate.go
This PR enables `misspell` linter.
=> chore: enable misspell linter

.golangci.yml
This PR enables `makezero` linter.
=> chore: enable makezero linter

pkg/background/generate/generate.go, pkg/background/request_process.go, pkg/background/update_request_controller.go
=> fix: handle UR delete once trigger namespace deleted (#3934)

pkg/background/common/util.go, pkg/background/request_process.go, pkg/policy/updaterequest.go
use patch to update handler status in UR
=> fix: use patch to update handler status in UR

pkg/controllers/policycache/controller.go
This PR fixes cache warmup log message.
=> fix: cache warmup log message

.golangci.yml
This PR enables `grouper` linter.
=> chore: enable grouper linter

pkg/background/generate/generate.go, pkg/background/request_process.go, pkg/background/update_request_controller.go
This PR handles UR cleanup properly for generate policies, cc @prateekpandey14 .
Related discussion https://kubernetes.slack.com/archives/C032MM2CH7X/p1652790488443279.
=> Cleanup URs on trigger deletion

pkg/background/generate/generate.go, pkg/background/request_process.go, pkg/background/update_request_controller.go
=> Cherry pick #3953 #3955

charts/kyverno/Chart.yaml, charts/kyverno/templates/NOTES.txt, charts/kyverno/templates/validate.yaml
Co-authored-by: shuting <shuting@nirmata.com>
Cherry-pick #3954.
=> Cherry-pick: replica count in helm chart (#3954)

cmd/kyverno/main.go, pkg/background/request_process.go, pkg/background/update_request_controller.go
Cherry-pick:#3961
cc @eddycharly
=> fix: mark ur retry on conflict (#3961)

cmd/kyverno/main.go, pkg/background/update_request_controller.go
This PR releases ur when handler pod is gone.
=> fix: release ur when handler pod is gone

pkg/webhooks/resource/handlers.go
This PR removes an unused field.
=> fix: remove unused field
