cmd/kyverno/kyverno.go
init.go
main.go
pkg/config/config.go
pkg/controller/controller.go
pkg/dclient/certificates.go
pkg/dclient/client.go
pkg/engine/engine.go
pkg/engine/generation.go
pkg/engine/mutation.go
pkg/engine/overlay.go
pkg/engine/patches.go
pkg/engine/pattern.go
pkg/engine/validation.go
pkg/event/controller.go
pkg/kyverno/apply/apply.go
pkg/violation/builder.go
pkg/webhooks/server.go

Initial revision to introduce glog as logger
Changes:
- Replace log.logger interface with glog
- glog used global logging, so no logger is to be passed to components
- Default flags for controller and cli
- not passing logger instance to http.Server. It will use go log pkg to print internal errors
To-do:
- CLI use of glog
- define guidelines for verbosity levels
- Developers to update the code as per the guidelines

introduce glog, remove log.logger references

---

README.md
definitions/install.yaml
documentation/writing-policies-generate.md
examples/generate/policy_generate.yaml
examples/generate/policy_networkPolicy.yaml
pkg/apis/policy/v1alpha1/types.go
pkg/dclient/client.go
pkg/engine/generation.go
test/ConfigMapGenerator-SecretGenerator/policy-cm-test.yaml
test/ConfigMapGenerator-SecretGenerator/policy-namespace-patch-cmgCG-sgCG.yaml

- Update the documentation examples for generate scenario
- add a yaml to create a network policy
- rework: in previous changes, I had changed the generate namespaces to the one specified inside generate. With this commit, I have reverted the behavior, and the generated resource takes the namespace from the trigger conditions(selector or name)
- removing the check on mandatory attributes for any resource during create/data mode of generation.
- update the test examples

update namespace trigger + update documentation

---

.travis.yml
README.md
init.go
main.go
pkg/apis/policy/v1alpha1/types.go
pkg/controller/controller.go
pkg/dclient/certificates.go
pkg/dclient/client.go
pkg/dclient/utils.go
pkg/engine/overlay.go
pkg/engine/utils.go
pkg/engine/validation.go
pkg/engine/validation_test.go
pkg/event/util.go
pkg/result/reason.go
pkg/result/result.go
pkg/sharedinformer/sharedinformerfactory.go
pkg/tls/tls.go
pkg/webhooks/server.go

Resolves #78 
- add go report badge
- inital refactoring of code as per goReport suggestions
- miss-spells
- exported functions
- comments
- refresh report after build

Go Report formatting and support

---

definitions/install.yaml
documentation/installation.md
main.go
pkg/webhooks/server.go
pkg/webhooks/utils.go

Issue: #171 
Introduce command line argument "filterKind", to allow the user to specify the Kinds that are to be filtered while processing policies at admission webhook.
k8 kind where policy is not evaluated by the admission webhook. example --filterKind "Event" --filterKind "TokenReview","ClusterRole"

171 filter logs

---

main.go
pkg/engine/engine.go
pkg/engine/generation_new.go
pkg/gencontroller/controller.go
pkg/gencontroller/generation.go
pkg/gencontroller/utils.go
pkg/utils/informer.go
pkg/utils/json.go
pkg/webhooks/server.go

Resolves #202 
Additions:
- New controller to watch for namespace resource, and apply generate rules
- if the rule is of type 'clone', then we just verify if the resource already exists and don't verify the contents. If the resource does not exist, we create a clone from the reference resource
- if the rule is of type 'data', then verify if the resource exists and contents are present in the existing resource. If JSON configuration in the rule is validated against the resource, to see if its present. (Support of array is alpha). If the resource does not exists then create a new one.
Removal:
- generation is not processed from adm-webhook or processexisting/policycontroller.
TODO:
- the logic for old generate is still present for reference in pkg/engine. To remove once stable as mentioned …

202 refactor generate

---

pkg/engine/mutation.go
pkg/engine/overlay.go
pkg/engine/patches.go
pkg/webhooks/server.go

Changes:
- patch the resource after every rule
- mutation rules operated on the patched resource while processing the rule
- the actual JSON patch if all rules succeed is done by passing the patches to the response.
Resolves #157 
Removal:
- removed type PatchBytes, as the type didn't have methods associated with it. 
- we would remove the common components into pkg/utils, and not typing it with allow us to not have cyclic dependencies and keep types across packages simple

resource patched after every rule + rm PatchBytes

---

pkg/dclient/client.go
pkg/dclient/client_test.go
pkg/dclient/utils.go
pkg/engine/generation_new.go
pkg/event/controller.go
pkg/gencontroller/controller.go
pkg/testrunner/test.go
pkg/violation/builder.go

Fixes partially #76
Changes:
- The dynamic client now use "Kind" as the identifier instead of the resource name
- if a kind -> resource mapping fails we invalidate the cache and retry. If it is still not found then we fail. The 2 retry mechanism is similar to mechanism used by DefaultRESTMapper.
- Fix tests accordingly

get resource using kind & add cache invalidate mechanism and retry

---

main.go
pkg/controller/controller.go
pkg/engine/engine.go
pkg/engine/generation_new.go
pkg/engine/overlay_test.go
pkg/engine/utils.go
pkg/engine/validation.go
pkg/gencontroller/controller.go
pkg/gencontroller/generation.go
pkg/webhooks/utils.go

Process generation rules on an existing resource. (there is a scenario when the controller is already up, and the generation informer also has filled it cache but does not process policy as no policy is present. When the policy is created, it is not picked by generation controller, so need to process it from policy controller)
- Apply generate on the existing namespace
- Add annotations to Namespace resource
Misc:
- Go vet suggestions
fixes #224

224 feature

---

pkg/annotations/annotations.go
pkg/controller/cleanup.go
pkg/engine/mutation.go
pkg/info/info.go

For a successful mutation rule application, we store the JSON patch used to mutate the object in annotations.
fixes #233

show mutation changes in annotation

---

README.md

Correct the examples, after the introduction of the match and exclude option in resource description.
fixes #265

fix Readme examples

---

pkg/engine/pattern.go

fixes #307 
for anchors, if the value is object/[map]interface{}, we only check if the resource "key" has an object as value, but we do not compare the content of object in resource & pattern

Validate anchor values of type object/[map]interface{}

---

examples/best_practices/policy_validate_hostpid_hosipc.yaml
pkg/engine/generation.go
pkg/engine/mutation.go
pkg/engine/response.go
pkg/engine/validation.go
pkg/namespace/generation.go
pkg/namespace/report.go
pkg/policy/apply.go
pkg/policy/existing.go
pkg/policy/report.go
pkg/policyviolation/helpers.go
pkg/testrunner/scenario.go
pkg/testrunner/utils.go
pkg/webhooks/mutation.go
pkg/webhooks/report.go
pkg/webhooks/utils.go
pkg/webhooks/validation.go

Renaming of EngineResponseNew to EngineResponse
fixes #369

update engineResponse Name

---

pkg/policy/controller.go

Resolves Issues #388 
Testing:
- Create a policy violation object with no active policy, then the policy violation is removed as the policy it refers to is inactive.

delete PV if the P it refers to is stale

---

samples/RequireNSLimitsQuotas.md
samples/best_practices/require_namespace_quota.yaml
test/scenarios/samples/best_practices/scenario_validate_require_namespace_quota.yaml

Changes:
- `data` was not specified in generate policy
- when specifying values for cpu we need to user `requests.cpu: '1'`, then the value is considered as float64(type is preserved). But if we use value as `1` & `"1"`, its type is string. As the type interpreted in string in go, the case for float needs to be handled explicitly as described in issue https://github.com/nirmata/kyverno/issues/375.
The correction uses `''` to preserve the types and add values for requests and limits.
In this policy, if the namespace already contains a resource quota(existing resources) with name `defaultresourcequota` and has the configuration as
```
spec:
hard:
requests.cpu: '1'
requests.memory: "1Gi"
limits.cpu: '3'
limits.memory: "2Gi"
```
then the policy is successful. But if the resourcequota is not …

fix generate format

---

main.go
pkg/config/dynamicconfig.go

Dynamic configuration:
- Refer to configMap to get the resources to be filtered, we will watch the configMap for changes and accordingly update.
- To support backward compatibility, the user can also provide resources to be filtered as command-line arguments. These will be used as initial list of resources to be filtered. 
- If both command line and config map resources are defined, we initialize using command line arguments, but the configMap resync will overwrite the list of resources to be filtered. So the configMap will be considered.
Add comments for removal of command-line argument option.

add backward support for command line arguments for filtering resources

---

pkg/engine/validation.go
pkg/engine/validation_test.go
samples/DisallowHostNetworkPort.md
samples/RunAsNonRootUser.md
samples/best_practices/deny_runasrootuser.yaml
samples/best_practices/disallow_host_network_hostport.yaml
test/policy/validate/policy_validate_disallow_default_serviceaccount.yaml
test/scenarios/other/scenario_validate_selinux_context.yaml
test/scenarios/samples/best_practices/scenario_valiadate_require_image_tag_not_latest_deny.yaml
test/scenarios/samples/best_practices/scenario_validate_disallow_default_namespace.yaml
test/scenarios/samples/best_practices/scenario_validate_disallow_host_filesystem.yaml
test/scenarios/samples/best_practices/scenario_validate_disallow_hostpid_hostipc.yaml
test/scenarios/samples/best_practices/scenario_validate_disallow_new_capabilities.yaml
test/scenarios/samples/best_practices/scenario_validate_disallow_node_port.yaml
test/scenarios/samples/best_practices/scenario_validate_disallow_priviledged_privelegesecalation.yaml
test/scenarios/samples/best_practices/scenario_validate_probes.yaml
test/scenarios/samples/best_practices/scenario_validate_require_pod_requests_limits.yaml
test/scenarios/samples/best_practices/scenario_validate_require_readonly_rootfilesystem.yaml
test/scenarios/samples/more/scenario_validate_container_capabilities.yaml
test/scenarios/samples/more/scenario_validate_sysctl_configs.yaml

fixes #431 
- Add a period at the end of `Validation.Message`.
- Update scenario files expected responses.
- Update policy `Validation.Message` to not use a period( for consistency).
- Update the markdown files for the policies that have been updated.

update message string

---

main.go
pkg/api/kyverno/v1alpha1/utils.go
pkg/config/dynamicconfig.go
pkg/policy/cleanup.go
pkg/policy/controller.go
pkg/policy/report.go
pkg/policyviolation/controller.go
pkg/policyviolation/helpers.go

- cleanup policy violations in policy controller
- policy violation on resource 
- policy violation on the owner of the resource( using getOwners function in policyviolation pkg)
- Expose `GetOwners` function in `policyviolation` pkg
additional changes:
- store the cache sync variable in struct for dynamic config
- remove type `pvResourceOwner` and replace it with `kyverno.ResourceSpec` as they have the same types and functionality.
fixes #458
There is some latency hit in the policy correction and policy violation removal. Created issue #463 to optimize.

458 cleanup

---

pkg/engine/generation.go
pkg/engine/validation.go
pkg/policy/controller.go

- Return resource as patched resource ( was missed in generation & validation[update])
- Register Namespaced cluster policy violation handler with correct informer
- Wait for namespaced cluster policy informer cache to sync.
fixes #480

add patched resource + correct register handlers

---

main.go
pkg/policy/controller.go
pkg/policy/webhookregistration.go
pkg/webhookconfig/checker.go
pkg/webhookconfig/policy.go
pkg/webhookconfig/registration.go
pkg/webhookconfig/resource.go

Each policy re-conciliation in policy controller was querying the client to check if the resource mutating webhook configuration is present or not, this check can be instead done on the local informer cache. 
Reduces the processes involved in a policy loop.
Also uses dynamic client, as we dont need to a typed client and makes api consistent.
fixes #506

refer informer cache in policy controller for mutatingwebhookconfigs

---

pkg/engine/policy/validate.go
pkg/engine/policy/validate_test.go

Fix #499.
Add policy validation checks for UserInfo definition:
- roles: has to be namespace:rolename
- subjects:
if kind = ServiceAccount, the namespace field should not be empty

499 policy validation userinfo

---

pkg/engine/overlay.go
pkg/engine/overlayCondition.go
pkg/engine/overlayCondition_test.go
pkg/engine/overlay_test.go

Previously we only skip processing policy if condition tag (key) is not present in the resource. This PR skips processing mutate policy if any condition is not met for the resource, also updates the debugging logs.

Skip processing mutate policy if condition is not met

---

pkg/engine/pattern.go
pkg/engine/pattern_test.go
pkg/engine/utils.go

Fix #428.
In order to handle quantity comparison (`pattern` in a rule is defined with string, e.g. "1Gi"), we first parse the pattern:
- if it's with type quantity, then compare by the quantities
- if it's a normal string, then a wildcard match

implement quantity comparison

---

pkg/engine/overlay.go
pkg/engine/overlay_test.go

In the mutation, there are 2 iterations, the first would check the matched conditions, and only if they match, we will generate patch bytes in the second iteration.
This PR removes condition check while generating mutation patch, as conditions are already verified in the first iteration.

fix mutation patch bytes

---

samples/DisallowBindMounts.md
samples/DisallowPrivilegedContainers.md
samples/DisallowRootUser.md
samples/best_practices/disallow_privileged.yaml
samples/best_practices/disallow_root_user.yaml

add anchors for omitempty tag

---

cmd/kyverno/main.go
definitions/install.yaml
documentation/installation.md
pkg/dclient/certificates.go
pkg/tls/tls.go

- Introduce Flag `FQDNCN` to use FQDN as CommonName in CSR.

flag to use FQDN as CommonName in CSR

---

pkg/engine/mutation.go
pkg/engine/utils/utils.go
pkg/webhookconfig/common.go
pkg/webhooks/mutation.go
samples/best_practices/disallow_default_namespace.yaml

This PR 
- fix #631, set failurepolicy of webhookconfiguration to `Ignore`
- for the same admission request, fix to pass in patchedResource for mutation
- update policy annotation

Default failurepolicy & bug fix

---

pkg/engine/mutate/overlay.go
pkg/engine/mutation.go
pkg/engine/validation.go
pkg/webhooks/common.go
pkg/webhooks/mutation.go
pkg/webhooks/server.go
pkg/webhooks/validation.go

This PR fix #627, #636.
Mutation failure is only reported as a violation in this fix. The resource creation would not be blocked if any error occurs.
Further support can be tracked in #639.

mutation failure should not block resource creation

---

pkg/engine/context/context.go
pkg/policyviolation/namespacedpv.go

log level 4 to "Loading variable" logs in context.go line no 124 and 139 (https://github.com/nirmata/kyverno/issues/527#issuecomment-576942064)
and 
Typo at pkg/policyviolation/namespacedev.go

Adding log level in "loading variable "

---

cmd/initContainer/main.go
pkg/dclient/client.go
pkg/dclient/utils.go

- Add a check-in InitContainer to exit if the kubernetes server version is  < v1.12.7.
Tested with minikube versions(v1.12.6[fail] & v1.12.7[pass])

add kubernetes server version check

---

pkg/engine/mutation_test.go
pkg/engine/validation.go
pkg/engine/validation_test.go
pkg/engine/variables/variables_test.go
pkg/engine/variables/vars.go
pkg/engine/variables/vars_test.go

fixes #727 
Resolve the variables bottom-up (i.e. resolve the inner-most variable to the outer variables). Regular expression leveraged to identify the variables.
There are 2 possible scenarios:
1. No inner variables {{variable}}. The resolved value can be scalar or non-scalar.
2. Contains inner variables {{variable-{{variable}}}}. The inner values need to be scalar for the outer variable can be resolved{{variable-value}}. If the inner variable is non-scalar, the resolution is inconsistent so it's considered as failed variable resolution for reporting.
Limitations:
- Only equal operator is supported for variables
- In the inner-variable resolves to a non-scalar value, then it is considered as a failed variable.

support nested variable resolution

---

pkg/event/controller.go

Sets the logger format for the event. The controller runtime cannot be doesn't provide method for info logs with arguments.
Defauling to `klog`, which is the actual logging framework.
fixes #774

use klog as logger for event broadcasting

---

charts/kyverno/Chart.yaml
charts/kyverno/README.md
charts/kyverno/crds/crds.yaml
charts/kyverno/templates/_helpers.tpl
charts/kyverno/templates/clusterrole.yaml
charts/kyverno/templates/clusterrolebinding.yaml
charts/kyverno/templates/configmap.yaml
charts/kyverno/templates/deployment.yaml
charts/kyverno/templates/secret.yaml
charts/kyverno/templates/service.yaml
charts/kyverno/templates/serviceaccount.yaml
charts/kyverno/values.yaml

Adds a Helm chart for Kyverno, as a way to install it instead of https://github.com/nirmata/kyverno/blob/master/definitions/install.yaml. Closes #835.
It is written in a manner that allows it to be installed in different namespaces or with a different name, but because of Kyverno's code hard-coding assumptions about names, it MUST be installed in the Kyverno namespace and MUST be installed with the release name "kyverno"; you will not get a working installation if you use different names.
The chart supports providing generatecontroller resources to add to a default list, and supports creating a self signed cert via Helm.
Other things to point out (that can be reversed if so desired):
* For the resourceFilters, we deconstruct it into a yaml list, one entry for each filter. For adding to …

Add Helm chart for Kyverno - #835

---

pkg/policy/apply.go
pkg/policy/controller.go
pkg/policy/existing.go
pkg/policyviolation/clusterpv.go
pkg/policyviolation/common.go
pkg/policyviolation/namespacedpv.go

Fixes #695 , a few other fixes:
- skip generating pv on the evicted pod
- fix violations get re-created on the same resource
- skip background processing if a resource is to be deleted

fix policy violation updated without owner

---

pkg/kyverno/apply/command.go
pkg/kyverno/common/common.go
pkg/kyverno/validate/command.go

Issue: 
https://github.com/nirmata/kyverno/issues/877
Solution:
Now, we can pass multi YAML files in both policies and resources with `validate` and `apply` commands in CLI. 
Refactoring:
Created a common package for CLI which handles common functionalities.

Handling Multi YAML (Policies and Resources)

---

charts/kyverno/templates/configmap.yaml
charts/kyverno/templates/deployment.yaml
charts/kyverno/templates/service.yaml
charts/kyverno/templates/serviceaccount.yaml
definitions/install.yaml
documentation/installation.md
pkg/checker/status.go
pkg/config/config.go
pkg/dclient/client_test.go
pkg/generate/cleanup/controller.go
pkg/generate/cleanup/resource.go
pkg/generate/controller.go
pkg/generate/status.go
pkg/webhooks/generate/generate.go

Closes #841 
> /kind bug
Currently `KubePolicyNamespace` is hardcode in the code. Now we are getting it from the environment variable.
works.

removing hardcoded namespace from the code

---

pkg/userinfo/roleRef.go

In generate sync feature there is a bug where we are not able to delete namespace. 
/kind bug
works.

Namespace not able to delete if it have generated resource

---

charts/kyverno/crds/crds.yaml
definitions/crds/crds.yaml
definitions/install.yaml
definitions/install_debug.yaml
definitions/release/install.yaml

/kind cleanup
When deploying Kyverno using Argo CD, we get a persistent false diff for the ClusterPolicy custom resource definition (the definition itself, not instances of ClusterPolicy), because Kubernetes converts the invalid `AnyValue: {}` property types to just an empty dict `{}`. Since the Kubernetes server makes this change to `{}` unilaterally after applying, when a diffing tool like Argo CD compares it against the YAML manifest, each such instance of AnyValue appears as a diff.
I know that since AnyValue is not part of the official OpenAPI V3 schema, and that when you run `kubectl get crd clusterpolicies.kyverno.io -o yaml` the status message shows Kubernetes complaining about "Required value: must not be empty for specified object fields" for all of these fields. In theory the …

Replace CRD AnyValue fields with empty dict

---

charts/kyverno/crds/crds.yaml
definitions/crds/crds.yaml
definitions/install.yaml
definitions/install_debug.yaml
definitions/release/install.yaml

/kind cleanup
This implements the same change as #1047, except for the new Policy CRD instead of the ClusterPolicy CRD, which apparently did not get those updates before merging.
When deploying Kyverno using Argo CD, we get a persistent false diff for the Policy custom resource definition (the definition itself, not instances of Policy), because Kubernetes converts the invalid AnyValue: {} property types to just an empty dict {}. Since the Kubernetes server makes this change to {} unilaterally after applying, when a diffing tool like Argo CD compares it against the YAML manifest, each such instance of AnyValue appears as a diff.
I know that since AnyValue is not part of the official OpenAPI V3 schema, and that when you run kubectl get crd policies.kyverno.io -o yaml the status message …

Replace Policy CRD AnyValue fields with empty dict

---

pkg/openapi/crdSync.go

closes #954
close #1050
Ignoring the error for fields - allOf, anyOf, oneOf and not.
works.
Kubernetes doesn't support openAPIV3 yet. Kubernetes itself doesn't validate for anyOf, allOf, not, OneOf - https://github.com/kubernetes/apiextensions-apiserver/blob/a704491594d836db7402ab8609c72ce891ffbebe/pkg/controller/openapi/v2/conversion.go#L36

added validation for openapi_v3

---

pkg/api/kyverno/v1/types.go

closes https://github.com/nirmata/kyverno/issues/1108
> /kind bug
Fixed the duplicate name in struct. Now the mutated policy can be printed in yaml formal using flag ```-o yaml```.
works.

fixed duplicate name

---

documentation/writing-policies-configmap-reference.md
pkg/engine/mutate/patchesUtils.go
pkg/engine/utils.go
pkg/engine/variables/operator/in.go
pkg/engine/variables/operator/notin.go
test/e2e/generate/utils.go

In #724, we support configMap lookup. This PR is to handle an array that is defined in the configMap. 
For example, with the following configMap,
````yaml
data:
allowed-roles: "[\"cluster-admin\", \"cluster-operator\", \"tenant-admin\"]"
````
The value of `allowed-roles` will be converted to array for operator `In` `NotIn` operation.

Parse string value to array from configMap

---

pkg/dclient/certificates.go
pkg/tls/tls.go

This PR generates a self-signed certificate, and uses it to build the TLS webhook server, as documented [here](https://github.com/kyverno/kyverno/blob/master/documentation/installation.md#option-2-use-your-own-ca-signed-certificate). This behavior becomes the default after Kubernetes v1.19.
For those running prior versions of Kyverno( 1.2.0-), once upgrade, Kyverno will automatically generate the rootCA and write it to the secret `kyverno-svc.kyverno.svc.kyverno-tls-ca`, update `kyverno-svc.kyverno.svc.kyverno-tls-pair` accordingly.
Add certificate checker https://github.com/kyverno/kyverno/issues/1177.

Use Self-signed certificate to build TLS webhook server

---

pkg/kyverno/common/common.go
pkg/kyverno/common/regex.go
pkg/policy/validate.go

Policy with variable declaration with spaces was not allowed:
```
metadata:
name: add-service-annotation
spec:
rules:
- name: add-annotation
match:
resources: 
kinds:
- Service
preconditions:
- key: "{{ request.object.spec.type }}"
operator: Equal
value: LoadBalancer
mutate:
overlay:
metadata:
labels:
+(service/loadbalancer): "true"
```
Resource:
```
apiVersion: v1
kind: Service
metadata:
name: example-service
spec:
selector:
app: example
ports:
- port: 8765
targetPort: 9376
type: LoadBalancer
```
Resulting error:
```
λ kubectl-kyverno apply C:\tmp\kyverno\policies\add_label_to_loadbalancer.yaml -r C:\tmp\kyverno\service-example.yaml
applying 1 policy to 1 resource
skipping policy add-service-annotation as it is not valid: …
```

fix regex for allowed variable to support spaces

---

pkg/engine/utils.go
pkg/engine/validate/common.go
pkg/engine/validate/pattern.go
pkg/engine/validation.go
pkg/event/controller.go
pkg/webhookconfig/registration.go
pkg/webhookconfig/rwebhookregister.go

Fixes #1192.
Fixes #1224. 
Fixes #1225.

Improve logging message

---

charts/kyverno/crds/crds.yaml
definitions/crds/crds.yaml
definitions/install.yaml
definitions/install_debug.yaml
pkg/api/kyverno/v1/types.go

Fixes #1220 .
Added `validationFailureAction` and `background` to kubectl additional printer columns.
```
$ kubectl get cpol
NAME             BACKGROUND   VALIDATION FAILURE ACTION
require-labels   true         audit
test-policy-1    false        audit
```

Print validationFailureAction with kubectl get

---

go.sum
pkg/engine/mutation_test.go
pkg/engine/validation_test.go
pkg/engine/variables/vars.go
pkg/generate/cleanup/controller.go
pkg/generate/controller.go
pkg/generate/generate.go
pkg/generate/status.go

Fixes: https://github.com/kyverno/kyverno/issues/1251
fixed panic and added logs
works.

1251 fix generate panic

---

.github/ISSUE_TEMPLATE/bug_report.md
pkg/api/kyverno/v1/clusterpolicy_types.go
samples/AddDefaultLabels.md

Correct minor column misspelling in `kubectl get cpol` output.
works.

column misspelling

---

pkg/kyverno/apply/command.go

closes https://github.com/kyverno/kyverno/issues/1206
- removed printing skipping statement for policy
- added log level
- error message in log gives the name of variables in the policy 
(changes done in - https://github.com/kyverno/kyverno/pull/1279)
works.

added log level for skipped policy

---

charts/kyverno/crds/crds.yaml
cmd/kyverno/main.go
definitions/crds/kyverno.io_clusterpolicies.yaml
definitions/install.yaml
definitions/install_debug.yaml
pkg/api/kyverno/v1/clusterpolicy_types.go
pkg/generate/cleanup/controller.go
pkg/generate/generate.go
pkg/generate/generate_controller.go
pkg/kyverno/apply/command.go
pkg/policy/validate_controller.go
pkg/policyreport/reportrequest.go
pkg/policystatus/policy_status.go
pkg/policystatus/policy_status_test.go
pkg/webhookconfig/monitor.go
pkg/webhookconfig/status.go
pkg/webhooks/generate/generate.go
pkg/webhooks/generation.go
pkg/webhooks/mutation.go
pkg/webhooks/validation.go

Fixes https://github.com/kyverno/kyverno/issues/1319
/kind bug
- Update policy status management logic to removed cached entry. Previously all status was being re-written every 10 seconds. This would cause all policies to be updates, triggering policy validation checks.
- Added checks in controllers to only update policy status when there is a real change.
- Changed resync intervals to 15 minutes and removed resync from listers.
works.

1319 fix throttling

---

samples/RequirePodRequestsLimits.md
samples/best_practices/require_pod_requests_limits.yaml

none, just saw the key/value missing and wanted to contribute a fix.
The example for requests and limits on pods was missing a check for cpu limits existence. I added they key/value pair just like the one for memory limits.
works.

adds cpu limit to pod requests limits example

---

charts/kyverno/templates/deployment.yaml
cmd/initContainer/main.go
cmd/kyverno/main.go
pkg/auth/auth.go
pkg/dclient/certificates.go
pkg/dclient/client.go
pkg/dclient/utils.go
pkg/generate/cleanup/controller.go
pkg/generate/generate_controller.go
pkg/openapi/validation.go
pkg/utils/util.go

When the API server is not available for some reason, one cannot get CRD / API resources through kubectl or client. This results in Kyverno crashing as it cannot fetches CRDs for Kyverno.
```
couldn't get resource list for controlplane.antrea.tanzu.vmware.com/v1beta1: the server is currently unable to handle the request
```
This PR ignores such an error when the API server is unavailable.
Also add cleanup for cluster / report change requests in init container.

Fix Kyverno crash when CRD is not installed

---

pkg/engine/utils.go
pkg/engine/validate/pattern.go
pkg/engine/validate/validate.go
pkg/engine/validate/validate_test.go
pkg/engine/validation.go
pkg/engine/wildcards/wildcards.go

Fixes #1332.
/kind bug
Substitute wildcard keys for `metadata.labels` and  `metadata.annotations` before pattern matching.
- [x ] I have added tests that prove my fix is effective or that my feature
works.
- [ x] I have added or changed [the documentation](documentation/).

wildcard label and annotation keys validate patterns

---

pkg/generate/generate.go

closes https://github.com/kyverno/kyverno/issues/1320
> /kind bug
skipping update of status for generate request
works.

removing generate error message

---

pkg/kyverno/apply/command.go

closes https://github.com/kyverno/kyverno/issues/1383
now policies can be passed using pipe operator while applying on resource(s)
works.

added pipe for passing policy in apply

---

charts/kyverno/crds/crds.yaml
charts/kyverno/values.yaml
definitions/install.yaml
definitions/install_debug.yaml
definitions/manifest/deployment.yaml
pkg/resourcecache/main.go

As we've seen more and more OOM [issue](https://kubernetes.slack.com/archives/CLGR9BJU9/p1608078134224500) on a relatively large cluster, sending this PR to increase the default memory limit to 256Mi.
Here's the issue to publish the resource usages of kyverno https://github.com/kyverno/kyverno/issues/689.

Increase default memory limit to 256 Mi

---

charts/kyverno/crds/crds.yaml
cmd/initContainer/main.go
definitions/crds/kyverno.io_clusterpolicies.yaml
definitions/crds/kyverno.io_clusterreportchangerequests.yaml
definitions/crds/kyverno.io_policies.yaml
definitions/install.yaml
definitions/install_debug.yaml
pkg/api/kyverno/v1alpha1/clusterreportchangerequest_types.go
pkg/config/dynamicconfig.go
pkg/engine/response/response.go
pkg/generate/generate.go
pkg/kyverno/apply/report.go
pkg/kyverno/apply/report_test.go
pkg/policy/apply.go
pkg/policy/common.go
pkg/policy/existing.go
pkg/policy/report.go
pkg/policy/validate_controller.go
pkg/policyreport/builder.go
pkg/policyreport/policyreport.go
pkg/policyreport/reportcontroller.go
pkg/policyreport/reportrequest.go
pkg/webhooks/validation.go

This PR:
- fixes #1398, reduces RCR throttling requests
- reduces throttling requests when getting resources, by adding a [scope map](https://github.com/realshuting/kyverno/blob/a97fbb8f863157dd072d1f35917964eacf9c157a/pkg/policy/existing.go#L29-L38) to cache resource's scope
- stops updating policy status from the background controller
- updates resourcesFilter to exclude `Namespace` itself when it has `[*,<namespace name>,*]`

1398 - Reduce RCR throttling requests

---

.gitignore
pkg/policy/validate_controller.go

closes [#1264](https://github.com/kyverno/kyverno/issues/1264)
works.

add logging for policy creation and deletion events

---

pkg/engine/anchor/anchor.go
pkg/engine/anchor/common/common.go
pkg/engine/common/anchorKey.go
pkg/engine/mutation.go
pkg/engine/validation.go
pkg/engine/wildcards/wildcards.go
pkg/engine/wildcards/wildcards_test.go

Fixes #1457 
Add back anchors after wildcard substitution for annotations and labels keys.
- [x ] I have added tests that prove my fix is effective or that my feature
works.

handle anchors for wildcard annotations

---

pkg/engine/wildcards/wildcards_test.go
pkg/webhooks/validate_audit.go

Fixes https://github.com/kyverno/kyverno/issues/1448.

Fix memory leak - remove item from the cache once done (audit handler)

---

pkg/engine/mutate/patchesUtils.go
pkg/engine/mutate/patchesUtils_test.go
pkg/engine/utils/utils_test.go
pkg/webhooks/common.go

Fixes https://github.com/kyverno/kyverno/issues/1216.
Fixes https://github.com/kyverno/kyverno/issues/1339.
Fixes https://github.com/kyverno/kyverno/issues/1419.

Remove unnecessary JSON patches; fixes strategicMergePatch for tolerations

---

.github/workflows/krew.yaml

[The previous](https://github.com/realshuting/kyverno/commit/5ecdfda4e093efc9c20027acb34c29b19c6f1e27#diff-f3965722a67b62a317529747e0618a47fce629078f1e97b42ded57438a77e4a6) change for krew was not triggered when publishing a new release, this PR revert the changes to the working solution.

Revet GitHub action change for krew

---

.github/workflows/build.yaml
Makefile
cmd/cli/kubectl-kyverno/Dockerfile
cmd/initContainer/Dockerfile
cmd/kyverno/Dockerfile

**Changes**
- [**Multi-stage**] Adding multi-stage docker build of the following docker images
- kyverno/kyverno
- kyverno/cmd/cli/kubectl-kyverno
- kyverno/kyvernopre
- [**Non-root**] Base image changed from `scratch` to `alpine` (Because non-root user can't be added in scratch image)
**Following is the screenshot of the user inside the kyverno pod (which is non-root user)**
- [**Size**] Image sizes
- kyverno/kyverno     -  **47.3MB**
- kyverno/cmd/cli/kubectl-kyverno - **43.9MB**
- kyverno/kyvernopre -  **33.5MB**
- [**Makefile**] Refactoring docker build step in Makefile to accommodate the new docker file changes 
- Issue- https://github.com/kyverno/kyverno/issues/1321
works.

Enhancing dockerfiles (multi-stage) of kyverno components and adding non-root user to the docker images

---

pkg/policy/validate.go
pkg/policy/validate_test.go

From now on, under any policy, under the `conditions.value` field nothing apart from the values ["CREATE", "UPDATE", "DELETE", "CONNECT"] will be allowed to be passed, when the `condition.key` is `{{request.operation}}`
**Sample Input 1**
```yaml
conditions:
- key: "{{request.operation}}"
operator: In
value: 
- CREATE
- errrr
- DELETE
```
**Output**
```
Error from server: error when creating "/home/yash1300/Desktop/kyverno-stuff/sample-ops-3.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].validate.deny.conditions[0].value[1]: unknown value 'errrr' found under the 'value' field. Only the following values are allowed: [CREATE, UPDATE, DELETE, CONNECT]
```
**Sample Input 2**
```yaml
conditions:
- key: …
```

feat: validation of 'value' field under 'deny.conditions' in the rule object

---

charts/kyverno/README.md
charts/kyverno/templates/deployment.yaml
charts/kyverno/values.yaml

the `values.yaml`, when dealing with helm, also contains the `hostNetwork`(bool) field (default: false) will allow the kyverno pod to share the host network's namespace. This is useful is situations when dealing with a custom CNI over Amazon EKS.
works.

added: hostNetwork toggle to the dep. and values manifests

---

pkg/engine/apiPath.go
pkg/engine/context/context.go
pkg/engine/context/evaluate.go
pkg/engine/generation.go
pkg/engine/jsonContext.go
pkg/engine/mutation.go
pkg/engine/validation.go
pkg/engine/validation_test.go
pkg/testrunner/scenario.go

These changes somehow got missed in the last PR....when I merged.
- [ x] I have added tests that prove my fix is effective or that my feature
works.

redo changes reverted by merge

---

index.yaml

Removes v1.3.0-rc1 as ArtifacHub reports the chart is missing.
```
error preparing package: error loading chart (https://kyverno.github.io/kyverno/kyverno-v1.3.0-rc1.tgz): unexpected status code received: 404 (package: kyverno version: v1.3.0-rc1)
```

Removes Helm Chart v1.3.0-rc1

---

pkg/engine/validate/pattern.go
pkg/engine/validate/pattern_test.go

Related issue: #1538
/kind feature
I have added operator '&' support for validation scalar values (strings, integers, etc.)
The reason for this changes described in feature request #1538 
works.

Add AND logical operator support

---

pkg/kyverno/common/common.go
pkg/kyverno/common/fetch.go

Revert "Adding HTTP(git raw or any public url ) URL applying functionality to kyverno cli"

---

pkg/api/kyverno/v1/policy_types.go
pkg/engine/variables/evaluate_test.go
pkg/engine/variables/operator/numeric.go
pkg/engine/variables/operator/operator.go

#1512 
The newly added operators which can be applied to `validate.deny.conditions` and `preconditions` over kyverno policy rules are the following:
- `GreaterThanOrEquals` : key >= value?
- `GreaterThan` : key > value?
- `LessThanOrEquals` : key <= value?
- `LessThan` : key < value?
works.
Here, the key will only be expected to be int, int64, float, float64, string (for the cases like "2", "2.4" only)
In rest of the cases, an error with saying "Unknown key type found" would be generated because clearly, these are numeric operators and these operations can't be applied on types which can't be casted to int or float.

feat: support for numeric operators

---

Makefile
cmd/kyverno/localDockerfile
go.mod
go.sum
pkg/policyreport/builder.go
pkg/policyreport/changerequestcreator.go
pkg/policyreport/reportrequest.go

Fixes https://github.com/kyverno/kyverno/issues/1497.
This PR adds a buffer to slow down report change request creation.

Reduce RCR Throttling

---

pkg/kyverno/test/command.go
pkg/webhookconfig/common.go
pkg/webhooks/generation.go
pkg/webhooks/generation_test.go

closes #1551 
removed redundant err checks, redundant use of composite literals and unreachable pieces of code.
works.

performed cleanups

---

pkg/webhooks/generation.go
pkg/webhooks/generation_test.go

Fixed generation.go interface conversion panic:
```
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 17228 [running]:
github.com/kyverno/kyverno/pkg/webhooks.stripNonPolicyFields(0xc0056462d0, 0xc0011c6b40, 0x211b700, 0xc0011c6960, 0x4, 0xc00597ab57)
/Users/shutingzhao/go/src/github.com/realshuting/kyverno/pkg/webhooks/generation.go:191 +0xfd9
github.com/kyverno/kyverno/pkg/webhooks.(*WebhookServer).handleUpdateTargetResource(0xc000b13c80, 0xc00010f520, 0xc0038f64a8, 0x1, 0x1, 0xc0011c6ab0, 0x211b700, 0xc0011c6960)
/Users/shutingzhao/go/src/github.com/realshuting/kyverno/pkg/webhooks/generation.go:165 +0x6af
github.com/kyverno/kyverno/pkg/webhooks.(*WebhookServer).handleUpdate(0xc000b13c80, …
```

Panic fix in generation.go

---

.github/PULL_REQUEST_TEMPLATE.md

- [] I have read the [contributing guidelines](../blob/main/CONTRIBUTING.md).

Actually fix contributor link in PR template

---

pkg/engine/variables/operator/in.go
pkg/engine/variables/operator/notin.go

Fixes #1367 
Added checking if a set of strings is in an allowed list of strings when using `In` and `NotIn` operators
works.
I wrote the [setExistsInArray](https://github.com/kyverno/kyverno/compare/main...RinkiyaKeDad:operator-add?expand=1#diff-38948620ce7b14acdfbdedbfdae0ca0213aa0b84b9ca81515bc9499720ef26c6R119) function based on [keyExistsInArray](https://github.com/kyverno/kyverno/blob/main/pkg/engine/variables/operator/in.go#L65) function already present. I had a doubt here, if we have a return statement in [default case](https://github.com/kyverno/kyverno/blob/main/pkg/engine/variables/operator/in.go#L100) wouldn't this mean that the return statement [outside the switch …

feat(operators): support subset checking for in and notin

---

charts/kyverno/README.md
charts/kyverno/templates/_helpers.tpl
charts/kyverno/templates/policies/default/disallow-adding-capabilities.yaml
charts/kyverno/templates/policies/default/disallow-host-namespaces.yaml
charts/kyverno/templates/policies/default/disallow-host-path.yaml
charts/kyverno/templates/policies/default/disallow-host-ports.yaml
charts/kyverno/templates/policies/default/disallow-privileged-containers.yaml
charts/kyverno/templates/policies/default/disallow-proc-mount.yaml
charts/kyverno/templates/policies/default/disallow-selinux.yaml
charts/kyverno/templates/policies/default/restrict-apparmor-profiles.yaml
charts/kyverno/templates/policies/default/restrict-sysctls.yaml
charts/kyverno/templates/policies/restricted/deny-privilege-escalation.yaml
charts/kyverno/templates/policies/restricted/require-non-root-groups.yaml
charts/kyverno/templates/policies/restricted/require-run-as-nonroot.yaml
charts/kyverno/templates/policies/restricted/restrict-seccomp.yaml
charts/kyverno/templates/policies/restricted/restrict-volume-types.yaml
charts/kyverno/values.yaml

/kind feature
I would like to deploy Kyverno with the Helm provided policies, except one or two of the charts won't work in my environment so I'd like to ideally exclude a few like so:
```yaml
podSecurityExclude:
- disallow-host-path
```
I can add Helm CI tests is that's desired (seeing the checkbox above), but since none already existed I opted not to add any tests for Helm.
Also I think the only name issue is `disallow-proc-mount.yaml` and `require-run-as-nonroot.yaml` had a different name than the actual name in metadata, so if the previous name needs to remain the same …

Allow some helm policies to be excluded

---

Makefile

closes #1617 
> /kind bug
From now on, whenever the user will run `make controller-gen`, it will be made sure that they end up specifically with v0.4.0 (currently) of controller-gen.
Here's an example of it working:
1. User doesn't have controller-gen installed
```sh
► make controller-gen
controller-gen not found!
installing controller-gen v0.4.0...
make[1]: Entering directory '/home/yash1300/Projects/GoProjects/github.com/yashvardhan-kukreja/kyverno'
go: creating new go.mod: module tmp
go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.4.0
CONTROLLER_GEN=/home/yash1300/Projects/GoProjects/bin/controller-gen
make[1]: Leaving directory …
```

feat: added versioned validation and installation of controller-gen

---

charts/kyverno/templates/NOTES.txt

/kind bug
This ensures the NOTES output when adding Helm chart actually describes what was setup, especially if sites don't deploy with the defaults.

Fix Helm chart notes to use template values

---

go.mod
go.sum
pkg/engine/context/context.go
pkg/engine/mutate/mutation.go
pkg/engine/mutate/overlay.go
pkg/engine/mutate/overlayCondition.go
pkg/engine/mutate/overlay_test.go
pkg/engine/mutate/patchJson6902.go
pkg/engine/mutate/patchJson6902_test.go
pkg/engine/mutate/patchesUtils.go
pkg/engine/mutate/patchesUtils_test.go
pkg/engine/utils/utils.go
pkg/kyverno/common/common.go
pkg/policy/apply.go
pkg/policymutation/policymutation.go
pkg/webhooks/annotations.go

Fixes https://github.com/kyverno/kyverno/issues/1340.
This PR adds support for [SupportNegativeIndices, AllowMissingPathOnRemove, and EnsurePathExistsOnAdd](https://github.com/evanphx/json-patch/tree/master#configuration) to `patchesJson6902`, here's the list of use cases:
1. add non-exist object:
```yaml
spec:
containers:
- name: nginx
image: nginx:1.14.2
```
```yaml
- path: "/spec/nodeSelector"
op: add 
value: {"node.kubernetes.io/role": "test"}
```
2. add non-exist array
```yaml
spec:
containers:
- name: nginx
image: nginx:1.14.2
```
```yaml
- path: "/spec/tolerations"
op: add
value: [{"key": "node-role.kubernetes.io/test", "effect": "NoSchedule", "operator": "Exists"}]
```
3. append an element to the existing list:
```yaml
spec:
containers:
- name: nginx
image: …
```

Support AllowMissingPathOnRemove and EnsurePathExistsOnAdd in patchesJSON6902

---

pkg/engine/context/context.go
pkg/engine/jsonContext.go
pkg/policy/apply.go
pkg/policy/background.go
pkg/policy/validate_test.go
pkg/utils/util.go

> /kind bug
Fixes https://github.com/kyverno/kyverno/issues/1621.

Substitute variables in context.configMap

---

charts/kyverno/crds/crds.yaml
definitions/crds/kyverno.io_clusterpolicies.yaml
definitions/crds/kyverno.io_policies.yaml
definitions/install.yaml
definitions/install_debug.yaml
pkg/api/kyverno/v1/policy_types.go

fix: added details regarding match.resources

---

pkg/engine/jsonContext.go
pkg/engine/jsonContext_test.go

closes #1242 
In the situations where certain values are passed from a configmap to the cluster policy, the multi-line block present in the configmap (if present) will be interpreted as a `[]string` corresponding to that multi-line block split by `\n`, instead of being interpreted as a multi-line single string literal.
```yaml
data:
key: |-
CREATE
UPDATE
DELETE
```
Here, after this PR, the value of `data.key` would be interpreted as `["CREATE", "UPDATE", "DELETE"]` unlike previously where it would have been interpreted as `"CREATE\nUPDATE\nDELETE"`
- [] I have added or changed [the …

feat: added functionality for delimiting multi-line block by newline characters

---

pkg/kyverno/apply/command.go
pkg/kyverno/common/common.go

closes #1659 
> /kind bug
- If the value of `-o` is a directory path, then, simply write the output of mutated policies in overwrite-mode itself.  
- If the value of `-o` is a file path (path ending with .yaml or .yml), then, truncate/empty it in the first place in `pkg/kyverno/apply/command.go` and then, write the output of mutated policies in append-mode. (truncating/emptying followed appending will simulate an overwrite, basically).
If the value of `-o` is a file path (path ending with .yaml or .yml), then, truncate/empty it in the first place in `pkg/kyverno/apply/command.go` and then, write the output of mutated policies in append-mode. (truncating/emptying followed appending will simulate an overwrite, basically). Can't …

fix: overwrite the output file when repetedly executing kyverno apply command

---

pkg/engine/variables/evaluate_test.go
pkg/engine/variables/operator/in.go
pkg/engine/variables/operator/notin.go

Fixes #1689 
Updated the `In` and `NotIn` functions as per new definitions and changed the tests.
New definitions:
`In`: S1 in S2 means all values of S1 are present in S2
Iterate through S1 and if any value in S1 is not found in S2 return false else return true in the end.
`NotIn`: S1 not in S2 means no value of S1 is present in S2
Iterate through S1 and if any value is found in S2 return false else return true in the end.
Tests are passing locally. Also verified with a sample policy.

fix: changed logic for In and NotIn for sets

---

pkg/engine/apiPath.go
pkg/engine/apiPath_test.go

Signed-off-by: Joshua Snider <jsnider@mtu.edu>
#1679 
/kind bug
URL paths of format "/apis/GROUP/VERSION/*" should have Version set to GROUP/VERSION part of the path instead of just VERSION. So the URL "/apis/extensions/v1beta1/namespaces/example/ingresses" should have Version set to "extensions/v1beta1"
Tested on Kubernetes 1.19:
```
I0306 06:41:19.146674       1 validate_controller.go:185] PolicyController "msg"="policy created event"  "kind"="ClusterPolicy" "policy_name"="upstream-must-exist" "uid"="fb0caf50-80e1-4cd3-9bbb-52f42ae64c18"
I0306 06:41:19.266289       1 jsonContext.go:80] EngineValidate "msg"="added APICall context entry" "kind"="RouteTable" "name"="example-external-qa" …
```

Bug Fix #1679; Set Version to Group/Version for /apis/* URLs

---

pkg/api/kyverno/v1/utils.go
pkg/engine/variables/operator/numeric.go

The following policy restrict pod count per k8s node, this PR fixes the variable substitution in NumericOperatorHandler.
```yaml
metadata:
name: restrict-pod-count
annotations:
pod-policies.kyverno.io/autogen-controllers: None
spec:
rules:
- name: restrict-pod-count
match:
resources:
kinds:
- Pod
context:
- name: podcounts
apiCall:
urlPath: "/api/v1/pods"
jmesPath: "items[?spec.nodeName=='minikube'] | length(@)"
preconditions:
value: "CREATE"
validate:
message: "restrict pod counts to be no more than 12 on node minikube"
deny:
conditions:
- key: "{{ podcounts }}"
operator: GreaterThanOrEquals …
```

Fix variable substitution in NumericOperatorHandler

---

pkg/engine/variables/vars.go
pkg/engine/variables/vars_test.go

fixes #1585
/kind bug
The reason of the issue was invalid validation process during DELETE operation. JSON path could not be resolved because we needed to validate oldResource instead of resource (validation context has no resource). So I just added substitution for the resource name and it works.

Bug Fix: #1585 issue; validate on DELETE the oldResource

---

pkg/generate/generate_controller.go

closes https://github.com/kyverno/kyverno/issues/1720
> /kind bug
Skipping enqueueing generate requests for the policies where the spec is same in old and updated policies.

Skip generate requests for spec being same in old and updated policy

---

pkg/engine/variables/vars.go
pkg/policy/validate.go

None - I went straight for the PR for now.
/kind bug
This fixes an issue where `validateAPICall` fails if a variable contains `/` and therefore exceeds the limit of 7 parts in the path.
Example of such a circumstance (falsely failing validation):
```
apiCall:
urlPath: "/apis/cluster.x-k8s.io/v1alpha3/namespaces/{{ request.object.metadata.namespace }}/clusters/{{ request.object.metadata.labels.\"cluster.x-k8s.io/cluster-name\" }}"
```
The solution I went for, is to replace all variables with a simple string during validation.
I am not sure how valuable this validation is at all. It is easy to construct cases where a variable might be templated into a string containing one or multiple `/` during execution of a `ClusterPolicy`.
The benefit of this change is that values from labels and …

Make validateAPICall work with special characters in variables

---

cmd/kyverno/main.go
pkg/config/dynamicconfig.go
pkg/policy/report.go
pkg/policy/validate_controller.go
pkg/policyreport/policyreport.go
pkg/policyreport/reportcontroller.go
pkg/webhookconfig/registration.go

> /kind bug
fixes https://github.com/kyverno/kyverno/issues/1577
fixes https://github.com/kyverno/kyverno/issues/1277
fixes https://github.com/kyverno/kyverno/issues/1682
This PR:
- allows users to configure background scan interval by flag `--background-scan`, the default is set to one hour. The allowed format can be 30s, 15m, 12h.
- reconciles policy reports at the given interval (background scan interval), refreshes the policy results entries, and removes invalid records
- re-creates policy report if it gets deleted
- reconciles policy reports if `resourceFilters` (configured in the Configmap) changes
- If not, I have raised an issue in …

Auto-recover policy report

---

pkg/kyverno/apply/command.go
pkg/kyverno/apply/command_test.go
pkg/kyverno/common/common.go
pkg/kyverno/common/common_test.go
pkg/kyverno/test/command.go
pkg/policymutation/policymutation.go

closes #1657
closes #1615
/kind bug
- For kyverno cli mutate policy, output option added for stdout 
`-i - | `
- Update variable paths when auto generate the controller rules

Fix : 1657 (Update variable paths when auto generate the controller rules)  and 1615 ( kyverno apply pipe through to kubectl)

---

charts/kyverno/templates/clusterrole.yaml
definitions/install.yaml
definitions/install_debug.yaml
definitions/k8s-resource/clusterroles.yaml
definitions/release/install.yaml

Signed-off-by: Yuto Takahashi <ytaka23dev@gmail.com>
#1733
Allow `kyverno:generatecontroller` to handle Roles by default. It has permission for ClusterRoleBindings, ClusterRole and RoleBindings, so should do for Roles too.

Allow generatecontroller to handle Roles

---

charts/kyverno/values.yaml
definitions/install.yaml
definitions/manifest/deployment.yaml
pkg/webhooks/server.go

Fixes #1747
During liveness check, ensure webhooks are present.
I wasn't sure if better to reuse the existing `Check()` for webhooks or maybe instead just check the `kyverno.io/webhookActive` annotation.  I opted for 30s period for liveness check and failure count of 2 to hopefully make sure that the monitor loop could fix things before second failure occurs.

Check webhooks are present during liveness

---

cmd/kyverno/main.go
pkg/engine/jsonContext.go
pkg/engine/variables/vars.go
pkg/policy/background.go
pkg/webhookconfig/registration.go

/kind bug
Fixes https://github.com/kyverno/kyverno/issues/1749.
I cannot reproduce the issue, but it's pretty suspicious that the lookup operates on the same configmap so the fatal happens. I changed to operate on the [copy](https://github.com/kyverno/kyverno/pull/1755/files#diff-9cf26ca6f0b2c8a0b141a28a138874442955a960e18c444f1dfb720989775150R197) of each configmap and generate the test image `ghcr.io/kyverno/kyverno:v1.3.5-rc1-dev-9-gcab81ead` to verify.

Fix concurrent read/write when loading configmap data

---

charts/kyverno/templates/clusterrole.yaml
definitions/install.yaml
definitions/install_debug.yaml
definitions/k8s-resource/clusterroles.yaml

closes https://github.com/kyverno/kyverno/issues/1746
/kind bug
-  Remove default permissions for generate controller

remove permission

---

pkg/api/policyreport/v1alpha1/policyreport_types.go
pkg/policyreport/builder.go

Signed-off-by: Frank Jogeleit <frank.jogeleit@web.de>
#1760 @JimBugwadia @realshuting 
/kind feature
Add support for a now annotion "policies.kyverno.io/severity" to support severity for PolicyResults
I changed the logic to collect all annotation values from one fetch instead of fetching the annotations for each value. This makes it easier to extend the logic for further annotations.

Add Support for policies.kyverno.io/severity annotation

---

pkg/policy/validate_controller.go
pkg/policystatus/policy_status.go

closes https://github.com/kyverno/kyverno/issues/1446
/kind bug
- Fix Failed to mutate policy defaults

Fix #1446 :Failed to mutate policy

---

pkg/engine/mutate/mutation.go
pkg/engine/mutation.go
pkg/engine/mutation_test.go
pkg/engine/validation.go
pkg/engine/validation_test.go
pkg/generate/generate.go
pkg/policy/background.go

Fixes #1777
/kind bug
I have moved variable substitution to higher level, closer to Validation/Mutation/Generation handlers, to avoid unhandled cases when variables are not resolved.
I have added only test from issue description. Currently I'm writing more tests so please leave this PR in draft state until I add more tests.

Variable substitution

---

pkg/engine/validation_test.go
pkg/engine/variables/variables_test.go
pkg/engine/variables/vars.go
pkg/engine/variables/vars_test.go

Fixes https://github.com/kyverno/kyverno/issues/1777.
ConditionOperator `In` and `NotIn` operates on a set of values. The variable substation for these types of values is not handled properly in the previous PR.
> /kind bug
1. Follow the reproduce steps described in https://github.com/kyverno/kyverno/issues/1777, this is the output:
```
Error from server: error when creating "resource.yaml": admission webhook "validate.kyverno.svc" denied the request:
resource Deployment/default/busybox was blocked due to the following policies
cm-array-example:
validate-role-annotation: 'The animal cow is not in the allowed list of animals: ["snake","bear","cat","dog"].'
```
2. If I change `validate.deny.operator` to `In`, the resource creation is …

Fix array variables substitution

---

pkg/engine/mutation.go
pkg/engine/mutation_test.go
pkg/engine/validation.go
pkg/engine/validation_test.go
pkg/engine/variables/vars.go

/bug
With PR https://github.com/kyverno/kyverno/pull/1785, the admission request gets blocked if the referred path in a variable is not present.
This PR ignores such an error and continues rule application instead of return the error (block admission request) immediately.
Further enhancement …

Skip rule application if referred path not exist

---

pkg/utils/util.go

closes #1765 
**After this PR** 
If someone declares `preconditions` or `validate.deny.conditions` containing `any`/`all`, they won't be able to specify any other sub-field apart from `any`/`all`.
For example, the following policy:
```yaml
metadata:
name: cluster-cm-array-example
spec:
validationFailureAction: enforce 
background: false 
rules:
- name: sample-rule
context:
- name: ops-cm
configMap:
name: ops-cm
match:
resources:
kinds:
- Deployment
validate:
message: "The role {{ request.object.metadata.annotations.role }} is not in the allowed list of roles: {{ \"roles-dictionary\".data.\"allowed-roles\" }}."
deny:
conditions:
any:
value:  "{{ …
```

feat: added validation check for ensuring the existence of only 'any'/'all'

---

charts/kyverno/templates/policies/restricted/require-non-root-groups.yaml

change the policy require-non-root-groups to allow fsGroup values greater than zero
https://github.com/kyverno/policies/pull/49
/kind bug

allow fsGroup values greater than zero

---

pkg/generate/generate.go
pkg/resourcecache/main.go
pkg/webhooks/generation.go
pkg/webhooks/server.go

closes https://github.com/kyverno/kyverno/issues/1783
> /kind bug
The issue is because of comparing a pattern with variables with an object where the variables are replaced by values.
To resolved the variables in the pattern is replaced by values using source resource. 
- [] I have read the [PR documentation guide](pr_documentation.md) and followed the process including adding proof manifests to this …

Bug fix/1783 generate endlessly

---

pkg/engine/forceMutate.go
pkg/engine/forceMutate_test.go

Signed-off-by: Max Goncharenko <kacejot@fex.net>
Fixes #1737
/kind bug
Added two handlers to forceMutate: patchStrategicMerge and patchesJson6902

Fix #1737: forceMutate does not handle StrategicMerge patchesJson6902

---

pkg/engine/validate/validate.go
pkg/engine/validation_test.go

Signed-off-by: Max Goncharenko <kacejot@fex.net>
Closes #1826
/kind feature
Added new handling logic to the validation handler. Now if we validate array we also checking, if there string in the pattern to apply the operator, if it present.
I had no manifests, I checked the logic through the tests.

Support operators (>=, <, etc ...) on list values

---

pkg/policy/apply.go
pkg/policy/background.go
pkg/policy/background_test.go

Closes https://github.com/kyverno/kyverno/issues/1812.
The following policy has no `background` set, which means by default the policy will apply in the background mode.
```yaml
metadata:
name: require-network-policy
annotations:
pod-policies.kyverno.io/autogen-controllers: none
spec:
rules:
- name: require-network-policy
match:
resources:
kinds:
- Pod
validate:
message: "Tag 'latest' is not allowed for 'nginx' container. "
deny:
conditions:
- key: "{{ images.containers.nginx.tag}}"
value: latest
```
I have 2 pods (nginx and nginx-8669ff8c97-fbcjr ) with `nginx` container in the cluster
```
✗ kg pod
NAME …
```

Enable image substitution in the background mode

---

pkg/kyverno/common/fetch.go
pkg/utils/loadpolicy.go

Closes https://github.com/kyverno/kyverno/issues/1848, https://github.com/kyverno/kyverno/issues/1845
> /kind bug
skipping yaml file when kind is missing.
policy.yaml:
```
---
metadata:
name: portefaix-M0003
annotations:
policies.kyverno.io/title: portefaix-M0003
policies.kyverno.io/category: Best Practices
Metadata should have annotations
spec:
rules:
- name: check-for-annotations
match:
resources:
kinds:
- Pod
validate:
message: "Annotations is required."
pattern:
metadata:
annotations:
foo: "?*"
```
resource.yaml:
```
---
apiVersion: v1
kind: Pod
metadata:
name: myapp-pod-ok …
```

Fix for commented yaml files in Kyverno CLI

---

pkg/policy/validate_controller.go
pkg/policy/validate_test.go
pkg/policymutation/policymutation.go
pkg/policymutation/policymutation_test.go

Closes https://github.com/kyverno/kyverno/issues/1805.
> /kind bug
When there are mixed kinds (Pod & Pod controllers) defined in `match.resources.kinds` or `exclude.resources.kinds`,  the auto-gen is disabled.
Create the following policy:
```yaml
metadata:
name: block-old-flux
spec:
rules:
- name: block-old-flux
match:
resources:
kinds:
- Deployment
- CronJob
- Job
- StatefulSet
- DaemonSet
- Pod
validate:
message: Cannot use old Flux v1 annotation.
pattern:
metadata:
=(annotations):
X(fluxcd.io/*): "*?"
```
The auto-gen is automatically disabled by `pod-policies.kyverno.io/autogen-controllers: none`:
```yaml
✗ kg cpol block-old-flux -o yaml | …
```

Disable auto-gen when a rule has mixed of kinds: pod & pod controllers

---

pkg/policymutation/policymutation.go

Closes https://github.com/kyverno/kyverno/issues/1856.

Remove debug log

---

cmd/kyverno/main.go
pkg/resourcecache/main.go
pkg/tls/certRenewer.go
pkg/tls/reader.go
pkg/webhookconfig/monitor.go

https://github.com/kyverno/kyverno/issues/1540
> /kind enhancement
In this issue https://github.com/kyverno/kyverno/issues/1540#issuecomment-814386682, we found that the default `resourceCache` could result in OOM kill. This PR removes kind "Secret" from the `resourceCache`. …

Remove secret from default resourceCache

---

pkg/kyverno/crds/policy_crd.go
pkg/kyverno/validate/commmand_test.go

closes https://github.com/kyverno/kyverno/issues/1867
> /kind bug
For now, removing all these definitions to pass the CLI validation, as string map is validated when we parse the policy YAML to Go object.

Removing additionalProperties from policy schema 

---

pkg/policy/existing.go

closes #1893 
> /kind bug
Just before the creation creation of reports via `applyAndReportPerNamespace` method, a check is added to ensure that for `kind: Policy`, only the namespace to which that policy belongs is considered and rest are ignored. …

fix: consider policy's namespace as well while report rule results to policy reports

---

pkg/policycache/cache.go
pkg/policycache/cache_test.go
pkg/webhooks/server.go
pkg/webhooks/validate_audit.go

/bug 
Fixes #1894.
cc @vyankyGH 
Since we are not changing any values that are passed by reference, this PR passes those parameters by value instead.

Pass by value in policy cache

---

charts/kyverno/templates/policies/restricted/require-non-root-groups.yaml

there is no issue @github. We discussed this in slack: https://kubernetes.slack.com/archives/CLGR9BJU9/p1620493463206200?thread_ts=1620454770.199000&cid=CLGR9BJU9
/kind bug
supplementalGroups with a value greater than 0 should be allowed.

allow only supplementalGroups greater 0

---

api/apiResources.go
api/preferredResources.go
go.mod
pkg/openapi/crdSync.go
pkg/openapi/validation.go
pkg/openapi/validation_test.go
pkg/webhooks/checker.go
pkg/webhooks/generation.go
pkg/webhooks/mutation.go
pkg/webhooks/policymutation.go
pkg/webhooks/policyvalidation.go
pkg/webhooks/server.go
pkg/webhooks/validation.go
test/e2e/mutate/config.go
test/e2e/mutate/mutate_test.go
test/e2e/mutate/resources.go

Closes #1903.
/bug
Before this change, the openAPISchemas are stored using the Kind only. This PR updates to use gvk to store these schemas.
Policy:
```yaml
metadata:
name: mutate-ingress-host
spec:
rules:
- name: mutate-rules-host
match:
resources:
kinds:
- Ingress
mutate:
- op: replace
path: /spec/rules/0/host
value: {{request.object.spec.rules[0].host}}.mycompany.com
```
Given `networking.k8s.io/v1` Ingress, it is mutated correctly:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: kuard2
labels:
app: kuard
spec:
rules:
- host: kuard
http:
paths:
- backend:
service: 
name: kuard
port: 
number: 8080
path: /
pathType: ImplementationSpecific
tls:
- hosts:
- kuard
```
```yaml
✗ k get ingress kuard2 -o …
```

Update to use gvk to store OpenAPI schema 

---

pkg/engine/variables/vars.go
pkg/engine/variables/vars_test.go
pkg/kyverno/common/regex.go

/kind bug
- Added @ to allowed variables
- Fixed @ substitution
Policy:
```yaml
metadata:
spec:
rules:
- name: replace-image-registry
match:
resources:
kinds:
- Pod
mutate:
spec:
containers:
- (name): "*"
image: "{{ replace_all('{{@}}', 'ghcr.io/linuxserver', 'index.docker.io') }}"
```
Resource:
```yaml
metadata:
name: my-dep2
labels:
app: hello-nginx
spec:
selector:
matchLabels:
app: hello-nginx
replicas: 1
template:
metadata:
labels:
app: hello-nginx
foo: bar
spec:
containers:
- name: hello-nginx
image: ghcr.io/linuxserver/nginx
ports:
- containerPort: 8080
- name: hello-nginx2
image: ghcr.io/linuxserver/nginx
ports:
- …
```

Fix `{{@}}` behavior

---

pkg/webhooks/generation.go

closes https://github.com/kyverno/kyverno/issues/1932
PR for HA - fixing generate policy flow.
Fixing 3 generate policy flows:
-  **Case 1:** When changes are made in clone source resource, the same should be replicated in generated resources.
-  **Case 2:** When generated resource is deleted, kyverno should immediately  recreate the deleted resource
-  **Case 3:** When any changes are made in generated resource and the changes conflict with the generate policy data, Kyverno should replace the updated generated resource.
**Case 1:**
1. Create the following config map:
```
apiVersion: v1
metadata:
name: config-template
data:
player_initial_lives: "5"
ui_properties_file_name: "user-interface.properties"
```
2. Apply …

HA | Fixed generate policy flow

---

pkg/policy/validate_controller.go

This confused me quite a bit while running kyverno. I do not believe this `fmt` output should be here.

Remove unneeded fmt error

---

pkg/webhooks/generation.go

> /kind bug
PR for HA - fixing generate policy flow.
Fixing 3 generate policy flows:
-  **Case 1:** When changes are made in clone source resource, the same should be replicated in generated resources.
-  **Case 2:** When generated resource is deleted, kyverno should immediately  recreate the deleted resource
-  **Case 3:** When any changes are made in generated resource and the changes conflict with the generate policy data, Kyverno should replace the updated generated resource.
**Case 1:**
1. Create the following config map:
```
apiVersion: v1
metadata:
name: config-template
data:
player_initial_lives: "5"
ui_properties_file_name: "user-interface.properties"
```
2. Apply following policy:
```
apiVersion: …
```

main branch | Fixed generate policy flow

---

pkg/engine/validate/pattern.go
pkg/engine/validate/pattern_test.go

#1944 
> /kind bug
If we remove the leading and trailing white spaces from the pattern before extracting the numeric and string value then we won't ever face the bug and the existing functions would also keep working as expected.
Tested it out locally with the [manifests](https://github.com/kyverno/kyverno/issues/1944#issue-909054723) @wimo7083 provided in their issue - it is wokring as expected now.
- [] I have raised an issue in …

fix operator matching with spacing

---

pkg/metrics/admissionreviewlatency/admissionReviewLatency.go
pkg/metrics/metrics.go
pkg/webhooks/generation.go
pkg/webhooks/server.go
pkg/webhooks/validation.go

closes #1969 
From now on, even `admission_request_timestamp` will be registered as a part of the `kyverno_admission_review_latency_milliseconds` metric.
Same resource being re-applied again and again yet still kyverno_admission_review_latency_milliseconds is successfully able to register a new metric for each of them
```
kyverno_admission_review_latency_milliseconds{admission_request_timestamp="2021-06-07 02:02:15 +0000 UTC", cluster_policies_count="1", generate_rules_count="1", instance="localhost:8000", job="kyverno", mutate_rules_count="0", namespaced_policies_count="0", resource_kind="Namespace", resource_name="something", resource_request_operation="create", validate_rules_count="0"}  851.0625 …
```

added: admission_request_timestamp for kyverno_admission_review_latency_milliseconds

---

charts/kyverno/templates/deployment.yaml

This fails on openshift since we cannot specify users within this range. Also, this template should be as close as possible to the vanilla manifest for deployment https://github.com/kyverno/kyverno/blob/main/definitions/release/install.yaml
Vanilla manifest omits the user specification https://github.com/kyverno/kyverno/blob/main/definitions/release/install.yaml#L2478
- [] I have read the [PR …

Remove runAsUser specification from Security Context

---

cmd/kyverno/main.go
go.sum
pkg/config/dynamicconfig.go
pkg/webhookconfig/registration.go
pkg/webhookconfig/resource.go

Closes https://github.com/kyverno/kyverno/issues/1950.
/enhancement
Prior to this change, there's no way to customize webhookConfigurations for Kubernetes resources in Kyverno. This PR allows users to customize `namespaceSelector` of `MutatingWebhookConfiguration` and `ValidatingWebhookConfiguration`, to name them specifically, `kyverno-resource-mutating-webhook-cfg` and `kyverno-resource-validating-webhook-cfg`.
This PR adds another attribute `webhooks` in the Kyverno init ConfigMap, it currently only takes a list of [namespaceSelector](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector) in JSON format.
The `namespaceSelector` is added in the above webhook configurations if it is defined in the initial ConfigMap, …

Customize namespaceSelector of Webhookconfigurations

---

pkg/metrics/parsers.go
pkg/metrics/policychanges/policyChanges.go
pkg/metrics/policyruleexecutionlatency/policyRuleExecutionLatency.go
pkg/metrics/policyruleinfo/policyRuleInfo.go
pkg/metrics/policyruleresults/policyRuleResults.go

Fixes #1989.
/bug
As[ cpol.spec.background](https://github.com/kyverno/kyverno/blob/6f07ea407fce4d2f9677298c7c1f9579beddd660/pkg/api/kyverno/v1/policy_types.go#L55) takes a pointer to boolean, we need to check nil before access its value. This PR fixes the panics when referencing a nil pointer. …

Fix prometheus panics

---

.github/workflows/e2e.yaml
pkg/webhookconfig/monitor.go
scripts/verify-deployment.sh

/bug
With HA, each instance will run the webhook monitor to monitor the webhook status. This is because the webhook requests can be forwarded to any Kyverno instance, so the timestamp on the Deployment is to record the last received admission request. However the issue here is that this timestamp is not updated by the active instance (which receives admission requests) correctly. This PR fixes this problem.
- [] I have raised an issue in …

BugFix - update the annotation lastRequestTimestamp from active instances

---

charts/kyverno/templates/service.yaml

This fixes issue introduced with #1987 
> /kind bug
Fix typo from #1987

Fix Helm chart metrics service to allow NodePort

---

pkg/policyreport/builder.go

Fixes #1961 
Create the following policy:
```
metadata:
annotations:
policies.kyverno.io/scored: "false"
spec:
rules:
- name: no-labels
match:
resources:
kinds:
- Pod
validate:
message: "label 'app.kubernetes.io/name' is required"
pattern:
metadata:
labels:
app.kubernetes.io/name: "?*"
```
Create a pod which violates this policy:
```
apiVersion: v1
kind: Pod
metadata:
name: test
spec:
containers:
- name: web
image: nginx
```
Run `kubectl get polr -o wide` and you'll see that it is reported under `warn` and not `fail`.
- [] I have added or …

adding support for policies.kyverno.io/scored annotation

---

litmuschaos/README.md
litmuschaos/pod_cpu_hog/config.go
litmuschaos/pod_cpu_hog/pod_cpu_hog_test.go
litmuschaos/pod_cpu_hog/resources.go
test/e2e/utils.go

Signed-off-by: Mahfuza mhmohona@gmail.com
/kind feature
Litmus provides a large number of experiments for testing containers, pods, nodes, as well as specific platforms and tools. The advantage of chaos engineering is that one can quickly figure out issues that other testing layers cannot easily capture. This can save a lot of time in the future and will help to find the loopholes in the system and fix them.
In this PR, I integrated LitmusChaos experiment to test Kyverno pod to check it's behavior. 
- Tested it out locally with the Alpine Docker image. 
- The Docker image needs to be pulled -  ` docker pull ghcr.io/kyverno/kyverno:test-litmuschaos ` 
- Kyverno pod needs to be restarted - `kubectl -n kyverno delete pod --all` 
- Run the Chaos Experiment - ` go test …

Integrate LitmusChaos - Pod Memory Hog experiment

---

charts/kyverno/templates/deployment.yaml

Fixes #2002 and #1819
/kind bug
If instaling the Helm chart with a different release name then the lookup for the OwnerRef fails as it defaults to a deployment name of "kyverno". This change makes sure the `KYVERNO_DEPLOYMENT` environment variable is set to the same name as the deployment to ensure this logic always gets the correct value.
```sh
helm install kyverno-custom --namespace kyverno kyverno/kyverno --create-namespace
```
- [] I have raised an issue in [kyverno/website](https://github.com/kyverno/website) to track the …

fix: set deployment name env var

---

pkg/policymutation/policymutation.go
pkg/webhooks/server.go

Fixes https://github.com/kyverno/kyverno/issues/1816.
/bug
Before this change, with both enforce and audit policies exist in the cluster, the policy report only generates results for the enforce policy (if the resource complies with the enforce policy). After the reconciliation of the policy report, all results are audited. This PR fixes the inconsistency issue for the policy report.
Install both policies provided in the issue, create the Ingress resource, now there are two results audited in the policy report.
```
✗ k get polr
NAME              PASS   FAIL   WARN   ERROR   SKIP   AGE
polr-ns-default   1      1      0      0       0      4s
```
- [] My PR …

Fix inconsistent polr for audit policy

---

pkg/policy/validate.go
pkg/policy/validate_test.go

closes https://github.com/kyverno/kyverno/issues/1963
Reject the policy if wildcards present on match/exclude block
```yaml
metadata:
spec:
rules:
- name: check-for-labels
match:
resources:
kinds:
- Pod
validate:
message: "label 'app.kubernetes.io/name' is required"
pattern:
metadata:
labels:
app.kubernetes.io/name: "?*"
```
- Apply the Policy.
- Policy get Rejected with Error 
**Error from server: error when creating ".\\Yamls\\policy.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: wildcards are not accepted in a kind block. at least one resource kind must be specified in a kind block.**
- [] I have raised an …

Fix wildcards issue for match/exclude kind block

---

pkg/webhookconfig/resource.go

closes https://github.com/kyverno/kyverno/issues/2044
/kind bug
Resource :
```yaml
metadata:
name: myapp-maintenance
namespace: myapp
labels:
app: nginx
spec:
replicas: 1
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- name: nginx
image: nginx:1.14.2
ports:
- containerPort: 80
```
Scenario : 
1.  Block pod Exec depend on Pod name
```yaml
metadata:
name: pod-exec-allowed
spec:
rules:
- name: myapp-maintenance-allowed
match:
resources:
kinds:
- PodExecOptions
preconditions:
value: "CONNECT"
validate:
deny: …
```

support for disallow pod exec operation

---

pkg/engine/jsonContext.go
pkg/engine/mutation.go
pkg/engine/validation.go

Signed-off-by: Maxim Goncharenko <goncharenko.maxim@apriorit.com>
/kind cleanup
I have added exception for NotFoundError in mutation and validation handling logic when context is resolved.
Now it is logged at Info level.
Policy:
```yaml
metadata:
name: select-secrets
spec:
rules:
- name: select-secrets-from-volumes
match:
resources:
kinds:
- Pod
context:
- name: volsecret
apiCall:
urlPath: "/api/v1/namespaces/{{request.object.metadata.namespace}}/secrets/{{request.object.spec.volumes[0].secret.secretName}}"
jmesPath: "metadata.labels.foo"
preconditions:
value: "CREATE"
validate:
message: "The Secret named …
```

Changed error to info for NotFoundError in jsonContext

---

.github/workflows/helm-release.yaml
cmd/kyverno/main.go
pkg/webhooks/server.go

Fixes https://github.com/kyverno/kyverno/issues/2028.
/bug
/enhancement
This PR mutates the containers images (if present) to their full path, i.e., `registry/repository/name:tag`, they can be used for the variables manipulations later.
```yaml
metadata:
annotations:
policies.kyverno.io/title: Replace Image Registry
policies.kyverno.io/minversion: 1.4.2
Rather than blocking Pods which come from outside registries,
it is also possible to mutate them so the pulls are directed to
approved registries. This sample policy mutates …
```

Add default image registry to patched resource

---

pkg/dclient/client.go

closes https://github.com/kyverno/kyverno/issues/2126
> /kind bug
Moved error log to info log for group `external.metrics.k8s.i`
1. install keda using `kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.3.0/keda-2.3.0.yaml`
2. install kyverno
3. check kyverno logs - should not get any error in logs. 
Prior to code changes, we were getting the following error log:
```
E0719 11:59:10.973641       1 memcache.go:196] couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
E0719 11:59:10.974143       1 client.go:367] dclient "msg"="failed to retrieve API group" "error"="Got empty response for: external.metrics.k8s.io/v1beta1" …
```

moving to error info log for external.metrics.k8s.io/v1beta1 

---

pkg/engine/context/context.go
pkg/engine/context/imageutils.go
pkg/engine/mutation.go
pkg/engine/mutation_test.go
pkg/webhooks/server.go

Closes https://github.com/kyverno/kyverno/issues/2022.
/bug
/enhancement
The JSON context for resource object in the mutate policy is not updated with the patched resource, thus the chained mutate rules fail. This PR updates the JSON context with the updated patched resource.
Given this chained mutate policy:
```yaml
metadata:
annotations:
policies.kyverno.io/minversion: 1.4.2   
spec:
rules:
- name: replace-image-registry
match:
resources:
kinds:
- Pod
mutate:
spec:
containers:
- (name): "*"
image: |-
{{ regex_replace_all('^[^/]+', '{{@}}', 'myregistry.corp.com') }}
- name: replace-image-registry-chained
match:
resources: …
```

Update JSON context with patched resource for chained mutate rules

---

pkg/engine/anchor/common/common.go
pkg/engine/forceMutate.go
pkg/engine/forceMutate_test.go
pkg/engine/mutate/patchesUtils_test.go
pkg/engine/mutate/strategicMergePatch.go
pkg/engine/mutate/strategicMergePatch_test.go
pkg/engine/mutate/strategicPreprocessing.go
pkg/engine/mutate/strategicPreprocessing_test.go
pkg/engine/validate/validate.go

Closes #1658 
Closes #1915 
Fixes #1896 
/kind bug
I have totally refactored patchStrategicMerge. Now condition anchors should work properly for lists: impact only list element that it was specified in. I have fixed panic during creation by adding stub element to list that does nothing. It prevents list from being deleted, if it cointains only condition and nothing more. Condition is needed to be deleted during preProcessing, so we have an empty list that will delete the same list in the resource. To workaround this moment, I have added stub element `{ "name": "" } to the patch`. It won't mutate anything, it is needed for list to not be empty.
Also I have added new tests.
```yaml
metadata: 
name: add-safe-to-evict
annotations: …
```

Patch strategic merge preprocessing: implement anchor handling

---

pkg/engine/context/context.go
pkg/engine/variables/vars.go
pkg/kyverno/apply/apply_command.go
pkg/kyverno/common/common.go
pkg/kyverno/common/common_test.go
pkg/kyverno/test/test_command.go

closes https://github.com/kyverno/kyverno/issues/1996
closes https://github.com/kyverno/kyverno/issues/1870
> /kind bug
- added resource in the context to get `request.object.*` variables
- added check for the variable - user should pass variable other than `request.object.*` variables
- supporting list variable in cli
Example 1:
Apply following policy :
```
metadata:
name: mutate-ingress-host
spec:
rules:
- name: mutate-rules-host
match:
resources:
kinds:
- Ingress
preconditions:
- key: "{{request.object.spec.rules[0].host}}"
operator: NotEquals
value: "*.mycompany.com"
mutate:
- op: replace
path: /spec/rules/0/host
value: some.mycompany.com
- name: …
```

Resolving variables from the resource passed | CLI

---

dashboard/grafana/dashboard.json

https://github.com/kyverno/kyverno/issues/2188
/kind feature
Add a templating value for the variable DS_PROMETHEUS_KYVERNO to make it use the default Prometheus datasource by default.
N/A

fix: add templating variable for Datasource field

---

pkg/kyverno/apply/apply_command.go
pkg/kyverno/common/common.go
pkg/kyverno/common/common_test.go
pkg/kyverno/test/test_command.go

closes https://github.com/kyverno/kyverno/issues/2197
> /kind bug
moving position of logic to check operation is delete or not
Using following files:
policy.yaml
```
metadata:
name: pod-account-validation
namespace: kyverno
spec:
rules:
- name: pods-user-authorized-for-account
match:
resources:
kinds:
- Pod
namespaces:
- "user-?*"
preconditions:
operator: In
value: ["CREATE","UPDATE"]
context:
- name: userGroupMap
configMap:
name: user-groups-map
namespace: k8-ldap-configmap
validate:
message: "{{ request.object.metadata.namespace }} not authorized to charge against account {{ …
```

CLI result varies if multiple resources are passed for a policy with `request.operation`

---

pkg/api/kyverno/v1/policy_types.go
pkg/engine/variables/evaluate_test.go
pkg/engine/variables/operator/duration.go
pkg/engine/variables/operator/operator.go

Fixes #2213
Allow deny conditions and preconditions to have the following new operators:
* DurationGreaterThanOrEquals : key >= value?
* DurationGreaterThan : key > value?
* DurationLessThanOrEquals : key <= value?
* DurationLessThan : key < value?
The key and value can only be float64, …

Add DurationOperator to handle duration comparison operations

---

pkg/kyverno/common/common.go

Supporting backward compatibility for PR - https://github.com/kyverno/kyverno/pull/2180.
Ignoring `request.object*` variables passed by the user will be ignored by Kyverno CLI.
policy.yaml:
```
metadata:
name: pod-account-validation
namespace: kyverno
spec:
rules:
- name: pods-user-authorized-for-account
match:
resources:
kinds:
- Pod
namespaces:
- "user-?*"
preconditions:
operator: In
value: ["CREATE","UPDATE"]
context:
- name: userGroupMap
configMap:
name: user-groups-map
namespace: k8-ldap-configmap
validate:
message: "{{ request.object.metadata.namespace }} not authorized to charge against account {{ …
```

Added backward compatibility | Resolving variables from the resource passed | CLI 

---

pkg/kyverno/apply/apply_command.go

closes https://github.com/kyverno/kyverno/issues/2223
> /kind bug
Adding context variable in `store.Context `.
policy.yaml:
```
metadata:
name: pod-account-validation
namespace: kyverno
spec:
rules:
- name: pods-user-authorized-for-account
match:
resources:
kinds:
- Pod
namespaces:
- "user-?*"
preconditions:
operator: In
value: ["CREATE","UPDATE"]
context:
- name: userGroupMap
configMap:
name: user-groups-map
namespace: k8-ldap-configmap
validate:
message: "{{ request.object.metadata.namespace }} not authorized to charge against account {{ request.object.metadata.labels.account }}"
deny:
conditions:
- key: "{{ request.object.metadata.labels.account }}" …
```

Fix for - CLI panics when variables are passed using `set` flag

---

pkg/kyverno/common/common.go

Related discussion:- https://kubernetes.slack.com/archives/CLGR9BJU9/p1628261152173800?thread_ts=1628188238.149400&cid=CLGR9BJU9

Updated cli comment for skipping `request.object.*` variables

---

.github/ISSUE_TEMPLATE/bug_report.md

Just adds a field in the bug template to ask for the Kubernetes platform in use.

add platform to bug template

---

pkg/kyverno/apply/apply_command.go
pkg/kyverno/common/common.go
pkg/kyverno/common/common_test.go
pkg/kyverno/test/test_command.go

`engineresponses` is useful for checking mutate and generate response. Further it is not used by the policy report.
https://github.com/kyverno/kyverno/blob/7d9c06da81714e3fd4a7a262656c87961a4c0ed9/pkg/kyverno/apply/apply_command.go#L317
here `engineResponses` returned from `common.ApplyPolicyOnResource` is not used. 
Hence, removing `engineresponses` variable from the above mentioned line.
- [] I have raised an issue in …

Removing `engineresponses` variable from Kyverno CLI

---

pkg/engine/mutation.go
pkg/engine/mutation_test.go

No issue - just a regression I noticed.
/kind bug
Fixes a mistake where some templating was done on the original object instead of the copy which is used for condition validation.
To test this easily with `kubectl apply -f`:
```json
{
"apiVersion": "v1",
"kind": "Pod",
"metadata": {
"name": "nginx-config-test",
"labels": {
"app.kubernetes.io/managed-by": "Helm"
}
},
"spec": {
"containers": [
{
"image": "nginx:latest",
"name": "test-nginx"
}
]
}
}
```
```json
{
"apiVersion": "kyverno.io/v1",
"kind": "ClusterPolicy",
"metadata": {
"name": "cm-variable-example"
},
"spec": {
"rules": [
{
"name": "example-configmap-lookup",
"match": {
"resources": {
"kinds": [
"Pod"
]
}
},
"preconditions": [
{
"key": "{{ request.object.metadata.labels.\"app.kubernetes.io/managed-by\"}}",
"operator": "Equals", …
```

Fix precondition logic for mutating policies

---

go.mod
pkg/engine/variables/vars.go
test/e2e/validate/config.go
test/e2e/validate/resources.go
test/e2e/validate/validate_test.go

Signed-off-by: Maxim Goncharenko <goncharenko.maxim@apriorit.com>
Closes #2241
/kind failing-test
Added test case from #2241 using new variant of [this policy](https://github.com/fluxcd/flux2-multi-tenancy/blob/985b484959707bbe291340f3020b4c2d4144d15d/infrastructure/kyverno-policies/flux-multi-tenancy.yaml) with preconditions.
```yaml
metadata:
name: flux-multi-tenancy
spec:
rules:
- name: serviceAccountName
exclude:
resources:
namespaces:
- flux-system
match:
resources:
kinds:
- Kustomization
- HelmRelease
validate:
message: ".spec.serviceAccountName is required"
pattern:
spec:
serviceAccountName: "?*"
- name: sourceRefNamespace
exclude:
resources:
namespaces:
- flux-system
match:
resources:
kinds:
- …
```

Added 2241 test case

---

pkg/policy/actions.go
pkg/policy/validate.go
pkg/webhooks/common.go

closes https://github.com/kyverno/kyverno/issues/2149
closes https://github.com/kyverno/kyverno/issues/1941
/milestone 1.5.0
Policy with same generate kind get block while installation
```yaml
metadata:
name: add-networkpolicy
annotations:
policies.kyverno.io/title: Add Network Policy
policies.kyverno.io/category: Multi-Tenancy
policies.kyverno.io/subject: NetworkPolicy
By default, Kubernetes allows communications across all Pods within a cluster. 
The NetworkPolicy resource and a CNI plug-in that supports NetworkPolicy must be used to restrict 
communications. A default NetworkPolicy should be configured for each Namespace to 
default deny all ingress and …
```

Validation for generate loops and support ClusterPolicy/Policy in match block

---

pkg/generate/generate.go

Signed-off-by: Matthias Frey <matthias.frey@kit.edu>
closes #2276 
/kind bug
By now when kyverno clones a resource to other namespaces, it will also copy the ownerReferences of the source. This is not allowed in Kubernetes and the garbage collector will delete the new resource. (https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-dependents)
1. Create this secret und an get the generated uid with: `kubectl get secret -n default test-owner-secret -o yaml`
```yaml
---
apiVersion: v1
kind: Secret
metadata:
name: test-owner-secret
type: Opaque
```
2. Create the next secret with the fetched uid (Sorry if this is complicated, normally ownerReferences are set by an Operator, not manually):
```yaml
---
apiVersion: v1
data:
TEST: VEVTVF9TT1VSQ0UK
kind: …
```

remove ownerReferences when cloning resources to other namespace.

---

Makefile
pkg/generate/generate.go

closes https://github.com/kyverno/kyverno/issues/2181
> /kind bug
Added logic to update the label and generated resource according to the `synchronize` flag in generate policy.
**Logic:**
In case `synchronize` is true - update the resource label and generated resource according to the data available in generate policy.
In case `synchronize` is false - update the resource label only if it does not match with the generate policy label and do not update the old generated resource.
1. Apply the following policy:
```
metadata:
annotations:
policies.kyverno.io/category: Workload Isolation
policies.kyverno.io/description: To limit the number of objects, as well as the total amount of compute …
```

Added condition for resource sync

---

pkg/policy/validate.go

Signed-off-by: Sachin  sachin.maurya7666@gmail.com
closes #2117
/kind feature
I have added the function for the check of the forward slash
PS : I know that the function return type and input is not correct . Please let me know that what are the changes that needs to be done .
Try applying this policy
```
metadata:
name: policy-remove-label
spec:
rules:
- name: "Remove unwanted label"
match:
resources:
kinds:
- Secret
mutate:
- path: "metadata/labels/purpose"
op: remove    
```
```
$ kyverno apply policy.yaml
----------------------------------------------------------------------
Policy path is invalid
Error: invalid policy.
Cause: add a forward slash to the path
exit status 1
```
- [] I have added tests that prove my fix is …

add check for the forward slash

---

pkg/kyverno/common/fetch.go

closes https://github.com/kyverno/kyverno/issues/2363
Add the milestone label by commenting `/milestone 1.4.3`.
> /kind bug
Extracting `kind` from the policy `kinds` by string operations.
policy.yaml:
```
metadata:
name: container-image-latest
annotations:
policies.kyverno.io/owner: Red Hat CoP
policies.kyverno.io/category: Workload Management
policies.kyverno.io/description: Check a Deployment is not using the latest tag for their image
spec:
rules:
- name: validate-resources
match:
resources:
kinds:
- apps/v1/Deployment
validate:
message: "{{request.object.kind}}/{{request.object.metadata.name}}: one of its containers is using the latest tag for its …
```

Fix | Support gvk in CLI for policies applied on cluster

---

definitions/crds/kyverno.io_clusterpolicies.yaml
definitions/crds/kyverno.io_policies.yaml
definitions/install.yaml
definitions/install_debug.yaml
pkg/api/kyverno/v1/policy_types.go
pkg/openapi/validation.go

closes https://github.com/kyverno/kyverno/issues/2185
closes https://github.com/kyverno/kyverno/issues/2100
/milestone 1.4.3
Introduce a key under the spec which allows skipping policy validation checks.
old_Policy.yaml
```yaml
metadata:
name: policy-change-memory-limits
annotations:
pod-policies.kyverno.io/autogen-controllers: None
spec:
rules:
- name: pod-containers-1-inject-image
match:
resources:
kinds:
- Pod
preconditions:
all:
- key: "{{request.object.spec.containers[] | length(@)}}"
value: "1"
mutate:
- op: add
path: "/spec/containers/0/env/-"
value: {"name":"K8S_IMAGE","value":"{{request.object.spec.containers[0].image}}"}
- name: …
```

allowing users to skip policy validation when mutating resources

---

pkg/engine/jmespath/functions.go
test/e2e/validate/config.go
test/e2e/validate/resources.go
test/e2e/validate/validate_test.go

Signed-off-by: Maxim Goncharenko <goncharenko.maxim@apriorit.com>
#2260
Fixes #2345
> /kind bug
Removed `contains` function duplicate because it is already defined in the upstream go-jmespath.
```yaml
metadata:
name: drop-cap-net-raw
spec:
rules:
- name: drop-cap-net-raw
match:
resources:
kinds:
- Pod
validate:
deny:
conditions:
any:
- key: "{{ request.object.spec.containers[].securityContext.capabilities.drop[] | contains(@, 'NET_RAW') }}"
value: false
```
```yaml
apiVersion: v1
kind: Pod
metadata:
name: test
spec:
initContainers:
- name: jimmy
image: defdasdabian:923
command: ["/bin/sh", "-c", "sleep infinity"]
capabilities:
drop:
- XXXNET_RAWYYY
- SETUID …
```

Remove contains function

---

charts/kyverno/templates/networkpolicy.yaml
charts/kyverno/values.yaml

Fixes #2287 
Allowed customization for NetworkPolicy with namespaceSelector and podSelector via helm.
Verified locally

networkPolicy customization

---

Makefile

Signed-off-by: Namanl2001 <namanlakhwani@gmail.com>
Fixes #2262 

Add labels to helm templates

---

pkg/policymutation/policymutation.go
pkg/policymutation/policymutation_test.go

Signed-off-by: Marcel Mueller <marcel.mueller1@rwth-aachen.de>
#2337
/kind bug

Check Any and All ResourceFilters during policymutation

---

pkg/engine/jsonContext.go
test/cli/test/variables/cm-blk-scalar-example.yaml
test/cli/test/variables/resources.yaml
test/cli/test/variables/test.yaml
test/cli/test/variables/variables.yaml

#2245 
/kind bug
Parses Multiline Blocks from value files, similar to the webhook as done by function `fetchConfigMap()` in `pkg/engine/jsonContext.go`
```yaml
metadata:
name: cm-array-example
spec:
rules:
- name: validate-role-annotation
context:
- name: roles-dictionary
configMap:
name: roles-dictionary
match:
resources:
kinds:
- Deployment
validate:
message: "The role {{ request.object.metadata.annotations.role }} is not in the allowed list of roles: {{ \"roles-dictionary\".data.\"allowed-roles\" }}."
deny:
conditions:
- key: "{{ request.object.metadata.annotations.role }}"
operator: NotIn
value:  "{{ …
```

Block scalars for value files

---

.github/workflows/e2e.yaml
Makefile
pkg/policyreport/builder.go
pkg/policyreport/reportcontroller.go
scripts/create-e2e-infrastruture.sh

Fixes https://github.com/kyverno/kyverno/issues/2384.
/milestone 1.4.3
/kind bug
When we upgraded (Cluster)PolicyReport and (Cluster)ReportChangeRequest CRDs to v1alpha2, there wasn't a conversion webhook to update `status` to `result` for each rcr / crcr, thus Kyverno panicked when it tried to update summary of each report.
This PR adds a label `app.kubernetes.io/version` indicating which version of Kyverno is managing report change request and uses it to list existing RCRs / CRCRs. All old ones are removed automatically.
This PR also changes how we build the image tag from git tags. This is because we add another tag `helm-chart-v*` to trigger the Helm release.
There is no restart of Kyverno Pod when upgrading from 1.4.2 to this commit:
```
✗ k get -n kyverno pod -w
NAME …
```

Fix upgrade issue from 1.4.2 to 1.4.3-rc1

---

pkg/policymutation/policymutation.go
pkg/policymutation/policymutation_test.go

Fixes https://github.com/kyverno/kyverno/issues/2392.
Also relates to #2337.
/milestone 1.4.3
/kind bug
PR https://github.com/kyverno/kyverno/pull/2261 converts GVK to its valid format during policy mutation, while any/all is not handled properly.
This PR covers any/all conversion in both match and exclude, to name them: `match.any.resources.kinds`, `match.all.resources.kinds`, `exclude.any.resources.kinds`, `exclude.all.resources.kinds`. 
The following policies creation passes:
```yaml
metadata:
name: test
spec:
rules:
- name: test
match:
all:
- resources:
kinds:
- configmap
exclude:
all:
- resources:
kinds:
- configmap
validate:
message: "Metadata label 'name' is required."
pattern:
metadata:
labels:
name: "?*"
```
```yaml
apiVersion: …
```

Fix - policy gets blocked with 1.4.3-rc1 if any/all is defined in match block

---

charts/kyverno/templates/_helpers.tpl
charts/kyverno/templates/deployment.yaml
charts/kyverno/templates/tests/test.yaml
charts/kyverno/values.yaml
definitions/install.yaml
definitions/install_debug.yaml
definitions/manifest/deployment.yaml

Fixes #1966 
Added pod anti-affinity to kyverno. 
Can enable or disable this by editing the following flag in charts/kyverno/value.yaml:
```yaml
antiAffinity:
enable: true
```
https://github.com/kyverno/website/issues/301

adding pod anti-affinity to Kyverno

---

pkg/webhooks/annotations.go
pkg/webhooks/annotations_test.go
pkg/webhooks/mutation.go

Signed-off-by: anushkamittal20 <anumittal4641@gmail.com>
Closes #1528 
Renames `patches` annotations to `last-applied-patches` to reflect on last executed patches in annotations
The PR aims to clarify to the user that the patch added was last one to be added and so proposes to change the terminology `last-applied-patches` instead of just `patches`
New annotation will take the value `policyAnnotation = "policies.kyverno.io~1last-applied-patches"`  and if there is an already existing annotation we add a JSONpatch to remove that annotation.
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: kuard
annotations:
policies.kyverno.io/patches: Workload Management
labels:
app: kuard
spec:
rules:
- host: kuard
http:
paths:
- backend:
service: …
```

Renames patches annotations to last-applied-patches

---

pkg/kyverno/common/fetch.go

issue reported in slack - https://kubernetes.slack.com/archives/CLGR9BJU9/p1631904964399300
`/milestone 1.5.0`.
> /kind bug
apply the following pod manifest in cluster:
```yaml
apiVersion: v1
kind: Pod
metadata:
name: nginx2
spec:
containers:
- name: nginx
image: nginx
ports:
- containerPort: 30000
hostPort: 30000
```
now test it using the Kyverno CLI apply command with the following policy:
```yaml
metadata:
name: block-pod-host-port-node-port-collision
spec:
rules:
- name: check-host-port
match:
resources:
kinds:
- Pod
validate:
message: "Pods may not request use of a host port that overlaps with the cluster's Service node port range."
pattern:
spec: …
```

Bug fix | CLI `apply` command | not filtering the resources from cluster 

---

pkg/engine/jmespath/functions.go
pkg/engine/jmespath/functions_test.go
pkg/kyverno/common/regex.go

Closes #604 
Closes #2409 
/kind feature
Adds arithmetic operators to our custom JMESPath functions suite.
```yaml
metadata:
name: variablethis
spec:
rules:
- name: variablethis
match:
resources:
kinds:
- Pod
mutate:
overlay:
spec:
containers:
- (image): "*"
resources:
requests:
memory: "{{ add(`12`,`13`) }}Mi"
cpu: "250m"
limits:
memory: "{{ @ }}"
cpu: "{{ @ }}"
```
```yaml
apiVersion: v1
kind: Pod
metadata:
name: myapp-pod
labels:
app: myapp
spec:
containers:
- name: myapp-container
image: busybox
command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"]
resources:
requests:
memory: "64Mi"
cpu: "150m"
limits:
memory: "128Mi"
cpu: "500m" …
```

JMESPath: Arithmetic Operators

---

pkg/webhooks/generation.go

closes https://github.com/kyverno/kyverno/issues/2332
`/milestone 1.5.0`.
> /kind bug
When `synchronize` is `true` - when the triggred resource is deleted the `generateRequest` get updated. On updation of the 
`generateRequests` the cleanup controller will enqueue the `generateRequests` for deletion.
While when `synchronize` is `false` - when the triggred resource is deleted the `generateRequest` is not getting updated. And `generateRequests` is not getting enqueued for deletion. 
Now, the same process will be followed when a triggred resource is deleted. As the `generateRequests` will be enqueue only if the GR is added, deleted or updated:
```
c.grInformer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{ …
```

Enqueue the GRs when triggred resource is deleted

---

charts/kyverno/templates/networkpolicy.yaml

Signed-off-by: Namanl2001 <namanlakhwani@gmail.com>
`from` in kyverno Helm Chart should be an array of objects instead of an object.
changes as per slack discussion: https://kubernetes.slack.com/archives/CLGR9BJU9/p1632167129427100
cc: @realshuting  @antoineozenne @diranged
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
labels: 
app.kubernetes.io/component: kyverno
app.kubernetes.io/instance: RELEASE-NAME
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: kyverno
app.kubernetes.io/part-of: kyverno
app.kubernetes.io/version: "v2.0.4"
helm.sh/chart: kyverno-v2.0.4
app: kyverno
name: RELEASE-NAME-kyverno
spec:
podSelector:
matchLabels:
app: kyverno
policyTypes:
- Ingress
ingress:
- from:
- namespaceSelector:
- {} …
```

NetworkPolicy: `from` should be an array of objects

---

pkg/engine/variables/vars.go
pkg/engine/variables/vars_test.go

Closes #2413 
/milestone 1.5.0
/kind feature
Escape references with '\\'
Reference: https://github.com/kyverno/kyverno/issues/2413
```yaml
kind: Policy
metadata:
name: add-otel-resource-env
spec:
rules:
- name: imbue-pod-spec
match:
resources:
kinds:
- v1/Pod
mutate:
spec:
containers:
- (name): "?*"
env:
- name: NODE_NAME
value: "mutated_name"
- name: POD_IP_ADDRESS
valueFrom:
fieldRef:
fieldPath: status.podIP
- name: POD_NAME
valueFrom:
fieldRef:
fieldPath: metadata.name
- name: POD_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
- name: POD_SERVICE_ACCOUNT
valueFrom:
fieldRef:
fieldPath: spec.serviceAccountName
- name: OTEL_RESOURCE_ATTRIBUTES
value: >- …
```

Escape references

---

pkg/kyverno/test/test_command.go

closes https://github.com/kyverno/kyverno/issues/2445
/kind bug
policy.yaml
```
metadata:
name: block-updates-deletes
annotations:
policies.kyverno.io/title: Block Updates and Deletes
policies.kyverno.io/subject: RBAC
Kubernetes RBAC allows for controls on kinds of resources or those
with specific names. But it does not have the type of granularity often
required in more complex environments. This policy restricts updates and deletes to any
Service resource that contains the label `protected=true` unless by
a cluster-admin.
spec:
rules:
- name: block-updates-deletes
match: …
```

Fix skipped policy message is displayed even if variable is passed

---

pkg/policy/background.go

closes https://github.com/kyverno/kyverno/issues/2300
/milestone 1.5.0
Fix No warning about background mode when using any / all in match or exclude blocks
```yaml
metadata:
name: block-updates-deletes
annotations:
policies.kyverno.io/title: Block Updates and Deletes
policies.kyverno.io/subject: RBAC
Kubernetes RBAC allows for controls on kinds of resources or those
with specific names. But it does not have the type of granularity often
required in more complex environments. This policy restricts updates and deletes to any
Service resource that contains the label `protected=true` unless by
a cluster-admin.
spec: …
```

Fix No warning about background mode when using any / all in match

---

charts/kyverno/templates/crds.yaml
definitions/crds/kyverno.io_generaterequests.yaml
definitions/install.yaml
definitions/install_debug.yaml
pkg/api/kyverno/v1/generaterequest_types.go
pkg/generate/generate.go
pkg/generate/generate_controller.go
pkg/webhooks/generation.go

closes https://github.com/kyverno/kyverno/issues/2226
closes https://github.com/kyverno/kyverno/issues/2095
`/milestone 1.5.0`.
> /kind bug
Related Doc - https://docs.google.com/document/d/143RzgN6m5iJmXlOWnHsI1pPll0WE4JUXmKn-TjzJxbY/edit
When `applyGenerate` calls `engine.Generate`, `policyContext.JSONContext` has resource, user info, service account, and image info. But request operation is not added here. Because of which pre-condition evaluation fails as request.operation is not available in the policy context.
Approach:
Updated the `GenerateRequestContext` struct to store the admission request.
```
type GenerateRequestContext struct {
// +optional
UserRequestInfo RequestInfo `json:"userInfo,omitempty" yaml:"userInfo,omitempty"` …
```

supporting request object for generate policies

---

pkg/policy/existing.go
pkg/policy/validate.go

closes https://github.com/kyverno/kyverno/issues/2386
closes https://github.com/kyverno/kyverno/issues/2389
- Handle case-sensitive GVK properly in engine
- Fix any/all matching logic in the background controller
```yaml
metadata:
name: test
spec:
rules:
- name: test
match:
resources:
kinds:
- configmap
validate:
message: "Metadata label 'name' is required."
pattern:
metadata:
labels:
name: "?*"
```
Any/All policy
```yaml
metadata:
spec:
rules:
- name: no-labels
match:
any:
- resources:
kinds: 
- configmap
validate:
message: "label …
```

Validate GVK while installing policy  & Fix any/all matching logic

---

cmd/initContainer/main.go

Relates to #2474 but not sure if solves.
Based on feedback from #2474 but not sure if solves the issue encountered where containers would go into …

Improve init container to use DeleteCollection to remove policy reports

---

pkg/metrics/policyexecutionduration/policyExecutionDuration.go
pkg/metrics/policyresults/policyResults.go

closes #2629 
> /kind bug
From now on, the `rule_result` label will have the following values depending on the policy's execution:
- pass
- fail
- warn
- error
- skip
In the issue described, the metrics' wrongly reported `rule_result=fail` would be `rule_result=skip` from now on considering preconditions not being not met.
```
kyverno_policy_results_total{policy_background_mode="false",policy_name="set-service-defaults",policy_namespace="-",policy_type="cluster",policy_validation_mode="enforce",resource_kind="Service",resource_namespace="default",resource_request_operation="create",rule_execution_cause="admission_request",rule_name="set-service-defaults",rule_result="skip",rule_type="mutate"} 1
```
- [] I have read the …

Fix: RuleResult label to be correctly populated while registering respective metrics

---

ADOPTERS.md

Added my organization, Ohio Supercomputer Center.  Also add myself as I will be presenting 2 presentations at https://sc21.supercomputing.org/ that directly describe how we are using Kyverno to support multi-user pods as HPC "jobs" inside Kubernetes.

Add OSC related adopters

---

pkg/policy/report.go

/kind bug
This feels like an unintentional change that happened as part of https://github.com/kyverno/kyverno/commit/39061d91c44e383d326a2073d79c4ec8e570a7be. It changed from:
```
if rule.Success {
continue
}
```
to:
```
if rule.Status != response.RuleStatusPass {
continue
}
```
So currently kyverno is generating failed events only on the successful resources. …

Fix bug in event creation for failed policies

---

pkg/engine/context/context.go
pkg/engine/context/evaluate.go
pkg/engine/context/mock_context.go
pkg/engine/variables/vars.go
pkg/engine/variables/vars_test.go
pkg/kyverno/apply/apply_command.go
pkg/kyverno/common/common.go
pkg/kyverno/common/regex.go
pkg/kyverno/test/test_command.go
pkg/policy/allowed_vars_test.go
pkg/policy/background.go
pkg/policy/background_test.go
pkg/policy/policy_controller.go
pkg/policy/validate.go
pkg/policy/validate_test.go

Fixes https://github.com/kyverno/kyverno/issues/2625
1.5.2
/kind bug
Re-implemented variable validation to handle new rule types
```yaml
metadata:
name: secret-lookup
annotations:
policies.kyverno.io/title: WIP check secrets
policies.kyverno.io/category: Other
policies.kyverno.io/minversion: 1.5.0
WIP     
spec:
rules:
- name: secrets-lookup-from-env
match:
resources:
kinds:
- Pod
preconditions:
all:
- key: "{{ request.object.spec.containers[].env[].valueFrom.secretKeyRef | length(@)}}"
operator: GreaterThanOrEquals
value: 1
- key: …
```

redo variable validation

---

go.mod
go.sum
pkg/policyreport/builder.go

Signed-off-by: ShutingZhao <shutting06@gmail.com>
https://github.com/kyverno/kyverno/issues/2427
https://github.com/kyverno/kyverno/issues/2524
1.5.2
/bug
This PR switches to use JSON marshaler to convert typed `ReportChangeRequest` to unstructured `ReportChangeRequest`. This change was made based on the observation of the following profiling data:
```
Kyverno-policies, 5 corncobs installed, background = false
NAME                       CPU(cores)   MEMORY(bytes)
kyverno-64bdb56c76-mb5sm   1209m        381Mi
0     0%     0%    67.02MB 53.05%  github.com/kyverno/kyverno/pkg/policyreport.(*Generator).processNextWorkItem
0     0%     0%    67.02MB 53.05%  github.com/kyverno/kyverno/pkg/policyreport.(*Generator).processNextWorkItem.func1
0     0%     0%    67.02MB 53.05% …
```

Fix memory issue - RCR conversion

---

pkg/webhookconfig/configmanager.go
pkg/webhookconfig/registration.go

Signed-off-by: weiwei.danny <weiwei.danny@bytedance.com>
Fixes: [#2691](https://github.com/kyverno/kyverno/issues/2691)
/kind bugfix
N/A

obtain webhook config name dynamically

---

api/kyverno/v1/generaterequest_types.go
pkg/generate/generate.go
pkg/generate/status.go

closes https://github.com/kyverno/kyverno/issues/2654
`/milestone 1.6.0`.
> /kind bug
Added `Skip` as a new status when ever the generated skips generating the resource.
1. Create a ServiceAccount:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
name: test
```
2. Create a generate policy:
```yaml
metadata:
name: generate-test-policy
spec:
rules:
- generate:
data:
metadata:
ownerReferences:
- apiVersion: v1
kind: ServiceAccount
name: '{{request.object.metadata.name}}'
uid: '{{request.object.metadata.uid}}'
spec:
egress:
- ports:
- port: 5353
protocol: UDP
podSelector: {}
policyTypes:
- Egress
kind: NetworkPolicy …
```

Added `Skip` status for generate

---

CODEOWNERS

Signed-off-by: Marcel Mueller <marcel.mueller1@rwth-aachen.de>
We discussed this briefly during the last contributors meeting. The goal is to ensure that maintainers get marked as reviewers in areas of code they are interesting in.
Documentation for CODEOWNERS: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

Add CODEOWNERS file for maintainers

---

api/policyreport/v1alpha2/policyreport_types.go
pkg/policyreport/policyreport.go
pkg/policyreport/policyreport_test.go

We experienced an issue where we had PolicyReports without a `result` property in their `results`. We're not 100% clear how this happened by my best guess is they were previously v1alpha1 and were converted to v1alpha2 incorrectly somehow.
The missing `result` property results in Kyverno crashing on startup due to a nil pointer. This change guards against that nil pointer to at least allow Kyverno to start up successfully.
/kind bug
N/A
- [] I have raised an issue in [kyverno/website](https://github.com/kyverno/website) to track the …

Handle reports with missing result property

---

pkg/policy/validate.go

Signed-off-by: anushkamittal20 <anumittal4641@gmail.com>
#2473 
> /kind bug
I have added a check in validateConditionValues to make sure that if there is a misspelled `key` `value` or `operator` the policy will not be validated and will return an error.
```
metadata:
name: drop-cap-net-raw
spec:
rules:
- name: drop-cap-net-raw
match:
resources:
kinds:
- Pod
validate:
deny:
conditions:
any:
- key: "{{ request.object.spec.[containers, initContainers][].securityContext.capabilities.drop[] }}"
operator: AnyNotIn
values: green
```
if you try to apply this policy it will show an error and the policy will not be validated.
You can also try changing `key` to `keys` , kyverno won't …

added check for misspelled fields in condition

---

pkg/engine/variables/evaluate_test.go
pkg/engine/variables/operator/allin.go
pkg/engine/variables/operator/anyin.go
pkg/engine/variables/operator/anynotin.go

From the conversation in the [PR](https://github.com/kyverno/kyverno/pull/2543#issuecomment-954322817)
The operators can now accept multiple key items and single string value item. AllNotIn operator is now corrected.
```
apiVersion: v1
kind: Pod
metadata:
name: test
spec:
containers:
- name: test
image: defdasdabian:923
command: ["/bin/sh", "-c", "sleep infinity"]
capabilities:
drop:
- orange
- blue
- green
```
```
metadata:
name: drop-cap-net-raw
spec:
rules:
- name: drop-cap-net-raw
match:
resources:
kinds:
- Pod
validate:
deny:
conditions:
any:
- key: "{{ request.object.spec.[containers, initContainers][].securityContext.capabilities.drop[] …
```

Fixes in new operators

---

charts/kyverno/templates/clusterrole.yaml
definitions/install.yaml
definitions/install_debug.yaml
definitions/k8s-resource/clusterroles.yaml
definitions/release/install.yaml
pkg/config/config.go
pkg/webhookconfig/common.go

closes https://github.com/kyverno/kyverno/issues/2713
/kind bug
Install Kyverno using local changes
Kyverno Pod coming  state
Unistall Kyverno

fix hardcoded clusterrole name issue

---

charts/kyverno/templates/clusterrole.yaml
config/install.yaml
config/install_debug.yaml
config/k8s-resource/clusterroles.yaml
config/release/install.yaml
pkg/config/config.go
pkg/webhookconfig/common.go

closes https://github.com/kyverno/kyverno/issues/2713
milestone 1.6.0
/kind bug
Install Kyverno using local changes
Kyverno Pod coming  state
Unistall Kyverno
- [] I have …

Fix: Hard-coded ClusterRoleName in OwnerRef breaks 

---

pkg/webhookconfig/configmanager.go

For cases where a policy matches the _Bindings_ kind in the "core/v1" API group and version, adjust the pertinent Webhook configuration rule to use the "pods/binding" subresource.
Doing so allows observing and reacting to the Kubernetes scheduler (and its "extenders") assigning pods to nodes, before any other system actors observe that assignment. This is an opportune moment in between the pod' creation and a kubelet starting it running.
Kyverno's code base was already "aware" of the _v1/Binding_ kind; we include it in the known API schema, and block this kind in the default filter set supplied via the "kyverno" container's `--filterK8sResources` command-line flag. Writing policies that target this kind requires editing that filter set to remove the `[Binding,*,*]` entry.
/kind feature

Allow use of "pods/binding" subresource

---

pkg/common/common.go
pkg/policy/common.go

Signed-off-by: Jose Armesto <github@armesto.net>
Fixes https://github.com/kyverno/kyverno/issues/2729
/kind bug
Don't log errors when namespace is empty, meaning when using non namespaced resources.
- [] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed …

Do not log error when resource is not namespaced

---

pkg/engine/jmespath/functions.go
pkg/engine/jmespath/functions_test.go

cc - @JimBugwadia 
Closes #2606 
/kind feature
- Add `time_since('<layout>', '<time1>', '<time2>')` JMESPath function
Policy
```yaml
metadata:
name: test-policy
spec:
rules:
- name: test-rule
match:
resources:
kinds:
- Pod
validate:
message: "Denied"
deny:
conditions:
- key: "{{ time_since('', '2021-01-02T15:04:05-07:00', '2021-01-10T03:14:05-07:00') }}"
value: 48h
```
Pod
```yaml
apiVersion: v1
kind: Pod
metadata:
name: myapp
spec:
containers:
- name: my-container
image: nginx
```
Pod is not created.
Policy
```yaml
metadata:
name: test-policy …
```

Added time_since() custom JMESPath function

---

pkg/cosign/cosign.go

https://github.com/kyverno/kyverno/issues/2739
1.5.2
/kind bug
Fix signature construction.
With this change, using an invalid key returns:
```sh
❯ kubectl run test --image=ghcr.io/jimbugwadia/pause2
Error from server: admission webhook "mutate.kyverno.svc-fail" denied the request:
resource Pod/default/test was blocked due to the following policies
attest-code-review:
attest: |-
failed to fetch attestations for ghcr.io/jimbugwadia/pause2:latest: no matching signatures:
failed to verify signature
```
-->
- [] I have added or changed …

fix signature

---

charts/kyverno/templates/servicemonitor.yaml

None.
Up for chart maintainer.
/kind feature
`.Capabilities.APIVersions.Has` function has limitations when running with `helm template`, which is common step in multiple CD tools. In order to properly resolve `Capabilities.APIVersions` `helm template` has to run with `--validate` option and connect to cluster that has Prom Operator CRDs installed.
As this template is opt-in and user has to set value to enable this, apiVersion check doesn't provide much value and can be removed.
Not applicable.
- [] I have added or changed [the documentation](https://github.com/kyverno/website) …

Don't check for Prom Operator apiVersion

---

pkg/openapi/validation.go
pkg/openapi/validation_test.go

closes https://github.com/kyverno/kyverno/issues/2609
/kind bug
1. Deploy crossplane and their gcp-provider
```
kubectl api-resources | grep -i serviceaccounts
serviceaccounts                   sa           v1                                            true         ServiceAccount
serviceaccounts                                iam.gcp.crossplane.io/v1alpha1                false        ServiceAccount 
```
2. Create Policy
```yaml
metadata:
name: test-gvk
spec:
rules:
- name: add-vault-policy-k8srole-label
exclude:
resources:
- key: namespaceKind
operator: In
values:
- platform
- ci
match:
resources:
kinds:
- …
```

change matchGVK logic

---

pkg/engine/jmespath/functions.go
pkg/engine/jmespath/functions_test.go
test/cli/test/custom-functions/policy.yaml
test/cli/test/custom-functions/resources.yaml
test/cli/test/custom-functions/test.yaml

/kind feature
- Add a custom JMESPath function `pattern_match` analogous to `regex_match`. \
Pattern match is implemented using the same [wildcard library](https://pkg.go.dev/github.com/minio/pkg@v1.1.3/wildcard) as the rest of Kyverno.
To test use the pod.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
name: myapp
labels:
customLabel: prefix-example
spec:
containers:
- name: my-container
image: nginx
```
when the policy pol.yaml
```yaml
metadata:
name: validate-pod-metadata
spec:
rules:
- match:
all:
- resources:
kinds:
- Pod
name: validate-labels
validate:
deny:
conditions:
all:
- key: '{{pattern_match(`"prefix-*"`, `"{{request.object.metadata.labels.customLabel}}"`)}}' …
```

Add `pattern_match` custom JMESPath function analogous to `regex_match`

---

charts/kyverno/templates/clusterrole.yaml
config/install.yaml
config/install_debug.yaml
config/k8s-resource/clusterroles.yaml
config/release/install.yaml
pkg/webhookconfig/common.go

/kind bug
Install Kyverno using local changes
Kyverno Pod coming  state
Unistall Kyverno

change cluster role labels

---

pkg/cosign/cosign.go
pkg/engine/imageVerify.go

Signed-off-by: Joel Kamp <joel.kamp@invitae.com>
#2790 
@JimBugwadia 
/kind bug
This PR updates the image registry credentials keychain `authn.DefaultKeychain` on calls to `engine.VerifyAndPatchImages()` to fix registry authentication failures due to short lived access token expiration. …

fix: update registry credentials on image verify

---

pkg/engine/jmespath/functions_test.go

Signed-off-by: weiwei.danny <weiwei.danny@bytedance.com>
#2273 
/kind bug
This PR updates the test cases of `path_canonicalize` custom JMESPath function to fix the unit test failures on Windows system.

fix: add Windows testcases for path_canonicalize

---

api/kyverno/v1/policy_types.go
go.sum
pkg/cosign/cosign.go
pkg/cosign/cosign_test.go

Signed-off-by: Namanl2001 <namanlakhwani@gmail.com>
https://github.com/kyverno/kyverno/issues/2591
- adding a new field `Issuer` to the policy declaration.
- using this field to add issuer check in `cosign.go`
- [] I have …

added issuer check

---

cmd/initContainer/main.go
cmd/kyverno/main.go
pkg/policy/report.go
pkg/policyreport/builder.go
pkg/policyreport/reportcontroller.go

Closes #2755 .
/kind bug
/kind cleanup
PolicyReports as well as ClusterPolicyReports from Kyverno get a special label which is used to fetch only Kyverno related resources.
Current behavior without 
```bash
kubectl get polr --show-labels -n default
NAME              PASS   FAIL …
```

Add SelectorLabel to (Cluster)PolicyReporter resources

---

go.mod
go.sum
pkg/engine/jmespath/functions.go
pkg/engine/jmespath/functions_test.go

/kind feature
This PR adds a `truncate` custom jmespath function that receives a string and length(integer) and returns a new string with only the length(integer) bytes.
This is useful for policies, where some fields are populated from the source resource but may need to be truncated to a certain length due to field size restrictions.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
name: test-very-long-name
```
```yaml
metadata:
name: test-truncate
spec:
rules:
- name: test-truncate
match:
resources:
kinds:
- v1/ServiceAccount
mutate:
metadata:
labels:
truncated-name: "{{request.object.metadata.name | truncate(@, `9`)}}"
```
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
annotations: …
```

truncate custom jmespath function

---

.github/workflows/e2e.yaml
Makefile
pkg/kyverno/test/git.go
pkg/kyverno/test/test_command.go

Signed-off-by: Abhinav Sinha <zeborg3@gmail.com>
Closes #2746
/kind feature
* Added `--git-branch` _(shorthand `-b`)_ flag for specifying the branch for the git path mentioned in `kyverno test` command.
* Added support for specifying the directory in git path having the policies which the user wants to test.
* Supported git path syntaxes for `kyverno test` following this PR:
* `kyverno test https://github.com/{owner}/{repo}/{branch}`
_(same as the old syntax for backwards compatibility; uses `main` as default branch in the absence of `{branch}`; does not support testing a specific directory in git path)_
* Example:
`kyverno test https://github.com/kyverno/policies/release-1.5`
* `kyverno test https://github.com/{owner}/{repo}/{directory} --git-branch {branch}`
* Example: …

added support for --git-branch flag and directory in git path for kyverno test cmd

---

pkg/engine/jmespath/functions.go
pkg/engine/jmespath/functions_test.go

#2836 
/kind bug
Fixes handling of negative length input value in the JMESPath custom truncate function
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
name: test-very-long-name
```
```yaml
metadata:
name: test-truncate
spec:
rules:
- name: test-truncate
match:
resources:
kinds:
- v1/ServiceAccount
mutate:
metadata:
labels:
truncated-name: "{{request.object.metadata.name | truncate(@, `-1`)}}"
```
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
annotations:
policies.kyverno.io/last-applied-patches: |
test-truncate.test-truncate.kyverno.io: added /metadata/labels
labels:
truncated-name: ""
name: test-very-long-name
```
- [] My PR contains new or altered …

jmespath truncate - handle negative input value

---

charts/kyverno/values.yaml
config/install.yaml
config/manifest/deployment.yaml

Based on the memory measurement for different sets of resources, captured in [this](https://docs.google.com/spreadsheets/d/1cCQfCtCQn6aMs7IbxXc48SnhuVxAbnBmEZ-gxxboUXw/edit?usp=sharing.) sheet by @siddharthlal25 (thank you Siddharthlal!), and a few other user's [feedback](https://kubernetes.slack.com/archives/CLGR9BJU9/p1639659703367900?thread_ts=1639616500.355300&cid=CLGR9BJU9),  `256Mi` of memory limit seems to cause OOM issue.
This PR bumps the memory request and limit based on the above observation, to 128Mi and 384Mi.

Increase Kyverno memory request and limit

---

pkg/engine/variables/vars.go
pkg/engine/variables/vars_test.go

closes https://github.com/kyverno/kyverno/issues/2863
milestone 1.6.0
/kind bug
Policy.yaml
```yaml
metadata:
annotations:
policies.kyverno.io/title: Replace Image Registry
policies.kyverno.io/minversion: 1.3.6
Rather than blocking Pods which come from outside registries,
it is also possible to mutate them so the pulls are directed to
approved registries. In some cases, those registries may function as
pull-through proxies and can fetch the image if not cached.
This policy policy mutates all images either
in the form …
```

Fix Foreach JMESPath issue

---

go.mod
go.sum
pkg/engine/jmespath/functions.go
pkg/engine/jmespath/functions_test.go
pkg/engine/variables/evaluate_test.go
pkg/engine/variables/operator/numeric.go
pkg/kyverno/test/test_command.go

#2837 
Add a custom JMESPath function semver_compare to prevent bypassing the version validation.
SBOM fragment used for testing: https://github.com/kyverno/kyverno/pull/2846#issuecomment-997671084
policy
```yaml
metadata:
name: attest-sbom
spec:
rules:
- name: check-sbom
match:
resources:
kinds:
- Pod
verifyImages:
- image: "ghcr.io/namanl2001/kyverno:*"
key: |-
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEtS69SctDWseJdFcQnpJGh3Yq3WfM
EpLCSBfCcCyTotqkFCsGjhAFiSblvmX8vn51dbnZ7cdtiahat/eehymyJg==
-----END PUBLIC KEY-----
attestations:
- predicateType: https://example.com/CycloneDX/v1
conditions:
- all:
- key: "{{ …
```

add `semver_compare` JMESPath function

---

pkg/engine/mutation.go

closes https://github.com/kyverno/kyverno/issues/2725
milestone 1.6.0
> /kind bug
Policy.yaml
```yaml
metadata:
annotations:
policies.kyverno.io/title: Replace Image Registry
spec:
rules:
- name: replace-image-registry
match:
resources:
kinds:
- Pod
preconditions:
value: "CREATE"
mutate:
foreach:
- list: "request.object.spec.containers"
spec:
containers:
- name: "{{ element.name }}"   
image: |-    
{{ regex_replace_all('^[^/]+', '{{element.image}}', 'myregistry.corp.com' )}}
```
Resource.yaml
```
apiVersion: v1
kind: Pod
metadata:
annotations:
annotation.corp.com/restrict1: foo1 …
```

Fix : Foreach  Precondition  issue

---

pkg/policyreport/builder.go
pkg/policyreport/reportcontroller.go

Cherry-pick https://github.com/kyverno/kyverno/pull/2610 to fix the policy report issue.
Related: https://github.com/kyverno/kyverno/issues/2330:
I am seeing memory increase using Kyverno v1.5.2. 
The memory kept increasing due to the stale results in reports, where the pods were deleted but the results were left in the reports. Test setup: with the best practice policies installed and cronjobs scheduled, the report results weren't cleaned up when the pods were GC-ed. 
Next: will test the fixed version and continue troubleshooting https://github.com/kyverno/kyverno/issues/2330.

Fix policy report reconciliation on resource/policy deletion

---

pkg/engine/response/response.go
pkg/engine/utils.go
pkg/engine/validation.go
pkg/policyreport/builder.go

Closes https://github.com/kyverno/kyverno/issues/2330.
/1.5.3
/enhancement
/bug
With PR https://github.com/kyverno/kyverno/pull/2648, Kyverno applies policy on all managed pods/jobs to fix the security issue. While duplicate policy results are audited in the reports, for example, when there's a CronJob installed, the report includes results for CronJob, Job, and Pod. If one has enough CronJobs scheduled in the cluster, the report will eventually be flooded and exceed its limit (ResourceExhausted). Furthermore, reportChangeRequests can no longer be merged to policy reports (due to "ResourceExhausted") thus leading to memory increase.
This PR keeps the policy application at managed pods/jobs level, while only reporting the results for …

Don't generate policy report on managed pod/job

---

pkg/webhooks/common.go

Signed-off-by: anushkamittal20 <anumittal4641@gmail.com>
closes #2819 
/milestone 1.5.3
> /kind bug
We have added a check that ensures the Roles and ClusterRoles within any/all are checked and not missed.
pol.yaml
```
metadata:
name: exc
spec:
rules:
- name: match-criticals-except-given-rbac
match:
all:
- resources:
kinds:
- Pod
selector:
matchLabels:
app: critical
exclude:
all:
- clusterRoles:
- cluster-admin
validate:
message: You must disable SA token. Roles are {{request.roles}} and cluster roles are {{request.clusterRoles}}
pattern:
spec:
automountServiceAccountToken: false
```
role.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
name: jim
rules: …
```

added check for any/all

---

.github/workflows/image.yaml
.github/workflows/release.yaml

added missing `|` character which was leading the workflows to fail with this error: https://github.com/kyverno/kyverno/runs/4704334691?check_suite_focus=true#step:9:1
cc: @JimBugwadia

fix: cosign command in github action workflows

---

pkg/tls/certRenewer.go
pkg/tls/reader.go
pkg/webhookconfig/registration.go

Closes #2805 
/milestone 1.5.3
/kind bug
- Disable auto-cleanup of Kyverno secrets on pod deletion
- Annotate CA Secret and verify consistency with current Deployment UID
- Test as described [here](https://github.com/kyverno/kyverno/issues/2805#issue-1074434002).
- Upgrade test from 1.5.2

Fix TLS inconsitency in HA

---

.github/workflows/image.yaml
Makefile

fix for #2920 
tested the same workflow in a separate repo https://github.com/Namanl2001/learning-github/blob/master/.github/workflows/cosign.yaml through which I'm successfully able to sign the image but not able write the image back in the registry due to some permission issues (tried multiple ways to resolve it but no help) https://github.com/Namanl2001/learning-github/runs/4727092772?check_suite_focus=true#step:7:13 
I hope changes in this pr should work fine in the kyverno repo 🤞

Fixing the CI job to push images

---

charts/kyverno/values.yaml
config/install.yaml
config/manifest/deployment.yaml
pkg/webhookconfig/registration.go

Signed-off-by: Abhinav Sinha <zeborg3@gmail.com>
Closes #2347, #2761 
`/milestone 1.6.0`
`/kind bug`
Updated the `INIT_CONFIG` value in the Kyverno Deployment with the current name of default Kyverno ConfigMap, i.e., `kyverno`. Also synced changes within comments referring to the value of `INIT_CONFIG` in the codebase. …

Corrected the value of `INIT_CONFIG` env in deployment

---

pkg/tls/reader.go

Closes #2928
cc - @realshuting, @prateekpandey14 
/milestone 1.5.4
- [] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr …

Fix condition for rolling update

---

pkg/tls/certRenewer.go

#2928 
/milestone 1.5.4
/kind bug
Add check in `ValidCert()` for addition of missing Deployment UID annotation. …

ValidCert Secret Annotation Check

---

pkg/engine/jmespath/functions.go
pkg/engine/jmespath/functions_test.go
test/cli/test/custom-functions/policy.yaml
test/cli/test/custom-functions/resources.yaml
test/cli/test/custom-functions/test.yaml

Fixes #2940
This PR  adds a parse_json JMESPath function which complements the upstream to_string JMESPath function. More details around usage in the attached issue.
/kind feature
This change adds a `parse_json` JMESPath function that is capable of parsing arbitrary json strings to correct objects. Examples noted below. Related docs PR https://github.com/kyverno/website/pull/433
Note - They have also been added to CLI tests.
cf.yaml
```yaml
---
apiVersion: v1
metadata:
name: valid-test
annotations:
test: |
{"a": "b"}
---
apiVersion: v1
metadata:
name: invalid-test
annotations:
test: |
{"a": "not-b"}
```
policy.yaml
```yaml
metadata:
name: …
```

Add parse_json function the decode json strings

---

cmd/cli/kubectl-kyverno/Dockerfile
cmd/initContainer/Dockerfile
cmd/kyverno/Dockerfile

#2967 
/kind cleanup
Update Golang version in Dockerfiles from 1.7.2 to 1.7.6 to inherit bug and security fixes from Go patch releases
Proof can be achieved through the following commands:
```shell
docker build -f cmd/cli/kubectl-kyverno/Dockerfile  .
docker build -f cmd/initContainer/Dockerfile  .
docker build -f cmd/kyverno/Dockerfile  .
```
> Change does not alter Kyverno functionality and does not require new tests or documentation.   Existing tests are sufficient.

chore: bump go version used to build images

---

pkg/policymutation/cronjob.go
pkg/policymutation/policymutation.go
pkg/policymutation/policymutation_test.go
test/policy/mutate/policy_mutate_pod_foreach_with_context.yaml

Closes #2988
/kind bug
```yaml
apiVersion : kyverno.io/v1
metadata:
name: resolve-image
spec:
rules:
- name: resolve-image-containers
match:
resources:
kinds:
- Pod
preconditions:
all:
- key: "{{request.operation}}"
operator: In
value:
- CREATE
- UPDATE
mutate:
foreach:
- list: "request.object.spec.containers"
context:
- name: dictionary
configMap:
name: some-config-map
namespace: some-namespace 
spec:
containers:
- name: "{{ element.name }}"           
image: "{{ dictionary.data.image }}"
```
Applying the above with `kubectl apply -f policy.yaml --dry-run=server -oyaml` it should output the correct set of rules instead of erroring out like it currently …

Fix autogen issue with cronjob generator and foreach pod generator

---

.goreleaser.yml

Adds arm64 CLI release per the discussion here: #2888 
I believe that the arm64 binary for the CLI is already being built by CI and wasn't being published by go-releaser.
https://github.com/kyverno/kyverno/blob/main/Makefile#L154-L157
To that end I do wonder why there's a specific build target just for `amd64` GOARCH, would appreciate clarification on that.

Add arm64 goarch to go releaser

---

pkg/engine/variables/vars.go
test/e2e/mutate/config.go
test/e2e/mutate/resources.go

Fixes #2971
/kind bug
This was a very subtle bug where preconditions for rules get var subs. correctly but not for foreach preconditions. The issue was that the json traversal method used for var substitution relies on the input document being a json document and not a struct. foreach preconditions (AnyAllConditions) are of a different type than rule preconditions(apiextensions.JSON). The latter is compatible with the traversal method, the former isn't. The fix involved converting the foreach precondition to an untyped object (map like) which allows the json traversal to work properly.
An E2E test has been added to replicate the behavior described at https://github.com/kyverno/kyverno/issues/2971 which is now …

Fix variable substitution for foreach preconditions

---

cmd/kyverno/main.go

Fixes https://github.com/kyverno/kyverno/issues/2951.
1.6.0
Added the flag `webhookRegistrationTimeout` to configure the timeout for the webhook registration. The default is set to 120s.
See comments in https://github.com/kyverno/kyverno/issues/2951.
https://github.com/kyverno/website/issues/447

Add flag webhookRegistrationTimeout

---

pkg/engine/jmespath/functions.go
pkg/engine/jmespath/functions_test.go
test/cli/test/custom-functions/kyverno-test.yaml
test/cli/test/custom-functions/policy.yaml
test/cli/test/custom-functions/resources.yaml

Fixes #2998 
Fixes #2693 
This PR adds a `parse_yaml` function that does the following - 
- Convert YAML string to JSON string: This is necessary since YAML is a superset of JSON in terms of the types you can define (for eg. things like `Inf`, `Nan` etc.). We first convert YAML to a JSON serializable string if possible. If it is not possible, the rule will throw an appropriate error describing the error in conversion.
- Deserialize JSON string to an object: We then take the output JSON string and convert it to an object so that it can be queried using JMESPath.
/kind feature
---
Policy to validate some keys inside a YAML string
<details>
<summary>policy</summary>
```yaml
kind: …
```

Add a parse_yaml function

---

.krew.yaml

N/A
N/A
/kind feature
Adds ARM64 binary to Krew plugin config. 
N/A
:warning: **Note**: Requires a new version of Kyverno to be released with the latest goreleaser-action so the binary is built and uploaded to the GitHub release.

Added Mac ARM64 build to Krew config

---

cmd/kyverno/main.go
pkg/engine/generation.go
pkg/engine/imageVerify.go
pkg/engine/jsonContext.go
pkg/engine/mutation.go
pkg/engine/policyContext.go
pkg/engine/validation.go
pkg/generate/generate.go
pkg/generate/generate_controller.go
pkg/policy/apply.go
pkg/policy/common.go
pkg/policy/existing.go
pkg/policy/generate/validate.go
pkg/policy/policy_controller.go
pkg/webhooks/generation.go
pkg/webhooks/server.go
pkg/webhooks/validate_audit.go

Fixes https://github.com/kyverno/kyverno/issues/3012.
/1.6.0
/enhancement
This PR removes `resourceCache` from the background controller, generate controller, and the webhook server. With the change, the configmap lookup is now using the client call to fetch the given configmap.
1. Tested the configmap lookup with the following policy:
```yaml
metadata:
name: mutate-env-label
spec:
rules:
- name: mutate-env-label
context:
- name: dictionary
configMap:
name: datastore
match:
resources:
kinds:
- Deployment
mutate:
metadata:
annotations:
kyverno.io/created-by: "{{ request.userInfo.username }}"
labels:
my-environment-name: "{{ dictionary.data.env }}"
```
```yaml
apiVersion: v1
kind: …
```

Remove `resourceCache` from engine

---

pkg/generate/status.go
pkg/generate/util.go

fixes:#2547
> /kind bug
This PR addresses the `object has been modified, please apply your changes to the latest version and try again` issue we see a lot in the generate controller logs with success status while updating  GenereteRequest resource. Similar changes can be done with Failed and Skip status update as well.
N/A

fix(generate): use JSON patch for GenerateRequests status updates 

---

pkg/webhookconfig/registration.go

Closes https://github.com/kyverno/kyverno/issues/3008.
/1.6.0
/bug
Clean up webhook configurations when kyverno deployment is not found.
With Kyverno running in the cluster, if I delete the deployment by `k delete -n kyverno deploy kyverno`, the webhooks are cleaned up automatically.
Here's the log:
```
I0118 15:42:07.305534       1 controller.go:129] EventGenerator "msg"="shutting down"
I0118 15:42:07.305579       1 reportrequest.go:192] ReportChangeRequestGenerator "msg"="shutting down"
I0118 15:42:07.305589       1 informer.go:118] PolicyCacheController "msg"="shutting down"
I0118 15:42:07.305667       1 policy_controller.go:448] PolicyController "msg"="shutting down"
I0118 15:42:07.305684       1 reportcontroller.go:274] …
```

Clean up webhook configurations when cannot find kyverno deployment

---

pkg/policy/common.go
pkg/policy/existing.go
pkg/policy/report.go

https://github.com/kyverno/kyverno/issues/2793.
/1.6.0
/enhancement
Previously with M policies and N namespaces, Kyverno lists matching resources M*N times in the background controller. After this change, Kyerno lists resources M times in order to reduce throttling requests.
1. Verified reports are generated successfully and correctly: results are the same for the same setup before and after the change.
2. With 80 Cronjobs, 10k ConfigMaps, best-practices policies in place, here's the Kyverno Memory usage 
- for 1.5.2-xxx Kyverno:
```
root@da-m3-large-x86-02:~# kubectl -n kyverno top pod
NAME                       CPU(cores)   MEMORY(bytes)
kyverno-5d496f9bc9-55f7h   227m         414Mi
```
- with the latest change (remove dynamic informers): …

Background controller: list resources once per policy 

---

pkg/tls/certRenewer.go
pkg/webhookconfig/registration.go

`/milestone 1.6.0`.
-  Add verbose level in info success update logs , logged in each 30 sec 
-  fix deployment replica count conversion issue

fix deployment replica type conversion and refactor webhook logs 

---

pkg/policymutation/policymutation.go
pkg/policymutation/policymutation_test.go
pkg/webhooks/policymutation_test.go

Closes #2751
/kind bug
[missingAutogenRules()](https://github.com/kyverno/kyverno/blob/5c16ee738af04cfeb41b0fc4557d06762d268651/pkg/policy/policy_controller.go#L575) updates `spec.rules` when policy doesn't mention Pod. Setting `autogen-controller` annotation to `none` by default in such a case solves the issue.
Policy
```yaml
apiVersion : kyverno.io/v1
metadata:
name: restrict-image-registries
spec:
rules:
- name: validate-registries
match:
resources:
kinds:
- Namespace
validate:
message: "Images may only come from our internal enterprise registry."
pattern:
metadata:
name: test-ns
```
CLI
```bash
$ k get cpol restrict-image-registries -o yaml …
```

Disable autogen for policies without Pod

---

pkg/cosign/cosign.go

closes:
- https://github.com/kyverno/kyverno/issues/3014 verified my changes for this locally
- https://github.com/kyverno/kyverno/issues/3017 needs to be verified by the user as it requires an image signed by a GCP KMS key, and Kyverno needs to have GCP credentials configured

fix for cosign image verification in v1.5.4

---

pkg/engine/jmespath/arithmetic.go
pkg/engine/jmespath/functions_test.go

cc - @chipzoller, @realshuting 
Closes #2985
/kind design
Make division output unitless incase both dividend and divisor have the same base unit
Policy
```yaml
apiVersion : kyverno.io/v1
metadata:
name: requests-limits
spec:
rules:
- name: check-requests-limits
match:
resources:
kinds:
- Pod
validate:
message: Limits may not exceed 2.5x the requests.
foreach:
- list: "request.object.spec.containers"
deny:
conditions:
any:
- key: "{{ divide('{{ element.resources.limits.memory }}', '{{ element.resources.requests.memory }}') }}"
value: 2.5
```
Pod
```yaml
apiVersion: v1
kind: Pod
metadata:
name: busybox
spec:
containers:
- image: asdfsasdffs:1.28 …
```

Update division for same units

---

pkg/webhookconfig/configmanager.go

Fixes https://github.com/kyverno/kyverno/issues/3041.
/1.6.0
/bug
List cluster policies for Namespaced policy reconciliation.
Tested with the following policy that generates mutate and validate namespace policies for new the namespace.
```yaml
metadata:
name: require-namespace-label
annotations:
policies.kyverno.io/title: Require Namespace Labels
policies.kyverno.io/category: Core
policies.kyverno.io/severity: high
policies.kyverno.io/subject: Namespace
Namespaces are required to have POC and AppID labels
spec:
rules:
- name: require-labels
match:
resources:
kinds:
- Namespace
validate:
pattern:
metadata:
labels: …
```

Fix dynamic webhook for namespace policies

---

pkg/engine/mutate/patch/patchesUtils.go

From slack - https://kubernetes.slack.com/archives/CLGR9BJU9/p1642983927127400.
/1.6.0
/bug
```yaml
metadata:
name: namespace-policy
spec:
rules:
- name: namespace-mutate-add-owner-reference
match:
resources:
kinds:
- Namespace
mutate:
metadata:
ownerReferences:
- uid: 4d734737-41fa-4f74-8710-7375166a931f
apiVersion: v1
kind: Namespace
name: kube-system
```
```yaml
✗ k get ns test -o yaml
apiVersion: v1
kind: Namespace
metadata:
annotations:
policies.kyverno.io/last-applied-patches: |
namespace-mutate-add-owner-reference.namespace-policy.kyverno.io: added /metadata/ownerReferences
creationTimestamp: "2022-01-24T03:55:45Z"
labels:
kubernetes.io/metadata.name: test
name: test …
```

Fix mutating ownerReferences

---

go.mod
go.sum
pkg/cosign/cosign.go
pkg/engine/jsonContext.go
pkg/registryclient/client.go

Currently if image pull secrets are specified the default key chain grows linearly with each policy evaluation causing a run off memory leak. 
/kind bug

Fix memory leak when updating ggcr keychain

---

api/kyverno/v1/policy_types.go
charts/kyverno/templates/crds.yaml
config/crds/kyverno.io_clusterpolicies.yaml
config/crds/kyverno.io_policies.yaml
config/install.yaml
config/install_debug.yaml

fix: typo Cluter to Cluster

---

pkg/registryclient/client.go

Related PR #3088 
/kind bug
This PR is a follow up on #3088 and sets the kyverno default keychain to be the ggcr keychain when it is not Initialized. Although a keychain with value nil allows for anonymous access, the default keychain can take into account docker credential semantics which might be useful even if image pull secrets are not specified especially in the future if we add registry access to kyverno CLI for local usage and we wish to provide auth credentials via docker config.
This is also the default behavior of GGCR (using the defaultkeychain instead of nil)

Fix the kyverno default keychain value to be the ggcr default keychain when uninitialized

---

charts/kyverno/templates/poddisruptionbudget.yaml

Fixes #2983
/kind bug
We updated our helm charts and install manifests to use policy/v1/PodDisruptionBudget as a part of fixing https://github.com/kyverno/kyverno/pull/2561
policy/v1 api group is not available in K8s versions 1.20 and below.
This PR adds a capabilities check to our helm charts to check if policy/v1 api group is available or not before using it. If it is not available, we fallback to policy/v1beta1. For our direct install manifest, we do not use pod disruption budget by default so I have left it as is.

Add b/w compat support for K8s version 1.20 and below for Kyverno 1.6 (cherry-pick v1.6)

---

charts/kyverno/templates/poddisruptionbudget.yaml

Fixes #2983
/kind bug
We updated our helm charts and install manifests to use policy/v1/PodDisruptionBudget as a part of fixing https://github.com/kyverno/kyverno/pull/2561
policy/v1 api group is not available in K8s versions 1.20 and below.
This PR adds a capabilities check to our helm charts to check if policy/v1 api group is available or not before using it. If it is not available, we fallback to policy/v1beta1. For our direct install manifest, we do not use pod disruption budget by default so I have left it as is.

Add b/w compat support for K8s version 1.20 and below for Kyverno 1.7

---

pkg/cosign/cosign.go
pkg/cosign/cosign_test.go

adding tests for cosign keyless image verification feature along with a small fix which does not make issuer and subject mismatch to work

Adding tests for cosign keyless image verification

---

pkg/engine/context/imageutils.go

Signed-off-by: Abhinav Sinha <abhinav@nirmata.com>
Closes #3141 
`/milestone 1.6.0`
`/kind bug`
* Added non-existence check for `image` key in `container` map before type conversion in `func convertToImageInfo(containers []interface{}, jsonPath string) (images []*ContainerImage, err error)
`
Follow the steps in this [comment](https://github.com/kyverno/kyverno/issues/3141#issuecomment-1026342495) to reproduce the issue
```logos
2022/01/31 20:42:28 http: panic serving 10.239.125.13:57878: interface conversion: interface {} is nil, not string
goroutine 1714041 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x1b07ee0, 0xc005489680})
/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/kyverno/kyverno/pkg/engine/context.convertToImageInfo( …
```

Fix kyverno panic with `PodSpec.containers` JSON merge patch w/o image

---

charts/kyverno-policies/Chart.yaml
charts/kyverno/Chart.yaml

This PR bumps Helm charts versions to fix chart testing failure https://github.com/kyverno/kyverno/pull/3126/#issuecomment-1028715938. I will send a separate PR to cherry-pick changes to release-1.6 including Helm changes.
The comparison between `release-1.6` and `main` can be found (you can locate chart changes in `charts/...`) https://github.com/kyverno/kyverno/compare/release-1.6...realshuting:bump_chart_versions.

Bump chart versions in `main`

---

pkg/engine/jmespath/functions.go
pkg/engine/jmespath/new.go
pkg/kyverno/jp/jp_command.go
pkg/kyverno/main.go

Fixes #3167 
/kind feature
Adds a `kyverno jp` command to test JMESPath expressions with Kyverno grammar.
```
$ ./cmd/cli/kubectl-kyverno/kyverno jp --help
Provides a command-line interface to JMESPath, enhanced with Kyverno specific custom functions
Usage:
kyverno jp [flags]
Flags:
--ast                Only print the AST of the parsed expression.  Do not rely on this output, only useful for debugging purposes
-c, --compact            Produce compact JSON output that omits nonessential whitespace
-e, --expr-file string   Read JMESPath expression from the specified file
-f, --filename string    Read input JSON from a file instead of stdin
-h, --help               help for jp
-l, --list-functions     Output a list of …
```

Add a kyverno jp command to test jmespath expressions

---

Makefile
charts/kyverno/values.yaml

Fixes #3172 
/kind bug
Reverts `tagTest` back to `tag` for the test image (busybox) but keeps the functionality from #3159 
```
> make helm-test-values
sed -i -e "s|nameOverride:.*|nameOverride: kyverno|g" charts/kyverno/values.yaml
sed -i -e "s|fullnameOverride:.*|fullnameOverride: kyverno|g" charts/kyverno/values.yaml
sed -i -e "s|namespace:.*|namespace: kyverno|g" charts/kyverno/values.yaml
sed -i -e "s|tag:  # replaced in e2e tests.*|tag: 1.6-dev-122-ga9062a18|" charts/kyverno/values.yaml
> git diff | cat
diff --git a/charts/kyverno/values.yaml b/charts/kyverno/values.yaml
index 2805380d..27b2c96a 100644
--- a/charts/kyverno/values.yaml
+++ b/charts/kyverno/values.yaml
@@ -1,6 +1,6 @@
-nameOverride: …
```

Fix unused tagTest in helm chart tests

---

pkg/kyverno/test/test_command.go

Removed unnecessary indentation on line 107 to avoid confusion in 'kyverno test'
Fixes https://github.com/kyverno/kyverno/issues/3077
Issue Opened by: @chipzoller
> /kind bug
Fixed the indentation error by removing the extra tab space.
Thank you for this opportunity to contribute to such a massive project. I would love to learn more and contribute to this amazing community.

Indentation fix

---

pkg/webhookconfig/registration.go

1.6.1
/enhancement
Before this PR, Kyerno updates `namespaceSelector` of webhook configurations for every policy reconciliation. This results in an issue that Kyverno fails to update webhooks due to frequent updates (via dynamic client). This PR updates the webhooks only if the `namespaceSelector` is not nil and the value has changed.
Ideally, we should switch to use the typed client to adviod such an issue.

Skip updating webhook configs if namespaceSelector is nil

---

.github/workflows/cli.yaml
.github/workflows/e2e.yaml
.github/workflows/image-build.yaml
.github/workflows/tests.yaml
Makefile

Fixes #3003
/kind cleanup
Does a simple change to E2E tests to use local go builds rather than building it inside the container. This should significantly improve CI timings enough to allow us to test against a matrix of K8s version. More PRs can follow to improve CI timings for other workflows like builds.

Improve E2E test CI timings

---

.github/workflows/helm-release.yaml

This is cherry-pick of #3268 to release-1.6 branch.

release-1.6: Fix Helm releasing to preserve creation timestamps (#3268)

---

charts/kyverno/templates/deployment.yaml
config/install.yaml
config/manifest/deployment.yaml
config/release/install.yaml

/kind cleanup
Kyverno manifests are incompatible with the restricted Pod Security Standards included with Kubernetes 1.22 and 1.23 because the Pod Security admission controller looks for "ALL" in securityContext.capabilities.drop, but does not accept "all".
The value is set here: https://github.com/kubernetes/pod-security-admission/blob/1b741f89aa417a489aa68ec2d0cc65eeca8dff80/policy/check_capabilities_restricted.go#L30
And the comparison is here: https://github.com/kubernetes/pod-security-admission/blob/1b741f89aa417a489aa68ec2d0cc65eeca8dff80/policy/check_capabilities_restricted.go#L88
The manifests generated by the Helm chart, at least, are compatible with the `restricted` Pod Security Standard when this patch is applied. Accepting this patch will save cluster administrators from …

Modify capabilities for compatibility with Pod Security

---

.github/workflows/image.yaml
.github/workflows/reuse.yaml
Makefile

currently `latest` tag gets updated after each merge on the `main` or `release` branch, ref: https://github.com/kyverno/kyverno/pkgs/container/kyverno
after this pr, `latest` tag will get updated only for merge on `main` and in this way `latest` will always point to the `main` branch :)

`latest` tag pointing to main

---

go.mod
go.sum
pkg/policy/validate.go
pkg/policy/validate_test.go

fixes:#3139
`/milestone 1.6.1`.
> /kind bug
- Validate the policy creation based on the in-memory cached matched Kind
- With this change policy will be block  while applying if matched resource not found in cache.
```sh
$ kubectl create -f policy.yaml 
Error from server: error when creating "policy.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: the kind defined in the any match resource is invalid, err: unable to convert GVK to GVR, [Provisioner], err: kind 'Provisioner' not found in apiVersion ''
```
```yaml
metadata:
name: add-karpenter-aws-provider
annotations:
Mutates Karpenter Provisioner resources to add the …
```

validate and block policy based on the matched kind cache

---

.github/workflows/image-build.yaml
.github/workflows/reuse.yaml

Signed-off-by: skuethe <56306041+skuethe@users.noreply.github.com>
#3292 
/kind bug
This fixes github workflow execution for building the multi platform container images using docker buildx.
The error was introduced with #3277 as docker buildx does not support s390x out of the box - it needs QEMU setup for this.
Adding a "Set up QEMU" step before every "Set up Docker Buildx" step fixes this issue.

fix: add support for other platforms before executing docker buildx

---

.github/workflows/cli.yaml
Makefile
pkg/kyverno/test/test_command.go

Fixes #3288 
/kind feature
We were previously instantiating the open api controller on each test run. This is a particularly expensive initialisation which was costing us more than a second for each test directory. If we move this to once per test command we can dramatically reduce our test times.
Without this change `kyverno test https://github.com/kyverno/policies --git-branch main` takes 27s. With this change it reduces down to 6s.

Improve CLI test times by instantiating openapi controller once

---

charts/kyverno-policies/templates/baseline/disallow-capabilities.yaml
charts/kyverno-policies/templates/baseline/disallow-host-namespaces.yaml
charts/kyverno-policies/templates/baseline/disallow-host-path.yaml
charts/kyverno-policies/templates/baseline/disallow-host-ports.yaml
charts/kyverno-policies/templates/baseline/disallow-host-process.yaml
charts/kyverno-policies/templates/baseline/disallow-privileged-containers.yaml
charts/kyverno-policies/templates/baseline/disallow-proc-mount.yaml
charts/kyverno-policies/templates/baseline/disallow-selinux.yaml
charts/kyverno-policies/templates/baseline/restrict-apparmor-profiles.yaml
charts/kyverno-policies/templates/baseline/restrict-seccomp.yaml
charts/kyverno-policies/templates/baseline/restrict-sysctls.yaml
charts/kyverno-policies/templates/other/require-non-root-groups.yaml
charts/kyverno-policies/templates/restricted/disallow-capabilities-strict.yaml
charts/kyverno-policies/templates/restricted/disallow-privilege-escalation.yaml
charts/kyverno-policies/templates/restricted/require-run-as-non-root-user.yaml
charts/kyverno-policies/templates/restricted/require-run-as-nonroot.yaml
charts/kyverno-policies/templates/restricted/restrict-seccomp-strict.yaml
charts/kyverno-policies/templates/restricted/restrict-volume-types.yaml
charts/kyverno-policies/values.yaml

This PR adds support for background mode configuration in kyverno-policies chart.
This is useful when configuring exclusion based on infos that are not available in background mode.
Else, the following message is triggered:
```
Error: release kyverno-policies failed, and has been uninstalled due to atomic being set: admission webhook "validate-policy.kyverno.svc" denied the request: only select variables are allowed in background mode. Set spec.background=false to disable background mode for this policy rule: invalid variable used at path: spec/rules[0]/exclude/all[0]/subjects 
```

feat: support background mode configuration in kyverno-policies chart

---

charts/kyverno/templates/clusterrole.yaml

Bug in helm chart when uses generatecontrollerExtraResources in `values.yaml`.  The indentation of specific generate rule in [ClusterRole](https://github.com/kyverno/kyverno/blob/main/charts/kyverno/templates/clusterrole.yaml#L132-L143) is wrong.
Error message: `Error: YAML parse error on kyverno/templates/clusterrole.yaml: error converting YAML to JSON: yaml: line 56: did not find expected key`
/kind bug
Apply whitespaces to fix indentation of rule in Cluster Role.
Command to reproduce error: `helm template kyverno kyverno/kyverno --set generatecontrollerExtraResources\[0\]=services --version=2.3.0 --debug`
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: kyverno:generate
labels: 
app.kubernetes.io/component: kyverno
app.kubernetes.io/instance: kyverno …
```

fix: helm chart broken when use generatecontrollerExtraResources

---

Makefile

`BuildVersion` for `1.6.1-rc2` should be `v1.6.1-rc2` and not `v1.6.1-rc1-14-g5d17bbcfd` 
ref: https://github.com/kyverno/kyverno/runs/5365196710?check_suite_focus=true#step:19:226

changing git command

---

pkg/policy/policy_controller.go
pkg/policymutation/policymutation.go
pkg/policymutation/policymutation_test.go

This PR passes only the policy spec instead of the whole policy when possible.
This is a preliminary PR, I would like to introduce an `autogen` package next.

refactor: pass only spec instead of whole policy when possible

---

.github/workflows/helm-test.yaml

This PR fixes an incorrect path in helm-test workflow.
It checks only the `kyverno` chart but ignores the `kyverno-policies` one.

fix: incorrect path in helm-test workflow

---

pkg/policy/validate.go
test/cli/test/any-all-wildcard/kyverno-test.yaml
test/cli/test/any-all-wildcard/policy.yaml
test/cli/test/any-all-wildcard/resource.yaml
test/cli/test/any-all-wildcard/test.yaml

closes : https://github.com/kyverno/kyverno/issues/3340
/kind bug
1. Create this policy.
```yaml
metadata:
name: disallow-protected-namespaces
spec:
rules:
- name: disallow
match:
all:
- resources:
kinds:
- "*"
namespaces:
- "namespace1"
- "namespace2"
validate:
message: "This resource is protected and changes are not allowed."
deny: {}
```
```yaml
metadata:
name: disallow-protected-namespaces
spec:
rules:
- name: disallow
match:
any:
- resources:
kinds:
- "*"
namespaces:
- "namespace1"
- "namespace2"
validate:
message: "This …
```

Fix any_all wildcard issue

---

pkg/cosign/cosign.go

Signed-off-by: Ivan Wallis <iwallis@gmail.com>
When attempting to verify a signed image using RSA you get:
```
kubectl run signed --image=localhost:5000/alpine:latest
Error from server: admission webhook "mutate.kyverno.svc-fail" denied the request: 
resource Pod/default/signed was blocked due to the following policies
check-image:
check-image: 'image verification failed for localhost:5000/alpine:latest: loading
credentials: pem to ecdsa: invalid public key: was *rsa.PublicKey, require *ecdsa.PublicKey'
```
/kind feature
Updates signature verification process to support RSA, ECDSA and EDDSA public keys as supported by cosign.

support RSA, ECDSA and EDDSA public key verification

---

pkg/autogen/rule.go
pkg/autogen/utils.go
pkg/policy/validate.go
pkg/policy/validate_test.go
pkg/utils/util.go

closes : https://github.com/kyverno/kyverno/issues/3370
/kind bug
1. Create this policy.
```yaml
---
metadata:
name: deny-exec-to-pod
annotations:
policies.kyverno.io/title: Block Pod Exec
policies.kyverno.io/minversion: 1.4.2
The `exec` command may be used to gain shell access, or run other commands, in a Pod's container. While this can
be useful for troubleshooting purposes, it could represent an attack vector and is discouraged.
spec:
rules:
- name: deny-pod-exec
match:
resources:
kinds:
- PodExecOptions
preconditions: …
```

fix PodExecOptions issue

---

pkg/policy/existing.go
pkg/policy/validate_test.go

closes : https://github.com/kyverno/kyverno/issues/3349
/kind bug
1. create NetworkPolicy
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: test-network-policy
spec:
podSelector:
matchLabels:
role: db
policyTypes:
- Ingress
- Egress
```
2 . Create this policy.
```yaml
---
metadata:
name: np-test
spec:
rules:
- name: no-LoadBalancer
match:
any:
- resources:
kinds:
- networking.k8s.io/v1/NetworkPolicy
validate:
message: "np-test"
pattern:
metadata:
name: "?*"
```
`The error mention  the issue of **policyController "msg"="failed to find resource" "error"="kind 'networking.k8s.io/v1/NetworkPolicy'**   Fixed …

Fix for GVK not working for existing resources policy

---

config/install.yaml
pkg/kyverno/apply/apply_command.go
pkg/kyverno/common/fetch.go
pkg/kyverno/test/test_command.go
pkg/kyverno/validate/command.go
pkg/policy/validate.go
pkg/policy/validate_test.go
pkg/webhooks/policyvalidation.go

Closes:#1381, #3156 
/kind design
* Return a warning as part of the admission response when a mutate policy is applied directly to pods using `patchesJson6902`
* Applied the below manifest (re: 1381) which is referenced within the issue:
```yaml
metadata:
name: add-node-selector
spec:
rules:
- name: patch-pod-controllers
match:
resources:
kinds:
- Pod
mutate:
- path: "/spec/nodeSelector"
op: add
value: {"node.kubernetes.io/role": "test"}
- path: "/spec/tolerations/-"
op: add
value: {"key": "node-role.kubernetes.io/test", "effect": "NoSchedule", "operator": "Exists"}
```
When the above policy is applied, a warning is returned as part of the response:
* Applied the below manifest (re: 3158) to return a warning as part of the …

Return warning on admission response when mutating pods

---

cmd/kyverno/main.go
pkg/webhookconfig/monitor.go
pkg/webhookconfig/registration.go
pkg/webhookconfig/status.go
pkg/webhooks/checker.go
pkg/webhooks/server.go

Closes https://github.com/kyverno/kyverno/issues/3265.
Closes https://github.com/kyverno/kyverno/issues/3286.
/1.6.2
/bug
This PR fixes webhook re-creation issue when the Kyverno is installed with multiple replicas and no policies. 
When we support `namespaceSelector` configuration of the webhook, it added a blocking call which blocks the webhook monitor from updating the `kyverno.io/last-request-time` annotation. Due to outdated request timestamp, Kyverno treats it as a webhook failure thus keeps re-creating webhook configurations.
In addition to the bug fix, this PR also switched to use the typed client to update/get Kyverno deployment, this avoids failures when using dynamic client, i.e., 
```
the object has been modified; please apply your changes to the latest version and try again …
```

Fix webhook re-creation error

---

pkg/webhookconfig/resource.go

Closes https://github.com/kyverno/kyverno/issues/3360.
/1.6.2
/bug
When `autoUpdateWebhooks` is set to false, Kyverno registers both mutating and validating webhooks with a single rule that matches "*", and the failure policy is set to `Ignore`.
With this change, the pod creation passed through when Kyverno pod was not running.
```
✗ k get -n kyverno pod                                  
NAME                       READY   STATUS             RESTARTS   AGE
kyverno-5b4cf6dd5b-rpxsr   0/1     ImagePullBackOff   0          2m54s
```
Pod was created successfully.
```
✗ k run nginx --image=nginx:latest                                 
pod/nginx created
```
mutatingwebhookconfiguration is registered with a single rule and `failurePolicy=Ignore`:
```
✗ k get mutatingwebhookconfigurations …
```

Fix webhook configuration issue when auto update is disabled

---

pkg/webhookconfig/configmanager.go
pkg/webhookconfig/configmanager_test.go

#3380
/kind bug
Add a function webhookRulesEqual to handle edge cases in comparing the internal representation of webhook rules with what is currently on the API server's webhook object.
At the moment the equals comparison always returns false, so the webhook is always updated.
The first commit moves the current method of comparison (reflect.DeepEqual) into the function, and adds a test that shows the issue. Any test cases that should be returning equal are failing.
```
--- FAIL: TestRulesEqual (0.00s)
--- FAIL: TestRulesEqual/empty-equal (0.00s)
--- FAIL: TestRulesEqual/configmaps-equal (0.00s)
--- FAIL: TestRulesEqual/cm-secrets-equal (0.00s)
--- PASS: TestRulesEqual/add-configmaps (0.00s)
--- PASS: TestRulesEqual/add-secrets (0.00s)
```
The second commit expands the function to account …

Fix check for generated webhook rules being equal to what the API server has

---

pkg/kyverno/common/common.go

closes : https://github.com/kyverno/kyverno/issues/3435
/kind bug
Applied on local kind cluster
```
kubectl kyverno apply test/cli/policy.yaml --cluster                 
Applying 1 policy to 13 resources... 
(Total number of result count may vary as the policy is mutated by Kyverno. To check the mutated policy please try with log level 5)
pass: 13, fail: 0, warn: 0, error: 0, skip: 26 
```
with resource. yaml
```
kubectl kyverno  apply test/cli/policy.yaml -r test/cli/resources.yaml
Applying 1 policy to 2 resources... 
(Total number of result count may vary as the policy is mutated by Kyverno. To check the mutated policy please try with log level 5)
policy disallow-latest-tag -> resource …
```

Fix cli apply command panic for --cluster flag

---

pkg/policymutation/policymutation.go

This PR reduces policy mutations.
`background`, `validationFailureAction` and `failurePolicy` are now defaulted at runtime and can be removed from the mutation webhook.
Only when autogen internals feature flag is on for now.

refactor: reduce policy mutations

---

pkg/engine/context/context.go
pkg/engine/context/context_test.go
pkg/engine/context/evaluate.go
pkg/engine/context/evaluate_test.go
pkg/engine/context/imageutils.go
pkg/engine/context/imageutils_test.go
pkg/engine/context/utils.go
pkg/engine/forceMutate.go
pkg/engine/forceMutate_test.go
pkg/engine/imageVerify.go
pkg/engine/imageVerify_test.go
pkg/engine/jsonContext.go
pkg/engine/mutate/mutation.go
pkg/engine/mutation.go
pkg/engine/mutation_test.go
pkg/engine/policyContext.go
pkg/engine/validation.go
pkg/engine/validation_test.go
pkg/engine/variables/evaluate_test.go
pkg/engine/variables/variables_test.go
pkg/engine/variables/vars.go
pkg/engine/variables/vars_test.go
pkg/generate/generate.go
pkg/kyverno/common/common.go
pkg/policy/apply.go
pkg/webhooks/common.go
pkg/webhooks/generation.go
pkg/webhooks/handlers.go
pkg/webhooks/server.go
pkg/webhooks/validate_audit.go

This PR refactor the engine context package.
- Do not expose the concret context, only the interface
- Add missing methods to the interface
- Simplify a couple of utils
- Hide the `AddJSON` method (way too broad and error prone)
One last instace of `AddJSONObject`, dunno how to remove it yet.

refactor: engine context

---

.github/workflows/codecov.yaml
.github/workflows/e2e.yaml

See Slack [discussion](https://kubernetes.slack.com/archives/C032MM2CH7X/p1649658307920869), this PR:
- run CodeCov on Ubuntu
- removes 1.16 - 1.19 e2e tests and keeps the last 4 K8s releases

Update GH workflow config

---

pkg/background/generate/generate.go
pkg/background/request_process.go

`/milestone 1.7.0`.
fix the missing `policy.kyverno.io/policy-name` label in target resources

fix missing `policy.kyverno.io/policy-name` label

---

charts/kyverno/README.md
charts/kyverno/README.md.gotmpl
charts/kyverno/templates/NOTES.txt
charts/kyverno/templates/_helpers.tpl
charts/kyverno/templates/deployment.yaml
charts/kyverno/templates/poddisruptionbudget.yaml
charts/kyverno/templates/validate.yaml
charts/kyverno/values.yaml
config/install.yaml

This PR removes helm mode setting.
The `ha` vs `standalone` mode can be replaced with a simpler replicas count (the `ha` mode only influenced replicas count, making it hard to understand).
It also adds a couple of warnings in `NOTES.TXT` when deployed in non-ha and/or without namespace exclusions.

Remove helm mode setting

---

cmd/kyverno/main.go
pkg/background/generate/cleanup/controller.go
pkg/background/generate/generate.go
pkg/background/request_process.go
pkg/background/update_request_controller.go
pkg/webhooks/generation.go

Closes: #3046
`/milestone 1.7.0`.
use the typed namespace informer in GenerateRequest controller

refactor: use the typed namespace informer in GenerateRequest controller

---

charts/kyverno/templates/NOTES.txt

This PR warns if kube version is too old in helm notes.

chore: warn if kube version is too old in helm notes

---

charts/kyverno/templates/NOTES.txt

This PR print warnings when using helm install in non HA mode and/or depending on webhooks exclusions.
TODO: set correct links in NOTES.
Fixes: #3607

fix: print helm install warnings

---

charts/kyverno/templates/validate.yaml

This PR prevents installing chart with 2 replicas.

fix: prevent installing chart with 2 replicas

---

pkg/webhookconfig/registration.go

Closes #3625
@realshuting 
/kind bug
Currently during the webhook registration leader initialization all webhook configs are deleted and recreated. This creates a small time window that the cluster doesn't have any webhook configuration and as a result the resources are not validated.
This PR changes the registration logic to not remove the webhook configurations on the leader initialization. Instead it updates the existing webhook configuration to the current desired values. 
To test this PR:
1. Create a Policy with `validationFailureAction: enforce` :
```yaml
kind: Policy
metadata:
name: disallow-host-namespaces
spec:
rules:
- name: host-namespaces
match:
any:
- resources:
kinds:
- Pod
validate: …
```

fix: do not remove webhooks during initialization

---

pkg/policy/policy_controller.go

This PR fixes policy controller missing GVK when updating resources.
The fix uses a typed client.
Fixes #3584

fix: policy controller missing GVK

---

.github/workflows/e2e.yaml

This PR removes e2e tests for kube 1.20 (we officially support the 3 latest minor versions of kube).

chore: remove e2e tests for kube 1.20

---

.github/workflows/helm-release.yaml

This is really ugly hack but there are limited options on Github Actions to release Helm charts with tags.  Looking at the code for action currently used, the `charts_dir` must be parent directory of charts so this will create a tmp directory and put the charts being released into that directory.
Once the final approach is merged, I'll open a request against main branch.

Support releasing kyverno and kyverno-policies chart separately

---

pkg/engine/variables/operator/anyin.go
pkg/engine/variables/operator/in.go
test/cli/test/context-entries/kyverno-test.yaml
test/cli/test/context-entries/policies.yaml

Fixes #3685 
/kind bug
Allows for both wildcard keys and values in `AnyIn` operator.
Added as a CLI test

Fix regression in wildcard matches in In/AnyIn operators

---

config/github/rbac.yaml
test/e2e/mutate/config.go
test/e2e/mutate/mutate_test.go
test/e2e/mutate/resources.go

This PR adds the following e2e tests for mutate existing policies:
- mutate the existing secret on configmap creation
- mutate the existing secret on configmap deletion
- mutate the existing secret on policy creation
- mutate the existing secret (Json Patch) on configmap creation

Add e2e tests for mutate existing policies

---

api/kyverno/v1/clusterpolicy_types.go
api/kyverno/v1/policy_types.go
api/kyverno/v1alpha2/clusterreportchangerequest_types.go
api/kyverno/v1alpha2/reportchangerequest_types.go
api/kyverno/v1beta1/updaterequest_types.go
docs/config.json
docs/crd/v1/index.html
docs/crd/v1alpha2/index.html
docs/crd/v1beta1/index.html

This PR fixes generated api reference docs:
- missing resource types list at the top
- missing k8s apiserver extensions in external packages
The tool we use is expecting comments in a specific format https://github.com/ahmetb/gen-crd-api-reference-docs/blob/af7c5e0048a3487c6164bcc6c3e43afe539d3131/main.go#L326

fix: generated api reference docs

---

Makefile
test/e2e/utils.go
test/e2e/verifyimages/config.go
test/e2e/verifyimages/resources.go
test/e2e/verifyimages/verifyimages_test.go

E2E tests for image verify were not actually enabled in the Makefile. This PR enables them.

Enable tests in makefile

---

cmd/cli/kubectl-kyverno/test/test_command.go

Signed-off-by: Prateeknandle <prateeknandle@gmail.com>
Closes #3747 
`/kind bug`
Due to [this](https://github.com/kyverno/kyverno/blob/main/cmd/cli/kubectl-kyverno/test/test_command.go#L444) printing was not happening after failure it's getting exit with error, due to `os.Exit(1)`, Now priniting statement is added before it get exit with error.
```
$ go run ./cmd/cli/kubectl-kyverno/main.go test ./test/cli/test/simple
Executing test-simple...
applying 3 policies to 7 resources... 
│─────────│─────────────────────│────────────────────│────────────────────────────────────────────│────────│
│ # (15)  │ POLICY              │ RULE               │ RESOURCE                                   │ RESULT │
│─────────│─────────────────────│────────────────────│────────────────────────────────────────── …
```

Test Summary printing for failure test cases

---

test/e2e/verifyimages/verifyimages_test.go

/kind failing-test
Adds retry logic for failing tests due to Tekton task CRD not being ready at times.

Retry policy creation to avoid flaky CRD readiness

---

test/e2e/verifyimages/config.go
test/e2e/verifyimages/resources.go

Adds a test case for e2e tests for `required:true` for image verify.

Add tests for required checks for image verify

---

cmd/cli/kubectl-kyverno/jp/jp_command.go
go.mod

Fixes #3767 
/kind feature
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
name: example-task-name
spec:
steps:
- name: cosign
image: ghcr.io/sigstore/cosign/cosign
```
```json
{
"apiVersion": "tekton.dev/v1beta1",
"kind": "Task",
"metadata": {
"name": "example-task-name"
},
"spec": {
"steps": [
{
"image": "ghcr.io/sigstore/cosign/cosign",
"name": "cosign"
}
]
}
}
```
```bash
$ cat task.yml | ./cmd/cli/kubectl-kyverno/kyverno jp '@'
{
"apiVersion": "tekton.dev/v1beta1",
"kind": "Task",
"metadata": {
"name": "example-task-name"
},
"spec": {
"steps": [
{
"image": "ghcr.io/sigstore/cosign/cosign",
"name": "cosign"
}
]
}
}
```
```bash
$ ./cmd/cli/kubectl-kyverno/kyverno jp '@' -f task.yml
{
"apiVersion": …
```

Allow kyverno jp to take yaml files as inputs

---

.github/workflows/pr-update.yaml

Fixes the PR update flow.
@realshuting - we will need to inject a token in the repo as a secret that can be accessed by this action. The token should have appropriate permissions to modify fork repos.
See https://github.com/adRise/update-pr-branch/#token
I also added the ability to update PRs that are targeted for release branches.

Fix PR update flow and allow updates from release branches

---

pkg/tls/certRenewer.go

This PR parses all root CA certs.
We will need this for graceful certs rotation.

feat: parse all root CA certs

---

charts/kyverno/templates/secret.yaml

This PR removes broken `.ca` from helm chart.

chore: remove broken .ca from helm chart

---

pkg/policy/validate.go
test/cli/test/context-entries/kyverno-test.yaml
test/cli/test/context-entries/policies.yaml

Relaxes the policy validation that does a regex check on the rule body to see if a context variable is being used. 
This specific commit was introduced in https://github.com/kyverno/kyverno/pull/2336 and the original issue it was meant to fix https://github.com/kyverno/kyverno/issues/2289 was actually still unfixed as the main cause was dereferencing a nil pointer at [NoSkillGirl/kyverno@ad0cb6e/pkg/engine/jsonContext.go#L30](https://github.com/NoSkillGirl/kyverno/blob/ad0cb6e1ee49338831bf816688650a47463bcc84/pkg/engine/jsonContext.go#L30) - given that jmespath vars might include expressions like above - it seems invalid to introduce additional constraints that don’t fully conform to the jmespath grammar. We should relax the …

Relax JMESPath variable validation

---

cmd/cli/kubectl-kyverno/apply/apply_command_test.go
cmd/cli/kubectl-kyverno/utils/common/common.go
pkg/policyreport/builder.go
test/cli/apply/policies/policy.yaml
test/cli/test/depecated_apis/kyverno-test.yaml
test/cli/test/depecated_apis/policy.yaml

Closes #3818
/kind bug
The `policies.kyverno.io/scored` annotation does not result in a `warn` when testing a resource through `kyverno apply`. This PR fixes that behaviour. I think this was intended in the first place.
```yaml
apiVersion: v1
kind: Pod
metadata:
name: add-capabilities-bad
spec:
initContainers:
- name: init
image: gcr.io/google-samples/node-hello:1.0
containers:
- name: add-capabilities
image: gcr.io/google-samples/node-hello:1.0
capabilities:
add: ["SYS_TIME"]
drop:
- ALL
```
Kyverno Policy
```yaml
metadata:
name: drop-all-capabilities
annotations:
policies.kyverno.io/scored: "false"
spec:
rules:
- name: require-drop-all
match:
any:
- resources:
kinds:
- Pod …
```

CLI should respect scored annotation for warnings

---

pkg/webhookconfig/configmanager.go

This PR fixes policy deletion in `webhookconfig`.
We were checking against a nil policy but it never happens, the correct solution is to check the error returned (the policy is never nil).

fix: policy deletion in webhookconfig

---

cmd/kyverno/main.go
pkg/controllers/certmanager/controller.go
pkg/tls/certRenewer.go
pkg/tls/reader.go
pkg/tls/tls.go

This PR remove the need for self-signed annotation on cert secret.
We can check the name and namespace of secrets are known in advance, we can filter on the secret names rather than on an annotation.

refactor: remove the need for self-signed annotation on cert secret

---

.github/workflows/tests.yaml

This PR enables golangci-lint in ci.

chore: enable golangci-lint in ci

---

cmd/kyverno/main.go
pkg/controllers/certmanager/controller.go

This PR inits certs using certs renewer directly rather than through the controller.

refactor: init certs with certs renewer directly

---

.golangci.yml

This PR increases `golangci-lint` timeout.

chore: increase golangci-lint timeout

---

.golangci.yml

This PR enables `asciicheck` and `bidichk` linters.

chore: enable asciicheck and bidichk linters

---

.golangci.yml

This PR enables `exportloopref` linter.

chore: enable exportloopref linter

---

api/kyverno/v1/common_types.go
charts/kyverno/templates/crds.yaml
config/crds/kyverno.io_clusterpolicies.yaml
config/crds/kyverno.io_generaterequests.yaml
config/crds/kyverno.io_policies.yaml
config/crds/kyverno.io_updaterequests.yaml
config/install.yaml
config/install_debug.yaml

Related: https://github.com/kyverno/kyverno/issues/3858
/kind bug
Undo the OpenAPIV3 Policy validation check for generate rule resource name if it exceeds the 63 char limit, has been done as part of #3640, since there are policy that can used with combination of variables to construct the name , for example:
```yaml
kind: KubernetesRole
name: k8s-{{request.object.metadata.namespace}}-{{request.object.metadata.name}}
namespace: '{{request.object.metadata.namespace}}'
```
Also limits should adhere to k8s spec ([ resource names up to 253 chars )](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names)

fix: undo policy length validation check for generate rule resource name

---

.github/workflows/helm-release.yaml

This PR removes permissions settings in helm-release workflow due to https://github.com/kyverno/kyverno/runs/6401161466?check_suite_focus=true:
```
remote: Permission to kyverno/kyverno.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/kyverno/kyverno/': The requested URL returned error: 403
```

Remove permissions in helm-release workflow

---

pkg/common/common.go

This PR removes unused function `GetNamespaceSelectorsFromGenericInformer`.

chore: remove unused function

---

.golangci.yml

This PR enables `goprintffuncname` linter.

chore: enable goprintffuncname linter

---

cmd/cli/kubectl-kyverno/jp/jp_command.go

Part of KubeCon EU 2022 Bugbash
Signed-off-by: Dhaval Shah <30974879+dhavalgshah@users.noreply.github.com>

[Bugbash] fix: gosec G304 file inclusion error

---

pkg/background/common/util.go
pkg/background/request_process.go
pkg/policy/updaterequest.go

`/milestone 1.7.0`
/kind bug
use patch to update handler status in UR to resolve the resource version error

fix: use patch to update handler status in UR

---

.golangci.yml

This PR enables `nolintlint` linter.

chore: enable nolintlint linter

---

pkg/background/request_process.go

This PR Fix the panic happen in MarkUR function.
1.7.0
/kind bug
Policy.yaml
```
metadata:
name: add-networkpolicy
annotations:
policies.kyverno.io/title: Add Network Policy
policies.kyverno.io/category: Multi-Tenancy
policies.kyverno.io/subject: NetworkPolicy
By default, Kubernetes allows communications across all Pods within a cluster.
The NetworkPolicy resource and a CNI plug-in that supports NetworkPolicy must be used to restrict
communications. A default NetworkPolicy should be configured for each Namespace to
default deny all ingress and egress traffic to the Pods in the Namespace. Application
teams can then configure additional NetworkPolicy resources …
```

Fix panic issue for UR

---

.golangci.yml

This PR enables `goimports` linter.

chore: enable goimports linter

---

pkg/background/request_process.go
pkg/background/update_request_controller.go

This PR fixes a couple of things in UR controller:
- make funcs private
- fix retry on conflict when marking an UR
- deep copy ur being reconciled as everything coming from the cache has to be treated read only
- fix flow in reconcile func

fix: mark ur retry on conflict

---

.github/workflows/e2e-autogen-internals.yaml
.github/workflows/e2e.yaml

This PR adds previous pod logs in case of job failure.
This is useful when the failure comes from a pod restart to understand why the container crashed.

chore: add previous pod logs in case of job failure

---

pkg/background/update_request_controller.go

This PR stops mutating cached resource in ur controller.
It looks like we don't need to.

fix: stop mutating cached resource in ur controller

---

pkg/background/generate/generate.go
pkg/background/mutate/mutate.go
pkg/background/update_request_controller.go

This PR cleans up background controllers:
- remove unused fields
- remove errors always nil

refactor: background controllers cleanup

---

pkg/engine/context/context.go
pkg/engine/jsonContext.go
pkg/engine/mutation.go
pkg/engine/mutation_test.go
pkg/engine/variables/vars.go
pkg/policy/validate.go

This PR
- supports `@` for mutate targets
- enable variables for target resources, i.e., `{{target.}}`
- closes https://github.com/kyverno/kyverno/issues/3997
/1.7.0
/enhancement
Policy:
```yaml
metadata:
name: sync-cms
spec:
mutateExistingOnPolicyUpdate: false
rules:
- name: concat-cm
match:
any:
- resources:
kinds:
- ConfigMap
names:
- cmone
namespaces:
- foo
mutate:
targets:
- apiVersion: v1
name: cmtwo
namespace: bar
- apiVersion: v1
name: cmthree
namespace: bar
data:
key: "{{@}}-{{request.object.data.keyone}}"
```
Results:
```
✗ k -n bar get cm cmtwo -o yaml
apiVersion: v1
data:
key: valuetwo-valueone
metadata: …
```

Support `@` for mutate targets

---

go.mod
go.sum
pkg/policy/validate.go

Closes #3922 
1.7.0
/kind bug
validation check to ensure the annotations/labels are  quoted
Policy.yaml
```yaml
metadata:
name: inject-s3-logging-annotations-to-lb
annotations:
policies.kyverno.io/title: Inject S3 Logging Annotations to LB
policies.kyverno.io/category: Logging
policies.kyverno.io/subject: Service
Any new service of LoadBalancer type will be injected with the annotations for AWS S3 bucket access logging
spec:
rules:
- name: inject-nlb-s3-annotations
match:
resources:
kinds:
- Service
preconditions:
all:
- key: "{{request.object.spec.type}}"
value: "LoadBalancer"
mutate:
metadata: …
```

Add validation check to ensure the annotations quoted

---

pkg/background/common/labels.go

MutateExisting policies with target's `apiVersion` specified fail to apply prior to this change.
This PR replaces `/` in labels by `-` to fix it.
```yaml
metadata:
name: add-sec
annotations:
foo: bar
spec:
mutateExistingOnPolicyUpdate: true
rules:
- name: add-sec-rule
match:
any:
- resources:
kinds:
- Deployment
mutate:
targets:
- apiVersion: apps/v1
spec:
template:
spec:
containers:
- (name): "nginx"
runAsNonRoot: true
allowPrivilegeEscalation: false
privileged: false
```
With the above policy installed, create a new deployment and the pod template gets mutated:
```
✗ k create deploy foobar --image=nginx
✗ k get pod -w
NAME …
```

Fix labels with invalid chars

---

charts/kyverno-policies/Chart.yaml
charts/kyverno-policies/templates/_helpers.tpl

Fixes #4031
> /kind bug
Get the last element of image to ensure only getting tag version and not breaking when image has registry port number.

Fix handling of kyverno-policies version check when port in image tag

---

test/e2e/generate/generate_test.go

This PR makes use of `t.Cleanup` in e2e tests.

refactor: use t.Cleanup in e2e tests

---

pkg/webhooks/updaterequest/generator.go

Closes #4140
Cherry-pick: #4114 
`/milestone 1.7.1`
> /kind bug
In case of namespace policy `ur.spec.policy` contains namespace/policy-name combinations, hence can't be used to set the policy name label.
```yaml
kind: Policy
metadata:
name: scale-deployment-zero
namespace: test
spec:
rules:
- name: annotate-deployment-rule
match:
any:
- resources:
kinds:
- v1/Pod.status
preconditions:
all:
- key: "{{request.operation}}"
value: UPDATE
- key: "{{request.object.status.containerStatuses[0].restartCount}}"
value: 2 # Pods like minio often restarts few times before going healthy.
context:
- name: rsname
variable:
jmesPath: "request.object.metadata.ownerReferences[0].name" …
```

fix: use policyName key to get the policy name

---

Makefile

use `LD_FLAGS_DEV` tag for init container local build target

fix: use dev tag for init container local build target

---

cmd/kyverno/main.go
pkg/background/generate/cleanup/controller.go
pkg/background/update_request_controller.go
pkg/controllers/certmanager/controller.go
pkg/controllers/config/controller.go
pkg/controllers/config/log.go
pkg/controllers/policycache/controller.go
pkg/policy/policy_controller.go
pkg/policyreport/reportcontroller.go
pkg/policyreport/reportrequest.go
pkg/utils/controller/run.go
pkg/webhooks/resource/validate_audit.go

With one of the refactoring changes in 1.7.0, Kyverno does not consistently wait for its informer caches to sync before processing events . Doing this is a best practice in Kubernetes controller development and can help avoid issues related to those caches not being fully populated (e.g. items missing from the listers).
Fixes https://github.com/kyverno/kyverno/issues/4086.
1.7.2
/bug
Wait for informers' caches to be synced before starting controllers.
Before this change Kyverno cannot get webhookconfigurations due to `NotFound` error, thus blocking its pod from running.
```
E0615 10:16:02.211594       1 asm_amd64.s:1581] Register/UpdateWebhookConfigurations "msg"="unable to update mutatingWebhookConfigurations" "error"="unable to get …
```

Wait for informer caches to be synced before starting controllers

---

cmd/kyverno/main.go
pkg/policyreport/builder.go
pkg/policyreport/changerequestcreator.go
pkg/policyreport/policyreport.go
pkg/policyreport/reportcontroller.go
pkg/policyreport/reportrequest.go

The current PolicyReport  implementation works well for small scale environments but when the policy change report crosses the 2k+ entries hence the bigger size data resource in etcd. That may cause high CPU usage and `resourceExhausted` failures while adding/updating large reports and scan may not be completed in a given time frame.
This does not scale well for large clusters or the clusters have a relatively large number of policies configured. For example, one can hit this issue if the cluster has 20 policies (1 rule per policy) with 100 matching resources in a namespace (20 x 100 = 2k).
To overcome this problem we need to split  larger reports per namespace entries which have been explained in this [KDP …

feat: split policy report per policy bases

---

pkg/policyreport/reportcontroller.go

Delete policy reports if the clusterpolicy/policy has been deleted from the cluster.
/milestone-1.7.2
Delete policy reports if the clusterpolicy/policy has been deleted from the cluster.
```sh
$ k get cpolr
NAME                                    PASS   FAIL   WARN   ERROR   SKIP   AGE
clusterpolicyreport-require-ns-labels   0      2      0      0       0      5s
$ kubectl delete -f clusterpolicy.yaml 
clusterpolicy.kyverno.io "require-ns-labels" deleted
$ k get cpolr
No resources found
$ k get polr -A
NAMESPACE   NAME                                                PASS   FAIL   WARN   ERROR   SKIP   AGE
default     polr-ns-default-secrets-not-from-env-vars   1      0      0      0       0      14m
test5 …
```

delete policy reports on policy deletion

---

pkg/dclient/discovery.go
pkg/dclient/fake.go
pkg/openapi/crdSync.go
pkg/policy/validate.go
pkg/utils/util.go

Closes #3244 , https://github.com/kyverno/kyverno/issues/2267
This PR is fix the issue of getting  sync error continuously when we have external metrics install in cluster with kyverno.
this happen because of external.metrics API returns an empty array. 
Previously we are using DiscoveryCache ServerGroupsAndResource method which fails when the first error occurs.
discovery.ServerGroupsAndResources runs queries in parallel and collects all errors, and return errors back in a more graceful manner. 
Also customize the error handlers as we do not want the default logging behaviors.
1.7.2
/kind bug
1. Install KEDA or DataDog Cluster Agent as External Metrics Provider
2. Install Kyverno
3. Install psp policies …

fix external.metrics.k8s.io/v1beta1 issue

---

Makefile
charts/kyverno/templates/crds.yaml
config/crds/kyverno.io_clusterpolicies.yaml
config/crds/kyverno.io_clusterreportchangerequests.yaml
config/crds/kyverno.io_generaterequests.yaml
config/crds/kyverno.io_policies.yaml
config/crds/kyverno.io_reportchangerequests.yaml
config/crds/kyverno.io_updaterequests.yaml
config/crds/wgpolicyk8s.io_clusterpolicyreports.yaml
config/crds/wgpolicyk8s.io_policyreports.yaml
config/install.yaml
config/install_debug.yaml

This PR switches back to the official controller-gen repo now https://github.com/kubernetes-sigs/controller-tools/pull/683 was merged.

fix: use official controller-gen

---

pkg/webhookconfig/monitor.go
pkg/webhookconfig/registration.go

If the channel send is blocked then there is already an
update queued, and there is no point waiting to queue
another one.
In profiling, the channel send in monitor.go has been
seen to "leak" goroutines as the channel is not being
read from fast enough, but the root cause is not known.
Profile sample:
```
goroutine profile: total 11805
11560 @ 0x439c16 0x4057c5 0x40537d 0x20dc646 0x46b101
#	0x20dc645	github.com/kyverno/kyverno/pkg/webhookconfig.(*Monitor).Run.func1+0x65	/src/pkg/webhookconfig/monitor.go:120
```
This pod is four days old, and there are 11560 goroutines waiting on a [channel send to UpdateWebhookChan](https://github.com/kyverno/kyverno/blob/58337716c841a2eff40de325df0b228682485bfb/pkg/webhookconfig/monitor.go#L120) (out of 11805 goroutines total).
Stack trace of one …

Use non-blocking channel send for UpdateWebhookChan

---

pkg/background/common/labels.go
pkg/background/update_request_controller.go
pkg/webhooks/updaterequest/generator.go

Signed-off-by: Byron Ibarra V <bibarrav@falabella.cl>
This PR is to FIX Update Request (UR) labeling for creation and query usage, this was patched but the problem still exist (#4104), and to FIX kyverno keeps processing completed update requests (#4152)
In Kyverno v1.7.0 and v1.71, namespaced Policy has a create error when generateExistingOnPolicyUpdate: true is used, because label error, the UR resource can't be created.  And with ClusterPolicy,  when generateExistingOnPolicyUpdate: true is used, kyverno keeps processing completed update requests.
And I cleanup some unused parameters.
Closes #4152 
Closes #4104 (Still appears in v1.7.1) 
@realshuting 
@prateekpandey14 
/milestone 1.7.2
/kind bug
Modify UR labeling functions (Generate and Mutate) to continue receive namespace/policy-name …

Fix UpdateRequest labeling

---

cmd/cli/kubectl-kyverno/apply/apply_command.go

As the issue statement describes , the output messages returned while using the apply command were odd and unclear to the user . As @JimBugwadia has pointed out in the issue statement
> Its a bit odd to ask users to check debug logs to understand the output:
(Total number of result count may vary as the policy is mutated by Kyverno. To check the mutated policy please try with log level 5)
And, in cases where the policies are not for a pod, this message is meaningless and confusing.
Also as pointed out in [this comment](https://github.com/kyverno/kyverno/issues/3414#issuecomment-1086718950) , it makes sense to switch from policy counts to policy rule counts . Hence we should be returning back correct rule counts and resource counts in our output messages. Also we could let the user know if …

Removed confusing output message in CLI apply command and refactored it

---

CHANGELOG.md
cmd/kyverno/main.go
pkg/event/controller.go

Cherry-pick #4233.
>This PR adds a new container flag maxQueuedEvents to limit the events that are queued internally. There will be a potential memory increase if events are piled up in the queue, this change allows users to tune the event queue size to remedy the issue. Further optimization for events can be tracked in 1.8.0.

Cherry-pick #4233

---

cmd/cli/kubectl-kyverno/Dockerfile
cmd/initContainer/Dockerfile
cmd/kyverno/Dockerfile

There has been a new distroless base image concept around for a while, thanks to [apko](https://github.com/chainguard-dev/apko) + [melange](https://github.com/chainguard-dev/melange) technology stack from Chainguard, which made it possible. In kyverno, we use scratch as a base image, and copy /etc/passsword and necessary CA certs from the above stages, which we don't need to do when we use ghcr.io/distroless/static.
```sh
$ crane export ghcr.io/distroless/static:latest - | tar -Oxf - ./etc/passwd
root:x:0:0:root:/root:/bin/ash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync …
```

chore: use new distroless base image provided by distroless org

---

cmd/initContainer/main.go
cmd/kyverno/main.go
pkg/policy/report.go
pkg/policyreport/builder.go
pkg/policyreport/changerequestcreator.go
pkg/policyreport/reportcontroller.go
pkg/policyreport/reportrequest.go
pkg/toggle/toggle.go

Refactor the code to handle the updated policyName in case of eraseResultsEntries in policy reports during background scan.
`/milestone 1.7.2`.
> /kind bug
Refactor the code to handle the updated policyName in case of eraseResultsEntries in policy reports during background scan
The test set up https://github.com/kyverno/kyverno/issues/4126#issuecomment-1187645542.
The memory stays around ~400 Mi in about an hour with --maxReportChangeRequests=100 and continuous load.
```
kubectl -n kyverno top pod
NAME                       CPU(cores)   MEMORY(bytes)   
kyverno-86f8dd44d9-9rzrc   516m         401Mi           
kubectl -n kyverno get pod
NAME                       READY   STATUS    RESTARTS   AGE
kyverno-86f8dd44d9-9rzrc   1/1 …
```

fix split policyreport name with background scan

---

cmd/cli/kubectl-kyverno/apply/apply_command.go
cmd/cli/kubectl-kyverno/test/test_command.go

Signed-off-by: anutosh491 <andersonbhat491@gmail.com>
As the issue statement describes clearly , this PR intends to add a flag to show only the failing tests to make debugging easier for the user.
Fixes #4220 
`/kind feature`
Now lets say we want to test `policies/best-practices/disallow_latest_tag` from the policies repo ( All tests would pass here so If I randomly switch few tests from pass to fail in `kyverno-test.yaml` we would have ....)
```
anutosh491:~/go/src/github.com/kyverno$ kyverno test ../policies/best-practices/disallow_latest_tag
Executing disallow_latest_tag...
applying 1 policy to 8 resources... 
Note : The resource field is being deprecated in 1.8.0 release. Please provide the resources under the resources parameter as an array in the results field …
```

Implementing flag to show all failing tests only through the test command

---

cmd/cli/kubectl-kyverno/apply/apply_command.go
cmd/initContainer/main.go
cmd/kyverno/main.go
pkg/dclient/client.go

Current implementation create 2 clientset. So limitRate (etc) is shared between both.

fix: use only 1 kubernetes client

---

cmd/cli/kubectl-kyverno/Dockerfile
cmd/initContainer/Dockerfile
cmd/kyverno/Dockerfile

With a relative path, containers started with a different working directory will fail to find the entrypoint
Fixes: #4252
Signed-off-by: James Callahan <jamescallahan@bitgo.com>

fix: use an absolute path in docker entrypoint

---

pkg/webhookconfig/configmanager.go
pkg/webhookconfig/registration.go
pkg/webhooks/server.go

When no Kyverno pod is running, all policies show READY=true which does not reflect their true status. This PR resets the policy `.status.ready` to false on termination.
Closes https://github.com/kyverno/kyverno/issues/4190.
/1.8.0
/bug
This PR:
- resets policies `.status.ready` to false on termination
- retreis reconciling failed policies when there's an error updating webhook configs
1. Policies are set to `READY=false` when scaling down Kyverno
```
✗ k scale -n kyverno deploy/kyverno --replicas=0
```
```
✗ k get cpol
NAME                                    BACKGROUND   ACTION    READY
require-drop-all-capabilities           false        audit     false
disallow-istio-injection-bypass         true         audit     false
restrict-capabilities                   true         audit …
```

Reset policy status on termination

---

docs/crd/v1/index.html
pkg/engine/response/response.go
pkg/event/controller.go
pkg/event/events.go
pkg/event/reason.go
pkg/policy/report.go
pkg/webhooks/resource/report.go

Signed-off-by: viveksahu26 <vivekkumarsahu650@gmail.com>
2 possible changes are implemented through this PR:-
For https://github.com/kyverno/kyverno/issues/4093
Added NORMAL event on background scans for skipped policies. Earlier it was WARNING event type.
For https://github.com/kyverno/kyverno/issues/4044
Added new REASON: PolicySkipped for skip policies on resources. Earlier it shows REASON: PolicyApplied for admission controller, whereas for Policy Controller, it shows REASON: PolicyViolation for skipped resources.
For more, refer to this [doc](https://docs.google.com/document/d/1czDT-DF5FP2LM8Lli0MrBD5OejrCAm4jGxWHxb574B0/edit#)
closes https://github.com/kyverno/kyverno/issues/4093 https://github.com/kyverno/kyverno/issues/4044
none
/kind bug
/kind enhacement
On background scans if a …

feature: added new type of event, PolicySkipped

---

charts/kyverno/Chart.yaml
charts/kyverno/README.md
charts/kyverno/ci/extraContainers-values.yaml
charts/kyverno/templates/deployment.yaml
charts/kyverno/values.yaml

This PR introduces the possibility to define additional init and sidecar container before and along kyverno. The functionality will not alter the behaviour of kyverno directly and is disabled by default. This is useful with the introduction of the `verifyImages` functionality if one wants to have an init/sidecar container that refreshes a hashicorp vault token periodically for example.
N/A
/milestone 1.8.0
/kind feature
No changes in default behaviour
N/A
N/A
Not sure if this makes sense, but maybe splitting the helm chart from the application would ease the review and release process in the future. I had the feeling that a lot of the requirements in the PR documention and contributing guide aim directly the application and not the helm chart, therfore are not applicable for changes like …

[Helm Chart] additional init and sidecar container

---

charts/kyverno/templates/aggregateroles.yaml

Signed-off-by: aofekiko <aofekiko@gmail.com>
ClusterRoles should have resource names as plurals
Closes https://github.com/kyverno/kyverno/issues/4311
/kind bug

Change resource names to plurals

---

pkg/event/events.go

cc - @prateekpandey14 
Currently, the Kyverno Events add `status` twice to the message in-case of `RuleStatusError`. The original intention was to add the error Message here. This PR fixes the typo.
Closes #4314

Fix Kyverno Events Missing Error Message

---

CODEOWNERS

I get a lot of noise on github notifications as I am a code-owner on quite a few of these files which distracts me from kyverno PR/issues where I am actually mentioned and a review is needed. Removing myself from code-owners for now.

Remove myself as codeowner

---

pkg/engine/imageVerify.go

Fixes image verification logs not correctly formatted.
Closes #4346

fix: image verify logs

---

pkg/engine/validation.go
pkg/engine/variables/vars.go
test/cli/test/nil-values-in-variables/exclude_namespaces_dynamically/exclude_namespaces_dynamically.yaml
test/cli/test/nil-values-in-variables/exclude_namespaces_dynamically/kyverno-test.yaml
test/cli/test/nil-values-in-variables/exclude_namespaces_dynamically/resource.yaml
test/cli/test/nil-values-in-variables/exclude_namespaces_dynamically/values.yaml
test/cli/test/nil-values-in-variables/limit-duration/kyverno-test.yaml
test/cli/test/nil-values-in-variables/limit-duration/limit-duration.yaml
test/cli/test/nil-values-in-variables/limit-duration/resource.yaml

Currently, the value for any variable present in the precondition block is assigned as empty string(" ") when  value for the corresponding variable is not present, whereas value for variables present outside of precondition block or normal variables  is assigned as nil. Due to this partiality, normal variables throws an error when it's value is not found.  To deal with need to remove partiality and treat normal as well as precondition variables equally. Therefore proposed changes is to assigned nil value when  value for the corresponding variable is not present  for both normal as well as precondition variable.
closes https://github.com/kyverno/kyverno/issues/3982
/kind bug 
The proposed changes is to assigned nil value when value for the corresponding variable is not present for both …

Treat normal and precondition variable equally

---

pkg/controllers/config/controller.go

The config controller is logging a "reconciling" message for every ConfigMap changed in the namespace where Kyverno is running, even for the ones that does not match the ConfigMap where the Kyverno configuration is stored, which I believe is incorrect.
Closes #4065 
/kind bug
This PR is performing a simple fix to only generate the "reconciling" message when the ConfigMap changed is actually the one Kyverno is interested on.
In the latest `v1.7.2` version and also on main, if you install Kyverno on a non-default namespace, where other controllers are also installed, you will see the stdout logs from Kyverno quite flooded with logs lines like the above:
```
I0821 09:14:07.590284       1 controller.go:123] config-controller "msg"="reconciling ..." …
```

fix: fix the verbosity of reconciling logs in the config controller

---

charts/kyverno/Chart.yaml
charts/kyverno/templates/validate.yaml

Installing kyverno in `kube-system` namespace is not supported.
This PR adds a check in the helm chart and fails if the user tries to install in `kube-system`.

fix: prevent installing helm chart in namespace kube-system

---

pkg/autogen/autogen.go

When enabling autogen internals, previously auto generated rules must be discarded.
This PR ignores auto generated rules in the policy spec when autogen internals is enabled.

fix: exclude autogen rules when autogen internals is enabled

---

.github/workflows/image.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml

Pinning github actions to commit sha makes them more secure (using tag or branches, actions are mutable, with commit SHA they are immutable).
See https://michaelheap.com/ensure-github-actions-pinned-sha/
Pinning GH actions https://github.com/mheap/pin-github-action
This PR adds a verification step to make sure all github actions used are pinned.

chore: add workflow to ensure github actions are pinned to a commit SHA

---

pkg/webhooks/resource/generation.go
pkg/webhooks/resource/handlers.go
pkg/webhooks/resource/updaterequest.go
pkg/webhooks/resource/validate_audit.go
pkg/webhooks/resource/validation.go

Duration metrics are computed from admission request timestamp, but this timestamp was rounded to the nearest second.
This PR keeps the full admission request timestamp precision.
Closes #4320

fix: duration metrics precision

---

.github/workflows/reuse.yaml

All CI jobs failed due to this cosign failure https://github.com/kyverno/kyverno/runs/7995970752?check_suite_focus=true.
Bump to the latest version 1.11.0 to see if it fixes the issue.
Slack conv https://sigstore.slack.com/archives/C02K0T1LNPQ/p1661350000528639.

Attempt to fix a cosign issue - Bump cosign version to 1.11.0

---

Makefile

This PR improves the way we tag docker images by tagging at build time.
It also adds all tags at once when building multi platform images instead of building multiple times.

chore: improve docker image tagging

---

cmd/cli/kubectl-kyverno/Dockerfile
cmd/initContainer/Dockerfile
cmd/kyverno/Dockerfile

bump golang 1.18.5 version digest in Dockerfile as part of  #4408 PR to bump the overall go version to 1.18. 
Note: Earlier 1.17.9 golang image digest has been used
```sh
$ crane config golang@sha256:724abf4dd44985d060f7aa91af5211eb2052491424bd497ba3ddc31f7cee969d | jq
{
"architecture": "amd64",
"config": {
"Hostname": "",
"Domainname": "",
"User": "",
"AttachStdin": false,
"AttachStdout": false,
"AttachStderr": false,
"Tty": false,
"OpenStdin": false,
"StdinOnce": false,
"Env": [
"PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"GOLANG_VERSION=1.17.9",
"GOPATH=/go"
```
```sh
$ crane digest golang:1.18.5
sha256:5540a6a6b3b612c382accc545b3f6702de21e77b15d89ad947116c94b5f42993
$  mquery …
```

bump golang 1.18.5 version digest in Dockerfile

---

Makefile

The `make ko-build-*-dev` targets weren't passing `--bare`, which meant the image refs they pushed didn't match expectations on the subsequent signing steps, leading to failures.
#2925 
/milestone 1.8.0
/kind bug

fix: Add --bare for ko-build-dev targets

---

.ko.yaml
Makefile
test/cli/registry/resources.yaml

This PR makes `ldflags` optional in .ko.yaml to allow local builds that don't define the env var.

fix: make ldflags optional in .ko.yaml

---

Makefile

This PR fixes `ko login` issue for the `kyverno` image (was fixed for other ones).

fix: ko login

---

.github/workflows/codecov.yaml
.github/workflows/fossa.yml
.github/workflows/helm-release.yaml
.github/workflows/tests.yaml

This PR fetches history in pre-checks job.
This is to avoid:
```
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
```

fix: fetch history in pre-checks job

---

.github/workflows/tests.yaml
.github/workflows/verify-codegen.yaml
Makefile

This PR refactors codegen verification targets in makefile.
It also separates the workflow that verifies codegen because verifying client code is up to date is long.

refactor: verify codegen targets in makefile

---

pkg/utils/image/infos_test.go

This PR adds unit tests for `pkg/utils/image` package.
TODO:
What are we expecting for images like `docker.io/test/centos@sha256:dead07b4d8ed7e29e98de0f4504d87e8880d4347859d839686a31da35a3b532f` ?
Currently this returns `docker.io/test/centos:` (no tag, no digest, just `:` at the end).

chore: add unit tests for pkg/utils/image

---

cmd/kyverno/main.go
pkg/background/common/status.go
pkg/background/common/util.go
pkg/background/generate/generate.go
pkg/background/update_request_controller.go
pkg/clients/wrappers/clientset.go
pkg/clients/wrappers/kyverno/v1/clusterpolicy.go
pkg/clients/wrappers/kyverno/v1/kyverno_client.go
pkg/clients/wrappers/kyverno/v1/policy.go
pkg/clients/wrappers/kyverno/v1alpha2/clusterreportchangerequest.go
pkg/clients/wrappers/kyverno/v1alpha2/kyverno_client.go
pkg/clients/wrappers/kyverno/v1alpha2/reportchangerequest.go
pkg/clients/wrappers/kyverno/v1beta1/kyverno_client.go
pkg/clients/wrappers/kyverno/v1beta1/updaterequest.go
pkg/clients/wrappers/policyreport/v1alpha2/clusterpolicyreport.go
pkg/clients/wrappers/policyreport/v1alpha2/policyreport.go
pkg/clients/wrappers/policyreport/v1alpha2/policyreport_client.go
pkg/common/common.go
pkg/policy/policy_controller.go
pkg/policy/report.go
pkg/policyreport/changerequestcreator.go
pkg/policyreport/policyreport.go
pkg/policyreport/reportcontroller.go
pkg/policyreport/reportrequest.go
pkg/webhookconfig/configmanager.go
pkg/webhookconfig/registration.go
pkg/webhooks/resource/handlers.go
pkg/webhooks/updaterequest/generator.go

This PR refactors our client wrappers.
It removes unnecessary interface definitions, simplifies the way we wrap clients, and makes types private when possible.

refactor: client wrappers

---

cmd/kyverno/main.go
pkg/webhooks/resource/audit/validate_audit.go
pkg/webhooks/resource/fake.go
pkg/webhooks/resource/handlers.go

This PR move validation audit handler out of webhooks package.

refactor: move validation audit out of webhooks package

---

pkg/webhooks/resource/handlers.go
pkg/webhooks/resource/mutation/mutation.go
pkg/webhooks/resource/utils.go
pkg/webhooks/utils/error.go

This PR moves mutation handler out of webhooks package.

refactor: move mutation handler out of webhooks package

---

.github/cherry-pick-bot.yml

This PR preserves pr title in cherry picks.
See https://github.com/googleapis/repo-automation-bots/pull/4357

chore: preserve pr title in cherry picks

---

pkg/policyreport/changerequestcreator.go

This PR fixes split policy report flag not applied correctly.
The code used a field that was never set, I suspect it should look at the feature flag instead.

fix: split policy report flag

---

pkg/engine/validation.go

Apply `validate.podSecurity` even when no `exclude` elements are specified.
1.8
/kind bug
Remove check for `exclude`
Configure policy:
```yaml
metadata:
name: pod-security
spec:
rules:
- name: restricted
match:
all:
- resources:
kinds:
- Pod
validate:
podSecurity:
level: restricted
version: v1.24
```
Run an insecure image:
```sh
❯ kubectl run nginx --image nginx
Error from server: admission webhook "validate.kyverno.svc-fail" denied the request:
policy Pod/default/nginx for resource violation:
pod-security:
restricted: |
Validation rule 'restricted' failed. It violates PodSecurity "restricted:v1.24": ({Allowed:false ForbiddenReason:allowPrivilegeEscalation != false …
```

allow PSa validation with no exceptions

---

Makefile

This PR adds a `codegen-quick` makefile target to rebuild all generated code except the client.

chore: add a codegen-quick makefile target

---

pkg/autogen/autogen.go
pkg/autogen/autogen_test.go
pkg/autogen/rule.go

Fix AutoGen for `validate.podsecurity` when no exclude is configured
n/a
1.8
/kind bug
Allow autogen for pod security rules that have no exclude elements configured
Configure a policy like this:
```yaml
metadata:
name: pod-security
spec:
rules:
- name: restricted
match:
all:
- resources:
kinds:
- Pod
validate:
podSecurity:
level: restricted
version: v1.24
```
Apply it to a cluster. You should see autogen rules in the `status` block.

enable autogen for validate.podsecurity with no exclude

---

Makefile
pkg/policyreport/changerequestcreator.go

This PR simplifies RCR creator queue.
This removes the caches instances and uses only a simple queue, the cache keys are random ints, the indirection between the cache and the queue seems useless.
This code is simpler and should be safer in terms of memory and synchronisation.

refactor: simplify RCR creator queue

---

pkg/policyreport/mapper.go
pkg/policyreport/reportrequest.go

This PR adds a lock around policy report mapper.
Access to the mapper needs to be properly synchronized to be used reliably.

fix: lock in policy report mapper

---

pkg/utils/controller/handlers.go
pkg/utils/controller/metadata.go
pkg/utils/controller/utils.go

This PR adds controller utils tools:
- to manage labels, annotations and owner references
- to help with resources update, create or update, and cleanup

feat: add controller utils tools

---

pkg/policyreport/reportcontroller.go

This PR fixes an incorrect namespace in report controller code

fix: incorrect namespace in report controller

---

cmd/cli/kubectl-kyverno/apply/apply_command.go
cmd/cli/kubectl-kyverno/apply/apply_command_test.go
pkg/config/client.go
pkg/config/config_test.go

Signed-off-by: Sandesh More <sandesh.more@infracloud.io>
previously ```kyverno apply``` command only supported default kubeconfig file or kubeconfig file from KUBECONFIG env variable with current-context. This PR intends to add  flags to kyverno apply command to support use of seperate kubeconfig file and context.
closes: #2317
/kind feature
add cli flags namely ```kubeconfig``` and ```context``` in ```kyverno apply``` command while creating kubeclient
for testing i have two kubeconfig files 
```
$ kubectl config get-contexts
CURRENT   NAME                CLUSTER     AUTHINFO    NAMESPACE
developer-context
kind-c1             kind-c1     kind-c1
*         kind-kind           kind-kind   kind-kind   default
````
```
$ kubectl --kubeconfig ~/newkubeconfig config get-contexts
CURRENT   NAME …
```

added kubeconfig and context flag to kyverno apply

---

.github/workflows/cli.yaml
.github/workflows/codecov.yaml
.github/workflows/e2e-autogen-internals.yaml
.github/workflows/e2e.yaml
.github/workflows/fossa.yml
.github/workflows/image-build.yaml
.github/workflows/release.yaml
.github/workflows/reuse.yaml
.github/workflows/tests.yaml
.github/workflows/verify-codegen.yaml

This PR bumps minimum go version to `1.18.6`, fixing CVE CVE-2022-27664.
Fixes #4676

chore: bump minimum go version

---

.github/workflows/image.yaml
.github/workflows/release.yaml

Update github action to use current workflow path, earlier it was pointing to `main` which has been updated with latest changes.
https://github.com/kyverno/kyverno/actions/runs/3128643227/workflow

fix: update github action to use current workflow path

---

pkg/controllers/certmanager/log.go

This PR uses a constant in cert manager controller.

chore: use constant in cert manager controller

---

cmd/cli/kubectl-kyverno/jp/jp_command.go
cmd/cli/kubectl-kyverno/test/test_command.go
cmd/cli/kubectl-kyverno/utils/common/common.go
cmd/cli/kubectl-kyverno/utils/common/fetch.go
pkg/autogen/autogen_test.go
pkg/config/config_test.go
pkg/registryclient/client.go
pkg/testrunner/scenario.go
pkg/testrunner/scenario_test.go
pkg/testrunner/utils.go
pkg/webhooks/handlers/admission.go

The `io/ioutil` package has been deprecated in Go 1.16, the same functionality is now provided by package io or package os (See https://pkg.go.dev/io/ioutil).
/milestone 1.8.1
/kind cleanup
Replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages:
- `ioutil.Discard` => `io.Discard`
- `ioutil.NopCloser` => `io.NopCloser`
- `ioutil.ReadAll` => `io.ReadAll`
- `ioutil.ReadDir` => `os.ReadDir` (returns a slice of `os.DirEntry` rather than a slice of `fs.FileInfo`, this may improve performance in some cases as `os.ReadDir` is more efficient [\[1\]])
- `ioutil.ReadFile` => `os.ReadFile`
- `ioutil.TempDir` => `os.MkdirTemp`
- `ioutil.TempFile` => `os.CreateTemp`
- `ioutil.WriteFile` => `os.WriteFile`
[\[1\]]: https://pkg.go.dev/io/ioutil#ReadDir

refactor: move from io/ioutil to io and os packages

---

Makefile
cmd/cli/kubectl-kyverno/apply/apply_command.go
cmd/initContainer/main.go
cmd/kyverno/main.go
pkg/clients/dclient/client.go
pkg/clients/dclient/discovery.go

This PR uses context in dynamic client instead of chan.

refactor: use context in dynamic client instead of chan

---

cmd/kyverno/main.go
pkg/openapi/crdSync.go
pkg/policy/validate.go

This PR uses context in openapi controller instead of chan.

refactor: use context in openapi controller

---

pkg/policy/validate.go
pkg/policy/validate_test.go
pkg/utils/util.go
pkg/utils/util_test.go

Signed-off-by: ansalamdaniel <ansalam.daniel@infracloud.io>
Currently `validationFailureActionOverrides` field is not provided with validation of the namespaces for different actions defined in it. A policy can be created without validation even if the same namespace defined under different actions.
In this manifest we can observe that `default` namespace is mistakenly configured for both the actions. In the current release, this policy will be created.
```yaml
metadata:
spec:
validationFailureActionOverrides:
- action: audit
namespaces:
- prod
- default
- action: enforce
namespaces:
- test
- default
rules:
- name: check-for-labels
match:
any:
- resources:
kinds:
- Pod
validate:
message: …
```

Fix : policy validation for ValidationFailureActionOverride field

---

pkg/clients/dclient/client.go

This PR replaces AbsPath with RequestURI to support query params.
Fixes #4848 
Tried with:
```yaml
metadata:
name: limits
spec:
rules:
- name: limit-lb-svc
match:
any:
- resources:
kinds:
- Service
context:
- name: serviceCount
apiCall:
urlPath: "/api/v1/namespaces/{{ request.namespace }}/services?limit=1"
jmesPath: "items[?spec.type == 'LoadBalancer'] | length(@)"    
preconditions:
any:
value: CREATE
validate:
message: "Only one LoadBalancer service is allowed per namespace"
deny:
conditions:
any:
- key: "{{ serviceCount }}"
value: 1
```
I see no error in the logs …

fix: replace AbsPath with RequestURI to support query params

---

test/e2e/mutate/config.go
test/e2e/mutate/mutate_test.go
test/e2e/mutate/resources.go

Signed-off-by: slayer321 <sachin.maurya7666@gmail.com>
closes https://github.com/kyverno/kyverno/issues/2358
Added e2e test to set-image-pull-secret
cc @chipzoller

e2e test for mutate policy

---

pkg/policy/generate/validate.go

Hardening policy validation for generate cloneList. Optional fields like `generate.name` and `generate.kind` can not be specified if cloneList has been used in policy.
N/A
`/milestone 1.8.1`.
> /kind bug
1. If `generate.name` has been specified with cloneList
```yaml
generate:
namespace: "{{request.object.metadata.name}}"
synchronize : true
name: generate-secret
cloneList:
namespace: stagging
kinds:
- v1/Secret
- v1/ConfigMap
selector:
matchLabels:
allowedToBeCloned: "true"
```
```sh
$ kubectl apply -f multi-clone-policy.yaml 
Error from server: error when creating "multi-clone-policy.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].generate.name.: with cloneList, generate.name should …
```

fix: hardening policy validation for generate cloneList 

---

pkg/utils/report/labels.go

This PR fixes background scan labels inverted between policies and cluster policies.

fix: background scan labels

---

cmd/cli/kubectl-kyverno/test/test_command.go

Signed-off-by: Anant Vijay <anantvijay3@gmail.com>
Currently on running tests with `results[].resources[]` if tests fail, then the result is displayed in the colour Green instead of in Red, this is due to a wrong colour assignment in the cli, simply changing the colour would lead to desired behaviour.
Closes #4864 @chipzoller
/kind bug
Modify the colour of the fail result text.
```yaml
name: deny-all-traffic
policies:
- add_network_policy.yaml
resources:
- resource.yaml
results:
- policy: add-networkpolicy
rule: default-deny
resources: 
- hello-world-namespace
generatedResource: generatedResource.yaml
kind: Namespace
result: fail
```
```yaml
apiVersion: v1
kind: Namespace
metadata:
name: hello-world-namespace
```
```yaml
metadata:
name: …
```

 [Bug] [CLI] Fail results are not colored red

---

pkg/controllers/report/resource/controller.go

This PR fixes non watchable resources in report controller.
Before starting the watcher we make sure that api resource supports watch and list verbs.
This also fixes an issue with Events that are not allowed to be an owner (hence we can't attach background scan reports).
Fixes #4889

fix: non watchable resources in report controller
