- pkg/background/update_request_controller.go
This PR fixes a case where ur is nil in ur controller.
> fix: ur is nil in ur controller

- pkg/cosign/cosign.go
- pkg/cosign/cosign_test.go
- pkg/engine/imageVerify.go
- pkg/engine/jsonContext.go
- pkg/registryclient/client.go
This PR makes registry client variables private.
> refactor: make registry client variables private

- .golangci.yml
- pkg/autogen/rule.go
This PR enables `nosprintfhostport` linter.
> chore: enable nosprintfhostport linter

- cmd/kyverno/main.go
- pkg/background/update_request_controller.go
> fix: release ur when handler pod is gone (#3973)

- cmd/initContainer/main.go
This PR fixes multiple deepcopy in init container.
> fix: init container gr copy

- pkg/background/update_request_controller.go
> fix: stop mutating cached resource in ur controller (#4003)

- pkg/policy/policy_controller.go
This PR stops mutating policies when autogen internals is enabled.
> fix: stop mutating policies when autogen internals is enabled

- cmd/kyverno/main.go
- pkg/background/update_request_controller.go
> refactor: add policy event listener in ur controller (#4012)

- api/kyverno/v1/common_types.go
- api/kyverno/v1/resource_spec_types.go
- api/kyverno/v1beta1/constants.go
- cmd/kyverno/main.go
- pkg/background/common/labels.go
- pkg/background/generate/cleanup/cleanup.go
- pkg/background/generate/generate.go
- pkg/policy/policy_controller.go
- pkg/policy/updaterequest.go
- pkg/webhooks/generation.go
- pkg/webhooks/server.go
- pkg/webhooks/updaterequest/generator.go
- pkg/webhooks/updaterequest/log.go
Cherry pick #4004 #4009 and #3996
> fix: stop mutation policies when autogen internals is enabled (#4004,#4009,#3996)

- pkg/webhooks/handlers.go
> Cherry pick #4007 #4008

- go.mod
- go.sum
closes https://github.com/kyverno/kyverno/security/dependabot/5
> Fix vulnerable

- cmd/cli/kubectl-kyverno/utils/common/common.go
- test/cli/test/default_value_to_create/check-supplemental-groups.yaml
- test/cli/test/default_value_to_create/kyverno-test.yaml
- test/cli/test/default_value_to_create/resource.yaml
Cherry-pick PR https://github.com/kyverno/kyverno/pull/3894
> Cherry-picking Request operation value by default to CREATE (#3894)

- go.mod
- go.sum
cherry pick:  https://github.com/kyverno/kyverno/pull/4027
> cherry pick  vulnerability (#4027)

- pkg/background/common/labels.go
> Fix labels with invalid charrs (#4034)

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/crds.yaml
- config/install.yaml
- config/release/install.yaml
- config/release/kustomization.yaml
- config/release/labels.yaml
> Release v1.7.0-rc3

- test/more/disallow_secrets_from_env_vars.yaml
> Fix policy typo from test dir

- test/more/disallow_secrets_from_env_vars.yaml
> Cherry pick 4039

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/templates/restricted/disallow-capabilities-strict.yaml
Issue raised on Slack: https://kubernetes.slack.com/archives/CLGR9BJU9/p1654006131712009
> /kind bug
Ensure that a default values.yaml or empty `policyPreconditions` will still have the necessary preconditions in place.
I opted to not update the values.yaml with default values to avoid weird merging behavior with other people's possible values.
@realshuting It would be good to cherry-pick this into release-1.7.
> Ensure preconditions are present with default values

- .github/workflows/e2e-autogen-internals.yaml
- .github/workflows/e2e.yaml
- Makefile
Cherry-pick: https://github.com/kyverno/kyverno/pull/3877
> refactor: bump KIND version to use v1.24.0 k8s release

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/crds.yaml
- config/install.yaml
- config/release/install.yaml
- config/release/kustomization.yaml
- config/release/labels.yaml
> Release v1.7.0

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- config/release/install.yaml
This PR syncs v1.7.0 release manifests.
> Sync v1.7.0 release manifests

- cmd/cli/kubectl-kyverno/test/test_command.go
Signed-off-by: Prateeknandle <prateeknandle@gmail.com>
Closes #3631 
Aggregated all the failed test cases at the end for the test cmd.
```
Test Summary: 147 tests passed and 6 tests failed
Aggregated Failed Test Cases : 
│───│─────────────────────│───────────────────────────│───────────────────────────────────────────────│───────────│
│ # │ POLICY              │ RULE                      │ RESOURCE                                      │ RESULT    │
│───│─────────────────────│───────────────────────────│───────────────────────────────────────────────│───────────│
│ 1 │ images              │ only-allow-trusted-images │ default/Pod/test-pod-with-non-root-user-image │ Fail      │
│ 2 │ images              │ only-allow-trusted-images │ default/Pod/test-pod-with-trusted-registry    │ Fail …
```
> Print for failed test cases

- charts/kyverno/Chart.yaml
This PR adds missing release notes in helm chart.
> fix: add missing release notes in helm chart

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/templates/_helpers.tpl
- charts/kyverno-policies/templates/restricted/disallow-capabilities-strict.yaml
> Cherry-pick Helm fixes

- .krew.yaml
Closes https://github.com/kyverno/kyverno/issues/4062.
> Remove s390X for Krew

- .krew.yaml
> Cherry-pick the fix for Krew

- test/e2e/generate/config.go
- test/e2e/generate/generate_test.go
- test/e2e/generate/helpers.go
This PR refactors generate e2e tests.
> refactor: generate e2e tests

- cmd/cli/kubectl-kyverno/jp/jp_command.go
Signed-off-by: viveksahu26 <vivekkumarsahu650@gmail.com>
https://github.com/kyverno/kyverno/issues/4069
/milestone 1.7.1
/kind cli
Updated kyverno cli command `jp` flags and also added link for more info.
> Updated jp command flags and also added URL for help.

- charts/kyverno/templates/NOTES.txt
> docs(chart): fix deadlink in NOTES.txt

- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/_helpers.tpl
- charts/kyverno/templates/configmap.yaml
- charts/kyverno/values.yaml
- config/k8s-resource/configmap.yaml
Fixes #4075
Exclude Kyverno namespace by default.  Updated YAML manifests too.
Needs backport into 1.7 release branch I believe.
> Exclude Kyverno namespace by default

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- config/install.yaml
- config/install_debug.yaml
> Bump chart versions to v2.4.2

- CODEOWNERS
> add chipzoller to CODEOWNERS

- pkg/background/update_request_controller.go
Closes: #4077
> /kind bug
Handle the nil ur while retry
> fix: handle nil ur while retry

- api/kyverno/v1/image_verification_types.go
- pkg/background/update_request_controller.go
- pkg/policy/policy_controller.go
Cherry-pick https://github.com/kyverno/kyverno/pull/4013, https://github.com/kyverno/kyverno/pull/4053.
> Cherry pick #4013, #4035

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- config/install.yaml
- config/install_debug.yaml
- config/release/install.yaml
> Sync release versions

- charts/kyverno-policies/Chart.yaml
- charts/kyverno/Chart.yaml
- charts/kyverno/templates/crds.yaml
- config/install.yaml
- config/release/install.yaml
- config/release/kustomization.yaml
- config/release/labels.yaml
- pkg/webhookconfig/registration.go
Cherry-pick #3641 and release v1.6.3.
> Release 1.6.3

- cmd/kyverno/main.go
In 1.7.1, a generic pod informer was registered to list Kyverno pods. This won't scale on a large number of workloads clusters. This change switched to use namespace pod informer (for kyverno namespace) to avoid memory growth.
https://github.com/kyverno/kyverno/issues/4072
/1.7.2
/bug
This PR use kyverno namespace pod informer to list Kyverno pods while processing URs in the background.
> Switch to use kyverno namespace pod informer to avoid memory growth

- pkg/event/util.go
- pkg/webhooks/resource/handlers.go
- pkg/webhooks/resource/validation.go
With the test described in #4072, the events get piled up in the queue with 10 retires. There are two issues regarding the event generation:
1. the events are generated on DELETE requests
2. the event creation retries 10 times before give-up
With the Job scheduling test, the events doubled on Job deletion, and the 10-time retry delays the event processing. This leads to the observation that Kyverno memory growth (not a leak, but a growth).
This PR:
- Disable events generation on DELETE requests
- Reduce the event generation retry from 10 to 3
https://github.com/kyverno/kyverno/issues/4072
1.7.2
/enhancement
Before this change, the events in the queue doubled on resource deletion, from 10k to 20k. Now the number of events in the queue does …
> Disable event generation for resources on DELETE requests

- CHANGELOG.md
- cmd/kyverno/main.go
- pkg/policy/policy_controller.go
- pkg/policy/report.go
- pkg/policyreport/builder.go
- pkg/policyreport/changerequestcreator.go
- pkg/policyreport/mapper.go
- pkg/policyreport/policyreport.go
- pkg/policyreport/reportcontroller.go
- pkg/policyreport/reportrequest.go
> Cherry-pick fixes to 1.7.2

- cmd/kyverno/main.go
- pkg/background/generate/cleanup/controller.go
- pkg/background/update_request_controller.go
- pkg/controllers/certmanager/controller.go
- pkg/controllers/config/controller.go
- pkg/policy/policy_controller.go
- pkg/policycache/cache_test.go
- pkg/policycache/informer.go
- pkg/policycache/policy_cache.go
- pkg/policyreport/reportcontroller.go
- pkg/policyreport/reportrequest.go
- pkg/webhooks/validate_audit.go
Due to significant refactoring in the main branch, this PR re-implements #4155.
> Cherry pick #4155

- pkg/event/util.go
- pkg/webhooks/mutation.go
- pkg/webhooks/validation.go
- pkg/webhooks/verify_images.go
Due to significant refactoring in the main branch, this PR re-implements #4159.
> Cherry pick #4159 to 1.7.2

- cmd/kyverno/main.go
- pkg/policyreport/builder.go
- pkg/policyreport/changerequestcreator.go
- pkg/policyreport/policyreport.go
- pkg/policyreport/reportcontroller.go
- pkg/policyreport/reportrequest.go
> feat: split policy report per policy bases (#4147)

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/crds.yaml
- config/install.yaml
- config/release/install.yaml
- config/release/kustomization.yaml
- config/release/labels.yaml
> Tag v1.7.2-rc1

- CODEOWNERS
This PR adds myself into `CODEOWNERS`
> chore: add myself into owners

- test/e2e/framework/framework.go
- test/e2e/verifyimages/resources.go
- test/e2e/verifyimages/verifyimages_test.go
This PR adds more verify images e2e tests for bool fields.
> fix: add more verify images e2e test for bool fields

- pkg/policyreport/reportcontroller.go
> delete policy reports on policy deletion (#4174)

- pkg/dclient/discovery.go
- pkg/dclient/fake.go
- pkg/openapi/crdSync.go
- pkg/policy/validate.go
- pkg/utils/util.go
> cherry pick external.metrics.k8s.io/v1beta1 issue

- CONTRIBUTING.md
Fixes #4121 
cc: @realshuting 
> docs(contributing): add how to cherry-pick section

- CONTRIBUTING.md
Sections were added and moved in f67f145d90 and d05a0759ca, resulting in duplicate headers. The TOC [link to DCO instructions](https://github.com/kyverno/kyverno/blob/a37901425fbab76fb79a777a961f0af613a69a2d/CONTRIBUTING.md#developer-certificate-of-origin-dco-sign-off) appears empty.
This puts the "cherry-pick" section between the "PR" and "DCO" sections, which I believe was the original intent.
Updates #4121
Updates #4127
Related to #4119
> Resolve conflict introduced to contributing page

- pkg/autogen/autogen.go
- pkg/policy/apply.go
- pkg/policymutation/policymutation.go
- pkg/utils/annotations.go
- pkg/utils/json/patch.go
- pkg/utils/json/utils.go
- pkg/utils/json/utils_test.go
- pkg/webhooks/resource/handlers.go
Fix for merging patches across image verification and mutate policy rules.
Fixes https://github.com/kyverno/kyverno/issues/4111
1.8.0
/kind bug
Update JSON patch merge to handle statements and patches.
n/a
> Fix merging JSON patches

- pkg/policy/common.go
use the unstructured list instead of interface type
Related: #4072
/kind bug
> fix: use the unstructured list instead of interface type

- pkg/policy/common.go
> use the unstructured list instead of interface type

- cmd/cli/kubectl-kyverno/apply/apply_command.go
- cmd/cli/kubectl-kyverno/utils/common/common.go
> Make method public

- pkg/webhooks/handlers/admission.go
This change is applied in two areas in the admission
handler that had high heap allocations seen in profiling.
This addresses a memory leak that is no longer present in the master branch due to other refactoring. Rather than backport the refactoring commit, this patch fixes the issue directly for the 1.7 release branch.
#4208
> /kind bug
Check the logging level before setting up any context. Also, shadowing the logging variable (`:=` rather than `=`) may help, or at least is consistent with how new loggers are created elsewhere.
> Only set up logging context if it will be used

- cmd/cli/kubectl-kyverno/apply/apply_command.go
- config/install.yaml
Fix kyverno  cli policy report typo and add shorthand for policy-report flag
closes https://github.com/kyverno/kyverno/issues/4223
/milestone 1.7.3
> /kind bug
`-p, --policy-report          Generates policy report when passed (default policyviolation)`
> Fix kyverno cli policy-report typo

- cmd/cli/kubectl-kyverno/apply/apply_command.go
> Cherry-pick: fix kyverno cli policy-report typo (#4224)

- pkg/metrics/policyexecutionduration/policyExecutionDuration.go
- pkg/metrics/policyresults/policyResults.go
This PR fixes the metrics for kyverno_policy_results_total (and duration) when an action override is present for that specific rule evaluation.
N/A
TBD
/kind bug
> Fix metrics with invalid validationMode

- pkg/metrics/policyexecutionduration/policyExecutionDuration.go
- pkg/metrics/policyresults/policyResults.go
> Revert "Fix metrics with invalid validationMode"

- pkg/dclient/discovery.go
- pkg/policy/common.go
The check [deprecated apis](https://github.com/kyverno/policies/blob/main/best-practices/check_deprecated_apis/check_deprecated_apis.yaml) throws error of schema not found. The error is coming because of when kyverno listing and finding resources  instead of sending kind, kyverno passes the GVK because of that it throws schema not found error. This pr is fix for that.
/milestone 1.7.2
/kind bug
Apply the check_deprecated_apis policy and check logs. kyverno not throwing schema not found error.
> Fix check depreciated api issue

- pkg/dclient/discovery.go
- pkg/policy/common.go
> fix check depreciated api issue (#4243)

- cmd/initContainer/main.go
- cmd/kyverno/main.go
- pkg/policy/report.go
- pkg/policyreport/builder.go
- pkg/policyreport/changerequestcreator.go
- pkg/policyreport/reportcontroller.go
- pkg/policyreport/reportrequest.go
- pkg/toggle/toggle.go
> fix split policyreport name with background scan (#4237)

- pkg/webhookconfig/monitor.go
- pkg/webhookconfig/registration.go
> Use non-blocking channel send for UpdateWebhookChan (#4204)

- ADOPTERS.md
Signed-off-by: Tuan Anh Tran <me@tuananh.org>
> Add Techcombank to adopters

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/crds.yaml
- config/install.yaml
- config/release/install.yaml
- config/release/kustomization.yaml
- config/release/labels.yaml
> Release v1.7.2

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Sync v1.7.2 Helm versions

- cmd/kyverno/main.go
- pkg/metrics/init.go
- pkg/metrics/metrics.go
- pkg/tracing/tracing.go
Signed-off-by: Tathagata Paul <tathagatapaul7@gmail.com>
This PR adds shutdown methods for metrics and traces exporter and controllers. This will prevent dropping of metrics and traces when the process is exiting.
Referenced from this review: https://github.com/kyverno/kyverno/pull/3910#discussion_r918245548
> Add shutdown methods for exporters and controllers

- pkg/engine/variables/evaluate.go
Suppress unnecessary logs for CLI
Fixes https://github.com/kyverno/kyverno/issues/4074
1.8.0
/kind cleanup
Update log levels
n/a
> update log levels

- cmd/initContainer/main.go
Signed-off-by: Dylan Shepard <dylan@shepard.dev>
Dead simple typo update. quiting -> quitting in the log message where Kyverno is concluding that a leader has successfully been elected.
It's a 1 letter typo, I don't think an issue is neccessary
n/a, it's a trivial typo
/kind cleanup
quiting -> quitting, just tired of seeing the typo on the logs of Kyverno's startup honestly
> trivial typo update

- config/k8s-resource/clusterroles.yaml
Signed-off-by: anutosh491 <andersonbhat491@gmail.com>
As pointed out in the issue statement ....` kyverno:events Clusterrole` is configured to look across all api groups through
```
rules:
- apiGroups:
- '*'
resources:
- events
```
Though as the events resource is a part of  core apiGroup and `events.k8s.io` , we could reduce it's scope to
```
rules:
- apiGroups:
- ""
- events.k8s.io
resources:
- events
```
Closes #3222 
`/kind bug`
As shown in the explanation
None
> Tightened scope on apiGroups for kyverno:events Clusterrole

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno-policies/templates/baseline/disallow-capabilities.yaml
- charts/kyverno-policies/templates/baseline/disallow-host-namespaces.yaml
- charts/kyverno-policies/templates/baseline/disallow-host-path.yaml
- charts/kyverno-policies/templates/baseline/disallow-host-ports.yaml
- charts/kyverno-policies/templates/baseline/disallow-host-process.yaml
- charts/kyverno-policies/templates/baseline/disallow-privileged-containers.yaml
- charts/kyverno-policies/templates/baseline/disallow-proc-mount.yaml
- charts/kyverno-policies/templates/baseline/disallow-selinux.yaml
- charts/kyverno-policies/templates/baseline/restrict-apparmor-profiles.yaml
- charts/kyverno-policies/templates/baseline/restrict-seccomp.yaml
- charts/kyverno-policies/templates/baseline/restrict-sysctls.yaml
- charts/kyverno-policies/templates/other/require-non-root-groups.yaml
- charts/kyverno-policies/templates/restricted/disallow-capabilities-strict.yaml
- charts/kyverno-policies/templates/restricted/disallow-privilege-escalation.yaml
- charts/kyverno-policies/templates/restricted/require-run-as-non-root-user.yaml
- charts/kyverno-policies/templates/restricted/require-run-as-nonroot.yaml
- charts/kyverno-policies/templates/restricted/restrict-seccomp-strict.yaml
- charts/kyverno-policies/templates/restricted/restrict-volume-types.yaml
- charts/kyverno-policies/values.yaml
- config/install.yaml
- config/install_debug.yaml
Add support for failurePolicy to helm charts and some whitespace cleanup
For Feature request [4319](https://github.com/kyverno/kyverno/issues/4319)
/kind feature
Grants more flexibility to consumers of the kyverno-policies helm chart by allowing them to set failurePolicy.
Helm Linting test
```bash
┌──kyverno/charts/kyverno-policies ─🕙 2022.08.09 16:02:39 ─on 🌱 helm-failure-policy ->
└─>via ⎈ v3.8.1 💀>  helm lint 
==> Linting .
1 chart(s) linted, 0 chart(s) failed
```
Helm  chart installation test with changes
```bash
┌──kyverno/charts/kyverno-policies ─🕙 2022.08.09 16:02:43 ─on 🌱 helm-failure-policy ->
└─>via ⎈ v3.8.1 👌>  helm install kyverno-policies --set failurePolicy=Ignore .
NAME: kyverno-policies
LAST DEPLOYED: Tue Aug  9 16:02:53 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1 …
```
> support failurePolicy in kyverno-policies helm chart

- pkg/webhookconfig/configmanager.go
This pr fixes the issue of deprecated api policy. In this pr  Kyverno  ensure the webhooks are updated so that a wildcard (*) overrules anything else in the apiVersions[] list if a policy is introduced which specifies a wildcard in the version
closes https://github.com/kyverno/kyverno/issues/3580
milestone 1.8.0
/kind bug
Tested by Multiple users.
https://kubernetes.slack.com/archives/CLGR9BJU9/p1659951874277279?thread_ts=1658255138.483029&cid=CLGR9BJU9
https://kubernetes.slack.com/archives/CLGR9BJU9/p1659971118139089?thread_ts=1658255138.483029&cid=CLGR9BJU9
https://kubernetes.slack.com/archives/CLGR9BJU9/p1659951757921729?thread_ts=1658315858.446579&cid=CLGR9BJU9
> Fix deprecated  api policy issue

- pkg/webhookconfig/configmanager.go
> Cherry-pick: fix kyverno cli policy-report typo(#4349)

- cmd/cli/kubectl-kyverno/apply/apply_command.go
Signed-off-by: Anurag <81210977+kranurag7@users.noreply.github.com>
- Updated the message of the command `kyverno apply -h` 
- applying to a folder of resources was added through this PR
closes #4338
#4338 
> update apply help message

- api/policyreport/v1alpha2/policyreport_types.go
- charts/kyverno/templates/crds.yaml
- config/crds/kyverno.io_clusterreportchangerequests.yaml
- config/crds/kyverno.io_reportchangerequests.yaml
- config/crds/wgpolicyk8s.io_clusterpolicyreports.yaml
- config/crds/wgpolicyk8s.io_policyreports.yaml
- config/install.yaml
- config/install_debug.yaml
This PR fixes https://github.com/kyverno/kyverno/issues/4324 by
updating ClusterPolicyReport and PolicyReport CRD to match https://github.com/kubernetes-sigs/wg-policy-prototypes commit dd8096683fecb8b0d7338f9c8d4575e5336846bc
to allow Kyverno chart deployment to be compatible with other tools using the updated working group policy CRDs 
Closes #4324 @fjogeleit @realshuting
/kind bug
I'm not sure what's the kind, it's not technically a bug
- [ x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [ x] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.
> Update wgpolicyk8s.io CRDs

- charts/kyverno/templates/aggregateroles.yaml
- config/install.yaml
- config/install_debug.yaml
- config/k8s-resource/aggregateroles.yaml
This PR adds missing aggregated role for `UpdateRequest` resources.
Closes #4340
> fix: missing aggregated role for UR

- .github/workflows/fossa.yml
This PR fixes FOSSA ci job (was targeting the `master` branch instead of main).
> chore: fix fossa ci job

- MAINTAINERS.md
This PR updates maintainers md (@chipzoller affiliation and formatting).
> chore: update maintainers md

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Sync 1.7.3 Helm versions

- .golangci.yml
This PR enables `asasalint` linter.
> chore: enable asasalint linter

- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/values.yaml
This PR fixes chart docs for `generatecontrollerExtraResources`.
> fix: chart docs for generatecontrollerExtraResources

- api/kyverno/v1/rule_types.go
- pkg/config/config.go
- pkg/cosign/cosign.go
- pkg/engine/common/pattern.go
- pkg/engine/context/mock_context.go
- pkg/engine/imageVerify.go
- pkg/engine/jmespath/functions.go
- pkg/engine/loadtargets.go
- pkg/engine/mutate/patch/patchesUtils.go
- pkg/engine/response/response.go
- pkg/engine/utils.go
- pkg/engine/variables/operator/allin.go
- pkg/engine/variables/operator/anyin.go
- pkg/engine/variables/operator/equal.go
- pkg/engine/variables/operator/in.go
- pkg/engine/variables/operator/notequal.go
- pkg/engine/wildcards/wildcards.go
- pkg/policy/common.go
- pkg/utils/util.go
- pkg/utils/wildcard/match.go
This PR introduces a new `wildcard` utils package.
This way we have a single place to change to swap implementation.
This could help with #4372
> refactor: introduce wildcard utils package

- .github/workflows/reuse.yaml
This PR attempts to fix `ko login`.
> fix: ko login

- DEVELOPMENT.md
This PR adds a local image build section to the dev docs.
> docs: add local image build section

- DEVELOPMENT.md
This PR adds a section about pushing images in the docs.
> docs: add pushing images section

- .github/cherry-pick-bot.yml
This PR enables a cherry pick bot to help cherry picking pr across release branches.
> chore: enable cherry-pick bot

- Makefile
This PR speeds up local image builds by building only for the local platform.
> chore: speed up local image builds

- .github/workflows/pr-update.yaml
This PR relaxes on auto update PRs conditions (do not require all checks pass).
> chore: relax auto update PRs conditions

- .github/workflows/cli.yaml
- .github/workflows/e2e-autogen-internals.yaml
- .github/workflows/e2e.yaml
- .github/workflows/image-build.yaml
- .github/workflows/release.yaml
- .github/workflows/reuse.yaml
- .github/workflows/tests.yaml
This PR bumps cache action and improves cached paths.
> chore: bump cache action and improve paths

- .github/workflows/helm-release.yaml
This PR will address publishing Kyverno charts to GitHub Container Registry using Helm's native OCI support. For example, GitOps tools like Flux can use Helm OCI repositories for reconciliation.
> https://helm.sh/blog/storing-charts-in-oci/
> https://fluxcd.io/docs/components/source/helmrepositories/#helm-oci-repository
Fixes #4376 
/kind feature
I've only added two more steps to the `helm-release` workflow for login and push operations.
Successful workflow:
> https://github.com/developer-guy/kyverno/actions/runs/2970857608
> chore: publish helm charts to ghcr.io

- Makefile
This PR fixes an invalid `kustomize` call in makefile.
> fix: incorrect kustomize call in makefile

- Makefile
This PR adds support for easily switching between `ko` and `docker` build systems (`ko` by default).
We can now `BUILD_WITH=docker make ...`.
> feat: support switching build with docker or ko

- Makefile
This PR refactors helm targets in makefile.
> chore: refactor helm targets in makefile

- DEVELOPMENT.md
This PR adds a docs section about switching between docker and ko.
> docs: add section about switching between docker and ko

- pkg/utils/wildcard/match_test.go
This PR adds wildcard package unit test.
> chore: add wildcard unit test

- DEVELOPMENT.md
This PR adds a docs section for generating helm docs and crds.
> docs: add section for generating helm docs and crds

- MAINTAINERS.md
This PR updates maintainers with my new affiliation :tada:
> chore: update my affiliation in maintainers

- .github/workflows/codecov.yaml
- pkg/utils/os/env_test.go
This PR adds unit tests for `pkg/utils/os` package.
> chore: add unit tests for pkg/utils/os

- pkg/engine/loadtargets.go
- pkg/engine/wildcards/wildcards.go
- pkg/utils/kube/wildcard.go
- pkg/utils/wildcard/match_test.go
- pkg/utils/wildcard/utils.go
- pkg/utils/wildcard/utils_test.go
This PR adds unit tests for `pkg/utils/wildcard`.
> chore: add unit tests for pkg/utils/wildcard

- pkg/utils/yaml/utils_test.go
This PR adds unit tests for `pkg/utils/yaml` package.
> chore: add unit tests for pkg/utils/yaml

- pkg/utils/json/patch_test.go
This PR adds unit tests for `pkg/utils/json` package.
> chore: add unit tests for pkg/utils/json

- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/clients/dclient/fake.go
This PR add an auth interface and unit tests.
> refactor: add auth interface and unit tests

- CHANGELOG.md
This PR adds `protectManagedResources` flag to changelog.
> chore: add protectManagedResources flag to changelog

- go.mod
- go.sum
- pkg/engine/jmespath/functions.go
Signed-off-by: Anurag <contact.anurag7@gmail.com>
- This PR adds a new `random` JMESPath filter and is subject to change. 
Closes #3598.
/kind feature
> add random filter

- pkg/webhooks/resource/handlers.go
This PR defers ur update until validation passes.
No need to update an ur if the validation webhook rejects the request.
> fix: defer ur update until validation passes

- pkg/webhooks/resource/handlers.go
- pkg/webhooks/utils/update_request_updater_test.go
This PR adds a unit test for updating ur status
> chore: add unit test for updating ur status

- CHANGELOG.md
- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/crds.yaml
- config/install.yaml
- config/install_debug.yaml
- config/release/install.yaml
- config/release/kustomization.yaml
- config/release/labels.yaml
- Releases v1.8.0-rc1
- Closes https://github.com/kyverno/kyverno/issues/4188, removes `v` from Helm charts versions
> Release v1.8.0-rc1

- pkg/webhooks/resource/handlers.go
- pkg/webhooks/resource/validation.go
- pkg/webhooks/utils/event.go
This PR moves webhook events utils in utils package.
> refactor: move webhook events utils in utils package

- .github/workflows/helm-release.yaml
This PR triggers Helm releases on tags `kyverno-chart-*` and `kyverno-policies-chart-*`.
> Update helm release config

- .github/workflows/helm-release.yaml
> Cherry-pick - Update helm release config #4551

- pkg/webhooks/resource/handlers.go
- pkg/webhooks/resource/utils.go
- pkg/webhooks/resource/validate_audit.go
- pkg/webhooks/resource/validation/validation.go
- pkg/webhooks/utils/policy_report.go
This PR moves validation handler out of webhooks package.
> refactor: move validation handler out of webhooks package

- DEVELOPMENT.md
> add help on fetching tags

- pkg/webhooks/resource/generation/generation.go
- pkg/webhooks/resource/generation/generation_test.go
- pkg/webhooks/resource/generation/utils.go
- pkg/webhooks/resource/handlers.go
- pkg/webhooks/resource/updaterequest.go
- pkg/webhooks/resource/utils.go
This PR moves generation handler out of webhooks package.
> refactor: move generation handler out of webhooks package

- pkg/toggle/toggle_test.go
This PR adds toggle package unit tests.
> chore: add toggle package unit tests

- .github/ISSUE_TEMPLATE/bug-cli.yaml
- .github/ISSUE_TEMPLATE/bug-other.yaml
- .github/ISSUE_TEMPLATE/bug-webhook.yaml
This PR adds `1.8.0` version to all relevant issue templates in preparation for the pending 1.8.0 release of Kyverno.
/kind cleanup
* Updates Kyverno version drop-down in 3 issue templates to add 1.8.0
> update version drop-down

- go.mod
- go.sum
- pkg/utils/wildcard/match.go
This PR switches to github.com/IGLOU-EU/go-wildcard instead of our own fork.
Closes #3613
Closes #4500
> chore: switch to github.com/IGLOU-EU/go-wildcard

- .github/workflows/helm-release.yaml
Fixes https://github.com/kyverno/kyverno/runs/8299766073?check_suite_focus=true.
> Update helm releases path

- pkg/policyreport/builder.go
- pkg/policyreport/changerequestcreator.go
- pkg/policyreport/info.go
- pkg/policyreport/reportrequest.go
This PR refactors info struct in policyreport package.
> refactor: info in policyreport package

- Makefile
This PR adds messages in makefile kind targets.
> chore: add messages in makefile kind targets

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/crds.yaml
- config/install.yaml
- config/release/install.yaml
- config/release/kustomization.yaml
- config/release/labels.yaml
> Release v1.8.0-rc2

- pkg/engine/jmespath/functions.go
Signed-off-by: Anurag <contact.anurag7@gmail.com>
- enhancing the jmespath filter  #4527  so it produces random output when tested from the `kyverno jp` command.
#4527 
/milestone 1.8.0
/kind bug
> enhance jmespath random-filter

- api/kyverno/v1/clusterpolicy_types.go
- api/kyverno/v1/policy_types.go
- api/kyverno/v1/spec_types.go
- charts/kyverno/templates/crds.yaml
- config/crds/kyverno.io_clusterpolicies.yaml
- config/crds/kyverno.io_policies.yaml
This PR fixes background printer column not being defaulted correctly.
#4616
> fix: background printer column

- Makefile
This PR adds a makefile target to deploy policy reporter.
> chore: add target to deploy policy reporter

- Makefile
This PR adds a makefile target to deploy metrics server.
> chore: add makefile target to deploy metrics server

- pkg/webhooks/resource/handlers.go
This PR removes RCR creation from mutation webhook.
> fix: remove RCR from mutation webhook

- api/kyverno/v1alpha2/clusterreportchangerequest_types.go
- api/kyverno/v1alpha2/interface.go
- api/kyverno/v1alpha2/reportchangerequest_types.go
- docs/crd/v1alpha2/index.html
This PR introduces a new RCR interface common to clustered and namespaced types.
> feat: introduce RCR interface

- api/kyverno/v1/constants.go
- pkg/background/common/labels.go
- pkg/policyreport/policyreport.go
- pkg/policyreport/reportcontroller.go
- pkg/tls/renewer.go
- pkg/tls/utils.go
- pkg/webhookconfig/common.go
- pkg/webhookconfig/registration.go
- pkg/webhookconfig/status.go
- pkg/webhooks/resource/generation/generation.go
- pkg/webhooks/resource/handlers.go
- pkg/webhooks/server.go
This PR adds a couple of constants in our api.
> refactor: add a couple of constants in api

- .github/workflows/reuse.yaml
- Makefile
This PR aims to fix the problem of uploading SBOMs to a different repository from kyverno's images.
Fixes #4592 
/kind bug
> chore: publish sbom result to a different repositry from an image

- pkg/policy/generate/validate.go
- test/e2e/generate/resources.go
Handle auth permission for cloneList resource to validate whether it has sufficient RBAC permission to create/update/delete resources in a given namespace.
Fixes #4683
/milestone 1.8.0
> /kind bug
Handle auth permission for cloneList resource to validate whether it has sufficient RBAC permission to create/update/delete resources in a given namespace.
Authenticate the list of  CloneList kinds to validate them one by one.
```yaml
metadata:
name: clone-secrets
spec:
rules:
- name: clone
match:
any:
- resources:
kinds:
- Namespace
generate:
synchronize: true
cloneList:
namespace: shared-secrets
kinds:
- v1/secrets
- v1/configmaps
```
> fix: handle auth permission for cloneList validation

- go.mod
- go.sum
This PR bumps net standard lib.
This is to fix a CVE in the net lib.
> fix: bump net standard lib

- pkg/utils/kube/kind.go
- pkg/webhookconfig/configmanager.go
- test/cli/registry/kyverno-test.yaml
- test/cli/registry/values.yaml
Cherry-picked Fix issue for wildcard versions (#4670)
> Cherry-picked Fix issue for wildcard versions (#4670)  to 1.7

- pkg/clients/wrappers/kyverno/v1/generaterequest.go
- pkg/clients/wrappers/kyverno/v1/kyverno_client.go
- pkg/clients/wrappers/kyverno/v1alpha2/kyverno_client.go
- pkg/clients/wrappers/kyverno/v1beta1/kyverno_client.go
- pkg/clients/wrappers/policyreport/v1alpha2/policyreport_client.go
This PR adds missing client wrapper.
> fix: missing client wrapper

- Makefile
This PR refactors manifests related makefile targets.
> chore: refactor manifests related makefile targets

- pkg/engine/imageVerify_test.go
This PR changes a key used in the verify image tests.
> fix: change key used in test

- Makefile
This PR redirects makefile messages to stderr.
This should fix publishing digests in CI pipeline.
> fix: output make messages to stderr

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/crds.yaml
- config/install.yaml
- config/release/install.yaml
- config/release/kustomization.yaml
- config/release/labels.yaml
> Release 1.8.0-rc3

- pkg/controllers/report/resource/controller.go
This PR catches watch error in resource controller.
> fix: watch error in resource controller

- cmd/kyverno/main.go
- pkg/logging/log.go
Signed-off-by: damilola olayinka <holayinkajr@gmail.com>
> add and use package level logger

- cmd/kyverno/main.go
- pkg/logging/log.go
This PR splits main in a couple of funcs and use local loggers.
> refactor: split main in a couple of funcs and use local loggers

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/crds.yaml
- config/install.yaml
- config/release/install.yaml
- config/release/kustomization.yaml
- config/release/labels.yaml
> Release v1.8.0-rc4

- cmd/kyverno/main.go
- pkg/webhooks/server.go
This PR makes the server owner of the cleanup chan.
> refactor: make server owner of the cleanup chan

- cmd/kyverno/main.go
This PR fixes flags parsing error handling.
> fix: parse flags error handling

- .github/workflows/helm-release.yaml
- .gitignore
> Based on the Slack conversation: _https://kubernetes.slack.com/archives/C032MM2CH7X/p1664466952893839_
This issue aims to fix the chart registry URL, and it will replace the existing ones with the following:
_ghcr.io/kyverno/kyverno/kyverno_ => _ghcr.io/kyverno/charts/kyverno_
_ghcr.io/kyverno/kyverno/kyverno-policies_ => _ghcr.io/kyverno/charts/kyverno-policies_
/kind feature
_Successful job URL_
> _https://github.com/developer-guy/kyverno/actions/runs/3161085676/jobs/5146285073#step:9:14_
kindly ping @eddycharly @chipzoller
> chore: change charts registry url

- pkg/webhooks/utils/block.go
Skip succeed rules when building the blocked return message.
Closes https://github.com/kyverno/kyverno/issues/4615.
/1.8.0
/bug
The error message for policy `psa` is gone: 
```
✗ k apply -f resources.yaml
Error from server: error when creating "resources.yaml": admission webhook "validate.kyverno.svc-fail" denied the request:
policy Pod/default/badpod01 for resource violation:
test:
istio-controlplane_AC-4(istio-injection-enabled): 'validation error: Every pod should
have istio-proxy. rule istio-controlplane_AC-4(istio-injection-enabled) failed
at path /spec/containers/'
```
> Skip succeed rules when building the blocked return message

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- config/install.yaml
- config/labels.yaml
> Release v1.8.0-rc5

- cmd/initContainer/main.go
- cmd/kyverno/main.go
- pkg/logging/log.go
This PR adds context funcs to logging package.
> feat: add context funcs to logging package

- cmd/initContainer/main.go
- cmd/kyverno/main.go
- pkg/leaderelection/leaderelection.go
This PR adds context support to leader election.
> feat: add context support to leader election

- cmd/kyverno/main.go
- pkg/config/client.go
- pkg/version/version.go
This PR splits main into sub funcs.
> refactor: split main into sub funcs

- cmd/kyverno/main.go
This PR fixes controllers start in loop.
> fix: controllers start in loop

- cmd/kyverno/main.go
> Cherry-pick #4815

- api/kyverno/v1/spec_types.go
- api/kyverno/v2beta1/spec_types.go
- charts/kyverno/templates/crds.yaml
- config/crds/kyverno.io_clusterpolicies.yaml
- config/crds/kyverno.io_policies.yaml
- config/install.yaml
- config/install_debug.yaml
This PR fixes validationFailureAction default value.
> fix: validationFailureAction default value

- go.mod
- go.sum
Signed-off-by: damilola olayinka <holayinkajr@gmail.com>
This PR is to fix logs showing the wrong call site.
```
I1006 09:52:43.228612       1 config.go:263] config "msg"="Updated resource excludeGroupRoles" "name"="kyverno" "namespace"="kyverno" "newExcludeGroupRole"=["","system:serviceaccounts:kube-system","system:nodes","system:kube-scheduler"] "oldExcludeGroupRole"=["system:serviceaccounts:kube-system","system:nodes","system:kube-scheduler"]
I1006 09:52:43.228977       1 config.go:297] config "msg"="Updated webhooks configurations" "name"="kyverno" "namespace"="kyverno" "newWebhookd"=[{"namespaceSelector":{"matchExpressions":[{"key":"kubernetes.io/metadata.name","operator":"NotIn","values":["kyverno"]}]}}] "oldWebhooks"=null
```
initially, the logs shows the wrong call site …
> upgrade controller-runtime dependency

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Tag v1.8.0-rc6

- cmd/kyverno/informer.go
- cmd/kyverno/main.go
- go.mod
- go.sum
- pkg/controllers/certmanager/controller.go
- pkg/controllers/certmanager/log.go
- pkg/controllers/webhook/controller.go
- pkg/controllers/webhook/log.go
This PR refactors leader controllers management.
> refactor: leader controllers management

- api/kyverno/v1/common_types.go
- charts/kyverno/templates/crds.yaml
- config/crds/kyverno.io_clusterpolicies.yaml
- config/crds/kyverno.io_policies.yaml
- config/install.yaml
- config/install_debug.yaml
- docs/crd/v1/index.html
Update `clusterpolicy.spec.rules.validate.podSecurity.exclude.images` description for the wildcard support.
Closes https://github.com/kyverno/kyverno/issues/4835
> Update PSa images dsecription

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> release: 1.8

- .gitignore
- .vscode/launch.json
This PR adds `launch.json` file for vscode debugging.
> chore: add launch.json for vscode debugging

- pkg/cosign/cosign.go
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>
Fixes #4852 
/kind feature
We added oid (object identifier) keys into the switch/case.
- [] I have raised an issue in [kyverno/website](https://github.com/kyverno/website) to track the documentation update and the link is:
> feature: use cert extension oid as key

- cmd/cli/kubectl-kyverno/Dockerfile
- cmd/initContainer/Dockerfile
- cmd/kyverno/Dockerfile
Cherry-pick: https://github.com/kyverno/kyverno/pull/4413
> bump golang 1.18.5 version digest in Dockerfile (#4413)

- charts/kyverno/README.md
- charts/kyverno/README.md.gotmpl
This PR adds a section in helm docs to install with argocd.
> docs: add section in helm docs to install with argocd

- pkg/controllers/webhook/controller.go
This PR reduces webhook controller logs.
> fix: reduce webhook controller logs

- .github/workflows/helm-release.yaml
- .github/workflows/reuse.yaml
This PR aims to sign Helm Charts by using cosign. 
Successful workflow: 
_https://github.com/developer-guy/kyverno/actions/runs/3177150844_
Closes #4787
/kind feature
_An important note for the maintainers:_
As we publish Helm Chart to a different repository than the actual repository, _ghcr.io/kyverno/charts_, we couldn't use the _GITHUB_TOKEN_ provided by the GitHub Actions; thus, it has only enough permissions to operate on the same repository. To make it work, I've created a personal access token and used it to log in to _ghcr.io_. 
So, we should create a personal access token in order to make it work. 🤷🏻‍♂️
But, if we don't want to create a personal access token in order to sign Helm Chart with cosign, we can use the …
> chore: signing helm releases

- pkg/engine/utils.go
- pkg/engine/utils_test.go
This PR fixes an issue where resources where not correctly matched when using a generated name.
Fixes https://github.com/kyverno/kyverno/issues/4250
> fix: consider generateName when matching resources

- cmd/kyverno/main.go
- pkg/tls/keypair.go
- pkg/tls/renewer.go
- pkg/tls/utils.go
- pkg/utils/runtime/utils.go
This PR makes sure pods are not reporting ready state until certs are valid.
> fix: don't report ready until certs are valid

- go.mod
- go.sum
This PR bumps a few deps
- sigstore/k8s-manifest-sigstore
- sigstore/cosign
> chore: bump a few deps

- api/kyverno/v1alpha2/admission_report_types.go
- charts/kyverno/templates/crds.yaml
- config/crds/kyverno.io_admissionreports.yaml
- config/crds/kyverno.io_clusteradmissionreports.yaml
- config/install.yaml
- config/install_debug.yaml
This PR fixes admission reports printer.
> fix: admission reports printer

- pkg/controllers/webhook/controller.go
This PR fixes missing autogen rules written in status.
> fix: missing autogen rules in status

- OWNERS.md
This PR adds myself in approvers.
> chore: add myself in approvers

- charts/kyverno/README.md
- charts/kyverno/README.md.gotmpl
This PR adds resource exclusions note in helm docs.
NOTE: we should add that on the website too.
> docs: add resource exclusions note in helm docs

- scripts/labs/argocd/README.md
- scripts/labs/argocd/kind-argo.sh
This PR adds policy-reporter to argocd lab.
> feat: add policy-reporter to argocd lab

- pkg/webhooks/resource/validation/validation.go
This PR skips admission report in dry run requests.
> fix: skip admission report in dry run requests

- pkg/webhooks/utils/policy_context_builder.go
This PR fixes the issue of pre-defined variables, request.roles and request.clusterRoles are always substituted correctly
closes https://github.com/kyverno/kyverno/issues/4302
/milestone 1.8.1
/kind bug
Followed the steps given in the issue
1. Run shell script.
2. create Role in the qa Namespace.
3. Create a RoleBinding in the qa Namespace.
4. Create a mutate policy.
5. Create a Deployment by using the kubeconfig
```
KUBECONFIG=vyankateshkudtarkar-kubeconfig kubectl -n qa create deploy busybox --image busybox:1.28 -- sleep 9999
```
Result:
```
"annotations": {
"deployment.kubernetes.io/revision": "1",
"kyverno.io/clusterroles": "[\"system:public-info-viewer\",\"system:discovery\",\"system:basic-user\"]", …
```
> [Bug]: fix principal and role variables are not substituted

- pkg/controllers/webhook/controller.go
- pkg/utils/controller/run.go
This PR fixes update to policy status.
We were returning early when no error occured, not processing the whole policy list.
> fix: update policy status

- pkg/controllers/report/background/controller.go
- pkg/controllers/report/utils/utils.go
This PR removes non background policies in background scan.
> fix: don't process non background policies in background scan

- pkg/policy/validate.go
This PR fixes policy not denied when kinds set is empty.
Fixes #3731
> fix: policy not denied when kinds set is empty

- pkg/webhooks/utils/policy_context_builder.go
remove RBACInfo check as not required.
https://github.com/kyverno/kyverno/issues/4302
Followed the steps given in the issue
1. Run shell script.
2. create Role in the qa Namespace.
3. Create a RoleBinding in the qa Namespace.
4. Create a mutate policy.
5. Create a Deployment by using the kubeconfig
```
KUBECONFIG=vyankateshkudtarkar-kubeconfig kubectl -n qa create deploy busybox --image busybox:1.28 -- sleep 9999
```
Result:
```
"annotations": {
"deployment.kubernetes.io/revision": "1",
"kyverno.io/clusterroles": "[\"system:public-info-viewer\",\"system:discovery\",\"system:basic-user\"]",
"kyverno.io/roles": "[\"qa:example\"]",
"kyverno.io/userinfo": …
```
> remove RBACInfo check

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Tag v1.8.1-rc1

- pkg/controllers/certmanager/controller.go
- pkg/controllers/certmanager/log.go
- pkg/controllers/config/controller.go
- pkg/controllers/config/log.go
- pkg/controllers/metrics/policy/log.go
- pkg/controllers/openapi/log.go
- pkg/controllers/policycache/controller.go
- pkg/controllers/policycache/log.go
- pkg/controllers/report/admission/controller.go
- pkg/controllers/report/admission/log.go
- pkg/controllers/report/aggregate/controller.go
- pkg/controllers/report/aggregate/log.go
- pkg/controllers/report/background/controller.go
- pkg/controllers/report/background/log.go
- pkg/controllers/report/resource/controller.go
- pkg/controllers/report/resource/log.go
- pkg/controllers/webhook/controller.go
- pkg/logging/log.go
This PR adds a controller logger helper to create a logger to be used by controller.
> feat: add controller logger helper

- pkg/controllers/report/utils/scanner.go
This PR adds image verification support to background scan.
Fixes #4977
> feat: add image verification support to background scan

- cmd/kyverno/main.go
This PR sets up max procs with the correct logger.
> fix: setup max procs with correct logger

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
This PR is preparing for release 1.8.1-rc.2.
> release: 1.8.1-rc.2

- test/conformance/main.go
- test/conformance/tests.yaml
This PR adds best practices policies in conformance tests.
> test: add best practices policies in conformance tests

- .github/workflows/release.yaml
> Cherry pick 5035, 5046

- pkg/background/update_request_controller.go
Handle delete of `UpdateRequest` when policy is deleted based on synchronize field has been configured.
There was a regression due to merge of cleanup and generate controller which missed this case to handle the date policy correctly.
Fixes: https://github.com/kyverno/kyverno/issues/5018
`/milestone 1.8.1`
> /kind bug
****1.** Generate data Policy with `synchronize: false` , on policy delete,  only the `UpdateRequest` gets deleted**
```yaml
metadata:
name: cp1
spec:
rules:
- name: r1
match:
any:
- resources:
kinds:
- Namespace
generate:
synchronize: false
apiVersion: v1
name: cm1
namespace: "{{request.object.metadata.name}}"
data:
data:
test.yml: |-
cm1 …
```
> fix: handle resource cleanup when policy is deleted

- pkg/background/common/util.go
- pkg/background/generate/generate.go
- test/e2e/generate/config.go
Allow delete of target resource with `synchronize:false` in generate data policy. 
Fixes:#4457
`/milestone 1.8.1`
> /kind bug
> fix: allow delete of target resource data with synchronize false

- cmd/kyverno/main.go
- pkg/controllers/report/background/controller.go
- pkg/controllers/webhook/controller.go
This PR fixes incorrect side effects in validating webhooks.
Fixes #4105
> fix: use correct side effects in validating webhooks

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.8.1-rc.3

- test/conformance/tests.yaml
This PR fixes conformance tests.
> fix: conformance tests

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.8.1

- pkg/webhooks/resource/handlers.go
- pkg/webhooks/resource/handlers_test.go
Cherry-pick 632bd99 commit into release-1.8
PR for original change: https://github.com/kyverno/kyverno/pull/4996
> Fixed issue-4655: verifyImages is executed before mutate

- pkg/webhooks/utils/event.go
This PR fixes mismatched events generated for non-applicable policies.
Closes https://github.com/kyverno/kyverno/issues/5155.
https://github.com/kyverno/kyverno/issues/3970
/1.8.2
/bug
Follow the steps described in the issue and verify there's no events generated for the default namespace:
> fix: policy events created for non-applied resources

- cmd/cli/kubectl-kyverno/utils/common/common.go
- test/cli/test/owner_references/kyverno-test.yaml
- test/cli/test/owner_references/policy.yaml
- test/cli/test/owner_references/resource.yaml
This Pr fix cli issue for resources which includes `ownerReferences` fields value.
Closes https://github.com/kyverno/kyverno/issues/5151
/milestone 1.9.0
/kind bug
In kyverno CLI there is no need to remove autogen-controllers annotations if resources have ownerReferences defined.
This cause breaking autogen test cases for cli 
Added test cases
> [Cli Bug] fix cli issue for ownerReferences resources

- pkg/webhooks/handlers/admission.go
This PR fixes content type in log.
> fix: content type in log

- api/kyverno/v1/clusterpolicy_types.go
- api/kyverno/v1/policy_interface.go
- api/kyverno/v1/policy_types.go
- api/kyverno/v1/spec_types.go
- api/kyverno/v2beta1/spec_types.go
- charts/kyverno/templates/crds.yaml
- config/crds/kyverno.io_clusterpolicies.yaml
- config/crds/kyverno.io_policies.yaml
- docs/user/crd/index.html
- pkg/webhooks/resource/mutation/mutation.go
Kyverno validates schema patterns on patched resources for mutate policies. However when the corresponding kinds (usually CRDs) don't have a schema defined, the validation fails. This PR provides an option to disable such schema validation via `policy.spec.schemaValidation`.
https://github.com/kyverno/kyverno/issues/5136
/1.8.2
Extend `policy.spec.schemaValidation` to the schema validation on patched resources.
Follow [these](https://github.com/kyverno/kyverno/issues/5136#issuecomment-1298114074) steps and set `cpol.spec.schemaValidation=false`, verify no following messages printed in Kyverno logs:
```
... failed to validate resource mutated by policy ... couldn't find model , err: invalid kind" "kind"="RangeAllocation" …
```
> feat: support disabling schema validation on the patched resource

- pkg/policy/validate.go
- pkg/policy/validate_test.go
- pkg/utils/admission/utils.go
- pkg/webhooks/policy/handlers.go
This PR fixes early return in policy validation.
Returning early has the negative effect of bypassing some validation rules.
> fix: early return in policy validation

- pkg/metrics/common_types.go
- pkg/metrics/metrics.go
- pkg/metrics/policyexecutionduration/policyExecutionDuration.go
- pkg/policy/existing.go
- pkg/webhooks/utils/metrics.go
This PR removes the following filter labels from the metric `kyverno_policy_execution_duration_seconds`:
- resource_kind
- resource_namespace
- resource_request_operation
- general_rule_latency_type
Now this metric only reports execution latency by rule info.
Closes https://github.com/kyverno/kyverno/issues/4959.
/1.8.2
https://github.com/kyverno/website/issues/678
> fix: too much information for the Policy Rule Execution Latency metric

- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex-keyless/01-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex-keyless/01-manifests.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex-keyless/02-task.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex-keyless/03-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex-keyless/99-cleanup.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex-keyless/README.md
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/01-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/01-manifests.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/02-create-task.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/03-errors.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/99-cleanup.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/README.md
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/badtask.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-none/01-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-none/01-manifests.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-none/02-task.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-none/03-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-none/99-cleanup.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-none/README.md
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/01-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/01-manifests.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/02-create-task.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/03-errors.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/99-cleanup.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/README.md
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/badtask.yaml
* Adds the remainder of the e2e verifyImages tests as kuttl tests. The only exception here was the test with raw policy named `kyvernoTaskPolicyKeyless` as not ported as there was no functional difference between it and `kyvernoTaskPolicyKeylessRequired`.
Partially addresses #5203 
/kind tests
> add remainder of e2e verifyImages tests

- api/kyverno/v1/image_verification_types.go
- charts/kyverno/templates/crds.yaml
- config/crds/kyverno.io_clusterpolicies.yaml
- config/crds/kyverno.io_policies.yaml
- config/install.yaml
- config/install_debug.yaml
- docs/user/crd/index.html
This PR fixes description for `attestor.entries.secret`
#4530 
/milestone 1.9.0
Fixed description for `attestor.entries.secret`
> Fixed description for secret name

- pkg/webhooks/handlers/admission.go
- pkg/webhooks/handlers/dump.go
- pkg/webhooks/handlers/dump_test.go
- pkg/webhooks/handlers/filter.go
- pkg/webhooks/handlers/protect.go
- pkg/webhooks/handlers/verify.go
- pkg/webhooks/server.go
This PR moves all middlewares in handlers sub package.
> refactor: move all middlewares in handlers sub package

- pkg/config/config.go
This PR removes unused code in config package.
> fix: remove unused code in config

- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex-keyless/01-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex-keyless/01-manifests.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex-keyless/02-task.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex-keyless/03-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex-keyless/99-cleanup.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex-keyless/README.md
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/01-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/01-manifests.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/02-create-task.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/03-errors.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/99-cleanup.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/README.md
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-complex/badtask.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-none/01-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-none/01-manifests.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-none/02-task.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-none/03-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-none/99-cleanup.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-none/README.md
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/01-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/01-manifests.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/02-create-task.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/03-errors.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/99-cleanup.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/README.md
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/badtask.yaml
add remainder of e2e verifyImages tests (cherry-pick #5229)
> add remainder of e2e verifyImages tests (cherry-pick #5229)

- pkg/utils/admission/response.go
- pkg/utils/admission/response_test.go
- pkg/utils/admission/utils.go
- pkg/webhooks/handlers/protect.go
- pkg/webhooks/handlers/verify.go
- pkg/webhooks/policy/handlers.go
- pkg/webhooks/resource/handlers.go
- pkg/webhooks/resource/utils.go
refactor: admission response utils (cherry-pick #5234)
> refactor: admission response utils (cherry-pick #5234)

- cmd/kyverno/main.go
- pkg/metrics/admissionrequests/admissionRequests.go
- pkg/metrics/admissionreviewduration/admissionReviewDuration.go
- pkg/webhooks/handlers/admission.go
- pkg/webhooks/handlers/filter.go
- pkg/webhooks/handlers/metrics.go
- pkg/webhooks/handlers/protect.go
- pkg/webhooks/resource/generation/generation.go
- pkg/webhooks/resource/mutation/mutation.go
- pkg/webhooks/resource/updaterequest.go
- pkg/webhooks/resource/validation/validation.go
- pkg/webhooks/server.go
- pkg/webhooks/utils/metrics.go
refactor: admission metrics (counter and latency) (cherry-pick #5245)
> refactor: admission metrics (counter and latency) (cherry-pick #5245)

- pkg/background/generate/generate.go
- test/conformance/kuttl/kuttl-test.yaml
Signed-off-by: Prateek Pandey <prateek.pandey@nirmata.com>
Allow delete of cloned target resource with `synchronize:false` in generate clone policy.
Fixes https://github.com/kyverno/kyverno/issues/4457
/milestone 1.8.2
Allow delete of cloned target resource with `synchronize:false` in generate clone policy.
> fix: allow delete of clone target resource with synchronize false

- pkg/policy/validate.go
> chore: Fix policy installation issue (cherry-pick #5239)

- pkg/controllers/webhook/controller.go
- pkg/policy/validate.go
- pkg/utils/controller/run.go
- pkg/webhooks/resource/generation/generation.go
- pkg/webhooks/resource/updaterequest.go
- pkg/webhooks/utils/exclude.go
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-list-sync-update/00-cluster-policy.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-list-sync-update/01-trigger.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-list-sync-update/02-update.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-list-sync-update/03-update-source.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-list-sync-update/README.md
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-list-sync-update/cluster-policy-ready.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-list-sync-update/cluster-policy.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-list-sync-update/manifests.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-list-sync-update/ns.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-list-sync-update/resource-assert.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-list-sync-update/synchronized-target.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-list-sync-update/update-source.yaml
To keep the resources synchronized across source resource changes, you can use the synchronize property. When `synchronize` is set to true, the generated resource is kept in-sync with the source resource. These changes fixes the behavior which was not working when we use the multiple clone feature using CloneList parameter in Policy.
Fixes #4930
> /kind bug
Refer [kuttl tests ](https://github.com/kyverno/kyverno/pull/5317/commits/777ad7c17d3d209024f60ec74bfb85ebdcb83cf7) for proof manifests.
> fix: synchronize source resource update to clone list resource

- test/conformance/kuttl/kuttl-test.yaml
- test/conformance/kuttl/webhooks/expected-webhooks/00-webhooks.yaml
- test/conformance/kuttl/webhooks/expected-webhooks/README.md
- test/conformance/kuttl/webhooks/expected-webhooks/webhooks.yaml
This PR adds test to check expected webhooks are created.
> test: add test to check expected webhooks are created

- .github/workflows/image.yaml
Fixes the variable used to reference the SHA256 digests of the Kyverno artifacts in order to allow the SLSA provenance generator to run. The `image.yaml` workflow was incorrectly referring to the digest of the artifacts as perhaps an older variable named defined in `reuse.yaml`. This fix updates `image.yaml` to consume the output variables with the digests as set through `reuse.yaml`.
> fix digest variable

- test/cli/test/manifests/verify-signature/kyverno-test.yaml
- test/cli/test/manifests/verify-signature/policies.yaml
- test/cli/test/manifests/verify-signature/resources.yaml
Cherry-pick https://github.com/kyverno/kyverno/pull/5326.
* add test cases for yaml verification feature
Signed-off-by: Riko Kudo <rurikudo@ibm.com>
* update policies to use the new schema version
Signed-off-by: Riko Kudo <rurikudo@ibm.com>
Signed-off-by: Riko Kudo <rurikudo@ibm.com>
Co-authored-by: Chip Zoller <chipzoller@gmail.com>
Co-authored-by: shuting <shuting@nirmata.com>
> Cherry pick #5326

- test/conformance/kuttl/kuttl-test.yaml
- test/conformance/kuttl/rbac/aggregate-to-admin/00-cluster-role.yaml
- test/conformance/kuttl/rbac/aggregate-to-admin/README.md
- test/conformance/kuttl/rbac/aggregate-to-admin/admin-generaterequest.yaml
- test/conformance/kuttl/rbac/aggregate-to-admin/admin-policies.yaml
- test/conformance/kuttl/rbac/aggregate-to-admin/admin-policyreport.yaml
- test/conformance/kuttl/rbac/aggregate-to-admin/admin-reports.yaml
- test/conformance/kuttl/rbac/aggregate-to-admin/admin-updaterequest.yaml
Cherry-pick https://github.com/kyverno/kyverno/pull/5337.
> cherry-pick test: add rbac kuttl test (#5337)

- pkg/tracing/tracing.go
- pkg/webhooks/handlers/admission.go
This PR improves the tracing package:
- returns context for further propagation
- support variadic attributes
> refactor: improve tracing package

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- config/install.yaml
- config/install_debug.yaml
> Release v1.8.2-rc.1

- cmd/kyverno/main.go
Signed-off-by: damilola olayinka <holayinkajr@gmail.com>
Adds missing os.Exit line after error logging in metrics server.
> fix: add os.Exit

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.8.2-rc.2

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.8.2

- .github/ISSUE_TEMPLATE/bug-cli.yaml
- .github/ISSUE_TEMPLATE/bug-other.yaml
- .github/ISSUE_TEMPLATE/bug-webhook.yaml
- .github/workflows/report-on-vulnerabilities.yaml
* Bumps Trivy to 0.34
* Adds 1.8.2 to all issue template drop-downs
> Update version drop-downs; bump Trivy

- pkg/controllers/report/resource/controller.go
This PR add a log when getting a watcher error occurs.
> fix: log watcher error in reports controller

- Makefile
This PR adds instrumented clients codegen verification.
> chore: add instrumented clients codegen verification

- cmd/kyverno/main.go
- pkg/engine/mutate/patch/strategicMergePatch.go
This PR fixes an issue when calling kustomize concurrently.
Fixes https://github.com/kyverno/kyverno/issues/3585
> fix: issue when calling kustomize concurrently

- cmd/kyverno/main.go
fix: issue when calling kustomize concurrently (cherry-pick #5465)
> fix: issue when calling kustomize concurrently (cherry-pick #5465)

- pkg/webhooks/handlers/filter.go
- pkg/webhooks/policy/handlers.go
- pkg/webhooks/resource/handlers.go
- pkg/webhooks/server.go
This PR add new filtering handlers:
- one for filtering admission request operations
- one for filtering admission request subresource
> feat: add new filtering handlers

- scripts/labs/argocd/7-kyverno.sh
- scripts/labs/argocd/8-kyverno-policies.sh
This PR bumps kyverno charts versions in argo lab.
> chore: bump kyverno version in argo lab

- pkg/metrics/admissionrequests/admissionRequests.go
- pkg/metrics/admissionreviewduration/admissionReviewDuration.go
- pkg/metrics/metrics.go
- pkg/webhooks/handlers/metrics.go
This PR adds a `request_allowed` label to admission metrics.
> feat: add allowed label to admission metrics

- pkg/webhooks/handlers/metrics.go
This PR fixes a panic when response is nil.
> fix: panic when response is nil

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Tag 1.8.3-rc.1

- ADOPTERS.md
Signed-off-by: Saim Safdar <59512053+Saim-Safdar@users.noreply.github.com>
> Adding Rafay Systems to Kyverno Adopters list.

- pkg/controllers/report/resource/controller.go
This PR fixes a bug in report resource watcher.
The `gvr`/`gvk` were not correctly captured and it introduced a mismatch when the watcher received an event.
> fix: bug in report resource watcher

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.8.3-rc.2

- .github/workflows/image.yaml
https://github.com/slsa-framework/slsa-github-generator/releases/tag/v1.4.0
> Bump SLSA GitHub generator to 1.4.0

- ADOPTERS.md
Adds Wayfair to list of adopters
> add Wayfair to adopters

- cmd/cli/kubectl-kyverno/jp/jp_command.go
This PR refactors cli jp command:
- split into small functions making the code easier to read
- improves the rendering of functions list
```
Name: add
Signature: add(any, any) any
Name: base64_decode
Signature: base64_decode(string) string
Name: base64_encode
Signature: base64_encode(string) string
Name: compare
Signature: compare(string, string) number
Name: divide
Signature: divide(any, any) any
Note:      divisor must be non zero
Name: equal_fold
Signature: equal_fold(string, string) bool
Name: items
Signature: items(object, string, string) array
Note:      converts a map to an array of objects where each key:value is an item in the array
Name: label_match
Signature: label_match(object, object) bool
Note:      object …
```
> refactor: cli jp command

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.8.4-rc.1

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> release v1.8.4

- .github/workflows/helm-test.yaml
This PR includes these changes.
- Set fetch-depth as zero instead of run unshallow step
- Run helm test only for changes on charts
helm-test workflow has a trigger limitation with these paths.
https://github.com/kyverno/kyverno/blob/cf8c91dfd9dd59d96c5d65923b35cd5982b46219/.github/workflows/helm-test.yaml#L7-L9
When `.github/workflows/helm-test.yaml` file is changed without changes in `charts/` dir, helm test cli is failing because of no changes here.
https://github.com/kyverno/kyverno/blob/cf8c91dfd9dd59d96c5d65923b35cd5982b46219/.github/workflows/helm-test.yaml#L31
In this PR, this is fixed by checking chart changes before lint.
https://github.com/kyverno/kyverno/blob/306e7d3eb507d1cb35ee4748a445f5809adba79d/.github/workflows/helm-test.yaml#L29-L34
Signed-off-by: cuttingedge1109 …
> fix: Improve helm-test workflow

- ADOPTERS.md
Added two adopters based on entries in Google Form
Adds Arrikto and Trendyol as Kyverno adopters.
> added Arrikto and Trendyol as adopters (via Google Form)

- .github/workflows/conformance.yaml
- charts/kyverno/templates/cleanup-controller/role.yaml
This PR fixes a missing permission in cleanup controller role (must read configmap).
> fix: missing permission in cleanup controller role

- api/kyverno/v2alpha1/policy_exception_types.go
- cmd/kyverno/main.go
- pkg/webhooks/exception/validate.go
- pkg/webhooks/server.go
Follow up PR for policy exception validation webhook.
> fix: exception validation follow up

- api/kyverno/v1/clusterpolicy_types.go
- api/kyverno/v1alpha2/admission_report_types.go
- api/kyverno/v1alpha2/background_scan_report_types.go
- api/kyverno/v1beta1/updaterequest_types.go
- api/kyverno/v2beta1/clusterpolicy_types.go
- charts/kyverno/templates/crds.yaml
- config/crds/kyverno.io_admissionreports.yaml
- config/crds/kyverno.io_backgroundscanreports.yaml
- config/crds/kyverno.io_clusteradmissionreports.yaml
- config/crds/kyverno.io_clusterbackgroundscanreports.yaml
- config/crds/kyverno.io_clusterpolicies.yaml
- config/crds/kyverno.io_updaterequests.yaml
- config/install.yaml
- config/install_debug.yaml
Delete category all from CRDs (cherry-pick #5557)
> Delete category all from CRDs (cherry-pick #5557)

- pkg/policy/policy_controller.go
Fix missing assignment in https://github.com/kyverno/kyverno/issues/5704.
> fix: missing assignment in configmap resolver 

- pkg/engine/imageVerify.go
- pkg/engine/imageVerify_test.go
Cherry-pick https://github.com/kyverno/kyverno/pull/5703, https://github.com/kyverno/kyverno/pull/5715.
> cherry-pick: fix digest and verify logic

- api/kyverno/v1/image_verification_types.go
- charts/kyverno/templates/crds.yaml
- config/crds/kyverno.io_clusterpolicies.yaml
- config/crds/kyverno.io_policies.yaml
- config/install.yaml
- config/install_debug.yaml
- docs/user/crd/index.html
- pkg/engine/imageVerify.go
> Cherry-pick Require predicate type

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.8.5-rc.1

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.8.5

- CHANGELOG.md
- cmd/kyverno/main.go
- pkg/controllers/report/background/controller.go
- pkg/controllers/report/utils/utils.go
This PR forces background scan at regular intervals.
Fixes https://github.com/kyverno/kyverno/issues/5642
> feat: force background scan regularly

- .github/workflows/reuse.yaml
- Makefile
This PR fixes cleanup controller image build
> fix: cleanup controller image build

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.9.0-beta.1

- .github/workflows/reuse.yaml
Attempt to fix the image digest variable. If succeed, I will cherry-pick it to main.
> fix: image digest

- .github/workflows/reuse.yaml
Cherry-pick https://github.com/kyverno/kyverno/pull/5762.
> cherry-pick: fix image digest (#5762)

- go.mod
- go.sum
Bump go-plugin dep to fix the release issue.
> Bump go-plugin

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
Remove `v` from the chart's version.
> fix: chart version

- .github/ISSUE_TEMPLATE/bug-cli.yaml
- .github/ISSUE_TEMPLATE/bug-other.yaml
- .github/ISSUE_TEMPLATE/bug-webhook.yaml
Adds 1.9.0 to all issue template drop-down menus. Adds "Cleanup" to rule type drop-down.
> add 1.9.0 to version drop-downs

- pkg/background/update_request_controller.go
> cherry-pick: fix delete policy (#5776)

- api/kyverno/v1/image_verification_types.go
- charts/kyverno/templates/crds.yaml
- config/crds/kyverno.io_clusterpolicies.yaml
- config/crds/kyverno.io_policies.yaml
- config/install.yaml
- docs/user/crd/index.html
Closes https://github.com/kyverno/kyverno/issues/5784.
/1.9.0
> chore: update publicKey description

- .github/workflows/helm-release.yaml
Co-authored-by: shuting <shuting@nirmata.com>
Cherry-pick #5782.
> cherry-pick: redirect stderr to get digest successfully (#5782)

- cmd/cli/kubectl-kyverno/oci/oci.go
- cmd/cli/kubectl-kyverno/oci/oci_pull.go
- cmd/cli/kubectl-kyverno/oci/oci_push.go
This PR aims to improve the logging of the oci subcommand, fix the pull flag description to cover the pull capability.
/kind feature
/kind bug
/cc @chipzoller
> enhance logging, fix pull flag description

- .goreleaser.yml
I'm trying to [add kyverno CLI into the Wolfi OS](https://github.com/wolfi-dev/os/pull/338) by Chainguard Team, then while working on this issue, I've noticed that there is no checksum information about the tar archieve for the source code, so, this PR is going to add this support.
/kind feature
> add source archive checksum into the checksums.txt

- api/kyverno/v1/spec_types.go
- charts/kyverno/templates/crds.yaml
- config/crds/kyverno.io_clusterpolicies.yaml
- config/crds/kyverno.io_policies.yaml
- config/install.yaml
This PR fixes enum values for ValidationFailureActionOverride.
> fix: enum values for ValidationFailureActionOverride

- .github/workflows/codecov.yaml
- .github/workflows/comment-commands.yaml
- .github/workflows/conformance.yaml
This PR simplifies the workflow for code coverage report.
> chore: cleanup codecov workflow

- pkg/policy/validate/validate.go
- allow any list to be used in validate.foreach.list
- allow nested foreach in validate rules 
https://github.com/kyverno/kyverno/issues/5451
Fixes https://github.com/kyverno/kyverno/issues/5859
https://github.com/kyverno/kyverno/pull/5589#issuecomment-1367347185
1.9.x
/kind bug
Fix validation checks for foreach and nested foreach
> fix validation checks for foreach and nested foreach

- pkg/controllers/report/background/controller.go
- pkg/controllers/report/resource/controller.go
- pkg/utils/controller/metadata.go
refactor: improve background scan reconciliation (cherry-pick #5871)
> refactor: improve background scan reconciliation (cherry-pick #5871)

- .github/actions/setup-build-env/action.yaml
- .github/workflows/cli.yaml
- .github/workflows/codecov.yaml
- .github/workflows/conformance.yaml
- .github/workflows/fossa.yml
- .github/workflows/helm-release.yaml
- .github/workflows/helm-test.yaml
- .github/workflows/image-build.yaml
- .github/workflows/nancy.yaml
- .github/workflows/release.yaml
- .github/workflows/report-on-vulnerabilities.yaml
- .github/workflows/sonarcloud.yaml
- .github/workflows/tests.yaml
- .github/workflows/verify-codegen.yaml
chore: add setup-build-env gh action (cherry-pick #5892)
> chore: add setup-build-env gh action (cherry-pick #5892)

- .github/workflows/cli.yaml
- .github/workflows/codecov.yaml
- .github/workflows/fossa.yml
- .github/workflows/nancy.yaml
- .github/workflows/sonarcloud.yaml
- .github/workflows/verify-codegen.yaml
This PR configures gh workflow permissions.
This fix some security warnings.
> fix: configure gh workflow permission

- .github/workflows/cli.yaml
- .github/workflows/codecov.yaml
- .github/workflows/fossa.yml
- .github/workflows/nancy.yaml
- .github/workflows/sonarcloud.yaml
- .github/workflows/verify-codegen.yaml
fix: configure gh workflow permission (cherry-pick #5909)
> fix: configure gh workflow permission (cherry-pick #5909)

- .github/workflows/tests.yaml
- .github/workflows/verify-codegen.yaml
fix: golangci-lint workflow (cherry-pick #5913)
> fix: golangci-lint workflow (cherry-pick #5913)

- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
Update Helm chart appVersion to latest
1.10 
/kind cleanup
Remove v1.7.3 as appVersion and set to `latest` instead
```sh
❯ helm install kyverno -n kyverno charts/kyverno --create-namespace
NAME: kyverno
LAST DEPLOYED: Thu Jan  5 14:10:16 2023
NAMESPACE: kyverno
STATUS: deployed
REVISION: 1
NOTES:
Chart version: v2.5.3
Kyverno version: latest
Thank you for installing kyverno! Your release is named kyverno.
⚠️  WARNING: Setting replicas count below 3 means Kyverno is not running in high availability mode.
💡 Note: There is a trade-off when deciding which approach to take regarding Namespace exclusions. Please see the documentation at https://kyverno.io/docs/installation/#security-vs-operability to understand the risks.
kyverno on  main [$!?] via …
```
> switch app version to latest

- .github/workflows/cli.yaml
- .github/workflows/codecov.yaml
- .github/workflows/fossa.yml
- .github/workflows/helm-release.yaml
- .github/workflows/helm-test.yaml
- .github/workflows/image-build.yaml
- .github/workflows/image.yaml
- .github/workflows/nancy.yaml
- .github/workflows/release.yaml
- .github/workflows/scorecard.yaml
- .github/workflows/sonarcloud.yaml
This PR adds missing gh workflow concurrency statements.
> chore: add missing gh workflow concurrency statements

- .github/actions/is-defined/action.yaml
- .github/workflows/pr-update.yaml
This PR fixes condition jobs in gh workflows.
> fix: condition jobs in gh workflows

- .github/workflows/tests.yaml
- Makefile
This PR simplifies tests workflow:
- moves things in makefile
- merge both jobs together
> chore: simplify tests workflow

- .github/workflows/cli.yaml
- README.md
This PR fixes releaser badge in README.
> chore: fix releaser badge

- .github/workflows/cli.yaml
- .github/workflows/codecov.yaml
- .github/workflows/fossa.yml
- .github/workflows/helm-release.yaml
- .github/workflows/helm-test.yaml
- .github/workflows/image-build.yaml
- .github/workflows/image.yaml
- .github/workflows/nancy.yaml
- .github/workflows/release.yaml
- .github/workflows/scorecard.yaml
- .github/workflows/sonarcloud.yaml
chore: add missing gh workflow concurrency statements (cherry-pick #5914)
> chore: add missing gh workflow concurrency statements (cherry-pick #5914)

- pkg/engine/jmespath/functions.go
- pkg/engine/jmespath/functions_test.go
Added a time_add() filter to add duration and absolute time (cherry-pick #5817)
> Added a time_add() filter to add duration and absolute time (cherry-pick #5817)

- .github/workflows/cli.yaml
- README.md
chore: fix releaser badge (cherry-pick #5910)
> chore: fix releaser badge (cherry-pick #5910)

- api/kyverno/v2alpha1/policy_exception_types.go
- charts/kyverno/templates/crds.yaml
- config/crds/kyverno.io_policyexceptions.yaml
- config/install.yaml
- docs/user/crd/index.html
This PR updates policyExcetion CRD description.
Closes https://github.com/kyverno/kyverno/issues/5945.
/1.9.0
/bug
> fix: update policy exception CRD description

- pkg/controllers/report/background/controller.go
- pkg/controllers/report/resource/controller.go
- pkg/controllers/report/utils/utils.go
> chore: policy report - improve logging (cherry-pick #5941)

- pkg/engine/jmespath/functions.go
- pkg/engine/jmespath/functions_test.go
- pkg/engine/jmespath/time.go
- pkg/engine/jmespath/time_test.go
> feat: add more time jmespath filters - Cherry pick 5950

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.9.0-beta.2

- .github/workflows/release.yaml
> chore: upload CRDs manifests to GH release (cherry-pick #5967)

- pkg/engine/jmespath/functions.go
- pkg/engine/jmespath/functions_test.go
> Fixes time_now failing (cherry-pick 5928)

- .github/workflows/tests.yaml
- Makefile
> chore: simplify tests workflow (cherry-pick #5920)

- pkg/controllers/report/utils/events.go
- pkg/event/events.go
- pkg/webhooks/utils/event.go
fix: generate policy exception events (cherry-pick #5987)
> fix: generate policy exception events (cherry-pick #5987)

- cmd/kyverno/main.go
- pkg/controllers/report/background/controller.go
- pkg/controllers/report/utils/scanner.go
- pkg/engine/validation.go
- test/conformance/kuttl/reports/admission/exception/01-policy.yaml
- test/conformance/kuttl/reports/admission/exception/02-exception.yaml
- test/conformance/kuttl/reports/admission/exception/03-configmap.yaml
- test/conformance/kuttl/reports/admission/exception/04-report.yaml
- test/conformance/kuttl/reports/admission/exception/README.md
- test/conformance/kuttl/reports/admission/exception/configmap.yaml
- test/conformance/kuttl/reports/admission/exception/exception.yaml
- test/conformance/kuttl/reports/admission/exception/policy-assert.yaml
- test/conformance/kuttl/reports/admission/exception/policy.yaml
- test/conformance/kuttl/reports/admission/exception/report-assert.yaml
- test/conformance/kuttl/reports/background/exception/01-policy.yaml
- test/conformance/kuttl/reports/background/exception/02-exception.yaml
- test/conformance/kuttl/reports/background/exception/03-configmap.yaml
- test/conformance/kuttl/reports/background/exception/04-report.yaml
- test/conformance/kuttl/reports/background/exception/README.md
- test/conformance/kuttl/reports/background/exception/configmap.yaml
- test/conformance/kuttl/reports/background/exception/exception.yaml
- test/conformance/kuttl/reports/background/exception/policy-assert.yaml
- test/conformance/kuttl/reports/background/exception/policy.yaml
- test/conformance/kuttl/reports/background/exception/report-assert.yaml
fix: policy exceptions not working in background mode (cherry-pick #5980)
> fix: policy exceptions not working in background mode (cherry-pick #5980)

- pkg/engine/utils_test.go
- pkg/utils/match/kind.go
- pkg/utils/match/kind_test.go
- test/cli/test/wildcard_match_label_selector/policy.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/00-create-crd.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/01-assert.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/01-manifests.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/02-script.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/99-cleanup.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/README.md
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/postgresqls-ready.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/postgresqls.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/resource.yaml
Signed-off-by: Vyom-Yadav <jackhammervyom@gmail.com>
Kyverno was updating the kind in the policy to title case while comparing it with the admission review request. Though the preferred pattern for kinds is PascalCase but lowercase kinds are also allowed, for eg [posgresql crd](https://github.com/zalando/postgres-operator/blob/ce1fee858634f4058ea82bff354e3c64b78d952d/charts/postgres-operator/crds/postgresqls.yaml)
Closes #5989
/kind bug
kuttl e2e test added.
> fix: policy match Kind case-senstive

- pkg/engine/utils_test.go
- pkg/utils/match/match.go
- pkg/utils/match/match_test.go
- test/cli/test/wildcard_match_label_selector/policy.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/00-create-crd.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/01-assert.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/01-manifests.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/02-script.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/99-cleanup.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/README.md
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/postgresqls-ready.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/postgresqls.yaml
- test/conformance/kuttl/validate/e2e/lowercase-kind-crd/resource.yaml
Cherry-picked fix: policy match Kind case-senstive (#6008) 
Signed-off-by: Vyom-Yadav [jackhammervyom@gmail.com](mailto:jackhammervyom@gmail.com)
> fix: policy match Kind case-senstive (cherry-pick #6008)

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> tag v1.9.0-rc.1

- pkg/engine/utils.go
- test/conformance/kuttl/validate/clusterpolicy/standard/enforce/ns-selector-with-wildcard-kind/01-ns.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/enforce/ns-selector-with-wildcard-kind/02-policy.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/enforce/ns-selector-with-wildcard-kind/03-pod-fail.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/enforce/ns-selector-with-wildcard-kind/README.md
- test/conformance/kuttl/validate/clusterpolicy/standard/enforce/ns-selector-with-wildcard-kind/ns.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/enforce/ns-selector-with-wildcard-kind/pod-fail.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/enforce/ns-selector-with-wildcard-kind/pod-pass.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/enforce/ns-selector-with-wildcard-kind/policy-assert.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/enforce/ns-selector-with-wildcard-kind/policy.yaml
Cherry-pick https://github.com/kyverno/kyverno/pull/6020.
> fix: ns labels matching (cherry-pick #6020)

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.9.0-rc.2

- charts/kyverno/README.md
- charts/kyverno/values.yaml
- cmd/kyverno/main.go
- cmd/reports-controller/main.go
- config/install.yaml
- pkg/controllers/report/background/controller.go
- pkg/controllers/report/utils/scanner.go
- pkg/engine/policyContext.go
- pkg/webhooks/resource/handlers.go
- pkg/webhooks/utils/policy_context_builder.go
- scripts/config/dev/kyverno.yaml
- scripts/config/standard/kyverno.yaml
> feat: add missing polex flags (cherry-pick #6030)

- charts/kyverno/README.md
- charts/kyverno/templates/_helpers.tpl
- charts/kyverno/templates/config/_helpers.tpl
- charts/kyverno/templates/config/imagepullsecret.yaml
- charts/kyverno/values.yaml
This PR moves helm image pull secrets in config folder.
> refactor: move helm image pull secrets in config folder

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.9.0-rc.3

- pkg/webhooks/handlers/protect.go
This PR allows deletion of namespace containing managed resources (when managed resources protection is enabled).
Fixes https://github.com/kyverno/kyverno/issues/6097
> fix: allow deletion of namespace containing managed resources

- .ko.yaml
This PR fixes new binaries version not embedded in the binaries.
> fix: new binaries version

- cmd/cleanup-controller/main.go
- cmd/initContainer/main.go
- cmd/internal/setup.go
- cmd/internal/tracing.go
- cmd/kyverno/main.go
- cmd/reports-controller/main.go
- cmd/updaterequest-controller/main.go
- pkg/tracing/attributes.go
- pkg/tracing/config.go
- pkg/webhooks/handlers/trace.go
This PR fixes tracing attributes length and tracer name.
> fix: tracing attributes length and tracer name

- Makefile
- pkg/controllers/report/utils/events.go
- pkg/event/events.go
- pkg/webhooks/utils/event.go
This PR fixes incorrect policy exception event source.
> fix: policy exception event source

- Makefile
This PR updates kuttl to fix a deletion race.
> fix: update kuttl to fix deletion race

- Makefile
This PR adds missing image tag values in makefile.
> fix: missing image tag values in makefile

- Makefile
This PR removes obsolete targets from makefile.
> chore: remove obsolete targets from makefile

- charts/kyverno/templates/NOTES.txt
This PR adds deployed components to helm chart notes.
> chore: add deployed components to helm chart notes

- api/kyverno/v1/spec_types.go
- pkg/engine/api/engineresponse_test.go
This PR adds more engine api package unit tests.
> test: add more engine api package tests

- pkg/engine/api/engineresponse_test.go
This PR completes engine api tests (100% coverage).
> refactor: complete engine api tests

- pkg/engine/jsonContext.go
> chore: clean up the unnecessary package import rename

- cmd/cli/kubectl-kyverno/apply/report.go
- cmd/cli/kubectl-kyverno/main.go
- pkg/background/common/resource.go
> chore: clean up the unnecessary package import rename found

- docs/dev/api/README.md
- docs/dev/troubleshooting/reports.md
> optimize the document for readability

- api/kyverno/v1/image_verification_types.go
- cmd/cleanup-controller/handlers/cleanup/condition.go
- go.mod
- pkg/background/common/context.go
- pkg/background/update_request_controller.go
- pkg/cosign/cosign.go
- pkg/engine/apicall/apiCall.go
- pkg/engine/context/context.go
- pkg/engine/context/evaluate.go
- pkg/engine/forceMutate.go
- pkg/engine/imageVerify.go
- pkg/engine/imageVerifyMetadata.go
- pkg/engine/imageVerifyValidate.go
- pkg/engine/jsonContext.go
- pkg/engine/k8smanifest.go
- pkg/engine/mutate/patch/strategicPreprocessing.go
- pkg/engine/policyContext.go
- pkg/engine/utils.go
- pkg/engine/validation.go
- pkg/leaderelection/leaderelection.go
- pkg/openapi/manager.go
- pkg/policy/mutate/validate.go
- pkg/policy/policy_controller.go
- pkg/policy/validate.go
- pkg/tls/reader.go
- pkg/utils/image/infos.go
- pkg/utils/kube/secret.go
- pkg/utils/retry/retry.go
- pkg/webhooks/resource/mutation/mutation.go
- pkg/webhooks/utils/policy_context_builder.go
/kind cleanup
The functionality `that thegithub.com/pkg/errors` provides is already present in golang's builtin errors，and the github repo is now read-only.
So it is suggested to remove the dependency on 'github.com/pkg/errors', please review, thanks
> chore: remove dependency on github.com/pkg/errors

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.9.0

- pkg/engine/jmespath/functions.go
This PR fixes jp items function.
> fix: jp items function

- Makefile
This PR fixes our image tagging strategy.
Backport of #6195
> fix: image tagging strategy

- pkg/engine/jmespath/functions.go
- pkg/engine/jmespath/functions_test.go
- pkg/engine/jmespath/new.go
- pkg/engine/jmespath/new_test.go
This PR adds a couple unit tests to our jp functions.
> test: add a couple unit tests

- pkg/engine/api/imageverifymetadata.go
- pkg/engine/api/imageverifymetadata_test.go
This PR adds missing engine api unit tests.
> fix: add engine api unit tests

- pkg/background/common/resource.go
- pkg/webhooks/resource/utils.go
- test/conformance/kuttl/mutate/clusterpolicy/standard/existing/basic-delete/01-assert.yaml
- test/conformance/kuttl/mutate/clusterpolicy/standard/existing/basic-delete/01-manifests.yaml
- test/conformance/kuttl/mutate/clusterpolicy/standard/existing/basic-delete/02-delete-cm.yaml
- test/conformance/kuttl/mutate/clusterpolicy/standard/existing/basic-delete/03-assert.yaml
- test/conformance/kuttl/mutate/clusterpolicy/standard/existing/basic-delete/README.md
- test/conformance/kuttl/mutate/clusterpolicy/standard/existing/basic-delete/cleanup.yaml
> fix: admission review variables for DELETE operations (Cherry-pick #6197)

- Makefile
This PR fixes ko publish image targets.
> fix: ko publish image targets

- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/admission-controller/deployment.yaml
- charts/kyverno/values.yaml
Signed-off-by: André Bauer <andre.bauer@staffbase.com>
* make sigstore volume configurable
> [kyverno helm chart] make sigstore volume configurable

- CONTRIBUTING.md
- CONTRIBUTORS.md
Adds a new CONTRIBUTORS.md file and updates info in the contributing guide per latest community guidelines update.
* Adds CONTRIBUTORS.md
* Updates CONTRIBUTING.md
> Create CONTRIBUTORS.md and update info

- pkg/engine/policyContext.go
- pkg/webhooks/resource/validation/validation.go
- test/conformance/kuttl/reports/admission/namespaceselector/01-policy.yaml
- test/conformance/kuttl/reports/admission/namespaceselector/02-pod.yaml
- test/conformance/kuttl/reports/admission/namespaceselector/03-report.yaml
- test/conformance/kuttl/reports/admission/namespaceselector/README.md
- test/conformance/kuttl/reports/admission/namespaceselector/pods.yaml
- test/conformance/kuttl/reports/admission/namespaceselector/policy-assert.yaml
- test/conformance/kuttl/reports/admission/namespaceselector/policy.yaml
- test/conformance/kuttl/reports/admission/namespaceselector/report-expected.yaml
- test/conformance/kuttl/reports/admission/namespaceselector/report-unexpected.yaml
> fix: namespaceSelector for audit rules (Cherry-pick 6216)

- go.mod
- go.sum
- pkg/engine/jmespath/functions.go
- pkg/engine/jmespath/new.go
- pkg/engine/jmespath/time_test.go
- pkg/engine/jmespath/utils.go
This PR add more jp unit tests and check for out of bounds argument.
> fix: add more jp unit tests and check for out of bounds argument

- pkg/engine/jmespath/arithmetic.go
- pkg/engine/jmespath/error.go
- pkg/engine/jmespath/functions.go
- pkg/engine/jmespath/utils.go
This PR fixes a couple of jp functions not managing errors correctly.
> fix: error management in jp functions

- pkg/engine/validate/validate_test.go
- test/cli/test-mutate/foreach/addIfNotPresent/deploy-patched.yaml
- test/cli/test-mutate/foreach/addIfNotPresent/resources.yaml
- test/cli/test/foreach/resources.yaml
- test/cli/test/owner_references/resource.yaml
- test/output/pod-with-default-volume.yaml
- test/output/pod-with-emptydir.yaml
- test/output/pod-with-hostpath.yaml
- test/resources/pod-with-default-volume.yaml
- test/resources/pod-with-emptydir.yaml
- test/resources/pod-with-hostpath.yaml
- test/resources/resource_validate_healthChecks.yaml
https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/#tl-dr-what-you-need-to-know-about-this-change
/kind feature
PTAL @chipzoller @eddycharly @realshuting
> move from k8s.gcr.io to registry.k8s.io

- cmd/cleanup-controller/main.go
- cmd/internal/informer.go
- cmd/kyverno/main.go
This PR adds error logs in wait for cache sync helper.
> chore: add error logs in wait for cache sync helper

- pkg/background/common/labels.go
- pkg/background/generate/generate.go
- pkg/background/generate/labels.go
- pkg/background/update_request_controller.go
- pkg/policy/validate.go
- pkg/webhooks/resource/generation/generation.go
- pkg/webhooks/resource/generation/generation_test.go
- pkg/webhooks/resource/generation/utils.go
- pkg/webhooks/resource/handlers.go
- pkg/webhooks/utils/update_request_updater.go
- pkg/webhooks/utils/update_request_updater_test.go
Adds label keys for generate policies.
> chore: add label keys for generate policies

- api/kyverno/v1/resource_spec_types.go
- api/kyverno/v1beta1/updaterequest_types.go
- charts/kyverno/templates/crds/crds.yaml
- config/crds/kyverno.io_updaterequests.yaml
- docs/user/crd/index.html
- pkg/background/common/context.go
- pkg/background/common/resource.go
- pkg/background/generate/generate.go
- pkg/background/mutate/mutate.go
- pkg/background/update_request_controller.go
- pkg/client/listers/kyverno/v1beta1/updaterequest_expansion.go
- pkg/policy/policy_controller.go
- pkg/webhooks/resource/handlers.go
- pkg/webhooks/updaterequest/generator.go
This PR updates the UR spec, once accepted, I'll change the mapping strategy between the UR and the generate policy.
> feat: add new fields to UR for generate rule details

- pkg/engine/api/policyresponse.go
- pkg/engine/api/ruleresponse.go
- pkg/engine/api/ruleresponse_test.go
- pkg/engine/background.go
- pkg/engine/generation.go
- pkg/engine/imageVerify.go
- pkg/engine/internal/response.go
- pkg/engine/mutate/patch/patchJSON6902.go
- pkg/engine/mutate/patch/strategicMergePatch.go
- pkg/engine/mutation.go
- pkg/engine/validation.go
- pkg/metrics/policyexecutionduration/policyExecutionDuration.go
- pkg/webhooks/resource/validation_test.go
This PR makes engine stats standard fields.
> refactor: make engine stats standard fields

- pkg/engine/api/engineresponse.go
- pkg/engine/api/engineresponse_test.go
- pkg/engine/api/policyresponse.go
- pkg/engine/internal/response.go
- pkg/webhooks/utils/block_test.go
This PR removes validate failure action and overrides from response, we can take the info from the policy directly.
> refactor: remove validate failure actions from response

- cmd/kyverno/main.go
This PR uses apiserver instrumented client.
> fix: use apiserver instrumented client

- MAINTAINERS.md
This PR moves maintainers Vyankatesh and Prateek to emeritus status. Voting remains open for up to 7 days. Successful vote results in merging of this PR and removal from the organization.
* Introduce a Maintainers Emeritus table in `MAINTAINERS.md` and move Vyankatesh and Prateek.
* Updates governance link to point to prod site, not main.
> Move Vyankataesh and Prateek to emeritus status

- cmd/cleanup-controller/server.go
- cmd/kyverno/main.go
- pkg/webhooks/handlers/dump.go
- pkg/webhooks/handlers/dump_test.go
- pkg/webhooks/resource/fake.go
- pkg/webhooks/resource/handlers.go
- pkg/webhooks/server.go
This PR adds roles and clusterroles when dumping admission requests.
> fix: add roles and clusterroles when dumping admission requests

- cmd/cleanup-controller/server.go
- cmd/kyverno/main.go
- pkg/webhooks/handlers/dump.go
- pkg/webhooks/handlers/dump_test.go
- pkg/webhooks/resource/fake.go
- pkg/webhooks/resource/handlers.go
- pkg/webhooks/server.go
fix: add roles and clusterroles when dumping admission requests (cherry-pick #6319)
> fix: add roles and clusterroles when dumping admission requests (cherry-pick #6319)

- pkg/engine/validate/validate_test.go
This PR updates `k8s.gcr.io` to `registry.k8s.io`
Part of https://github.com/kubernetes/k8s.io/issues/4780
> Update k8s.gcr.io to registry.k8s.io

- pkg/webhooks/resource/validation/validation.go
This PR fixes missing metrics for policies in audit mode.
Fixes #6315
> fix: missing metrics for policies in audit mode

- test/conformance/kuttl/mutate/cascading/two-foreach-rules/01-policy.yaml
- test/conformance/kuttl/mutate/cascading/two-foreach-rules/02-configmap.yaml
- test/conformance/kuttl/mutate/cascading/two-foreach-rules/README.md
- test/conformance/kuttl/mutate/cascading/two-foreach-rules/configmap-assert.yaml
- test/conformance/kuttl/mutate/cascading/two-foreach-rules/configmap.yaml
- test/conformance/kuttl/mutate/cascading/two-foreach-rules/policy-assert.yaml
- test/conformance/kuttl/mutate/cascading/two-foreach-rules/policy.yaml
This PR adds a cascading kuttl test with two foreach rules
> chore: add cascading kuttl test

- pkg/engine/variables/vars.go
> fix: error log

- charts/kyverno/README.md
- charts/kyverno/README.md.gotmpl
- charts/kyverno/templates/NOTES.txt
- charts/kyverno/templates/admission-controller/deployment.yaml
- charts/kyverno/templates/admission-controller/poddisruptionbudget.yaml
- charts/kyverno/templates/validate.yaml
- charts/kyverno/values.yaml
This PR refactors helm admission controller replicas.
> refactor: helm admission controller replicas

- charts/kyverno/README.md
- charts/kyverno/README.md.gotmpl
- charts/kyverno/templates/admission-controller/deployment.yaml
- charts/kyverno/templates/admission-controller/poddisruptionbudget.yaml
- charts/kyverno/templates/cleanup-controller/deployment.yaml
- charts/kyverno/values.yaml
This PR refactors helm admission controller config:
- `updateStrategy`
- `priorityClassName`
- `hostNetwork`
- `dnsPolicy`
- `nodeSelector`
- `tolerations`
- `topologySpreadConstraints`
- `podDisruptionBudget`
> refactor: helm admission controller config

- pkg/event/events.go
>  fix: update resource info in polex events (Cherry-pick 6459)

- README.md
ArtifactHub Badge added
@JimBugwadia Need Reviews
#6479 
> /kind documentation
> ArtifactHub badge added

- README.md
> Add license scanning

- Makefile
This PR fixes release workflow.
> fix: release

- pkg/background/mutate/mutate.go
- pkg/clients/dclient/discovery.go
- pkg/clients/dclient/discovery_test.go
- pkg/clients/dclient/fake.go
- pkg/clients/dclient/utils.go
This PR fixes looking up GVK from GVR.
> fix: lookup GVK from GVR

- .github/workflows/verify-codegen.yaml
This PR uploads install manifest in gh action artifact.
Fixes #6427
> chore: upload install manifest

- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/01-clusterpolicy.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/02-ns.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/03-check.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/04-update-sync.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/05-delete-rule.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/06-sleep.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/07-checks.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/README.md
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/configmap.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/delete-rule.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/policy-ready.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/policy.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-sync-to-nosync-delete-rule/secret.yaml
This PR adds a kuttl test `cpol-data-sync-to-nosync-delete-rule` for the process to delete a policy/rule after changing synchronize to false (1. Create policy/rule; 2. Create trigger; 3. Verify resource is generated; 4. Change sync to false; 5. Delete policy/rule; 6. Verify generated resource is NOT deleted).
Item 5 in https://github.com/kyverno/kyverno/issues/6458.
/1.10.0
/test
> test: add a kuttl test for rule deletion

- cmd/internal/flag.go
- pkg/controllers/report/admission/controller.go
fix: improve reports controller default values and workers (cherry-pick #6522)
> fix: improve reports controller default values and workers (cherry-pick #6522)

- cmd/internal/flag.go
This PR increases burst to 300.
See:
- https://kubernetes.slack.com/archives/CLGR9BJU9/p1678371541095359
- https://kubernetes.slack.com/archives/C0EG7JC6T/p1678464196586169
> fix: increase burst

- pkg/webhooks/resource/validation/validation.go
fix: process audit policies when admission reports are disabled (cherry-pick #6531)
> fix: process audit policies when admission reports are disabled (cherry-pick #6531)

- charts/kyverno/templates/background-controller/servicemonitor.yaml
- scripts/config/dev/kyverno.yaml
- scripts/config/standard/kyverno.yaml
This PR adds missing service monitor for background controller.
> fix: add missing service monitor for background controller

- pkg/openapi/manager.go
- test/conformance/kuttl/validate/clusterpolicy/cornercases/schema-validation-for-mutateExisting/00-policy.yaml
- test/conformance/kuttl/validate/clusterpolicy/cornercases/schema-validation-for-mutateExisting/README.md
- test/conformance/kuttl/validate/clusterpolicy/cornercases/schema-validation-for-mutateExisting/policy-assert.yaml
- test/conformance/kuttl/validate/clusterpolicy/cornercases/schema-validation-for-mutateExisting/policy.yaml
> fix: schema validation for mutateExisting type of policy

- pkg/clients/dclient/discovery.go
- pkg/clients/dclient/fake.go
- pkg/controllers/webhook/controller.go
- pkg/engine/loadtargets.go
- pkg/policy/validate.go
- pkg/policycache/cache.go
- pkg/policycache/cache_test.go
- pkg/policycache/store.go
- pkg/policycache/test.go
This PR maps `APIResource` in `FindResources` results.
> fix: map APIResource in FindResources results

- charts/kyverno/README.md
- charts/kyverno/README.md.gotmpl
- charts/kyverno/templates/admission-controller/deployment.yaml
- charts/kyverno/values.yaml
- scripts/config/dev/kyverno.yaml
- scripts/config/standard/kyverno.yaml
This PR refactors the way we configure logging, tracing and metering in helm chart.
> refactoring: helm logging, tracing and metering config

- .github/actions/kyverno-logs/action.yaml
This PR adds reports controller debug logs in ci step.
> chore: add reports controller debug logs

- pkg/engine/validation.go
This PR fixes an incorrect old resource check.
> fix: incorrect old resource check

- .vscode/launch.json
This PR adds vscode config to debug background controller.
> chore: add vscode config to debug background controller

- pkg/auth/auth.go
- pkg/background/common/context.go
- pkg/engine/imageVerifyValidate.go
- pkg/engine/internal/imageverifier.go
- pkg/engine/internal/logging.go
- pkg/engine/internal/response.go
- pkg/engine/mutation.go
- pkg/engine/validation.go
- pkg/webhooks/resource/generation/handler.go
- pkg/webhooks/resource/imageverification/handler.go
- pkg/webhooks/resource/mutation/mutation.go
- pkg/webhooks/resource/validation/validation.go
This PR removes a couple `DeepEqual` and fixes deletion check bug.
> fix: remove a couple DeepEqual and fix deletion check bug

- pkg/engine/policyContext.go
This PR fixes GVK fallback in policy context.
Ideally we want to make it mandatory from the caller, I will improve this soon.
> fix: GVK fallback in policy context

- cmd/cli/kubectl-kyverno/utils/common/common.go
- cmd/cli/kubectl-kyverno/utils/common/fetch.go
This PR uses `FindResources` (instead of `FindResource`) in CLI.
> fix: use FindResources in CLI

- pkg/engine/jmespath/arithmetic.go
- pkg/engine/jmespath/functions.go
This PR reports the correct filter name in case of jp add/sum error.
> fix: filter name in add/sum error

- pkg/engine/background.go
- pkg/engine/engine.go
- pkg/engine/handlers/handler.go
- pkg/engine/handlers/manifest/k8smanifest.go
- pkg/engine/handlers/mutation/common.go
- pkg/engine/handlers/mutation/loadtargets.go
- pkg/engine/handlers/mutation/loadtargets_test.go
- pkg/engine/handlers/mutation/mutate.go
- pkg/engine/handlers/mutation/mutateexisting.go
- pkg/engine/mutation.go
- pkg/engine/policycontext/policyContext.go
- pkg/engine/utils/foreach.go
- pkg/engine/utils/match.go
- pkg/engine/utils/utils_test.go
- pkg/engine/validation.go
This PR implements mutation rule handlers.
This is a follow up of https://github.com/kyverno/kyverno/pull/6680
Next I will implement middlewares so that we can move the logic out of the rule handler itself:
- Rule matching
- Context loading
- Exception handling
> refactor: implement mutation rule handlers

- pkg/engine/background.go
- pkg/engine/engine.go
- pkg/engine/exceptions.go
- pkg/engine/handlers/handler.go
- pkg/engine/handlers/manifest/k8smanifest.go
- pkg/engine/handlers/mutation/mutate.go
- pkg/engine/handlers/mutation/mutateexisting.go
- pkg/engine/imageVerify.go
- pkg/engine/mutation.go
- pkg/engine/validation.go
This PR factorises rule handler invocation code:
- creates a trace
- matches resource against rules match/exclude statements
- checks exception
- loads context
This is simpler than a middleware system. We can always make it a middleware system later if needed.
> refactor: factorise rule handler invocation code

- cmd/cli/kubectl-kyverno/utils/common/common.go
- pkg/utils/api/image.go
This PR propagates the error when parsing an image fails.
Fixes #6587
> fix: propagate error when parsing an image fails

- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/_helpers/_pdb.tpl
- charts/kyverno/values.yaml
This PR allows overriding PDB api version.
Closes #6078
> fix: allow overriding PDB api version

- charts/kyverno/README.md
- charts/kyverno/templates/reports-controller/deployment.yaml
- charts/kyverno/values.yaml
This PR fixes a missing volume for sigstore in reports controller.
@realshuting background controller may be affected too.
> fix: missing volume for sigstore in reports controller

- api/kyverno/v1/resource_description_types.go
- api/kyverno/v2beta1/resource_description_types.go
- pkg/webhooks/resource/generation/handler.go
- pkg/webhooks/resource/generation/utils.go
- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-data-create-on-trigger-deletion/01-manifests.yaml
This is a follow-up PR of #6658 that refactors the generate logic for DELETE admission requests.
> refactor - fire generate upon trigger deletion

- pkg/engine/engine.go
- pkg/engine/handlers/handler.go
- pkg/engine/handlers/mutation/common.go
- pkg/engine/handlers/mutation/mutate_image.go
- pkg/engine/handlers/validation/validate_image.go
- pkg/engine/handlers/validation/validate_resource.go
- pkg/engine/imageVerify.go
- pkg/engine/internal/preconditions.go
- pkg/engine/mutation.go
- pkg/engine/validation.go
- pkg/engine/variables/vars.go
This PR introduces image mutation handler and makes use of `invokeHandler` helper.
> refactor: introduce image mutation handler

- Makefile
- api/kyverno/v1/common_types.go
- charts/kyverno/templates/crds/crds.yaml
- config/crds/kyverno.io_clusterpolicies.yaml
- config/crds/kyverno.io_policies.yaml
- config/install-latest-testing.yaml
- docs/crd/v1/index.html
- docs/user/crd/index.html
This PR bumps the allowed PSa to 1.26.
cc @YTGhost
> dep: bump allowed PSa to 1.26

- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/README.md.gotmpl
- charts/kyverno/templates/admission-controller/deployment.yaml
- charts/kyverno/templates/background-controller/deployment.yaml
- charts/kyverno/templates/cleanup-controller/deployment.yaml
- charts/kyverno/templates/hooks/pre-delete.yaml
- charts/kyverno/templates/reports-controller/deployment.yaml
- charts/kyverno/values.yaml
This PR fixes missing image pull secrets in helm hooks.
Fixes https://github.com/kyverno/kyverno/issues/6753
> fix: missing image pull secrets in helm hooks

- pkg/background/generate/generate.go
- pkg/background/mutate/mutate.go
- pkg/policy/validate.go
- test/conformance/kuttl/generate/e2e/generate-on-subresource-trigger/01-cluster-policy.yaml
- test/conformance/kuttl/generate/e2e/generate-on-subresource-trigger/02-script.yaml
- test/conformance/kuttl/generate/e2e/generate-on-subresource-trigger/03-assert.yaml
- test/conformance/kuttl/generate/e2e/generate-on-subresource-trigger/99-cleanup.yaml
- test/conformance/kuttl/generate/e2e/generate-on-subresource-trigger/README.md
- test/conformance/kuttl/generate/e2e/generate-on-subresource-trigger/namespace-ready.yaml
- test/conformance/kuttl/generate/e2e/generate-on-subresource-trigger/namespace.yaml
- test/conformance/kuttl/generate/e2e/generate-on-subresource-trigger/policy-ready.yaml
- test/conformance/kuttl/generate/e2e/generate-on-subresource-trigger/policy.yaml
Signed-off-by: Vyom-Yadav [jackhammervyom@gmail.com](mailto:jackhammervyom@gmail.com)
While processing the update request, it was checked whether the resource triggering the UR is existent or not. Many subresources are ephemeral and are deleted as soon as their work finishes.
Current logic still tries to get the resource because some subresources co-exist with the parent resource throughout the lifecycle of the parent resource (eg: status). In case it is not found, it resorts back to `request.object` or `request.oldObject`
Closes https://github.com/kyverno/kyverno/issues/6399
/milestone 1.10.0
/kind bug
>  fix: Support subresources as the trigger in generate rules

- MAINTAINERS.md
The maintainer off-boarding process was not properly followed previously. Hence, we discussed and with Sam's consent are reinstating him as a maintainer. 
See: https://github.com/kyverno/website/issues/810
> reinstate Sam as a maintainer

- cmd/cli/kubectl-kyverno/apply/report_test.go
- pkg/controllers/report/utils/events.go
- pkg/engine/api/policyresponse.go
- pkg/engine/image_verify.go
- pkg/engine/mutation.go
- pkg/engine/validation.go
- pkg/event/events.go
- pkg/webhooks/utils/event.go
This PR simplifies engine responses usage.
> refactor: simplify engine responses

- Makefile
- scripts/config/dev/policy-reporter.yaml
This PR adds policy reporter to the dev lab.
> feat: add policy reporter to the dev lab

- Makefile
- scripts/config/force-failure-policy-ignore/kyverno.yaml
This PR adds support multiple helm values through makefile targets.
> chore: support multiple helm values

- Makefile
- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release 1.10.0 alpha.1

- cmd/cleanup-controller/main.go
- cmd/kyverno/main.go
- pkg/config/config.go
- pkg/controllers/generic/webhook/controller.go
- pkg/controllers/webhook/controller.go
This PR improves config management:
- more detailed logs
- better error logs
- notifies clients when the configuration was reloaded
Fixes https://github.com/kyverno/kyverno/issues/6794
> fix: improve config management

- .github/actions/publish-image/action.yaml
- .github/workflows/cli.yaml
- .github/workflows/conformance.yaml
- .github/workflows/images-build.yaml
- .github/workflows/images-publish.yaml
- .github/workflows/release.yaml
- Makefile
This PR implements the expected tagging strategy.
See https://github.com/kyverno/kyverno/issues/6251
> chore: implement expected tagging strategy

- .github/actions/publish-image/action.yaml
- .github/workflows/cli.yaml
- .github/workflows/conformance.yaml
- .github/workflows/images-build.yaml
- .github/workflows/images-publish.yaml
- .github/workflows/release.yaml
- Makefile
chore: implement expected tagging strategy (cherry-pick #6820)
> chore: implement expected tagging strategy (cherry-pick #6820)

- .github/workflows/images-publish.yaml
- .github/workflows/release.yaml
This PR fixes slsa provenance generation.
> fix: slsa provenance generation

- .github/workflows/images-publish.yaml
This PR adds slsa provenance jobs to all images published.
> chore: add slsa provenance jobs to all images published

- .github/workflows/images-publish.yaml
- .github/workflows/release.yaml
This PR fixes slsa generator for reports controller.
> fix: slsa generator for reports controller

- Makefile
This PR fixes a small makefile bug where command was not trapped correctly.
> chore: fix makefile nits

- Makefile
This PR fix a small makefile mistake, hiding the command in `kind-install-kyverno` target.
> fix: makefile nit

- cmd/background-controller/main.go
- cmd/internal/config.go
- cmd/internal/engine.go
- cmd/internal/flag.go
- cmd/kyverno/main.go
- cmd/reports-controller/main.go
- pkg/background/update_request_controller.go
- pkg/controllers/report/background/controller.go
- pkg/policy/policy_controller.go
This PR factorises engine creation code in all our binaries:
- enable/disable config map caching
- policy exceptions arguments
> refactor: factorise engine creation

- scripts/config/dev/kyverno.yaml
- test/conformance/kuttl/force-failure-policy-ignore/cluster-policy/fail/policy-assert.yaml
- test/conformance/kuttl/force-failure-policy-ignore/cluster-policy/fail/policy.yaml
- test/conformance/kuttl/force-failure-policy-ignore/cluster-policy/fail/webhooks-assert.yaml
This PR fixes kuttl tests for `force-failure-policy-ignore` config.
> fix: kuttl tests for force-failure-policy-ignore config

- pkg/engine/internal/imageverifier.go
This PR accounts for cosign default repository.
> fix: account for cosign default repository

- cmd/background-controller/main.go
- cmd/cleanup-controller/main.go
- cmd/internal/config.go
- cmd/internal/flag.go
- cmd/internal/registry.go
- cmd/internal/setup.go
- cmd/kyverno-init/main.go
- cmd/kyverno/main.go
- cmd/reports-controller/main.go
This PR moves registry client initialisation code in internal package.
> refactor: move registry client init in internal package

- charts/kyverno/templates/background-controller/deployment.yaml
- charts/kyverno/templates/reports-controller/deployment.yaml
This PR adds missing image pull secrets in new components.
> fix: add missing image pull secrets

- cmd/cli/kubectl-kyverno/test/filter.go
- cmd/cli/kubectl-kyverno/test/help.go
- cmd/cli/kubectl-kyverno/test/test_command.go
This PR refactors cli test filter.
> refactor: cli test filter

- pkg/engine/api/engineresponse.go
- pkg/engine/api/policyresponse.go
- pkg/engine/api/stats.go
- pkg/engine/image_verify.go
- pkg/engine/mutation.go
- pkg/engine/validation.go
- pkg/webhooks/resource/validation_test.go
This PR refactors policy response:
- makes some fields private
- provides some accessors
> refactor: policy response

- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
chore: split unit tests and linter jobs (cherry-pick #6901)
> chore: split unit tests and linter jobs (cherry-pick #6901)

- test/conformance/kuttl/validate/clusterpolicy/standard/exclude/exclude-namespace/01-policies.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/exclude/exclude-namespace/02-resources.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/exclude/exclude-namespace/README.md
- test/conformance/kuttl/validate/clusterpolicy/standard/exclude/exclude-namespace/policies-assert.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/exclude/exclude-namespace/policies.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/exclude/exclude-namespace/resources.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/wildcard/block-verifyimage/README.md
This PR adds a kuttl test for namespace exclusion.
> chore: add kuttl test for namespace exclusion

- test/conformance/kuttl/generate/clusterpolicy/cornercases/cpol-clone-create-on-trigger-deletion/01-manifests.yaml
Fix the kuttl test `cpol-clone-create-on-trigger-deletion`. The source name was wrong before.
> fix: kuttl test for the generate rule

- cmd/background-controller/main.go
The background controller does not process anything related to the image verify rule, this PR removes the ` imageSignatureRepository` flag from those controller.
https://github.com/kyverno/kyverno/issues/6836
/1.10.0
/bug
> fix: remove imageSignatureRepository flag from the background controller

- pkg/engine/apicall/apiCall.go
This PR enables tracing in api call.
> fix: enable tracing in api call

- cmd/background-controller/main.go
- cmd/cleanup-controller/main.go
- cmd/internal/client.go
- cmd/internal/config.go
- cmd/internal/setup.go
- cmd/kyverno-init/main.go
- cmd/kyverno/main.go
- cmd/reports-controller/main.go
- pkg/metrics/common_types.go
This PR moves clients creation in internal package.
> refactor: move clients creation in internal package

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> Release v1.10.0-alpha2

- pkg/utils/match/kind.go
This PR fixes a bug when matching ephemeral containers.
Fixes https://github.com/kyverno/kyverno/issues/6943
> fix: match on ephemeral containers

- charts/kyverno/templates/admission-controller/clusterrole.yaml
- charts/kyverno/templates/background-controller/clusterrole.yaml
- charts/kyverno/templates/cleanup-controller/clusterrole.yaml
- charts/kyverno/templates/reports-controller/clusterrole.yaml
- config/install-latest-testing.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/generate-event-upon-edit/01-clusterrole.yaml
This PR removes `delete` operation from the default permissions, and adds the group `event.k8s.io/v1` to the group.
https://github.com/kyverno/kyverno/issues/6947
/1.10.0
/bug
> fix: refine event permissions in default roles

- pkg/policy/validate.go
- pkg/policy/validate_test.go
- pkg/utils/yaml/loadpolicy.go
- test/conformance/kuttl/policy-validation/cluster-policy/background-variables-update/01-policy.yaml
- test/conformance/kuttl/policy-validation/cluster-policy/background-variables-update/02-policy.yaml
- test/conformance/kuttl/policy-validation/cluster-policy/background-variables-update/README.md
- test/conformance/kuttl/policy-validation/cluster-policy/background-variables-update/policy-assert.yaml
- test/conformance/kuttl/policy-validation/cluster-policy/background-variables-update/policy-update.yaml
- test/conformance/kuttl/policy-validation/cluster-policy/background-variables-update/policy.yaml
fix background variables validation (cherry-pick #6978)
> fix background variables validation (cherry-pick #6978)

- cmd/internal/flag.go
- cmd/internal/registry.go
- pkg/registryclient/client.go
feat: add credential helpers flags (cherry-pick #6974)
> feat: add credential helpers flags (cherry-pick #6974)

- .github/workflows/conformance.yaml
chore: bump kind image to 1.27.1 (cherry-pick #6993)
> chore: bump kind image to 1.27.1 (cherry-pick #6993)

- charts/kyverno/templates/admission-controller/clusterrole.yaml
- charts/kyverno/templates/admission-controller/deployment.yaml
- charts/kyverno/templates/background-controller/clusterrolebinding.yaml
- charts/kyverno/templates/cleanup-controller/clusterrole.yaml
- charts/kyverno/templates/cleanup-controller/deployment.yaml
- cmd/cli/kubectl-kyverno/apply/apply_command.go
- cmd/cli/kubectl-kyverno/oci/oci_push.go
- cmd/cli/kubectl-kyverno/test/test_command.go
- cmd/kyverno/main.go
- config/install-latest-testing.yaml
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/config/config.go
- pkg/engine/handlers/validation/validate_manifest.go
- pkg/policy/actions.go
- pkg/policy/generate/auth.go
- pkg/policy/generate/validate.go
- pkg/policy/mutate/auth.go
- pkg/policy/mutate/validate.go
- pkg/policy/validate.go
- pkg/policy/validate_test.go
- pkg/validation/cleanuppolicy/validate.go
- pkg/webhooks/policy/handlers.go
feat: new access checks for background policies (cherry-pick #6970)
> feat: new access checks for background policies (cherry-pick #6970)

- pkg/controllers/generic/configmap/controller.go
This PR record configmap resource version to not reload when version didn't change.
This prevents reloading when the configmap is resynced or after warmup (first reconcile).
> fix: record configmap resource version to not reload when version didn't change

- ADOPTERS.md
Red Hat ACM is useful for distributed kyverno policies across a managed fleet of clusters.  Adding to adopters file with a link that describes details of using the ACM policy generator with Kyverno.
> Add Red Hat ACM to the Adopters list

- charts/kyverno/templates/config/metricsconfigmap.yaml
This PR fixes an invalid helm template with metricsRefreshInterval.
> fix: helm template with metricsRefreshInterval

- ADOPTERS.md
Adds Saxo Bank and Velux as adopters via Google Form application
> add Saxo Bank and Velux as adopters

- DEVELOPMENT.md
As a result of [this PR](https://github.com/kyverno/kyverno/pull/6970), we need to pass `backgroundServiceAccountName` when running kyverno locally so that kyverno policies containing generate/mutate-existing rules can be created. 
Otherwise, when trying to run kyverno as follows:
```
go run ./cmd/kyverno/ --kubeconfig ~/.kube/config --serverIP=172.18.0.1:9443 
```
and then applying a policy that contains a generate rule as follows:
```
metadata:
name: generate-configmap
spec:
generateExisting: false
rules:
- name: zk-kafka-address
match:
any:
- resources:
kinds:
- Namespace
selector:
matchLabels:
trigger-generate: "true"
generate:
synchronize: true
apiVersion: v1
name: zk-kafka-address
namespace: "staging"
data:
kind: …
```
> update development doc

- go.mod
- pkg/utils/json/patch.go
- pkg/utils/json/utils_test.go
chore: use github.com/evanphx/json-patch/v5 (cherry-pick #7015)
> chore: use github.com/evanphx/json-patch/v5 (cherry-pick #7015)

- cmd/cli/kubectl-kyverno/apply/report_test.go
- cmd/cli/kubectl-kyverno/test/test_command.go
- cmd/cli/kubectl-kyverno/utils/common/common.go
- pkg/background/generate/generate.go
- pkg/controllers/report/utils/events.go
- pkg/engine/api/engineresponse.go
- pkg/engine/api/engineresponse_test.go
- pkg/engine/metrics.go
- pkg/event/events.go
- pkg/utils/annotations.go
- pkg/utils/report/results.go
- pkg/webhooks/resource/utils.go
- pkg/webhooks/utils/block.go
- pkg/webhooks/utils/error.go
- pkg/webhooks/utils/warning.go
- pkg/webhooks/utils/warning_test.go
refactor: engine response policy (cherry-pick #7063)
> refactor: engine response policy (cherry-pick #7063)

- pkg/policy/generate/validate.go
- pkg/policy/generate/validate_test.go
- test/conformance/kuttl/generate/clusterpolicy/cornercases/clone-role-and-rolebinding/01-manifests.yaml
- test/conformance/kuttl/generate/clusterpolicy/cornercases/data-role-and-rolebinding/01-manifests.yaml
This PR makes `generate.apiVersion` mandatory.
Closes https://github.com/kyverno/kyverno/issues/7048.
/1.10.0
/enhancement
> feat: require `generate.apiVersion`

- cmd/cleanup-controller/handlers/cleanup/handlers.go
- pkg/engine/exceptions.go
- pkg/utils/match/match.go
This PR removes excluded groups from matching.
> fix: remove excluded groups from matching

- charts/kyverno/README.md
- charts/kyverno/values.yaml
- config/install-latest-testing.yaml
- pkg/config/config.go
- pkg/config/types.go
- pkg/config/types_test.go
- pkg/webhooks/handlers/filter.go
This PR adds config inclusions support.
> feat: add config inclusions support

- Makefile
- scripts/config/kwok/kustomization.yaml
This PR adds a makefile target to deploy kwok.
> chore: add makefile target for kwok

- api/kyverno/v1/common_types.go
- api/kyverno/v1/rule_test.go
- api/kyverno/v1/rule_types.go
- api/kyverno/v2beta1/rule_test.go
- api/kyverno/v2beta1/rule_types.go
- pkg/validation/policy/validate.go
- test/conformance/kuttl/generate/validation/clusterpolicy/target-namespace-scope/01-fail.yaml
- test/conformance/kuttl/generate/validation/clusterpolicy/target-namespace-scope/README.md
- test/conformance/kuttl/generate/validation/clusterpolicy/target-namespace-scope/policy-cluster-target.yaml
- test/conformance/kuttl/generate/validation/clusterpolicy/target-namespace-scope/policy-namespaced-target.yaml
- test/conformance/kuttl/generate/validation/policy/target-namespace-scope/01-fail.yaml
- test/conformance/kuttl/generate/validation/policy/target-namespace-scope/README.md
- test/conformance/kuttl/generate/validation/policy/target-namespace-scope/policy-namespaced-target.yaml
This PR checks that the target namespace must be set for namespace-scoped target resources, and must not be set for cluster-wide target resources.
Closes https://github.com/kyverno/kyverno/issues/7038.
/1.10.0
/enhancement
> feat: generate policy validation - target resource scope & namespace settings

- CHANGELOG.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/configmap.yaml
- charts/kyverno/values.yaml
- cmd/cleanup-controller/main.go
- cmd/kyverno/main.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/controllers/generic/webhook/controller.go
- pkg/controllers/webhook/controller.go
- pkg/controllers/webhook/utils.go
> feat: add webhook annotations support in config map (cherry-pick #6579)

- docs/dev/controllers/README.md
Adds controller internals for Kyverno 1.10.
1.10
* Adds controller internals info based on 1.10
> add Controller Internals info

- charts/kyverno/README.md
- charts/kyverno/templates/_helpers.tpl
- charts/kyverno/templates/admission-controller/deployment.yaml
- charts/kyverno/templates/background-controller/deployment.yaml
- charts/kyverno/templates/cleanup-controller/deployment.yaml
- charts/kyverno/templates/reports-controller/deployment.yaml
- charts/kyverno/values.yaml
- config/install-latest-testing.yaml
This PR adds logging feature to helm chart.
> feat: add logging feature to helm chart

- cmd/cleanup-controller/handlers/cleanup/handlers.go
- pkg/engine/context/context.go
- pkg/engine/handlers/mutation/mutate_existing.go
- pkg/engine/mutate/mutation.go
- test/conformance/kuttl/mutate/existing/preconditions/01-resources.yaml
- test/conformance/kuttl/mutate/existing/preconditions/02-policy.yaml
- test/conformance/kuttl/mutate/existing/preconditions/03-resources-assert.yaml
- test/conformance/kuttl/mutate/existing/preconditions/04-resources-error.yaml
- test/conformance/kuttl/mutate/existing/preconditions/README.md
- test/conformance/kuttl/mutate/existing/preconditions/policy-ready.yaml
- test/conformance/kuttl/mutate/existing/preconditions/policy.yaml
- test/conformance/kuttl/mutate/existing/preconditions/resources-assert.yaml
- test/conformance/kuttl/mutate/existing/preconditions/resources-error.yaml
- test/conformance/kuttl/mutate/existing/preconditions/resources.yaml
This PR fixes preconditions in mutate existing rules.
Fixes https://github.com/kyverno/kyverno/issues/7174
> fix: preconditions in mutate existing rules

- pkg/webhooks/handlers/admission.go
- pkg/webhooks/handlers/metrics.go
This PR fixes http request metrics:
- wrong name
- not registered
> fix: http request metrics

- cmd/cleanup-controller/handlers/cleanup/handlers.go
- pkg/engine/context/context.go
- pkg/engine/handlers/mutation/mutate_existing.go
- pkg/engine/mutate/mutation.go
- test/conformance/kuttl/mutate/existing/preconditions/01-resources.yaml
- test/conformance/kuttl/mutate/existing/preconditions/02-policy.yaml
- test/conformance/kuttl/mutate/existing/preconditions/03-resources-assert.yaml
- test/conformance/kuttl/mutate/existing/preconditions/04-resources-error.yaml
- test/conformance/kuttl/mutate/existing/preconditions/README.md
- test/conformance/kuttl/mutate/existing/preconditions/policy-ready.yaml
- test/conformance/kuttl/mutate/existing/preconditions/policy.yaml
- test/conformance/kuttl/mutate/existing/preconditions/resources-assert.yaml
- test/conformance/kuttl/mutate/existing/preconditions/resources-error.yaml
- test/conformance/kuttl/mutate/existing/preconditions/resources.yaml
fix: preconditions in mutate existing rules (cherry-pick #7183)
> fix: preconditions in mutate existing rules (cherry-pick #7183)

- pkg/engine/variables/evaluate.go
- pkg/engine/variables/evaluate_test.go
Append `deny.conditions.any|all.message` to result message
Fixes https://github.com/kyverno/kyverno/issues/3716
1.10.0
/kind feature
Handle messages from conditions that evaluate to true, in addition to false
- See test case
Policy:
```yaml
metadata:
name: message-name
spec:
rules:
- name: message-rule
match:
any:
- resources:
kinds:
- ConfigMap
validate:
message: main message is here
deny:
conditions:
any:
- key: "{{ request.object.data.food }}"
value: cheese
message: my favorite food is cheese
- key: "{{ request.object.data.day }}"
value: monday
message: you have a case of the Mondays
```
Resource:
```yaml
apiVersion: v1
metadata:
name: mymap …
```
> handle Deny rules where conditions eval to true

- pkg/webhooks/handlers/admission.go
- pkg/webhooks/handlers/metrics.go
fix: http request metrics (cherry-pick #7197)
> fix: http request metrics (cherry-pick #7197)

- pkg/controllers/report/admission/controller.go
This PR fixes a panic in reports controller.
> fix: panic in reports controller

- go.mod
- go.sum
https://deps.dev/go/github.com%2Fkyverno%2Fkyverno/v1.10.0-beta.1
Cherry-pick [bump github.com/cloudflare/circl from 1.3.2 to 1.3.3](https://github.com/kyverno/kyverno/pull/7172#top).
> chore(deps): bump github.com/cloudflare/circl from 1.3.2 to 1.3.3 

- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> release: v1.10.0-rc.1

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
This PR fixes policies chart version.
> fix: policies chart

- pkg/utils/yaml/utils.go
This PR adds a yaml util to check empty document.
> feat: add yaml util to check empty document

- .github/ISSUE_TEMPLATE/bug-cli.yaml
- .github/ISSUE_TEMPLATE/bug-other.yaml
- .github/ISSUE_TEMPLATE/bug-webhook.yaml
Updates version numbers in issue template drop-down menus.
> Update version numbers in issue template drop-down menus

- charts/kyverno/templates/_helpers/_labels.tpl
Currently, the (unreleased) 3.0.0 helm chart is using a non-standard value of `app.kubernetes.io/instance`, which causes problems with Argo CD.
In [chart versions 2.X.X we used `{{ .Release.Name }}`](https://github.com/kyverno/kyverno/blob/release-1.9/charts/kyverno/templates/_helpers.tpl#L101), so this is effectively a revert of that change.
Closes #7245
@eddycharly
/milestone 1.10.0
/kind bug
Reverts the  `app.kubernetes.io/instance`  chart label to the more standard value of `{{ .Release.Name }}`, rather than the `"kyverno.name"` template.
> fix: chart `app.kubernetes.io/instance` label value

- api/kyverno/v1/image_verification_types.go
- api/kyverno/v2beta1/image_verification_types.go
- charts/kyverno/templates/crds/crds.yaml
- config/crds/kyverno.io_clusterpolicies.yaml
- config/crds/kyverno.io_policies.yaml
- config/install-latest-testing.yaml
- docs/user/crd/index.html
- pkg/engine/internal/imageverifier.go
- pkg/notary/notary.go
- pkg/notary/registry.go
- pkg/notary/truststore.go
Rename NotaryV2 to Notary
/milestone 1.10
/kind cleanup
> rename NotaryV2 to Notary

- charts/kyverno/README.md
- charts/kyverno/templates/admission-controller/deployment.yaml
- charts/kyverno/templates/background-controller/deployment.yaml
- charts/kyverno/templates/cleanup-controller/deployment.yaml
- charts/kyverno/templates/reports-controller/deployment.yaml
- charts/kyverno/values.yaml
Missing the ability to add datadog annotations to background clean and reports controllers
https://kyverno.io/docs/monitoring/#disabling-metrics
Closes #7313
Add podLabels and podAnnotations to background clean and reports controllers
> feat: [Feature] add podLabels and podAnnotations to background clean and reports controllers

- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/auth/checker/auth.go
- pkg/auth/checker/helpers.go
- pkg/auth/checker/self.go
- pkg/auth/checker/subject.go
This PR adds auth checker interface (from https://github.com/kyverno/playground/pull/325)
> feat: add auth checker interface

- pkg/controllers/report/background/controller.go
- pkg/controllers/report/utils/scanner.go
This PR fixes a panic in background reports.
Fixes https://github.com/kyverno/kyverno/issues/7330
> fix: panic in background reports

- .github/ISSUE_TEMPLATE/bug-cli.yaml
- .github/ISSUE_TEMPLATE/bug-other.yaml
- .github/ISSUE_TEMPLATE/bug-webhook.yaml
Updates version drop-downs in issue templates
> Update version drop-downs

- pkg/engine/handlers/mutation/mutate_image.go
This PR mutates resource in image verification handler.
> fix: mutate resource in image verification handler

- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
new helm chart version `v3.0.1`
> chore: new helm chart version

- charts/kyverno/README.md
- charts/kyverno/templates/cleanup/cleanup-admission-reports.yaml
- charts/kyverno/templates/cleanup/cleanup-cluster-admission-reports.yaml
- charts/kyverno/values.yaml
This PR adds the ability to configure tolerations for the admission cleanup jobs.
Closes #7328
I have added config sections for both the `admissionReports` and `clusterAdmissionReports` as well as the required template sections to enable tolerations for cleanup jobs
> feat: cleanup job tolerations

- charts/kyverno/README.md
- charts/kyverno/README.md.gotmpl
Fixes an issue in the Helm migration guide
> fix: helm migration guide

- CONTRIBUTORS.md
Added myself to CONTRIBUTORS.md
1. https://github.com/kyverno/kyverno/pull/7010
2. https://github.com/kyverno/kyverno/pull/6744
3. https://github.com/kyverno/kyverno/pull/5964
4. https://github.com/kyverno/kyverno/pull/5928
5. https://github.com/kyverno/kyverno/pull/6133
> Added Vishal Choudhary to CONTRIBUTORS.md

- pkg/webhooks/handlers/protect.go
This PR fixes protect managed resource not considering other components.
Fixes #7358
> fix: protect managed resource not considering other components

- pkg/policy/mutate/validate.go
This PR fixes permission validation message.
Fixes https://github.com/kyverno/kyverno/issues/7359
> fix: permission validation message

- charts/kyverno/templates/admission-controller/deployment.yaml
- config/install-latest-testing.yaml
- pkg/config/config.go
- pkg/utils/os/env.go
This PR will make kyverno panic if an env variable is missing.
> fix: missing/incorrect env variables

- ADOPTERS.md
Adds HCS Company as Kyverno adopters from the Google Form
> add HCS company as adopters from Google Form

- go.mod
- go.sum
- pkg/engine/mutate/patch/patchesUtils.go
- pkg/engine/mutate/patch/patchesUtils_test.go
This PR replaces `mattbaird/jsonpatch` with `appscode/jsonpatch`.
Unfortunately `mattbaird/jsonpatch` has issues and seems not really maintained.
> fix: replace mattbaird/jsonpatch with appscode/jsonpatch

- charts/kyverno/README.md
- charts/kyverno/README.md.gotmpl
Updates the Helm migration guide with important notes and guidance for users of generate rules.
#7170 
1.10.0
/kind docs
* Updates the Helm migration guide with important notes and guidance for users of generate rules.
> update migration guide with generate guidance

- pkg/utils/api/image.go
Expose `images.jsonPointer` for extension services. 
This will allow sending the extension a list of images, and having the extension return image JSON Pointer paths for mutate patches.
> expose JSON Pointer in Images variable for extension services

- pkg/engine/mutate/patch/patchesUtils.go
- pkg/engine/mutate/patch/patchesUtils_test.go
This PR fixes json patch unit tests.
> fix: json patch unit tests

- charts/kyverno-policies/README.md
- charts/kyverno-policies/values.yaml
`audit` is deprecated, so the default value in helm chart should change to `Audit`
> charts: changes validationFailureAction default value

- pkg/controllers/report/aggregate/controller.go
- pkg/utils/report/labels.go
If you add a custom label to (Cluster)PolicyReport the reconcileReport method invokes and cleanup all labels to only add the kyverno labels again. This removes the custom label and leads to a diff between the current and updates report. So the updated report without the custom label is persisted.
This change preserves custom labels and (re)adds only `kyverno.io` labels, so no change is detected and the report is not updated.
#5542
With this change it is possible to add additional labels to the report, allowing to group them or add information in a customizable way.
> feat: hold custom labels

- pkg/clients/dclient/discovery.go
This PR fixes a reports discovery error.
Fixes https://github.com/kyverno/kyverno/issues/7350
> fix: reports discovery error

- cmd/kyverno/main.go
- pkg/utils/kube/crd.go
This PR fixes the error reported when sanity check fails.
Fixes https://github.com/kyverno/kyverno/issues/7354
> fix: error reported when sanity check fails

- pkg/engine/mutate/patch/buffer.go
- pkg/engine/mutate/patch/buffer_test.go
This PR adds buffer unit tests.
> chore: add buffer unit tests

- pkg/autogen/rule.go
- test/conformance/kuttl/autogen/deployment-cronjob/01-policy.yaml
- test/conformance/kuttl/autogen/deployment-cronjob/README.md
- test/conformance/kuttl/autogen/deployment-cronjob/policy-assert.yaml
- test/conformance/kuttl/autogen/deployment-cronjob/policy.yaml
- test/conformance/kuttl/autogen/deployment-statefulset-job/policy-assert.yaml
- test/conformance/kuttl/autogen/deployment-statefulset-job/policy.yaml
- test/conformance/kuttl/autogen/none/policy-assert.yaml
- test/conformance/kuttl/autogen/none/policy.yaml
- test/conformance/kuttl/autogen/only-cronjob/policy-assert.yaml
- test/conformance/kuttl/autogen/only-cronjob/policy.yaml
- test/conformance/kuttl/autogen/only-deployment/policy-assert.yaml
- test/conformance/kuttl/autogen/only-deployment/policy.yaml
- test/conformance/kuttl/autogen/should-autogen/policy-assert.yaml
- test/conformance/kuttl/autogen/should-autogen/policy.yaml
- test/conformance/kuttl/autogen/should-not-autogen/policy-assert.yaml
- test/conformance/kuttl/autogen/should-not-autogen/policy.yaml
This PR fixes an autogen issue not generating the correct kind.
Fixes https://github.com/kyverno/kyverno/issues/7444
> fix: autogen not generating the correct kind

- charts/kyverno/templates/admission-controller/deployment.yaml
This PR fixes image pull secrets in admission controller.
Fixes https://github.com/kyverno/kyverno/issues/7472
> fix: image pull secrets in admission controller

- .github/workflows/release.yaml
- .goreleaser.yml
This PR signs released artifacts.
> feat: sign released artifacts

- pkg/clients/dclient/helpers.go
- pkg/engine/adapters/dclient.go
- pkg/engine/api/client.go
- pkg/engine/handlers/mutation/load_targets.go
- pkg/engine/handlers/mutation/mutate_existing.go
This PR propagate context when listing resources.
> fix: propagate context when listing resources

- api/kyverno/v1/spec_types.go
- cmd/kyverno/main.go
- pkg/controllers/webhook/controller.go
- pkg/toggle/context.go
- pkg/toggle/toggle.go
- pkg/toggle/toggle_test.go
- pkg/webhooks/resource/handlers.go
- pkg/webhooks/resource/imageverification/handler.go
- pkg/webhooks/resource/validation/validation.go
- pkg/webhooks/server.go
This PR uses context for toggles management.
> feat: use context for toggles management

- pkg/engine/context/evaluate.go
This PR fixes recursive lazy loading.
> fix: recursive lazy loading

- pkg/engine/handlers/mutation/common.go
- pkg/engine/mutation_test.go
feat: obey the order field in patchStrategicMerge method (cherry-pick #7336)
> feat: obey the order field in patchStrategicMerge method (cherry-pick #7336)

- pkg/engine/context/evaluate.go
fix: recursive lazy loading (cherry-pick #7552)
> fix: recursive lazy loading (cherry-pick #7552)

- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/cleanup/cleanup-admission-reports.yaml
- charts/kyverno/templates/cleanup/cleanup-cluster-admission-reports.yaml
- charts/kyverno/values.yaml
feat: cleanup jobs resources (cherry-pick #7337)
> feat: cleanup jobs resources (cherry-pick #7337)

- .github/workflows/release.yaml
- .goreleaser.yml
feat: sign released artifacts (cherry-pick #7478)
> feat: sign released artifacts (cherry-pick #7478)

- docs/dev/reports/README.md
Added fixes to typos found in `docs/dev/reports/README.md`.
Fix typos in  `docs/dev/reports/README.md`.
> fix: update typos in docs/dev/reports/README.md

- .github/workflows/scorecard.yaml
This PR tries to fix the scorecard workflow.
> fix: scorecard workflow

- .github/workflows/cli.yaml
- Makefile
fix: CLI tests (cherry-pick #7596)
> fix: CLI tests (cherry-pick #7596)

- test/conformance/kuttl/generate/clusterpolicy/cornercases/pod-restart-on-cm-update/05-sleep.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/nosync/cpol-clone-nosync-delete-source/04-forcesleep.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/nosync/cpol-clone-nosync-modify-downstream/04-forcesleep.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/nosync/cpol-clone-nosync-modify-source/04-forcesleep.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-sync-delete-policy/00-sleep.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-sync-delete-policy/05-sleep.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-sync-delete-rule/00-sleep.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-sync-modify-downstream/00-sleep.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/existing/existing-basic-add-rule-data/03-sleep.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/existing/existing-basic-add-rule-data/06-sleep.yaml
- test/conformance/kuttl/generate/clusterpolicy/standard/existing/existing-basic-create-policy-data/03-sleep.yaml
- test/conformance/kuttl/generate/policy/standard/clone/nosync/pol-clone-nosync-delete-downstream/05-sleep.yaml
- test/conformance/kuttl/generate/policy/standard/clone/nosync/pol-clone-nosync-delete-policy/04-sleep.yaml
- test/conformance/kuttl/generate/policy/standard/clone/nosync/pol-clone-nosync-delete-rule/04-sleep.yaml
- test/conformance/kuttl/generate/policy/standard/clone/nosync/pol-clone-nosync-delete-source/04-sleep.yaml
- test/conformance/kuttl/generate/policy/standard/clone/nosync/pol-clone-nosync-modify-downstream/04-sleep.yaml
- test/conformance/kuttl/generate/policy/standard/clone/nosync/pol-clone-nosync-modify-source/04-sleep.yaml
- test/conformance/kuttl/generate/policy/standard/clone/sync/pol-clone-sync-delete-policy/05-sleep.yaml
- test/conformance/kuttl/generate/policy/standard/clone/sync/pol-clone-sync-delete-rule/04-sleep.yaml
- test/conformance/kuttl/generate/policy/standard/clone/sync/pol-clone-sync-delete-source/04-sleep.yaml
- test/conformance/kuttl/generate/policy/standard/data/sync/pol-data-sync-delete-trigger/03-sleep.yaml
> chore: reduce sleep duration for generate kuttl tests (cherry-pick #7589)

- .github/workflows/report-on-vulnerabilities.yaml
This PR fixes token permissions on report vulns workflow.
> fix: token permissions on report vulns workflow

- .github/workflows/check-actions.yaml
This PR fixes some token permissions.
> fix: token permissions

- cmd/reports-controller/main.go
Fixed a few typos in the flag descriptions of `cmd/reports-controller`.
/kind bug
Fix typos in the flag descriptions of  `cmd/reports-controller`.
> fix: update the flag descriptions of the reports-controller

- charts/kyverno/templates/admission-controller/deployment.yaml
- charts/kyverno/templates/background-controller/deployment.yaml
- charts/kyverno/templates/cleanup-controller/deployment.yaml
- charts/kyverno/templates/reports-controller/deployment.yaml
- cmd/internal/check.go
- cmd/internal/setup.go
- config/install-latest-testing.yaml
This PR panics if env var is not defined.
> fix: panic if env var not defined

- pkg/engine/variables/vars.go
This PR reduces number of queries to detect delete operations.
> fix: reduce number of queries to detect delete operations

- charts/kyverno/templates/cleanup-controller/clusterrole.yaml
- charts/kyverno/templates/cleanup-controller/role.yaml
- config/install-latest-testing.yaml
This PR hardens cleanup controller rbac.
> fix: harden cleanup controller rbac

- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/templates/admission-controller/role.yaml
- charts/kyverno/templates/hooks/pre-delete.yaml
- charts/kyverno/values.yaml
- config/install-latest-testing.yaml
This PR enables the Helm pre-delete hook by default to cleanup Kyverno webhook configurations automatically upon uninstallation.
Closes https://github.com/kyverno/kyverno/issues/7576.
/1.10.1
/enhancement
> feat: enable Helm webhook cleanup hook by default

- pkg/utils/controller/utils.go
- pkg/webhooks/server.go
This PR cleans up controllerutils client interfaces.
> fix: cleanup controllerutils client interfaces

- pkg/engine/api/context.go
- pkg/engine/api/contextloader.go
- pkg/engine/api/resolver_test.go
- pkg/engine/apicall/apiCall.go
- pkg/engine/apicall/apiCall_test.go
- pkg/engine/context/loader.go
- pkg/engine/context/loaders/apicall.go
- pkg/engine/context/loaders/configmap.go
- pkg/engine/context/loaders/imagedata.go
- pkg/engine/context/loaders/variable.go
This PR adds specific loaders from #7597.
This will make the changes in #7597 easier to review if we split the PR, this part is clearly something we want in.
> refactor: add specific loaders from #7597

- charts/kyverno/templates/cleanup-controller/clusterrole.yaml
- cmd/cleanup-controller/handlers/cleanup/handlers.go
- cmd/cleanup-controller/main.go
- config/install-latest-testing.yaml
This PR adds cleanup controller context changes from #7597.
> fix: cleanup controller context from #7597

- charts/kyverno/templates/cleanup-controller/role.yaml
- config/install-latest-testing.yaml
This PR fixes cleanup controller RBAC (missing secret delete).
> fix: cleanup controller rbac

- pkg/engine/api/context.go
- pkg/engine/api/contextloader.go
- pkg/engine/api/resolver_test.go
- pkg/engine/apicall/apiCall.go
- pkg/engine/apicall/apiCall_test.go
- pkg/engine/context/loader.go
- pkg/engine/context/loaders/apicall.go
- pkg/engine/context/loaders/configmap.go
- pkg/engine/context/loaders/imagedata.go
- pkg/engine/context/loaders/variable.go
refactor: add specific loaders from #7597 (cherry-pick #7671)
> refactor: add specific loaders from #7597 (cherry-pick #7671)

- pkg/engine/context/context.go
- pkg/engine/context/evaluate.go
- pkg/engine/factories/contextloaderfactory.go
This PR partially migrates context loaders from #7597.
> refactor: migrate context loaders (part 1) from #7597

- cmd/cli/kubectl-kyverno/utils/store/contextloader.go
- cmd/internal/engine.go
- pkg/engine/api/contextloader.go
- pkg/engine/context/context.go
- pkg/engine/context/evaluate.go
- pkg/engine/factories/contextloaderfactory.go
- pkg/engine/image_verify_test.go
- pkg/engine/mutation_test.go
- pkg/engine/validation_test.go
- pkg/webhooks/resource/fake.go
- pkg/webhooks/resource/validation_test.go
refactor: migrate context loaders (part 1) from #7597 (cherry-pick #7676)
> refactor: migrate context loaders (part 1) from #7597 (cherry-pick #7676)

- charts/kyverno/README.md
- charts/kyverno/templates/_helpers.tpl
- charts/kyverno/templates/admission-controller/deployment.yaml
- charts/kyverno/templates/background-controller/deployment.yaml
- charts/kyverno/templates/cleanup-controller/deployment.yaml
- charts/kyverno/templates/reports-controller/deployment.yaml
- charts/kyverno/values.yaml
- cmd/background-controller/main.go
- cmd/cleanup-controller/main.go
- cmd/internal/config.go
- cmd/internal/flag.go
- cmd/kyverno/main.go
- cmd/reports-controller/main.go
- config/install-latest-testing.yaml
- pkg/engine/context/loaders/apicall.go
- pkg/engine/factories/contextloaderfactory.go
- pkg/toggle/context.go
- pkg/toggle/toggle.go
This PR adds a lazy loading feature flag.
The flag is managed directly by the context load making everything non intruisive.
> feat: add lazy loading feature flag

- charts/kyverno/templates/cleanup-controller/role.yaml
- config/install-latest-testing.yaml
fix: cleanup controller rbac (cherry-pick #7669)
> fix: cleanup controller rbac (cherry-pick #7669)

- charts/kyverno/README.md
- charts/kyverno/templates/_helpers.tpl
- charts/kyverno/templates/admission-controller/deployment.yaml
- charts/kyverno/templates/background-controller/deployment.yaml
- charts/kyverno/templates/cleanup-controller/deployment.yaml
- charts/kyverno/templates/reports-controller/deployment.yaml
- charts/kyverno/values.yaml
- cmd/background-controller/main.go
- cmd/cleanup-controller/main.go
- cmd/internal/config.go
- cmd/internal/flag.go
- cmd/kyverno/main.go
- cmd/reports-controller/main.go
- config/install-latest-testing.yaml
- pkg/engine/context/loaders/apicall.go
- pkg/engine/factories/contextloaderfactory.go
- pkg/toggle/toggle.go
feat: add lazy loading feature flag (cherry-pick #7680)
> feat: add lazy loading feature flag (cherry-pick #7680)

- pkg/engine/internal/imageverifier.go
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/update-multi-containers/01-policy.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/update-multi-containers/02-resource.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/update-multi-containers/README.md
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/update-multi-containers/policy-assert.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/update-multi-containers/policy.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/update-multi-containers/resource-v1.yaml
- test/conformance/kuttl/verifyImages/clusterpolicy/standard/update-multi-containers/resource-v2.yaml
fix: image verification (cherry-pick #7652)
> fix: image verification (cherry-pick #7652)

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/README.md
- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
> release v1.10.1-rc.1

- pkg/controllers/openapi/controller.go
- pkg/controllers/openapi/manager.go
- pkg/openapi/manager.go
This PR locks schema manager when updating it.
> fix: lock schema manager when updating it

- .github/workflows/release.yaml
- .goreleaser.yml
This PR should fix release signing.
> fix: release signing

- .github/workflows/release.yaml
This PR removes show goreleaser version step.
> fix: remove show goreleaser version step

- .github/workflows/release.yaml
- .goreleaser.yml
fix: release signing (cherry-pick #7711)
> fix: release signing (cherry-pick #7711)

- .github/workflows/cli.yaml
- .github/workflows/codecov.yaml
- .github/workflows/comment-commands.yaml
- .github/workflows/fossa.yml
- .github/workflows/images-build.yaml
This PR reduces token permissions.
> fix: reduce token permissions

- test/conformance/kuttl/_aaa_template_resources/02-setup-user.yaml
Adds a template to the kuttl test scaffolding directory containing a script to create a user in kubectl and creates the context for that user so that they can execute `kubectl` commands as that user, given the rolebindings it requires.
@chipzoller Please take a look.
Adds a step to the kuttl test scaffolding directory which contains a bash script to create a user and a context for them to perform `kubectl` commands.
> feat: template for user setup in kuttl

- cmd/internal/check.go
Fix small typo in `cmd/internal/check.go` (`environement` -> `environment`).
/kind bug
Change `environement` -> `environment`.
> fix: typo in check cmd

- cmd/cli/kubectl-kyverno/apply/apply_command.go
- cmd/cli/kubectl-kyverno/test/api/types.go
- cmd/cli/kubectl-kyverno/utils/common/common.go
- cmd/cli/kubectl-kyverno/utils/common/common_test.go
- cmd/cli/kubectl-kyverno/utils/common/fetch.go
- cmd/cli/kubectl-kyverno/utils/common/kyverno_resources_types.go
- cmd/cli/kubectl-kyverno/utils/common/validatingadmission_resources_types.go
- cmd/cli/kubectl-kyverno/utils/values/load.go
- cmd/cli/kubectl-kyverno/utils/values/types.go
This PR refactors cli values loading and removes dead code.
> fix: refactor cli values loading and remove dead code

- cmd/cli/kubectl-kyverno/apply/apply_command.go
This PR improves cli apply args check.
> fix: improve cli apply args check

- cmd/cli/kubectl-kyverno/apply/apply_command.go
- cmd/cli/kubectl-kyverno/apply/apply_command_test.go
- cmd/cli/kubectl-kyverno/apply/generate.go
- cmd/cli/kubectl-kyverno/apply/generate_test.go
- cmd/cli/kubectl-kyverno/apply/log.go
- cmd/cli/kubectl-kyverno/apply/report.go
- cmd/cli/kubectl-kyverno/apply/report_test.go
- cmd/cli/kubectl-kyverno/test/test.go
- cmd/cli/kubectl-kyverno/utils/common/common.go
This PR removes cli dead/obsolete code.
> fix: remove cli dead code

- charts/kyverno/Chart.yaml
- charts/kyverno/templates/admission-controller/role.yaml
Fixes an regression introduced in #7633 where the helm chart template would render multiple resources on the same line, resulting in invalid yaml.
This removes the hyphen in the template to ensure that each resource is rendered on a new line
Before:
```yaml
- apiGroups:
- apps
resources:
- deployments- deployments/scale
verbs:
- get
- list
- watch- patch
- update
```
After:
```yaml
- apiGroups:
- apps
resources:
- deployments
- deployments/scale
verbs:
- get
- list
- watch
- patch
- update
```
> chart: fix admission controller rbac templating

- cmd/internal/registry.go
- pkg/engine/api/client.go
- pkg/engine/factories/registryclientfactory.go
- pkg/images/verifier.go
- pkg/notary/registry.go
- pkg/registryclient/authn.go
- pkg/registryclient/client.go
- pkg/registryclient/utils.go
This PR removes manual keychain refresh from client.
> refactor: remove manual keychain refresh from client

- pkg/event/events.go
- pkg/webhooks/utils/event.go
> fix: skip creating event for an empty resource name #7810 (cherry-pick #7810)

- go.mod
- pkg/cosign/cosign_test.go
Tekton image was causing nancy to fail. This PR replaces that
> bug: fix nancy by removing tekton payload from cosign test

- charts/kyverno/Chart.yaml
- charts/kyverno/README.md
- charts/kyverno/ci/cleanupJobs-values.yaml
- charts/kyverno/templates/cleanup/cleanup-admission-reports.yaml
- charts/kyverno/templates/cleanup/cleanup-cluster-admission-reports.yaml
- charts/kyverno/values.yaml
Ensure the cleanup CronJob resources can have `nodeSelector` set.
Fixes #7826
/milestone 1.10.2
/kind feature
> Add nodeSelector for cleanupJob CronJob resources

- charts/kyverno/Chart.yaml
- charts/kyverno/templates/admission-controller/role.yaml
Cherry-pick https://github.com/kyverno/kyverno/pull/7774.
> chart: fix admission controller rbac templating (cherry-pick #7774)

- cmd/internal/registry.go
- pkg/notary/registry.go
- pkg/registryclient/authn.go
- pkg/registryclient/client.go
- pkg/registryclient/utils.go
cherry-pick: https://github.com/kyverno/kyverno/pull/7806
> refactor: remove manual keychain refresh from client (#7806) (cherry-pick)

- api/kyverno/v1/clusterpolicy_types.go
- api/kyverno/v1/common_types.go
- api/kyverno/v1/policy_types.go
- test/conformance/kuttl/generate/validation/clusterpolicy/cloneList/01-clusterrole.yaml
- test/conformance/kuttl/generate/validation/clusterpolicy/cloneList/02-check.yaml
- test/conformance/kuttl/generate/validation/clusterpolicy/cloneList/README.md
- test/conformance/kuttl/generate/validation/clusterpolicy/cloneList/policy-fail-1.yaml
- test/conformance/kuttl/generate/validation/clusterpolicy/cloneList/policy-fail-2.yaml
- test/conformance/kuttl/generate/validation/clusterpolicy/cloneList/policy-fail-3.yaml
- test/conformance/kuttl/generate/validation/clusterpolicy/cloneList/policy-pass.yaml
- test/conformance/kuttl/generate/validation/policy/cloneList/01-ns.yaml
- test/conformance/kuttl/generate/validation/policy/cloneList/02-check.yaml
- test/conformance/kuttl/generate/validation/policy/cloneList/README.md
- test/conformance/kuttl/generate/validation/policy/cloneList/policy-fail-1.yaml
- test/conformance/kuttl/generate/validation/policy/cloneList/policy-fail-2.yaml
- test/conformance/kuttl/generate/validation/policy/cloneList/policy-fail-3.yaml
- test/conformance/kuttl/generate/validation/policy/cloneList/policy-pass.yaml
Cherry-pick https://github.com/kyverno/kyverno/pull/7823.
> Feat: cloneList rule validation (cherry-pick #7823)

- CHANGELOG.md
- charts/kyverno/README.md
- charts/kyverno/templates/_helpers.tpl
- charts/kyverno/templates/reports-controller/deployment.yaml
- charts/kyverno/values.yaml
- cmd/reports-controller/main.go
- config/install-latest-testing.yaml
- pkg/controllers/report/background/controller.go
> add flag for policy reports (cherry-pick #7888)

- ADOPTERS.md
Adds IITS Consulting as a Kyverno adopter via the Google Form.
Updates ADOPTERS with IITS Consulting.
> add IITS Consulting as adopter from Google Form

- api/kyverno/constants.go
- pkg/controllers/generic/webhook/controller.go
- pkg/controllers/webhook/controller.go
- pkg/controllers/webhook/utils.go
- pkg/utils/annotations.go
- pkg/webhooks/server.go
> chore: move more constants

- .github/ISSUE_TEMPLATE/bug-cli.yaml
- .github/ISSUE_TEMPLATE/bug-other.yaml
- .github/ISSUE_TEMPLATE/bug-webhook.yaml
Updates issue template drop-down lists with 1.10.2.
Updates issue template drop-down lists with 1.10.2.
> add 1.10.2 to issue drop-downs

- cmd/cleanup-controller/main.go
- pkg/controllers/ttl/controller.go
- pkg/controllers/ttl/manager.go
- pkg/controllers/ttl/utils.go
- pkg/controllers/ttl/utils_test.go
This PR renames ttl controller package.
> chore: rename ttl controller package

- api/kyverno/constants.go
- pkg/controllers/ttl-controller/utils.go
- pkg/validation/ttl-label/validate.go
This PR moves ttl formats to constants.
> chore: move ttl formats to constants

- pkg/controllers/ttl/controller.go
This PR fixes ttl cleanup controller events processing:
- don't register for delete events
- incorrect calls to `queue.Done` and `queue.Forget`
> fix: ttl cleanup controller events processing

- pkg/controllers/ttl/manager.go
This PR fixes ttl manager stop informer on error.
> fix: ttl manager stop informer on error

- pkg/engine/context/context.go
When using a label or annotation with quoted dots, AddVariable was splitting inside the quote causing it to be improperly parsed and replaced
Example
```
- name: remove-annotation
preconditions:
all:
value: UPDATE
- key: "{{ request.oldObject.metadata.labels.\"com.example/my-label\" || '' }}"
value: all
```
variables.yaml
```
policies:
- name: secret-annotation
resources:
- name: remove-secret-annotation
values:
request.operation: UPDATE
request.oldObject.metadata.labels."com.example/my-label": test
```
AddVariable splits on `.` so it is splitting the value into:
```
{
"request": {
"oldObject": {
"metadata": {
"labels": {
"com": {
"example/my-label": "test"
}
}
}
}
}
}
```
instead of
```
{
"request": {
"oldObject": { …
```
> fix: Fixed issue with AddVariable that prevented certain variables

- cmd/cli/kubectl-kyverno/apply/apply_command.go
- cmd/cli/kubectl-kyverno/apply/apply_command_test.go
- cmd/cli/kubectl-kyverno/utils/common/common.go
- cmd/cli/kubectl-kyverno/utils/common/kyverno_policies_types.go
[Here](https://github.com/kyverno/kyverno/blob/c38a014468f46a4a92c09f69a12dee0e821fdabd/cmd/cli/kubectl-kyverno/apply/apply_command.go#L402C1-L451C5) for kyverno apply after getting a engine response we are updating rc ( a struct which contains results status count) .
But we are are doing the same thing [here](https://github.com/kyverno/kyverno/blob/c38a014468f46a4a92c09f69a12dee0e821fdabd/cmd/cli/kubectl-kyverno/utils/common/kyverno_policies_types.go#L181C1-L182C1) for the same response
So we have to remove the repeated logic from kyverno_policies_types.go .
Closes #6115 .
/kind bug
```yaml
metadata:
name: disallow-latest-tag
annotations:
policies.kyverno.io/category: Best Practices
The ':latest' tag is …
```
> fix: Kyverno cli apply duplicate result counts 

- pkg/engine/context/deferred.go
Load data did not return an error
> fix: return err in load data

- .github/ISSUE_TEMPLATE/bug-webhook.yaml
This PR adds K8S 1.28 to issue template.
> chore: add 1.28 to issue template

- pkg/engine/fuzz_test.go
The fuzzer instantiates its own `cfg` variable and does not need to rely on one from other tests. 
/kind cleanup
Reference the fuzzers own variable.
> chore: use fuzzers own cfg variable

- charts/kyverno/Chart.yaml
- charts/kyverno/templates/background-controller/deployment.yaml
- charts/kyverno/templates/cleanup-controller/deployment.yaml
- charts/kyverno/templates/reports-controller/deployment.yaml
- charts/kyverno/values.yaml
- config/install-latest-testing.yaml
This PR fixes image pull policy missing in a couple of deployments.
Fixes #8058
> fix: image pull policy missing

- pkg/engine/adapters/dclient.go
- pkg/engine/api/client.go
- pkg/engine/handlers/validation/validate_cel.go
- test/conformance/kuttl/validate/clusterpolicy/standard/cel/check-statefulset-namespace/01-ns.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/cel/check-statefulset-namespace/02-policy.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/cel/check-statefulset-namespace/03-statefulset.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/cel/check-statefulset-namespace/README.md
- test/conformance/kuttl/validate/clusterpolicy/standard/cel/check-statefulset-namespace/ns.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/cel/check-statefulset-namespace/policy-assert.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/cel/check-statefulset-namespace/policy.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/cel/check-statefulset-namespace/statefulset-fail.yaml
- test/conformance/kuttl/validate/clusterpolicy/standard/cel/check-statefulset-namespace/statefulset-pass.yaml
This PR is to support namespaceObject variable in CEL expressions for Kyverno policies.
Closes #8070 
/kind 
1. `kubectl create namespace testing`
2. `kubectl create namespace production`
3. policy.yaml:
```
metadata:
name: check-deployment-namespace
spec:
rules:
- name: deployment-namespace
match:
any:
- resources:
kinds:
- Deployment
validate:
cel:
expressions:
- expression: "namespaceObject.metadata.name == 'production'"
message: "The deployment must be created in the 'production' namespace."
```
4. bad-deployment.yaml:
```
metadata:
name: deployment-test
namespace: testing
spec:
replicas: 1
selector:
matchLabels:
app: app
template: …
```
> feat: support namespaceObject variable in CEL expressions

- pkg/webhooks/utils/exclude.go
- pkg/webhooks/utils/exclude_test.go
This PR allows mutation of policy reports.
Fixes #7772
> fix: allow mutation of policy reports
