pkg/autogen/autogen.go
pkg/autogen/autogen_test.go

This PR fixes a case where auto gen generates rules when names is used in `match` or `exclude`.
Fixes https://github.com/kyverno/kyverno/issues/4339

fix: auto gen enabled when using names

---

pkg/controllers/report/background/controller.go

This PR fixes an issue where background scan reports were not correctly removed when policies are deleted.

fix: clean background scan reports

---

cmd/kyverno/main.go

This PR makes use constants defined in openapi controller.

fix: use constants defined in openapi controller

---

pkg/policycache/cache.go
pkg/policycache/cache_test.go

Signed-off-by: Sandesh More <sandesh.more@infracloud.io>
currently when validation policy is created with ValidationFailureActionOverride and has enforce action defined for atleast one namespace, then validation always happens in validation webhook handler and even when it has action audit for a namespace. 
This PR will add filter policies for audit/enforce considering resource namespace and ValidationFailureActionOverride.
closes: #3058 part 1
/kind bug
filter policies for validation policies considering requested resource namespace and action/namespace defined in ValidationFailureActionOverride for more granularity.
```
metadata:
name: check-label-app-test
spec:
validationFailureActionOverrides:
- action: …
```

filter validation policies using ValidationFailureActionOverride

---

api/kyverno/v1/image_verification_types.go
charts/kyverno/templates/crds.yaml
config/crds/kyverno.io_clusterpolicies.yaml
config/crds/kyverno.io_policies.yaml
config/install.yaml
config/install_debug.yaml
docs/crd/v1/index.html
pkg/cosign/cosign.go
pkg/engine/imageVerify.go
pkg/policy/validate.go
pkg/policy/validate_test.go
test/e2e/verifyimages/resources.go

This PR adds support to specify signature algorithm in verifyImages.attestors.entries.keys. Currently Kyverno only supports sha256 crypto hash algorithm. This doesn't handle keys with sha512 hash algorithm. With this PR, user can specify algorithm type in Kyverno policy.
Closes #4433 
/kind feature
- Added new field SignatureAlgorithm in verifyImages.attestors.entries.keys
- Updated CRDs to accommodate this field
- Modified decodePEM function to pass user specified algorithm or a default value sha256
Policy: 
```yaml
metadata:
name: check-image
spec:
rules:
- name: check-image
match:
any:
- resources: …
```

Added support to specify key signature algorithm in verifyImages

---

.github/workflows/release.yaml

This PR will store the `install.yaml` in an OCI registry by using _Flux CLI_.
Fixes #4869 
/kind feature

chore: Push and sign install manifests to GHCR

---

pkg/webhooks/handlers/admission.go

This PR adds user info in admission request logs.
This is useful for troubleshooting an abnormal quantity of admission requests.

fix: add user info in admission request logs

---

charts/kyverno/Chart.yaml
charts/kyverno/README.md
charts/kyverno/ci/imageRegistry-values.yaml
charts/kyverno/templates/_helpers.tpl
charts/kyverno/templates/deployment.yaml
charts/kyverno/templates/tests/test.yaml
charts/kyverno/values.yaml

To make the customization of the container registries easier, eg. a custom private registry, this change adds a new property on the images configuration to allow setting a custom image registry without needing to mess around the name of the image.
This is specially need if you use some GitOps tool like Flux / ArgoCD an you want to use a private container registry where its URL its stored ConfigMap. This change would allow us to simply replace the registry without having to have a custom ConfigMap entry with the `private.container.registry/kyverno/kyvernopre` to be replaced when installing Kyverno.
https://github.com/kyverno/kyverno/issues/4280
/kind feature
Add a registry property on the image settings in the Helm chart to allow for customization of the registry separately.
```bash
❯ helm …
```

feat: Add container registry setting on Helm Chart

---

charts/kyverno/Chart.yaml
charts/kyverno/README.md
charts/kyverno/ci/imageRegistry-values.yaml
charts/kyverno/templates/_helpers.tpl
charts/kyverno/templates/deployment.yaml
charts/kyverno/templates/tests/test.yaml
charts/kyverno/values.yaml

This is cherry-pick of #4281 
To make the customization of the container registries easier, eg. a custom private registry, this change adds a new property on the images configuration to allow setting a custom image registry without needing to customize the repository of the image.
Signed-off-by: Samuel Torres <samuelpirestorres@gmail.com>

feat: Add container registry setting on Helm Chart (cherry-pick #4281)

---

scripts/labs/argocd/README.md
scripts/labs/argocd/kind-argo.sh

This PR adds metrics server and kube-prometheus-stack to argocd lab.
Unfortunately kube-prometheus-stack fails to sync the first time it is deployed hence we need to make it pass by hand.

feat: add metrics server and kube-prometheus-stack to argocd lab

---

pkg/utils/runtime/utils.go

This PR fixes webhooks not registering when using name override.
Fixes #4605

fix: webhooks not registering when using name override

---

pkg/controllers/webhook/controller.go
pkg/utils/controller/utils.go

This PR adds an update status helper.
It makes it easier to update a resource status by automatically deep copying the resource and checking if something changed.

refactor: add update status helper

---

pkg/background/common/util.go
pkg/background/update_request_controller.go

DefaultRetry is the recommended retry for a conflict where multiple clients are making changes to the same resource. 
Earlier parameters were to aggressive , which was causing update conflicts. 
The news defaults parameters are
```go
var DefaultRetry = wait.Backoff{
Steps:    5,
Duration: 10 * time.Millisecond,
Factor:   1.0,
Jitter:   0.1,
}
```
Fixes: https://github.com/kyverno/kyverno/issues/4265

fix: use default retry with retryfunc for a conflict

---

pkg/webhooks/resource/handlers.go
pkg/webhooks/resource/handlers_test.go

This PR sets mutation changes done for resource image in policy context. This verifies public key against mutated image.
Closes #4655 
/milestone 1.8.2
/kind bug
Added fix to build new policy context once images are mutated.
Policy:
```yaml
metadata:
name: disallow-unsigned-images
spec:
rules:
- name: replace-image-registry
match:
any:
- resources:
kinds:
- Pod
mutate:
foreach:
- list: "request.object.spec.containers"
spec:
containers:
- name: "{{ element.name }}"
image: "{{ regex_replace_all_literal('.*(.*)/', '{{element.image}}', 'pratikrshah/' )}}"
- name: "disallow-unsigned-images-rule"
match:
any:
- resources:
kinds:
- …
```

Fixed issue-4655: verifyImages is executed before mutate

---

pkg/controllers/certmanager/controller.go
pkg/controllers/config/controller.go
pkg/controllers/openapi/controller.go
pkg/controllers/policycache/controller.go
pkg/controllers/report/admission/controller.go
pkg/controllers/report/aggregate/controller.go
pkg/controllers/report/background/controller.go
pkg/controllers/report/resource/controller.go
pkg/controllers/webhook/controller.go
pkg/utils/controller/run.go
pkg/webhooks/utils/policy_context_builder.go

This PR fixes go routines not gracefully shut down in controllers.
It's done by delegating the creation of those go routines in the `controller.Run` helper, this way we can account for them in the wait group when shutting down.

fix: go routines not gracefully shut down in controllers

---

pkg/utils/runtime/utils.go

This PR fixes a case for detection of kyverno going down.
We were not checking the deletion timestamp of the deployment.

fix: detection of kyverno going down

---

pkg/logging/log.go
pkg/webhooks/server.go

This PR adds webhook server logger support.
Basically it provides a `log.Logger` wrapper around a `logr.Logger` and uses that in the webhook server.

feat: add webhook server logger

---

cmd/cli/kubectl-kyverno/apply/apply_command.go
cmd/cli/kubectl-kyverno/test/test_command.go
cmd/cli/kubectl-kyverno/utils/common/common.go
cmd/cli/kubectl-kyverno/utils/common/common_test.go
cmd/cli/kubectl-kyverno/utils/store/store.go
pkg/engine/jsonContext.go

Signed-off-by: Sandesh More <sandesh.more@infracloud.io>
previously, **kyverno apply** command ignored **API CALLS** when used with **--cluster** option.
This PR enables **API CALL** for  **kyverno apply** command when used with **--cluster** option. 
Closes #2777
/feature
```
metadata:
name: restrict-ns-pods-count
spec:
rules:
- name: restrict-ns-pod-count
match:
resources:
kinds:
- Pod
context:
- name: podcounts
apiCall:
urlPath: "/api/v1/namespaces/test/pods"
jmesPath: "items | length(@)"
validate:
message: "maximum of 5 Pods allowed in test namespace"
deny:
conditions:
- key: "{{ podcounts }}"
value: 5
```
Above policy checks for pod count in **test** namespace.
``` …
```

added apiCalls support in kyverno-apply command

---

pkg/engine/validate/utils.go
pkg/engine/validate/validate.go

This PR makes engine response order predictable by sorting keys when iterating over maps.
Fixes #5057

fix: make response order predictable

---

pkg/controllers/webhook/log.go

This PR uses the correct logger constructor in webhook controller.

fix: use correct logger in webhook controller

---

.github/workflows/release.yaml

Use the `docker/login-action` action and the default `GITHUB_TOKEN` for setting up the GHCR credentials for Flux and Cosign to be able to push OCI artifacts to ` ghcr.io/kyverno/manifests/kyverno`.

ci: Use the Docker login action for GHCR auth

---

CHANGELOG.md
cmd/kyverno/main.go

This PR adds a flag to configure the number of background scan workers.

feat: add flag to configure the number of background scan workers

---

.github/workflows/release.yaml

Fixes to the `release` workflow:
- use the correct version to tag artifacts
- add only the generated install.yaml to the artifact contents

ci: Fix publishing install manifests with Flux

---

pkg/engine/mutate/patch/patchesUtils.go
pkg/engine/mutate/patch/patchesUtils_test.go

This PR allows the `/metadata/finalizers` path to be patched with patchesJson6902 mutation
fixes https://github.com/kyverno/kyverno/issues/5131
/kind bug
add `/metadata/finalizers` to ignorePaths exception conditional

fix finalizers mutation with patchesJson6902

---

pkg/background/mutate/mutate.go

When updating existing resources while process mutate existing policies, the resource version might have changed during the update. This PR resets the resource version on updates.
Fixes https://github.com/kyverno/kyverno/issues/5142.
/1.8.2
/bug
1. install the sample policy https://kyverno.io/policies/psa/add-privileged-existing-namespaces/add-privileged-existing-namespaces/
2. observe that the existing namespaces are labeled correctly
3. observe the lifecycle of the UR, the completed UR is GC-ed by Kyverno
```
~ kg ur -n kyverno -w
NAME       POLICY                               RULETYPE   RESOURCEKIND   RESOURCENAME   RESOURCENAMESPACE   STATUS   AGE
ur-zzbwj   add-privileged-existing-namespaces   mutate     Namespace      default …
```

fix: mutateExisting failure - reset resource version on update

---

cmd/kyverno/main.go

This PR runs leader election in a loop so that pods don't terminate when loosing the lead but start a new leader election process.

feat: run leader election in loop

---

Makefile
scripts/kind.yaml

This PR adds a kind config file to enable a couple of options when creating the cluster.
We use this config file when invoking `make kind-create-cluster`.

chore: add kind config file

---

cmd/kyverno/main.go

This PR removes context cancellation when loosing the lead.
Now we are running leader election in a loop we must not cancel the context.

fix: do not cancel context when loosing the lead

---

pkg/controllers/report/background/controller.go
pkg/utils/controller/handlers.go

This PR checks resource version on update notification.
This is to avoid unnecessary calculations if resource didn't change (on informer resync).
Fixes https://github.com/kyverno/kyverno/issues/5129

fix: check resource version on update notification

---

pkg/controllers/report/aggregate/controller.go

This PR uses pagination to aggregate reports to preserve memory usage.

fix: use pagination to aggregate reports

---

cmd/cli/kubectl-kyverno/apply/apply_command.go
cmd/cli/kubectl-kyverno/apply/report.go
cmd/cli/kubectl-kyverno/apply/report_test.go
cmd/cli/kubectl-kyverno/test/test_command.go
cmd/cli/kubectl-kyverno/utils/common/common.go
cmd/cli/kubectl-kyverno/utils/common/info.go

This PR removes policyreport package.
One file remained in the package, used only by the CLI, I moved the file in the CLI common utils package.

refactor: remove policyreport package

---

scripts/labs/argocd/kind-argo.sh

ArgoCD 2.5 is out with server side apply support.
This PR updates argocd lab to make use of it.

chore: server side apply in argo lab

---

pkg/controllers/report/aggregate/controller.go

This PR adds policy label to policy reports.
The label key is `cpol.kyverno.io/<policy name>` or `pol.kyverno.io/<policy name>` for cluster policies/namespaced policies.
The label value is the policy version.
Length of policy name is currently not restricted, this could be an issue for long policy names that exceed 63 chars.
Fixes https://github.com/kyverno/kyverno/issues/5113

feat: add policy label to policy reports

---

pkg/engine/mutation.go
pkg/engine/validation.go

Add a condition to check whether foreach elements are nil or not. If the element is empty then no need to proceed further which blocks the deletion of resources as variables are not getting resolved.
closes https://github.com/kyverno/kyverno/issues/3110
/milestone 1.8.2
/kind bug
```yaml
metadata:
name: disallow-capabilities-strict
annotations:
policies.kyverno.io/category: Pod Security Standards (Restricted)
policies.kyverno.io/minversion: 1.6.0
kyverno.io/kyverno-version: 1.6.0
kyverno.io/kubernetes-version: "1.22-1.23"
Adding capabilities other than `NET_BIND_SERVICE` is disallowed. In addition,
all containers must explicitly drop `ALL` …
```

[BUG] Fix foreach deletion issue

---

.github/workflows/comment-commands.yaml

This PR removes `/approve` from prow actions.
`/approve` in its current form allows PR authors to approve their own PRs.

fix: remove /approve from prow actions

---

pkg/policy/validate.go

This PR fixes the installation issue of the policy happened because of an error Got an empty response for external metrics
Closes https://github.com/kyverno/kyverno/issues/5221
/milestone 1.8.2
/kind bug
1. Create a New cluster
2. Install KEDA onto the cluster via the Helm chart but do not create any ScaledObject resources
3. Install Kyverno 
4. Create following policy
```yaml
kind: Policy
metadata:
name: block-evil-cr-from-my-precious-resources
namespace: my-precious
spec:
rules:
- name: he-protecc-he-attacc
match:
all:
- clusterRoles:
- evil-cr
resources:
kinds:
- PersistentVolumeClaim
- Service
- Ingress
- ConfigMap
- Secret
- Deployment
- StatefulSet
- Pod
validate:
message: 'You should be careful when trying …
```

Fix policy installation issue for Got empty response for: external.metrics.k8s.io/v1beta1 

---

pkg/openapi/manager.go
pkg/openapi/manager_test.go

Signed-off-by: Sandesh More <sandesh.more@infracloud.io>
currently validating the resource's schema when using any|all match conditions is skipped.
This PR will validate resource schema when any|all match conditions are used.
closes: #4440
bug
```
metadata:
name: mutate-pod
spec:
rules:
- name: mutate-pod
match:
any:
- resources:
kinds:
- Pod
mutate:
spec:
pod: incorrect
```
```
$ k apply -f second.yaml 
Error from server: error when creating "second.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: mutate result violates resource schema: ValidationError(io.k8s.api.apps.v1.DaemonSet.spec.template.spec): unknown field "pod" in io.k8s.api.core.v1.PodSpec
```

fix: resource schema validation in policies under any/all match

---

Makefile

This PR bumps kuttl to `v0.14.0`

chore: update kuttl

---

charts/kyverno/values.yaml
config/install.yaml
config/manifest/deployment.yaml

This PR reduces startup probe delay.
30 seconds is unnecessarily long.

fix: reduce startup probe delay

---

.gitignore

This PR adds the cli binary to gitignore.

chore: add cli binary to gitignore

---

pkg/engine/validation.go

Add missing `Replicaset` and `Replicationcontroller` kinds  while validating PodSecurity policies added as part of PR
https://github.com/kyverno/kyverno/pull/4975

fix: add replicaset and replicationController kinds in podsecurity validation

---

test/conformance/kuttl/kuttl-test.yaml
test/conformance/kuttl/rbac/aggregate-to-admin/00-cluster-role.yaml
test/conformance/kuttl/rbac/aggregate-to-admin/README.md
test/conformance/kuttl/rbac/aggregate-to-admin/admin-generaterequest.yaml
test/conformance/kuttl/rbac/aggregate-to-admin/admin-policies.yaml
test/conformance/kuttl/rbac/aggregate-to-admin/admin-policyreport.yaml
test/conformance/kuttl/rbac/aggregate-to-admin/admin-reports.yaml
test/conformance/kuttl/rbac/aggregate-to-admin/admin-updaterequest.yaml

This PR adds rbac kuttl test.
It checks the necessary cluster roles that will be aggregated in the `admin` cluster role.

test: add rbac kuttl test

---

pkg/policy/validate.go
pkg/policy/validate_test.go

Add validation for generate namespace policy
- Generate of cluster scope resource not allowed in namespace policy
- Only allowed to generate resource in policy namespace
Fixes #5099

fix: add validation for generate namespace policy

---

api/kyverno/v1/image_verification_test.go
api/kyverno/v1/image_verification_types.go
pkg/policy/validate.go

A verifyImage policy specifying multiple `entries` should be allowed to create. Prior to this PR the policy creation is blocked.
Closes #5379.
1.9.0
/bug
The policy with multiple entries can be created/updated successfully.
```yaml
metadata:
name: verify-image-with-multi-keys
annotations:
policies.kyverno.io/title: Verify Image with Multiple Keys
policies.kyverno.io/minversion: 1.7.0
kyverno.io/kyverno-version: 1.7.2
kyverno.io/kubernetes-version: "1.23"
There may be multiple keys used to sign images based on
the parties involved in the creation process. …
```

fix: the entry length validation for the verify image rule

---

api/kyverno/v1/image_verification_test.go
api/kyverno/v1/image_verification_types.go
pkg/policy/validate.go
test/e2e/verifyimages/resources.go

The policy validation for the verifyImage rule is not invoked properly prior to this change. This PR enables  policy validation for the verifyImage rule.
https://github.com/kyverno/kyverno/issues/5379
/1.8.2
/bug
Bad policy should be blocked:
```
Error from server: error when creating "test.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: spec.rules[0].verifyImages[0].attestors[0]: Invalid value: v1.AttestorSet{Count:(*int)(0xc0028266a8), Entries:[]v1.Attestor{v1.Attestor{Keys:(*v1.StaticKeyAttestor)(0xc001cb1590), Certificates:(*v1.CertificateAttestor)(nil), Keyless:(*v1.KeylessAttestor)(nil), Attestor:(*v1.JSON)(nil), Annotations:map[string]string(nil), Repository:""}, …
```

fix: enable policy validation for the verifyImage rule

---

cmd/cleanup-controller/handlers.go
cmd/cleanup-controller/server.go
pkg/webhooks/handlers/admission.go
pkg/webhooks/handlers/dump.go
pkg/webhooks/handlers/filter.go
pkg/webhooks/handlers/metrics.go
pkg/webhooks/handlers/protect.go
pkg/webhooks/handlers/verify.go
pkg/webhooks/policy/handlers.go
pkg/webhooks/resource/handlers.go
pkg/webhooks/resource/handlers_test.go
pkg/webhooks/server.go

This PR propagates context through admission handlers.
This is needed to implement proper tracing.

refactor: propagate context through admission handlers

---

pkg/engine/imageVerify.go
pkg/engine/imageVerifyValidate.go
pkg/engine/imageVerify_test.go
pkg/policy/validate.go
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/01-policy.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/02-create-good-pod.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/03-create-bad-pod.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/04-update-policy.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/05-create-pod-with-configmap.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/99-cleanup.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/README.md
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/bad-pod.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/good-pod.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/namespace.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/pod-with-configmap-ready.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/pod-with-configmap.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/policy-ready.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/policy.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/update-policy.yaml

This PR doesn't verify resource images which are different from policy images. This allows user to create resources even if there are image verification errors.
Closes #3709 
/kind bug
This PR adds `requireValidation` function which executes following checks.
- checks for variables. if any variables are present in imageRef, function will return `true` so that regular workflow of image verification takes place. if we block variables here, we might not allow user to provide variables for imageRef at all.
- next, function will take images from `policyContext` and if imageExtractors are present in rule, it will generate custom images and replace `images` variable with images from imageExtractors
- then, with images we get, function will check …

Fixed issue-3709: Image verify rule gives error for non-existing configmap

---

hack/main.go
pkg/clients/wrappers/traces/kube/clientset.generated.go
pkg/clients/wrappers/traces/kyverno/clientset.generated.go
pkg/webhooks/handlers/admission.go
pkg/webhooks/handlers/dump.go
pkg/webhooks/handlers/filter.go
pkg/webhooks/handlers/metrics.go
pkg/webhooks/handlers/protect.go
pkg/webhooks/handlers/trace.go
pkg/webhooks/handlers/types.go
pkg/webhooks/handlers/utils.go
pkg/webhooks/handlers/verify.go

This PR makes traces better:
- better use of tracer info
- better operation names
- record errors

feat: make traces better

---

Makefile
cmd/cleanup-controller/main.go
cmd/kyverno/main.go
hack/main.go
pkg/clients/kube/clientset.generated.go
pkg/clients/kyverno/clientset.generated.go
pkg/clients/middleware/metrics/kube/clientset.generated.go
pkg/clients/middleware/metrics/kyverno/clientset.generated.go
pkg/clients/middleware/tracing/kube/clientset.generated.go
pkg/clients/middleware/tracing/kyverno/clientset.generated.go

This PR improves instrumented clients creation:
- adds missing creation funcs
- uses a builder pattern for creation

refactor: improve instrumented clients creation

---

api/kyverno/v1alpha2/admission_report_types.go
charts/kyverno/templates/crds.yaml
cmd/kyverno/main.go
config/crds/kyverno.io_admissionreports.yaml
config/crds/kyverno.io_clusteradmissionreports.yaml
config/install.yaml
config/install_debug.yaml
pkg/controllers/report/admission/controller.go
pkg/controllers/report/aggregate/controller.go
pkg/controllers/report/background/controller.go
pkg/controllers/report/resource/controller.go
pkg/controllers/report/utils/utils.go
pkg/utils/controller/metadata.go
pkg/utils/controller/run.go
pkg/utils/report/labels.go
pkg/utils/report/new.go
pkg/webhooks/resource/imageverification/handler.go
pkg/webhooks/resource/validation/validation.go

This PR fixes admission reports stacking up.
This is due to admission of same resource again and again, therefore the hash does not change and we never get a chance to cleanup reports.
The solution is to continuously aggregate admission reports into one and delete reports that have been aggregated.
Aggregated reports are labeled specifically so that high level reports can consider only those aggregated admission reports.

fix: admission reports stacking up

---

pkg/webhooks/handlers/filter.go
pkg/webhooks/policy/handlers.go
pkg/webhooks/resource/handlers.go
pkg/webhooks/server.go

This PR removes filtering from policy admission handlers.
Filtering only applies to resource admission.

fix: remove filtering for policy admission handlers

---

api/kyverno/v1alpha1/cleanup_policy_interface.go
api/kyverno/v1alpha1/cleanup_policy_types.go
charts/kyverno/templates/cleanup-controller/clusterrole.yaml
charts/kyverno/templates/crds.yaml
cmd/cleanup-controller/controller.go
cmd/cleanup-controller/logger/log.go
cmd/cleanup-controller/main.go
config/crds/kyverno.io_cleanuppolicies.yaml
config/crds/kyverno.io_clustercleanuppolicies.yaml
config/install.yaml
config/install_debug.yaml
pkg/controllers/cleanup/controller.go
pkg/controllers/cleanup/log.go
pkg/controllers/cleanup/utils.go

Signed-off-by: Nikhil Sharma <nikhilsharma230303@gmail.com>
This PR adds reconciling logic for creating CronJob whenever a new cleanup policy is created.
<!--
In a couple sentences, explain why this PR is needed and what it addresses. This should be an explanation a non-developer user can understand and covers the "why" question. It should also clearly indicate whether this PR represents an addition, a change, or a fix of existing behavior. This explanation will be used to assist in the release note drafting process.

Add reconciling logic for creating cronjobs whenever a new cleanup policy is created

---

cmd/cli/kubectl-kyverno/oci/oci_pull.go
cmd/cli/kubectl-kyverno/oci/oci_push.go
pkg/utils/policy/mashal.go

This PR creates a policy utils package.
We manipulate policies a lot and this package will contain policy manipulation code we use often.
For now I added functions to marshal policies into json/yaml.

feat: create a policy utils package

---

pkg/autogen/autogen.go

This PR fixes a typo in autogen package.
`match any block is not be applicable` -> `match any block is not applicable`

fix: typo in autogen package

---

cmd/cleanup-controller/main.go
cmd/kyverno/main.go
pkg/controllers/metrics/policy/controller.go
pkg/controllers/metrics/policy/metrics.go
pkg/metrics/admissionrequests/admissionRequests.go
pkg/metrics/admissionreviewduration/admissionReviewDuration.go
pkg/metrics/client.go
pkg/metrics/init.go
pkg/metrics/metrics.go
pkg/metrics/policychanges/policyChanges.go
pkg/metrics/policyexecutionduration/policyExecutionDuration.go
pkg/metrics/policyresults/policyResults.go
pkg/metrics/policyruleinfo/policyRuleInfo.go
pkg/policy/existing.go
pkg/webhooks/handlers/metrics.go
pkg/webhooks/resource/generation/generation.go
pkg/webhooks/resource/mutation/mutation.go
pkg/webhooks/resource/updaterequest.go
pkg/webhooks/resource/validation/validation.go
pkg/webhooks/utils/metrics.go

This PR propagates context to the metrics package.

feat: propagate context to the metrics package

---

pkg/utils/api/image.go

This PR adds image extractor for `ReplicationController`.

fix: add image extractor for ReplicationController

---

pkg/engine/jsonutils/traverse.go
pkg/utils/util.go
pkg/utils/util_test.go

This PR makes use of builtin `slices.Clone` instead of our own implementation.

chore: use builtin slices.Clone

---

pkg/webhooks/resource/validation/validation.go

cleanup: bring back action on validation failed logging (cherry-pick #5416)

cleanup: bring back action on `validation failed` logging (cherry-pick #5416)

---

cmd/kyverno/main.go
pkg/engine/context/resolvers/constants.go
pkg/engine/context/resolvers/resolvers.go
pkg/engine/context/resolvers/resolvers_test.go
pkg/engine/context/resolvers/types.go
pkg/engine/context/resolvers/utils.go
pkg/engine/context/resolvers/utils_test.go
pkg/engine/imageVerify_test.go
pkg/engine/jsonContext.go
pkg/engine/policyContext.go
pkg/webhooks/resource/fake.go
pkg/webhooks/resource/handlers.go
pkg/webhooks/utils/policy_context_builder.go

This PR adds support for cache enhancements for ConfigMap using informers.
Closes #4613 
/kind feature
KDP: https://github.com/kyverno/KDP/pull/38
We create new filtered shared factory instance which filters CM with labels `"cache.kyverno.io/enabled": "true"`. In other words, any CM having these labels will be stored in informer cache.
Using these shared factory instance, we create a resolverChain which gets CM either from informer cache or by using Kubernetes client.
User needs to specify these labels at the time of CM creation. If user doesn't provide these labels, call to get CM will be made to API server which will use Kubernetes client and CM won't be cached.
Policy:
```yaml
---
metadata: …
```

issue-4613: Add support for cache enhancements with informers

---

charts/kyverno/templates/_helpers.tpl

Signed-off-by: Jacob Lorenzen <jacob@lorenzen.me>
When using Flux the Chart version number can contain the plus symbol (+). 
This is not an allowed label field value.
The PR will replace plus symbol with underscore.
/kind bug

fix: replace + symbol with _ symbol on the Chart.Version field

---

pkg/engine/mutate/patch/strategicPreprocessing.go
pkg/engine/mutate/patch/strategicPreprocessing_test.go
test/cli/test-mutate/global-anchor/kyverno-test.yaml
test/cli/test-mutate/global-anchor/patchedResource.yaml
test/cli/test-mutate/global-anchor/patchedResourceWithVolume.yaml
test/cli/test-mutate/global-anchor/policy.yaml
test/cli/test-mutate/global-anchor/resources.yaml

Signed-off-by: ansalamdaniel <ansalam.daniel@infracloud.io>
This PR aims to handle the global anchor variable disparity in apply command for mutation policy. Resource is mutated even if the global anchor match is false.
**policy.yaml**
```yaml
metadata: 
name: add-safe-to-evict
annotations:
policies.kyverno.io/category: Workload Management
policies.kyverno.io/description: The Kubernetes cluster autoscaler does not evict pods that 
use hostPath or emptyDir volumes. To allow eviction of these pods, the annotation 
cluster-autoscaler.kubernetes.io/safe-to-evict=true must be added to the pods. 
spec: 
rules: 
- name: annotate-empty-dir
match:
any:
- resources: 
kinds:
- Pod
mutate: 
metadata:
annotations: …
```

Fix: handling unexpected global-anchor-variable for the apply command

---

pkg/background/mutate/mutate.go

This PR fixes the panic issue for background mutating, reported from [Slack](https://kubernetes.slack.com/archives/CLGR9BJU9/p1670469596364199) against Kyverno v1.7.X:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1ebbe0b]
goroutine 1126 [running]:
[k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0](http://k8s.io/apimachinery/pkg/util/runtime.HandleCrash(%7B0x0), 0x0, 0xfffffffe?})
/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x228d360, 0x4294410})
/usr/local/go/src/runtime/panic.go:838 +0x207
[github.com/kyverno/kyverno/pkg/background/mutate.(*MutateExistingController).report(0xc001909848](http://github.co …
```

fix: Panic on nil error

---

cmd/cli/kubectl-kyverno/utils/common/common.go
cmd/kyverno/main.go
pkg/background/generate/generate.go
pkg/background/mutate/mutate.go
pkg/controllers/report/background/controller.go
pkg/controllers/report/utils/scanner.go
pkg/cosign/cosign.go
pkg/cosign/cosign_test.go
pkg/engine/background.go
pkg/engine/imageVerify.go
pkg/engine/imageVerifyValidate.go
pkg/engine/imageVerify_test.go
pkg/engine/jsonContext.go
pkg/engine/mutation.go
pkg/engine/mutation_test.go
pkg/engine/validation.go
pkg/engine/validation_test.go
pkg/policy/apply.go
pkg/testrunner/scenario.go
pkg/webhooks/resource/generation/generation.go
pkg/webhooks/resource/generation/utils.go
pkg/webhooks/resource/handlers.go
pkg/webhooks/resource/imageverification/handler.go
pkg/webhooks/resource/mutation/mutation.go
pkg/webhooks/resource/updaterequest.go
pkg/webhooks/resource/utils.go
pkg/webhooks/resource/validation/validation.go
pkg/webhooks/resource/validation_test.go
pkg/webhooks/updaterequest/fake.go
pkg/webhooks/updaterequest/generator.go

This PR propagates context through engine code.
This is need for proper tracing.

feat: propagate context through engine

---

CHANGELOG.md
cmd/kyverno/main.go

This PR removes deprecated flag `splitPolicyReport`.

chore: remove deprecated flag splitPolicyReport

---

pkg/autogen/autogen.go
pkg/autogen/log.go
pkg/autogen/rule.go

This PR bumps log level for `autogen` debug logs.
Level 3 is too low, they are polluting logs too much.

fix: bump log level for autogen debug logs

---

pkg/webhooks/handlers/admission.go
pkg/webhooks/resource/validation/validation.go

Unify the format of gvk, gvr, kind. Fix info kind msg.
https://github.com/kyverno/kyverno/issues/5641
/kind bug

fix info kind error

---

cmd/kyverno/main.go
pkg/background/common/context.go
pkg/background/generate/generate.go
pkg/background/mutate/mutate.go
pkg/background/update_request_controller.go
pkg/controllers/report/background/controller.go
pkg/controllers/report/utils/scanner.go
pkg/policy/apply.go
pkg/policy/existing.go
pkg/policy/policy_controller.go
pkg/policy/updaterequest.go

This PR initializes configmap resolver in background components to fix the panic issue.
Closes https://github.com/kyverno/kyverno/issues/5704.
/1.9.0
/bug
Re-apply the policy attached in the issue, Kyverno no longer panics.
cc @shahpratikr

fix: Initializes configmap resolver in background components

---

pkg/engine/imageVerify.go

This PR fixes a logger panic issue introduced in https://github.com/kyverno/kyverno/pull/5703, the cherry-pick PR should come after https://github.com/kyverno/kyverno/pull/5706.

fix: logger panic

---

.github/workflows/scorecard.yaml

This reverts commit 2d231d60c4324558c2cbd3e1be0bd2a33c895268 in #5724.

Revert "chore(deps): bump ossf/scorecard-action from 2.1.0 to 2.1.1 (#5724)

---

.github/workflows/cli.yaml
.github/workflows/codecov.yaml
.github/workflows/conformance.yaml
.github/workflows/e2e.yaml
.github/workflows/fossa.yml
.github/workflows/image-build.yaml
.github/workflows/release.yaml
.github/workflows/reuse.yaml
.github/workflows/tests.yaml
.github/workflows/verify-codegen.yaml

Fixes CVE-2022-41717 https://avd.aquasec.com/nvd/2022/cve-2022-41717/.

Bump Go 1.19.4

---

pkg/metrics/parsers.go

This PR adds the rule type VerifyImages when parsing the rule type. It fixes the empty rule_type entry in the metric.

fix: add rule type "ImageVerify"

---

api/kyverno/v1/policy_types.go
api/kyverno/v2beta1/policy_types.go
charts/kyverno/templates/crds.yaml
config/crds/kyverno.io_policies.yaml
config/install.yaml

This PR removes `all` category from all our CRDs.

fix: remove all category from all our CRDs

---

pkg/engine/background.go
pkg/engine/imageVerify.go
pkg/engine/mutation.go
pkg/engine/validation.go

Signed-off-by: Eileen Yu <eileenylj@gmail.com>
Add policy exception logic to:
- mutate
- generate
- imageVerify
https://github.com/kyverno/kyverno/issues/2627

feat: add exception logic

---

.github/workflows/conformance.yaml

This PR enables conformance tests to be run on different k8s versions of clusters.

feat: run conformance tests with different k8s versions

---

.github/workflows/tests.yaml

This PR removes autogen internals specific tests.
Autogen internals is now the only supported option.

chore: remove autogen internals tests

---

pkg/event/events.go
pkg/webhooks/utils/event.go

Signed-off-by: Eileen <eileenylj@gmail.com>
Generate K8s event when `Policyexception` is triggered.
/kind feature

feat: generate k8s event for exception

---

pkg/controllers/report/background/controller.go

This PR fixes error handling in last scan time parsing.
The condition check was actually wrong and checked error was nil instead of checking it was NOT nil.

fix: error handling in last scan time parsing

---

charts/kyverno-policies/Chart.yaml
pkg/engine/jmespath/functions.go

Signed-off-by: Vishal Choudhary <contactvishaltech@gmail.com>
Adds notes to all the functions in https://github.com/kyverno/kyverno/blob/faeab45ede1354e7912045fa002902fd96ee1401/pkg/engine/jmespath/functions.go#L120
Closes #5555

Adds notes to functions

---

pkg/engine/jmespath/functions.go

Signed-off-by: Vishal Choudhary <contactvishaltech@gmail.com>
Adds a custom JMESPath filter which simply prints the current time in, minimally, RFC 3339 format.
Closes #5799 
/kind feature
Add `time_now('<layout>')` JMESPath function
Policy
```yaml
metadata:
name: test-policy
spec:
rules:
- name: test-rule
match:
resources:
kinds:
- Pod
validate:
message: "Denied"
deny:
conditions:
- key: "{{ time_since('') }}"
value: '2023-01-01T22:39:05-07:00'
```
Pod
```yaml
apiVersion: v1
kind: Pod
metadata:
name: myapp
spec:
containers:
- name: my-container
image: nginx
```
Policy
```yaml
metadata:
name: test-policy
spec: …
```

Adds JMESPath filter for returning current time

---

api/kyverno/v1/spec_types.go
api/kyverno/v2beta1/spec_types.go
charts/kyverno/templates/crds.yaml
config/crds/kyverno.io_clusterpolicies.yaml
config/crds/kyverno.io_policies.yaml
config/install.yaml
docs/user/crd/index.html

This PR fixes default value for `validationFailureAction` (use `Audit` instead of `audit`).

fix: default value for validationFailureAction

---

cmd/cli/kubectl-kyverno/apply/report.go
cmd/cli/kubectl-kyverno/utils/common/common.go
cmd/cli/kubectl-kyverno/utils/common/fetch.go
pkg/background/generate/generate.go
pkg/clients/dclient/client.go
pkg/engine/forceMutate_test.go
pkg/engine/imageVerify_test.go
pkg/engine/mutate/mutation_test.go
pkg/engine/mutation_test.go
pkg/engine/utils/utils.go
pkg/engine/utils_test.go
pkg/engine/validation_test.go
pkg/utils/admission/resource.go
pkg/utils/api/image_test.go
pkg/utils/kube/unstructured.go
pkg/utils/kube/unstructured_test.go
pkg/webhooks/handlers/dump.go
pkg/webhooks/resource/generation/generation.go
pkg/webhooks/resource/handlers.go
pkg/webhooks/resource/validation_test.go

This PR moves ConvertToUnstructured from engine utils to kube utils.
There's no relationship with the engine here.

chore: move ConvertToUnstructured from engine utils to kube utils

---

cmd/cli/kubectl-kyverno/apply/report.go
cmd/cli/kubectl-kyverno/utils/common/common.go
cmd/cli/kubectl-kyverno/utils/common/fetch.go
pkg/background/generate/generate.go
pkg/clients/dclient/client.go
pkg/engine/forceMutate_test.go
pkg/engine/imageVerify_test.go
pkg/engine/mutate/mutation_test.go
pkg/engine/mutation_test.go
pkg/engine/utils/utils.go
pkg/engine/utils_test.go
pkg/engine/validation_test.go
pkg/utils/admission/resource.go
pkg/utils/api/image_test.go
pkg/utils/kube/unstructured.go
pkg/utils/kube/unstructured_test.go
pkg/webhooks/handlers/dump.go
pkg/webhooks/resource/generation/generation.go
pkg/webhooks/resource/handlers.go
pkg/webhooks/resource/validation_test.go

chore: move ConvertToUnstructured from engine utils to kube utils (cherry-pick #5847)

chore: move ConvertToUnstructured from engine utils to kube utils (cherry-pick #5847)

---

pkg/controllers/report/background/controller.go

This PR fixes forcing background scan reconciliation at regular intervals.

fix: force background scan recomputation

---

pkg/controllers/report/background/controller.go
pkg/controllers/report/resource/controller.go
pkg/utils/controller/metadata.go

This PR improves background scan reconciliation:
- does not create empty reports
- unifies the full/partial report rebuild paths
- simplifies the reconciliation logic (needs reconcile/reconcile)

refactor: improve background scan reconciliation

---

.github/actions/setup-test-env/action.yaml
.github/workflows/conformance.yaml
.github/workflows/scorecard.yaml

This PR adds a `setup-test-env` gh action.

chore: add setup test env gh action

---

.github/workflows/check-actions.yaml
.github/workflows/tests.yaml

This PR makes check actions pinned by hash a standalone ci job.

chore: make check actions pinned by hash a standalone ci job

---

.github/workflows/tests.yaml
.github/workflows/verify-codegen.yaml

This PR fixes golangci-lint workflow by disabling cache (already managed by `setup-build-env` action).

fix: golangci-lint workflow

---

.github/workflows/check-actions.yaml
.github/workflows/tests.yaml

chore: make check actions pinned by hash a standalone ci job (cherry-pick #5907)

chore: make check actions pinned by hash a standalone ci job (cherry-pick #5907)

---

pkg/background/mutate/mutate.go

This PR set the new object's resource version before updating it.
Closes https://github.com/kyverno/kyverno/issues/5769.
/1.9.0
/bug

fix: mutateExisting - set resourceVersion before update

---

pkg/controllers/webhook/utils.go
pkg/engine/utils.go
pkg/policy/validate.go
pkg/utils/match/match.go
pkg/utils/match/match_test.go

Signed-off-by: Vyom-Yadav <jackhammervyom@gmail.com>
https://github.com/kyverno/kyverno/pull/4916 added support for subresources and removed hardcoded subresources from webhooks (`pods/ephemeralcontainers` and `services/status`). Removal of `pods/ephemeralcontainers` resulted in losing backward compatibility for existing [PSS policies](https://kyverno.io/policies/pod-security/) as all those policies did not explicitly match on `pods/ephemeralcontainers`.
If policies were updated with the kind `Pod/ephemeralcontainers`, it resulted in breaking the auto-gen feature. Finally, it was decided to keep the hardcoded value of `pods/ephemeralcontainers` in the webhook.
1.9.0
/kind bug
```bash
$ kustomize build https://github.com/kyverno/policies/pod-security | kubectl apply -f -
Warning: …
```

fix: Configure webhook to add `ephemeralcontainers` for policies matching on Pod

---

pkg/controllers/cleanup/controller.go

Cronjobs created by the Kyverno cleanup controller should be locked down to PSS restricted checks.

fix: cleanup controller - restrict cronjobs by PSS restricted checks

---

.github/workflows/pr-update.yaml

This PR skips running `pr update` workflow if token is not defined.

chore: do not run pr update workflow if token is not defined

---

.github/workflows/pr-update.yaml
.github/workflows/sonarcloud.yaml

This PR does not run sonar workflow if token is not defined.
Useful for forks that do not have access to the secret.

chore: do not run sonar workflow if token is not defined

---

.github/workflows/scorecard.yaml

This PR skips scorecard workflow if token is not defined.

chore: do not run scorecard workflow if token is not defined

---

Makefile
pkg/event/controller.go

- fix make debug-deploy
- improve log messages

Makefile and log

---

cmd/cleanup-controller/handlers/cleanup/handlers.go
pkg/engine/validation.go
pkg/utils/match/match.go

This PR adds missing user info matching in util funcs (used by policy exceptions and cleanup policies).
Fixes https://github.com/kyverno/kyverno/issues/5930

fix: missing user info matching

---

api/kyverno/v1/user_info_types.go
api/kyverno/v2alpha1/cleanup_policy_types.go
api/kyverno/v2beta1/match_resources_types.go
test/conformance/kuttl/cleanup/validation/no-user-info-in-match/01-cleanuppolicy.yaml
test/conformance/kuttl/cleanup/validation/no-user-info-in-match/README.md
test/conformance/kuttl/cleanup/validation/no-user-info-in-match/cleanuppolicy-with-clusterroles.yaml
test/conformance/kuttl/cleanup/validation/no-user-info-in-match/cleanuppolicy-with-roles.yaml
test/conformance/kuttl/cleanup/validation/no-user-info-in-match/cleanuppolicy-with-subjects.yaml

This PR adds cleanup policies validation to reject policies with user infos in match/exclude.
As they are exclusively processed in the background we don't have user infos when executing those policies.

fix: cleanup policies with user infos in match/exclude should be rejected

---

pkg/engine/jmespath/functions.go
pkg/engine/jmespath/functions_test.go

Signed-off-by: Vishal Choudhary <contactvishaltech@gmail.com>
`time_now` function currently fails in returning correct time
```
1 generate.go:357] background "msg"="variable substitution failed for rule %s" "error"="failed to resolve time_now('') at path /generate/data/spec/schedule: JMESPath query failed: parsing time \"2023-01-07 13:20:09.0738949 +0000 UTC m=+1177.923478701\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \" 13:20:09.0738949 +0000 UTC m=+1177.923478701\" as \"T\"" ""="(MISSING)" "apiVersion"="kyverno.io/v2alpha1" "kind"="PolicyException" "name"="mynewpolex" "namespace"="foo" "policy"="automate-cleanup"
```
Fixes #5800 
This PR fixes the failing of tests
The result string is manually verified to be of right format as there is no way to assert equality with current time

Fixes `time_now` failing

---

pkg/config/config.go
pkg/controllers/report/background/controller.go
pkg/controllers/report/resource/controller.go
pkg/controllers/report/utils/utils.go

This PR logs out a message for the current configured background scan interval. 
It doesn't address item 1 from https://github.com/kyverno/kyverno/issues/5933 as we simply re-queue the report with the background scan interval. That means, we don't know how the reconciliation is triggered.
>1. that the background scan interval has been reached and a scan is taking place
Closes https://github.com/kyverno/kyverno/issues/5933.
/1.9.0
/enhancement

chore: policy report - improve logging

---

pkg/engine/jmespath/functions.go
pkg/engine/jmespath/functions_test.go
pkg/engine/jmespath/time.go
pkg/engine/jmespath/time_test.go

This PR adds a couple more time related jmespath filters:
- `time_utc`
- `time_now_utc`
- `time_diff` (the ultimate replacement for `time_since`)
- `time_before`
- `time_after`
- `time_between`
- `time_truncate`
I also took the opportunity to refactor existing funcs and restructure the package to put all time related filters in a separate file.
- time_utc
`time_utc('2023-02-02T15:04:05-07:00')` -> `2023-02-02T22:04:05Z`
- time_now_utc
same as `time_now` but result is in UTC
- time_diff
`time_diff('2021-01-02T15:04:05-07:00', '2021-01-10T03:14:05-07:00')` -> `180h10m0s`

feat: add more time jmespath filters

---

pkg/engine/imageVerify.go
test/conformance/kuttl/verifyImages/clusterpolicy/cornercases/multiple-attestors/01-assert.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/cornercases/multiple-attestors/01-policy.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/cornercases/multiple-attestors/02-assert.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/cornercases/multiple-attestors/02-pod.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/cornercases/multiple-attestors/99-cleanup.yaml
test/conformance/kuttl/verifyImages/clusterpolicy/cornercases/multiple-attestors/README.md

This PR fixes the images mismatch issue when a verifyImages rule has multiple attestors defined.
Reported in Slack: https://kubernetes.slack.com/archives/CLGR9BJU9/p1673303296239259
Related PR: https://github.com/kyverno/kyverno/pull/5272
cc @shahpratikr 
/1.9.0
/bug
See the kuttl test.

fix: imageRef mismatch

---

cmd/cleanup-controller/handlers/cleanup/handlers.go

Log out deleted resources at default level 2 for cleanup policies.

chore: log out deleted resources at default level for cleanup policies

---

charts/kyverno/templates/clusterrole.yaml
cmd/internal/setup.go
cmd/kyverno/main.go
config/install.yaml
pkg/controllers/generic/webhook/controller.go
pkg/controllers/webhook/controller.go
pkg/controllers/webhook/utils.go
pkg/utils/annotations.go
pkg/webhooks/server.go

This PR cleans up Kyverno managed resources (leases, *webhookconfigurations) and fixes the shutdown panic. The webhooks' owner is set to clusterrole `kyverno:webhook` to deal with Helm uninstall where kyverno lost permission to perform such cleanup.
Closes https://github.com/kyverno/kyverno/issues/5942.
Closes https://github.com/kyverno/kyverno/issues/5355.
/1.9.0
/bug

fix: invoke cleanup process during shutdown

---

charts/kyverno/templates/cleanup-controller/clusterrole.yaml
cmd/cleanup-controller/handlers/cleanup/event.go
cmd/cleanup-controller/handlers/cleanup/handlers.go
config/install.yaml

With this change, an event is created for the successfully applied cleanup policy,
Closes https://github.com/kyverno/kyverno/issues/5976.
/1.9.0
/enhancement
See events are created for both cluatercleanuppolicy and cleanuppolicy:
```
✗ k describe cleanpol cleanup-pod
...
Events:
Type    Reason         Age   From                Message
----    ------         ----  ----                -------
Normal  PolicyApplied  45s   cleanup-controller  successfully cleaned up the target resource Pod/default/example
✗ k describe ccleanpol cleanup-pod  
...
Events:
Type    Reason         Age   From                Message
----    ------         ----  ----                -------
Normal  PolicyApplied  53s   cleanup-controller  successfully cleaned up the …
```

feat: create events for cleanup policies

---

pkg/event/controller.go

There was a bug when we set `--maxQueuedEvents=0`, this PR fixes the issue.
Closes https://github.com/kyverno/kyverno/issues/3185.
/1.10.0
/bug

fix: drop events when queue size is zero

---

pkg/controllers/report/utils/events.go
pkg/event/events.go
pkg/webhooks/utils/event.go

This PR fixes policy exception events.

fix: generate policy exception events

---

cmd/cleanup-controller/handlers/cleanup/handlers.go

Creates warning events when kyverno cannot clean up target resources.
#5976 
/1.9.0
/enhancement
Warning event is generated when delete permission is missing.
```
Events:
Type     Reason       Age   From                Message
----     ------       ----  ----                -------
Warning  PolicyError  20s   cleanup-controller  failed to clean up the target resource ConfigMap/default/example: configmaps "example" is forbidden: User "system:serviceaccount:kyverno:kyverno-cleanup-controller" cannot delete resource "configmaps" in API group "" in the namespace "default"
```

feat: create warning events on errors for cleanup policies

---

.github/workflows/helm-test.yaml

This PR fixes `helm-test` workflow  cache key.

fix: helm test workflow  cache key

---

cmd/reports-controller/main.go

Signed-off-by: damilola olayinka <holayinkajr@gmail.com>
This PR fixes the issue of audit-mode events not showing up.
```
default              8m48s       Warning   PolicyViolation           pod/badpod01                                                                                 kyverno-scan                                policy disallow-host-namespaces/host-namespaces fail: validation error: Sharing the host namespaces is disallowed. The fields spec.hostNetwork, spec.hostIPC, and spec.hostPID must be unset or set to `false`. rule host-namespaces failed at path /spec/hostIPC/                                                                                                                          8m48s        1       badpod01.173d0149202f920e
default              8m48s       Warning …
```

fix: run event generator to add audit mode events

---

.ko.yaml

This PR fixes cleanup-controller version not being embedded in the binary.

fix: cleanup-controller version

---

pkg/policy/allowed_vars_test.go
pkg/policy/validate.go

Signed-off-by: Zadkiel Aharonian <hello@zadkiel.fr>
Allow the use of context-fetched configmap metadata and data top level objects in policies.
https://kubernetes.slack.com/archives/C032MM2CH7X/p1674668051884029
/kind bug
Add `configmap.data`, `configmap.metadata` and `configmap.metadata.*` as allowed variables.
- Should I add additional tests for the metadata part?
- Are proof manifests needed if there is tests in the PR?

fix: allow configmap.data/configmap.metadata in policy validation

---

.golangci.yml

/kind cleanup
```
➜  kyverno git:(main) golangci-lint run -c .golangci.yml 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
```

chore: the linter `structcheck` `varcheck` and `deadcode` are deprecated (since v1.49.0)

---

charts/kyverno/README.md
charts/kyverno/values.yaml
config/install.yaml

`exceptionNamespace` is not an init-container flag, this PR fixes the issue.

fix: remove `exceptionNamespace` from init-container

---

pkg/background/common/resource.go
pkg/webhooks/resource/utils.go
test/conformance/kuttl/mutate/clusterpolicy/standard/existing/basic-delete/01-assert.yaml
test/conformance/kuttl/mutate/clusterpolicy/standard/existing/basic-delete/01-manifests.yaml
test/conformance/kuttl/mutate/clusterpolicy/standard/existing/basic-delete/02-delete-cm.yaml
test/conformance/kuttl/mutate/clusterpolicy/standard/existing/basic-delete/03-assert.yaml
test/conformance/kuttl/mutate/clusterpolicy/standard/existing/basic-delete/README.md
test/conformance/kuttl/mutate/clusterpolicy/standard/existing/basic-delete/cleanup.yaml
test/conformance/kuttl/mutate/clusterpolicy/standard/existing/temp/basic-delete/01-assert.yaml

>When a background (generate/mutateExisting) policy defines variables referring to admission request data on DELETE operation, these variables may not be available anymore if the resource is removed from the cluster.
This PR supports admission review variables in DELETE requests for background policies.
Closes https://github.com/kyverno/kyverno/issues/6189.
/1.10
/bug

fix: admission review variables for DELETE operations

---

pkg/webhooks/handlers/filter.go

This PR fixes exclude user names in configmap not working.

fix: exclude user names in configmap not working

---

pkg/engine/background.go
pkg/engine/engine.go
pkg/engine/generation.go
pkg/engine/imageVerify.go
pkg/engine/imageVerifyValidate.go
pkg/engine/imageVerify_test.go
pkg/engine/mutation.go
pkg/engine/mutation_test.go
pkg/engine/validation.go
pkg/engine/validation_test.go

This PR moves engine funcs to methods to stop passing all parameters to every func.

refactor: make funcs part of engine struct to reduce parameter passing

---

cmd/background-controller/main.go
cmd/cli/kubectl-kyverno/utils/common/common.go
cmd/kyverno/main.go
cmd/reports-controller/main.go
pkg/background/generate/generate.go
pkg/controllers/report/background/controller.go
pkg/controllers/report/utils/scanner.go
pkg/engine/api/contextloader.go
pkg/engine/api/engine.go
pkg/engine/background.go
pkg/engine/engine.go
pkg/engine/generation.go
pkg/engine/imageVerify.go
pkg/engine/imageVerifyValidate.go
pkg/engine/imageVerify_test.go
pkg/engine/internal/context.go
pkg/engine/jsonContext.go
pkg/engine/mutation.go
pkg/engine/mutation_test.go
pkg/engine/validation.go
pkg/engine/validation_test.go
pkg/policy/policy_controller.go
pkg/testrunner/scenario.go
pkg/webhooks/resource/fake.go
pkg/webhooks/resource/generation/generation.go
pkg/webhooks/resource/handlers.go
pkg/webhooks/resource/imageverification/handler.go
pkg/webhooks/resource/updaterequest.go
pkg/webhooks/resource/validation_test.go

This PR refactors context loading and engine methods:
- add `context.Context` where missing
- manage registry client in engine

refactor: context loading and engine methods

---

pkg/engine/utils.go
pkg/engine/utils_test.go

We filed a bug earlier today -- https://github.com/kyverno/kyverno/issues/6231 -- where we found a problem with some of our Mutating Policies. These policies of ours were basically tied to specific users and namespaces only:
```
- exclude:
resources: {}
generate:
clone: {}
match:
any:
- resources:
kinds:
- Pod
namespaces:
- user1-restricted
- resources:
kinds:
- Pod
subjects:
- kind: User
name: user1
resources: {}
```
(In case it's helpful, I also added the full exported yaml for this particular rule in `user1.yaml` as an attachment
[user1.yaml.txt](https://github.com/kyverno/kyverno/files/10669023/user1.yaml.txt))
However, we saw them being applied to completely unrelated Pods (and other kinds of Resources), such as an Ingress Controller. I think this is because the three calls to …

fix: do not pass dynamicConfig to matchesResourceDescriptionMatchHelper (#6231)

---

cmd/cli/kubectl-kyverno/apply/apply_command.go
cmd/cli/kubectl-kyverno/oci/oci_push.go
cmd/cli/kubectl-kyverno/test/test_command.go
cmd/kyverno/main.go
pkg/clients/dclient/utils.go
pkg/engine/apicall/apiCall_test.go
pkg/engine/attestation_test.go
pkg/engine/background.go
pkg/engine/engine.go
pkg/engine/forceMutate.go
pkg/engine/forceMutate_test.go
pkg/engine/generation.go
pkg/engine/imageVerify.go
pkg/engine/imageVerify_test.go
pkg/engine/internal/logging.go
pkg/engine/mutate/mutation_test.go
pkg/engine/mutate/patch/patchJSON6902_test.go
pkg/engine/mutate/patch/patchesUtils_test.go
pkg/engine/mutate/patch/strategicMergePatch_test.go
pkg/engine/mutate/patch/strategicPreprocessing_test.go
pkg/engine/mutation.go
pkg/engine/pattern/pattern_test.go
pkg/engine/validate/validate_test.go
pkg/engine/validation.go
pkg/engine/variables/evaluate_test.go
pkg/engine/variables/variables_test.go
pkg/engine/variables/vars_test.go
pkg/openapi/manager.go
pkg/openapi/manager_test.go
pkg/policy/validate_test.go

This PR improves engine logger management:
- adds helpers to add policy, resources, rules in the logger context
- uses helpers to create and propagate the logger

refactor: improve engine logger management

---

cmd/kyverno/main.go
pkg/utils/kube/crd.go

This PR uses client instead of discovery for sanity checks.
Will backport in 1.9.
Closes https://github.com/kyverno/kyverno/issues/6286

fix: use client instead of discovery for sanity checks

---

pkg/controllers/report/utils/events.go
pkg/engine/api/ruleresponse.go
pkg/engine/exceptions.go
pkg/event/events.go
pkg/webhooks/utils/event.go

This PR propagates exception in rule response instead of studying the error message to know if an exception occured and parse the message to get exception infos.

refactor: propagate exception in rule response

---

cmd/kyverno/main.go
go.mod
pkg/utils/kube/crd.go

fix: use client instead of discovery for sanity checks (cherry-pick #6296)

fix: use client instead of discovery for sanity checks (cherry-pick #6296)

---

pkg/userinfo/roleRef.go

This PR uses `labels.Everything()` in userinfo clusterroles matching (instead of `labels.NewSelector()`).

fix: use labels.Everything in userinfo clusterroles matching

---

pkg/utils/image/infos.go

This PR fixes a logger call where key/value are in the wrong order.

fix: logger key value in wrong order

---

test/conformance/kuttl/generate/policy/standard/clone/sync/pol-clone-sync-modify-source/01-assert.yaml
test/conformance/kuttl/generate/policy/standard/clone/sync/pol-clone-sync-modify-source/01-manifests.yaml
test/conformance/kuttl/generate/policy/standard/clone/sync/pol-clone-sync-modify-source/02-trigger.yaml
test/conformance/kuttl/generate/policy/standard/clone/sync/pol-clone-sync-modify-source/03-assert.yaml
test/conformance/kuttl/generate/policy/standard/clone/sync/pol-clone-sync-modify-source/04-modifysource.yaml
test/conformance/kuttl/generate/policy/standard/clone/sync/pol-clone-sync-modify-source/05-assert.yaml
test/conformance/kuttl/generate/policy/standard/clone/sync/pol-clone-sync-modify-source/README.md

This PR adds a kuttl test for https://github.com/kyverno/kyverno/issues/5277. Changes to the source should be synced to the downstream for a generate Policy (Namespaced), with sync, clone.

test: add the kuttl test pol-clone-sync-modify-source

---

pkg/controllers/policycache/controller.go

This PR fixes the panic while fetching the resource GVK via the client.
Closes https://github.com/kyverno/kyverno/issues/6417.
/1.9.1
/bug

fix: panic when fails to fetch resource GVK

---

charts/kyverno/README.md
charts/kyverno/README.md.gotmpl
charts/kyverno/templates/admission-controller/deployment.yaml
charts/kyverno/templates/admission-controller/servicemonitor.yaml
charts/kyverno/values.yaml
scripts/config/dev/kyverno.yaml

This PR refactors helm admission controller config:
- `serviceMonitor`
- `podSecurityContext`
- `tufRootMountPath`
- `sigstoreVolume`

refactor: helm admission controller config

---

pkg/utils/kube/kind.go
pkg/utils/kube/kind_test.go

This PR compiles a regex globally instead on every call.
It also supports parsing `*/*`.

fix: compile regex globally

---

pkg/webhooks/resource/validation/validation.go

Cherry-pick of https://github.com/kyverno/kyverno/pull/6363 on to `release-1.9`, because the automated cherry-pick in that PR failed.
- https://github.com/kyverno/kyverno/pull/6363
- https://github.com/kyverno/kyverno/issues/6315

fix: missing metrics for policies in audit mode (cherry-pick #6363)

---

pkg/autogen/autogen_test.go

This PR adds verbosity to the `pkg/autogen` unit tests.

fix: adding verbosity to the ./pkg/autogen unit tests

---

charts/kyverno/README.md
charts/kyverno/values.yaml

This PR removes obsolete `generatecontrollerExtraResources` from helm chart.

fix: remove obsolete generatecontrollerExtraResources from helm chart

---

charts/kyverno/README.md
charts/kyverno/templates/background-controller/serviceaccount.yaml
charts/kyverno/templates/cleanup-controller/serviceaccount.yaml
charts/kyverno/templates/reports-controller/serviceaccount.yaml
charts/kyverno/values.yaml

This PR adds annotations support for all service accounts in helm chart.

fix: add annotations support for all SA in helm chart

---

pkg/controllers/report/resource/controller.go

This PR uses GVR in reports resource controller.
This is needed when a policy targets multiple resources.

fix: use GVR in reports resource controller

---

pkg/engine/background.go
pkg/engine/mutation.go
pkg/engine/utils.go
pkg/engine/utils_test.go
pkg/engine/validation.go

This PR checks if resource is empty when matching.

fix: check if resource is empty when matching

---

pkg/clients/dclient/discovery.go
pkg/clients/dclient/fake.go
pkg/policycache/cache.go
pkg/policycache/test.go

This PR refactors our discovery client:
- removes the `FindResource` method

refactor: discovery client

---

.vscode/launch.json
api/kyverno/v1/clusterpolicy_types.go
api/kyverno/v1/policy_status.go
api/kyverno/v1/policy_types.go
api/kyverno/v2beta1/clusterpolicy_types.go
api/kyverno/v2beta1/policy_types.go
charts/kyverno/templates/crds/crds.yaml
config/crds/kyverno.io_clusterpolicies.yaml
config/crds/kyverno.io_policies.yaml
config/install-latest-testing.yaml
pkg/controllers/webhook/controller.go
pkg/webhooks/handlers/trace.go

This PR adds support for ready message.
```console
$ kubectl get cpol
NAME           BACKGROUND   VALIDATE ACTION   READY   AGE   MESSAGE
verify-image   false        enforce           True    32m   Ready
```

feat: add support for ready message

---

pkg/policy/mutate/validate.go

This PR fixes the auth validation for the mutate existing policy where it does not require `create` permission.
Closes https://github.com/kyverno/kyverno/issues/6681.
/1.10.0
/bug

fix: auth validation for mutate existing policies

---

pkg/utils/api/image.go

This PR allows an image to be not present when parsing a resource manifest.
Fixes #6128

fix: allow image to be not present

---

Makefile

This PR bumps default k8s version to v1.26.2.

chore: bump default k8s version to v1.26.2

---

test/conformance/kuttl/reports/background/verify-image-fail/01-pod.yaml
test/conformance/kuttl/reports/background/verify-image-fail/02-policy.yaml
test/conformance/kuttl/reports/background/verify-image-fail/03-bgscanr.yaml
test/conformance/kuttl/reports/background/verify-image-fail/README.md
test/conformance/kuttl/reports/background/verify-image-fail/bgscanr-assert.yaml
test/conformance/kuttl/reports/background/verify-image-fail/pod-assert.yaml
test/conformance/kuttl/reports/background/verify-image-fail/pod.yaml
test/conformance/kuttl/reports/background/verify-image-fail/policy-assert.yaml
test/conformance/kuttl/reports/background/verify-image-fail/policy.yaml
test/conformance/kuttl/reports/background/verify-image-pass/01-pod.yaml
test/conformance/kuttl/reports/background/verify-image-pass/02-policy.yaml
test/conformance/kuttl/reports/background/verify-image-pass/03-bgscanr.yaml
test/conformance/kuttl/reports/background/verify-image-pass/README.md
test/conformance/kuttl/reports/background/verify-image-pass/bgscanr-assert.yaml
test/conformance/kuttl/reports/background/verify-image-pass/pod-assert.yaml
test/conformance/kuttl/reports/background/verify-image-pass/pod.yaml
test/conformance/kuttl/reports/background/verify-image-pass/policy-assert.yaml
test/conformance/kuttl/reports/background/verify-image-pass/policy.yaml

This PR adds a kuttl test for bgscan report with image verification rule passing.
This is to make sure the reports controller works as expected.

test: bgscan report with image verification rule passing

---

pkg/engine/api/engineresponse.go
pkg/engine/api/policyresponse.go
pkg/engine/api/stats.go
pkg/engine/background.go
pkg/engine/engine.go
pkg/engine/generation.go
pkg/engine/imageVerify.go
pkg/engine/internal/response.go
pkg/engine/mutation.go
pkg/engine/validation.go
pkg/utils/annotations_test.go
pkg/webhooks/utils/block_test.go

This PR refactors engine responses:
- moves execution stats from policy response to engine response
- adds a `Done()` method to update the processing time
- adds `WithPolicyResponse()` and `WithPatchedResource()` making engine response immutable
- changes private handlers to return a policy response instead of an engine response

refactor: engine responses

---

pkg/clients/dclient/discovery.go
pkg/clients/dclient/utils.go
pkg/clients/dclient/utils_test.go

This PR stops filtering on group when service based apiservice discovery fails.
When kyverno is installed with a wildcard policy and something goes wrong, the `TokenRequest` will not work for service based apiservice and the cluster won't recover.
I don't think it makes sense to apply the group filtering, the exception should apply in all cases.
Fixes https://github.com/kyverno/kyverno/issues/6558

fix: don't filter on group when service based apiservice discovery fails

---

test/conformance/kuttl/autogen/deployment-statefulset-job/policy-assert.yaml
test/conformance/kuttl/autogen/deployment-statefulset-job/policy.yaml
test/conformance/kuttl/autogen/none/policy-assert.yaml
test/conformance/kuttl/autogen/none/policy.yaml
test/conformance/kuttl/autogen/only-cronjob/policy-assert.yaml
test/conformance/kuttl/autogen/only-cronjob/policy.yaml
test/conformance/kuttl/autogen/only-deployment/policy-assert.yaml
test/conformance/kuttl/autogen/only-deployment/policy.yaml
test/conformance/kuttl/autogen/should-autogen/policy-assert.yaml
test/conformance/kuttl/autogen/should-autogen/policy.yaml
test/conformance/kuttl/autogen/should-not-autogen/policy-assert.yaml
test/conformance/kuttl/autogen/should-not-autogen/policy.yaml
test/conformance/kuttl/reports/admission/test-report-admission-mode/01-manifests.yaml
test/conformance/kuttl/reports/background/background-scan-report-deletion/policy.yaml
test/conformance/kuttl/reports/background/test-report-background-mode/policy-assert.yaml
test/conformance/kuttl/reports/background/test-report-background-mode/policy.yaml
test/conformance/kuttl/validate/clusterpolicy/standard/audit/background-match-clusterRoles/02-errors.yaml
test/conformance/kuttl/validate/clusterpolicy/standard/audit/background-match-clusterRoles/manifests.yaml
test/conformance/kuttl/validate/clusterpolicy/standard/audit/background-match-roles/02-errors.yaml
test/conformance/kuttl/validate/clusterpolicy/standard/audit/background-match-roles/manifests.yaml
test/conformance/kuttl/validate/clusterpolicy/standard/audit/background-vars-roles/02-errors.yaml
test/conformance/kuttl/validate/clusterpolicy/standard/audit/background-vars-roles/manifests.yaml
test/conformance/kuttl/validate/clusterpolicy/standard/audit/background-vars-serviceAccountName/02-errors.yaml
test/conformance/kuttl/validate/clusterpolicy/standard/audit/background-vars-serviceAccountName/manifests.yaml
test/conformance/kuttl/validate/clusterpolicy/standard/audit/background-vars-userInfo/02-errors.yaml
test/conformance/kuttl/validate/clusterpolicy/standard/audit/background-vars-userInfo/manifests.yaml
test/conformance/kuttl/validate/clusterpolicy/standard/audit/configmap-context-lookup/01-manifests.yaml

This PR uses `Audit` instead of `audit` in kuttl tests.

chore: use Audit instead of audit in kuttl tests

---

CHANGELOG.md
charts/kyverno/README.md
charts/kyverno/values.yaml
cmd/background-controller/main.go
cmd/cleanup-controller/main.go
cmd/cli/kubectl-kyverno/utils/common/common.go
cmd/kyverno/main.go
cmd/reports-controller/main.go
config/install-latest-testing.yaml
pkg/config/config.go
pkg/controllers/generic/webhook/controller.go
pkg/controllers/webhook/controller.go
pkg/engine/handlers/validation/validate_manifest_test.go
pkg/engine/image_verify_test.go
pkg/utils/api/image_test.go
pkg/utils/image/infos_test.go
pkg/webhooks/resource/fake.go
pkg/webhooks/resource/validation_test.go

This PR adds a flag to skip resource filters in reports controller.
By default the reports controller will scan all resources, whatever is configured in resource filters in the config map.
Setting the flag to false will enable resource filters in the reports controller.
Fixes https://github.com/kyverno/kyverno/issues/5028

feat: add flag to skip resource filters in reports controller

---

pkg/background/generate/utils.go
test/conformance/kuttl/generate/clusterpolicy/standard/clone/sync/cpol-clone-sync-delete-trigger/06-assert.yaml
test/conformance/kuttl/generate/policy/standard/clone/sync/pol-clone-sync-delete-trigger/06-assert.yaml

When a trigger is deleted for a generate policy with clone and sync, the downstream should be deleted while the source resource retains.
Closes https://github.com/kyverno/kyverno/issues/6831.
/1.10.0
/bug

fix: preserve source on trigger deletion for a generate policy with clone, sync

---

.github/workflows/conformance.yaml

This PR adds k8s 1.27 to the test grid.

chore: add k8s 1.27 to the test grid

---

pkg/engine/api/context.go
pkg/engine/apicall/apiCall.go
pkg/engine/apicall/apiCall_test.go

This PR fixes context in api call.
It should not be part of the struct but the first argument in the method call.

fix: context in api call

---

cmd/internal/flag.go
cmd/reports-controller/main.go

This PR makes flag default values configurable (QPS / Burst in reports controller for example).

fix: make flag default values configurable

---

.github/workflows/conformance.yaml

This PR bumps kind image to 1.27.1.

chore: bump kind image to 1.27.1

---

pkg/engine/forceMutate.go
pkg/engine/handlers/mutation/common.go
pkg/engine/mutate/mutation.go
pkg/engine/mutate/mutation_test.go
pkg/engine/mutate/patch/patchJSON6902.go
pkg/engine/mutate/patch/patchJSON6902_test.go
pkg/engine/mutate/patch/patches.go
pkg/engine/mutate/patch/patchesUtils.go
pkg/engine/mutate/patch/patchesUtils_test.go
pkg/engine/mutate/patch/strategicMergePatch.go
pkg/engine/mutate/patch/strategicMergePatch_test.go

This PR refactors engine patchers:
- decouples the creation of the patcher and the `Patch` method invocation
- uses more typed json patches
- reduce the adherence to engine api in return types

refactor: engine patchers

---

.github/actions/kyverno-wait-ready/action.yaml

This PR fixes flaky github action when waiting for ready pods (we need to exclude jobs).

fix: flaky github action

---

cmd/cli/kubectl-kyverno/apply/apply_command.go
cmd/cli/kubectl-kyverno/apply/report.go
cmd/cli/kubectl-kyverno/apply/report_test.go
cmd/cli/kubectl-kyverno/test/test.go
cmd/cli/kubectl-kyverno/utils/common/common.go
pkg/background/generate/generate.go
pkg/controllers/report/utils/events.go
pkg/engine/api/engineresponse.go
pkg/engine/api/engineresponse_test.go
pkg/engine/metrics.go
pkg/event/events.go
pkg/utils/annotations.go
pkg/utils/report/results.go
pkg/webhooks/resource/utils.go
pkg/webhooks/utils/block.go
pkg/webhooks/utils/error.go
pkg/webhooks/utils/warning.go
pkg/webhooks/utils/warning_test.go

This PR refactors engine response policy (use a getter instead of having a public field).

refactor: engine response policy

---

go.mod
go.sum

chore(deps): bump github.com/docker/docker from 23.0.2+incompatible to 23.0.3+incompatible #6787 (cherry-pick #6787)

---

pkg/policy/policy_controller.go

This PR updates the periodic reconciliation message for the background controller.

chore: update background scan logging messages

---

cmd/cleanup-controller/handlers/cleanup/handlers.go

This PR fixes cleanup controller metrics name (missing `kyverno_` prefix).

fix: cleanup controller metrics name

---

pkg/webhooks/utils/block.go
pkg/webhooks/utils/block_test.go

Fixed the error message.
Closes #7159 
/kind bug
```
metadata:
name: disallow-latest-tag
annotations:
policies.kyverno.io/title: Disallow Latest Tag
policies.kyverno.io/category: Best Practices
policies.kyverno.io/minversion: 1.6.0
The ':latest' tag is mutable and can lead to unexpected errors if the
image changes. A best practice is to use an immutable tag that maps to
a specific version of an application Pod. This policy validates that the image
specifies a tag and that it is not called `latest`.
spec:
rules:
- name: require-image-tag
match:
any:
- resources:
kinds:
- Pod
validate: …
```

[Bug] Enforce message wrong

---

charts/kyverno/README.md
charts/kyverno/values.yaml
config/install-latest-testing.yaml

This PR does not exclude kube-system service accounts by default.

fix: do not exclude kube-system service accounts by default

---

pkg/utils/api/image.go

The image validation used in the mutation webhook prints the failing image without quotes. In cases where the image name contains a whitespace, the error is hard to read, as the whitespace is not visible.
/milestone v1.9.3
/kind cleanup
The image is surrounded with single quotes to make the boundaries if the image string visible.

fix: quote image in ImageInfo validation error

---

pkg/controllers/webhook/controller.go

This PR fixes auto update webhooks not configuring fail endpoint.
Fixes https://github.com/kyverno/kyverno/issues/7194

fix: auto update webhooks not configuring fail endpoint

---

pkg/pss/evaluate.go
pkg/pss/evaluate_test.go

This PR builds a latest version check map in order to apply the `latest` when it is defined in the rule, otherwise whatever the first version of check is applied. i.e., when a check has two versions of implementation, say 1.10 and 1.19, 1.10 will be applied as it is the first check in the array.
Closes https://github.com/kyverno/kyverno/issues/7260.
/1.10.0
/bug

fix: PSa latest version check

---

charts/kyverno/templates/admission-controller/_helpers.tpl
charts/kyverno/templates/background-controller/_helpers.tpl
charts/kyverno/templates/cleanup-controller/_helpers.tpl
charts/kyverno/templates/rbac/_helpers.tpl
charts/kyverno/templates/reports-controller/_helpers.tpl

This PR uses `kyverno.fullname` template to create cluster roles instead of `.Release.name`.
Fixes https://github.com/kyverno/kyverno/issues/7246

fix: do not use release name in chart

---

cmd/cleanup-controller/server.go
pkg/webhooks/server.go

This PR fixes tls cipher suites.

fix: tls cipher suites

---

api/kyverno/v1/spec_types.go
api/kyverno/v2beta1/spec_types.go

Remove validation checks for `generateExistingOnPolicyUpdate` as this breaks backwards compatibility for a v1 declaration.
Fixes https://github.com/kyverno/kyverno/issues/7319
1.10
/kind cleanup

remove validation for deprecated field generateExistingOnPolicyUpdate

---

charts/kyverno/templates/background-controller/deployment.yaml
charts/kyverno/templates/cleanup-controller/deployment.yaml
charts/kyverno/templates/reports-controller/deployment.yaml
config/install-latest-testing.yaml

This PR fixes config map name in helm chart when the chart is deployed with a specific name.
The `INIT_CONFIG` env var was not set.
Fixes https://github.com/kyverno/kyverno/issues/7335

fix: config map name in helm chart

---

test/conformance/kuttl/mutate/refactor/add-external-secret-prefix/03-sleep.yaml

This PR tries to fix a flaky kuttl test (`add-external-secret-prefix`).

fix: flaky kuttl test add-external-secret-prefix

---

CHANGELOG.md
cmd/internal/flag.go
cmd/internal/setup.go

This PR deprecates `imageSignatureRepository` flag.

chore: deprecate imageSignatureRepository flag

---

charts/kyverno/README.md
charts/kyverno/templates/admission-controller/deployment.yaml
charts/kyverno/templates/background-controller/deployment.yaml
charts/kyverno/templates/cleanup-controller/deployment.yaml
charts/kyverno/templates/reports-controller/deployment.yaml
charts/kyverno/values.yaml
config/install-latest-testing.yaml

This PR adds missing `extraEnvVars` in helm chart (background, cleanup and reports controllers).
Fixes https://github.com/kyverno/kyverno/issues/7402

fix: missing extraEnvVars in helm chart

---

pkg/engine/engine.go

This PR adds config exclusions in the engine (currently it's only implemented in the admission chain).

feat: add config exclusions in the engine

---

pkg/engine/handlers/mutation/mutate_image.go
pkg/engine/image_verify_test.go
pkg/engine/internal/imageverifier.go

This PR stops recording json patches in rule responses.
This one addresses image verifier.

fix: stop recording json patches in rule responses (part 2)

---

charts/kyverno/templates/admission-controller/deployment.yaml
config/install-latest-testing.yaml

Documentation and other template suggests anti affinity be enabled with `antiAffinity.enabled` instead of `antiAffinity.enable`. 
/kind bug
This fixes a typo in the helm chart template for the admission controller when enabling `antiAffinity` and aligns the template with the other controllers.

fixed typo in admission controller chart template

---

pkg/engine/mutate/mutation_test.go
pkg/engine/mutate/testdata/endpoints.yaml

This PR removes json patches from rule response in tests.

refactor: remove json patches from rule response in tests

---

api/kyverno/v1/rule_types.go
api/kyverno/v2beta1/rule_types.go
charts/kyverno/templates/crds/crds.yaml
config/crds/kyverno.io_clusterpolicies.yaml
config/crds/kyverno.io_policies.yaml
config/install-latest-testing.yaml

This PR fixes rule name not required in the crd schema.
Lesson learned, if a field is marked with `omitempty` it CAN'T be required, makes sense i guess.

fix: rule name not required in the crd schema

---

pkg/engine/handlers/mutation/load_targets.go

When loading the mutate target resource with variables defined, the background controller panics if the variable is resolved to nil. This PR fixes the issue.
Closes https://github.com/kyverno/kyverno/issues/7459.

fix: background controller panics during variables substitution

---

cmd/cli/kubectl-kyverno/utils/store/contextloader.go
pkg/engine/api/contextloader.go
pkg/engine/test/contextloader.go

This PR uses RawClient in context loader.

fix: use RawClient in context loader

---

cmd/cli/kubectl-kyverno/utils/common/common.go
cmd/cli/kubectl-kyverno/utils/common/kyverno_policies_types.go
cmd/cli/kubectl-kyverno/utils/store/contextloader.go
cmd/internal/engine.go
pkg/engine/adapters/rclient.go
pkg/engine/api/client.go
pkg/engine/api/context.go
pkg/engine/api/contextloader.go
pkg/engine/context/evaluate.go
pkg/engine/engine.go
pkg/engine/image_verify_test.go
pkg/engine/mutation_test.go
pkg/engine/test/contextloader.go
pkg/engine/validation_test.go
pkg/webhooks/resource/fake.go
pkg/webhooks/resource/validation_test.go

This PR introduces engine image data client interface.
This allows easily mocking the client responsible for getting image data.

refactor: introduce engine image data client interface

---

pkg/policy/policy_controller.go

Updated the message to the level 4 log and removed err that originated from ApplyBackgroundChecks.
Closes #7521 .
kind bug

Updated the message to the level4log and removed err that originated from ApplyBackgroundChecks.

---

pkg/controllers/report/utils/scanner.go

fix: background image verification not working (cherry-pick #7564)

fix: background image verification not working (cherry-pick #7564)

---

cmd/internal/maxprocs.go

This PR makes configuring max procs not exit in case of error.

fix: make configuring max procs not exit in case of error

---

charts/kyverno/templates/cleanup-controller/deployment.yaml
config/install-latest-testing.yaml

This PR fixes service account name env var defined twice.

fix: service account name env var defined twice

---

cmd/cleanup-controller/main.go
cmd/cleanup-controller/server.go
cmd/kyverno/main.go
pkg/tls/renewer.go
pkg/utils/runtime/utils.go
pkg/webhooks/handlers/probe.go

This PR stops using a lister in tls renewer.

fix: stop using lister in tls renewer

---

pkg/validation/policy/background.go

Error messages corresponding to `rule.ExcludeResources.Any` and `rule.ExcludeResources.All` are written as "invalid variable used at path: spec/rules[%d]/exclude/**all**[%d]/%s" and "invalid variable used at path: spec/rules[%d]/exclude/**any**[%d]/%s", respectively.
The PR swaps the word "any" and "all".
Related PR: #2451 
/kind cleanup
```yaml
metadata:
name: disallow-privileged-containers
spec:
rules:
- name: privileged-containers
match:
any:
- resources:
kinds:
- Pod
exclude:
all:
- resources:
kinds:
- BANANA
- subjects:
- kind: Group
name: "system:masters"
validate:
pattern:
spec:
=(ephemeralContainers):
- =(securityContext):
=(privileged): "false"
=(initContainers):
- =(securityContext):
=(privileged): …
```

fix: Swap any/all in the error message.

---

.github/workflows/release.yaml

This PR fixes the goreleaser version to 1.8.2 due to https://github.com/kyverno/kyverno/actions/runs/5409052815/jobs/9829975770.

fix goreleaser to 1.8.2

---

.github/workflows/images-publish.yaml

This PR uses github token instead of pat.
It also reduces the permissions at the workflow level.

chore: use github token instead of pat

---

cmd/cli/kubectl-kyverno/test/test_command.go

Running `kyverno test --fail-only <target>` right now always return `0` even if there is a failed test. This fixes that behaviour and makes the command return `0` or `1` depending on the existance of failed tests
N/A
/kind bug
This is a bug fix so there are no proposed changes outside of the code included in the PR
There are no functional changes in the code or behaviour of any section of the application, however, the behaviour can be tested by comparing the old result of this command (with failed tests):
```shell
$ old-kyverno test tests `--fail-only`
...
Test Summary: 1 out of 39 tests failed
$ echo $?
0
```
```shell
$ new-kyverno test tests `--fail-only`
...
Test Summary: 1 out of 39 tests failed
$ echo $?
1
```
Whereas not using `--fail-only` behaves as expected:
```shell
$kyverno …
```

fix: make `test --fail-only` return 1 if there are failed tests

---

pkg/notary/notary.go
pkg/notary/notary_test.go
pkg/notary/registry.go
pkg/notary/repository.go
pkg/notary/repository_test.go

The gcr remote package has an option called [reuse](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/remote#Reuse) which takes a Puller or Pusher and reuses it for remote interactions rather than starting from a clean slate.
While gcr crane doesn't have it. This PR replaces all gcr crane methods with gcr remote equivalents.
This PR, in theory, should make verification faster.

Replaced gcr crane with gcr remote

---

cmd/cli/kubectl-kyverno/utils/common/common.go

`kyverno apply` can fail (exit code > 0) without dumping any information for the user (without the report flag).
If apply exits > 0 I would expect that I get the reason why the command failed. The error is also not visible with an increased verbosity. That said the errors are visible in the reports mode.
However I would expect to see errors immediately if a command exits > 0 without the need of supplying flags to actually see the problem. (Also reports contain a lot more information while I only want to see errors.)
For failed policies the errors are actually dumped to stdout but that's not the case for errors. 
1. kyverno apply does not dump errors to stdout but apply actually exits > 0 if error count is > 0.
Its' pretty hard to find the cause with this behavior.
```
cat resources | …
```

fix(kubectl-kyverno): dump error validation response message

---

pkg/controllers/report/background/controller.go
pkg/controllers/report/resource/controller.go
pkg/controllers/report/utils/utils.go

Both background scan controller and resource report controller implement the functionality of fetching Policies/ClusterPolicies. Therefore, I moved these functions to utils.
/kind cleanup

Move fetchClusterPolicies() and fetchPolicies() to utils

---

cmd/cli/kubectl-kyverno/create/command.go
cmd/cli/kubectl-kyverno/create/templates/templates.go
cmd/cli/kubectl-kyverno/create/templates/test.yaml
cmd/cli/kubectl-kyverno/create/test/command.go
cmd/cli/kubectl-kyverno/main.go

This PR adds a `create test` cli command.
```
Create a Kyverno test file.
Usage:
kyverno create test [flags]
Examples:
kyverno create test -p policy.yaml -r resource.yaml -f values.yaml --pass policy-name,rule-name,resource-name,resource-namespace,resource-kind
Flags:
--fail fail          Expected fail results
-h, --help               help for test
-n, --name string        Test name (default "test-name")
-o, --output string      Output path (uses standard console output if not set)
--pass pass          Expected pass results
-p, --policy strings     List of policy files
-r, --resource strings   List of resource files
--skip skip          Expected skip results
-f, --values string      Values file
```
Using it with `kyverno create test -p policy.yaml -r resource.yaml -f values.yaml --pass …

feat: add `create test` cli command

---

cmd/cli/kubectl-kyverno/create/command.go
cmd/cli/kubectl-kyverno/create/templates/templates.go
cmd/cli/kubectl-kyverno/create/templates/user-info.yaml
cmd/cli/kubectl-kyverno/create/userinfo/command.go

This PR adds a `create user-info` cli command.
```
Create a Kyverno user-info file.
Usage:
kyverno create user-info [flags]
Examples:
kyverno create user-info -u molybdenum@somecorp.com -g basic-user -c admin
Flags:
-c, --cluster-role strings   Cluster role
-g, --group strings          Group
-h, --help                   help for user-info
-o, --output string          Output path (uses standard console output if not set)
-r, --role strings           Role
-u, --username string        User name
```
Example with `create user-info -u molybdenum@somecorp.com -g basic-user -c admin`:
```yaml
roles:
clusterRoles:
- admin
userInfo:
username: molybdenum@somecorp.com
groups:
- basic-user
```

feat: add `create user-info` cli command

---

pkg/validation/policy/validate.go
pkg/validation/policy/validate_test.go

Signed-off-by: Vishal Choudhary <sendtovishalchoudhary@gmail.com>
While applying the following policy
```yaml
metadata:
name: check-images     
spec:
rules:
- name: call-aws-signer-extension
match:
any:
- resources:
namespaces:
- test-notation
kinds:
- Pod
context:
- name: response
apiCall:
method: POST
data:
- key: imagesInfo
value: "{{images}}"
service:
url: https://svc.kyverno-notation-aws/checkimages
caBundle: |-
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
validate:
message: "not allowed"
deny:
conditions:
all:
- key: "{{ response.verified }}"
operator: EQUALS
value: false
```
I encountered the following error
```bash
Error from server: error when creating …
```

feat: add `images` to allowed variables in substitution

---

pkg/event/events.go
pkg/webhooks/utils/event.go

Initially, the created pods have no name when ReplicaSet uses its pod template to create them. As a result, we check the resource name in the engine response to prevent creating events for empty resource names.
Closes #7497 
/kind bug
```
metadata:
name: check-image
spec:
rules:
- name: check-image
match:
any:
- resources:
kinds:
- Pod
verifyImages:
- imageReferences:
- "docker.io/mariamfahmy98/busybox*"
attestors:
- count: 1
entries:
- keys:
publicKeys: |-
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfGWKeHwlXVtkBPIYxal5HYUfqvvq
y0xdr/txWrbylYt+lFI61ioTs0C0a3mPMfdGOO5wtYXw7kfGL5+54HUElQ==
-----END PUBLIC KEY----- …
```

fix: skip creating event for an empty resource name

---

pkg/validation/policy/validate.go

One of Kyvernos fuzzers found a way to trigger the type confusions in the modified code in this PR. This PR fixes that. 
Found by OSS-Fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60714
/kind bug

fix type confusion in policy validation

---

.nancy-ignore

This PR adds `golang/github.com/tektoncd/pipeline@v0.44.0` to nancy-ignore file.
Related [Nancy is failing because of tektoncd/pipeline@v0.44.0](https://github.com/kyverno/kyverno/issues/7845).

fix: add tekton/pipeline to nancy ignore list

---

pkg/validation/policy/validate.go

OSS-Fuzz has found an issue whereby an action is an "audit" but a key does not exist for it in the `action` map in `validateNamespaces`.
/kind bug
This PR adds a check for whether it is valid at all. Return an error if it is not valid.

policy validation: fix assignment to entry in nil map

---

pkg/engine/context/deferred.go
pkg/engine/context/deferred_test.go
pkg/engine/factories/contextloaderfactory.go

Cherry-pick https://github.com/kyverno/kyverno/pull/7834.
* Added error message to deferred loader on API call failure
* Small change in error message
---------

Added log message for API call failures (#7834), cherry picked

---

pkg/background/generate/generate.go
pkg/background/mutate/mutate.go
pkg/clients/dclient/client.go
pkg/clients/dclient/client_test.go
pkg/event/action.go
pkg/event/controller.go
pkg/event/events.go
pkg/event/info.go
pkg/event/recorder.go
pkg/policy/policy_controller.go
pkg/webhooks/resource/generation/handler.go
pkg/webhooks/resource/updaterequest.go
test/conformance/kuttl/background-only/cluster-policy/no-admission-event/admission-event.yaml
test/conformance/kuttl/background-only/cluster-policy/no-admission-event/background-event.yaml
test/conformance/kuttl/background-only/policy/no-admission-event/admission-event.yaml
test/conformance/kuttl/background-only/policy/no-admission-event/background-event.yaml
test/conformance/kuttl/events/clusterpolicy/generate-events-upon-successful-generation/policy-event.yaml
test/conformance/kuttl/events/clusterpolicy/generate-events-upon-successful-generation/resource-event.yaml
test/conformance/kuttl/events/clusterpolicy/generate-events-upon-successful-mutation/event-assert.yaml
test/conformance/kuttl/events/clusterpolicy/no-events-upon-fail-generation/event.yaml
test/conformance/kuttl/events/clusterpolicy/no-events-upon-skip-generation/event.yaml
test/conformance/kuttl/events/policy/policy-applied/event-assert.yaml
test/conformance/kuttl/events/policy/policy-violation/event-assert.yaml
test/conformance/kuttl/exceptions/events-creation/05-assert.yaml

Move all Events to the events.k8s.io/v1 group and version.
Fixes #7471
/kind feature
```
metadata:
name: require-ns-purpose-label
spec:
rules:
- name: require-ns-purpose-label
match:
any:
- resources:
kinds:
- Namespace
validate:
message: "You must have label `purpose` with value `production` set on all new namespaces."
pattern:
metadata:
labels:
purpose: production
```
2. `kubectl create ns ns-1`
3. `kubectl get events.events.k8s.io`:
```
2m1s        Warning   PolicyViolation           clusterpolicy/require-ns-purpose-label   Namespace ns-1: [require-ns-purpose-label] fail (blocked); validation error: You must have label  with value  set on all new namespaces. rule …
```

feat: migrate to events.k8s.io/v1

---

cmd/cli/kubectl-kyverno/apply/report.go
cmd/cli/kubectl-kyverno/apply/report_test.go
pkg/utils/report/results.go

* test: add test for severity and category
Signed-off-by: Vishal Choudhary <sendtovishalchoudhary@gmail.com>
* fix: add severity and category to cpol report
Signed-off-by: Vishal Choudhary <sendtovishalchoudhary@gmail.com>
* refactor: reuse report util SeverityFromString
Signed-off-by: Vishal Choudhary <sendtovishalchoudhary@gmail.com>
---------
Signed-off-by: Vishal Choudhary <sendtovishalchoudhary@gmail.com>
cherry pick: #7828

bug: add severity and category in cluster policy report (#7828)

---

api/kyverno/constants.go
pkg/tls/renewer.go
pkg/tls/utils.go

This PR moves `cert.kyverno.io/managed-by` label in constants.

chore: move cert.kyverno.io/managed-by label in constants

---

api/kyverno/constants.go
pkg/engine/context/resolvers/constants.go
pkg/engine/context/resolvers/resolvers_test.go
pkg/engine/context/resolvers/utils.go
pkg/engine/context/resolvers/utils_test.go

This PR moves `cache.kyverno.io/enabled` label in the api packge.

chore: move cache enabled label

---

.vscode/launch.json

This PR fixes cleanup controller debug in vscode (`KYVERNO_SVC` was missing).

chore: fix cleanup controller debug in vscode

---

policy.yaml
resource.yaml

- adds `policies.kyverno.io/category` and `policies.kyverno.io/severity` to `ClusterPolicyReport`
- updates tests to check for the above mentioned fields
Closes #8000 
N/A
/kind bug
Added changes to add severity and category fields in policy report generated by CLI
Create this ClusterPolicy locally and also apply to a cluster.
```yaml
metadata:
annotations:
kyverno.io/kubernetes-version: 1.22-1.23
kyverno.io/kyverno-version: 1.6.0
policies.kyverno.io/category: Pod Security Standards (Restricted)
policies.kyverno.io/description: Adding capabilities other than `NET_BIND_SERVICE`
is disallowed. In addition, all containers must explicitly drop `ALL` capabilities.
policies.kyverno.io/minversion: 1.6.0 …
```

Add category and severity fields in cli policy report

---

.github/workflows/conformance.yaml

This PR adds k8s 1.28 testing.

chore: add k8s 1.28 testing

---

.github/workflows/conformance.yaml

This PR removes tests for k8s v1.24

chore: remove tests for k8s v1.24

---

Makefile

This PR uses k8s 1.27 by default.

chore: use k8s 1.27 by default

---

pkg/tls/keypair.go

This PR fixes missing server name without port to generated certificate.
Fixes #7924

fix: server name without port to generated certificate

---

api/kyverno/v1/common_types.go
api/kyverno/v1/zz_generated.deepcopy.go
charts/kyverno/templates/crds/crds.yaml
config/crds/kyverno.io_clusterpolicies.yaml
config/crds/kyverno.io_policies.yaml
config/install-latest-testing.yaml
docs/user/crd/index.html
pkg/client/applyconfigurations/kyverno/v1/cel.go

This PR is to bump the fields defined in `validate.cel` subrule to v1beta1.
/kind cleanup
```
type CEL struct {
// Expressions is a list of CELExpression types.
Expressions []v1beta1.Validation `json:"expressions,omitempty" yaml:"expressions,omitempty"`
// ParamKind is a tuple of Group Kind and Version.
// +optional
ParamKind *v1beta1.ParamKind `json:"paramKind,omitempty" yaml:"paramKind,omitempty"`
// ParamRef references a parameter resource.
// +optional
ParamRef *v1beta1.ParamRef `json:"paramRef,omitempty" yaml:"paramRef,omitempty"`
// AuditAnnotations contains CEL expressions which are used to produce audit annotations for the audit event of the API request.
// +optional
AuditAnnotations []v1beta1.AuditAnnotation `json:"auditAnnotations,omitempty" …
```

chore: replace usage of v1alpha1 with v1beta1 for cel subrule

---

cmd/cli/kubectl-kyverno/main.go

This PR stops hiding flags in the cli.
Fixes https://github.com/kyverno/kyverno/issues/5334

fix: stop hiding flags in the cli

---

api/kyverno/v1/common_types.go
api/kyverno/v1/zz_generated.deepcopy.go
charts/kyverno/templates/crds/crds.yaml
config/crds/kyverno.io_clusterpolicies.yaml
config/crds/kyverno.io_policies.yaml
config/install-latest-testing.yaml
docs/user/crd/index.html
pkg/client/applyconfigurations/kyverno/v1/cel.go

This PR is to revert the changes of bumping v1alpha1 to v1beta1 since there are no differences between the two versions using client-go 1.28
/kind cleanup

chore: replace usage of v1beta1 with v1alpha1 for cel subrule

---

cmd/cli/kubectl-kyverno/utils/common/kyverno_policies_types.go
pkg/engine/handlers/validation/validate_cel.go

This PR is to check if the client is set in CEL validations.
Closes #8097
/kind bug
1. Create a policy that uses `validate.cel` subrule as follows:
```
metadata:
name: check-deployment-replicas
spec:
rules:
- name: deployment-replicas
match:
any:
- resources:
kinds:
- Deployment
validate:
cel:
expressions:
- expression: "object.spec.replicas <= 3"
message: "Deployment spec.replicas must be less than 3."
```
2. Create a deployment:
```
metadata:
name: deployment-test
spec:
replicas: 1
selector:
matchLabels:
app: app
template:
metadata:
labels:
app: app
spec:
containers:
- name: container2
image: nginx
```
3. Apply the policy on the …

fix: check if client is set in CEL validations

---

pkg/validation/policy/validate.go

This PR fixes a misleading warning about matching on status.
Fixes #6912

fix: misleading warning about matching on status

---

charts/kyverno-policies/.helmignore
charts/kyverno/.helmignore

This PR adds .helmignore to .helmignore.
See https://helm.sh/docs/chart_template_guide/helm_ignore_file/

chore: add .helmignore to .helmignore

---

.vscode/launch.json

This PR modifies the `.vscode/launch.json` to add the following flags in the admission controller:
```
--caSecretName=kyverno-svc.kyverno.svc.kyverno-tls-ca
--tlsSecretName=kyverno-svc.kyverno.svc.kyverno-tls-pair
```
Otherwise, it will throw an error:
```
I0828 19:47:34.077080  598751 run.go:112] webhook-controller/worker "msg"="Dropping request from the queue" "error"="secret \"\" not found" "id"=0 "obj"="kyverno-resource-mutating-webhook-cfg"
I0828 19:47:34.077176  598751 run.go:112] webhook-controller/worker "msg"="Dropping request from the queue" "error"="secret \"\" not found" "id"=1 "obj"="kyverno-resource-validating-webhook-cfg"
E0828 19:47:34.108512  598751 renewer.go:94] tls "msg"="failed to read CA" "error"="resource name may not be empty" 
I0828 19:47:34.108598  598751 …
```

fix: vscode debug config

---

pkg/tls/keypair.go
pkg/tls/log.go
pkg/tls/renewer.go
pkg/tls/utils.go

This PR removes logger from tls package to reduce dependencies.

refactor: remove logger from tls package

---

cmd/cli/kubectl-kyverno/test/test.go

This PR adds support for fully-qualified file paths in cli test command.
Fixes #2315

fix: support fully-qualified file paths in cli test command

---

.github/workflows/cli.yaml
.github/workflows/codecov.yaml
.github/workflows/conformance.yaml
.github/workflows/fossa.yml
.github/workflows/helm-release.yaml
.github/workflows/helm-test.yaml
.github/workflows/images-build.yaml
.github/workflows/images-publish.yaml
.github/workflows/lint.yaml
.github/workflows/nancy.yaml
.github/workflows/release.yaml
.github/workflows/sonarcloud.yaml
.github/workflows/tests.yaml
.github/workflows/verify-codegen.yaml

This PR increases `setup-build-env` timeout (looks like it was too small in some cases like when the cache is invalidated).

chore: increase setup-build-env timeout

---

go.mod
go.sum

This PR reverts rekor upgrade.
It requires go 1.21 and we're not ready for that (ci workflows need to be updated, etc).

fix: revert rekor upgrade

---

pkg/engine/image_verify_test.go
pkg/imageverifycache/client.go

`Wait()` blocks until all buffered writes have been applied. This ensures a call to `Set()` will be visible to future calls to `Get()`.

feat: update ivcache `Set()` to use `Wait()`

---

.github/workflows/conformance.yaml
charts/kyverno/templates/NOTES.txt

This PR is to remove the support of generating validating admission policies from Kyverno policies from K8s cluster v1.26 due to [this](https://github.com/kyverno/kyverno/issues/8288) issue.

chore: remove validating admission policy support from v1.26

---

pkg/clients/dclient/discovery.go
pkg/engine/adapters/dclient.go
pkg/engine/handlers/validation/validate_cel.go

This PR fixes cache invalidation not happening in FindResources when no resource is found.
#8242

fix: cache invalidation in FindResources

---

cmd/cli/kubectl-kyverno/commands/apply/command.go
cmd/cli/kubectl-kyverno/commands/test/test.go
cmd/cli/kubectl-kyverno/processor/vap_processor.go

This PR fixes vap processor in the cli:
- pass all policies at once to the processor
- remove redundant args

fix: vap processor in cli

---

pkg/controllers/webhook/controller.go

This PR fixes an issue with generate rules where an empty kind would be accepted.

fix: generate empty kind

---

pkg/engine/image_verify_test.go

Previously, the ratio of time taken with cache : time taken without cache was `1:10`, This works in most scenario but every once in a while, the assertion fails in CI because time taken is slightly more than 1/10th due to some reason.
```bash
image_verify_test.go:1066: assertion failed: expression is false: secondOperationTime < firstOperationTime/10: cache entry is valid, so image verification should be from cache.%!(EXTRA time.Duration=25.163356ms, time.Duration=2.982342ms)
```
This PR updates the ratio to `1:2`.

feat: update condition in image verify cache tests

---

test/cli/test/deny-modify-platform-label/deny-modify-platform-label.yaml
test/cli/test/deny-modify-platform-label/kyverno-test.yaml
test/cli/test/deny-modify-platform-label/resource.yaml
test/cli/test/deny-modify-platform-label/variables.yaml

This PR fixes: Kyverno test ignores variables.yaml file unless context is present.
Fixes #6206

fix: Kyverno test ignores variables.yaml file unless context is present

---

cmd/cli/kubectl-kyverno/processor/generate.go
test/cli/test-generate/sync-multiple-resources/cm.yaml
test/cli/test-generate/sync-multiple-resources/deployment.yaml
test/cli/test-generate/sync-multiple-resources/gen-cm.yaml
test/cli/test-generate/sync-multiple-resources/gen-secret.yaml
test/cli/test-generate/sync-multiple-resources/kyverno-test.yaml
test/cli/test-generate/sync-multiple-resources/policy.yaml
test/cli/test-generate/sync-multiple-resources/secret.yaml

This PR fixes all tests fails when use mutiple results with generate-clone.
Fixes #5452

fix: all tests fails when use mutiple results with generate-clone

---

test/cli/test/disallow-service/kyverno-test.yaml
test/cli/test/disallow-service/policy.yaml
test/cli/test/disallow-service/resource.yaml

This PR fixes: kyverno test ignores namespace of resources in resource.yaml.
Fixes #7044

fix: kyverno test ignores namespace of resources in resource.yaml

---

.github/workflows/conformance.yaml

This PR adds `--compress` to cli test files verification.

chore: add --compress to cli test files verification

---

.nancy-ignore

There is a new vulnerability: [CVE-2023-41338](https://github.com/gofiber/fiber/security/advisories/GHSA-3q5p-3558-364f) which is causing Nancy to fail in new PRs: https://github.com/kyverno/kyverno/actions/runs/6155928394/job/16703644963?pr=8337
We do not have github.com/gofiber/fiber/v2 in our `go.mod` because the dependency got pruned but nancy uses a broader dependency graph algorithm.
This PR adds that CVE to `.nancyignore` to fix failing check.

chore: add gofiber/fiber/v2@v2.43.0 to nancy ignore

---

test/cli/test-mutate/karpenter-annotations-to-nodeselector/kyverno-test.yaml
test/cli/test-mutate/karpenter-annotations-to-nodeselector/patched.yaml
test/cli/test-mutate/karpenter-annotations-to-nodeselector/policy.yaml
test/cli/test-mutate/karpenter-annotations-to-nodeselector/resource.yaml

This PR fixes: kyverno test are applying previous mutation rules to subsequent test cases causing failures.
Fixes #6816

fix: kyverno test are applying previous mutation rules to subsequent test cases causing failures

---

cmd/cli/kubectl-kyverno/processor/generate.go
pkg/clients/dclient/fake.go
test/cli/test-generate/custom-resource/clone-secret.yaml
test/cli/test-generate/custom-resource/gen-secret.yaml
test/cli/test-generate/custom-resource/kyverno-test.yaml
test/cli/test-generate/custom-resource/policy.yaml
test/cli/test-generate/custom-resource/resource.yaml

This PR fixes: Testing a generate rule for a custom resource fails
Fixes #7853

fix: Testing a generate rule for a custom resource fails

---

cmd/cli/kubectl-kyverno/commands/apply/command.go
cmd/cli/kubectl-kyverno/commands/apply/command_test.go
cmd/cli/kubectl-kyverno/commands/test/command.go
cmd/cli/kubectl-kyverno/commands/test/output.go
cmd/cli/kubectl-kyverno/commands/test/test.go
cmd/cli/kubectl-kyverno/processor/generate.go
cmd/cli/kubectl-kyverno/processor/policy_processor.go
cmd/cli/kubectl-kyverno/processor/policy_processor_test.go
cmd/cli/kubectl-kyverno/processor/result.go
cmd/cli/kubectl-kyverno/utils/common/common.go
cmd/cli/kubectl-kyverno/utils/common/fetch.go
cmd/cli/kubectl-kyverno/utils/common/kyverno_resources_types.go
cmd/cli/kubectl-kyverno/utils/common/validating_admission_resources.go

This PR replaces fmt.Print calls by fmt.Fprint ones so that we can capture the output.

fix: replace fmt.Print calls by fmt.Fprint ones

---

cmd/cli/kubectl-kyverno/policy/load.go
go.mod
go.sum

This PR bumps kubectl-validate (easier to use).

chore: bump kubectl-validate

---

cmd/cli/kubectl-kyverno/commands/fix/policy/command.go
cmd/cli/kubectl-kyverno/commands/fix/policy/command_test.go
cmd/cli/kubectl-kyverno/commands/fix/policy/doc.go
cmd/cli/kubectl-kyverno/commands/fix/policy/options.go
cmd/cli/kubectl-kyverno/fix/policy.go
cmd/cli/kubectl-kyverno/policy/load.go
cmd/cli/kubectl-kyverno/policy/load_test.go
docs/user/cli/kyverno_fix_policy.md

This PR adds a new command `kyverno fix policy` to automatically fix usage of deprecated fields in policies:
- match/exclude not using any/all
- preconditions not using any/all
- deprecated operators in preconditions (`Equal`, `NotEqual`, `In` and `NotIn`)
- validation failure action (`enforce` -> `Enforce` and `audit` -> `Audit`)

feat: fix policy command

---

pkg/background/mutate/mutate.go

This PR prints the error message when the mutate target is empty. Xref https://kubernetes.slack.com/archives/CLGR9BJU9/p1695042874452649.

chore: improve log messages

---

cmd/cli/kubectl-kyverno/policy/load.go

This PR deep copies the resource before calling kubectl-validate validation (because it mutates the resource).

fix: deep copy before validaitng

---

cmd/kyverno/main.go

This PR fixes `webhookTimeout` flag description not clear.
Fixes #8492

fix: webhookTimeout flag not clear

---

charts/kyverno/README.md
charts/kyverno/templates/_helpers.tpl
charts/kyverno/values.yaml
cmd/internal/flag.go
cmd/internal/tuf.go
scripts/config/custom-sigstore/kyverno.yaml

For a cluster in a private subnet with no internet, TUF will fail to initialize causing error, This PR adds a flag called enable TUF which is set to `false` by default.
Discussion: https://kubernetes.slack.com/archives/CLGR9BJU9/p1695369576794329?thread_ts=1695363064.424669&cid=CLGR9BJU9

fix: disables TUF by default

---

pkg/utils/controller/metadata.go
pkg/utils/report/labels.go
pkg/utils/report/new.go

This PR fixes: creating ClusterAdmissionReports fails for resources with colon in name.
Fixes #8011

fix: creating ClusterAdmissionReports fails for resources with colon in name

---

api/kyverno/v2alpha1/cleanup_policy_interface.go
api/kyverno/v2alpha1/cleanup_policy_types.go
pkg/controllers/cleanup/controller.go

This PR adds a new function to the cleanup policy interface to get the last execution time.

refactor: get the last execution time from the cleanup policy interface

---

api/kyverno/v2alpha1/policy_exception_types.go
api/kyverno/v2beta1/policy_exception_types.go
charts/kyverno/templates/crds/crds.yaml
cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policyexceptions.yaml
cmd/internal/engine.go
config/crds/kyverno.io_policyexceptions.yaml
config/install-latest-testing.yaml
pkg/engine/api/ruleresponse.go
pkg/engine/api/selector.go
pkg/engine/exceptions.go
pkg/webhooks/resource/fake.go

This PR uses `v2beta` version of policy exceptions in the code.
Closes #8582

fix: use v2beta1 of policy exceptions

---

api/kyverno/v2alpha1/cleanup_policy_types.go
pkg/event/events.go

This PR uses `GetKind()` from the cleanup policy interface instead of creating a new function to get the kind in the events package.

refactor: use GetKind() from the cleanup policy interface

---

cmd/kyverno/main.go
pkg/controllers/validatingadmissionpolicy-generate/controller.go
pkg/event/events.go

This PR generates events for Kyverno policies that generates VAPs.
None
/kind feature
1. Create a cluster with `ValidatingAdmissionPolicy` feature gate enabled.
2. Enable `--generateValidatingAdmissionPolicy` in the admission controller.
3. Create a policy that uses CEL subrule:
```
metadata:
name: disallow-host-path
spec:
rules:
- name: host-path
match:
any:
- resources:
kinds:
- Deployment
- StatefulSet
operations:
- CREATE
- UPDATE
validate:
cel:
expressions:
- expression: "!has(object.spec.template.spec.volumes) || object.spec.template.spec.volumes.all(volume, !has(volume.hostPath))"
message: "HostPath volumes are forbidden. The field spec.template.spec.volumes[*].hostPath must be unset." …
```

feat: generate events for CEL policies that generate VAPs

---

.github/actions/setup-build-env/action.yaml

Bump Go version due to https://github.com/golang/go/issues/63417.

deps: bump to Go 1.21.3

---

charts/kyverno/README.md
charts/kyverno/templates/admission-controller/poddisruptionbudget.yaml
charts/kyverno/templates/background-controller/poddisruptionbudget.yaml
charts/kyverno/templates/cleanup-controller/poddisruptionbudget.yaml
charts/kyverno/templates/reports-controller/poddisruptionbudget.yaml
charts/kyverno/values.yaml

This PR allows PDBs to be declaratively enabled and not rely on the replicas > 1 condition. To not break the existing behavior, there is currently no way to disable PDB if replicas > 1.
This fix will allow us to use FluxCD post-build substitutions in replicas values as explained in https://github.com/kyverno/kyverno/issues/8537.
Relates to https://github.com/kyverno/kyverno/issues/8537
Closes https://github.com/kyverno/kyverno/issues/8650
/kind bug
The proposed changes should be easy to understand. It just ORs the new `enabled` value with the existing `replicas > 1`.

fix(helm): add values for declaratively enabling PDBs

---

.devcontainer/Dockerfile

Using latest ubuntu image in dev containers can cause an error where `containerd.io` and `docker-ce-cli` are not found. 
This can be because docker's internal repos are not supported on latest by that time.
Similar issue: https://stackoverflow.com/questions/61401626/docker-installation-failed-on-ubuntu-20-04-ltsvmware
This PR:
- Downgrades to Ubuntu:22.04
- Bumps golang in dev container to 1.21.3 like in CI. 
Related discussion: https://kubernetes.slack.com/archives/CLGR9BJU9/p1697190012878899

feat: use ubuntu:22.04 in devcontainer

---

.github/workflows/devcontainer-build.yaml

PRs that upgrade the dev container base image needs to be tested manually.
Example: PR https://github.com/kyverno/kyverno/pull/8667 will cause [issues in devcontainer](https://github.com/kyverno/kyverno/pull/8667#issuecomment-1766384940) but there is no way to detect that right now. This PR adds a workflow that builds .devcontainer docker file from the current branch

feat: adds ci test for building devcontainer image

---

pkg/engine/jmespath/functions_test.go
pkg/utils/image/infos.go

This PR removes duplicated log messages in the `images` package.
Before removing them, we got the following:
```
I1017 16:33:00.060754  103178 infos.go:54] image "msg"="getting the image info" "defaultRegistry"="docker.io" "enableDefaultRegistryMutation"=true "image"="registry.k8s.io/coredns/coredns:v1.10.1"
I1017 16:33:00.060836  103178 infos.go:89] image "msg"="getting the image info" "digest"="" "image"="registry.k8s.io/coredns/coredns:v1.10.1" "name"="coredns" "path"="coredns/coredns" "registry"="registry.k8s.io" "tag"="v1.10.1"
I1017 16:33:00.060972  103178 context.go:299]  "msg"="updated image info" "images"={"containers":{"coredns":{"registry":"registry.k8s.io","name":"coredns","path":"coredns/coredns","tag":"v1.10.1","jsonPointer":"/spec/containers/0/image"}}}
```
After its …

remove duplicated log messages

---

.devcontainer/Dockerfile

Using devcontainer in `arm64` can sometimes cause the following error:
```bash
=> ERROR [7/8] RUN apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io                                                                                                                   4.4s 
------                                                                                                                                                                                                                
> [7/8] RUN apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io:                                                                                                                              
1.982 Hit:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease
2.132 Hit:2 …
```

feat: add arm64 support in devcontainers

---

charts/kyverno/templates/reports-controller/clusterrole.yaml

This PR adds permissions for the reports controller to get and list validating admission policies in case the user enabled the flag `--validatingAdmissionPolicyReports`.

fix: add VAP and VAPB to reports controller ClusterRole

---

pkg/controllers/validatingadmissionpolicy-generate/policycheck.go

This PR renames the VAP name logging to `ValidatingAdmissionPolicy`.

fix: rename vap logging name to ValidatingAdmissionPolicy

---

cmd/kyverno/main.go
pkg/controllers/validatingadmissionpolicy-generate/controller.go
pkg/toggle/context.go
pkg/toggle/toggle.go
pkg/utils/validatingadmissionpolicy/permissions.go
pkg/validation/policy/actions.go
pkg/validation/policy/validate.go

This PR displays a message when the admission controller has no permissions to generate validating admission policies and their bindings.
In case the user enabled the flag `--generateValidatingAdmissionPolicy=true` and created the following policy:
```
metadata:
name: disallow-host-path
spec:
rules:
- name: host-path
match:
any:
- resources:
kinds:
- Pod
validate:
cel:
expressions:
- expression: "!has(object.spec.volumes) || object.spec.volumes.all(volume, !has(volume.hostPath))"
message: "HostPath volumes are forbidden. The field spec.template.spec.volumes[*].hostPath must be unset."
```
The output:
```
Warning: doesn't have required permissions for generating ValidatingAdmissionPolicies …
```

fix: display a message when the controller has no permissions for VAPs

---

go.mod
go.sum

Cherry-pick https://github.com/kyverno/kyverno/pull/8679.
Closes https://github.com/kyverno/kyverno/issues/8838.

bump google.golang.org/grpc from 1.58.2 to 1.59.0

---

.github/workflows/conformance.yaml
.github/workflows/devcontainer-build.yaml
.github/workflows/images-build.yaml
.github/workflows/images-publish.yaml
.github/workflows/release.yaml
go.mod
go.sum
pkg/utils/image/infos.go
pkg/validation/policy/validate.go

This PR:
- bump sigstore/scaffolding from 838c26c783a08cf497dfff29d95ca90c6eeba3df to 46eb35c1c415d976c7f9d3ee4c936e65c35e8e3e
- bump aquasecurity/trivy-action from 0.13.1 to 0.14.0
- bump github.com/distribution/distribution from 2.8.2+incompatible to 2.8.3+incompatible
- bump sigs.k8s.io/kubectl-validate from 0.0.1 to 0.0.2
Closes https://github.com/kyverno/kyverno/pull/8851.
Closes https://github.com/kyverno/kyverno/pull/8843.
Closes https://github.com/kyverno/kyverno/pull/8616.
Closes https://github.com/kyverno/kyverno/pull/8854.

chore (deps): bump a couple of deps

---

cmd/cli/kubectl-kyverno/commands/create/exception/command.go
cmd/cli/kubectl-kyverno/commands/create/exception/command_test.go
cmd/cli/kubectl-kyverno/commands/create/templates/exception.yaml

This PR uses the `v2beta1` version for `kyverno create exception` .
None
/kind bug
Run the kyverno create command as follows:
```
cmd/cli/kubectl-kyverno/kubectl-kyverno create exception my-exception --namespace my-ns --policy-rules "policy,rule-1,rule-2" --any "kind=Pod,kind=Deployment,name=test-*"
```
The output should be an exception policy of `v2beta1`:
```
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
name: my-exception
namespace: my-ns
spec:
match:
any:
-
kinds:
- Pod
- Deployment
names:
- test-*
exceptions:
- policyName: policy
ruleNames:
- rule-1
- rule-2
```

fix: use v2beta1 version of exceptions in kyverno create CLI

---

charts/kyverno/Chart.yaml
charts/kyverno/templates/admission-controller/servicemonitor.yaml
charts/kyverno/templates/background-controller/servicemonitor.yaml
charts/kyverno/templates/cleanup-controller/servicemonitor.yaml
charts/kyverno/templates/reports-controller/servicemonitor.yaml

This reverts commit 590dce5830888ab592cb69e44ed57dd486403347.
This will ensure servicemonitor can be enabled with ArgoCD which doesn't support querying API capabilities
Fixes #8891

Revert "fix(chart): only create ServiceMonitor if cluster supports it (#7926)

---

cmd/cli/kubectl-kyverno/commands/create/exception/command.go
cmd/cli/kubectl-kyverno/commands/create/exception/command_test.go
cmd/cli/kubectl-kyverno/commands/create/templates/exception.yaml

Cherry-picked fix: use v2beta1 version of exceptions in kyverno create CLI (https://github.com/kyverno/kyverno/pull/8908)

fix: use v2beta1 version of exceptions in kyverno create CLI (cherry-pick #8908)

---

cmd/cli/kubectl-kyverno/test/test_command.go

Kyverno tests fails with random results in v1.9-v1.10.
This PR moves a default test namespace value assignation within the correct scope.
See repro at https://gist.github.com/aslafy-z/4be51cb23e7a40ee5e288ab2ad85f1a6
This bug was added with https://github.com/kyverno/kyverno/pull/4100 while fixing an other bug, see https://github.com/kyverno/kyverno/issues/4087
/milestone 1.9.6
/milestone 1.10.6
/kind bug
Move the block to the correct scope.

fix(test): random results when namespace is not specified [v1.9-v1.10]

---

pkg/controllers/ttl/controller.go

Fix ttl cleanup not working with cluster wide resources.
Fixes #9053

fix: ttl cleanup not working with cluster wide resources

---

.github/workflows/conformance.yaml

1. Add 1.29 to all test grids.
2. Remove 1.25 from all test grids.

chore: add 1.29 to all test grids and remove 1.25

---

pkg/controllers/validatingadmissionpolicy-generate/controller.go
pkg/validation/policy/actions.go

Improve ValidatingAdmissionPolicy validation messages 
n/a

improve messages

---

.github/workflows/cli.yaml
cmd/cli/kubectl-kyverno/experimental/experimental.go

Enable kubectl-validate by default in the cli.

feat: enable kubectl-validate by default in cli

---

pkg/policy/mutate.go
pkg/policy/policy_controller.go
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/background-false/chainsaw-step-01-apply-1-1.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/background-false/chainsaw-step-01-apply-1-2.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/background-false/chainsaw-step-03-assert-1-1.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/background-false/chainsaw-test.yaml

This PR fixes force reconciliation for mutateExisting policies. This policy will be applied during the background scan (1h by default, can be customized through use of env var `BACKGROUND_SCAN_INTERVAL`, performed by the background controller) regardless of `mutateExistingOnPolicyUpdate` settings.
Closes https://github.com/kyverno/kyverno/issues/9174.
/1.11.2
https://github.com/kyverno/website/pull/1078
/bug
No chainsaw test is added as it requires custom installation for the background controller. And checks for both scenarios are the same - to verify the annotation is added, just with different delays.
Update the background scan interval to `2m`, follow the reproduction steps in the issue, and:
1. apply the policy with …

fix: mutate existing force reconciliation

---

cmd/kyverno/main.go
pkg/controllers/validatingadmissionpolicy-generate/controller.go

This PR removes unnecessary parameter `polInformer` passed to the VAP controller.
Currently, VAPs can only be generated from clusterpolicies.

fix: remove policy informer from vap controller

---

cmd/cli/kubectl-kyverno/output/table/row_compact.go

This fixes the `apply` CLI command format issue with `--table` option.
After applying this commit the row count over 1000 will be `1234` instead of `1.2K`.
Closes #9280 
/kind bug
Same as noted in #9280. After applying this the output will be the following:
```
...
│ 1495       │ dummy  │ autogen-dummy │ default/Deployment/deploy-1494 │ Pass   │        │
│ 1496       │ dummy  │ autogen-dummy │ default/Deployment/deploy-1495 │ Pass   │        │
│ 1497       │ dummy  │ autogen-dummy │ default/Deployment/deploy-1496 │ Pass   │        │
│ 1498       │ dummy  │ autogen-dummy │ default/Deployment/deploy-1497 │ Pass   │        │
...
```

fix: large table row ID number format in CLI

---

go.mod
go.sum

This PR bumps kubectl-validate dep to the latest version.

chore(deps): bump kubectl-validate version

---

test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-exclude/validatingadmissionpolicybinding.yaml

This PR adds a missing `-binding` in a chainsaw test related to VAPs.

fix a chainsaw test

---

cmd/cli/kubectl-kyverno/commands/test/test.go

Added the change in test command from 9315.
That PR cannot directly be cherry picked as  `processor.PolicyProcessor` expects different fields.
```bash
❯ docker logout ghcr.io
❯ ./kubectl-kyverno test test-reg --registry=true --v=4
Loading test  ( test-reg/kyverno-test.yaml ) ...
Loading values/variables ...
Loading policies ...
Loading resources ...
Applying 1 policy to 1 resource ...
I0105 13:31:15.541919   53505 imageverifier.go:498] "image attestors verification failed" logger="engine.verify" policy.name="check-image" policy.namespace="" policy.apply="All" new.kind="Pod" new.namespace="default" new.name="signed" rule.name="verify-signature" verifiedCount=0 requiredCount=1 errors=".attestors[0].entries[0]: failed to parse image reference: …
```

fix: update CLI to use store for fetching regclient 

---

.github/ISSUE_TEMPLATE/bug-cli.yaml
.github/ISSUE_TEMPLATE/bug-other.yaml
.github/ISSUE_TEMPLATE/bug-webhook.yaml

Signed-off-by: chipzoller <chipzoller@gmail.com>
Adds more 1.11 patch release versions to issue templates and removes 1.6 versions.

Bump versions in issue templates

---

pkg/utils/controller/run.go

Reduce logs in controllers when an item is not found.

fix: reduce logs in controllers when an item is not found

---

pkg/utils/admission/metadata_test.go

This PR Adds test for `pkg/utils/admission/metadata.go` 
This PR adds unit test for `pkg/utils/admission/metadata.go`, also partially fixes and closes #9514

test: added test for pkg/utils/admission/metadata.go

---

cmd/cli/kubectl-kyverno/exception/load.go

This PR adds the support for applying/testing v2alpha1 exceptions using Kyverno CLI.
N/A
/kind bug
1. Using Kyverno apply command:
```
metadata:
name: max-containers
spec:
rules:
- name: max-two-containers
match:
any:
- resources:
kinds:
- Pod
validate:
message: "A maximum of 2 containers are allowed inside a Pod."
deny:
conditions:
any:
- key: "{{request.object.spec.containers[] | length(@)}}"
value: 2
```
2. exception.yaml:
```
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
name: container-exception
spec:
exceptions:
- policyName: max-containers
ruleNames:
- …
```

fix: add the support of v2alpha1 exceptions in the CLI

---

cmd/cli/kubectl-kyverno/commands/apply/command.go
cmd/cli/kubectl-kyverno/commands/apply/command_test.go
cmd/cli/kubectl-kyverno/processor/vap_processor.go
pkg/controllers/report/utils/scanner.go
pkg/validatingadmissionpolicy/matcher.go
pkg/validatingadmissionpolicy/validate.go
test/cli/test-validating-admission-policy/with-bindings-1/deployment1.yaml
test/cli/test-validating-admission-policy/with-bindings-1/deployment2.yaml
test/cli/test-validating-admission-policy/with-bindings-1/policy.yaml
test/cli/test-validating-admission-policy/with-bindings-2/deployment1.yaml
test/cli/test-validating-admission-policy/with-bindings-2/deployment2.yaml
test/cli/test-validating-admission-policy/with-bindings-2/policy.yaml
test/cli/test-validating-admission-policy/with-bindings-3/deployment1.yaml
test/cli/test-validating-admission-policy/with-bindings-3/deployment2.yaml
test/cli/test-validating-admission-policy/with-bindings-3/deployment3.yaml
test/cli/test-validating-admission-policy/with-bindings-3/policy.yaml
test/cli/test-validating-admission-policy/with-bindings-3/values.yaml
test/cli/test-validating-admission-policy/with-bindings-4/deployment1.yaml
test/cli/test-validating-admission-policy/with-bindings-4/deployment2.yaml
test/cli/test-validating-admission-policy/with-bindings-4/policy.yaml

This PR supports applying bindings along with VAPs using Kyverno CLI `apply` command in offline mode. i.e. without communicating to the cluster.
N/A
/kind feature
1. `policy.yaml`:
```
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
name: "check-deployment-replicas"
spec:
resourceRules:
- apiGroups:
- apps
apiVersions:
- v1
operations:
- CREATE
- UPDATE
resources:
- deployments
validations:
- expression: object.spec.replicas <= 2
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicyBinding
metadata:
name: "check-deployment-replicas-binding"
spec:
policyName: "check-deployment-replicas"
validationActions: [Deny]
matchResources: …
```

feat: apply VAP bindings in CLI apply command in offline mode

---

pkg/logging/log.go

With https://github.com/kyverno/kyverno/pull/9276 the default logging format was set to Epoch Nanos which is not easy to ready. This PR switches the default logging format to RFC3339.
/1.12.0
Logging timestamp after this PR:
```
k logs -n kyverno -f deploy/kyverno-admission-controller
Defaulted container "kyverno" out of: kyverno, kyverno-pre (init)
2024-02-23T09:22:14Z	INFO	setup.version	version/version.go:49	version	{"version": "(devel)", "hash": "cd023846a726d3b8b4bccb3ce83c901e562b2930", "time": "2024-02-23T08:54:46Z"}
2024-02-23T09:22:14Z	LEVEL(-2)	setup.flag	internal/flag.go:260		{"add_dir_header": "false"}
2024-02-23T09:22:14Z	LEVEL(-2)	setup.flag	internal/flag.go:260		{"admissionReports": "true"}
2024-02-23T09:22:14Z	LEVEL(-2) …
```

chore: default logging format to rfc3339

---

pkg/engine/mutate/patch/strategicMergePatch.go
pkg/engine/mutate/patch/strategicPreprocessing.go
pkg/engine/mutate/patch/strategicPreprocessing_test.go

We are using your fantastic project as a library, especially using your anchor technique for applying patch strategic merge.
In order to easily integrate with your code, we need the `preProcessPattern` to be accessible from our code, hence changing its name to `PreProcessPattern`.
https://github.com/kyverno/kyverno/issues/9886
My PR does not alter the behavior of Kyverno. 
/kind feature
It's really a little change, with only local changes as the function was previously private, the change cannot impact other projects nor users.
Not applicable
Thanks a lot for your great project!

give public access to PreProcessPattern

---

charts/kyverno/templates/admission-controller/deployment.yaml
charts/kyverno/templates/admission-controller/service.yaml
charts/kyverno/templates/cleanup-controller/deployment.yaml
charts/kyverno/templates/cleanup-controller/service.yaml

When deploying the charts on an EKS cluster with custom CNI (Calico), the `hostNetwork` option must be enabled. However, due to the hardcoded ports 9443 and 8000 for each controller, only one pod can run per node.
Closed #8898
/kind bug
```yaml
admissionController:
replicas: 3
hostNetwork: true
webhookServer:
port: 10254
startupProbe:
httpGet:
port: 10254
livenessProbe:
httpGet:
port: 10254
readinessProbe:
httpGet:
port: 10254
metering:
port: 10255
cleanupController:
hostNetwork: true
server:
port: 10257
startupProbe:
httpGet:
port: 10257
livenessProbe:
httpGet:
port: 10257
readinessProbe:
httpGet:
port: 10257
metering:
port: 10258
```
<details><summary>Test results</summary>
```sh
$ helm install -f override-values.yaml kyverno -n kyverno --create-namespace ./
NAME: kyverno
LAST DEPLOYED: …
```

fix: Adjust chart templates to handle hostNetwork set to true

---

charts/kyverno/README.md
charts/kyverno/templates/NOTES.txt
charts/kyverno/values.yaml
config/install-latest-testing.yaml

Signed-off-by: chipzoller <chipzoller@gmail.com>
This PR excludes by default the `kube-system` Namespace in webhooks and adds the `'admissions.enforcer/disabled': 'true'` annotation to webhooks in order to provide safer defaults for many groups of users, specifically EKS and AKS.
Users who wish to revert to the previous behavior may opt out of these defaults by adding the following to their values override file.
```yaml
config:
webhooks: null
webhookAnnotations: null
```
Note that this could be a **breaking change** for some users who specifically wish to act on admission events for resource in `kube-system`. It will need to be clearly called out in the release notes.
Closes #9947
Closes #8872
1.12.0 …

Default exclusions in webhooks

---

cmd/cli/kubectl-kyverno/commands/apply/command.go
cmd/cli/kubectl-kyverno/commands/test/test.go
cmd/cli/kubectl-kyverno/processor/generate.go
cmd/cli/kubectl-kyverno/processor/result.go
cmd/cli/kubectl-kyverno/utils/common/common.go
cmd/cli/kubectl-kyverno/utils/common/fetch.go
cmd/cli/kubectl-kyverno/utils/common/kyverno_resources_types.go
pkg/autogen/autogen.go
pkg/autogen/autogen_test.go
pkg/background/generate/generate.go
pkg/controllers/exceptions/controller.go
pkg/controllers/metrics/policy/controller.go
pkg/controllers/report/aggregate/controller.go
pkg/controllers/report/utils/utils.go
pkg/controllers/webhook/controller.go
pkg/controllers/webhook/utils_test.go
pkg/engine/background.go
pkg/engine/fuzz_test.go
pkg/engine/generation.go
pkg/engine/image_verify.go
pkg/engine/mutate/patch/strategicMergePatch_test.go
pkg/engine/mutation.go
pkg/engine/utils/utils_test.go
pkg/engine/validation.go
pkg/policy/generate.go
pkg/policycache/cache_test.go
pkg/policycache/store.go
pkg/validation/policy/background.go
pkg/validation/policy/validate.go
pkg/webhooks/resource/updaterequest.go

This PR improves the efficiency and accuracy of the autogen feature for Kubernetes policies. Previously, autogen would generate rules for all Pod Controllers (e.g., Deployments, DaemonSets) regardless of the specific controller targeted in the admission request. This could lead to unnecessary rule generation and potential conflicts.
This PR introduces a targeted approach where autogen only generates a rule for the specific Pod Controller type present in the admission request. This optimization ensures that only relevant rules are generated, improving performance and reducing the possibility of conflicting rules.
For example, if the admission request is for a Deployment, autogen will now only generate a rule for Deployments, instead of generating rules for all Pod Controller types.
This …

fix(autogen): only generate rule for request kind

---

cmd/background-controller/main.go
cmd/cleanup-controller/main.go
cmd/kyverno/main.go
cmd/reports-controller/main.go
pkg/event/controller.go
pkg/event/controller_test.go

1. Re-using the flag `maxQueuedEvents` to limit the nu. of the events to be queued. It doesn't solve the main issue but helps limit the creation of new events.
2. Check the error message in case the event fails to be created. If it does contain either `not found` or `being terminated`, it isn't re-queued. It is dropped from the queue immediately.
Closes #10020 
/kind bug
N/A
N/A

fix: re-use the maxQueuedEvents

---

pkg/config/metricsconfig.go
pkg/config/metricsconfig_test.go

This change translates the metric exposure config to a open-telemetry view function that selectively applies the a configured dimension filters and bucket aggregations driven by the underlying metrics runtime details.
The improvement completes and extends the metric dimension filter feature to other non histogram kind of metrics. It also fixes a side-effect where counters are accidentally getting transformed into histograms when the metric exposure config prescribes custom bucket boundaries.
Closes #9998 
/kind bug
Deploy a metric exposure config by populating the corresponding keys of the values.yaml e.g.:
```yaml
metricsConfig:
create: true
metricsExposure:
kyverno_policy_results:
enabled: false
kyverno_policy_execution_duration_seconds:
disabledLabelDimensions:
[ …
```

Fix: metrics exposure inconsistencies and unwanted side-effects

---

pkg/controllers/webhook/utils.go
pkg/controllers/webhook/utils_test.go

The error `MutatingWebhookConfiguration: webhooks[0].rules[0].operations: Required value` occurs when using mutating and generating rules in the same policy.
Fixes #10143 .
/milestone 1.12.1
/kind bug
Add a check in order to skip rules without any mapped operation.

fix: skip rules without operation in resource webhook creation

---

pkg/validatingadmissionpolicy/builder.go
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-ephemeral-containers/README.md
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-ephemeral-containers/chainsaw-test.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-ephemeral-containers/pod.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-ephemeral-containers/policy-assert.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-ephemeral-containers/policy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-ephemeral-containers/validatingadmissionpolicy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-ephemeral-containers/validatingadmissionpolicybinding.yaml

This PR is to add "pods/ephemeralcontainers" in the match block of the generated ValidatingAdmissionPolicies in case the Kyverno policy matches pods. This is because it is added by default in the validatingwebhookconfiguration.
N/A
/milestone 1.12.2
/kind bug
1. Create a Kyverno policy that blocks the use of ephemeral containers:
```
metadata:
name: block-ephemeral-containers
spec:
rules:
- name: block-ephemeral-containers
match:
any:
- resources:
kinds:
- Pod
validate:
cel:
expressions:
- expression: "!has(object.spec.ephemeralContainers)"
message: "Ephemeral (debug) containers are not permitted."
```
2. Check the generated VAP:
``` …
```

fix: add pods/ephemeralcontainers to the generated VAPs

---

pkg/validatingadmissionpolicy/kyvernopolicy_checker.go
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-multiple-resources-with-namespace-selector/chainsaw-test.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-multiple-resources-with-namespace-selector/policy-assert.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-multiple-resources-with-namespace-selector/policy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-multiple-resources-with-namespace-selector/validatingadmissionpolicy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-multiple-resources-with-namespace-selector/validatingadmissionpolicybinding.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-multiple-resources-with-object-selector/chainsaw-test.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-multiple-resources-with-object-selector/policy-assert.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-multiple-resources-with-object-selector/policy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-multiple-resources-with-object-selector/validatingadmissionpolicy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-multiple-resources-with-object-selector/validatingadmissionpolicybinding.yaml

This PR skips generating a VAP from a Kyverno policy that match multiple resources in which one of them defines either a `namespaceSelector` or an `objectSelector`.
Closes #10180 
/milestone 1.12.2
/kind bug
1. Create the following policy:
```
metadata:
name: disallow-host-path-t12
spec:
validationFailureAction: Audit
rules:
- name: host-path
match:
any:
- resources:
kinds:
- Deployment
operations:
- CREATE
- UPDATE
- key: type 
operator: In
values: 
- connector
- resources:
kinds:
- StatefulSet
operations:
- CREATE
- UPDATE
validate:
cel:
expressions:
- expression: "!has(object.spec.template.spec.volumes) || object.spec.template.spec.volumes.all(volume, …
```

fix: skip generating VAPs for policies that match multiple resources with a namespace/object selector

---

pkg/validatingadmissionpolicy/builder.go
pkg/validatingadmissionpolicy/kyvernopolicy_checker.go
pkg/validatingadmissionpolicy/kyvernopolicy_checker_test.go
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-resource-in-specific-namespace/chainsaw-test.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-resource-in-specific-namespace/policy-assert.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-resource-in-specific-namespace/policy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-resource-in-specific-namespace/validatingadmissionpolicy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-resource-in-specific-namespace/validatingadmissionpolicybinding.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-match-resource-in-specific-namespace/validatingadmissionpolicy.yaml

In Kyverno policies, users can match resources in specific namespaces as follows:
```
match:
any:
- resources:
kinds:
- Deployment
operations:
- CREATE
- UPDATE
namespaces:
- production
- staging
```
However, in ValidatingAdmissionPolicies, there is no way to specify a namespace by its name. Instead, this PR uses the `namespaceSelector` to achieve the same behavior:
```
- key: kubernetes.io/metadata.name
operator: In
values:
- production
- staging
resourceRules:
- apiGroups:
- apps
apiVersions:
- v1
operations:
- CREATE
- UPDATE
resources:
- deployments
```
N/A
/milestone 1.13
/kind feature
```
metadata:
name: …
```

feat: support generating VAPs in case of matching resources in specific namespaces

---

pkg/validatingadmissionpolicy/builder.go
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-kind-with-wildcard/chainsaw-test.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-kind-with-wildcard/policy-assert.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-kind-with-wildcard/policy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-kind-with-wildcard/validatingadmissionpolicy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-kind-with-wildcard/validatingadmissionpolicybinding.yaml

This PR generates VAPs that match all resources when the `kinds` is set to `*` in the Kyverno policy.
Closes #10207 
/milestone 1.12.2
/kind bug
Create the following policy:
```
metadata:
name: check-label-app4
spec:
validationFailureAction: Audit
rules:
- name: check-label-app
match:
all:
- resources:
kinds:
- '*'
namespaces:
- production
- staging
validate:
cel:
expressions:
- expression: "'app' in object.metadata.labels"
```
The policy is successfully created and the corresponding VAP is generated as follows:
```
apiVersion: admissionregistration.k8s.io/v1alpha1
metadata:
labels:
app.kubernetes.io/managed-by: kyverno
name: check-label-app4 …
```

fix: generate VAPs that match all resources when kinds is set to *

---

pkg/cosign/cosign_test.go

fix: cosign ctlog unit tests (#9970)

---

pkg/engine/handlers/mutation/common.go
pkg/engine/mutate/mutation.go
pkg/engine/utils/foreach.go
pkg/engine/utils/foreach_test.go
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/descending-patchJson6902/README.md
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/descending-patchJson6902/chainsaw-test.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/descending-patchJson6902/policy-assert.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/descending-patchJson6902/policy.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/descending-patchJson6902/target-pod-assert.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/descending-patchJson6902/target-pod-updated.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/descending-patchJson6902/target-pod.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/descending-patchJson6902/trigger-pod-assert.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/descending-patchJson6902/trigger-pod.yaml

After commit https://github.com/kyverno/kyverno/commit/46f02a8ba7c9c3bf00854f4e8904712c52a19839, when the order is set to `Descending` in foreach mutate, the order of items in the trigger resource also gets reverted, causing the wrong item to get patched.
This PR:
1. copies and reverses elements instead of swapping.
2. deepcopies the resource at the start of foreach
Closes #10224
Closes #10199

fix: deepcopy patched resource in foreach mutate

---

pkg/event/events.go
pkg/event/events_test.go

Truncate event message lengths to 1024 characters
Fixes https://github.com/kyverno/kyverno/issues/10210
1.12.2
/kind bug
Truncate event message lengths to 1024 characters
See unit tests

truncate event messages to 1024 chars

---

cmd/cli/kubectl-kyverno/_testdata/policies-invalid/artifacthub-pkg.yml
cmd/cli/kubectl-kyverno/_testdata/policies-invalid/chainsaw-test.yaml
cmd/cli/kubectl-kyverno/_testdata/policies-invalid/policy-ready.yaml
cmd/cli/kubectl-kyverno/_testdata/policies-mixed/artifacthub-pkg.yml
cmd/cli/kubectl-kyverno/_testdata/policies-mixed/cpol-pod-requirements.yaml
cmd/cli/kubectl-kyverno/_testdata/policies-mixed/nested/artifacthub-pkg.yml
cmd/cli/kubectl-kyverno/_testdata/policies-mixed/nested/cpol-pod-requirements.yaml
cmd/cli/kubectl-kyverno/commands/apply/command.go
cmd/cli/kubectl-kyverno/commands/fix/policy/options.go
cmd/cli/kubectl-kyverno/commands/oci/push/options.go
cmd/cli/kubectl-kyverno/commands/test/command.go
cmd/cli/kubectl-kyverno/commands/test/compare.go
cmd/cli/kubectl-kyverno/commands/test/load.go
cmd/cli/kubectl-kyverno/commands/test/output.go
cmd/cli/kubectl-kyverno/commands/test/test.go
cmd/cli/kubectl-kyverno/policy/legacy_loader.go
cmd/cli/kubectl-kyverno/policy/load.go
cmd/cli/kubectl-kyverno/policy/load_test.go
cmd/cli/kubectl-kyverno/policy/variables_test.go
cmd/cli/kubectl-kyverno/report/report_test.go

Fix CLI filesystem loader issues
Fixes https://github.com/kyverno/kyverno/issues/10171
1.12.2
/kind bug
Fixes CLI policy loading behaviors to allow policies to be stored in directories with non-Kubernetes resources, and other YAML files.
The change will also skip all hidden directories and files i.e. directories or files that start with a ".".
Some errors in the YAML files will be propagated e.g. an invalid schema error will not be ignored.
See unit tests.
You can also build and use the CLI locally like this:
(assumes the `kyverno-policies` repo is checked out in a local folder at `../kyverno-policies`)
```sh
./cmd/cli/kubectl-kyverno/kubectl-kyverno apply ../kyverno-policies/ -r /tmp/nginx.yaml
```
Note that the Git version of the …

Fix cli load policies from fs

---

pkg/controllers/webhook/controller_test.go
pkg/controllers/webhook/utils.go
pkg/controllers/webhook/utils_test.go

This PR fixes the webhookconfiguration operations list when merging across multiple policies. The operations list per resource should be built as a set across policies, not an intersection of two sets.
https://kubernetes.slack.com/archives/CLGR9BJU9/p1715760069018099
/1.12.2
/bug
Given these two policies snippets, full policies can be found in the Slack thread:
```yaml
metadata:
name: label-namespace-psa-restricted-enforce
spec:
rules:
- name: label-ns-psa-restricted-enforce
match:
any:
- resources:
kinds:
- Namespace
```
```yaml
metadata:
name: protect-deletion-rancher-service-namespace
spec:
rules:
- match:
any:
- resources:
kinds:
- Namespace …
```

fix: configure webhook operations list correctly across policies

---

.github/workflows/release.yaml

This is to fix the release failure https://github.com/kyverno/kyverno/actions/runs/9463689586/job/26081158003#step:9:16.

fix: remove dropped flag for goreleaser

---

pkg/engine/mutation_test.go
test/conformance/chainsaw/generate/clusterpolicy/cornercases/pod-restart-on-cm-update/policy.yaml
test/conformance/chainsaw/mutate/clusterpolicy/cornercases/variables-mutate-existing/chainsaw-step-01-apply-1-1.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/background-false/chainsaw-step-01-apply-1-2.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/basic-create-patchesJson6902/chainsaw-step-01-apply-1-3.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/basic-create/chainsaw-step-01-apply-1-3.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/basic-delete/chainsaw-step-01-apply-1-4.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/basic-update/chainsaw-step-01-apply-1-4.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/delete-trigger-namespace/policy.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/multiple-rules-match-exclude/chainsaw-step-01-apply-1-5.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/multiple-trigger-resources/policy.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/namespaceselector/policy.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/basic-create-policy/chainsaw-step-02-apply-1-1.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/namespaceselector/policy.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/preconditions/policy.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/validation/auth-check/cpol-namespace-variable/policy.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/validation/auth-check/cpol-standard-auth-check/policy.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/validation/mutate-existing-require-targets/policy-no-targets.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/validation/mutate-existing-require-targets/policy-targets.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/validation/target-variable-validation/policy-bad.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/validation/target-variable-validation/policy-good.yaml
test/conformance/chainsaw/mutate/policy/standard/existing/validation/auth-check/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/cornercases/schema-validation-for-mutateExisting/policy.yaml

This PR modifies the chainsaw tests to use the `mutateExistingOnPolicyUpdate` field which was introduced under the `mutate` rule.

chore: use mutateExistingOnPolicyUpdate under mutate rule in chainsaw tests

---

pkg/controllers/cleanup/controller.go

This PR fixes a bug related to deleting a resource by the cleanup controller.
Closes #10418 
/kind bug
/milestone 1.12.5
1. Apply the CRD of access tokens: https://github.com/crossplane-contrib/provider-gitlab/blob/6dd6214a54867b97d7c7d10c08f06aa24e9c7717/package/crds/projects.gitlab.crossplane.io_accesstokens.yaml
2. Create the cluster role for cleanup controller:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
labels:
app.kubernetes.io/component: cleanup-controller
app.kubernetes.io/instance: kyverno
app.kubernetes.io/part-of: kyverno
name: kyverno:cleanup-access-tokens
rules:
- apiGroups:
- 'projects.gitlab.crossplane.io'
resources:
- accesstokens
verbs:
- delete
- list
- get
```
3. Create cluster cleanup …

fix: failed to delete resource

---

pkg/controllers/cleanup/controller.go

Cherry-picked fix: cleanup policy name is appended to logs (#10583)

fix: cleanup policy name is appended to logs (cherry-pick #10583)

---

pkg/engine/handlers/validation/validate_cel.go
test/conformance/chainsaw/validate/clusterpolicy/cornercases/cel-messages-upon-resource-failure(deprecated)/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/cornercases/cel-messages-upon-resource-failure/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel(deprecated)/authorizor-checks/with-permissions/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel(deprecated)/authorizor-checks/without-permissions/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel(deprecated)/cel-preconditions/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel(deprecated)/cel-variables/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel(deprecated)/check-statefulset-namespace/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel(deprecated)/disallow-host-port/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel(deprecated)/parameter-resources/clusterscoped/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel(deprecated)/parameter-resources/namespaced/match-clusterscoped-resource/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel(deprecated)/parameter-resources/namespaced/set-paramref-namespace/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel(deprecated)/parameter-resources/namespaced/unset-paramref-namespace/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/authorizor-checks/with-permissions/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/authorizor-checks/without-permissions/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/cel-preconditions/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/cel-variables/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/check-statefulset-namespace/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/deny/README.md
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/deny/chainsaw-test.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/deny/policy-assert.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/deny/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/disallow-host-port/pod-fail.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/disallow-host-port/pod-pass.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/disallow-host-port/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/parameter-resources/clusterscoped/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/parameter-resources/namespaced/match-clusterscoped-resource/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/parameter-resources/namespaced/set-paramref-namespace/policy.yaml
test/conformance/chainsaw/validate/clusterpolicy/standard/cel/parameter-resources/namespaced/unset-paramref-namespace/policy.yaml

Policies that make use of `validate.cel` subrules aren't applied on resources in case the admission request is of type `DELETE`. This PR allows the application of policies on resources in case the `match` block matches the `DELETE` requests.
Closes #10576 
/milestone 1.12.5
/kind bug
1. Create an nginx pod: `kubectl run nginx --image=nginx`
2. Create a policy that denies the creation/deletion/update of pods:
```
metadata:
name: restrict-operations-on-pod
spec:
rules:
- name: rule-1
match:
any:
- resources:
kinds:
- Pod
validate:
cel:
expressions:
- expression: "false"
message: Create, update and delete on pods is not allowed
```
3. Delete the …

fix: CEL policies aren't applied to deleted resources

---

pkg/engine/mutation.go

When attempting to use the apply command in the cli to a policy that mutates existing resources the command panics due to an uninitialized client being passed to the rule handler
#10714
/kind bug
Add a check if the client is nil in the mutation handler factory

fix: Check for the client being nil before applying a mutation

---

pkg/validation/policy/validate.go
test/conformance/chainsaw/policy-validation/cluster-policy/assert/README.md
test/conformance/chainsaw/policy-validation/cluster-policy/assert/bad-context-name.yaml
test/conformance/chainsaw/policy-validation/cluster-policy/assert/chainsaw-test.yaml
test/conformance/chainsaw/policy-validation/cluster-policy/assert/no-foreach.yaml
test/conformance/chainsaw/policy-validation/cluster-policy/assert/ok.yaml
test/conformance/chainsaw/policy-validation/policy/assert/README.md
test/conformance/chainsaw/policy-validation/policy/assert/bad-context-name.yaml
test/conformance/chainsaw/policy-validation/policy/assert/chainsaw-test.yaml
test/conformance/chainsaw/policy-validation/policy/assert/no-foreach.yaml
test/conformance/chainsaw/policy-validation/policy/assert/ok.yaml

Add more policy validation around policies using kyverno-json:
- make sure a rule with `assert` and `foreach` is rejected
- validate context entry names when `assert` is used to verify we will be able to create the corresponding binding

feat: add more policy validation around policies using kyverno-json

---

pkg/engine/utils/exceptions.go
test/conformance/chainsaw/exceptions/exclude-ephemeral-containers/README.md
test/conformance/chainsaw/exceptions/exclude-ephemeral-containers/chainsaw-test.yaml
test/conformance/chainsaw/exceptions/exclude-ephemeral-containers/exception.yaml
test/conformance/chainsaw/exceptions/exclude-ephemeral-containers/excluded-pod.yaml
test/conformance/chainsaw/exceptions/exclude-ephemeral-containers/policy-assert.yaml
test/conformance/chainsaw/exceptions/exclude-ephemeral-containers/policy.yaml

This PR makes it possible for exceptions to match on ephemeralcontainers by default if they match pods.
Closes #9484 
/kind bug
Added a chainsaw test.

fix: allow exceptions to match Pod/ephemeralcontainers by default

---

pkg/validatingadmissionpolicy/builder.go
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-ephemeral-containers/policy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-ephemeral-containers/validatingadmissionpolicy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-exec-in-pods/chainsaw-test.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-exec-in-pods/ns.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-exec-in-pods/policy-assert.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-exec-in-pods/policy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-exec-in-pods/validatingadmissionpolicy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/block-exec-in-pods/validatingadmissionpolicybinding.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-any-exclude-namespace-match-resource/policy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-any-match-resources-by-names/policy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-all-exclude-one/chainsaw-test.yaml
test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-kind-with-wildcard/validatingadmissionpolicy.yaml

The generated VAPs set `operations` to only `CREATE` and `UPDATE`  in case users don't specify them in the Kyverno policies. This raises an issue when a Kyverno policy matches `pod/exec` in which the operation is of type `CONNECT` but isn't set in the policy definition itself. But, it is configured in the corresponding `validatingwebhookconfiguration`. Since the operations in the Kyverno policy aren't set, the generated VAP sets operations to `CREATE` and `UPDATE`. 
This PR adds all operations in the generated VAP by default.
N/A
/milestone 1.12.1
/kind bug
1. Set the flag `--generateValidatingAdmissionPolicy` to `true` in the admission controller.
2. Create the following policy that blocks exec commands in pods.
```
apiVersion: …
```

fix: set all operations by default in the generated VAP

---

api/kyverno/v1/common_types.go
api/kyverno/v1/spec_types.go
api/kyverno/v2beta1/spec_types.go
pkg/policy/mutate.go
pkg/validation/policy/validate.go
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-configurations-for-mutate-existing/README.md
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-configurations-for-mutate-existing/chainsaw-test.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-configurations-for-mutate-existing/configmaps.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-configurations-for-mutate-existing/mutated-secret-error.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-configurations-for-mutate-existing/mutated-secret.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-configurations-for-mutate-existing/namespaces.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-configurations-for-mutate-existing/policy-ready.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-configurations-for-mutate-existing/policy.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-configurations-for-mutate-existing/secrets.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-mutate-existing-values/README.md
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-mutate-existing-values/chainsaw-test.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-mutate-existing-values/configmaps.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-mutate-existing-values/mutated-secret-error.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-mutate-existing-values/mutated-secret.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-mutate-existing-values/namespaces.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-mutate-existing-values/policy-ready.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-mutate-existing-values/policy.yaml
test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/onpolicyupdate/different-mutate-existing-values/secrets.yaml

This PR adds chainsaw tests for a mutate policy with different values of `mutateExistingOnPolicyUpdate` field.
The 1st chainsaw test defines a policy with two rules, each sets the `mutateExistingOnPolicyUpdate` field with a different value.
The 2nd chainsaw test defines a policy with two rules; one of which doesn't specify the field so it is expected to use the higher level field while the other sets the field.
Related to https://github.com/kyverno/kyverno/issues/5606, https://github.com/kyverno/kyverno/issues/7959

feat: add tests for different values of mutateExistingOnPolicyUpdate

---

test/conformance/chainsaw/rbac/cleanup-policy-with-clusterrole/README.md
test/conformance/chainsaw/rbac/cleanup-policy-with-clusterrole/chainsaw-test.yaml
test/conformance/chainsaw/rbac/cleanup-policy-with-clusterrole/clusterrole.yaml
test/conformance/chainsaw/rbac/cleanup-policy-with-clusterrole/policy-assert.yaml
test/conformance/chainsaw/rbac/cleanup-policy-with-clusterrole/policy.yaml
test/conformance/chainsaw/rbac/mutate-policy-with-clusterrole/README.md
test/conformance/chainsaw/rbac/mutate-policy-with-clusterrole/chainsaw-test.yaml
test/conformance/chainsaw/rbac/mutate-policy-with-clusterrole/clusterrole.yaml
test/conformance/chainsaw/rbac/mutate-policy-with-clusterrole/policy-assert.yaml
test/conformance/chainsaw/rbac/mutate-policy-with-clusterrole/policy.yaml

This PR adds chainsaw tests to check the creation of mutate policy/cleanup policy after it is given the necessary permissions through clusterroles
Related to https://github.com/kyverno/kyverno/pull/10808, https://github.com/kyverno/kyverno/pull/10221

feat: add tests checking policy creation

---

pkg/validation/policy/actions.go

This PR checks the required permissions to generate VAPs if Kyverno policy has `validate.cel` subrule. Previously, the permissions were checked in case the rule is of type Validation but we only need the permissions in case of `cel` subrule.

fix: check permissions for validate.cel subrules only

---

pkg/engine/variables/vars.go
pkg/engine/variables/vars_test.go

Remove extra iterations for nested variable substitution
https://github.com/kyverno/kyverno/issues/10854
1.13

reduce recursions for nested var substitution

---

CODEOWNERS

Adding @YTGhost to codeowners for /pkg/pss
Contributions related to pod security:
https://github.com/kyverno/kyverno/pull/8585 (The commits was squashed)
https://github.com/kubernetes/kubernetes/pull/117059
/cc @realshuting

adding @YTGhost to codeowners

---

.github/workflows/conformance.yaml

Disable fail-fast in conformance.
Currenly, If one job in the conformance matrix fails because of a flake, others are getting cancelled.

chore: disable fail-fast in conformance

---

pkg/pss/utils/mapping.go

Use sync.OnceValue for initialization to avoid concurrent read-write issues.
Closes #11005 

fix: concurrent map read and map write when applying a validate.podSecurity rule

---

pkg/webhooks/updaterequest/generator.go

An empty updaterequest is generated for a cloneList rule when the trigger and source are the same resource (Chainsaw test `test/conformance/chainsaw/generate/clusterpolicy/cornercases/clone-list-sync-same-trigger-source-delete-source`). This PR fixes the issue.

fix: avoid generating empty urs

---

go.mod
go.sum

Closes #11087 
```bash
9:19:[vishal@nirmata kyverno]:bump-docker $ KO_DOCKER_REPO=ghcr.io/vishal-chdhry/kyverno ko build ./cmd/kyverno --bare --tags=release-1.12 --platform=all
2024/09/11 09:19:43 Using base cgr.dev/chainguard/static:latest@sha256:bde549df44d5158013856a778b34d8972cf52bb2038ec886475d857ec7c365ed for github.com/kyverno/kyverno/cmd/kyverno
2024/09/11 09:19:44 Using build config kyverno for github.com/kyverno/kyverno/cmd/kyverno
2024/09/11 09:19:44 Using build config kyverno for github.com/kyverno/kyverno/cmd/kyverno
2024/09/11 09:19:44 Building github.com/kyverno/kyverno/cmd/kyverno for linux/arm64
2024/09/11 09:19:44 Building github.com/kyverno/kyverno/cmd/kyverno for linux/amd64
2024/09/11 09:20:08 Publishing …
```

fix: bump docker in release 1.12

---

.github/actions/setup-build-env/action.yaml
go.mod

Addressing vulnerability `CVE-2024-34156` by upgrading Go version to `v1.23.1`
Closes #11105
milestone 1.12.5
/kind bug
- [x ] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [ x] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.

fix: Updated Go version to v1.23.1 to address CVE-2024-34156

---

cmd/cli/kubectl-kyverno/processor/policy_processor.go

Cherry-picked fix: get ns labels before creating a policy context https://github.com/kyverno/kyverno/pull/10773

fix: get ns labels before creating a policy context (cherry-pick #10773)

---

pkg/engine/handlers/validation/validate_assert.go
pkg/engine/handlers/validation/validate_pss.go
pkg/engine/handlers/validation/validate_resource.go
pkg/engine/handlers/validation/validate_resource_test.go
test/conformance/chainsaw/reports/admission/update-deployment/README.md
test/conformance/chainsaw/reports/admission/update-deployment/chainsaw-test.yaml
test/conformance/chainsaw/reports/admission/update-deployment/deployment.yaml
test/conformance/chainsaw/reports/admission/update-deployment/policy-assert.yaml
test/conformance/chainsaw/reports/admission/update-deployment/policy.yaml
test/conformance/chainsaw/reports/admission/update-deployment/report-assert.yaml
test/conformance/chainsaw/reports/admission/update-deployment/update-deployment.yaml

This PR skips processing the oldOject for the updated resource in case of audit policies.
Closes #10169 
/kind bug
1. Create a policy:
```
metadata:
name: require-multiple-replicas
annotations:
policies.kyverno.io/category: Best Practises
policies.kyverno.io/minversion: 1.9.2
policies.kyverno.io/severity: low
policies.kyverno.io/subject: Deployment,StatefulSet
policies.kyverno.io/title: Require Multiple Replicas
policies.kyverno.io/scored: "false"
spec:
rules:
- name: require-multiple-replicas
match:
any:
- resources:
kinds:
- Deployment
- StatefulSet
operations:
- CREATE
- UPDATE
validate:
pattern:
spec:
replicas: ">1"
validationFailureAction: Audit
```
2. …

fix: skip processing the oldObject for audit policies

---

pkg/autogenv2/autogen.go
pkg/autogenv2/autogen_test.go
pkg/autogenv2/log.go

This PR is just a package initialization for the new approach to autogen. It only includes interfaces and a random podextraction logic and some tests around it to get started with the newer approach.
This is a draft PR which needs further discussion with the maintainers.

Package initialization for new autogen approach with some tests

---

.github/workflows/helm-test.yaml

Due to github actions defaulting `ubuntu-latest` to ubuntu 24, and the action that installs python only supporting python 3.7 till ubuntu 22, python installations now fail. This PR is to increase the version that is supported on ubuntu 24
example failed run: https://github.com/kyverno/kyverno/actions/runs/11345105260/job/31551251507?pr=11208
/kind failing-test
Upgrade python version in installation

chore: Bump python installation in helm test to 3.8.13 as the installation action doesnt support ubuntu 24

---

charts/kyverno/Chart.yaml
charts/kyverno/templates/hooks/post-delete-configmap.yaml

Helm chart 3.3.0 and 3.3.1 (kyverno v1.13.0) uses a pre-delete helm hook to clean up the Kyverno configmap (won't handled by helm uninstall automatically because the CM is preserved `helm.sh/resource-policy: "keep"` by default) upon uninstallation. This could be an issue if any Enforce policy is installed, as the configmap has the default value for webhook `namespaceSelector` to exclude the kyverno namespace.
This PR fixes the issue by switch the job to use post-delete helm hook, the configmap will be cleaned up as the last step upon uninstallation.

fix: switch configmap removal to use post-delete helm hook

---

charts/kyverno/templates/_helpers/_image.tpl

This fix behavior when both `global.image.registry` and specific eg. `policyReportsCleanup.image.registry` are set. 
Before this change `global.image.registry` has priority upon more specific setting for "component".
We need this change to be able to use registry pull through cache. We are setting `global.image.registry` to our GitHub proxy and we need to set different registry for `policyReportsCleanup` and `webhooksCleanup` since they are using bitnami images on Docker Hub.
/kind bug
We are proposing change of priority for determination with registry to use to prefer more specific registry instead of global one.
```yaml
global:
image:
registry: "ghcr.io"
policyReportsCleanup:
image:
registry: "docker.io"
webhooksCleanup:
image:
registry: "docker.io"
```
Befor change
```yaml
apiVersion: …
```

fix(chart): correct behavior for global image registry

---

pkg/engine/handlers/validation/validate_resource.go

This PR adds the nil check before accessing a rule response, this issue was introduced in this method [validateOldObject](https://github.com/kyverno/kyverno/blob/main/pkg/engine/handlers/validation/validate_resource.go#L177) where the nil rule response can be returned.
Closes https://github.com/kyverno/kyverno/issues/11491.
- [] I have sent the draft PR to add or update [the documentation](https://github.com/kyverno/website) and the link is:

fix: panic for nil rule response when processing old object

---

pkg/engine/jmespath/functions.go
pkg/engine/jmespath/functions_test.go

While  SHA256 is secure than other algorithms, SHA256 hashes are 64 characters, so can't be used as part of many Kubernetes [resource names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names) and [annotation keys](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set) which are often limited to <=63 characters. To address this limitation, SHA-1 and MD5 hash functions have been added as alternatives. These algorithms generate shorter hashes (less than 64 characters), making them compatible with Kubernetes naming constraints.
- Adds SHA1 and MD5 hash functions to JMESPath
- Adds Unit tests for the respective functions
- Solves the issue #11506
A clone …

Add SHA1 and MD5 hash functions to JMESPath

---

pkg/controllers/webhook/controller.go

This PR fixes webhook reconciliation based on the policy type. Before this fix, there are duplicate reconciliations performed for mutatingwebhookconfiguration and validatingwebhookconfiguration. As you can see [here](https://github.com/kyverno/kyverno/blob/d618da161c0799eafb05d3542ce9119597947cf1/pkg/controllers/webhook/controller.go#L666-L687), `c.updatePolicyStatuses(ctx)` is invoked for both `config.MutatingWebhookConfigurationName` and `config.ValidatingWebhookConfigurationName` while it doesn't take the webhook type, so when Kyverno reconciles mutating webhook, there is empty validating webhook to reconcile thus updating all validate policies to `NotReady`, and later when it reconciles validating webhook, it updates those `NotReady` validate policies to `Ready`.
Relates to …

fix: update explicit webhook based on the policy type

---

pkg/background/generate/data.go

When evaluating a `generate` rule, if fetching the target object fails with a non-404 error, we currently do not catch that, resulting in a `nilref` panic when later trying to read data from it.
Fixes #11572
/milestone 1.13.2
/kind bug
Don't panic.
N/A

fix: Add missing error check

---

charts/kyverno-policies/README.md
charts/kyverno-policies/templates/baseline/disallow-capabilities.yaml
charts/kyverno-policies/templates/baseline/disallow-host-namespaces.yaml
charts/kyverno-policies/templates/baseline/disallow-host-path.yaml
charts/kyverno-policies/templates/baseline/disallow-host-ports.yaml
charts/kyverno-policies/templates/baseline/disallow-host-process.yaml
charts/kyverno-policies/templates/baseline/disallow-privileged-containers.yaml
charts/kyverno-policies/templates/baseline/disallow-proc-mount.yaml
charts/kyverno-policies/templates/baseline/disallow-selinux.yaml
charts/kyverno-policies/templates/baseline/restrict-apparmor-profiles.yaml
charts/kyverno-policies/templates/baseline/restrict-seccomp.yaml
charts/kyverno-policies/templates/baseline/restrict-sysctls.yaml
charts/kyverno-policies/templates/other/require-non-root-groups.yaml
charts/kyverno-policies/templates/restricted/disallow-capabilities-strict.yaml
charts/kyverno-policies/templates/restricted/disallow-privilege-escalation.yaml
charts/kyverno-policies/templates/restricted/require-run-as-non-root-user.yaml
charts/kyverno-policies/templates/restricted/require-run-as-nonroot.yaml
charts/kyverno-policies/templates/restricted/restrict-seccomp-strict.yaml
charts/kyverno-policies/templates/restricted/restrict-volume-types.yaml
charts/kyverno-policies/values.yaml

When deploy **kyverno-policies** helm chart it specifies versions as annotations of each policy:
- **kyverno.io/kyverno-version**: Automatically detects installed version of kyverno. If version couldn't be detected value taken from Chart.yaml AppVersion field.
- **kyverno.io/kubernetes-version**: Takes from values.yaml for which new key been added there.
/closes https://github.com/kyverno/policies/issues/1165
@realshuting
/milestone release-1.13
My PR does not contain any new functionalities to Kyverno. Documentation for helm chart been updated in README.md and comments been added to values.yaml
/kind bug
This change maintain appropriate annotations to Kubernetes resources when deploy policy using kyverno-policies helm chart. It gives users control to which versions of Kubernetes policies …

fix: kubernetes and kyverno version annotations in kyverno-policies helm chart (#1165)

---

cmd/cli/kubectl-kyverno/processor/policy_processor.go

Using the apply command with mutate policies creates a file with the name of the resource suffixed by -mutated and this file is opened in create mode. This has the effect of the file being overridden for resources with the same name
#11615 
/kind bug
Opening the file with append mode
`pol.yaml`
```yaml
kind: Policy
metadata:
name: testpolicy
namespace: test
spec:
rules:
- name: mutate
match:
any:
- resources:
kinds:
- apps/v1/Deployment
- Service
mutate:
metadata:
annotations:
test.kyverno: mutated
```
`svc.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
namespace: test
name: resource
spec:
type: ClusterIP
```
`depl.yaml`
```yaml
metadata:
namespace: …
```

fix: Open the mutated resources file in append mode to allow additions to it

---

charts/kyverno-policies/Chart.yaml
charts/kyverno-policies/templates/baseline/disallow-capabilities.yaml
charts/kyverno-policies/templates/baseline/disallow-host-namespaces.yaml
charts/kyverno-policies/templates/baseline/disallow-host-path.yaml
charts/kyverno-policies/templates/baseline/disallow-host-ports.yaml
charts/kyverno-policies/templates/baseline/disallow-host-process.yaml
charts/kyverno-policies/templates/baseline/disallow-privileged-containers.yaml
charts/kyverno-policies/templates/baseline/disallow-proc-mount.yaml
charts/kyverno-policies/templates/baseline/restrict-apparmor-profiles.yaml
charts/kyverno-policies/templates/baseline/restrict-seccomp.yaml
charts/kyverno-policies/templates/baseline/restrict-sysctls.yaml
charts/kyverno-policies/templates/restricted/disallow-privilege-escalation.yaml
charts/kyverno-policies/templates/restricted/require-run-as-non-root-user.yaml
charts/kyverno-policies/templates/restricted/require-run-as-nonroot.yaml
charts/kyverno-policies/templates/restricted/restrict-seccomp-strict.yaml
charts/kyverno-policies/templates/restricted/restrict-volume-types.yaml

Currently only a couple of Kyverno policies from its chart allow correct customization of `policyExclude`, while all the others simply get overriden, breaking multiple exclusions from different places (say, a default platform deployment of `kyverno-policies` with some `policyExclude` and specific teams needing to add their own customizations on top of it.
Without this PR add up customizations won't work in some of the shipped policies.
Unaffected policies are only:
- `./restricted/disallow-capabilities-strict.yaml`
- `./baseline/disallow-selinux.yaml`
- `./other/require-non-root-groups.yaml`
Fixes #11533 
Either `1.13.2` or simply a minor semver update of the `kyverno-policies`chart if it's simpler given it doesn't affect Kyverno itself, only templates.
I guess it's a `bug` though it's in …

fix(policy chart): fix the merging of policyExclude customizations to avoid wrong overrides (#11533)

---

charts/kyverno/templates/config/_helpers.tpl
config/install-latest-testing.yaml

This PR adds a type conversion function in Helm to fix the breaking change of switch a list to an object.
Closes https://github.com/kyverno/kyverno/issues/11661.
Upgrade from 3.2.6 to the latest:
3.2.6 values.yaml:
```yaml
config:
webhooks:
- namespaceSelector:
- key: kubernetes.io/metadata.name
operator: NotIn
values:
- test
```
validating webhook:
```
✗ kg validatingwebhookconfigurations  kyverno-resource-validating-webhook-cfg -o yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
name: kyverno-resource-validating-webhook-cfg
webhooks:
- admissionReviewVersions:
- v1
- key: kubernetes.io/metadata.name
operator: NotIn
values:
- test
- …
```

fix: add conversion function in Helm template

---

charts/kyverno/Chart.yaml
charts/kyverno/README.md
charts/kyverno/templates/_helpers/_image.tpl
charts/kyverno/templates/background-controller/_helpers.tpl
charts/kyverno/templates/cleanup-controller/_helpers.tpl
charts/kyverno/templates/reports-controller/_helpers.tpl
charts/kyverno/values.yaml

This PR fixies bug with was introduced with my previous PR https://github.com/kyverno/kyverno/pull/11482
Closes #11579
/kind bug
```
$ helm template ./charts/kyverno | grep image:
image:
image:
image:
image:
image:
image:
image: "ghcr.io/kyverno/kyvernopre:latest"
image: "ghcr.io/kyverno/kyverno:latest"
image: "ghcr.io/kyverno/background-controller:latest"
image: "kyverno/cleanup-controller:latest"
image: "kyverno/reports-controller:latest"
image: busybox:1.35
image: busybox:1.35
image: busybox:1.35
image: busybox:1.35
image: busybox:1.35
image: "bitnami/kubectl:1.30.2"
image: "bitnami/kubectl:1.30.2"
image: "ghcr.io/kyverno/kyverno-cli:latest"
image: "bitnami/kubectl:1.30.2"
```
```
$ helm template ./charts/kyverno --set global.image.registry=myregistry | grep image:
image:
image:
image: …
```

fix(chart): global image registry bug in 3.3.3

---

cmd/cli/kubectl-kyverno/apis/v1alpha1/test_result.go
cmd/cli/kubectl-kyverno/config/crds/cli.kyverno.io_tests.yaml
cmd/cli/kubectl-kyverno/data/crds/cli.kyverno.io_tests.yaml
docs/user/cli/crd/index.html
docs/user/cli/crd/kyverno_kubectl.v1alpha1.html

- The currently existing PatchedResource field has a misleading name, leading to users believing that it can only take a yaml containing a single resource. Another field with proper naming is added until this field is removed completely.
- Generate the new CRD from the struct.
closes: #11629
/kind bug

chore: Add a new field in the test results CRD to specify patched resources

---

cmd/cli/kubectl-kyverno/apis/v1alpha1/test_result.go
cmd/cli/kubectl-kyverno/commands/test/command.go
cmd/cli/kubectl-kyverno/deprecations/check.go
docs/user/cli/crd/index.html
docs/user/cli/crd/kyverno_kubectl.v1alpha1.html
test/cli/scenarios_to_cli/other/scenario_mutate_endpoint/kyverno-test.yaml
test/cli/scenarios_to_cli/other/scenario_mutate_pod_spec/kyverno-test.yaml
test/cli/test-mutate/add-default-resources/kyverno-test.yaml
test/cli/test-mutate/bug-demo/kyverno-test.yaml
test/cli/test-mutate/connection-draining/kyverno-test.yaml
test/cli/test-mutate/foreach/addIfNotPresent/kyverno-test.yaml
test/cli/test-mutate/foreach/cumulativePatch/kyverno-test.yaml
test/cli/test-mutate/foreach/kyverno-test.yaml
test/cli/test-mutate/foreach/replaceRegistry/kyverno-test.yaml
test/cli/test-mutate/global-anchor/kyverno-test.yaml
test/cli/test-mutate/karpenter-annotations-to-nodeselector/kyverno-test.yaml
test/cli/test-mutate/kyverno-test.yaml
test/cli/test-mutate/patched-resource/kyverno-test.yaml
test/cli/test/mixed-deprecated/kyverno-test.yaml
test/cli/test/mixed/kyverno-test.yaml
test/cli/test/mutate-keda-scaled-object/kyverno-test.yaml
test/cli/test/secret/kyverno-test.yaml
test/cli/test/wildcard_mutate/kyverno-test.yaml

This PR checks that the expected `patchedResources` from the `kyverno-test` files is equal to the mutated resource returned from the engine. There is also a warning added in case the user used the deprecated field `patchResource`.
Related to https://github.com/kyverno/kyverno/pull/11297
Closes #11685 
/milestone 1.13.2
/kind bug
1. `policy.yaml`:
```
apiVersion: kyverno.io/v2beta1
metadata:
name: secret-store-defaults
spec:
rules:
- name: vault-server-default
match:
any:
- resources:
kinds:
- SecretStore
mutate:
spec:
provider:
(vault):
+(server): ${VAULT_ADDR}
```
2. `resource.yaml`:
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
name: order-processor
spec:
provider: …
```

fix: check the patchedResources in kyverno-test

---

cmd/cli/kubectl-kyverno/commands/test/command.go
cmd/cli/kubectl-kyverno/commands/test/compare.go
go.mod

When running tests locally with `kyverno test`, even with `--detailed-results` there is currently no way to make the CLI actually show what the diff was.
This change adds some logging which (only if you've specified `-v=4` or higher) will log a textual diff between expected and actual results.
#9727
Not sure; this can easily be backported, but should it be?
/kind feature

feat: Show textual diff when generate test fails

---

cmd/cli/kubectl-kyverno/commands/apply/command.go
cmd/cli/kubectl-kyverno/commands/apply/print.go
docs/user/cli/commands/kyverno_apply.md

Added a new flag `--output-format` (to the Kyverno CLI, which enables the kyverno apply command to output results in either YAML (default) or JSON format for easier integration with tools and automation workflows.
Policy and Deployment manifest:
```
apiVersion: admissionregistration.k8s.io/v1
metadata:
name: "check-deployment-replicas"
spec:
resourceRules:
- apiGroups:
- apps
apiVersions:
- v1
operations:
- CREATE
- UPDATE
resources:
- deployments
validations:
- expression: object.spec.replicas <= 5
```
```
metadata:
name: nginx-pass
spec:
replicas: 2
selector:
matchLabels:
app: nginx-pass
template:
metadata:
labels:
app: nginx-pass
spec:
containers:
- name: nginx-server
image: nginx
```
Run the kyverno …

Add flag for JSON output in policy reports

---

pkg/cel/policy/compiler.go
pkg/cel/policy/policy.go

This PR adds auditAnnotation expressions in the CEL compiler as it will be used later in the policy report properties.
Related to #11894

feat: add auditAnnotation in CEL Compiler

---

cmd/cli/kubectl-kyverno/processor/vap_processor.go
cmd/cli/kubectl-kyverno/utils/common/fetch.go
cmd/cli/kubectl-kyverno/utils/common/validating_admission_resources.go
cmd/kyverno/main.go
cmd/reports-controller/main.go
pkg/admissionpolicy/api.go
pkg/admissionpolicy/builder.go
pkg/admissionpolicy/compiler.go
pkg/admissionpolicy/kyvernopolicy_checker.go
pkg/admissionpolicy/kyvernopolicy_checker_test.go
pkg/admissionpolicy/log.go
pkg/admissionpolicy/matcher.go
pkg/admissionpolicy/utils.go
pkg/admissionpolicy/validate.go
pkg/admissionpolicy/validate_test.go
pkg/admissionpolicy/version_converter.go
pkg/controllers/report/resource/controller.go
pkg/controllers/report/utils/scanner.go
pkg/controllers/validatingadmissionpolicy-generate/controller.go
pkg/engine/handlers/validation/validate_cel.go
pkg/engine/internal/match.go
pkg/validation/policy/actions.go
pkg/validation/policy/validate.go

1. Rename the package `validatingadmissionpolicy` to `admissionpolicy`. This package is used in generating VAPs, CLI and reporting system.
2. Delete the [CEL](https://github.com/kyverno/kyverno/tree/main/pkg/utils/cel) package and add it in the `admissionpolicy` package since it uses the upstream functions to compile VAPs for the CLI.

chore: move CEL package to admissionpolicy package

---

test/cli/test-validating-admission-policy/check-deployment-labels/policy.yaml
test/cli/test-validating-admission-policy/check-deployments-replica/policy.yaml
test/cli/test-validating-admission-policy/disallow-host-path/policy.yaml
test/cli/test-validating-admission-policy/with-bindings-1/policy.yaml
test/cli/test-validating-admission-policy/with-bindings-2/policy.yaml
test/cli/test-validating-admission-policy/with-bindings-3/policy.yaml
test/cli/test-validating-admission-policy/with-bindings-4/policy.yaml
test/cli/test-validating-admission-policy/with-match-conditions/disallow-host-path.yaml
test/cli/test-validating-admission-policy/with-namespaceObject-1/policy.yaml
test/cli/test-validating-admission-policy/with-namespaceObject-2/policy.yaml
test/cli/test/validating-admission-policies/disallow-host-path/disallow-host-path.yaml

This PR uses `v1` instead of `v1beta1` for VAPs in the tests.

chore: use v1 of VAPs in the tests

---

cmd/cli/kubectl-kyverno/commands/test/output.go

For Kyverno test command, if the result specified in the `kyverno-test` file is `fail`, and the actual result returned from the engine response is `pass`, the overall result printed out in the table is `pass` which is incorrect. This PR fixes the `Result` column in the table.
Closes #11814
/milestone 1.13.3
/kind bug
1. `policy.yaml`:
```
apiVersion: admissionregistration.k8s.io/v1
metadata:
name: deny-host-ipc
spec:
resourceRules:
- apiGroups: ["apps"]
apiVersions: ["v1"]
operations: ["CREATE", "UPDATE"]
resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
- apiGroups: ["batch"]
apiVersions: ["v1"]
operations: ["CREATE", "UPDATE"]
resources: …
```

fix the result column for Kyverno test

---

pkg/autogen/v1/autogen.go
pkg/autogen/v1/autogen_test.go

This PR removes the following functions from the autogen package since they aren't used anywhere in the codebase:
1. GetSupportedControllers()
2. GetRequestedControllers()
3. GetControllers()

chore: remove unused functions in autogen

---

cmd/internal/flag.go

Make flags compatible with controller-runtime (`kubeconfig` flag may be defined twice).

fix: make flags compatible with controller-runtime

---

api/kyverno/v2alpha1/spec_types.go
api/kyverno/v2alpha1/zz_generated.deepcopy.go
charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_validatingpolicies.yaml
cmd/cli/kubectl-kyverno/data/crds/kyverno.io_validatingpolicies.yaml
config/crds/kyverno/kyverno.io_validatingpolicies.yaml
config/install-latest-testing.yaml
docs/user/crd/index.html
docs/user/crd/kyverno.v2alpha1.html
pkg/client/applyconfigurations/kyverno/v2alpha1/validatingpolicyspec.go

This PR adds the `validationAction` in the ValidatingPolicies. This field doesn't exist in the VAP spec, it exists in the binding.

feat: add validation action to VPs

---

Makefile
charts/kyverno/README.md
charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_celpolicyexceptions.yaml
charts/kyverno/values.yaml
cmd/cli/kubectl-kyverno/data/crds/kyverno.io_celpolicyexceptions.yaml
config/install-latest-testing.yaml

This PR adds the celpolicyexceptions CRD in the helm chart.

chore: add celpolicyexceptions in helm chart

---

pkg/cel/autogen/rule.go
pkg/cel/autogen/rule_test.go
pkg/controllers/webhook/validatingpolicy.go
test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-cronjobs/check-autogen.yaml
test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-statefulsets/check-autogen.yaml
test/conformance/chainsaw/validating-policies/autogen/should-autogen/check-autogen.yaml

This PR uses `object.kind` instead of `object.Kind` for the auto-generated match conditions

fix CEL autogen

---

test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-cronjobs/bad-deployment.yaml
test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-cronjobs/chainsaw-test.yaml
test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-cronjobs/good-deployment.yaml
test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-statefulsets/bad-statefulset.yaml
test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-statefulsets/chainsaw-test.yaml
test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-statefulsets/good-statefulset.yaml

This PR adds resource manifests i,e bad/good deployments and statefulsets in autogen chainsaw tests.

chore: add resource manifests in autogen tests

---

cmd/kyverno/main.go
pkg/admissionpolicy/builder.go
pkg/controllers/validatingadmissionpolicy-generate/controller.go
pkg/controllers/validatingadmissionpolicy-generate/utils.go
test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-cel-exception/bad-deployment.yaml
test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-cel-exception/chainsaw-test.yaml
test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-cel-exception/exception.yaml
test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-cel-exception/policy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-cel-exception/skipped-deployment.yaml
test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-cel-exception/validatingadmissionpolicy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-cel-exception/validatingadmissionpolicybinding.yaml
test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-multiple-exceptions/chainsaw-test.yaml
test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-multiple-exceptions/exception.yaml
test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-multiple-exceptions/policy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-multiple-exceptions/validatingadmissionpolicy.yaml
test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-multiple-exceptions/validatingadmissionpolicybinding.yaml

This PR generates VAPs given cel policy exceptions.
Related to #12018 
1. Create a ValidatingPolicy:
```
apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
name: check-deployment-labels
spec:
validationActions:
- Deny
resourceRules:
- apiGroups:   [apps]
apiVersions: [v1]
operations:  [CREATE, UPDATE]
resources:   [deployments]
variables:
- name: environment
expression: >-
has(object.metadata.labels) && 'env' in object.metadata.labels && object.metadata.labels['env'] == 'prod'
validations:
- expression: >-
variables.environment == true
message: >-
Deployment labels must be env=prod
```
2. Create a CELPolicyException:
```
apiVersion: policies.kyverno.io/v1alpha1
kind: CELPolicyException
metadata:
name: check-deployment-name
spec:
policyRefs:
- name: …
```

feat: generate VAPs given celexceptions

---

charts/kyverno/templates/reports-controller/clusterrole.yaml
cmd/reports-controller/main.go
config/install-latest-testing.yaml
pkg/controllers/report/background/controller.go
pkg/controllers/report/utils/scanner.go
pkg/controllers/report/utils/utils.go

Support CELPolicyException in Report Controller
Closes https://github.com/kyverno/kyverno/issues/12274.
/milestone 1.14.0

feat: support CELPolicyException in the report-controller

---

pkg/cel/libs/context/impl_test.go
pkg/cel/libs/context/types.go
pkg/cel/policy/context.go
pkg/cel/policy/fake_context.go

Use pointer in context config map getter.

fix: use pointer in context config map getter

---

pkg/cel/policy/policy.go

Fixes: `admission webhook "vpol.validate.kyverno.svc-fail" denied the request: Policy check-deployment-labels failed: failed to evaluate message expression: invalid input, wanted Activation or map[string]any, got: (policy.evaluationData)`

Fix: data access in message expressions

---

test/conformance/chainsaw/validating-policies/subresources/block-ephemeral-containers/chainsaw-test.yaml
test/conformance/chainsaw/validating-policies/subresources/block-ephemeral-containers/pod.yaml
test/conformance/chainsaw/validating-policies/subresources/block-ephemeral-containers/policy-assert.yaml
test/conformance/chainsaw/validating-policies/subresources/block-ephemeral-containers/policy.yaml

I don't think we can automatically match `pods/ephemeralcontainers` for a pod's rule, as `spec.matchConstraints` is evaluated through CEL lib, the policy has to match the subresource specifically to apply.
cc @Mohdcode

chore: add a chainsaw test for vpol to block ephemeral containers

---

cmd/cli/kubectl-kyverno/commands/apply/command.go
cmd/cli/kubectl-kyverno/commands/test/test.go
cmd/cli/kubectl-kyverno/processor/vap_processor.go

Remove unused field in vap processor.

chore: remove unused field in vap processor

---

test/conformance/chainsaw/imagevalidatingpolicies/context/globalreference/chainsaw-test.yaml

Disable global context test, the test is not passing for some reasons, i will fix the test later but for now we're struggling merging any PRs.

chore: disable global context test

---

cmd/cli/kubectl-kyverno/commands/apply/command.go
cmd/cli/kubectl-kyverno/commands/apply/command_test.go

Forbid json and k8s resources at the same time in the CLI.

fix: forbid json and k8s resources at the same time in the CLI

---

.devcontainer/Dockerfile
.github/actions/setup-build-env/action.yaml
go.mod

This PR fixes a critical vulnerability (CVE-2025-22871) in the Go standard net/http package. This vulnerability could allow for HTTP request smuggling due to how bare line-feed (LF) characters are accepted as line terminators in chunk-size lines during chunked transfer encoding. This is a security fix that updates the Go version used in Kyverno to patched versions.
Closes #12701
/kind bug
/kind security
This PR updates the Go version from 1.23.4 to 1.23.8 to address the CVE-2025-22871 vulnerability. The following files were updated:
1. Updated `go.mod` from Go 1.23.4 to Go 1.23.8
2. Updated GitHub Actions build setup from Go ~1.23.1 to Go ~1.23.8
3. Updated development container Dockerfile from Go 1.21.3 to Go 1.23.8
These changes ensure …

fix: Update Go version to fix CVE-2025-22871 vulnerability

---

cmd/cli/kubectl-kyverno/apis/v1alpha1/test_result.go
cmd/cli/kubectl-kyverno/commands/test/command.go
cmd/cli/kubectl-kyverno/commands/test/output.go
cmd/cli/kubectl-kyverno/commands/test/test.go
cmd/cli/kubectl-kyverno/config/crds/cli.kyverno.io_tests.yaml
cmd/cli/kubectl-kyverno/data/crds/cli.kyverno.io_tests.yaml
cmd/cli/kubectl-kyverno/processor/policy_processor.go
docs/user/cli/crd/index.html
docs/user/cli/crd/kyverno_kubectl.v1alpha1.html
test/cli/test-image-validating-policy/sample-policy/bad-pod.yaml
test/cli/test-image-validating-policy/sample-policy/good-pod.yaml
test/cli/test-image-validating-policy/sample-policy/kyverno-test.yaml
test/cli/test-image-validating-policy/sample-policy/policy.yaml
test/cli/test-validating-policy/check-deployment-labels/deployment1.yaml
test/cli/test-validating-policy/check-deployment-labels/deployment2.yaml
test/cli/test-validating-policy/check-deployment-labels/kyverno-test.yaml
test/cli/test-validating-policy/check-deployment-namespace/kyverno-test.yaml
test/cli/test-validating-policy/check-deployment-namespace/policy.yaml
test/cli/test-validating-policy/check-deployment-namespace/resources.yaml
test/cli/test-validating-policy/check-deployments-replica/deployment1.yaml
test/cli/test-validating-policy/check-deployments-replica/kyverno-test.yaml
test/cli/test-validating-policy/disallow-host-path/kyverno-test.yaml

1. Add a field named `isImageValidatingPolicy` in the kyverno-test file.
2. Fix an error related to converting GVK to GVR. The main issue is that we create a fake client for the `test` command and [this](https://github.com/kyverno/kyverno/blob/c7366b88645e608284961e955655a1465ba47a20/cmd/cli/kubectl-kyverno/commands/test/test.go#L375-L379) part is executed which shouldn't be.
Tests are added for both ValidatingPolicies and ImageValidatingPolicies.
Closes #12707 
Closes #12668

fix VPOL and IVPOL for Kyverno test command

---

Makefile
test/cli/test-cel-exceptions/check-deployment-labels/kyverno-test.yaml
test/cli/test-exceptions/exceptions-3/exception.yaml
test/cli/test-validating-policy/check-deployment-namespace/kyverno-test.yaml
test/cli/test-validating-policy/check-deployment-namespace/values.yaml

Multiple tests are added in the CLI directory but they don't run in the workflow. This PR adds the following CLI test directories to the workflow:
1. test/cli/test-validating-admission-policy
2. test/cli/test-validating-policy
3. test/cli/test-image-validating-policy
4. test/cli/test-exceptions
5. test/cli/test-cel-exceptions

chore: add local CLI tests for the new policy types in the workflow

---

api/policies.kyverno.io/v1alpha1/imageverification_policy.go
api/policies.kyverno.io/v1alpha1/validating_policy.go
charts/kyverno/charts/crds/templates/policies.kyverno.io/policies.kyverno.io_imagevalidatingpolicies.yaml
charts/kyverno/charts/crds/templates/policies.kyverno.io/policies.kyverno.io_validatingpolicies.yaml
cmd/cli/kubectl-kyverno/data/crds/policies.kyverno.io_imagevalidatingpolicies.yaml
cmd/cli/kubectl-kyverno/data/crds/policies.kyverno.io_validatingpolicies.yaml
config/crds/policies.kyverno.io/policies.kyverno.io_imagevalidatingpolicies.yaml
config/crds/policies.kyverno.io/policies.kyverno.io_validatingpolicies.yaml
config/install-latest-testing.yaml
docs/user/crd/index.html

This PR adds a kubebuilder marker on the field `failurePolicy` so that its value would be either Fail or Ignore. It also updates the comments on some of the fields, as it isn't relevant.

fix: restrict failurePolicy to either Fail or Ignore

---

api/policies.kyverno.io/v1alpha1/imageverification_policy.go
api/policies.kyverno.io/v1alpha1/validating_policy.go
charts/kyverno/charts/crds/templates/policies.kyverno.io/policies.kyverno.io_imagevalidatingpolicies.yaml
cmd/cli/kubectl-kyverno/data/crds/policies.kyverno.io_imagevalidatingpolicies.yaml
config/crds/policies.kyverno.io/policies.kyverno.io_imagevalidatingpolicies.yaml
config/install-latest-testing.yaml
pkg/cel/engine/ivpolprovider.go
pkg/cel/engine/provider.go
test/conformance/chainsaw/image-validating-policies/validation-checks/invalid-action/chainsaw-test.yaml
test/conformance/chainsaw/image-validating-policies/validation-checks/invalid-action/policy.yaml

This PR restricts the validationActions field in IVPOLs to be either Deny, Audit or Warn.

fix: restrict validationActions in IVPOLs

---

Makefile

Update codegen api docs targets to remove go path shim.

chore: update codegen api docs targets

---

Makefile

Update codegen crds targets to remove go path shim usage.

chore: update codegen crds targets

---

pkg/cel/matching/matcher.go
pkg/cel/matching/predicates/namespace/matcher.go
pkg/cel/matching/predicates/namespace/matcher_test.go

fix: rewrite cel/matching package with upstream code (cherry-pick #12929)

fix: rewrite cel/matching package with upstream code (cherry-pick #12929)

---

api/policies.kyverno.io/v1alpha1/imagevalidating_policy.go
api/policies.kyverno.io/v1alpha1/zz_generated.deepcopy.go
charts/kyverno/charts/crds/templates/policies.kyverno.io/policies.kyverno.io_imagevalidatingpolicies.yaml
cmd/cli/kubectl-kyverno/commands/apply/command.go
cmd/cli/kubectl-kyverno/data/crds/policies.kyverno.io_imagevalidatingpolicies.yaml
config/crds/policies.kyverno.io/policies.kyverno.io_imagevalidatingpolicies.yaml
config/install-latest-testing.yaml
docs/user/crd/index.html
docs/user/crd/kyverno_cel_policies.v1alpha1.html
pkg/cel/policies/ivpol/engine/engine.go
pkg/imageverification/evaluator/compiler.go
pkg/imageverification/evaluator/policy.go
test/conformance/chainsaw/image-validating-policies/report/admission/policy.yaml
test/conformance/chainsaw/image-validating-policies/report/admission/report.yaml

Support AuditAnnotations in ivpols

add support for auditAnnotations in ivpols

---

pkg/cel/policies/vpol/validate.go

Ensure that MatchConditions are required for policies applied in an Kubernetes Cluster

fix: validate required match constraints in kubernetes env

---

cmd/cli/kubectl-kyverno/commands/apply/command.go

Fix Kyverno 1.14.0 cannot map gvk to gvr for custom resources.
Fixes #12916

fix: Kyverno 1.14.0 cannot map gvk to gvr for custom resources

---

cmd/cli/kubectl-kyverno/utils/common/fetch.go
pkg/admissionpolicy/validate.go
pkg/admissionpolicy/validate_test.go
pkg/controllers/report/resource/controller.go

This PR fixes the [GetKinds()](https://github.com/kyverno/kyverno/blob/584d3b5a42386d49b991eb7321162a237853b054/pkg/admissionpolicy/validate.go#L31-L73) function. Its purpose is to fetch the resource rules from the policy (vap, vp, or ivpol) and convert it into kind. It is used in the CLI to fetch resources from cluster for VAPs, and it is also used in the scanner.

fix: get kinds from vaps, vpols, and ivpols

---

Makefile
scripts/config/kind/codegen.yaml

Create a dedicated cluster when generating api-group-resources (cherry-pick #13015).

chore: create a dedicated cluster when generating api-group-resources (cherry-pick #13015)

---

pkg/cel/policies/vpol/compiler/compiler.go

fix: don't register custom libs when compiling match conditions (cherry-pick #13032)

fix: don't register custom libs when compiling match conditions (cherry-pick #13032)

---

go.mod
go.sum

Closes https://github.com/kyverno/kyverno/issues/13000.

chore: bump github.com/golang-jwt/jwt/v5 from 5.2.1 to 5.2.2

---

pkg/background/generate/clone.go

continues code execution when an error occurs and the source list is nil.
#11923 
/milstone 1.14.2

fix: continue loop when a list error occurs

---

charts/kyverno/Chart.yaml
charts/kyverno/templates/admission-controller/clusterrole.yaml
config/install-latest-testing.yaml

This PR removes the `delete` permission for exceptions in the admission controller.

fix: remove the delete permission of exceptions

---

test/conformance/chainsaw/verifyImages/clusterpolicy/standard/update-multi-containers/chainsaw-test.yaml

Skip chainsaw test based on deleted image.

fix: skip chainsaw test based on deleted image

---

pkg/engine/wildcards/wildcards.go
pkg/engine/wildcards/wildcards_test.go

The `getValueAsStringMap` function would previously panic when encountering nil or non-string values in map structures, which could be triggered by malformed JMESPath expressions using the {{@}} variable with non-existent functions.
This commit:
1. Adds proper nil checking before type assertions
2. Uses type switching to safely handle non-string values
3. Adds comprehensive test cases to verify the fix works with various input types
Increases test coverage from 16% to 70%.

fix(wildcards): nil values in JMESPath var subst 

---

Makefile
charts/kyverno/charts/crds/README.md
charts/kyverno/charts/crds/templates/policies.kyverno.io/policies.kyverno.io_generatingpolicies.yaml
charts/kyverno/charts/crds/templates/policies.kyverno.io/policies.kyverno.io_mutatingpolicies.yaml
charts/kyverno/charts/crds/values.yaml
config/install-latest-testing.yaml

This PR adds the CRDs of the MutatingPolicies and GeneratingPolicies in the helm chart.
Related to https://github.com/kyverno/kyverno/issues/11638

chore: add mpol and gpol crds in helm chart

---

Makefile
cmd/cli/kubectl-kyverno/data/crds/policies.kyverno.io_generatingpolicies.yaml
cmd/cli/kubectl-kyverno/data/crds/policies.kyverno.io_mutatingpolicies.yaml

This PR adds mpol and gpol CRDs in the target `codegen-cli-crds`.

chore: add mpol and gpol crds in the CLI

---

charts/kyverno-policies/README.md
charts/kyverno-policies/ci/test-with-annotations.yaml
charts/kyverno-policies/templates/_helpers.tpl
charts/kyverno-policies/templates/baseline/disallow-capabilities.yaml
charts/kyverno-policies/templates/baseline/disallow-host-namespaces.yaml
charts/kyverno-policies/templates/baseline/disallow-host-path.yaml
charts/kyverno-policies/templates/baseline/disallow-host-ports.yaml
charts/kyverno-policies/templates/baseline/disallow-host-process.yaml
charts/kyverno-policies/templates/baseline/disallow-privileged-containers.yaml
charts/kyverno-policies/templates/baseline/disallow-proc-mount.yaml
charts/kyverno-policies/templates/baseline/disallow-selinux.yaml
charts/kyverno-policies/templates/baseline/restrict-apparmor-profiles.yaml
charts/kyverno-policies/templates/baseline/restrict-seccomp.yaml
charts/kyverno-policies/templates/baseline/restrict-sysctls.yaml
charts/kyverno-policies/templates/other/require-non-root-groups.yaml
charts/kyverno-policies/templates/restricted/disallow-capabilities-strict.yaml
charts/kyverno-policies/templates/restricted/disallow-privilege-escalation.yaml
charts/kyverno-policies/templates/restricted/require-run-as-non-root-user.yaml
charts/kyverno-policies/templates/restricted/require-run-as-nonroot.yaml
charts/kyverno-policies/templates/restricted/restrict-seccomp-strict.yaml
charts/kyverno-policies/templates/restricted/restrict-volume-types.yaml
charts/kyverno-policies/values.yaml

Adds support for passing annotations to policies in `charts/kyverno-policies`. This resolves an issue where installing both `kyverno` and `kyverno-policies` as part of the same umbrella helm chart fails due to the default installation order of helm.
Allowing users to pass labels means that helm hooks can be used to apply the policies post installation of `kyverno` (i.e. after the CRDs have been created).
i.e.
```yaml
annotations:
helm.sh/hook: post-install,post-upgrade
```
Closes #13183 
Documentation for this change is not required in the kyverno website.
/kind bug
Scope of bigger picture is detailed above, but in short this enables users to install all the charts in `/charts` as part of a single umbrella helm chart. 
I have not provided proof manifests, as in this case it does not seem …

deploy(kyverno-policies): add support for passing custom annotations to chart

---

.github/workflows/conformance.yaml

Update chainsaw test to kube 1.30 - 1.33

chore: update chainsaw test to kube 1.30 - 1.33

---

cmd/cli/kubectl-kyverno/commands/test/command.go
test/cli/test-mutating-admission-policy/check-labels/expected-patched.yaml
test/cli/test-mutating-admission-policy/check-labels/resource1.yaml

For the CLI test command a new field `testResult.patchResources` was introduced and the `testResult.patchResource` field deprecated.
Unfortunately is the new introduced `testResult.patchResources` never used. So all tests using the new field will pass even the patched resource does not have the expected patches.

Fix: use the introduced testResult.patchResources field if provided

---

api/policies.kyverno.io/v1alpha1/generating_policy.go
api/policies.kyverno.io/v1alpha1/zz_generated.deepcopy.go
charts/kyverno/charts/crds/templates/policies.kyverno.io/policies.kyverno.io_generatingpolicies.yaml
cmd/cli/kubectl-kyverno/data/crds/policies.kyverno.io_generatingpolicies.yaml
config/crds/policies.kyverno.io/policies.kyverno.io_generatingpolicies.yaml
config/install-latest-testing.yaml
docs/user/crd/index.html
docs/user/crd/kyverno_cel_policies.v1alpha1.html
pkg/controllers/policystatus/controller.go

This PR removes the `background` field from the GPOL API.

chore(gpol): remove background from the API

---

pkg/cel/policies/dpol/engine/engine_test.go

Add unit-test for engine.go
#13011 

Add unit test for dpol

---

api/policies.kyverno.io/v1alpha1/mutating_policy_test.go
pkg/cel/policies/mpol/autogen/autogen_test.go
pkg/cel/policies/mpol/compiler/compiler.go
pkg/cel/policies/mpol/compiler/compiler_test.go
pkg/cel/policies/mpol/compiler/policy_test.go
pkg/cel/policies/mpol/engine/engine.go
pkg/cel/policies/mpol/engine/engine_test.go
pkg/cel/policies/mpol/engine/predicate_test.go
pkg/cel/policies/mpol/engine/provider_test.go
pkg/cel/policies/mpol/engine/reconciler_test.go
pkg/cel/policies/mpol/validate_test.go

Add unit test for mpol: 
1. api/mutating_policy.go
2. autogen.go
3. compiler.go 
4. policy.go
5. engine.go
6. predicate.go
7. provider.go
8. reconciler.go
9. validate.go
Resolves a bug : 
During compilation it was not checking if any CEL compilation error thrown for pols. It was checking for just PolicyExceptions.
#13011 

Add unit test for mpol

---

cmd/kyverno-init/main.go

API server client is needed for checking if CRDs (wgpolicy) are installed in kyvernopre before deleting them

init apiserver client in kyverno pre

---

.github/actions/cherry-pick/action.yaml

Cherry-picking bot had issues whenever the PR was already created / a pull was needed. This PR aims at fixing the issue
/milestone 1.16.0
/kind bug
This PR updates the way the bot handles branch when cherry-picking:
- It uses `-B` to either create a new branch or reset it back to `target_branch`
- It cherry picks the commit
- It `force-pushes` the change (needed because remote will be different than the local branch)
- It creates the `PullRequest` only if it wasn't already created

ci(chery-pick): reset cherry-pick branch if already exists

---

.devcontainer/Dockerfile
go.mod
hack/api-group-resources/go.mod
hack/controller-gen/go.mod

This is a copy of: https://github.com/kyverno/kyverno/pull/13822
Created a new PR because 1.14 is using an older golang version and we want to ensure compatibility (`1.23.12` instead of `1.24.6`)
fixes https://github.com/kyverno/kyverno/issues/13831

chore: Update go version to fix CVE-2025-47907

---

test/conformance/chainsaw/mutating-policies/context/api-call/http-post/http-pod.yaml
test/conformance/chainsaw/mutating-policies/context/api-call/http-post/policy.yaml

This PR fixes a spelling error in the API call test files where "recieved" was incorrectly spelled instead of "received". The typo appears in both the test policy and the corresponding mock API response, affecting code readability and consistency.
- **Fixed spelling**: Changed "recieved" to "received" in 3 locations within the http-post test
- **Files modified**:
- `test/conformance/chainsaw/mutating-policies/context/api-call/http-post/policy.yaml` (line 20)
- `test/conformance/chainsaw/mutating-policies/context/api-call/http-post/http-pod.yaml` (line 22)
This PR addresses a code quality issue (spelling error) found in the codebase.
This is a simple typo fix that:
- Maintains existing test functionality
- Improves code readability and professionalism
- Ensures consistency between the …

fix: correct spelling of 'received' in API call test

---

charts/kyverno/Chart.lock
charts/kyverno/Chart.yaml
charts/kyverno/README.md
charts/kyverno/ci/openreports-values.yaml
charts/kyverno/templates/_helpers.tpl
charts/kyverno/templates/reports-controller/deployment.yaml
charts/kyverno/values.yaml

This PR introduces a new configuration option to split the OpenReports CRD installation from the controller enabling flag in the Helm chart. This change allows users to have more granular control over OpenReports feature enablement and CRD installation, making it easier to manage CRDs in environments where they are handled separately from application deployment. The PR also includes validation to prevent invalid configurations, ensuring users don't enable CRD installation without enabling the feature itself.
Closes #13874
/kind feature
- Added new `openreports.installCrds` value to control CRD installation independently
- Added validation in _helpers.tpl to prevent invalid configurations
- Updated Chart.yaml dependencies with proper conditions for OpenReports
- Added test cases to verify …

feature: Split openreports CRD installation from controller flag enabling in the helm chart #13874

---

pkg/engine/utils/exceptions.go

After upgrading Kyverno helm chart on DEV clusters from 3.5.1 to 3.5.2 we noticed that Kyverno policy reporter for the policies with a kinds: ClusterRole started evaluating Cluster Roles as Failed but should have skipped them since as we have a Policy Exception. As it turned out Kyverno "ignores" policy exceptions for policies - https://github.com/kyverno/policies/blob/main/other/restrict-wildcard-verbs/restrict-wildcard-verbs.yaml, https://github.com/kyverno/policies/blob/main/other/restrict-wildcard-resources/restrict-wildcard-resources.yaml, https://github.com/kyverno/policies/blob/main/other/restrict-escalation-verbs-roles/restrict-escalation-verbs-roles.yaml
closes https://github.com/kyverno/kyverno/issues/14079
bug
add conditional statement to check if `resource.GetNamespace != ""` …

add check for namespace

---

pkg/cel/libs/context.go
pkg/cel/libs/fake_context.go
pkg/cel/libs/fake_context_test.go
pkg/cel/libs/resource/impl.go
pkg/cel/libs/resource/impl_test.go
pkg/cel/libs/resource/lib.go
pkg/cel/libs/resource/mock.go
pkg/cel/libs/resource/types.go

Optional argument to filter resources via label selector map
```yaml
apiVersion: policies.kyverno.io/v1alpha1
kind: GeneratingPolicy
metadata:
name: generate-secrets
spec:
resourceRules:
- apiGroups:   [""]
apiVersions: ["v1"]
operations:  ["CREATE", "UPDATE"]
resources:   ["namespaces"]
variables:
- name: nsName
expression: "object.metadata.name"
- name: sources
expression: resource.List("v1", "secrets", "default", { "copy": "true" })
generate:
- expression: generator.Apply(variables.nsName, [variables.sources])
```

support label selector in resource.List CEL lib
