kyverno/kyverno

pkg/validation/policy/validate.go, pkg/validation/policy/validate_test.go
This PR fixes a crash when applying unquoted null.
Fixes #7904
=> fix: crash when applying unquoted null

pkg/engine/handlers/validation/validate_cel.go
This PR does some refactoring for CEL expressions in Kyverno policies.
=> refactor CEL validation in Kyverno policies

api/kyverno/v1/common_types.go, api/kyverno/v1/zz_generated.deepcopy.go, charts/kyverno/templates/crds/crds.yaml, config/crds/kyverno.io_clusterpolicies.yaml, config/crds/kyverno.io_policies.yaml, config/install-latest-testing.yaml, docs/user/crd/index.html, pkg/client/applyconfigurations/kyverno/v1/cel.go, pkg/engine/handlers/validation/validate_cel.go, test/conformance/kuttl/validate/clusterpolicy/standard/cel/cel-variables/01-ns.yaml, test/conformance/kuttl/validate/clusterpolicy/standard/cel/cel-variables/02-policy.yaml, test/conformance/kuttl/validate/clusterpolicy/standard/cel/cel-variables/03-resources.yaml, test/conformance/kuttl/validate/clusterpolicy/standard/cel/cel-variables/README.md, test/conformance/kuttl/validate/clusterpolicy/standard/cel/cel-variables/deployments-fail.yaml, test/conformance/kuttl/validate/clusterpolicy/standard/cel/cel-variables/deployments-pass.yaml, test/conformance/kuttl/validate/clusterpolicy/standard/cel/cel-variables/ns.yaml, test/conformance/kuttl/validate/clusterpolicy/standard/cel/cel-variables/policy-assert.yaml, test/conformance/kuttl/validate/clusterpolicy/standard/cel/cel-variables/policy.yaml
This PR is to add variables for CEL expressions in Kyverno policies
Closes #8050 
/kind feature
A new field for variables are introduced in `validate.cel` as follows:
```
validate:
cel:
variables:
- name: foo
expression: "'foo' in object.spec.metadata.labels ? object.spec.metadata.labels['foo'] : 'default'"
expressions:
- expression: variables.foo == 'bar'
```
1. Create a policy as follows:
```
metadata:
name: image-matches-namespace-environment.policy.example.com
spec:
rules:
- name: image-matches-namespace-environment
match:
any:
- resources:
kinds:
- Deployment
validate:
cel:
variables:
- name: environment
expression: "'environment' in namespaceObject.metadata.labels ? …
```
=> feat: support variables for CEL in Kyverno policies

pkg/tls/keypair.go, pkg/tls/reader.go, pkg/tls/renewer.go, pkg/tls/utils.go
This PR reduces tls package dependencies.
TODO: remove dependency to the config package.
=> fix: reduce tls package dependencies

api/kyverno/v1/rule_types.go, api/kyverno/v1/zz_generated.deepcopy.go, docs/user/crd/index.html, pkg/client/applyconfigurations/kyverno/v1/rule.go, pkg/engine/fuzz_test.go, pkg/engine/handlers/validation/validate_cel.go, pkg/utils/cel/cel.go, pkg/validatingadmissionpolicy/validatingadmissionpolicy.go
This PR is to create `cel` package that is responsible for compiling CEL expressions in both Kyverno policies and Validating admission policies.
=> refactor: create cel package for compiling expressions

cmd/cli/kubectl-kyverno/main.go
This PR fixes cli logs not working.
Fixes #7889
=> fix: cli logs not working

go.mod, go.sum
=> chore: bump kustomize

.nancy-ignore
the rekor version in go mod file is v1.2.2. But nancy-ignore file is  not updated
#7594
=> [update] The nancy-ignore file is not updated

pkg/controllers/ttl/manager.go
This PR adds ttl manager metric for tracked resources.
=> feat: add ttl manager metric for tracked resources

cmd/cli/kubectl-kyverno/docs/docs.go
This PR fixes website docs link generation.
=> fix: website docs generation

cmd/cli/kubectl-kyverno/test/test.go, cmd/cli/kubectl-kyverno/utils/unstructured/unstructured.go, cmd/cli/kubectl-kyverno/utils/unstructured/unstructured_test.go, test/cli/test-mutate/patched-resource/kyverno-test.yaml, test/cli/test-mutate/patched-resource/patched-resource.yaml, test/cli/test-mutate/patched-resource/policy.yaml, test/cli/test-mutate/patched-resource/resource.yaml
This PR fixes mutation unit test not working as expected.
I refactored utils in a dedicated package and added unit tests.
Fixes #4825
=> fix: mutation unit test not working as expected

Makefile, cmd/cli/kubectl-kyverno/test/test.go, cmd/cli/kubectl-kyverno/utils/unstructured/unstructured.go, cmd/cli/kubectl-kyverno/utils/unstructured/unstructured_test.go
This PR fixes a kyverno test generated resource inconsistency.
Fixes #7547
=> fix: kyverno test generated resource inconsistency

Makefile
This PR fixes verification of cli docs.
=> fix: verification of cli docs breaks CI

pkg/engine/factories/contextloaderfactory.go
This PR fixes invalid logger calls.
=> fix: logger calls

cmd/cli/kubectl-kyverno/main.go, cmd/cli/kubectl-kyverno/utils/experimental/experimental.go, cmd/cli/kubectl-kyverno/utils/experimental/experimental_test.go
This PR introduces `experimental` utils package in the CLI.
=> refactor: introduce experimental cli package

cmd/cli/kubectl-kyverno/oci/command.go, cmd/cli/kubectl-kyverno/oci/internal/annotations.go, cmd/cli/kubectl-kyverno/oci/internal/annotations_test.go, cmd/cli/kubectl-kyverno/oci/pull/command.go, cmd/cli/kubectl-kyverno/oci/push/command.go, docs/user/cli/kyverno_oci.md, docs/user/cli/kyverno_oci_pull.md, docs/user/cli/kyverno_oci_push.md
This PR refactors CLI oci commands.
=> refactor: CLI oci commands

cmd/cli/kubectl-kyverno/apply/apply_command.go, cmd/cli/kubectl-kyverno/utils/common/common.go, cmd/cli/kubectl-kyverno/utils/common/common_test.go, cmd/cli/kubectl-kyverno/utils/common/fetch.go, cmd/cli/kubectl-kyverno/utils/common/regex.go, cmd/cli/kubectl-kyverno/utils/source/git.go, cmd/cli/kubectl-kyverno/utils/source/git_test.go, cmd/cli/kubectl-kyverno/utils/source/http.go, cmd/cli/kubectl-kyverno/utils/source/http_test.go, cmd/cli/kubectl-kyverno/utils/source/stdin.go, cmd/cli/kubectl-kyverno/utils/source/stdin_test.go
This PR introduces a `source` package in the cli.
=> refactor: introduce source package in cli

cmd/cli/kubectl-kyverno/README.md
This PR adds a section for our GH action to the cli readme.
=> chore: add gh action to the cli readme

cmd/cli/kubectl-kyverno/utils/source/stdin.go, cmd/cli/kubectl-kyverno/utils/source/stdin_test.go, cmd/cli/kubectl-kyverno/utils/unstructured/unstructured.go, cmd/cli/kubectl-kyverno/utils/unstructured/unstructured_test.go
This PR improves test coverage of source and unstructured cli utils package.
=> chore: improve test coverage of cli utils package

.github/ISSUE_TEMPLATE/bug-cli.yaml, .github/ISSUE_TEMPLATE/bug-other.yaml, .github/ISSUE_TEMPLATE/bug-webhook.yaml
Adds 1.10.3 to the dropdown menu of github issue template
=> feat: add 1.10.3 to github issue template

charts/kyverno/README.md, charts/kyverno/templates/NOTES.txt, charts/kyverno/templates/_helpers.tpl, charts/kyverno/templates/reports-controller/deployment.yaml, charts/kyverno/values.yaml, cmd/reports-controller/main.go, config/install-latest-testing.yaml, pkg/controllers/report/aggregate/controller.go, pkg/controllers/report/background/controller.go, pkg/controllers/report/resource/controller.go, pkg/controllers/report/utils/scanner.go, pkg/controllers/report/utils/utils.go, pkg/engine/api/policy.go, pkg/event/events.go, pkg/utils/report/labels.go, pkg/utils/report/results.go, pkg/utils/report/selector.go
This PR is to generate background scan reports for validating admission policies.
Closes #7642
/kind feature
1. Create a deployment:
```
metadata:
name: deployment-test
spec:
replicas: 2
selector:
matchLabels:
app: app
template:
metadata:
labels:
app: app
spec:
containers:
- name: container2
image: nginx
```
2. Create a validating admission policy:
```
apiVersion: [admissionregistration.k8s.io/v1alpha1](http://admissionregistration.k8s.io/v1alpha1)
metadata:
name: check-deployment-replicas
spec:
resourceRules:
- apiGroups:   ["apps"]
apiVersions: ["v1"]
operations:  ["CREATE", "UPDATE"]
resources:   ["deployments"]
validations:
- expression: "object.spec.replicas <= 3"
message: …
```
=> feat: generate backgroundscan reports for validating admission policies

cmd/cli/kubectl-kyverno/main.go
This PR makes the cli  exit cleanly.
=> fix: cli exit cleanly

cmd/cli/kubectl-kyverno/_testdata/policies/cpol-pod-requirements.yaml, cmd/cli/kubectl-kyverno/_testdata/policies/pol-pod-requirements.yaml, cmd/cli/kubectl-kyverno/report/report.go, cmd/cli/kubectl-kyverno/report/report_test.go, cmd/cli/kubectl-kyverno/userinfo/userinfo.go, cmd/cli/kubectl-kyverno/userinfo/userinfo_test.go, cmd/cli/kubectl-kyverno/values/load_test.go, cmd/cli/kubectl-kyverno/variables/new_test.go, cmd/cli/kubectl-kyverno/variables/parse_test.go
This PR improves unit tests in cli.
=> chore: improve unit tests in cli

.github/workflows/conformance.yaml, scripts/config/validating-admission-policy-reports/kyverno.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-fail/01-deployment.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-fail/02-policy.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-fail/03-bgscanr.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-fail/04-sleep.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-fail/README.md, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-fail/bgscanr-assert.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-fail/deployment-assert.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-fail/deployment.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-fail/policy.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-pass/01-deployment.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-pass/02-policy.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-pass/03-bgscanr.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-pass/04-sleep.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-pass/README.md, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-pass/bgscanr-assert.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-pass/deployment-assert.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-pass/deployment.yaml, test/conformance/kuttl/validating-admission-policy-reports/background/validating-admission-policy-pass/policy.yaml
This PR is to add kuttl tests for generating background scan reports for VAPs.
=> feat: add kuttl tests for validating admission policy reports

test/conformance/kuttl/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-all-match-resource/validatingadmissionpolicybinding.yaml, test/conformance/kuttl/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-any-match-multiple-resources/validatingadmissionpolicybinding.yaml, test/conformance/kuttl/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-any-match-resource/validatingadmissionpolicybinding.yaml
This PR adds `validationActions` in validating admission policy binding.
=> chore: add validationAction in kuttl tests

cmd/cli/kubectl-kyverno/processor/policy_processor.go, cmd/cli/kubectl-kyverno/processor/utils.go
This PR simplifies cli autogen and labels selector check.
=> fix: simplify cli autogen and labels selector check

cmd/cli/kubectl-kyverno/test/load_test.go, cmd/cli/kubectl-kyverno/test/test_case.go, cmd/cli/kubectl-kyverno/test/test_case_test.go
=> chore: add cli unit tests

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/commands/apply/command_test.go, cmd/cli/kubectl-kyverno/commands/test/test.go, cmd/cli/kubectl-kyverno/processor/policy_processor.go, cmd/cli/kubectl-kyverno/processor/policy_processor_test.go, cmd/cli/kubectl-kyverno/processor/utils.go, cmd/cli/kubectl-kyverno/resource/compare.go, cmd/cli/kubectl-kyverno/utils/common/common_test.go, test/cli/test-mutate/foreach/pod-updated-image.yaml, test/cli/test-mutate/patched-resource.yaml, test/cli/test-mutate/patchedResource8.yaml
This PR fixes cli engine invocation order.
=> fix: cli engine invocation order

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/commands/apply/command_test.go, cmd/cli/kubectl-kyverno/commands/test/command.go, cmd/cli/kubectl-kyverno/output/table/table_test.go, cmd/cli/kubectl-kyverno/policy/load.go, cmd/cli/kubectl-kyverno/report/report.go, cmd/cli/kubectl-kyverno/report/report_test.go, cmd/cli/kubectl-kyverno/variables/parse.go, pkg/engine/api/policy.go
This PR fixes some TODOs in the cli code.
=> fix: TODOs in cli

cmd/cli/kubectl-kyverno/commands/version/command.go, cmd/cli/kubectl-kyverno/commands/version/command_test.go
This PR improves cli version command and adds tests.
=> chore: improve cli version command and add tests

cmd/cli/kubectl-kyverno/log/log.go, cmd/cli/kubectl-kyverno/main.go
This PR disables cli logs when level is 0.
=> fix: disable cli logs when level is 0

Makefile
This PR switches back to official policies repo.
=> chore: switch back to official policies repo

.github/workflows/conformance.yaml, Makefile, test/cli/test/validating-admission-policies/disallow-host-path/kyverno-test.yaml
This PR validates test files are up to date.
=> chore: validate test files are up to date

cmd/cli/kubectl-kyverno/commands/fix/test/command.go, docs/user/cli/kyverno_fix_test.md, test/cli/registry/kyverno-test.yaml, test/cli/test-mutate/global-anchor/kyverno-test.yaml, test/cli/test/admission_user_info/kyverno-test.yaml, test/cli/test/anypattern_skip_error/kyverno-test.yaml, test/cli/test/container_reorder/kyverno-test.yaml, test/cli/test/deny-modify-platform-label/kyverno-test.yaml, test/cli/test/foreach/kyverno-test.yaml, test/cli/test/jmespath-brackets/kyverno-test.yaml, test/cli/test/simple/kyverno-test.yaml, test/cli/test/validating-admission-policies/disallow-host-path/kyverno-test.yaml, test/cli/test/variables/kyverno-test.yaml
This PR compresses test results in cli `fix test` command.
=> feat: compress test results in cli fix test command

test/cli/test-mutate/connection-draining/kyverno-test.yaml, test/cli/test-mutate/connection-draining/patched.yaml, test/cli/test-mutate/connection-draining/policy.yaml, test/cli/test-mutate/connection-draining/resource.yaml
This PR fixes: Kyverno test fails to load resources.
Fixes #7681
=> fix: Kyverno test fails to load resources

pkg/controllers/report/utils/utils.go
This PR fixes generating backgoundscan reports for the generated VAPs only. The current behavior is that reports are generated for both Kyverno policies and their generated VAPs in case both `background` and `--validatingAdmissionPolicyReports` are set.
If the user writes a Kyverno policy to generate VAPs, then he would expect that the generated backgroundscan reports will be for VAPs.
Closes #8353 
/kind bug
=> fix: ignore generating backgroundscan reports for Kyverno policies in case VAPs are generated

cmd/cli/kubectl-kyverno/processor/policy_processor.go, cmd/cli/kubectl-kyverno/processor/utils.go
This PR simplifies cli processor rule handling.
=> refactor: simplify cli processor

cmd/cli/kubectl-kyverno/apis/test/test.go, cmd/cli/kubectl-kyverno/apis/test/test_result.go, cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/commands/apply/command_test.go, cmd/cli/kubectl-kyverno/commands/fix/test/command.go, cmd/cli/kubectl-kyverno/commands/test/command.go, cmd/cli/kubectl-kyverno/commands/test/output.go, cmd/cli/kubectl-kyverno/report/report.go, cmd/cli/kubectl-kyverno/report/report_test.go, cmd/cli/kubectl-kyverno/test/filter/filter.go, cmd/cli/kubectl-kyverno/test/filter/filter_test.go, cmd/cli/kubectl-kyverno/test/load_test.go, test/cli/test-generate/create-default-pdb/kyverno-test.yaml, test/cli/test-mutate/connection-draining/kyverno-test.yaml, test/cli/test-mutate/kyverno-test.yaml, test/cli/test/any-all-wildcard/kyverno-test.yaml, test/cli/test/any-namespaceSelector/kyverno-test.yaml, test/cli/test/exec-subresource/kyverno-test.yaml, test/cli/test/images/digest/kyverno-test.yaml, test/cli/test/jmespath-brackets/kyverno-test.yaml, test/cli/test/jmespath-brackets/policy.yaml, test/cli/test/limit-configmap-for-sa/kyverno-test.yaml, test/cli/test/mixed/kyverno-test.yaml, test/cli/test/scale-subresource/kyverno-test.yaml, test/cli/test/simple/kyverno-test.yaml
This PR fixes: namespace in kyverno-test.yaml seems to have no effect in case of exclude
Fixes #7064
=> fix: namespace in kyverno-test.yaml seems to have no effect in case of exclude

test/cli/test-mutate/bug-demo/kyverno-test.yaml, test/cli/test-mutate/bug-demo/patched-resource-pattern.yaml, test/cli/test-mutate/bug-demo/policy.yaml, test/cli/test-mutate/bug-demo/resource.yaml
This PR fixes: kyverno test wrongly finds 'patchedResource mismatch' due to wrong order in array.
Fixes #6261
=> fix: kyverno test wrongly finds 'patchedResource mismatch' due to wrong order in array

test/cli/test/disallow-service/policy.yaml
This PR fixes a cli test policy.
=> fix: cli test policy

test/cli/test-mutate/add-default-resources/kyverno-test.yaml
=> chore: lint test files

cmd/cli/kubectl-kyverno/output/color/color.go
This PR fixes names not formatted correctly in cli output.
=> fix: names not formatted correctly in cli output

cmd/reports-controller/main.go, pkg/controllers/report/aggregate/namespace/controller.go, pkg/controllers/report/aggregate/namespace/log.go
This PR moves per namespace reports aggregator in a sub package.
=> refactor: move per namespace reports aggregator in a sub package

cmd/cli/kubectl-kyverno/fix/test.go
This PR detects duplicate resources in cli fix test command.
=> feat: detect duplicate resources in cli fix test

test/cli/test-mutate/connection-draining/kyverno-test.yaml, test/cli/test-mutate/foreach/kyverno-test.yaml, test/cli/test-mutate/global-anchor/kyverno-test.yaml, test/cli/test-mutate/kyverno-test.yaml, test/cli/test/anypattern_skip_error/kyverno-test.yaml, test/cli/test/autogen/kyverno-test.yaml, test/cli/test/custom-functions/kyverno-test.yaml, test/cli/test/foreach/kyverno-test.yaml, test/cli/test/images/verify-signature/kyverno-test.yaml, test/cli/test/jmespath-brackets/kyverno-test.yaml, test/cli/test/limit-configmap-for-sa/kyverno-test.yaml, test/cli/test/mutate-keda-scaled-object/kyverno-test.yaml, test/cli/test/resource_lists/kyverno-test.yaml, test/cli/test/restrict-something/kyverno-test.yaml, test/cli/test/restrict_ingress_host/kyverno-test.yaml, test/cli/test/simple/kyverno-test.yaml, test/cli/test/variables/kyverno-test.yaml, test/cli/test/wildcard_mutate/kyverno-test.yaml
This PR fixes cli test files with the new implementation which is predictible and reproducible.
=> chore: fix cli test files

test/cli/registry/image-example.yaml, test/cli/test-fail/invalid-ns/policy.yaml, test/cli/test-fail/missing-policy/policy.yaml, test/cli/test-fail/missing-resource/policy.yaml, test/cli/test-fail/missing-rule/policy.yaml, test/cli/test-generate/add-network-policy/policy.yaml, test/cli/test-generate/add-quota/policy.yaml, test/cli/test-generate/sync-secrets/policy.yaml
=> chore: apply policy fixes

api/kyverno/v1beta1/updaterequest_types.go
This PR adds missing omitempty tags.
=> fix: add missing omitempty tag

pkg/utils/controller/run.go
Suppress these controller reconciliation logs:
```
I0918 03:23:23.291917       1 run.go:156] webhook-controller/worker "msg"="reconciling ..." "id"=1 "key"="kyverno-resource-validating-webhook-cfg" "name"="kyverno-resource-validating-webhook-cfg" "namespace"=""
I0918 03:23:23.292057       1 run.go:156] webhook-controller/worker "msg"="reconciling ..." "id"=0 "key"="kyverno-resource-mutating-webhook-cfg" "name"="kyverno-resource-mutating-webhook-cfg" "namespace"=""
I0918 03:23:23.298838       1 run.go:158] webhook-controller/worker "msg"="done" "duration"="6.95075ms" "id"=1 "key"="kyverno-resource-validating-webhook-cfg" "name"="kyverno-resource-validating-webhook-cfg" "namespace"=""
I0918 03:23:23.299093       1 run.go:158] webhook-controller/worker "msg"="done" "duration"="7.247541ms" …
```
=> fix excessive logs

cmd/cli/kubectl-kyverno/commands/fix/test/options.go, cmd/cli/kubectl-kyverno/fix/values.go, test/cli/test-mutate/foreach/values.yaml, test/cli/test-mutate/patched-resource/kyverno-test.yaml, test/cli/test/any-namespaceSelector/value.yaml, test/cli/test/autogen-values/values.yaml, test/cli/test/context-foreach/values.yaml, test/cli/test/deny-modify-platform-label-2/variables.yaml, test/cli/test/deny-modify-platform-label-3/variables.yaml, test/cli/test/deny-modify-platform-label/variables.yaml, test/cli/test/limit-configmap-for-sa/variables.yaml, test/cli/test/nil-values-in-variables/exclude_namespaces_dynamically/values.yaml, test/cli/test/policy-reports-skip-validation/values.yaml, test/cli/test/restrict_ingress_host/values.yaml, test/cli/test/scale-subresource/values.yaml, test/cli/test/simple/values.yaml, test/cli/test/unordered-context-variables/variables.yaml, test/cli/test/variables/variables.yaml
This PR fixes variables used in tests (convert to the cli schema).
=> feat: fix variables used in tests

Makefile, cmd/cli/kubectl-kyverno/data/crds/cli.kyverno.io_tests.yaml, cmd/cli/kubectl-kyverno/data/crds/cli.kyverno.io_userinfoes.yaml, cmd/cli/kubectl-kyverno/data/crds/cli.kyverno.io_values.yaml
This PR embeds cli schemas in cli.
=> chore: embed cli schemas in cli

pkg/notary/notary.go, pkg/notary/repository.go
improve descriptions in notary verifier
=> style: improve descriptions in notary verifier

.github/workflows/lint.yaml, cmd/cli/kubectl-kyverno/experimental/experimental.go
=> fix: linter

cmd/reports-controller/main.go, pkg/controllers/report/aggregate/resource/controller.go
This PR uses vap map in report aggregation.
=> fix: use vap map in report aggregation

.github/workflows/conformance.yaml
This PR fixes custom-sigstore conformance job.
=> fix: custom-sigstore conformance job

.github/workflows/conformance.yaml
This PR adds a required job to simplify branch protection.
=> chore: add a required job to simplify branch protection

charts/kyverno-policies/Chart.yaml, charts/kyverno-policies/README.md, charts/kyverno/Chart.yaml, charts/kyverno/README.md
=> release: v1.11.0-beta.1

.github/actions/setup-build-env/action.yaml, .github/actions/setup-test-env/action.yaml
This PR frees disk space before running jobs.
=> chore: free disk space before running jobs

.github/actions/setup-build-env/action.yaml, .github/actions/setup-test-env/action.yaml, .github/workflows/release.yaml
This PR tries to fix our release workflow.
=> fix: release workflow

.github/workflows/images-publish.yaml
This PR tries to fix publish images workflow.
=> fix: publish images workflow

.github/workflows/release.yaml, .goreleaser.yml
This PR fixes release archive name template.
=> fix: release archive name template

.github/actions/setup-build-env/action.yaml, .github/actions/setup-test-env/action.yaml
This PR makes free disk space action configurable.
=> fix: make free disk space action configurable

charts/kyverno-policies/Chart.yaml, charts/kyverno-policies/README.md, charts/kyverno/Chart.yaml, charts/kyverno/README.md
This PR fixes chart versions for 1.11.0-beta.1
=> release: fix chart versions for 1.11.0-beta.1

pkg/utils/match/subjects.go
This PR fixes `CheckSubjects` func.
Fixes #6265
=> refactor: check subjects func

cmd/cli/kubectl-kyverno/_testdata/resources/namespace.yaml, cmd/cli/kubectl-kyverno/resource/convert/convert.go, cmd/cli/kubectl-kyverno/resource/convert/convert_test.go
This PR adds a package to convert unstructured into typed.
=> feat: add a package to convert unstructured into typed

cmd/cli/kubectl-kyverno/_testdata/resources/namespace.yaml, cmd/cli/kubectl-kyverno/resource/loader/loader.go, cmd/cli/kubectl-kyverno/resource/loader/loader_test.go
This PR adds a cli resource loader package.
=> feat: add cli resource loader package

pkg/engine/image_verify_test.go
=> feat: improve assertion and error messages in ivcache tests

cmd/cli/kubectl-kyverno/resource/load.go, cmd/cli/kubectl-kyverno/resource/load_test.go
This PR adds resource load funcs in cli.
=> feat: add resource load funcs in cli

Makefile, cmd/cli/kubectl-kyverno/_testdata/exceptions/exception-and-policy.yaml, cmd/cli/kubectl-kyverno/_testdata/exceptions/exception.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policyexceptions.yaml, cmd/cli/kubectl-kyverno/exception/load.go, cmd/cli/kubectl-kyverno/exception/load_test.go, cmd/cli/kubectl-kyverno/resource/loader/loader_test.go
This PR adds a cli package to load policy exceptions.
=> feat: add cli package to load policy exceptions

cmd/cleanup-controller/handlers/cleanup/handlers.go, cmd/cli/kubectl-kyverno/store/contextloader.go, pkg/engine/api/contextloader.go, pkg/engine/engine.go, pkg/engine/factories/contextloaderfactory.go, pkg/engine/internal/imageverifier.go
This PR fixes a panic when image cache is nil and cleans up code where it is not used.
=> fix: image cache panic and cleanup

charts/kyverno-policies/Chart.yaml, charts/kyverno-policies/README.md, charts/kyverno/Chart.yaml, charts/kyverno/README.md
=> release: 1.11.0-beta.2

charts/kyverno-policies/Chart.yaml, charts/kyverno-policies/README.md, charts/kyverno/Chart.yaml, charts/kyverno/README.md
=> release: v1.11.0-beta.3

charts/kyverno/templates/_helpers/_deployment.tpl, charts/kyverno/values.yaml
This PR makes the Helm chart skip validation of deployment replicas > 0 if replicas is set to a non-int value. This should fix the issue trying to use [post build variable substitution](https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution) in replicas values - as described in https://github.com/kyverno/kyverno/issues/8537.
Closes https://github.com/kyverno/kyverno/issues/8537
@chipzoller 
/kind bug
The proposed changes should not affect users using "normal" replicas values (integers), and the Kubernetes API will reject any non-int replicas value.
=> fix(helm): skip deployment replicas validation in non-int value

charts/kyverno/README.md, charts/kyverno/templates/_helpers.tpl, charts/kyverno/values.yaml, scripts/config/custom-sigstore/kyverno.yaml
This PR makes tuf feature in chart consistent with others.
=> fix: make tuf feature in chart consistent with others

pkg/engine/engine.go
This PR applies policy exceptions after applying cluster/namespaced policies to resources in case rule response has a status of `fail` .
=> fix: apply exceptions after executing the policy itself

cmd/cli/kubectl-kyverno/resource/loader/loader.go, go.mod, go.sum
This PR bumps kubectl-validate
=> chore: bump kubectl-validate

charts/kyverno-policies/Chart.yaml, charts/kyverno-policies/README.md, charts/kyverno/Chart.yaml, charts/kyverno/README.md
=> release: v1.11.0-beta.4

.github/actions/setup-build-env/action.yaml
Cherry-pick https://github.com/kyverno/kyverno/pull/8637.
=> deps: bump to Go 1.21.3 (cherry-pick #8637)

charts/kyverno/templates/background-controller/clusterrole.yaml, config/install-latest-testing.yaml
We upgraded to 1.11.0-rc.1 today and discovered a few issues. This PR is fixing one of them: **background-controller seems to require cluster-wide RBAC to policyexceptions**.  This has probably not been discovered because background-controller has read access to all resources by default. This is something we are trying to avoid, and this is now possible after https://github.com/kyverno/kyverno/pull/8083.
/kind bug
=> fix(helm): add missing policyexceptions RBAC to background-controller

cmd/cleanup-controller/handlers/admission/resource/handlers.go
=> fix typo (cherry-pick #8666)

cmd/kyverno/main.go, pkg/controllers/validatingadmissionpolicy-generate/controller.go, pkg/event/events.go
=> feat: generate events for CEL policies that generate VAPs (cherry-pick #8564)

.github/workflows/conformance.yaml
=> fix: use correct k8s version in custom sigstore tuf kuttl test (cherry-pick 8707)

.github/workflows/helm-test.yaml
fix: dynamically get branch name in helm test
=> fix: dynamically get branch name in helm test (cherry-pick: #8732)

.github/workflows/helm-test.yaml
=> fix: replace base_ref with ref_name in helm test GHA (Cherry Pick #8735)

.github/workflows/helm-release.yaml
=> fix: fetch correct branch name in helm-release workflow (Cherry-pick #8744)

charts/kyverno/templates/background-controller/role.yaml, config/install-latest-testing.yaml
=> Revert "feat: add secrets name in background-controller's role"

charts/kyverno/charts/grafana/dashboard/dashboard.json
Fixes a few queiries to better support `kyverno` running in multiple replica mode. Also includes some quality of life updates to graphs' colors, axes, and legends to be more meaningful to newer users while keeping the dashboard concise for experts.
Partially fixes #8750 
/kind bug
The fixes to the queries will support multiple replica deployments. Without them, the dashboard is just showing incorrect data.
I think because we are just changing an pure artifact this will essentially be the same as the GH diff. But if you want me to include, just LMK and I can add it. Instead tho, I have included before/after photos below:
**Before**
**After**
=> fix: grafana dashboard to support replicas

ext/file-info/ext.go, ext/file/ext.go, ext/file/ext_test.go
=> feat: add utils packages in ext

cmd/cli/kubectl-kyverno/output/color/color.go, ext/output/color/color.go, ext/output/color/color_test.go
Add force color in color ext pkg.
=> feat: add force color in color ext pkg

go.mod, go.sum
Closes: #8790
Fixes vulnerability issue in docker v24.0.7: https://github.com/advisories/GHSA-jq35-85cj-fj4p
=> chore: upgrade docker/docker to v24.0.7

charts/kyverno-policies/Chart.yaml, charts/kyverno-policies/README.md, charts/kyverno/Chart.yaml, charts/kyverno/README.md
Release 1.10.4 with CVE fixes https://github.com/kyverno/kyverno/pull/8798.
=> Release 1.10.4

.github/workflows/helm-release.yaml, .github/workflows/helm-test.yaml
=> chore(deps): bump helm/chart-testing-action from 2.4.0 to 2.6.0 (cherry-pick #8809)

.github/workflows/helm-release.yaml, .github/workflows/helm-test.yaml
Cherry-pick https://github.com/kyverno/kyverno/pull/8809
=> chore(deps): bump helm/chart-testing-action from 2.4.0 to 2.6.0 (#8809)

.github/workflows/helm-release.yaml, .github/workflows/images-publish.yaml, .github/workflows/release.yaml
upgrade cosign installer version in release 1.10 and use cosign 1.13.1
=> fix: upgrade cosign installer version in release 1.10 and use cosign 1.13.1

charts/kyverno-policies/Chart.yaml, charts/kyverno-policies/README.md, charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/charts/crds/Chart.yaml, charts/kyverno/charts/crds/README.md, config/install-latest-testing.yaml
=> Release 1.11.0-rc.8

go.mod, go.sum
Uses our fork of cosign that has fixes for https://github.com/advisories/GHSA-vfp6-jrw2-99g9 in cosign v1.13.1
Changes: https://github.com/kyverno/cosign/commit/5912cb31e816d0e60c07db1fa8bd3da26ef4faf1
=> feat:  add GHSA-vfp6-jrw2-99g9 fixes in cosign v1.13.1

pkg/engine/apicall/apiCall.go
Moves the closing of the response up. Currently the response will not be closed if Kyverno fails this conditional:
https://github.com/kyverno/kyverno/blob/9c3be3fd49839a1a9903e4b18439391674534749/pkg/engine/apicall/apiCall.go#L131-L138
This PR fixes that.
NONE
/kind bug
=> Close reponse right after succesful request

ADOPTERS.md
Removes duplicate Spotify adopter.
=> chore: remove duplicate adopter

charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/templates/admission-controller/deployment.yaml, charts/kyverno/templates/background-controller/deployment.yaml, charts/kyverno/templates/cleanup-controller/deployment.yaml, charts/kyverno/templates/reports-controller/deployment.yaml, charts/kyverno/values.yaml, config/install-latest-testing.yaml
This PR adds Helm chart parameters to tune the `revisionHistoryLimit` value in the four Deployments. The values default to 10 which is the implicit Kubernetes default.
/kind feature
=> fix: Add chart parameters for setting revisionHistoryLimit

.nancy-ignore
=> fix: nancy ignore list

.github/workflows/conformance.yaml, test/conformance/chainsaw/rbac/aggregate-to-admin/00-cluster-role.yaml, test/conformance/chainsaw/rbac/aggregate-to-admin/README.md, test/conformance/chainsaw/rbac/aggregate-to-admin/admin-policies.yaml, test/conformance/chainsaw/rbac/aggregate-to-admin/admin-policyreport.yaml, test/conformance/chainsaw/rbac/aggregate-to-admin/admin-reports.yaml, test/conformance/chainsaw/rbac/aggregate-to-admin/admin-updaterequest.yaml
Run rbac testsuite using chainsaw
=> chore: run rbac testsuite using chainsaw

.github/workflows/conformance.yaml, test/conformance/chainsaw/rangeoperators/standard/01-policy.yaml, test/conformance/chainsaw/rangeoperators/standard/02-resource.yaml, test/conformance/chainsaw/rangeoperators/standard/README.md, test/conformance/chainsaw/rangeoperators/standard/policy-assert.yaml, test/conformance/chainsaw/rangeoperators/standard/policy.yaml, test/conformance/chainsaw/rangeoperators/standard/resource.yaml
Run range operators tests with chainsaw.
=> chore: run range operators tests with chainsaw

.github/workflows/conformance.yaml
=> chore: bump chainsaw

.github/workflows/conformance.yaml, test/conformance/chainsaw/force-failure-policy-ignore/cluster-policy/fail/01-policy.yaml, test/conformance/chainsaw/force-failure-policy-ignore/cluster-policy/fail/02-webhooks.yaml, test/conformance/chainsaw/force-failure-policy-ignore/cluster-policy/fail/README.md, test/conformance/chainsaw/force-failure-policy-ignore/cluster-policy/fail/policy-assert.yaml, test/conformance/chainsaw/force-failure-policy-ignore/cluster-policy/fail/policy.yaml, test/conformance/chainsaw/force-failure-policy-ignore/cluster-policy/fail/webhooks-assert.yaml
Run force-failure-policy-ignore test using chainsaw.
=> chore: run force-failure-policy-ignore test using chainsaw

cmd/background-controller/main.go, cmd/internal/engine.go, cmd/kyverno/main.go, cmd/reports-controller/main.go, pkg/engine/apicall/apiCall.go, pkg/engine/apicall/apiCall_test.go, pkg/engine/context/loaders/apicall.go, pkg/engine/factories/contextloaderfactory.go
API Calls fetch data from external URL and saves it to the memory. If a user requests for a very large data from an API Call, this can cause the controller's memory to exhaust resulting in crash.
This PR adds checks for content-length of API Call response 
/kind bug
=> feat: add checks for max response size in API Call

charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/templates/admission-controller/_helpers.tpl, charts/kyverno/templates/admission-controller/deployment.yaml, charts/kyverno/templates/background-controller/_helpers.tpl, charts/kyverno/templates/background-controller/deployment.yaml, charts/kyverno/templates/reports-controller/_helpers.tpl, charts/kyverno/templates/reports-controller/deployment.yaml, charts/kyverno/values.yaml
Document how to set proxy environment variables
Fixes #6749
Fixes #5205
=> Allow defining ca-certificates bundle for Kyverno deployments

cmd/cli/kubectl-kyverno/commands/create/exception/command_test.go, cmd/cli/kubectl-kyverno/commands/create/templates/exception.yaml
In `kyverno create exception`, there is an additional dash appears between lines `any`/`all` and `kinds`. This PR removes it.
Closes #8945 
/kind bug
Run the following command:
```
cmd/cli/kubectl-kyverno/kubectl-kyverno create exception my-exception --namespace my-ns --policy-rules "policy,rule-1,rule-2" --all "kind=Pod,kind=Deployment,name=test-*"
```
Here is the created exception:
```
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
name: my-exception
namespace: my-ns
spec:
match:
all:
- kinds:
- Pod
- Deployment
names:
- test-*
exceptions:
- policyName: policy
ruleNames:
- rule-1
- rule-2
```
=> fix: remove the additional dash in kyverno create exception

cmd/background-controller/main.go, cmd/internal/engine.go, cmd/kyverno/main.go, cmd/reports-controller/main.go, pkg/engine/apicall/apiCall.go, pkg/engine/apicall/apiCall_test.go, pkg/engine/context/loaders/apicall.go, pkg/engine/factories/contextloaderfactory.go
API Calls fetch data from external URL and saves it to the memory. If a user requests for a very large data from an API Call, this can cause the controller's memory to exhaust resulting in crash.
This PR adds checks for content-length of API Call response 
/milestone 1.10.6
/kind bug
=> feat: add checks for max response size in API Call (release 1.10.6)

test/conformance/chainsaw/_config/common.yaml
Extend chainsaw cleanup timeout.
=> fix: extend chainsaw cleanup timeout

.github/workflows/conformance.yaml
Replace standard kuttl tests by chainsaw ones.
=> chore: replace standard kuttl tests by chainsaw ones

.github/workflows/conformance.yaml
Replace more kuttl tests by chainsaw ones.
=> chore: replace more kuttl tests by chainsaw

cmd/cli/kubectl-kyverno/commands/create/exception/command_test.go, cmd/cli/kubectl-kyverno/commands/create/templates/exception.yaml
Cherry-picked fix: remove the additional dash in kyverno create exception (#8983)
=> fix: remove the additional dash in kyverno create exception (cherry-pick #8983)

charts/kyverno/README.md, charts/kyverno/templates/hooks/post-upgrade.yaml, charts/kyverno/values.yaml
This PR adds a `post-upgrade` helm hook to remove the older policy reports; `PolicyReports` and `ClusterPolicyReports` contain `pol` in their name.
Closes #8918 
/kind bug
Adding a `post-upgrade` hook to be executed after all resources have been upgraded.
1. Install Kyverno 1.10
2. Create some policies and resources to get policy reports.
3. Get all policy reports:
```
$ kubectl get policyreports.wgpolicyk8s.io -A
NAMESPACE            NAME                            PASS   FAIL   WARN   ERROR   SKIP   AGE
default              cpol-disallow-host-namespaces   3      3      0      0       0      2m9s
default              pol-validate-1                  0      2      0      0       0      2m9s
kube-system          cpol-disallow-host-namespaces   4      14     0      0 …
```
=> fix: cleanup older policy reports

DEVELOPMENT.md, Makefile
Use Kubernetes 1.28 by default
=> chore: use Kubernetes 1.28 by default

charts/kyverno/Chart.yaml
This PR updates the Chart.yaml `artifacthub.io/changes` with the changes of adding a `nodeSelector` for policyReportsCleanup.
=> chore: update chart.yaml with the changes

cmd/cleanup-controller/main.go, cmd/kyverno/main.go, pkg/tls/renewer.go
This PR sets the cert renewal time to 15 days before expiration.
A new flag `--certBefore` is added for both admission and cleanup controllers.
Closes #8441
=> chore: set cert renewal time to 15 days before expiration

MAINTAINERS.md
Adding myself to maintainers list
Checklist:
-  https://github.com/kyverno/kyverno/commit/f7e57aa117cb8b1457e1a68fc79d08982b4831da
- [My PR list](https://github.com/kyverno/kyverno/pulls?q=is%3Apr+author%3Avishal-chdhry+sort%3Aupdated-desc)
--
=> feat: add myself (vishal-chdhry) to maintainers list

.github/workflows/conformance.yaml
=> chore: use test regex in chainsaw

MAINTAINERS.md
This PR adds myself to the maintainers list. 
Checklist:
-  https://github.com/kyverno/kyverno/commit/d9359b7896309a883004c484562d4399ef8c242d
- [My PR list](https://github.com/kyverno/kyverno/pulls?q=is%3Apr+is%3Aclosed+author%3AMariamFahmy98)
=> chore: add myself to the maintainers list

.github/workflows/conformance.yaml
Use new chainsaw github action (moved to a dedicated repository).
=> chore: use new chainsaw github action

.github/workflows/conformance.yaml
=> chore: add 1.29 to the test grid

charts/kyverno/README.md, charts/kyverno/templates/hooks/post-upgrade.yaml, charts/kyverno/values.yaml
This PR adds tolerations and affinity to the post-upgrade hook.
Closes #9150 
/milestone 1.11.2
/kind feature
=> fix: add tolerations and affinity to the post-upgrade hook

pkg/logging/log.go
This PR fixes the logger level setting.
=> fix: set logger level

charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/templates/hooks/post-upgrade.yaml, charts/kyverno/values.yaml
=> fix: add tolerations and affinity to the post-upgrate hook (#9156)

.github/workflows/conformance.yaml
=> chore: fix conformance tests

api/kyverno/v1/clusterpolicy_types.go, api/kyverno/v1/policy_interface.go, api/kyverno/v1/policy_types.go, api/kyverno/v1/spec_types.go, api/kyverno/v2beta1/spec_types.go, charts/kyverno/charts/crds/templates/crds.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, config/crds/kyverno.io_clusterpolicies.yaml, config/crds/kyverno.io_policies.yaml, config/install-latest-testing.yaml, docs/user/crd/index.html
This PR deprecates the `spec.schemaValidation`.
Closes #8919 
/kind bug
=> fix: deprecate spec.schemaValidation

pkg/engine/context/context_test.go
Add missing context unit test.
Follow up for https://github.com/kyverno/kyverno/pull/9124
=> chore: add missing context unit test

api/kyverno/v2alpha1/policy_exception_types.go, charts/kyverno/charts/crds/templates/crds.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policyexceptions.yaml, cmd/cli/kubectl-kyverno/exception/load.go, config/crds/kyverno.io_policyexceptions.yaml, config/install-latest-testing.yaml
This PR removes the `v2alpha1` version of policy exceptions
None
=> chore: remove v2alpha1 version of policy exceptions

.vscode/launch.json, test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/multiple-trigger-resources/README.md, test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/multiple-trigger-resources/chainsaw-test.yaml, test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/multiple-trigger-resources/configmap.yaml, test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/multiple-trigger-resources/namespace.yaml, test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/multiple-trigger-resources/patched-pod.yaml, test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/multiple-trigger-resources/pod.yaml, test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/multiple-trigger-resources/policy-ready.yaml, test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/multiple-trigger-resources/policy.yaml
This PR adds a chainsaw test for a mutate existing policy to make sure that URs aren't stuck at pending/fail status. The test creates a mutateExisting policy where `mutateExistingOnPolicyUpdate` is set to true and two trigger resources are created. Thus, two URs are generated, one of which has a `failure` status. It is expected that all URs got deleted.
Related to #9170 
/milestone 1.11.2
/kind feature
=> fix: add chainsaw test for mutate existing

charts/kyverno-policies/Chart.yaml, charts/kyverno-policies/README.md, charts/kyverno/Chart.yaml, charts/kyverno/README.md
=> release 1.10.7

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/commands/test/command.go, cmd/cli/kubectl-kyverno/commands/test/test.go, cmd/cli/kubectl-kyverno/deprecations/check.go, cmd/cli/kubectl-kyverno/variables/new.go, cmd/cli/kubectl-kyverno/variables/new_test.go
Add deprecation warnings in the CLI.
=> feat: add deprecation warnings in the CLI

cmd/cli/kubectl-kyverno/processor/policy_processor_test.go, cmd/cli/kubectl-kyverno/processor/result.go
Remove skip increment when resource not found in cli apply.
Fixes #9058
=> fix: remove skip increment when resource not found in cli apply

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/commands/test/test.go, cmd/cli/kubectl-kyverno/processor/policy_processor.go, cmd/cli/kubectl-kyverno/processor/policy_processor_test.go
=> fix(kubectl-kyverno): apply registry auth (cherry-pick #9151)

charts/kyverno/Chart.yaml
=> chore: update chart.yaml with the changes (cherry-pick #9070)

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/commands/test/command.go, cmd/cli/kubectl-kyverno/commands/test/test.go, cmd/cli/kubectl-kyverno/deprecations/check.go, cmd/cli/kubectl-kyverno/variables/new.go, cmd/cli/kubectl-kyverno/variables/new_test.go
feat: add deprecation warnings in the CLI (cherry-pick #9222)
=> feat: add deprecation warnings in the CLI (cherry-pick #9222)

cmd/cli/kubectl-kyverno/commands/test/output.go, cmd/cli/kubectl-kyverno/output/color/color.go, test/cli/test/exclude/kyverno-test.yaml, test/cli/test/exclude/policy.yaml, test/cli/test/exclude/resources.yaml
When resources are excluded the `EngineResponse` doesn't contain any `RuleResponse`s. This wasn't handled in the CLI and the resources were reported as `Not Found`.
Closes #8828 .
/milestone 1.11.2
/kind bug
If there are `EngineResponse`s but no `RuleResponse`s then report the resource as excluded.
The aforementioned issue contains the proof manifests.
=> fix(cli): handle excluded resources as pass

cmd/cli/kubectl-kyverno/commands/test/output.go, cmd/cli/kubectl-kyverno/output/color/color.go, test/cli/test/exclude/kyverno-test.yaml, test/cli/test/exclude/policy.yaml, test/cli/test/exclude/resources.yaml
=> fix(cli): handle excluded resources as pass (cherry-pick #9274)

test/conformance/chainsaw/validate/anchors/conditional/chainsaw-test.yaml, test/conformance/chainsaw/validate/anchors/conditional/labelled-resource.yaml, test/conformance/chainsaw/validate/anchors/conditional/namespace.yaml, test/conformance/chainsaw/validate/anchors/conditional/policy-ready.yaml, test/conformance/chainsaw/validate/anchors/conditional/policy.yaml, test/conformance/chainsaw/validate/anchors/conditional/unlabelled-resource.yaml
K8s selectors are merged into one string this ruins pattern matching. This commit spreads them into a map.
Fixes #7939
/milestone 1.11.2
/kind bug
Spread K8s selectors to a map.
=> fix(anchors): spread selectors

ADOPTERS.md
=> add Censhare to ADOPTERS.md

cmd/background-controller/main.go, cmd/cleanup-controller/main.go, cmd/internal/client.go, cmd/internal/config.go, cmd/internal/flag.go, cmd/internal/setup.go, cmd/kyverno/main.go, cmd/reports-controller/main.go, pkg/event/controller.go
When we flood Kyverno with requests it creates multiple events for each request for various actions. The `EventBroadcaster` creates a `goroutine` for each event which increases the memory usage and in turn crashes Kyverno. 
This PR creates a new client for the Events controller to increase its QPS and Burst to handle this flood of Events and better handle this burst of `goroutines`.
Closes #9197
https://github.com/kyverno/website/pull/1099
/kind feature
This PR creates a new client for the Events controller to increase its QPS and Burst to handle this flood of Events and better handle this burst of `goroutines`.
=> feat: add new client for events

pkg/controllers/validatingadmissionpolicy-generate/policycheck.go, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-exclude-namespace/chainsaw-test.yaml, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-exclude-namespace/policy-assert.yaml, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-exclude-namespace/policy.yaml, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-exclude-namespace/validatingadmissionpolicy.yaml, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-exclude-namespace/validatingadmissionpolicybinding.yaml
There are unnecessary checks for `exclude.any/all` in generating VAPs. If a Kyverno policy has an `exclude` block, the corresponding VAP isn't generated so there is no reason to check the contents of the exclude block.
None
/kind cleanup
A chainsaw test is added.
=> fix: remove the check of exclude in VAPs

pkg/webhooks/resource/generation/handler.go, pkg/webhooks/resource/updaterequest.go, pkg/webhooks/resource/utils.go
This PR skips admission requests for non-trigger resources regardless of `skipBackgroundRequests` settings for a Generate policy. The only action that can trigger a "synchronize" reconciliation is when the requests are sent by non-kyverno controllers (users).
Closes https://github.com/kyverno/kyverno/issues/9313.
/1.11.3
/bug
=> fix: non-trigger resources should be skipped for background policies regardless of `skipBackgroundRequests` settings

test/conformance/chainsaw/validate/clusterpolicy/standard/psa/test-exclusion-host-ports/bad-pod.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/psa/test-exclusion-host-ports/good-pod.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/psa/test-exclusion-hostprocesses/bad-pod.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/psa/test-exclusion-hostprocesses/excluded-pod.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/psa/test-exclusion-hostprocesses/good-pod.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/psa/test-exclusion-procmount/excluded-pod.yaml
This PR contains minor fixes related to PSA chainsaw tests.
=> fix PSA chainsaw tests

.github/workflows/report-on-vulnerabilities.yaml
Modifies the `report-on-vulnerabilities` workflow to be more specific on counting the results. While this wasn't necessary before, Trivy appears to be listing components now which have any vulns even if the list only includes those of a specific severity. This appears to be a behavioral change on Trivy's side.
Fixes #8979
/kind bug
Adds `.Vulnerabilities` to the workflow to count from the array of returned vulnerabilities.
Before:
```sh
~ cat ~/Downloads/scan.json | jq '.Results[] | select(.Target=="ko-app/kyverno") | length'
3
```
After:
```sh
~ cat ~/Downloads/scan.json | jq '.Results[] | select(.Target=="ko-app/kyverno").Vulnerabilities | length'
0
```
=> Fix report-on-vulnerabilities

charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/ci/nodeSelector-global-values.yaml, charts/kyverno/templates/admission-controller/deployment.yaml, charts/kyverno/templates/background-controller/deployment.yaml, charts/kyverno/templates/cleanup-controller/deployment.yaml, charts/kyverno/templates/cleanup/cleanup-admission-reports.yaml, charts/kyverno/templates/cleanup/cleanup-cluster-admission-reports.yaml, charts/kyverno/templates/hooks/post-upgrade.yaml, charts/kyverno/templates/hooks/pre-delete.yaml, charts/kyverno/templates/reports-controller/deployment.yaml, charts/kyverno/values.yaml
Allow a global node selector to apply to all pods in the kyverno Helm chart
This is useful for sites where infrastructure or certain types of workloads should be kept on specific set of nodes.
=> Add global nodeSelector

pkg/background/generate/generate.go, pkg/validation/policy/background.go, test/conformance/chainsaw/generate/clusterpolicy/cornercases/cpol-data-trigger-not-present/README.md, test/conformance/chainsaw/generate/clusterpolicy/cornercases/cpol-data-trigger-not-present/chainsaw-test.yaml, test/conformance/chainsaw/generate/clusterpolicy/cornercases/cpol-data-trigger-not-present/generated.yaml, test/conformance/chainsaw/generate/clusterpolicy/cornercases/cpol-data-trigger-not-present/policy-ready.yaml, test/conformance/chainsaw/generate/clusterpolicy/cornercases/cpol-data-trigger-not-present/policy.yaml, test/conformance/chainsaw/generate/clusterpolicy/cornercases/cpol-data-trigger-not-present/rbac.yaml, test/conformance/chainsaw/generate/clusterpolicy/cornercases/cpol-data-trigger-not-present/roles.yaml
This PR fixes the UR cleanup when the trigger resource does not present in the cluster. It also clarifies the failure detail when admission user variables are used in the rule with sync=true, the following log message will be printed out:
```
I0109 08:10:38.608437       1 generate.go:364] "warning: resources with admission request variables may not be regenerated" logger="background" name="ur-lmsdh" resource="v1/Namespace//" policy="add-ns-access-controls" rule="generate-owner-role" variable="{{request.userInfo.username}}"
```
Closes https://github.com/kyverno/kyverno/issues/9350.
/1.12
/bug
=> fix: clean up URs if the trigger doesn't exist

charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/templates/hooks/post-upgrade.yaml, charts/kyverno/templates/hooks/pre-delete.yaml, charts/kyverno/values.yaml
This PR adds `podLabels` for the Jobs pod template in the helm hooks.
Closes #9365 
/kind feature
=> feat: add podLabels to the hook jobs pod template

charts/kyverno/README.md, charts/kyverno/values.yaml, config/install-latest-testing.yaml
=> chore: bump bitnami/kubectl  (Cherry-pick #9408)

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/policy/load.go
=> fix: add v1beta1 of VAPs in the CLI (#9404)

cmd/cli/kubectl-kyverno/processor/result.go, pkg/controllers/report/background/controller.go, pkg/controllers/report/utils/scanner.go, pkg/engine/api/engineresponse.go, pkg/engine/api/policy.go, pkg/engine/metrics.go, pkg/event/events.go, pkg/utils/report/results.go
Change generic policy to not return any.
=> fix: change generic policy to not return any

Makefile
Load cli image when deploying locally.
=> chore: load cli image when deploying locally

README.md
Update README for new features and OSS security index card.
N/A
=> update README for new features and OSS security index card

charts/kyverno/README.md, charts/kyverno/templates/admission-controller/clusterrole.yaml, charts/kyverno/templates/cleanup-controller/clusterrole.yaml, charts/kyverno/templates/hooks/crds-migration/cleanup-post-upgrade.yaml, charts/kyverno/values.yaml, config/install-latest-testing.yaml
In 1.10:
- v2alpha1 is the storage version
In 1.11:
- v2beta1 is the storage version
- v2alpha1 is deprecated
In 1.12:
- v2beta1 is the storage version
- v2alpha1 is unserved
- v2 is introduced
This PR migrate the existing cleanup policies to the new storage version `v2beta1` as a post-upgrade helm hook.
Related to #5606
/kind feature
=> feat: migrate existing cleanup policies to the new storage version in helm hook

pkg/utils/admission/cleanup_test.go
This PR Adds test for `pkg/utils/admission/cleanup.go` 
This PR does not related to any issue but it adds unit test for `pkg/utils/admission/cleanup.go` 
=> test: added test for pkg/utils/admission/cleanup.go

CONTRIBUTORS.md
Add Anushka Mittal as contributor
5 merged PRs
1. https://github.com/kyverno/kyverno/pull/2360
2. https://github.com/kyverno/kyverno/pull/2543
3. https://github.com/kyverno/kyverno/pull/2441
4. https://github.com/kyverno/kyverno/pull/2707
5. https://github.com/kyverno/kyverno/pull/2483
NA
Added Anushka Mittal as contributor.
=> add Anushka Mittal as contributor

charts/kyverno/README.md, charts/kyverno/values.yaml, config/install-latest-testing.yaml, scripts/config/standard/kyverno.yaml
Omit PolicyApplied and PolicySkipped Events by default to get a performance increase.
/kind feature
=> chore(helm): omit normal events by default

charts/kyverno/templates/admission-controller/clusterrole.yaml, charts/kyverno/templates/reports-controller/clusterrole.yaml, config/install-latest-testing.yaml
Add more granular rbac rules to remove wildcards in follow up PRs.
=> feat: add more granular rbac rules to remove wildcards

pkg/utils/admission/policy_test.go
This PR Adds test for `pkg/utils/admission/policy.go` 
This PR adds unit test for `pkg/utils/admission/policy.go` and partially fixes #9514 
=> test: added test for pkg/utils/admission/policy.go

charts/kyverno/README.md, charts/kyverno/README.md.gotmpl, charts/kyverno/ci/resourceFiltersInclude-values.yaml, charts/kyverno/templates/config/_helpers.tpl, charts/kyverno/values.yaml
This PR adds the `config.resourceFiltersIncludeNamespaces` and `config.resourceFiltersInclude` values to the kyverno helm chart. These values support adding additional elements to the default list of `config.resourceFilters` without forcing the user to override the entire `config.resourceFilters` list.
Closes #9529 
/kind feature
The default behavior of the kyverno helm chart is unchanged as  the `config.resourceFiltersIncludeNamespaces` and `config.resourceFiltersInclude` values default to an empty array. 
```yaml
---
config:
resourceFiltersInclude:
- '[MyCRD,*,*]'
- '[MyCRD/*,*,*]'
resourceFiltersIncludeNamespaces:
- "my-namespace"
```
=> #9529 Support adding extra elements to the default resourceFilters list

.github/workflows/check-actions.yaml, .github/workflows/cli.yaml, .github/workflows/codecov.yaml, .github/workflows/comment-commands.yaml, .github/workflows/devcontainer-build.yaml, .github/workflows/fossa.yml, .github/workflows/helm-release.yaml, .github/workflows/helm-test.yaml, .github/workflows/images-build.yaml, .github/workflows/images-publish.yaml, .github/workflows/lint.yaml, .github/workflows/nancy.yaml, .github/workflows/pr-update.yaml, .github/workflows/release.yaml, .github/workflows/report-on-vulnerabilities.yaml, .github/workflows/scorecard.yaml, .github/workflows/sonarcloud.yaml, .github/workflows/tests.yaml, .github/workflows/verify-codegen.yaml
Configure gh workflows schemas.
=> chore: configure gh workflows schemas

CONTRIBUTING.md, test/conformance/chainsaw/mutate/e2e/jmespath-logic/README.md, test/conformance/chainsaw/verifyImages/clusterpolicy/standard/configmap-context-lookup/README.md
=> chore: remove reference to kuttl

pkg/engine/handlers/validation/validate_resource.go
=> fix: follow up for #9534

.nancy-ignore
=> fix: nancy ignore

charts/kyverno/README.md, charts/kyverno/README.md.gotmpl, charts/kyverno/templates/NOTES.txt
Signed-off-by: chipzoller <chipzoller@gmail.com>
AKS users who install Kyverno are suffering sometimes cluster-breaking issues when AKS' Admissions Enforcer has a reconciliation war with Kyverno's controllers over the webhooks. Although this can be avoided by users assigning an annotation during the Helm installation, this annotation must be manually assigned. We continue to find that too many aren't aware of this, proceed to install Kyverno, and their clusters experience issues.
Closes #7386
This PR adds a simple note at the end of a successful installation of the Kyverno chart (regardless of the values used) which warns AKS users about disabling the Admission Enforcer via a link to the relevant …
=> Add Helm note for AKS users

pkg/utils/policy/marshal_test.go
This PR Adds test for `pkg/utils/policy/marshal.go` 
This PR adds unit test for `pkg/utils/policy/marshal.go`, and closes #9575 
=> test: added test for pkg/utils/policy/marshal.go

docs/user/cli/crd/index.html
=> fix: update cli docs

go.mod, go.sum, pkg/cosign/cosign.go
Bumps [github.com/sigstore/cosign/v2](https://github.com/sigstore/cosign) from 2.2.2 to 2.2.3.
=> chore(deps): bump github.com/sigstore/cosign/v2 from 2.2.2 to 2.2.3

test/conformance/chainsaw/.chainsaw.yaml
Enable chainsaw fail fast mode.
=> chore: enable chainsaw fail fast

cmd/cli/kubectl-kyverno/commands/apply/command.go
I want to be able to use exception in cli public with this PR
NA
=> make exception in cli exportable

charts/kyverno/README.md, charts/kyverno/templates/_helpers.tpl, charts/kyverno/templates/admission-controller/deployment.yaml, charts/kyverno/templates/background-controller/deployment.yaml, charts/kyverno/templates/cleanup-controller/deployment.yaml, charts/kyverno/templates/reports-controller/deployment.yaml, charts/kyverno/values.yaml, cmd/background-controller/main.go, cmd/cleanup-controller/main.go, cmd/kyverno/main.go, cmd/reports-controller/main.go, config/install-latest-testing.yaml
Add global context support in helm chart.
=> feat: add global context support in helm chart

api/kyverno/v2alpha1/global_context_entry_types.go, api/kyverno/v2alpha1/zz_generated.deepcopy.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_globalcontextentries.yaml, config/crds/kyverno/kyverno.io_globalcontextentries.yaml, config/install-latest-testing.yaml, docs/user/crd/index.html, pkg/client/applyconfigurations/kyverno/v2alpha1/externalapicall.go, pkg/controllers/globalcontext/controller.go
Update refreshInterval in globalcontext CRD to use a duration
=> feat: update refreshInterval in globalcontext CRD to use a duration

cmd/cli/kubectl-kyverno/commands/apply/command.go, docs/user/cli/commands/kyverno_apply.md
This PR will add `-e` shorthand letter with `--exception` flag in apply command 
Closes: #9623 
=> support -e shorthand letter with --exception flag

.github/workflows/conformance.yaml, test/conformance/chainsaw/globalcontext/validate-crd/README.md, test/conformance/chainsaw/globalcontext/validate-crd/chainsaw-test.yaml, test/conformance/chainsaw/globalcontext/validate-crd/multiple-resources.yaml, test/conformance/chainsaw/globalcontext/validate-crd/no-resource.yaml, test/conformance/chainsaw/globalcontext/validate-crd/valid-context-assert.yaml, test/conformance/chainsaw/globalcontext/validate-crd/valid-context.yaml
add chainsaw tests for global context crd validation
=> feat: add chainsaw tests for global context crd validation

test/conformance/chainsaw/flags/standard/emit-events/chainsaw-test.yaml, test/conformance/chainsaw/generate/clusterpolicy/cornercases/cpol-data-trigger-not-present/chainsaw-test.yaml, test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/delete-trigger-namespace/chainsaw-test.yaml, test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/multiple-trigger-resources/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/cornercases/cel-messages-upon-resource-failure/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/audit/background-match-clusterRoles/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/audit/background-match-roles/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/audit/background-vars-roles/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/audit/background-vars-serviceAccountName/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/audit/background-vars-userInfo/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/enforce/block-pod-exec-requests/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/enforce/bypass-with-policy-exception/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/enforce/operator-allnotin-01/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/enforce/scaling-with-kubectl-scale/chainsaw-test.yaml
This PR modifies the chainsaw tests to check the command output using either ($stdout) or ($stderr).
For more info, check [this](https://github.com/kyverno/chainsaw/blob/main/website/docs/examples/test-output.md) document from @chipzoller 
N/A
=> feat: use the check block for checking CLI output in chainsaw tests

charts/kyverno/README.md, charts/kyverno/templates/_helpers.tpl, charts/kyverno/values.yaml, cmd/background-controller/main.go, cmd/cleanup-controller/main.go, cmd/internal/config.go, cmd/internal/flag.go, cmd/kyverno/main.go, cmd/reports-controller/main.go, config/install-latest-testing.yaml
Disable GlobalContext by default.
/kind cleanup
=> chore(globalcontext): remove global context flag

charts/kyverno/README.md, charts/kyverno/values.yaml
=> fix: add missing migrations

test/conformance/chainsaw/webhook-configurations/webhook-registeration/README.md, test/conformance/chainsaw/webhook-configurations/webhook-registeration/chainsaw-test.yaml, test/conformance/chainsaw/webhook-configurations/webhook-registeration/policy-assert.yaml, test/conformance/chainsaw/webhook-configurations/webhook-registeration/policy.yaml, test/conformance/chainsaw/webhook-configurations/webhook-registeration/webhook.yaml
This PR adds a chainsaw test to check the webhook registeration and its deletion when the policy is created and then deleted.
=> feat: add chainsaw test for policy webhook based configuration

.github/actions/setup-test-env/action.yaml, .github/workflows/conformance.yaml, .github/workflows/load-testing.yml, Makefile
=> chore: bump kind and k8s images

.github/PULL_REQUEST_TEMPLATE.md
This PR marks the doc as required for new features in PR template.
=> chore: mark doc as required for new features in PR template

.github/workflows/conformance.yaml
=> chore(deps): bump kyverno/action-install-chainsaw from 0.1.2 to 0.1.3 #9682 (cherry-pick #9682)

.github/workflows/conformance.yaml, DEVELOPMENT.md
Cherry-picked fix: modify the conformance config name #9691
=> fix: modify the conformance config name (cherry-pick #9691)

charts/kyverno/README.md, charts/kyverno/values.yaml, cmd/reports-controller/main.go, config/install-latest-testing.yaml, pkg/controllers/report/aggregate/controller.go, pkg/controllers/report/aggregate/utils.go, pkg/utils/report/metadata.go
fix: reports aggregation (cherry-pick #9697)
=> fix: reports aggregation (cherry-pick #9697)

charts/kyverno-policies/Chart.yaml, charts/kyverno-policies/README.md, charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/charts/crds/Chart.yaml, charts/kyverno/charts/crds/README.md, charts/kyverno/charts/grafana/Chart.yaml, charts/kyverno/charts/grafana/README.md, config/install-latest-testing.yaml
=> release: v1.12.0-alpha.1

.github/workflows/codecov.yaml
=> chore: split codecov jobs

cmd/cli/kubectl-kyverno/commands/apply/command.go, docs/user/cli/commands/kyverno_apply.md
add --resources and --exceptions as aliases, in addition to the current singular form options (--resource and --exception.)
Closes #9586
kind feature
- [ √ ] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [ √ ] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.
=> add plural form aliases for resources and exceptions flags

cmd/cli/kubectl-kyverno/commands/apply/command_test.go, cmd/cli/kubectl-kyverno/commands/test/test.go, test/cli/test-validating-admission-policy/with-bindings-1/deployment3.yaml, test/cli/test-validating-admission-policy/with-bindings-1/kyverno-test.yaml, test/cli/test-validating-admission-policy/with-bindings-2/kyverno-test.yaml, test/cli/test-validating-admission-policy/with-bindings-3/deployment1.yaml, test/cli/test-validating-admission-policy/with-bindings-3/deployment2.yaml, test/cli/test-validating-admission-policy/with-bindings-3/deployment3.yaml, test/cli/test-validating-admission-policy/with-bindings-3/kyverno-test.yaml, test/cli/test-validating-admission-policy/with-bindings-3/values.yaml, test/cli/test-validating-admission-policy/with-bindings-4/deployment1.yaml, test/cli/test-validating-admission-policy/with-bindings-4/kyverno-test.yaml
This PR adds the support of binding in Kyverno CLI test command.
#9479 
/kind feature
```
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
name: "check-deployment-replicas"
spec:
resourceRules:
- apiGroups:
- apps
apiVersions:
- v1
operations:
- CREATE
- UPDATE
resources:
- deployments
validations:
- expression: object.spec.replicas <= 2
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicyBinding
metadata:
name: "check-deployment-replicas-binding"
spec:
policyName: "check-deployment-replicas"
validationActions: [Deny]
matchResources:
- key: environment
operator: In
values:
- …
```
=> feat: support bindings in Kyvenro CLI test command

CONTRIBUTORS.md
Adding myself to contributors list.
5 merged prs
1. #9533 
2. #9713 
3. #9534 
4. #9749 
5. #9719 
=> Adding myself  in  CONTRIBUTORS.md

api/kyverno/v2alpha1/global_context_entry_status.go, api/kyverno/v2alpha1/global_context_entry_types.go, api/kyverno/v2alpha1/zz_generated.deepcopy.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_globalcontextentries.yaml, config/crds/kyverno/kyverno.io_globalcontextentries.yaml, config/install-latest-testing.yaml, docs/user/crd/index.html, docs/user/crd/kyverno.v2alpha1.html, pkg/client/applyconfigurations/kyverno/v2alpha1/globalcontextentrystatus.go, pkg/globalcontext/event/reason.go, pkg/globalcontext/externalapi/entry.go, pkg/globalcontext/k8sresource/entry.go, pkg/globalcontext/store/store.go
1. Fix old WaitGroup not stopping
2. Add optional tag to `gctxentry.spec.kubernetesResource.namespace`
3. Add `AGE` column to `gctxentry`
4. Add `lastRefreshTime` to `gctxentry.status`
5. Handle Informer run errors. Including wrong GVR.
=> fix(globalcontext): old WaitGroup not stopping

api/kyverno/v1/common_types.go, api/kyverno/v1/rule_types.go, api/kyverno/v2beta1/policy_exception_types.go, pkg/policy/validate/validate.go, test/conformance/chainsaw/policy-validation/cluster-policy/invalid-pod-security-exceptions/chainsaw-test.yaml, test/conformance/chainsaw/policy-validation/cluster-policy/invalid-pod-security-exceptions/exception-1.yaml, test/conformance/chainsaw/policy-validation/cluster-policy/invalid-pod-security-exceptions/exception-2.yaml, test/conformance/chainsaw/policy-validation/cluster-policy/invalid-pod-security-exceptions/exception-3.yaml, test/conformance/chainsaw/policy-validation/cluster-policy/invalid-pod-security-rule/chainsaw-test.yaml
This PR adds validation checks for podSecurity in exceptions.
Closes #9807 
/kind bug
=> fix: add podSecurity validation checks for exceptions

.github/workflows/conformance.yaml, cmd/cli/kubectl-kyverno/_testdata/apply/test-2/policy.yaml, cmd/cli/kubectl-kyverno/_testdata/apply/test-2/resources.yaml, cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/commands/apply/command_test.go, cmd/cli/kubectl-kyverno/main.go, test/conformance/chainsaw/cli/apply/warn-exit-code/chainsaw-test.yaml, test/conformance/chainsaw/cli/apply/warn-exit-code/policy.yaml, test/conformance/chainsaw/cli/apply/warn-exit-code/resource.yaml
=> [Bug] [CLI] Restore warn-exit-code functionality for apply command (cherry-pick #9828)

ADOPTERS.md
Add a new adopter to `ADOPTERS.md`
Similar to https://github.com/kyverno/kyverno/pull/8871 https://github.com/kyverno/kyverno/pull/9311
=> docs: Add new adopter to ADOPTERS.md

pkg/registryclient/client.go
Image verify rules in Kyverno fails when it attempts to access an "insecure" OCI registry to fetch oci descriptors. This is happening because `FetchImageDescriptor` does not use crane opts. This PR updates that behaviour.
Closes #9808 
=> fix: use gcr crane opts while fetching image descriptors

go.mod, go.sum, pkg/pss/evaluate_test.go, test/conformance/chainsaw/exceptions/exclude-hostpath-volume/exception.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/psa/test-exclusion-hostpath-volume/bad-pod.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/psa/test-exclusion-hostpath-volume/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/psa/test-exclusion-hostpath-volume/policy.yaml
The upstream implementation missed returning bad values for podSecurity hostpath volume check. The upstream fix is sent via https://github.com/YTGhost/pod-security-admission/pull/1, this PR adds the missing test scenarios for such check.
Closes https://github.com/kyverno/kyverno/issues/9836.
/1.12
=> fix: add missing unit tests for podSecurity.hostpathVolume check

.github/workflows/release.yaml
Fix release CRDs manifests.
Closes #9724.
=> fix: release CRDs manifests

.github/workflows/release.yaml
=> fix: release CRDs manifests (cherry-pick#9849)

pkg/engine/apicall/apiCall.go, pkg/engine/apicall/apiCall_test.go, pkg/engine/apicall/executor.go, pkg/globalcontext/externalapi/entry.go
Remove duplicate code from `apicall` package.
=> chore(apicall): remove duplicate code

CONTRIBUTORS.md
5 merged PRs
- https://github.com/kyverno/kyverno/pull/9785
- https://github.com/kyverno/kyverno/pull/9658
- https://github.com/kyverno/kyverno/pull/9395
- https://github.com/kyverno/website/pull/1171
- https://github.com/kyverno/website/pull/1168
Open PR
- https://github.com/kyverno/kyverno/pull/9611
Opened and closed issues
- https://github.com/kyverno/kyverno/issues/9393
- https://github.com/kyverno/kyverno/issues/9594
- https://github.com/kyverno/kyverno/issues/9398
=> Adding Suruchi Kumari as contributor 

cmd/cli/kubectl-kyverno/commands/apply/command.go, pkg/engine/handlers/validation/validate_image.go, pkg/engine/handlers/validation/validate_pss.go, pkg/engine/handlers/validation/validate_resource.go, pkg/pss/evaluate.go, pkg/pss/utils/mapping.go, pkg/pss/utils/types.go, pkg/utils/report/metadata.go, pkg/utils/report/results.go, test/conformance/chainsaw/reports/background/test-report-background-mode/report-assert.yaml
Add control names and images to 
Fixes https://github.com/kyverno/kyverno/issues/9787
/milestone 1.13
/kind design
Added JSON string to reports, so tools can parse control and image details to produce exceptions.
```sh
/cmd/cli/kubectl-kyverno/kubectl-kyverno apply /tmp/restricted.yaml --cluster -n default -p
apiVersion: wgpolicyk8s.io/v1alpha2
kind: ClusterPolicyReport
metadata:
creationTimestamp: null
name: merged
results:
- message: 'Validation rule ''restricted'' failed. It violates PodSecurity "restricted:latest":
(Forbidden reason: allowPrivilegeEscalation != false, field error list: [spec.containers[0].securityContext.allowPrivilegeEscalation:
Required value])(Forbidden reason: unrestricted capabilities, field error list:
[spec.containers[0].securityContext.capabilities.drop: …
```
=> add control names and images to PSS results

pkg/engine/handlers/validation/validate_pss_test.go, pkg/engine/policycontext/policy_context.go
Add unit tests for PSS data in policy reports
n/a
1.13
/kind cleanup
=> add unit test

.nancy-ignore
=> chore: fix nancy ignore

pkg/engine/exceptions.go
Simplify getting exception name.
=> chore: simplify getting exception name

api/kyverno/v1/common_types.go, api/kyverno/v2alpha1/global_context_entry_types.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_cleanuppolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clustercleanuppolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clusterpolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_globalcontextentries.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, config/crds/kyverno/kyverno.io_cleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clustercleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clusterpolicies.yaml, config/crds/kyverno/kyverno.io_globalcontextentries.yaml, config/crds/kyverno/kyverno.io_policies.yaml, config/install-latest-testing.yaml, docs/user/crd/index.html, docs/user/crd/kyverno.v1.html
=> chore(gctx): document schema better

test/cli/test-generate/clone-list/kyverno-test.yaml, test/cli/test/deny-pod-delete-match-opn-block/values.yaml, test/cli/test/update/values.yaml
This PR runs `make codegen-fix-tests`.
=> chore: run codegen-fix-tests

api/kyverno/v1/image_verification_types.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clusterpolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, config/crds/kyverno/kyverno.io_clusterpolicies.yaml, config/crds/kyverno/kyverno.io_policies.yaml, config/install-latest-testing.yaml, pkg/engine/internal/imageverifier.go
This PR 
1. Adds rekor and opts to cosign certificate verification.
2. Make rekor url optional
```yaml
metadata:
name: check-image-venafi-key
spec:
rules:
- name: check-image-venafi-key
match:
resources:
kinds:
- Pod
verifyImages:
- imageReferences:
- "*"
attestors:
- count: 1
entries:
- certificates:
cert: |-
-----BEGIN CERTIFICATE-----
MIIDTTCCAjWgAwIBAgIJAPI+zAzn4s0xMA0GCSqGSIb3DQEBCwUAMEwxCzAJBgNV
BAYTAlVTMQswCQYDVQQIDAJXQTEQMA4GA1UEBwwHU2VhdHRsZTEPMA0GA1UECgwG
Tm90YXJ5MQ0wCwYDVQQDDAR0ZXN0MB4XDTIzMDUyMjIxMTUxOFoXDTMzMDUxOTIx
MTUxOFowTDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAldBMRAwDgYDVQQHDAdTZWF0 …
```
=> fix: add rekor opts to cosign certificate verification and make rekor url optional

pkg/cosign/cosign_test.go
Fix string matching problem in unit test
=> fix: cosign ctlog unit tests

.github/workflows/check-milestone.yaml
This PR adds a job to check that the milestone of each opened PR is set.
N/A
/kind feature
=> chore: add a job to check the PR milestone is set

api/kyverno/v1/image_verification_types.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clusterpolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, config/crds/kyverno/kyverno.io_clusterpolicies.yaml, config/crds/kyverno/kyverno.io_policies.yaml, config/install-latest-testing.yaml, docs/user/crd/index.html, docs/user/crd/kyverno.v1.html, pkg/client/applyconfigurations/kyverno/v1/ctlog.go, pkg/cosign/cosign.go, pkg/cosign/cosign_test.go, pkg/engine/internal/imageverifier.go, pkg/images/verifier.go, test/conformance/chainsaw/verifyImages/clusterpolicy/standard/keyed-tsa/README.md, test/conformance/chainsaw/verifyImages/clusterpolicy/standard/keyed-tsa/chainsaw-step-01-apply-1.yaml, test/conformance/chainsaw/verifyImages/clusterpolicy/standard/keyed-tsa/chainsaw-step-01-apply-2.yaml, test/conformance/chainsaw/verifyImages/clusterpolicy/standard/keyed-tsa/chainsaw-step-01-assert-1.yaml, test/conformance/chainsaw/verifyImages/clusterpolicy/standard/keyed-tsa/chainsaw-step-02-apply-1.yaml, test/conformance/chainsaw/verifyImages/clusterpolicy/standard/keyed-tsa/chainsaw-step-02-assert-1.yaml, test/conformance/chainsaw/verifyImages/clusterpolicy/standard/keyed-tsa/chainsaw-test.yaml
Add support for TSACertChain in cosign verify images
/release 1.13
=> feat: add TSA cert chain support in cosign

.github/workflows/check-milestone.yaml
Exclude prs from dependabot in check milestone workflow
=> fix: exclude prs from dependabot in check milestone workflow

.github/workflows/check-milestone.yaml, ADOPTERS.md
=> fix: dependabot prs will not be checked for milestone

DEVELOPMENT.md, docs/dev/README.md
=> update dev docs

charts/kyverno/templates/_helpers/_flowcontrol.tpl
The `FlowControl` API version has been promoted to `v1` in Kubernetes v1.29 and the previous `v1beta3` version will be removed in v1.32.
This PR adds the needed check to use `v1` and future-proofs the chart for when v1.32 is out.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-32
/kind feature
This PR only bumps the `FlowControl` API version to v1. There are no other changes needed.
```yaml
---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
name: kyverno-admission-controller
labels:
app.kubernetes.io/component: admission-controller
app.kubernetes.io/instance: release-name
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/part-of: release-name-kyverno
app.kubernetes.io/version: v0.0.0 …
```
=> feat: update flowcontrol API version to v1

pkg/controllers/report/aggregate/controller.go
This PR makes the following changes:
1. Only fetch ephemeral reports that have owner references set. This ensures that the report has been reconciled by the frontReconciler first before going to the backReconciler
2. Fixes a typo where a nil report was added instead of the actual report
Closes: #10123 
=> fix: fetch only adopted ephemeral report

charts/kyverno/README.md, charts/kyverno/templates/hooks/post-upgrade-clean-reports.yaml, charts/kyverno/templates/hooks/post-upgrade-migrate-resources.yaml, charts/kyverno/templates/hooks/pre-delete-scale-to-zero.yaml, charts/kyverno/values.yaml
Cherry-pick https://github.com/kyverno/kyverno/pull/9875.
=> [kyverno helm chart] make webhook pod annotations configurable (Cherry-pick #9875)

pkg/validatingadmissionpolicy/kyvernopolicy_checker.go, pkg/validatingadmissionpolicy/kyvernopolicy_checker_test.go, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-resources-in-namespaces-with-wildcard/chainsaw-test.yaml, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-resources-in-namespaces-with-wildcard/policy-assert.yaml, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-resources-in-namespaces-with-wildcard/policy.yaml, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-resources-in-namespaces-with-wildcard/validatingadmissionpolicy.yaml, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/skip-generate/cpol-any-match-resources-in-namespaces-with-wildcard/validatingadmissionpolicybinding.yaml
This PR skips generating ValidatingAdmissionPolicies in case Kyverno policy declares namespaces with wildcards as follows:
```
rules:
- name: check-label-app
match:
any:
- resources:
kinds:
- Pod
namespaces: 
- "prod-*"
- "staging"
```
Related to #9981
/milestone 1.13
/kind bug
=> fix: skip generating VAPs in case namespace's name contains wildcards

pkg/webhooks/resource/validation/validation.go
This PR creates a separate context for reports generation for enforce policies.
Fixes https://github.com/kyverno/kyverno/issues/10219.
=> fix: isolate reports creation context

test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-any-match-resources-by-names/policy-assert.yaml
=> fix flake test in VAPs

test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-any-match-resources-by-names/policy-assert.yaml
=> fix flake test in VAPs (cherry-pick #10263)

charts/kyverno/README.md, charts/kyverno/charts/grafana/templates/dashboard.yaml, charts/kyverno/values.yaml
Support 2 features from the Grafana Operator:
folder: specify in which Grafana folder the dashboard will be imported
allowCrossNamespaceImport: allow to import this resources from an operator in a different namespace
=> feat(helm): GrafanaDashboard configuration

pkg/validatingadmissionpolicy/builder.go, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-kind-with-wildcard/chainsaw-test.yaml, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-kind-with-wildcard/policy-assert.yaml, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-kind-with-wildcard/policy.yaml, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-kind-with-wildcard/validatingadmissionpolicy.yaml, test/conformance/chainsaw/generate-validating-admission-policy/clusterpolicy/standard/generate/cpol-match-kind-with-wildcard/validatingadmissionpolicybinding.yaml
=> fix: generate VAPs that match all resources when kinds is set to * (cherry-pick #10208)

cmd/cli/kubectl-kyverno/_testdata/policies-invalid/artifacthub-pkg.yml, cmd/cli/kubectl-kyverno/_testdata/policies-invalid/chainsaw-test.yaml, cmd/cli/kubectl-kyverno/_testdata/policies-invalid/policy-ready.yaml, cmd/cli/kubectl-kyverno/_testdata/policies-mixed/artifacthub-pkg.yml, cmd/cli/kubectl-kyverno/_testdata/policies-mixed/cpol-pod-requirements.yaml, cmd/cli/kubectl-kyverno/_testdata/policies-mixed/nested/artifacthub-pkg.yml, cmd/cli/kubectl-kyverno/_testdata/policies-mixed/nested/cpol-pod-requirements.yaml, cmd/cli/kubectl-kyverno/_testdata/policies/restricted.yaml, cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/commands/fix/policy/options.go, cmd/cli/kubectl-kyverno/commands/oci/push/options.go, cmd/cli/kubectl-kyverno/commands/test/command.go, cmd/cli/kubectl-kyverno/commands/test/compare.go, cmd/cli/kubectl-kyverno/commands/test/load.go, cmd/cli/kubectl-kyverno/commands/test/output.go, cmd/cli/kubectl-kyverno/commands/test/test.go, cmd/cli/kubectl-kyverno/policy/legacy_loader.go, cmd/cli/kubectl-kyverno/policy/load.go, cmd/cli/kubectl-kyverno/policy/load_test.go, cmd/cli/kubectl-kyverno/policy/variables_test.go, cmd/cli/kubectl-kyverno/report/report_test.go
=> Fix cli load policies from fs (Cherry-pick #10270)

pkg/controllers/webhook/utils.go, test/conformance/chainsaw/webhook-configurations/webhook-registeration/webhook.yaml, test/conformance/chainsaw/webhooks/all-scale/webhooks.yaml, test/conformance/chainsaw/webhooks/clusterpolicy/webhooks.yaml, test/conformance/chainsaw/webhooks/double-wildcard/webhooks.yaml, test/conformance/chainsaw/webhooks/dyn-op-validate-multiple/webhooks.yaml, test/conformance/chainsaw/webhooks/only-pod/webhooks.yaml, test/conformance/chainsaw/webhooks/pod-all-subresources/webhooks.yaml, test/conformance/chainsaw/webhooks/policy-clusterpolicy-different-resource-group/webhooks.yaml, test/conformance/chainsaw/webhooks/policy-clusterpolicy-namespaced-clusterscoped-resources/webhooks.yaml, test/conformance/chainsaw/webhooks/policy-clusterpolicy-namespaced-resources/webhooks.yaml, test/conformance/chainsaw/webhooks/policy-clusterpolicy-same-resource/webhooks.yaml, test/conformance/chainsaw/webhooks/policy-clusterpolicy-wildcard-resource/webhooks.yaml, test/conformance/chainsaw/webhooks/policy-different-resource-group/webhooks.yaml, test/conformance/chainsaw/webhooks/policy-wildcard-resource/webhooks.yaml, test/conformance/chainsaw/webhooks/policy/webhooks.yaml
This PR sorts the operations list in the webhookconfiguration to avoid unnecessary updates for the unordered list.
Closes https://github.com/kyverno/kyverno/issues/10237.
/bug
=> fix: sort webhookconfig.operations

pkg/engine/validate/validate.go, pkg/engine/validate/validate_test.go
When a SKIP anchor fails its result is aggregated but not returned. When another non-SKIP anchor fails its result is returned. This shouldn't happen the SKIP anchor result should have priority. It's returned later down that path. This fixes the problem by not returning a non-SKIP anchor result if there is a SKIP anchor result already in the aggregate slice.
Fixes #10117
https://github.com/kyverno/website/pull/1248
=> fix(anchor): skip anchors don't have priority

cmd/cli/kubectl-kyverno/commands/apply/command.go
make already existing `continue-on-fail` flag available outside package
N/A
/milestone 1.12.2
chore
make flag public
=> chore: make continue-on-fail flag available outside package

charts/kyverno/README.md, charts/kyverno/templates/cleanup/cleanup-cluster-ephemeral-reports.yaml, charts/kyverno/templates/cleanup/cleanup-ephemeral-reports.yaml, charts/kyverno/templates/cleanup/clusterrole.yaml, charts/kyverno/values.yaml, config/install-latest-testing.yaml
This PR adds cleanup cronjobs to delete (cluster)ephemeralreports, the threshold is set to 10000 by default which can be configured via Helm.
https://github.com/kyverno/kyverno/issues/10308
/1.12.3
/feat
=> feat: add cleanup cronjobs for (cluster)ephemeralreports

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/commands/apply/command_test.go, cmd/cli/kubectl-kyverno/processor/policy_processor.go, cmd/cli/kubectl-kyverno/processor/policy_processor_test.go, cmd/cli/kubectl-kyverno/processor/result.go, cmd/cli/kubectl-kyverno/processor/vap_processor.go
This PR removes unused parameters/variables.
=> fix: remove unused parameters

.nancy-ignore
Update nancy ignore with one more month.
=> chore: update nancy ignore

.github/workflows/check-milestone.yaml
=> chore: fix check milestone job

go.mod, go.sum
=> chore: normalize go mod

cmd/reports-controller/main.go
=> feat: add aggregation workers flag

pkg/globalcontext/externalapi/entry.go
When an APIRequest fails it sets the error of a GlobalContextEntry but when it succeeds again it doesn't reset this error causing the old error to be returned. This PR resets the error.
Closes #10397
=> fix(gctx): returning old error

pkg/controllers/report/utils/scanner.go
A log message was added in #10287 that added a log message without verbosity, this PR fixes that.
Related to #10399
=> fix: add verbosity to background scanner log

DEVELOPMENT.md
Add links to docs in ./docs/dev folder
n/a
=> update dev guide

.github/workflows/conformance.yaml, test/conformance/chainsaw/lease/admission-controller/chainsaw-test.yaml, test/conformance/chainsaw/lease/background-controller/chainsaw-test.yaml, test/conformance/chainsaw/lease/cleanup-controller/chainsaw-test.yaml, test/conformance/chainsaw/lease/reports-controller/chainsaw-test.yaml
Add chainsaw test for controllers leader election (proper shutdown).
=> chore: add chainsaw test for controllers leader election

cmd/background-controller/main.go, cmd/cleanup-controller/main.go, cmd/kyverno/main.go, cmd/reports-controller/main.go
Cancel context for proper shutdown in reports-controller.
=> fix: cancel context for proper shutdown in reports-controller (#10415)

.github/workflows/conformance.yaml, test/conformance/chainsaw/lease/admission-controller/chainsaw-test.yaml, test/conformance/chainsaw/lease/background-controller/chainsaw-test.yaml, test/conformance/chainsaw/lease/cleanup-controller/chainsaw-test.yaml, test/conformance/chainsaw/lease/reports-controller/chainsaw-test.yaml
Add chainsaw test for controllers leader election.
=> chore: add chainsaw test for controllers leader election (#10416)

.github/workflows/conformance.yaml
https://sigstore.slack.com/archives/C01DGF0G8U9/p1718204315549609
=> chore: temporarily remove sigstore tests to unblock PRs

.github/workflows/report-on-vulnerabilities.yaml
Github's branches endpoint fetches a maximum of 30 branches in 1 api call by default: https://docs.github.com/en/rest/branches/branches?apiVersion=2022-11-28#list-branches 
Currently Kyverno has 45 branches. This leads to an issue where all the latest release-* branches are not fetched causing the workflow to pick up older releases.
Proof: https://github.com/kyverno/kyverno/actions/runs/9501559167/job/26187363210?pr=10462
=> fix: fetch all branches (max 100) in report on vulnerability workflow

.github/workflows/conformance.yaml, test/conformance/chainsaw/custom-sigstore/standard/basic/policy.yaml
* feat: add custom sigstore conformance tests
---------
=> feat: fix custom sigstore conformance tests (#10473)

charts/kyverno/README.md, charts/kyverno/values.yaml, config/install-latest-testing.yaml
The version 1.28.5 of the bitnami/kubectl image is outdated and contains various CVEs. This PR updates the image to the latest version.
Output of `trivy image bitnami/kubectl:1.28.5 --ignore-unfixed`
```
bitnami/kubectl:1.28.5 (debian 11.8)
Total: 24 (UNKNOWN: 0, LOW: 2, MEDIUM: 7, HIGH: 15, CRITICAL: 0)
```
=> chore: bump bitnami/kubectl to 1.30.2

Makefile
Fix missing codegen deep copy dependency.
=> fix: missing codegen deep copy dependency

.github/actions/setup-build-env/action.yaml, go.mod
Closes https://github.com/kyverno/kyverno/issues/10509.
=> fix: Golang CVE

pkg/utils/report/new.go
cherry-pick https://github.com/kyverno/kyverno/pull/10491.
=> fix: use generate name for admission reports (cherry-pick #10491)

api/kyverno/any.go, api/kyverno/v2/condition.go, api/kyverno/v2/condition_test.go, docs/user/crd/index.html, pkg/client/applyconfigurations/kyverno/v2/condition.go, pkg/utils/conditions/condition_test.go
Make `Any` struct common to all api versions.
=> feat: make any struct common to all api versions

pkg/background/mutate/mutate.go
Move mutate existing rule skipped log to v4
#9941 
=> move mutate existing rule skipped log to v4

pkg/engine/background.go, pkg/engine/handlers/mutation/mutate_existing.go, pkg/engine/handlers/mutation/mutate_image.go, pkg/engine/handlers/mutation/mutate_resource.go
This PR fixes the rule type for mutate and generate policies.
=> fix rule type for mutate and generate rules

pkg/webhooks/resource/validation/validation.go
include error message when policy context creation failed
Closes #10555
/kind bug
=> fix: include error message when policy context creation failed

pkg/notary/notary_test.go, pkg/notary/repository_test.go
=> feat: fix notary tests

pkg/controllers/cleanup/controller.go
This PR avoid reassigning the logger within the `enqueueFunc` function in the cleanup controller that results in appending the cleanup policy name.
Closes #10571 
/milestone 1.12.4
/kind bug
1. Create the following clustercleanup policy that is executed every minute:
2. Check the logs:
```
2024-07-02T16:41:00+03:00	INFO	cleanup-controller	cleanup/controller.go:95	updated	{"kind": "ClusterCleanupPolicy", "operation": "updated", "name": "crossplane-gitlab-rotate-token-delete-mrs"}
2024-07-02T16:42:00+03:00	INFO	cleanup-controller	cleanup/controller.go:95	updated	{"kind": "ClusterCleanupPolicy", "operation": "updated", "name": "crossplane-gitlab-rotate-token-delete-mrs"}
2024-07-02T16:43:00+03:00	INFO	cleanup-controller …
```
=> fix: cleanup policy name is appended to logs

ADOPTERS.md
Signed-off-by: Chetan Deshmukh cdeshmukh@infracloud.io
Add InfraCloud as a Kyerno adopter.
=> updating adopters list - adding InfraCloud

pkg/controllers/cleanup/controller.go
Cherry-picked fix: failed to delete resource (cherry-pick #10582)
=> fix: failed to delete resource (cherry-pick #10582)

charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/templates/_helpers.tpl, charts/kyverno/values.yaml, config/install-latest-testing.yaml
Make reports breaker threshold configurable.
=> feat: make reports breaker threshold configurable

.github/workflows/conformance.yaml, cmd/cli/kubectl-kyverno/processor/policy_processor.go, test/conformance/chainsaw/cli/apply/apply-exception-with-ns-selector/README.md, test/conformance/chainsaw/cli/apply/apply-exception-with-ns-selector/chainsaw-test.yaml, test/conformance/chainsaw/cli/apply/apply-exception-with-ns-selector/exception.yaml, test/conformance/chainsaw/cli/apply/apply-exception-with-ns-selector/pod.yaml, test/conformance/chainsaw/cli/apply/apply-exception-with-ns-selector/policy.yaml
Cherry-picked fix: get ns labels in the cluster mode when using the CLI (https://github.com/kyverno/kyverno/pull/10348)
=> fix: get ns labels in the cluster mode when using the CLI (cherry-pick #10348)

CHANGELOG.md, charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/templates/_helpers.tpl, charts/kyverno/templates/reports-controller/deployment.yaml, charts/kyverno/values.yaml, cmd/reports-controller/main.go, config/install-latest-testing.yaml
Remove deprecated reports chunking.
=> feat: remove reports chunking

charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/templates/config/configmap.yaml, charts/kyverno/templates/hooks/pre-delete-configmap.yaml, charts/kyverno/values.yaml, cmd/background-controller/main.go, cmd/kyverno/main.go, config/install-latest-testing.yaml, pkg/config/config.go, pkg/policy/generate.go, pkg/policy/policy_controller.go, pkg/utils/generator/clusterephemeralreports.go, pkg/utils/generator/ephemeralreports.go, pkg/utils/generator/interface.go, pkg/utils/generator/updaterequests.go, pkg/webhooks/updaterequest/generator.go
=> feat: add a circuit breaker for updaterequests (Cherry-pick 10382)

cmd/kyverno/breaker.go
Don't rely on events unicity in resource counters.
=> feat: don't rely on events unicity in resource counters

pkg/engine/context/context.go, pkg/engine/context/utils.go, pkg/engine/context/utils_test.go
This PR overwrites the entire element key in the JSON Context map each `foreach` iteration to delete old values that don't exist.
Fixes #10437
=> fix(json-ctx): overwrite element each iteration

charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/templates/_helpers.tpl, charts/kyverno/values.yaml, cmd/kyverno/breaker.go, cmd/kyverno/main.go, cmd/kyverno/watch/watcher.go, config/install-latest-testing.yaml, pkg/d4f/breaker.go, pkg/d4f/breaker_test.go, pkg/webhooks/resource/handlers.go, pkg/webhooks/resource/imageverification/handler.go, pkg/webhooks/resource/validation/validation.go
feat: add reports circuit breaker (cherry-pick #10499 #10596 #10610 #10613)
=> feat: add reports circuit breaker (cherry-pick #10499 #10596 #10610 #10613)

pkg/engine/background.go, pkg/engine/engine.go, pkg/engine/forceMutate.go, pkg/engine/fuzz_test.go, pkg/engine/generation.go, pkg/engine/image_verify_test.go, pkg/engine/internal/imageverifier.go, pkg/engine/internal/match.go, pkg/engine/mutation_test.go
=> fix: remove unused parameters (cherry-pick #10330)

cmd/kyverno/main.go, cmd/reports-controller/main.go, pkg/validatingadmissionpolicy/utils.go
=> refactor: add a function to check if VAPs are registered in the API server (cherry-pick #10014)

pkg/engine/handlers/validation/validate_cel.go, test/conformance/chainsaw/validate/clusterpolicy/cornercases/cel-messages-upon-resource-failure/policy.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/authorizor-checks/with-permissions/policy.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/authorizor-checks/without-permissions/policy.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/cel-preconditions/policy.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/cel-variables/policy.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/check-statefulset-namespace/policy.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/deny/README.md, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/deny/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/deny/policy-assert.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/deny/policy.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/disallow-host-port/pod-fail.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/disallow-host-port/pod-pass.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/disallow-host-port/policy.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/parameter-resources/clusterscoped/policy.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/parameter-resources/namespaced/match-clusterscoped-resource/policy.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/parameter-resources/namespaced/set-paramref-namespace/policy.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/cel/parameter-resources/namespaced/unset-paramref-namespace/policy.yaml
=> fix: CEL policies aren't applied to deleted resources (cherry-pick #10611)

pkg/controllers/webhook/controller.go, pkg/controllers/webhook/controller_test.go
Same as  [this PR but for main](https://github.com/kyverno/kyverno/pull/10638)
Closes #10547 
=> fix: compute operations for mutatingwebhookconf

go.mod, go.sum, pkg/pss/evaluate_test.go, scripts/config/kind/default.yaml, test/conformance/chainsaw/exceptions/psa-run-as-non-root/README.md, test/conformance/chainsaw/exceptions/psa-run-as-non-root/bad-pod-01.yaml, test/conformance/chainsaw/exceptions/psa-run-as-non-root/bad-pod-02.yaml, test/conformance/chainsaw/exceptions/psa-run-as-non-root/chainsaw-test.yaml, test/conformance/chainsaw/exceptions/psa-run-as-non-root/exception.yaml, test/conformance/chainsaw/exceptions/psa-run-as-non-root/good-pod.yaml, test/conformance/chainsaw/exceptions/psa-run-as-non-root/policy-assert.yaml, test/conformance/chainsaw/exceptions/psa-run-as-non-root/policy.yaml, test/conformance/chainsaw/validate/clusterpolicy/cornercases/psa-run-as-non-root/README.md, test/conformance/chainsaw/validate/clusterpolicy/cornercases/psa-run-as-non-root/bad-pod-01.yaml, test/conformance/chainsaw/validate/clusterpolicy/cornercases/psa-run-as-non-root/bad-pod-02.yaml, test/conformance/chainsaw/validate/clusterpolicy/cornercases/psa-run-as-non-root/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/cornercases/psa-run-as-non-root/good-pod.yaml, test/conformance/chainsaw/validate/clusterpolicy/cornercases/psa-run-as-non-root/policy-assert.yaml, test/conformance/chainsaw/validate/clusterpolicy/cornercases/psa-run-as-non-root/policy.yaml
This PR makes use of the forked pod security repo from the Kyverno org and adds chainsaw tests covering the test cases mentioned in #10581 
Closes #10581 
/kind bug
=> feat add chainsaw tests for pod security and exceptions

DEVELOPMENT.md
… file
- [ x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
=> Updated the outdated example mentioned in Development.md file with latest one

cmd/cli/kubectl-kyverno/processor/policy_processor.go, test/conformance/chainsaw/cli/apply/apply-on-cluster-scoped-resources/chainsaw-test.yaml, test/conformance/chainsaw/cli/apply/apply-on-cluster-scoped-resources/policy.yaml
This PR checks that the resource namespace isn't empty for Kyverno CLI.
Closes #10735 
/milestone 1.12.6
/kind bug
Added a chainsaw test
=> fix: check the resource namespace

go.mod, go.sum
=> chore: bump kyverno-json

.github/workflows/nancy.yaml
Convert the Nancy scan to daily periodic scan task.
fixes #10680 
=> feat: Move Nancy scan to a periodic job

.github/workflows/conformance.yaml, go.mod, go.sum, pkg/notary/notary_test.go, pkg/notary/repository_test.go
Upgrades docker version
Closes: #10757 
=> fix: critical docker vulnerability in release 1.11

.github/workflows/conformance.yaml, test/conformance/chainsaw/.chainsaw.yaml, test/conformance/chainsaw/cli/apply/apply-exception-with-ns-selector/chainsaw-test.yaml, test/conformance/chainsaw/generate/clusterpolicy/cornercases/cpol-data-trigger-not-present/chainsaw-test.yaml, test/conformance/chainsaw/globalcontext/validate-reference/chainsaw-test.yaml, test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/delete-trigger-namespace/chainsaw-test.yaml, test/conformance/chainsaw/mutate/clusterpolicy/standard/existing/multiple-trigger-resources/chainsaw-test.yaml, test/conformance/chainsaw/policy-validation/cluster-policy/invalid-pod-security-exceptions/chainsaw-test.yaml, test/conformance/chainsaw/policy-validation/cluster-policy/invalid-pod-security-rule/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/cornercases/check-message-upon-resource-failure/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/cornercases/invalid-jmespath-variable-substitution/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/cornercases/variable-substitution-failure-messages/chainsaw-test.yaml
chore: bump chainsaw (cherry-pick #10687)
=> chore: bump chainsaw (cherry-pick #10687)

cmd/cli/kubectl-kyverno/processor/policy_processor.go
Currently, we are getting the ns labels each time we create a policy context which leads to a delay when running the Kyverno CLI. We don't need to get the resource's namespace each time we create a policy context. This PR fixes this issue and get the ns labels before creating a policy context.
Closes #10769 
/milestone 1.12.6
/kind bug
=> fix: get ns labels before creating a policy context

Makefile, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policyexceptions.yaml, config/crds/kyverno/kyverno.io_cleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clustercleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clusterpolicies.yaml, config/crds/kyverno/kyverno.io_globalcontextentries.yaml, config/crds/kyverno/kyverno.io_policies.yaml, config/crds/kyverno/kyverno.io_policyexceptions.yaml, config/crds/kyverno/kyverno.io_updaterequests.yaml, config/crds/policyreport/wgpolicyk8s.io_clusterpolicyreports.yaml, config/crds/policyreport/wgpolicyk8s.io_policyreports.yaml, config/crds/reports/reports.kyverno.io_clusterephemeralreports.yaml, config/crds/reports/reports.kyverno.io_ephemeralreports.yaml, go.mod, go.sum, hack/controller-gen/main.go, hack/controller-gen/markers.go
Adds support for `oneOf` and `not` schema validation
/kind feature
Improved JSON Schemas and replacement of internal policy validation checks with schema validation
=> feat: switch to custom crd generator

scripts/config/kind/audit-config.yaml, scripts/config/kind/audit-policy.yaml
This PR adds an Audit Policy and Kind Config to use it. This could be really helpful in getting insights on requests made against policies.
=> feat(audit): enable audit logs for kind

test/cli/test/globalcontext/kyverno-test.yaml, test/cli/test/globalcontext/policy.yaml, test/cli/test/globalcontext/resources.yaml, test/cli/test/globalcontext/values.yaml
This PR adds a test for injecting Global Context values for the `test` and `apply` commands in the Kyverno CLI.
https://github.com/kyverno/website/pull/1323
=> test(gctx): cli variable injection

Makefile, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_updaterequests.yaml, config/crds/kyverno/kyverno.io_updaterequests.yaml, config/install-latest-testing.yaml
This PR adds `v1beta1` to the CRD generation.
=> fix(codegen): missing crd version

pkg/logging/log.go
Set Zerolog Level to 1 - logr Level to keep them in sync.
=> fix(log): set zerolog level to logr level

go.mod, go.sum
=> fix: bump docker in release 1.11

pkg/cosign/sigstore.go, test/conformance/chainsaw/verifyImages/clusterpolicy/standard/sigstore-attestation-verification-regexp/policy.yaml
regexp support for sigstore bundle
=> feat: regexp support for sigstore bundle

api/kyverno/v2alpha1/global_context_entry_types.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_globalcontextentries.yaml, config/crds/kyverno/kyverno.io_globalcontextentries.yaml, config/install-latest-testing.yaml, docs/user/crd/index.html, docs/user/crd/kyverno.v2alpha1.html, pkg/client/applyconfigurations/kyverno/v2alpha1/externalapicall.go, pkg/globalcontext/externalapi/entry.go, test/conformance/chainsaw/globalcontext/apicall-correct/chainsaw-test.yaml, test/conformance/chainsaw/globalcontext/apicall-correct/main-deployment.yaml, test/conformance/chainsaw/globalcontext/apicall-correct/new-deployment.yaml, test/conformance/chainsaw/globalcontext/apicall-failed/gctxentry.yaml, test/conformance/chainsaw/globalcontext/gctxentry-not-exist/chainsaw-test.yaml, test/conformance/chainsaw/globalcontext/gctxentry-not-exist/main-deployment.yaml, test/conformance/chainsaw/globalcontext/not-ready/chainsaw-test.yaml, test/conformance/chainsaw/globalcontext/not-ready/gctxentry.yaml, test/conformance/chainsaw/globalcontext/not-ready/main-deployment.yaml, test/conformance/chainsaw/globalcontext/not-ready/new-deployment.yaml, test/conformance/chainsaw/globalcontext/resource-correct/chainsaw-test.yaml, test/conformance/chainsaw/globalcontext/resource-correct/main-deployment.yaml, test/conformance/chainsaw/globalcontext/resource-correct/new-deployment.yaml, test/conformance/chainsaw/globalcontext/validate-crd/valid-context.yaml
This PR adds Retry Logic to Global Context Entries.
Closes https://github.com/kyverno/kyverno/issues/9888
Related to [#9649](https://github.com/kyverno/kyverno/issues/9649)
=> feat(gctx): retry logic

.github/workflows/conformance.yaml
Simplify e2e matrix definition.
=> chore: simplify e2e matrix

.github/e2e-matrix.json, .github/workflows/conformance.yaml
=> chore: use dynamic matrix

.github/dependabot.yml
Configure dependabot to work with composite actions.
=> fix: configure dependabot to work with composite actions

.github/actions/run-tests/action.yaml, .github/e2e-matrix.json, .github/workflows/conformance.yaml
Split conformance jobs per folder.
=> chore: split conformance jobs per folder

.github/actions/publish-image/action.yaml, .github/actions/run-tests/action.yaml, .github/workflows/codecov.yaml, .github/workflows/conformance.yaml, .github/workflows/load-testing.yml, .github/workflows/nancy.yaml, .github/workflows/report-on-vulnerabilities.yaml, .github/workflows/scorecard.yaml
Update upload/download artifact actions.
=> chore: update upload/download artifact actions

api/kyverno/v1/match_resources_types.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clusterpolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, config/crds/kyverno/kyverno.io_clusterpolicies.yaml, config/crds/kyverno/kyverno.io_policies.yaml, config/install-latest-testing.yaml
=> feat: add openapi validation around any/all

api/kyverno/v1/common_types.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_cleanuppolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clustercleanuppolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clusterpolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, config/crds/kyverno/kyverno.io_cleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clustercleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clusterpolicies.yaml, config/crds/kyverno/kyverno.io_policies.yaml, config/install-latest-testing.yaml
Add context entry openapi validation.
=> feat: add context entry openapi validation

api/kyverno/v1/common_types.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_cleanuppolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clustercleanuppolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clusterpolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, config/crds/kyverno/kyverno.io_cleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clustercleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clusterpolicies.yaml, config/crds/kyverno/kyverno.io_policies.yaml, config/install-latest-testing.yaml
Context entry name should be required.
=> fix: context entry name should be required

api/kyverno/v1/resource_description_types.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_cleanuppolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clustercleanuppolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clusterpolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policyexceptions.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policyexceptions.yaml, config/crds/kyverno/kyverno.io_cleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clustercleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clusterpolicies.yaml, config/crds/kyverno/kyverno.io_policies.yaml, config/crds/kyverno/kyverno.io_policyexceptions.yaml, config/install-latest-testing.yaml
Add resource description openapi validation.
=> feat: add resource description openapi validation

.github/workflows/conformance.yaml
Refactor conformance workflow.
=> chore: refactor conformance workflow

api/kyverno/v2beta1/match_resources_types.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_cleanuppolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clustercleanuppolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clusterpolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policyexceptions.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policyexceptions.yaml, config/crds/kyverno/kyverno.io_cleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clustercleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clusterpolicies.yaml, config/crds/kyverno/kyverno.io_policies.yaml, config/crds/kyverno/kyverno.io_policyexceptions.yaml, config/install-latest-testing.yaml
More openapi validation in v2 api.
=> feat: more openapi validation in v2 api

test/conformance/chainsaw/reports/admission/test-report-properties/chainsaw-step-01-apply-1.yaml
fix: use failureAction in reports properties chainsaw test
=> fix: use failureAction in reports properties chainsaw test

api/kyverno/v1/common_types.go, api/kyverno/v1/image_verification_types.go, api/kyverno/v1/spec_types.go, api/kyverno/v2beta1/image_verification_types.go
Remove remaining yaml markers.
=> feat: remove remaining yaml markers

api/kyverno/v1/rule_types.go, api/kyverno/v1/zz_generated.deepcopy.go, api/kyverno/v2beta1/rule_types.go, api/kyverno/v2beta1/zz_generated.deepcopy.go, pkg/webhooks/resource/utils.go
Fix unsupported defaults in api.
=> fix: unsupported defaults in api

charts/kyverno/README.md, charts/kyverno/templates/tests/admission-controller-liveness.yaml, charts/kyverno/templates/tests/admission-controller-metrics.yaml, charts/kyverno/templates/tests/admission-controller-readiness.yaml, charts/kyverno/templates/tests/cleanup-controller-liveness.yaml, charts/kyverno/templates/tests/cleanup-controller-metrics.yaml, charts/kyverno/templates/tests/cleanup-controller-readiness.yaml, charts/kyverno/templates/tests/reports-controller-metrics.yaml, charts/kyverno/values.yaml
Helm tests sleep configuration follow up PR.
=> feat: helm tests sleep follow up

test/conformance/chainsaw/generate/clusterpolicy/cornercases/cpol-clone-delete-ownerreferences-across-namespaces-deprecated/policy.yaml, test/conformance/chainsaw/mutate/e2e/variables-in-keys/policy.yaml, test/conformance/chainsaw/reports/admission/test-report-audit-warn/chainsaw-step-01-apply-1.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/emit-warning/policy.yaml
=> fix: chainsaw tests

api/kyverno/v1/common_types.go
=> fix: remove yaml markers from api

.github/workflows/report-on-vulnerabilities.yaml
=> chore: fix trivy action version

pkg/controllers/webhook/controller.go
We need to get the policy to update it to ensure we have the latest version. We do that in fact but twice. Once in the webhook controller and the second in the update status utility function.
=> fix(status): don't get the policy twice before status update

CONTRIBUTORS.md
Adding myself to the contributor list
PR Links:
- https://github.com/kyverno/kyverno/pull/10868
- https://github.com/kyverno/kyverno/pull/10832
- https://github.com/kyverno/kyverno/pull/10741
- https://github.com/kyverno/kyverno/pull/6757
- https://github.com/kyverno/kyverno/pull/5121
- https://github.com/kyverno/kyverno/pull/4671
Issue discussions:
- https://github.com/kyverno/kyverno/issues/10826
- https://github.com/kyverno/kyverno/issues/9870
- https://github.com/kyverno/kyverno/issues/6521
- https://github.com/kyverno/kyverno/issues/4421
Slack discussions:
- https://kubernetes.slack.com/archives/C032MM2CH7X/p1724670833512849
- https://kubernetes.slack.com/archives/C032MM2CH7X/p1724143042142609
- https://kubernetes.slack.com/archives/C032MM2CH7X/p1723529741579559
- …
=> Adding myself as contributor

.github/workflows/conformance.yaml
Add missing versions in actions refs.
=> chore: add missing versions in actions refs

.github/actions/run-tests/action.yaml, .github/workflows/conformance.yaml
=> chore: verify chainsaw with cosign

api/kyverno/v1/rule_types.go, api/kyverno/v1/zz_generated.deepcopy.go, pkg/controllers/webhook/controller_test.go, pkg/metrics/parsers.go, pkg/policy/generate.go, pkg/utils/fuzz/policy_spec.go, pkg/validation/policy/actions.go, pkg/validation/policy/validate.go
Use pointer in rule.
Part of #11047
=> feat: use pointer in rule (generate field)

api/kyverno/v1/rule_types.go, api/kyverno/v2/cleanup_policy_types.go, api/kyverno/v2beta1/cleanup_policy_types.go, api/kyverno/v2beta1/rule_types.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_cleanuppolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clustercleanuppolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clusterpolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, config/crds/kyverno/kyverno.io_cleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clustercleanuppolicies.yaml, config/crds/kyverno/kyverno.io_clusterpolicies.yaml, config/crds/kyverno/kyverno.io_policies.yaml, config/install-latest-testing.yaml
Make match field required in rule API.
=> fix: make match field required in rule API

CONTRIBUTORS.md
This PR adds my name, Anudeep Nalla, to the Kyverno contributors list as part of my contributions to the Kyverno project.
Changes made:
- Added my name to the CONTRIBUTORS.md file.
1. Cleanup rs with timebound
https://github.com/kyverno/policies/pull/1027
2. Added policy to deny resources in specified window.
https://github.com/kyverno/policies/pull/1032
3. Added policy for require-run-as-containeruser for windows pods.
https://github.com/kyverno/policies/pull/1024
4. Add policy Ensure HPA for Deployments
https://github.com/kyverno/policies/pull/1080
5.  Prevent duplicate HPA
https://github.com/kyverno/policies/pull/1081
=> added Anudeep to CONTRIBUTORS.md

sonar-project.properties
=> chore: fix sonar exclusions

api/kyverno/v1/rule_types.go, api/kyverno/v1/zz_generated.deepcopy.go, api/kyverno/v2beta1/rule_types.go, api/kyverno/v2beta1/zz_generated.deepcopy.go, pkg/autogen/autogen.go, pkg/autogen/rule.go, pkg/controllers/webhook/controller_test.go, pkg/controllers/webhook/utils_test.go, pkg/engine/mutate/mutation.go, pkg/engine/mutate/mutation_test.go, pkg/metrics/parsers.go, pkg/policycache/cache_test.go, pkg/utils/fuzz/policy_spec.go, pkg/validation/policy/actions.go, pkg/validation/policy/validate.go, pkg/validation/policy/validate_test.go
Use pointer in rule (mutation field).
Part of #11047
=> feat: use pointer in rule (mutation field)

test/fuzz/oss_fuzz_build.sh
The OSS-Fuzz build currently breaks. This PR fixes that so OSS-Fuzz can build and run the fuzzers.
=> fix broken oss-fuzz build

.github/workflows/release.yaml, .goreleaser.yml
=> fix: go releaser config

ADOPTERS.md, CONTRIBUTORS.md, MAINTAINERS.md
Move MAINTAINERS.md and CONTRIBUTORS.md to the [community repo](https://github.com/kyverno/community).
=> move governance

pkg/controllers/webhook/controller_test.go, pkg/controllers/webhook/utils.go, pkg/controllers/webhook/utils_test.go, test/conformance/chainsaw/webhooks/pod-all-subresources/webhooks.yaml
Cherry-pick #10748 
In this PR I have fixed the bug mentioned here
https://github.com/kyverno/kyverno/issues/10684
#10748 
N/A
=> fix: range through all resources to build webhook

.github/dependabot.yml
Update dependabot gomod config.
=> chore: update dependabot gomod config

charts/kyverno/templates/hooks/pre-delete-configmap.yaml
Cherry-pick https://github.com/kyverno/kyverno/pull/10685.
=> fix(helm): remove namespace from RoleBinding/roleRef field (cherry-pick #10685)

pkg/controllers/webhook/controller.go
=> fix(webhook): error variable

pkg/controllers/webhook/controller.go
fix(webhook): error variable (cherry-pick #11225)
=> fix(webhook): error variable (cherry-pick #11225)

pkg/controllers/webhook/controller.go
Fix webhooks reconciliation when no policies.
=> fix: webhooks reconciliation when no policies

pkg/config/types.go, pkg/controllers/webhook/controller.go, pkg/controllers/webhook/utils.go
Fix webhooks reconciliation with policies.
=> fix: webhooks reconciliation with policies

charts/kyverno/README.md, charts/kyverno/templates/_helpers.tpl, charts/kyverno/templates/admission-controller/deployment.yaml, charts/kyverno/values.yaml, cmd/kyverno/main.go, config/install-latest-testing.yaml, pkg/toggle/context.go, pkg/toggle/toggle.go, pkg/webhooks/resource/mutation/mutation.go
This PR adds the flag `--dumpPatches` to dump the mutated patches. By default, it is set to `false`.
Closes #10912 
1. Set the `--dumpPatches` flag to true in the admission controller.
2. Create the following policy:
```
metadata:
name: add-labels
spec:
admission: true
rules:
- match:
any:
- resources:
kinds:
- Pod
- Service
- ConfigMap
- Secret
mutate:
metadata:
labels:
foo: bar
name: add-labels
```
2. Create the following secret:
```
apiVersion: v1
data:
foo: YmFy
kind: Secret
metadata:
name: testingsecret
type: Opaque
```
3. Check the logs:
```
2024-09-25T13:36:28+03:00 INF …
```
=> feat: add dumpPatch flag

pkg/autogen/rule.go
Fix policy status updates not stabilising.
=> fix: policy status updates not stabilising

cmd/kyverno/main.go, pkg/breaker/resource_counter.go
move breaker resource counter to pkg
=> fix(refactor): move breaker resource counter to pkg

.github/workflows/conformance.yaml
chore(deps): bump kyverno/action-install-chainsaw from 0.2.10 to 0.2.11 (cherry-pick #11289)
=> chore(deps): bump kyverno/action-install-chainsaw from 0.2.10 to 0.2.11 (cherry-pick #11289)

test/conformance/chainsaw/reports/background/mutate-existing/chainsaw-test.yaml, test/conformance/chainsaw/reports/background/mutate-existing/permissions.yaml
=> fix: add permission for mutate existing report test

pkg/autogen/autogen_test.go, pkg/config/metricsconfig_test.go, pkg/config/types_test.go, pkg/controllers/ttl/controller.go, pkg/controllers/ttl/controller_test.go
=> chore: use ptr package

.github/workflows/devcontainer-build.yaml, .github/workflows/images-build.yaml, .github/workflows/images-publish.yaml, .github/workflows/release.yaml, .github/workflows/report-on-vulnerabilities.yaml
=> fix: use aws mirror of trivy db to fix rate limiter issue (#11342)

pkg/policycache/cache.go
This is an attempt to solve a performance issue in Kyverno 1.13. `checkValidationFailureActionOverrides` unnecessarily computes autogen rules as well as DeepCopies the Policy to create a new filtered one. We don't need to DeepCopy as we don't modify the Policy later on.
=> feat(cache): use shallow copy instead of deep copy

pkg/policycache/cache.go
=> feat(cache): use shallow copy instead of deep copy (cherry-pick #11378)

pkg/registryclient/authn.go
mcr.microsoft.com is a public registry and does not require credentials to login, output received from mcr during authentication using azure keychain can cause failure. This PR removes mcr.microsoft.com from azure keychain
Closes: #11479 
=> feat: skip azure keychain based login for mcr registry

test/conformance/chainsaw/sigstore-custom-tuf/sigstore-image-verification-test/pod.yaml
Use digest instead of tag for custom-sigstore-tuf conformance test
=> fix: use digest instead of tag for custom-sigstore-tuf conformance test

api/kyverno/v2beta1/spec_types.go, api/kyverno/v2beta1/zz_generated.deepcopy.go, charts/kyverno/Chart.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clusterpolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, config/crds/kyverno/kyverno.io_clusterpolicies.yaml, config/crds/kyverno/kyverno.io_policies.yaml, config/install-latest-testing.yaml, docs/user/crd/index.html, docs/user/crd/kyverno.v2beta1.html, pkg/client/applyconfigurations/kyverno/v2beta1/spec.go
This PR adds the `spec.emitWarning` field in Kyverno policies v2beta1.
N/A
=> fix: add emitWarning field in v2beta1

cmd/cli/kubectl-kyverno/policy/load.go
This PR supports v1 of VAPs in the CLI
Closes #11495 
/kind bug
=> fix: support VAP stable version v1 in the CLI

pkg/autogen/v1/autogen.go, pkg/autogen/v1/rule.go, test/conformance/chainsaw/autogen/cel-preconditions/README.md, test/conformance/chainsaw/autogen/cel-preconditions/chainsaw-test.yaml, test/conformance/chainsaw/autogen/cel-preconditions/check-autogen.yaml, test/conformance/chainsaw/autogen/cel-preconditions/policy.yaml
This PR adds celPreconditions in the autogen rules
Closes #11421 
/milestone 1.13.1
/kind bug
1. Create the following policy:
```
metadata:
name: disallow-privilege-escalation
spec:
rules:
- name: privilege-escalation
match:
any:
- resources:
kinds:
- Pod
celPreconditions:
- name: "Only for prod"  
expression: "has(object.metadata.labels) && has(object.metadata.labels.prod) && object.metadata.labels.prod == 'true'"
validate:
cel:
expressions:
- expression: >- 
object.spec.containers.all(container, has(container.securityContext) &&
has(container.securityContext.allowPrivilegeEscalation) &&
container.securityContext.allowPrivilegeEscalation == false)
message: >- …
```
=> fix: add celPreconditions in autogen rules

pkg/engine/handlers/validation/utils.go, pkg/engine/handlers/validation/validate_resource.go
* fix: update match logic for old object validation
* fix: linter
* fix: failing test due to user info
* fix: debug logs
---------
Cherry pick #11427
=> fix: update match logic for old object validation (#11427)

pkg/validation/policy/validate.go, test/conformance/chainsaw/webhook-configurations/match-conditions-fail/README.md, test/conformance/chainsaw/webhook-configurations/match-conditions-fail/chainsaw-test.yaml, test/conformance/chainsaw/webhook-configurations/match-conditions-fail/policy.yaml
* fix(validate): custom match conditions errors
* test(webhook): failing match conditions
---------
=> fix(validate): custom match conditions errors (cherry-pick #11461)

pkg/autogen/autogen.go, pkg/autogen/rule.go, test/conformance/chainsaw/autogen/cel-preconditions/README.md, test/conformance/chainsaw/autogen/cel-preconditions/chainsaw-test.yaml, test/conformance/chainsaw/autogen/cel-preconditions/check-autogen.yaml, test/conformance/chainsaw/autogen/cel-preconditions/policy.yaml
Cherry-picked fix: add celPreconditions in autogen rules (#11503)
=> fix: add celPreconditions in autogen rules (cherry-pick #11503)

pkg/engine/image_verify_test.go, pkg/engine/internal/imageverifier.go
fix: remove logic that uses annotation to skip image verification (cherry-pick #11529)
=> fix: remove logic that uses annotation to skip image verification (cherry-pick #11529)

pkg/validation/policy/generate.go
Closes https://github.com/kyverno/kyverno/issues/11540.
=> fix: add 'immutable fields' back in the policy validation msg for FluxCD

pkg/config/client.go
When we set the UserAgent used by client-go, it is easy to spot calls made by kyverno to the API server by scanning for the user agent we inserted in the http header.
We already do this in registryclient too, so extending the same to client-go.
https://github.com/kyverno/kyverno/blob/07f5a60fa31f0dc0fbc549c6250a13813fc257e2/pkg/registryclient/client.go#L44C2-L44C11
/kind cleanup
=> Set the UserAgent in client-go based calls to kube-apiserver

pkg/engine/handlers/validation/validate_resource.go
add a check for nil rule response
Part of #11491
=> fix: add a check for nil rule response

pkg/background/generate/controller.go, pkg/background/mutate/mutate.go, pkg/utils/report/new.go
Since mutate existing and generate also generate a bgscan report for the resource, it is better to user a generate name to avoid conflics
Closes: #11561
=> fix: use generate name for background scan reports

charts/kyverno/Chart.yaml, charts/kyverno/templates/validate.yaml
This PR uses `clusterephemeralreports`/`ephemeralreports` instead of `clusterbackgroundscanreports`/`backgroundscanreports`.
Closes #11589 
/milestone 1.13.2
/kind bug
=> fix: use ephemeralreportsfor reports controller in helm

.github/workflows/conformance.yaml
=> fix(ci): run conformance upgrade on schedule

pkg/controllers/cleanup/controller.go
Use deleteOptions in cleanup controller.
=> fix: use deleteOptions in cleanup controller

api/kyverno/v1/common_types.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_clusterpolicies.yaml, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_policies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_clusterpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_policies.yaml, config/crds/kyverno/kyverno.io_clusterpolicies.yaml, config/crds/kyverno/kyverno.io_policies.yaml, config/install-latest-testing.yaml, docs/crd/v1/index.html, docs/user/crd/index.html, docs/user/crd/kyverno.v1.html
This PR fixes incorrect links in the documentation related to Kustomize configurations. The changes ensure that the links correctly point to the updated folder structure, improving the accuracy and usability of the documentation.
This PR does not resolve a specific GitHub issue but addresses inaccuracies found in the documentation.
Not applicable.
Not applicable, as this PR does not introduce new features or behavior.
The following changes have been made:
- Fixed the link `kustomize/patchesjson6902` → `kustomize/kustomization/patchesjson6902`.
- Fixed the link `kustomize/patchesstrategicmerge` → `kustomize/kustomization/patchesstrategicmerge`.
These changes are purely documentation fixes to ensure the links are correct and aligned with the current folder structure.
Not …
=> Fix(doc): correct invalid links in documentation

test/conformance/chainsaw/validate/clusterpolicy/standard/apicalls/default/chainsaw-test.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/apicalls/default/ns-bad.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/apicalls/default/pod-bad.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/apicalls/default/pod.yaml, test/conformance/chainsaw/validate/clusterpolicy/standard/apicalls/default/policy.yaml
=> fix: api call chainsaw tests

charts/kyverno-policies/Chart.yaml
=> fix(readme): add changelog for spec.validate[*].allowExistingViolations field in kyverno chart

charts/kyverno-policies/README.md, charts/kyverno-policies/templates/baseline/disallow-capabilities.yaml, charts/kyverno-policies/templates/baseline/disallow-host-namespaces.yaml, charts/kyverno-policies/templates/baseline/disallow-host-path.yaml, charts/kyverno-policies/templates/baseline/disallow-host-ports.yaml, charts/kyverno-policies/templates/baseline/disallow-host-process.yaml, charts/kyverno-policies/templates/baseline/disallow-privileged-containers.yaml, charts/kyverno-policies/templates/baseline/disallow-proc-mount.yaml, charts/kyverno-policies/templates/baseline/disallow-selinux.yaml, charts/kyverno-policies/templates/baseline/restrict-apparmor-profiles.yaml, charts/kyverno-policies/templates/baseline/restrict-seccomp.yaml, charts/kyverno-policies/templates/baseline/restrict-sysctls.yaml, charts/kyverno-policies/templates/other/require-non-root-groups.yaml, charts/kyverno-policies/templates/restricted/disallow-capabilities-strict.yaml, charts/kyverno-policies/templates/restricted/disallow-privilege-escalation.yaml, charts/kyverno-policies/templates/restricted/require-run-as-non-root-user.yaml, charts/kyverno-policies/templates/restricted/require-run-as-nonroot.yaml, charts/kyverno-policies/templates/restricted/restrict-seccomp-strict.yaml, charts/kyverno-policies/templates/restricted/restrict-volume-types.yaml, charts/kyverno-policies/values.yaml
Until now it was not possible to set the allowExistingViolations for predefined policies in the policies chart. By default it should be set to , identical to how it is set up in the CRDs. Not only does this now allow users to set the config according to their needs, but this also solves a problem with ArgoCD. As the CRDs set it to true, but the template does not specifically declare the field, ArgoCD falls into a constant sync loop of trying to remove the field.
cherry pick #11656
=> add allowExistingViolations option in policy chart (cherry pick #11656)

.github/workflows/conformance.yaml
Custom Sigstore tests are failing on 24.01
=> fix: update custom sigstore conformance tests to fix issues with ubuntu 24.01 runner

pkg/engine/handlers/validation/validate_pss.go
In the current code logic, `convertChecks` is executed before applying pod security exceptions, which causes the `CheckResult.ErrList` to be modified, leading to bug when applying the pod security exceptions.
Closes #11729 
/kind bug
=> fix: exemption error caused by convertChecks function

.github/workflows/conformance.yaml
=> fix: update custom sigstore conformance tests to fix issues with ubuntu 24.01 runner (cherry-pick #11772)

.github/workflows/helm-release.yaml, .github/workflows/helm-test.yaml
Bump Python to fix [failure](https://github.com/kyverno/kyverno/actions/runs/12428623463/job/34700578346?pr=11776) in https://github.com/kyverno/kyverno/pull/11776.
=> chore: bump python to 3.13.1

pkg/policy/generate.go
=> Fix panic in background controller when updating Generate rule

.github/workflows/conformance.yaml, Makefile, test/conformance/chainsaw/.chainsaw.yaml
=> fix: increase chainsaw apply timeout to 30s

cmd/cli/kubectl-kyverno/fix/test.go, test/cli/test-mutate/add-default-resources/kyverno-test.yaml, test/cli/test-mutate/global-anchor/kyverno-test.yaml, test/cli/test/mutate-keda-scaled-object/kyverno-test.yaml
Fix sorting in fix test command.
=> fix: sorting in fix test command

Makefile, charts/kyverno/README.md, charts/kyverno/charts/crds/README.md, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_validatingpolicies.yaml, charts/kyverno/charts/crds/values.yaml, charts/kyverno/values.yaml, config/install-latest-testing.yaml
Add validating policy crd in helm chart.
Fixes https://github.com/kyverno/kyverno/issues/11872
=> feat: add validating policy crd in helm chart

pkg/utils/yaml/loadpolicy.go
=> refactor: get policy helper

pkg/cel/libs/context/impl.go, pkg/cel/libs/context/lib.go, pkg/cel/libs/context/types.go
Add context cel lib to get config map.
#11896
=> feat: add context cel lib to get config map

pkg/cel/policy/compiler.go
Add CEL variables support.
https://github.com/kyverno/kyverno/issues/11907
=> feat: add CEL variables support

pkg/cel/resource/openapi.go, pkg/cel/resource/openapi_test.go
Init object type checking based on OpenAPI v3 Schema
#11908
Add the milestone label by commenting `/milestone 1.2.3`.
/milestone 1.14.0
=> Implement Object type checking based on OpenAPI v3 schema

cmd/cli/kubectl-kyverno/commands/apply/command.go
=> refactor: cleanup cli apply functions

.github/ISSUE_TEMPLATE/bug-cli.yaml, .github/ISSUE_TEMPLATE/bug-other.yaml, .github/ISSUE_TEMPLATE/bug-webhook.yaml
Add 1.13.1 and 1.13.2 to issue templates.
=> chore: add 1.13.1 and 1.13.2 to issue templates

Makefile, cmd/cli/kubectl-kyverno/apis/v1alpha1/test_result.go, cmd/cli/kubectl-kyverno/commands/test/output.go, cmd/cli/kubectl-kyverno/config/crds/cli.kyverno.io_tests.yaml, cmd/cli/kubectl-kyverno/data/crds/cli.kyverno.io_tests.yaml, cmd/cli/kubectl-kyverno/fix/test.go, cmd/cli/kubectl-kyverno/test/load_test.go, docs/user/cli/crd/index.html, docs/user/cli/crd/kyverno_kubectl.v1alpha1.html, test/cli/test-mutate/mutate-existing/kyverno-test.yaml
Fix cli schema generation.
https://github.com/kyverno/kyverno/issues/11957
=> fix: cli schema generation

cmd/cli/kubectl-kyverno/commands/apply/command.go, pkg/cel/engine/engine.go, pkg/cel/engine/provider.go, pkg/cel/policy/compiler.go, pkg/cel/policy/policy.go, pkg/engine/api/policy.go
Add validating policy engine api wrapper.
=> feat: add validating policy engine api wrapper

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/commands/apply/table.go, cmd/cli/kubectl-kyverno/commands/test/output.go, cmd/cli/kubectl-kyverno/processor/policy_processor.go, cmd/cli/kubectl-kyverno/report/report.go, pkg/controllers/report/background/controller.go, pkg/controllers/report/utils/events.go, pkg/engine/api/policy.go, pkg/event/events.go, pkg/utils/report/metadata.go, pkg/utils/report/results.go, pkg/utils/report/selector.go, pkg/webhooks/resource/handlers.go, pkg/webhooks/resource/utils.go, pkg/webhooks/utils/block.go, pkg/webhooks/utils/error.go, pkg/webhooks/utils/warning.go
Reduce generic policy interface.
=> refactor: reduce generic policy interface

pkg/cel/engine/engine.go, pkg/cel/libs/context/impl.go, pkg/cel/libs/context/impl_test.go, pkg/cel/libs/context/lib.go, pkg/cel/libs/context/lib_test.go, pkg/cel/libs/context/types.go, pkg/cel/policy/policy.go
Implement cel context lib correctly.
=> fix: implement cel context lib correctly

pkg/cel/libs/context/impl.go, pkg/cel/libs/context/impl_test.go, pkg/cel/libs/context/lib.go, pkg/cel/libs/context/types.go
Add support for more context elements.
=> feat: add support for more context elements

cmd/cli/kubectl-kyverno/commands/apply/command_test.go, test/cli/test-validating-policy/check-deployments-replica/deployment1.yaml, test/cli/test-validating-policy/check-deployments-replica/deployment2.yaml, test/cli/test-validating-policy/check-deployments-replica/policy.yaml, test/cli/test-validating-policy/disallow-host-path/pod1.yaml, test/cli/test-validating-policy/disallow-host-path/pod2.yaml, test/cli/test-validating-policy/disallow-host-path/policy.yaml
=> test: add more cli vp tests

pkg/cel/autogen/autogen.go, pkg/cel/autogen/autogen_test.go, pkg/cel/autogen/rule.go, pkg/cel/autogen/rule_test.go
This PR adds an autogen package for ValidatingPolicies. All functionalities are covered by unit tests.
Related to #11968
=> feat: add autogen package for ValidatingPolicies

pkg/cel/policy/compiler.go, pkg/cel/policy/compiler_test.go
Register cel context lib in compiler.
=> feat: register cel context lib

pkg/config/config.go, pkg/controllers/webhook/validatingpolicy.go, pkg/controllers/webhook/validatingpolicy_test.go, pkg/webhooks/server.go
Add validating policy webhook handler.
=> feat: add validating policy webhook handler

test/cli/test-validating-admission-policy/check-deployment-labels/policy.yaml, test/cli/test-validating-admission-policy/check-deployments-replica/policy.yaml, test/cli/test-validating-policy/check-deployment-labels/policy.yaml, test/cli/test-validating-policy/check-deployments-replica/policy.yaml
=> fix: test typo

cmd/internal/config.go, cmd/internal/setup.go
Add rest config support in setup code.
=> feat: add rest config support in setup code

pkg/cel/engine/provider.go
=> fix: don't sort cel policies

pkg/cel/engine/engine.go, pkg/cel/matching/matcher.go
=> feat: use admission attributes

pkg/cel/libs/context/lib.go, pkg/cel/libs/context/types.go
Cel lib get config map return type.
=> fix: cel lib get config map return type

pkg/cel/engine/engine.go, pkg/cel/policy/policy.go
Use more admission attributes.
=> feat: use more admission attributes

pkg/cel/engine/engine.go, pkg/webhooks/server.go
Support admission review in cel engine.
=> feat: support admission review in cel engine

pkg/cel/engine/criteria.go, pkg/cel/engine/engine.go, pkg/webhooks/server.go
Process cel engine response in webhook handler.
=> feat: process cel engine response in webhook handler

pkg/admissionpolicy/matcher.go
This PR checks if the oldObject matches against the object selector for VAPs in the CLI.
Thanks to @eddycharly for catching this bug!
=> fix: match the old object against the object selector for VAPs in the CLI

.github/workflows/conformance.yaml
=> fix: remove 1.27 and 1.28 from tests

pkg/cel/engine/engine.go, pkg/cel/policy/policy.go
Add admission request cel variable.
=> feat: add admission request cel variable

pkg/cel/policy/compiler.go, pkg/cel/policy/policy.go
Add message expression support to validating policies.
=> feat: add message expression support to validating policies

cmd/kyverno/main.go, pkg/cel/libs/context/impl.go, pkg/cel/libs/context/lib.go, pkg/cel/policy/compiler.go, pkg/webhooks/server.go, test/conformance/chainsaw/validating-policies/context/configmap/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/context/configmap/configmap.yaml, test/conformance/chainsaw/validating-policies/context/configmap/negative.yaml, test/conformance/chainsaw/validating-policies/context/configmap/policy.yaml, test/conformance/chainsaw/validating-policies/context/configmap/positive.yaml
Add context provider in admission handling.
=> feat: add context provider in admission handling

pkg/cel/policy/policy.go, test/conformance/chainsaw/validating-policies/context/configmap/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/match-conditions/failure-policy/default/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/match-conditions/failure-policy/default/deployment.yaml, test/conformance/chainsaw/validating-policies/match-conditions/failure-policy/default/policy.yaml, test/conformance/chainsaw/validating-policies/match-conditions/failure-policy/fail/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/match-conditions/failure-policy/fail/deployment.yaml, test/conformance/chainsaw/validating-policies/match-conditions/failure-policy/fail/policy.yaml, test/conformance/chainsaw/validating-policies/match-conditions/failure-policy/ignore/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/match-conditions/failure-policy/ignore/deployment.yaml, test/conformance/chainsaw/validating-policies/match-conditions/failure-policy/ignore/policy.yaml, test/conformance/chainsaw/validating-policies/validation-rules/reject/chainsaw-test.yaml
Implement match conditions failure policy (with chainsaw tests)
=> feat: implement match conditions failure policy

api/kyverno/v2alpha1/spec_types.go, charts/kyverno/charts/crds/templates/kyverno.io/kyverno.io_validatingpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/kyverno.io_validatingpolicies.yaml, config/crds/kyverno/kyverno.io_validatingpolicies.yaml, config/install-latest-testing.yaml, docs/user/crd/index.html, docs/user/crd/kyverno.v2alpha1.html, pkg/cel/engine/engine.go, pkg/cel/engine/provider.go, pkg/webhooks/server.go, test/conformance/chainsaw/validating-policies/validation-actions/audit/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/validation-actions/audit/deployment.yaml, test/conformance/chainsaw/validating-policies/validation-actions/audit/policy.yaml, test/conformance/chainsaw/validating-policies/validation-actions/deny/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/validation-actions/deny/deployment.yaml, test/conformance/chainsaw/validating-policies/validation-actions/deny/policy.yaml, test/conformance/chainsaw/validating-policies/validation-actions/none/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/validation-actions/none/deployment.yaml, test/conformance/chainsaw/validating-policies/validation-actions/none/policy.yaml, test/conformance/chainsaw/validating-policies/validation-actions/warn/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/validation-actions/warn/deployment.yaml, test/conformance/chainsaw/validating-policies/validation-actions/warn/policy.yaml
=> feat: consider validation actions (Deny)

test/conformance/chainsaw/validating-policies/context/image-data/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/context/image-data/deployment.yaml, test/conformance/chainsaw/validating-policies/context/image-data/policy.yaml
Add chainsaw test for image data loading.
=> tests: add chainsaw test for image data loading

cmd/internal/flag.go
=> fix(flag): lookup kubeconfig only after parsing

pkg/webhooks/resource/vpol/handler.go
Consider Warn validation action in VP handler.
=> feat: consider Warn validation action

cmd/internal/flag.go, cmd/kyverno/main.go, pkg/webhooks/resource/vpol/handler.go
Add reporting to validating admission handler.
=> feat: add reporting to validating admission handler

charts/kyverno/templates/reports-controller/clusterrole.yaml, cmd/reports-controller/main.go, config/install-latest-testing.yaml, pkg/controllers/report/aggregate/controller.go, pkg/controllers/report/aggregate/controller_test.go, pkg/controllers/report/aggregate/utils.go, pkg/engine/api/policy.go, pkg/utils/report/results.go, pkg/utils/report/source.go, test/conformance/chainsaw/validating-policies/report/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/report/deployment.yaml, test/conformance/chainsaw/validating-policies/report/policy.yaml, test/conformance/chainsaw/validating-policies/report/report.yaml
Add validating policies to reports aggregation.
=> feat: add validating policies to reports aggregation

.github/workflows/conformance.yaml
Make validating policies e2e tests required.
=> chore: make validating policies e2e tests required

charts/kyverno/README.md, charts/kyverno/values.yaml, config/install-latest-testing.yaml
=> replace ghcr.io to reg.kyverno.io (cherry-pick #12031)

pkg/controllers/webhook/validatingpolicy.go
=> feat: add autogen pod controllers to webhooks

charts/kyverno/templates/admission-controller/clusterrole.yaml, cmd/kyverno/main.go, config/install-latest-testing.yaml, pkg/cel/engine/provider.go, pkg/cel/policy/compiler.go, pkg/cel/policy/compiler_test.go, pkg/cel/policy/policy.go, test/conformance/chainsaw/cel-policy-exceptions/exclude-deployments/bad-deployment.yaml, test/conformance/chainsaw/cel-policy-exceptions/exclude-deployments/chainsaw-test.yaml, test/conformance/chainsaw/cel-policy-exceptions/exclude-deployments/exception.yaml, test/conformance/chainsaw/cel-policy-exceptions/exclude-deployments/ns.yaml, test/conformance/chainsaw/cel-policy-exceptions/exclude-deployments/policy.yaml, test/conformance/chainsaw/cel-policy-exceptions/exclude-deployments/skipped-deployment.yaml
=> feat: compile and evaluate polex's match conditions

charts/kyverno/README.md, charts/kyverno/values.yaml, config/install-latest-testing.yaml
=> Revert "replace ghcr.io to reg.kyverno.io (cherry-pick #12031)"

pkg/cel/autogen/autogen.go, test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-cronjobs/README.md, test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-cronjobs/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-cronjobs/check-autogen.yaml, test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-cronjobs/policy.yaml, test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-statefulsets/README.md, test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-statefulsets/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-statefulsets/check-autogen.yaml, test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-statefulsets/policy.yaml, test/conformance/chainsaw/validating-policies/autogen/none/README.md, test/conformance/chainsaw/validating-policies/autogen/none/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/autogen/none/check-autogen.yaml, test/conformance/chainsaw/validating-policies/autogen/none/policy.yaml, test/conformance/chainsaw/validating-policies/autogen/should-autogen/README.md, test/conformance/chainsaw/validating-policies/autogen/should-autogen/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/autogen/should-autogen/check-autogen.yaml, test/conformance/chainsaw/validating-policies/autogen/should-autogen/policy.yaml, test/conformance/chainsaw/validating-policies/autogen/should-not-autogen/README.md, test/conformance/chainsaw/validating-policies/autogen/should-not-autogen/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/autogen/should-not-autogen/check-autogen.yaml, test/conformance/chainsaw/validating-policies/autogen/should-not-autogen/policy.yaml
This PR adds CEL Autogen Tests
=> feat: add cel-autogen chainsaw tests

pkg/cel/autogen/autogen.go, test/conformance/chainsaw/validating-policies/autogen/should-autogen/check-autogen.yaml
This is to fix the flaky tests by sorting resources list.
=> fix: sort autogen resources list

docs/user/crd/kyverno.v1.html, docs/user/crd/kyverno.v2.html, docs/user/crd/kyverno.v2beta1.html
=> fix: codegen

.github/workflows/conformance.yaml, test/conformance/chainsaw/cel-policy-exceptions/exclude-deployments/chainsaw-test.yaml, test/conformance/chainsaw/cel-policy-exceptions/exclude-deployments/exception.yaml, test/conformance/chainsaw/cel-policy-exceptions/exclude-deployments/ns.yaml, test/conformance/chainsaw/cel-policy-exceptions/exclude-deployments/skipped-deployment.yaml
This PR fixes a flake chainsaw test related to cel exceptions.
=> fix: modify celexception flake test

pkg/cel/resource/openapi.go, pkg/cel/resource/openapi_test.go
=> chore: add cel unit tests

codecov.yml
Add codecov config and exclude api generated files.
=> chore: add codecov config and exclude api generated files

api/policies.kyverno.io/v1alpha1/imageverification_policy_spec_types.go, config/crds/policies.kyverno.io/policies.kyverno.io_imageverificationpolicies.yaml, docs/user/crd/index.html, pkg/imageverification/evaluator/compiler.go, pkg/imageverification/evaluator/eval.go, pkg/imageverification/evaluator/eval_test.go, pkg/imageverification/imagedataloader/utils.go, pkg/imageverification/imageverifierfunctions/impl.go, pkg/imageverification/imageverifierfunctions/utils.go
This PR adds tests for images verification on any JSON payload
=> feat(test): image verification on any payload

test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/with-cel-exception/chainsaw-test.yaml
=> fix chainsaw test

api/policies.kyverno.io/v1alpha1/imageverification_policy_types_test.go
=> chore: add unit tests

pkg/cel/autogen/autogen.go, pkg/cel/autogen/autogen_test.go, pkg/cel/autogen/rule.go, pkg/cel/autogen/rule_test.go, pkg/controllers/webhook/validatingpolicy.go
=> fix: autogen refactor

api/policies.kyverno.io/v1alpha1/imageverification_policy_spec_types_test.go
=> chore: add policy API unit tests

pkg/imageverification/evaluator/compiler.go
=> Add CEL HTTP Lib to the imageverification compiler

pkg/imageverification/evaluator/compiler.go
=> Add CEL context.Lib to the imageverification compiler

pkg/cel/libs/http/http.go, pkg/cel/policy/compiler.go, pkg/cel/policy/policy.go
=> fix: providing the http provider in the compiler

CONTRIBUTING.md, DEVELOPMENT.md
Minor grammatical fixes in Contributing and Development docs
=> Minor fixes in Contributing and Development docs

cmd/cli/kubectl-kyverno/apis/v1alpha1/context.go, cmd/cli/kubectl-kyverno/config/crds/cli.kyverno.io_contexts.yaml, cmd/cli/kubectl-kyverno/data/crds/cli.kyverno.io_contexts.yaml, docs/user/cli/crd/index.html, docs/user/cli/crd/kyverno_kubectl.v1alpha1.html, pkg/cel/policy/context.go, pkg/cel/policy/fake_context.go
Mock list resources in context.
=> feat: mock list resources in context

pkg/imageverification/evaluator/compiler.go
=> fix: add missing context type and http type in ivpols

pkg/cel/policy/policy.go
=> Fix: data access in audit annotations

pkg/cel/engine/imageverifyengine.go, pkg/cel/engine/imageverifyengine_test.go, pkg/cel/env.go, pkg/cel/libs/context/impl.go, pkg/cel/libs/context/impl_test.go, pkg/cel/libs/context/lib.go, pkg/cel/libs/context/mock.go, pkg/cel/libs/context/types.go, pkg/cel/libs/image/lib.go, pkg/cel/libs/image/lib_test.go, pkg/cel/libs/image/types.go, pkg/cel/policy/context.go, pkg/cel/policy/fake_context.go, pkg/cel/policy/utils.go, pkg/imageverification/imagedataloader/loader.go, test/conformance/chainsaw/validating-policies/context/imagereference/bad-deployment.yaml, test/conformance/chainsaw/validating-policies/context/imagereference/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/context/imagereference/deployment.yaml, test/conformance/chainsaw/validating-policies/context/imagereference/policy.yaml
Adds parse image func as a global func
Adds Chainsaw tests for image parsing
=> fix: image parse func and add chainsaw tests

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/commands/test/test.go, pkg/cel/engine/vpolengine.go, pkg/controllers/report/utils/scanner.go
=> feat: add user info in cel engine

pkg/cel/libs/user/impl.go, pkg/cel/libs/user/impl_test.go, pkg/cel/libs/user/lib.go, pkg/cel/libs/user/types.go, pkg/cel/policy/compiler.go, pkg/imageverification/evaluator/compiler.go
=> feat: add cel user lib

pkg/engine/variables/operator/allin.go, pkg/engine/variables/operator/anyin.go, pkg/engine/wildcards/wildcards.go, pkg/validation/policy/validate.go
make function comment match function name
=> chore: make function comment match function name

pkg/cel/libs/resource/impl.go, pkg/cel/libs/resource/impl_test.go, pkg/cel/libs/resource/mock.go, pkg/cel/libs/resource/types.go, pkg/cel/policy/context.go, pkg/cel/policy/fake_context.go
=> feat: simplify resource cel lib

pkg/controllers/report/utils/scanner.go
=> fix: check if response includes a policy for ivpol

pkg/controllers/report/utils/scanner.go
=> fix: set correct policy for ivpols

pkg/controllers/report/utils/scanner.go
=> fix: engine response for ivpol background scanning

pkg/cel/libs/imageverify/impl.go, pkg/cel/libs/imageverify/impl_test.go, pkg/cel/libs/imageverify/lib.go, pkg/cel/libs/imageverify/utils.go, pkg/imageverification/evaluator/compiler.go, pkg/imageverification/evaluator/policy.go
=> chore: move imageverify cel lib

pkg/cel/libs/globalcontext/impl_test.go, pkg/cel/libs/user/impl_test.go, pkg/cel/libs/user/lib.go
=> chore: add some cel lib unit tests

go.mod, go.sum, pkg/pss/evaluate_test.go, pkg/pss/utils/mapping.go
After sync psa to v1.32.3(https://github.com/kyverno/pod-security-admission/tree/release-1.32.3), we need to adopt it in kyverno repository.
Closes #10012 
Closes #12221 
@realshuting 
/milestone 1.14.0
/kind feature
=> feat: adopt psa to v1.32.3

pkg/controllers/webhook/controller.go, test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/check-deployment-labels/chainsaw-test.yaml, test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/check-deployment-labels/policy-assert.yaml
Closes https://github.com/kyverno/kyverno/issues/12275.
=> chore: skip webhook registration if vap is generated

docs/user/crd/kyverno.v1.html, docs/user/crd/kyverno.v2.html, docs/user/crd/kyverno.v2beta1.html, go.mod, go.sum
Closes https://github.com/kyverno/kyverno/issues/12501.
=> fix CVE: bump `golang-jwt/jwt/v4`

cmd/cli/kubectl-kyverno/processor/policy_processor.go
Use correct resource in cli processor.
=> fix: use correct resource in cli processor

pkg/controllers/report/utils/scanner.go, pkg/event/events.go
https://github.com/kyverno/kyverno/issues/12749
/milestone 1.14.0
=> Apply PolicyException on Background Scanning for ivpol and vpol

test/conformance/chainsaw/imagevalidatingpolicies/report/with-exception/bad-deployment.yaml, test/conformance/chainsaw/imagevalidatingpolicies/report/with-exception/chainsaw-test.yaml, test/conformance/chainsaw/imagevalidatingpolicies/report/with-exception/exception.yaml, test/conformance/chainsaw/imagevalidatingpolicies/report/with-exception/fail-report-assert.yaml, test/conformance/chainsaw/imagevalidatingpolicies/report/with-exception/policy-assert.yaml, test/conformance/chainsaw/imagevalidatingpolicies/report/with-exception/policy.yaml, test/conformance/chainsaw/imagevalidatingpolicies/report/with-exception/skipped-deployment.yaml, test/conformance/chainsaw/imagevalidatingpolicies/report/with-exception/skipped-report-assert.yaml, test/conformance/chainsaw/validating-policies/report/with-exception/bad-deployment.yaml, test/conformance/chainsaw/validating-policies/report/with-exception/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/report/with-exception/exception.yaml, test/conformance/chainsaw/validating-policies/report/with-exception/fail-report-assert.yaml, test/conformance/chainsaw/validating-policies/report/with-exception/policy-assert.yaml, test/conformance/chainsaw/validating-policies/report/with-exception/policy.yaml, test/conformance/chainsaw/validating-policies/report/with-exception/skipped-deployment.yaml, test/conformance/chainsaw/validating-policies/report/with-exception/skipped-report-assert.yaml
This PR evaluates celexceptions with vpols and ivpols in the reports.
Closes #12749 
=> chore: add chainsaw tests for exceptions in the reports

api/policies.kyverno.io/v1alpha1/validating_policy.go, charts/kyverno/charts/crds/templates/policies.kyverno.io/policies.kyverno.io_validatingpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/policies.kyverno.io_validatingpolicies.yaml, config/crds/policies.kyverno.io/policies.kyverno.io_validatingpolicies.yaml, config/install-latest-testing.yaml, pkg/admissionpolicy/builder.go, test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/missing-action/chainsaw-test.yaml, test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/missing-action/policy-assert.yaml, test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/missing-action/policy.yaml, test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/missing-action/validatingadmissionpolicy.yaml, test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/missing-action/validatingadmissionpolicybinding.yaml, test/conformance/chainsaw/generate-validating-admission-policy/validatingpolicy/missing-action/validatingwebhookconfiguration.yaml, test/conformance/chainsaw/validating-policies/validation-checks/invalid-action/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/validation-checks/invalid-action/policy.yaml
1. Restrict the `validationActions` field to be one of the valid values: `Deny`, `Audit`, and `Warn`.
2. Use the default value while generating VAPs in case the field is unset.
Closes #12683 
=> fix: add default value for actions in VPOLs

pkg/cel/libs/imagedata/impl.go, pkg/cel/libs/imagedata/impl_test.go, pkg/cel/libs/imagedata/lib.go, pkg/cel/policy/compiler.go, test/conformance/chainsaw/image-validating-policies/context/imagedata/image-data-arch/policy.yaml, test/conformance/chainsaw/image-validating-policies/context/imagedata/image-data/policy.yaml, test/conformance/chainsaw/validating-policies/context/image-data-arch/policy.yaml, test/conformance/chainsaw/validating-policies/context/image-data/policy.yaml
https://github.com/kyverno/kyverno/issues/12704.
=> chore: rename `imagedata.Get` to `image.GetMetadata`

Makefile, api/policies.kyverno.io/v1alpha1/imagevalidating_policy.go, api/policies.kyverno.io/v1alpha1/policy_status.go, docs/user/config-api.yaml, docs/user/crd/index.html, docs/user/crd/kyverno_cel_policies.v1alpha1.html
Fix missing docs for new policy types.
=> fix: missing docs for new policy types

pkg/cel/utils/convert.go, pkg/cel/utils/convert_test.go
=> chore: add cel/utils unit tests

pkg/cel/compiler/compiler.go, pkg/cel/compiler/compiler_test.go
Add `cel/compiler` unit tests.
=> chore: add cel/compiler unit tests

pkg/cel/libs/fake_context_test.go
=> chore: add fake context unit tests

pkg/cel/matching/criteria_test.go, pkg/cel/matching/matcher.go, pkg/cel/matching/matcher_test.go
Fix object matching in cel/matching package.
=> fix: object matching in cel/matching package

pkg/cel/autogen/match_test.go, pkg/cel/engine/exception.go, pkg/cel/engine/exception_test.go, pkg/cel/engine/request_test.go, pkg/cel/policies/ivpol/engine/reconciler.go, pkg/cel/policies/vpol/engine/reconciler.go
=> chore: add cel/engine unit tests

Makefile
Remove gopath shim from makefile.
=> chore: remove gopath shim from makefile

codecov.yml
Add a couple folders to codecov ignore config.
=> chore: add folders to codecov ignore config

api/kyverno/v1/spec_types.go, pkg/background/generate/controller.go, pkg/background/mutate/mutate.go, pkg/policy/generate.go, pkg/policy/policy_controller.go, pkg/utils/engine/labels.go, pkg/utils/engine/labels_test.go, pkg/webhooks/resource/generation/handler.go, pkg/webhooks/resource/handlers.go, pkg/webhooks/resource/imageverification/handler.go, pkg/webhooks/resource/mutation/mutation.go, pkg/webhooks/resource/updaterequest.go, pkg/webhooks/resource/validation/validation.go
Cherry Pick https://github.com/kyverno/kyverno/pull/12744 commitID: 3ff923 into release1.13 branch
Resolved merge conflicts
Cherry-pick of: https://github.com/kyverno/kyverno/pull/12744
Merged to main with commit: 3ff923b7756e1681daf73849954bd88516589194 on 14th April
=> Cherry pick of #12744 CommitID:3ff923 to release 1.13

.github/ISSUE_TEMPLATE/bug-cli.yaml, .github/ISSUE_TEMPLATE/bug-other.yaml, .github/ISSUE_TEMPLATE/bug-webhook.yaml
This PR adds release 1.14 to the bug templates.
=> chore: add 1.14.0 to the bug templates

pkg/cel/matching/matcher.go, pkg/cel/matching/predicates/namespace/matcher.go, pkg/cel/matching/predicates/namespace/matcher_test.go
Rewrite `cel/matching` package with upstream code.
=> fix: rewrite cel/matching package with upstream code

pkg/cel/libs/http/http.go, pkg/cel/libs/http/impl.go, pkg/cel/libs/http/impl_test.go, pkg/cel/libs/http/lib.go, pkg/cel/libs/http/types.go, pkg/cel/policies/vpol/compiler/compiler.go, pkg/cel/policies/vpol/compiler/policy.go, pkg/imageverification/evaluator/compiler.go
=> refactor: cel http lib

pkg/cel/compiler/compiler.go, pkg/cel/compiler/keys.go, pkg/imageverification/evaluator/compiler.go, pkg/imageverification/evaluator/policy.go
=> refactor: centralize CEL keys

cmd/cli/kubectl-kyverno/processor/policy_processor.go, cmd/cli/kubectl-kyverno/processor/utils.go, pkg/admissionpolicy/validate.go, pkg/controllers/report/utils/scanner.go
This PR converts gvk to gvr for VAPs in the CLI.
=> fix: convert gvk to gvr for VAPs in the CLI

pkg/cel/compiler/compiler.go, pkg/cel/matching/image_test.go
Check output type of image reference match expression.
=> fix: check output type of image reference match expression

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/commands/test/test.go, cmd/cli/kubectl-kyverno/processor/policy_processor.go, cmd/cli/kubectl-kyverno/processor/utils.go, pkg/utils/restmapper/restmapper.go
This PR makes use of `GetRESTMapper()`.
=> chore: use GetRESTMapper()

.github/workflows/clean-stale-branches.yaml
=> cherry pick

pkg/cel/policies/vpol/compiler/compiler.go
Don't register custom libs when compiling match conditions.
=> fix: don't register custom libs when compiling match conditions

pkg/cel/libs/image/impl.go, pkg/cel/libs/image/lib.go, pkg/cel/libs/image/lib_test.go, pkg/cel/libs/image/types.go
=> refactor: simplify image lib

test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-cronjobs/policy.yaml, test/conformance/chainsaw/validating-policies/autogen/autogen-deployments-statefulsets/policy.yaml, test/conformance/chainsaw/validating-policies/autogen/none/policy.yaml, test/conformance/chainsaw/validating-policies/autogen/should-autogen/policy.yaml, test/conformance/chainsaw/validating-policies/autogen/should-not-autogen/policy.yaml, test/conformance/chainsaw/validating-policies/validation-checks/invalid-action/policy.yaml, test/conformance/chainsaw/validating-policies/validation-rules/with-match-conditions/policy.yaml, test/conformance/chainsaw/validating-policies/webhook-configuration/match-conditions/policy.yaml, test/conformance/chainsaw/validating-policies/webhook-configuration/match-conditions/webhooks.yaml
=> chore: fix names in tests

pkg/cel/libs/globalcontext/impl.go, pkg/cel/libs/globalcontext/impl_test.go, pkg/cel/libs/globalcontext/lib.go
Add globalContext lib overload.
=> feat: add globalContext lib overload

pkg/cel/libs/image/types.go, pkg/cel/libs/image/types_test.go
Fix cel image lib and add unit tests.
=> fix: cel image lib and add unit tests

pkg/cel/libs/imagedata/impl.go, pkg/cel/libs/imagedata/impl_test.go
Add missing tests in cel imagedata lib.
=> chore: add missing tests in cel imagedata lib

cmd/cli/kubectl-kyverno/utils/common/fetch.go
This PR removes unused function in the CLI
=> chore: remove unused function in CLI

cmd/cli/kubectl-kyverno/utils/common/common.go, cmd/cli/kubectl-kyverno/utils/common/fetch.go
=> refactor: use resource fetcher in the CLI

ADOPTERS.md
This PR aims to add Finastra as an adopter of Kyverno.
@JimBugwadia 
=> Update ADOPTERS.md with Finastra

pkg/cel/libs/globalcontext/impl_test.go, pkg/cel/libs/globalcontext/mock.go, pkg/cel/libs/imagedata/impl_test.go, pkg/cel/libs/imagedata/mock.go, pkg/cel/libs/resource/impl_test.go, pkg/cel/libs/resource/mock.go, pkg/cel/policies/ivpol/engine/engine_test.go
=> refactor: cel libs mocks

pkg/cel/policies/vpol/compiler/compiler.go, pkg/imageverification/evaluator/compiler.go
Proper error handling in cel policy engines.
=> fix: proper error handling in cel policy engines

cmd/cli/kubectl-kyverno/utils/common/fetch.go
=> chore: remove unused function in CLI (cherry-pick #13053)

pkg/cel/libs/http/impl.go, pkg/cel/libs/http/lib.go
=> chore: remove println statements

cmd/cli/kubectl-kyverno/utils/common/common.go, cmd/cli/kubectl-kyverno/utils/common/fetch.go
=> refactor: use resource fetcher in the CLI (Cherry-pick #13054)

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/utils/common/fetch.go, test/conformance/chainsaw/cli/apply/apply-vaps-in-cluster-mode/chainsaw-test.yaml, test/conformance/chainsaw/cli/apply/apply-vaps-in-cluster-mode/deployment1.yaml, test/conformance/chainsaw/cli/apply/apply-vaps-in-cluster-mode/deployment2.yaml, test/conformance/chainsaw/cli/apply/apply-vaps-in-cluster-mode/policy.yaml, test/conformance/chainsaw/cli/apply/apply-vps-in-cluster-mode/chainsaw-test.yaml, test/conformance/chainsaw/cli/apply/apply-vps-in-cluster-mode/deployment1.yaml, test/conformance/chainsaw/cli/apply/apply-vps-in-cluster-mode/deployment2.yaml, test/conformance/chainsaw/cli/apply/apply-vps-in-cluster-mode/policy.yaml
This PR fixes the issue related to applying VPs in cluster mode.
Chainsaw tests are added for both VPs and VAPs.
Closes #12940
=> fix: apply VPs in cluster mode in the CLI

pkg/cel/libs/globalcontext/impl_test.go, pkg/cel/libs/image/lib_test.go, pkg/cel/libs/imagedata/impl_test.go, pkg/cel/libs/imagedata/lib_test.go, pkg/cel/libs/resource/lib_test.go, pkg/cel/libs/user/impl_test.go
Improve cel libs unit tests env creation.
=> chore: improve cel libs unit tests env creation

pkg/cel/libs/http/impl.go, pkg/cel/libs/http/impl_test.go, pkg/cel/libs/resource/impl.go, pkg/cel/utils/function.go
Add missing unit tests in http lib.
=> chore: add missing unit tests in http lib

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/utils/common/fetch.go, test/conformance/chainsaw/cli/apply/apply-vaps-in-cluster-mode/chainsaw-test.yaml, test/conformance/chainsaw/cli/apply/apply-vaps-in-cluster-mode/deployment1.yaml, test/conformance/chainsaw/cli/apply/apply-vaps-in-cluster-mode/deployment2.yaml, test/conformance/chainsaw/cli/apply/apply-vaps-in-cluster-mode/policy.yaml, test/conformance/chainsaw/cli/apply/apply-vps-in-cluster-mode/chainsaw-test.yaml, test/conformance/chainsaw/cli/apply/apply-vps-in-cluster-mode/deployment1.yaml, test/conformance/chainsaw/cli/apply/apply-vps-in-cluster-mode/deployment2.yaml, test/conformance/chainsaw/cli/apply/apply-vps-in-cluster-mode/policy.yaml
=> fix: apply VPs in cluster mode in the CLI (cherry-pick #13084)

pkg/controllers/webhook/controller.go
=> chore: fix typo

cmd/cli/kubectl-kyverno/utils/common/fetch.go, test/conformance/chainsaw/cli/apply/apply-ivps-in-cluster-mode-with-polex/chainsaw-test.yaml, test/conformance/chainsaw/cli/apply/apply-ivps-in-cluster-mode-with-polex/exception.yaml, test/conformance/chainsaw/cli/apply/apply-ivps-in-cluster-mode-with-polex/policy.yaml, test/conformance/chainsaw/cli/apply/apply-ivps-in-cluster-mode-with-polex/resources.yaml, test/conformance/chainsaw/cli/apply/apply-ivps-in-cluster-mode/bad-pod.yaml, test/conformance/chainsaw/cli/apply/apply-ivps-in-cluster-mode/chainsaw-test.yaml, test/conformance/chainsaw/cli/apply/apply-ivps-in-cluster-mode/good-pod.yaml, test/conformance/chainsaw/cli/apply/apply-ivps-in-cluster-mode/policy.yaml
This PR fixes the issue related to applying ImageValidatingPolicies in cluster mode. Two chainsaw tests are added.
=> fix: apply IVPs in cluster mode in the CLI

pkg/cel/policies/ivpol/engine/provider.go, pkg/cel/policies/ivpol/engine/reconciler.go, test/conformance/chainsaw/image-validating-policies/context/globalreference/chainsaw-test.yaml
Fix missing infos in ivpol autogen.
=> fix: missing infos in ivpol autogen

pkg/admissionpolicy/utils.go
> 2025-01-21T10:57:45Z ERR github.com/kyverno/kyverno/cmd/kyverno/main.go:344 > ValidatingAdmissionPolicies isn't supported in the API server error="the server could not find the requested resource" logger=setup
v1beta1 `ValidatingAdmissionPolicy` and `ValidatingAdmissionPolicyBinding` was deprecated since v1.31.
=> check vap and vapd with v1 version

.github/workflows/verify-codegen.yaml, charts/kyverno-policies/README.md, charts/kyverno-policies/values.yaml
This pr fixes the link for kyverno policy chart values types.
Fixes issue #13144 
- [ x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [ x] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.
- [ x] This is a bug fix and I have added unit tests that prove my fix is effective.
=> Fix the link of Kyverno policy chart types 

pkg/cel/libs/context.go, pkg/cel/libs/fake_context.go, pkg/cel/libs/generator/impl.go, pkg/cel/libs/generator/impl_test.go, pkg/cel/libs/generator/lib.go, pkg/cel/libs/generator/lib_test.go, pkg/cel/libs/generator/mock.go, pkg/cel/libs/generator/types.go
=> feat: add a new CEL custom function to generate resources

pkg/cel/compiler/compiler.go, pkg/cel/compiler/compiler_test.go, pkg/cel/compiler/keys.go, pkg/cel/policies/gpol/compiler/compiler.go, pkg/cel/policies/gpol/compiler/policy.go
This PR adds a compiler for generating policies.
Related to https://github.com/kyverno/kyverno/issues/11638
=> feat: compile generatingpolicies

cmd/kyverno/main.go, pkg/imageverification/evaluator/validate.go, pkg/policy/generate.go, pkg/utils/admission/celexception_test.go, pkg/utils/admission/cleanup_test.go, pkg/utils/admission/exception_test.go, pkg/utils/admission/globalcontext_test.go, pkg/utils/admission/metadata_test.go, pkg/utils/admission/policy_test.go
This PR removes the redundant imported modules and some error checks that don't exist.
=> chore: remove redundant imported modules

api/policies.kyverno.io/v1alpha1/generating_policy.go, charts/kyverno/charts/crds/templates/policies.kyverno.io/policies.kyverno.io_generatingpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/policies.kyverno.io_generatingpolicies.yaml, config/crds/policies.kyverno.io/policies.kyverno.io_generatingpolicies.yaml, config/install-latest-testing.yaml, pkg/cel/policies/gpol/validate.go, pkg/controllers/webhook/controller.go, pkg/utils/admission/policy.go, pkg/webhooks/policy/handlers.go, test/conformance/chainsaw/generating-policies/validate/invalid-cel-expression/chainsaw-test.yaml, test/conformance/chainsaw/generating-policies/validate/invalid-cel-expression/policy.yaml, test/conformance/chainsaw/generating-policies/validate/missing-generate/chainsaw-test.yaml, test/conformance/chainsaw/generating-policies/validate/missing-generate/policy.yaml, test/conformance/chainsaw/generating-policies/validate/missing-match-constraints/chainsaw-test.yaml, test/conformance/chainsaw/generating-policies/validate/missing-match-constraints/policy.yaml
This PR adds validation webhook for GeneratingPolicies.
=> feat: add GeneratingPolicy validation webhook

pkg/cel/policies/vpol/validate.go, test/conformance/chainsaw/validating-policies/validation-checks/missing-match-constraints/chainsaw-test.yaml, test/conformance/chainsaw/validating-policies/validation-checks/missing-match-constraints/policy.yaml
This PR addresses a server crash that occurred when an invalid VP is created.
Closes #13189
=> fix: server crashes when an invalid VP is created

charts/kyverno/README.md, charts/kyverno/templates/admission-controller/clusterrole.yaml, charts/kyverno/templates/admission-controller/deployment.yaml, charts/kyverno/values.yaml, cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/internal/client.go, cmd/internal/flag.go, cmd/internal/setup.go, config/install-latest-testing.yaml, pkg/clients/dclient/client.go, pkg/clients/dclient/discovery.go
Cherry-pick https://github.com/kyverno/kyverno/pull/13141.
=> feat: add dynamic CRD watcher using informer (Cherry pick 13141)

.github/workflows/conformance.yaml, test/conformance/chainsaw/policy-exceptions-disabled/image-validating-policies/bad-pod.yaml, test/conformance/chainsaw/policy-exceptions-disabled/image-validating-policies/chainsaw-test.yaml, test/conformance/chainsaw/policy-exceptions-disabled/image-validating-policies/exception.yaml, test/conformance/chainsaw/policy-exceptions-disabled/image-validating-policies/good-pod.yaml, test/conformance/chainsaw/policy-exceptions-disabled/image-validating-policies/policy.yaml, test/conformance/chainsaw/policy-exceptions-disabled/validating-policies/bad-deployment.yaml, test/conformance/chainsaw/policy-exceptions-disabled/validating-policies/chainsaw-test.yaml, test/conformance/chainsaw/policy-exceptions-disabled/validating-policies/exception.yaml, test/conformance/chainsaw/policy-exceptions-disabled/validating-policies/good-deployment.yaml, test/conformance/chainsaw/policy-exceptions-disabled/validating-policies/policy.yaml
chore: Add tests for validating and imagevalidating policies with policy exception disabled (cherry-pick #13171)
=> chore: Add tests for validating and imagevalidating policies with policy exception disabled (cherry-pick #13171)

api/policies.kyverno.io/v1alpha1/imagevalidating_policy.go, charts/kyverno/charts/crds/templates/policies.kyverno.io/policies.kyverno.io_imagevalidatingpolicies.yaml, cmd/cli/kubectl-kyverno/data/crds/policies.kyverno.io_imagevalidatingpolicies.yaml, config/crds/policies.kyverno.io/policies.kyverno.io_imagevalidatingpolicies.yaml, config/install-latest-testing.yaml
=> feat: improve ivpol attestor api

pkg/cel/policies/gpol/engine/fetch.go, pkg/cel/policies/gpol/engine/policy.go, pkg/cel/policies/gpol/engine/provider.go
This PR adds a provider to GPOLs.
=> feat: add GPOL provider

.github/workflows/conformance.yaml
chore: shard vpol chainsaw tests (cherry-pick #13253)
=> chore: shard vpol chainsaw tests (cherry-pick #13253)

pkg/config/config.go, pkg/webhooks/server.go
=> fix: remove the duplicate webhook registeration for gpol

.github/workflows/conformance.yaml
chore: shard vpol chainsaw tests (cherry-pick #13261)
=> chore: shard vpol chainsaw tests (cherry-pick #13261)

pkg/background/gpol/controller.go, pkg/cel/libs/context.go, pkg/cel/libs/fake_context.go, pkg/cel/policies/gpol/compiler/policy.go, pkg/cel/policies/gpol/engine/engine.go, pkg/cel/policies/gpol/engine/response.go
This PR adds engine response for the GPOLs.
=> feat: add engine response for GPOLs

pkg/cel/policies/dpol/engine/engine.go
=> chore: remove unused types

charts/kyverno/templates/reports-controller/clusterrole.yaml, cmd/reports-controller/main.go, config/install-latest-testing.yaml, pkg/background/gpol/controller.go, pkg/background/update_request_controller.go, pkg/cel/policies/gpol/engine/engine.go, pkg/controllers/report/aggregate/controller.go, pkg/controllers/report/aggregate/controller_test.go, pkg/controllers/report/aggregate/utils.go, pkg/utils/report/metadata.go, pkg/utils/report/results.go, pkg/utils/report/source.go, test/conformance/chainsaw/generating-policies/reports/generate-cm/chainsaw-test.yaml, test/conformance/chainsaw/generating-policies/reports/generate-cm/namespace.yaml, test/conformance/chainsaw/generating-policies/reports/generate-cm/permissions.yaml, test/conformance/chainsaw/generating-policies/reports/generate-cm/policy.yaml, test/conformance/chainsaw/generating-policies/reports/generate-cm/report-assert.yaml, test/conformance/chainsaw/generating-policies/reports/generate-secrets/chainsaw-test.yaml, test/conformance/chainsaw/generating-policies/reports/generate-secrets/namespace.yaml, test/conformance/chainsaw/generating-policies/reports/generate-secrets/permissions.yaml, test/conformance/chainsaw/generating-policies/reports/generate-secrets/policy.yaml, test/conformance/chainsaw/generating-policies/reports/generate-secrets/report-assert.yaml, test/conformance/chainsaw/generating-policies/reports/generate-secrets/source.yaml
This PR generates reports for GPOLs. Chainsaw tests are added.
=> feat: generate reports for GPOLs

Makefile, charts/kyverno/README.md, charts/kyverno/charts/crds/README.md, charts/kyverno/charts/crds/templates/reports.kyverno.io/reports.kyverno.io_clusterephemeralreports.yaml, charts/kyverno/charts/crds/templates/reports.kyverno.io/reports.kyverno.io_ephemeralreports.yaml, charts/kyverno/charts/crds/templates/wgpolicyk8s.io/wgpolicyk8s.io_clusterpolicyreports.yaml, charts/kyverno/charts/crds/templates/wgpolicyk8s.io/wgpolicyk8s.io_policyreports.yaml, charts/kyverno/charts/crds/values.yaml, charts/kyverno/templates/reports-controller/deployment.yaml, charts/kyverno/templates/validate.yaml, charts/kyverno/values.yaml
=> Cherry Pick #13361

.github/workflows/lint.yaml, .golangci.yml, cmd/cli/kubectl-kyverno/processor/policy_processor.go, pkg/engine/utils/match.go, pkg/imageverification/imagedataloader/context.go, pkg/webhooks/resource/mutation/mutation.go
=> chore: bump linter

.github/workflows/conformance.yaml
Fix required conformance jobs.
=> chore: fix required conformance jobs

charts/kyverno/README.md, charts/kyverno/templates/admission-controller/deployment.yaml, charts/kyverno/templates/background-controller/deployment.yaml, charts/kyverno/templates/cleanup-controller/deployment.yaml, charts/kyverno/templates/hooks/post-delete-configmap.yaml, charts/kyverno/templates/hooks/post-upgrade-clean-reports.yaml, charts/kyverno/templates/hooks/post-upgrade-migrate-resources.yaml, charts/kyverno/templates/hooks/pre-delete-scale-to-zero.yaml, charts/kyverno/templates/reports-controller/deployment.yaml, charts/kyverno/templates/tests/admission-controller-liveness.yaml, charts/kyverno/templates/tests/admission-controller-metrics.yaml, charts/kyverno/templates/tests/admission-controller-readiness.yaml, charts/kyverno/templates/tests/cleanup-controller-liveness.yaml, charts/kyverno/templates/tests/cleanup-controller-metrics.yaml, charts/kyverno/templates/tests/cleanup-controller-readiness.yaml, charts/kyverno/templates/tests/reports-controller-metrics.yaml, charts/kyverno/values.yaml
according to security best practices, Kubernetes automatically mounts ServiceAccount credentials in each Pod. The ServiceAccount may be assigned roles allowing Pods to access API resources. Blocking this ability is an extension of the least privilege best practice and should be followed if Pods do not need to speak to the API server to function.
I have added a feature to the kyverno chart to be able to turn off auto mounting and add a projected volume on a perServiceAccount basis, i have left the default to true to ensure backwards compatibility. setting to false with also add the projected volume needed for the controller to function
#13041
=> feat(chart): add ability to disable automount of service account token

charts/kyverno/README.md, charts/kyverno/templates/_helpers.tpl, charts/kyverno/templates/admission-controller/deployment.yaml, charts/kyverno/values.yaml, cmd/kyverno/main.go, config/install-latest-testing.yaml
Add support for configuring controller runtime bind address.
Closes #13220
=> feat: add support for configuring controller runtime bind address

ADOPTERS.md
Appended the adopters list with Kubermatic Kubernetes Platform.
No related issue.
=> Adding Kubermatic to Kyverno adopters list

cmd/cli/kubectl-kyverno/processor/policy_processor.go, cmd/cli/kubectl-kyverno/utils/common/fetch.go, test/conformance/chainsaw/cli/apply/apply-gpols-in-cluster-mode-with-context/chainsaw-test.yaml, test/conformance/chainsaw/cli/apply/apply-gpols-in-cluster-mode-with-context/context.yaml, test/conformance/chainsaw/cli/apply/apply-gpols-in-cluster-mode-with-context/policy.yaml, test/conformance/chainsaw/cli/apply/apply-gpols-in-cluster-mode/chainsaw-test.yaml, test/conformance/chainsaw/cli/apply/apply-gpols-in-cluster-mode/policy.yaml
This PR applies GPOLs in cluster mode for the CLI `apply` command.
=> feat: apply GPOLs in cluster mode in CLI

test/conformance/chainsaw/generating-policies/foreach/data/data-generate-nps/chainsaw-test.yaml, test/conformance/chainsaw/generating-policies/foreach/data/data-generate-nps/downstream-assert.yaml, test/conformance/chainsaw/generating-policies/foreach/data/data-generate-nps/downstream-error.yaml, test/conformance/chainsaw/generating-policies/foreach/data/data-generate-nps/namespaces.yaml, test/conformance/chainsaw/generating-policies/foreach/data/data-generate-nps/policy-assert.yaml, test/conformance/chainsaw/generating-policies/foreach/data/data-generate-nps/policy.yaml
This PR adds a new chainsaw test for GPOLs.
=> chore(gpol): add chainsaw tests

cmd/cli/kubectl-kyverno/commands/apply/command.go, cmd/cli/kubectl-kyverno/processor/policy_processor.go, pkg/utils/restmapper/restmapper.go
This PR caches the namespace fetched for each resourceNamespace in policy processor and uses memcacheClient instead of discovery client with restmapper.NewDiscoveryRESTMapper() when fetching restmapper for apiGroupResources. This fix alone optimized the `kyverno apply` command for large number of resources (more than 1000s) from 15mins to 1-5 seconds.
Related issue: #12973
/kind bug
=> fix: optimized namespace fetching in policy processor and restmapper client

.github/workflows/helm-test.yaml, Makefile, charts/kyverno/Chart.lock, charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/templates/admission-controller/deployment.yaml, charts/kyverno/templates/reports-controller/clusterrole.yaml, charts/kyverno/templates/reports-controller/deployment.yaml, charts/kyverno/values.yaml, config/install-latest-testing.yaml
Cherry-pick https://github.com/kyverno/kyverno/pull/13524.
=> Render Openreports resources in the helm chart and propagate the value to flags (cherry-pick #13524)

pkg/admissionpolicy/builder.go, pkg/controllers/admissionpolicygenerator/generate-map.go, pkg/controllers/admissionpolicygenerator/generate-vap.go, pkg/controllers/admissionpolicygenerator/polex.go, test/conformance/chainsaw/generate-mutating-admission-policy/with-cel-exceptions/chainsaw-test.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-cel-exceptions/exception.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-cel-exceptions/mutatingadmissionpolicy.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-cel-exceptions/mutatingadmissionpolicybinding.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-cel-exceptions/mutatingwebhookconfiguration.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-cel-exceptions/policy-assert.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-cel-exceptions/policy.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-multiple-exceptions/chainsaw-test.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-multiple-exceptions/exception.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-multiple-exceptions/mutatingadmissionpolicy.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-multiple-exceptions/mutatingadmissionpolicybinding.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-multiple-exceptions/mutatingwebhookconfiguration.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-multiple-exceptions/policy-assert.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-multiple-exceptions/policy.yaml
This PR generates MAPs given exceptions
Related to #11637
=> feat: generate maps given cel exceptions

cmd/kyverno/main.go, pkg/webhooks/resource/validation/utils.go, pkg/webhooks/resource/validation/validation.go, pkg/webhooks/resource/vpol/handler.go
use Namespace Lister to improve performance
NSResolver: From 50ms+ to 40µs
Handling Report creation like old policy types in admission requests
=> Improve VPOL performance

scripts/config/kind/vap-v1beta1.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-cel-exceptions/chainsaw-test.yaml, test/conformance/chainsaw/generate-mutating-admission-policy/with-multiple-exceptions/chainsaw-test.yaml
This PR fixes flake chainsaw tests in MAPs.
=> fix: generate map tests

test/conformance/chainsaw/cli/apply/apply-vps-in-cluster-mode-with-context/chainsaw-test.yaml, test/conformance/chainsaw/cli/apply/apply-vps-in-cluster-mode-with-context/configmap.yaml, test/conformance/chainsaw/cli/apply/apply-vps-in-cluster-mode-with-context/pods.yaml, test/conformance/chainsaw/cli/apply/apply-vps-in-cluster-mode-with-context/policy.yaml
This PR adds a chainsaw test for applying validating policies using Kyverno CLI in cluster mode with context.
=> chore: add a chainsaw test

test/conformance/chainsaw/generating-policies/data/nosync/generate-on-eviction-subresource-trigger/chainsaw-test.yaml
=> chore: fix chainsaw test

.github/ISSUE_TEMPLATE/bug-cli.yaml, .github/ISSUE_TEMPLATE/bug-other.yaml, .github/ISSUE_TEMPLATE/bug-webhook.yaml
This PR adds `1.14.2`, `1.14.3`, `1.14.4` and `1.15.0` to the bug templates.
=> chore: update bug templates

Makefile
During the latest release (1.15), the `install.yaml` wasn't generated because the CI failed with the following issue (cf [this workflow](https://github.com/kyverno/kyverno/actions/runs/16641789054/job/47096150383) ):
- fixes #13730 
/1.15.1
/kind bug
=> chore: Fix codegen-manifest-release missing target

pkg/cel/policies/gpol/engine/engine_test.go, pkg/cel/policies/gpol/engine/fetch_test.go
=> add unit-test for gpol: engine package

pkg/cel/policies/gpol/engine/engine_test.go, pkg/cel/policies/gpol/engine/fetch_test.go
=> add unit-test for gpol: engine package (cherry-pick #13736)

api/kyverno/v1/common_types.go, docs/user/crd/index.html, docs/user/crd/kyverno.v1.html
=> cherry pick #13729

pkg/cel/policies/dpol/engine/engine_test.go, pkg/cel/policies/dpol/engine/fetch.go, pkg/cel/policies/dpol/engine/fetch_test.go, pkg/cel/policies/gpol/engine/fetch_test.go, sc.sh
=> test : improve unit test coverage for new policy types

.devcontainer/Dockerfile, go.mod, hack/api-group-resources/go.mod, hack/controller-gen/go.mod
About CVE-2025-47907 (Severity":"HIGH"):
> Cancelling a query (e.g. by cancelling the context passed to one of the query methods) during a call to the Scan method of the returned Rows can result in unexpected results if other queries are being made in parallel. This can result in a race condition that may overwrite the expected results with those of another query, causing the call to Scan to return either unexpected results from the other query or an error.
This vulnerability occurs in go's `stdlib` and was fixed in `1.14.6`, so we need to upgrade.
- fixes https://github.com/kyverno/kyverno/issues/13819
/milestone 1.15.1
/kind bug
In order to test that the vulnerability was fixed I ran the following command:
```shell
$ make ko-build-all …
```
=> fix: CVE-2025-47907

pkg/cel/policies/mpol/compiler/policy_test.go, pkg/cel/policies/mpol/compiler/type_converter_test.go
=> test: add unit test for mpol compiler package

cmd/cli/kubectl-kyverno/commands/apply/command_test.go, cmd/cli/kubectl-kyverno/processor/policy_processor.go, pkg/admissionpolicy/mutate.go, pkg/admissionpolicy/user_info.go, pkg/admissionpolicy/validate.go, pkg/controllers/report/utils/scanner.go, pkg/engine/handlers/validation/validate_cel.go, pkg/engine/internal/auth.go, pkg/engine/internal/match.go, test/cli/test-mutating-admission-policy/check-user-info/kyverno-test.yaml, test/cli/test-mutating-admission-policy/check-user-info/patched-resource.yaml, test/cli/test-mutating-admission-policy/check-user-info/policy.yaml, test/cli/test-mutating-admission-policy/check-user-info/resource.yaml, test/cli/test-mutating-admission-policy/check-user-info/userinfo.yaml, test/cli/test-validating-admission-policy/check-user-info/deployment.yaml, test/cli/test-validating-admission-policy/check-user-info/kyverno-test.yaml, test/cli/test-validating-admission-policy/check-user-info/policy.yaml, test/cli/test-validating-admission-policy/check-user-info/userinfo.yaml
This PR passes the user information to VAPs and MAPs in the CLI.
Closes #13829 
/milestone 1.15.2
/kind bug
Added two tests, one for VAPs and the other for MAPs.
=> fix: pass userInfo to VAPs and MAPs in the CLI

charts/kyverno/Chart.lock, charts/kyverno/Chart.yaml, charts/kyverno/README.md, charts/kyverno/ci/openreports-values.yaml, charts/kyverno/templates/_helpers.tpl, charts/kyverno/templates/reports-controller/deployment.yaml, charts/kyverno/values.yaml
=> Cherry pick #13924

charts/kyverno/README.md, charts/kyverno/values.yaml
Cherry pick of https://github.com/kyverno/kyverno/pull/13933
=> fix: Fix repository for helm hooks (cherry-pick #13933)

charts/kyverno/README.md, charts/kyverno/values.yaml
=> Correct minor typo (Cherry-pick #14033)

ADOPTERS.md
When we were on Kubernetes version 1.24 with all our AWS EKS and Azure AKS clusters, we introduced Kyverno (version 1.9 back then) to replace PSPs. That helped us to unblock the upgrade to K8s 1.25.
The next use cases were already around the corner and today we use Kyverno to enforce a variety of best practices:
* having a PDB
* spread constraint across all AZs
* not using latest tags
* automate some manual CIS Controls (like not using wildcards in ClusterRoles)
* ... (non-complete list)
n/a
n/a
n/a
n/a
n/a
none
=> feat: Add Swiss Post as a Kyverno Adopter

cmd/background-controller/main.go, cmd/cleanup-controller/main.go, cmd/kyverno/main.go, cmd/reports-controller/main.go, pkg/background/generate/controller.go, pkg/background/gpol/generate_controller.go, pkg/background/mpol/processor.go, pkg/background/mpol/processor_test.go, pkg/background/mutate/mutate.go, pkg/background/update_request_controller.go, pkg/controllers/report/utils/scanner.go, pkg/event/controller.go, pkg/event/controller_test.go, pkg/event/events.go, pkg/webhooks/resource/generation/handler.go, pkg/webhooks/resource/handlers.go, pkg/webhooks/resource/imageverification/handler.go, pkg/webhooks/resource/ivpol/handler.go, pkg/webhooks/resource/mpol/handler.go, pkg/webhooks/resource/mutation/mutation.go, pkg/webhooks/resource/updaterequest.go, pkg/webhooks/resource/vpol/handler.go, pkg/webhooks/utils/event.go, test/conformance/chainsaw/image-validating-policies/report/admission/chainsaw-test.yaml, test/conformance/chainsaw/image-validating-policies/report/admission/events-assert.yaml, test/conformance/chainsaw/mutating-policies/reporting/events-violation/chainsaw-test.yaml, test/conformance/chainsaw/mutating-policies/reporting/events-violation/configmap.yaml, test/conformance/chainsaw/mutating-policies/reporting/events-violation/event-assert.yaml, test/conformance/chainsaw/mutating-policies/reporting/events-violation/ns.yaml, test/conformance/chainsaw/mutating-policies/reporting/events-violation/policy.yaml
=> feat: enable events gen for gpol, mpol, ivpol
